### ISSUE TITLE
Proceso: Carga > Visualización

### ISSUE THREAD

**Issue by elsiosanchez** [solop-develop/vue-1.0#10]
Se espera que los campos que no tienen lógica de visualización se muestren siempre que cumplan con las demás condiciones de visualización.

visualizacion, debe respetar el orden de la secuencia, debe manejar logica de visualización, filtrado por el panel con el filter column, para que a criterio del usuario se muestre o se oculten campos

![image](https://user-images.githubusercontent.com/45974454/166769026-8fad403a-b93d-4edf-bf5b-70bae34e139e.png)

**Comment by EdwinBetanc0urt** [comment]
Los casos de uso para esta funcionalidad se pueden ver aquí:
https://solop-develop.github.io/frontend-core/es/guide/use-cases/process.html#visualizacion
