### ISSUE TITLE
Froma: Asignar OC-Recibo-Factura (Match PO-Receipt-Invoice)

### ISSUE THREAD

**Issue by EdwinBetanc0urt** [solop-develop/vue-1.0#1007]
![imagen](https://github.com/solop-develop/adempiere-grpc-server/assets/20288327/39a44121-3f9b-4681-be4e-8dffe56cb569)

#### Tabla desde:
- [x] Listar Asignar Desde.
- [x] Listar Modo de Búsqueda.
- [x] Listar Socios de Negocio (Proveedores).
- [x] Listar Productos.
- [x] Listar resultado desde.

#### Tabla hasta:
- [x] Listar Asignar Desde.
- [x] Listar resultado hasta.

#### Procesar
- [x] Procesar selección.

**Comment by niclopup** [comment]
no le daría prioridad a esta corrección pero no está funcionando ok.

En la grilla de abajo debería definir las Entregas/Recepción pero en vez de ello repite la misma grilla de las Fascturas que están arriba.

![image](https://github.com/solop-develop/frontend-core/assets/31936815/955e2994-b85d-4f44-8af5-ae4fd4a6d476)
