### ISSUE TITLE
Error crear Fase luego de Crear Proyecto

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#1032]
## Bug report

Si se desea crear un Proyecto y luego seguir a crear una FASE, para luego generar una Ordne de Veneta desde la Fase. Todo en una misma acción sin cerrar la ventana. Esto dará error ya que la pestaña de FASE no permite guardar, cuando permite guardar no se permite generar directo la orden desde la fase.

![error Fase en proyecto 1](https://github.com/solop-develop/frontend-core/assets/31936815/8eedb227-ee50-48c0-ba02-8e330e372560)

![Error crear FASE Desde Proyecto](https://github.com/solop-develop/frontend-core/assets/31936815/679b018b-ddce-4df2-80cd-bec4abd51cbc)

![ERror al guarda FASE 3](https://github.com/solop-develop/frontend-core/assets/31936815/671667f4-0eae-43fa-831f-aa888b0e3a80)

#### Steps to reproduce

1. [xxx]
2. [xxx]
3. [xxxx]

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:

**Comment by elsiosanchez** [comment]
Saludos @niclopup  ya este error fue solventado por favor prueba nuevamente


### _**GIF**_

![Peek 2023-06-01 12-09](https://github.com/solop-develop/frontend-core/assets/45974454/5583f66b-510c-4f02-ac24-23476b3b52df)
