### ISSUE TITLE
Mejoras en Búsqueda de Producto en VUE

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#1034]
## Feature request

Se desea poder aplicar los mismos filtros de la misma manera que permite actualmente ZK. 

Búsqueda desde ZK
![Búsqueda ZK 1](https://github.com/solop-develop/frontend-core/assets/31936815/7f5efc12-55e6-4a64-b184-a5cbbd7be778)

![Búsqueda Producto por Proveedor ZK](https://github.com/solop-develop/frontend-core/assets/31936815/55d91465-3369-4631-8829-02f79c0f9d38)

Búsqueda actual VUE

![Búsqueda Producto VUE](https://github.com/solop-develop/frontend-core/assets/31936815/cb4d5960-678a-491c-8bfb-bc25315bdba1)

Podemos definir los campos a filtrar en 2 categorías:

### Campos Editables
Para darle flexibildad a estas formas de búsquedas, lo mejor es que se muestren todos los campos que se definan como "Columna de Selección" en la tabla en cuestión.

Por ejemplo se podrían agregar campos como el siguiente según se desee en cada instancia. 

**Categoría de Producto:** la cateogría de producto es el único DATO OBLIGATORIO que se debe definir en la definición de productos, esto hace que sea el mejor para que aparezca para ser filtrado por. Estas opciones deben aparecer como una Lista desplegable con las categorías existentes. Deifnir el nombre es muy riesgoso ya que se debe aplicar la búsuqeda exacta y no es lo más ágil.

### Campos Fijos

1. **Lista de Precios** (Si no permite Filtrar por Lista de Precio puede dar a error de mostrar un producto que no está en la lista de precios). para hacerlo más fácil el control se puede seguir la misma lógica que aplica ZK actualmente. Por defecto se debería definir la lista de precios que tenga definida el documento desde uno está parado. Cuando se tenga definido una lista de precios, en ZK se agregan las columnas de Precio. Lo ideal sería mantener esta lógica, dejaría sólo el PRECIO en vez de agregar las 3 columnas de los 3 precios. 
2. **Almacén** Idem comportamiento a la lista de precios, se debería definir a partir del almacén definida en el documento en cuestión. Si se tiene definida un almacén, se debería mostrar las columas de inventario tal como lo hace ahora ZK.  
3. **Proveedor:** se debe permitir realzizar la búsqueda por proveedor tal como lo permite actualmete ZK. este filtro busca el proveedor definido en la pestaña Compras de la ventana Producto.

![image](https://github.com/solop-develop/frontend-core/assets/31936815/4827bdc3-23b2-4cdf-aef6-68f12e291504)

### Columnas a mostrar

Las columnas a mostrar deberán ser en base a los campos definidos como filtros.

* Columnas Fijas 
* Columnas de Selección

### Velocidad de selección

Cuando se define un dato en un campo de SDN o Producto y se encuentra un resultado exacto único, actualmente el sistema demora bastante en definir el dato cuando en ZK esto es casi instantaneo

Entiendo que el comportamiento debería ser igual a ZK, separando en los dos escenarios: 

* Existe un Dato único con el texto/nro definido: Se define el Registro automáticamente
* Existe más de un dato con el texto/nro definido: se abre la ventana de búsqueda definiendo dicho dato en código o nombre (no se como se podría definir esto inteligentemente)

**Ejemplo VUE**
![lentitud en selección de registro con búsqueda única](https://github.com/solop-develop/frontend-core/assets/31936815/d61bbbf0-aee4-4bef-bf8c-1db6e7dd0bc6)

**Ejemplo ZK**
![lentitud en selección de registro con búsqueda única EN ZK](https://github.com/solop-develop/frontend-core/assets/31936815/c5efa357-01f8-472b-85c3-d301856affeb)

**Comment by EdwinBetanc0urt** [comment]
Esto fue corregido, ya esta montado en https://vue-develop.solopcloud.com/#/Issues

![image](https://github.com/solop-develop/frontend-core/assets/20288327/2951e4ee-b893-447f-b8dc-38c02e9320e6)

**Comment by EdwinBetanc0urt** [comment]
El alcance o la entrega queda igual a como se trabajaba en legacy, queda pendiente con los cambios solicitados como la lista de precios

**Comment by EdwinBetanc0urt** [comment]
Se quita la funcionalidad de mostrar los campos marcados como `Selección` ahora los campos están directamente en el buscador, agregando `Versión de Lista de Precios`, `Almacén`, y `Proveedor`.

https://github.com/solop-develop/frontend-core/assets/20288327/c83e5c82-d915-46f0-8fac-d42c2275d876

Cabe destacar que en el zk el campo de búsqueda Si-No `Almacenado` es editable solo si se selecciona un almacén, en vue no es dependiente del almacén y se agrega como lista desplegable con opciones `Si`, `No` y `Vacio`.

**Comment by niclopup** [comment]
El  buscador de productos quedó bueno!

pero tiene algunos detalles todavía por resolver para ayudar en la velocidad de la operativa.

Versión de Lista de Precios definida por defecto según lista de precios del documento. Ahora lo está dejando vacío cuando debería definirlo automáticamente.

![image](https://github.com/solop-develop/frontend-core/assets/31936815/13467c74-a9da-4520-b35d-153ec124e94d)


**ZK**

![image](https://github.com/solop-develop/frontend-core/assets/31936815/b20230ad-9a34-4bdc-a4a7-57112c513ed6)


Control de Productos de la Organización

Veo que desde un rol que no tiene acceso a una organización (Agencia S.A.) veo en el buscador de priductos un producto de dicha agencia q no debería de ver ya q no tengo acceso en este rol a dicha organización.

no contola por orgnización

![image](https://github.com/solop-develop/frontend-core/assets/31936815/b57b6d61-4275-433f-afce-74d9c49934da)

**Comment by EdwinBetanc0urt** [comment]
Se agrego el establecer la lista de precio disponible a partir de la version del frontend https://github.com/solop-develop/frontend-core/releases/tag/3.6.1 y del backend https://github.com/solop-develop/adempiere-grpc-server/releases/tag/3.0.5

https://github.com/solop-develop/adempiere-grpc-server/assets/20288327/0a69de5e-3b30-4f7c-8e14-ec47051d12ec

**Comment by niclopup** [comment]
Dentro de este issue se pedian varias cosas:



> ### Campos Editables
> Para darle flexibildad a estas formas de búsquedas, lo mejor es que se muestren todos los campos que se definan como "Columna de Selección" en la tabla en cuestión.
> 
> Por ejemplo se podrían agregar campos como el siguiente según se desee en cada instancia.
> 
> Categoría de Producto: la cateogría de producto es el único DATO OBLIGATORIO que se debe definir en la definición de productos, esto hace que sea el mejor para que aparezca para ser filtrado por. Estas opciones deben aparecer como una Lista desplegable con las categorías existentes. Deifnir el nombre es muy riesgoso ya que se debe aplicar la búsuqeda exacta y no es lo más ágil.



Entiendo según un comentario que agregaron el 3 de Enero que no se aplicará esta opción de campos editables en este buscador. Esto sigue en curso? Es importante poder contar al menos con 2 tipos de buscadores, uno de inventario complejo que si está bueno ver toda la información que se pueda en la búsqueda pero otra que sea más simple que sólo muestre lo que se desea. Hay manera de hacer esto?

Lo ideal es poder editar para poder agregar los campos que se muestren según cada instancia.

Lo que estaría faltando es:

**Poder agregar un campo como Filtro:**
Ej: Categoría de Producto, Grupo, Clase, etc.

**Poder MOstrar o ocultar columnas en la grilla:**
Ej: SKU, EAN, todos los precios, todas las cantidades, Clase de producto, grupo de producto, etc. 










> ### Campos Fijos
> Lista de Precios (Si no permite Filtrar por Lista de Precio puede dar a error de mostrar un producto que no está en la lista de precios). para hacerlo más fácil el control se puede seguir la misma lógica que aplica ZK actualmente. Por defecto se debería definir la lista de precios que tenga definida el documento desde uno está parado. Cuando se tenga definido una lista de precios, en ZK se agregan las columnas de Precio. Lo ideal sería mantener esta lógica, dejaría sólo el PRECIO en vez de agregar las 3 columnas de los 3 precios.

OK. 

Se podría mostrar sólo 1 precio?

> Almacén Idem comportamiento a la lista de precios, se debería definir a partir del almacén definida en el documento en cuestión. Si se tiene definida un almacén, se debería mostrar las columas de inventario tal como lo hace ahora ZK.

OK

> Proveedor: se debe permitir realzizar la búsqueda por proveedor tal como lo permite actualmete ZK. este filtro busca el proveedor definido en la pestaña Compras de la ventana Producto.

**No funciona.**

No se puede buscar por Proveedor. Se debería poder abrir el buscador de Socio del Negocio dentro del buscador de productos para buscar el SDN exacto. 

![Buscador de Producto: Filtro de Proveedor ZK 2](https://github.com/solop-develop/frontend-core/assets/31936815/f22cb819-200d-4387-90f0-7c5d27204d9f)
![Buscador de Producto: Filtro de Proveedor ZK](https://github.com/solop-develop/frontend-core/assets/31936815/24f839c1-8c3d-4bb1-a6f3-4552656fecbd)
![Buscador de Producto: Filtro de Proveedor no funciona](https://github.com/solop-develop/frontend-core/assets/31936815/c3762a89-0c89-4799-9eed-0fbd5b890048)



> ### Velocidad de selección
> Cuando se define un dato en un campo de SDN o Producto y se encuentra un resultado exacto único, actualmente el sistema demora bastante en definir el dato cuando en ZK esto es casi instantaneo
> 
> Entiendo que el comportamiento debería ser igual a ZK, separando en los dos escenarios:
> 
> Existe un Dato único con el texto/nro definido: Se define el Registro automáticamente
> Existe más de un dato con el texto/nro definido: se abre la ventana de búsqueda definiendo dicho dato en código o nombre (no se como se podría definir esto inteligentemente)
> 

No veo respuesta sobre este punto.

**Comment by EdwinBetanc0urt** [comment]
Se agregan los filtros de Categoría de Producto, Grupo de Producto, Clase de Producto y Clasificación de Producto.

https://github.com/solop-develop/frontend-core/assets/20288327/7b27eadc-9cf8-4bc3-a282-3eddd2ad7e13


> Lo ideal es poder editar para poder agregar los campos que se muestren según cada instancia.

Con respecto a esto, no puede hacerse luego que se agrego almacén y lista de precios que son columnas que están en otra tabla distinta a M_Product, anteriormente se podría, pero al agregar la funcionalidad de mostrar las columnas de existencia y precios queda el sql muy customizado a este campo de búsqueda imposibilitando el dinamismo propuesto.


> No se puede buscar por Proveedor. Se debería poder abrir el buscador de Socio del Negocio dentro del buscador de productos para buscar el SDN exacto.

Por ahora esta funcionalidad no se puede agregar hay que evaluar los contras, el abrir una búsqueda dentro de otra búsqueda no es lo mejor, lo segundo es que en este punto solo esta soportado.

> Velocidad de selección

Se mejoro la velocidad de activación de la búsqueda tenia un retardo de 2 segundos al igual, que un retardo de 300 mili segundos al mostrar los resultados. Se redujo la activación de la búsqueda a 700 mili segundos y a 10 mili segundos el retardo para mostrar los resultados.

https://github.com/solop-develop/frontend-core/assets/20288327/e8c9eb3f-5e34-4a6e-84bd-4ac60e921aa5

**Comment by niclopup** [comment]
Ok

Se define que el buscador de productos será utilizado para poder buscar productos fácilmente, no para ver información general de productos como lo hace ahora ZK q en una misma ventana rinde para las dos necesidades diferentes.
Para estas necesidades de ver información general de productos, le daremos más funcionalidad a la forma "Información de Productos" que ahora está muy ligado al punto de venta pero en realidad no debería ser así, dejandolo libre para que toda organización pueda ver la información de sus productos desde este visor. Para esto crearé una nueva issue: #2043


### Se solicita entonces los siguientes cambios:

**Ocultar Campos:**
Ocultar SKU y EAN (tanto como filtros como columnas)
Dejar sólo 1 columna de Precio "Standard Price". Ocutlar las demás 
Dejar sólo 2 columans de Inventario, Avaiable y On Hand Qty. Ocutlar las demás 


**Modificar Orden de Campos:**

1. Código
2. Nombre
3. Precio
4. UM
5. IsStocked
6. Avaiable
7. on Hand
8. Categoría
9. Grupo
10. Clase
11. Proveedor


### Definir Proveedor desde el Contexto

Ya que es dificil agregar el buscador de SDN dentro del Buscador de Productos, sugiero aplicar una líguca similar al campo "Proveedor" a la que tiene el campo "Lista de Precio". Si encuentra un "DropShip_BPartner_ID" definido tanto en el registro que se encuentra como en el registro padre (C_ProjectPhaseLine con C_ProjectPhase) 
Ver video de la definición:

https://youtu.be/M-yb0DB4LHo

**Comment by EdwinBetanc0urt** [comment]
Como se observa del encabezado se eliminan los campo `SKU` `UPC/EAN`.


![imagen](https://github.com/solop-develop/frontend-core/assets/20288327/a04bff1d-9de1-433b-9843-f81f230e26e8)


Al igual que se modifica el orden de las columnas en el resultado, quitando algunas de precio y existencia.

![imagen](https://github.com/solop-develop/frontend-core/assets/20288327/0257c06d-c381-428e-9be3-f4a4119bf772)


![imagen](https://github.com/solop-develop/frontend-core/assets/20288327/c213e975-751b-4e7e-b4e3-124b793a86d1)
