### ISSUE TITLE
Formato de FECHA en ventana Issues

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#1036]
## Feature request

Se desea modificar la forma que se muestra las "Fecha de Siguiente Acción" en la ventana de Issues.

No es necesario agregar la HORA ya que no es tan determinante normalmente y agrega información que no es necesaria.

Por favor se desea modificar para que sólo muestre la FECHA y no la HORA.

![image](https://github.com/solop-develop/frontend-core/assets/31936815/57bbcacb-52b3-4acd-82dc-4250c0531c4e)

![image](https://github.com/solop-develop/frontend-core/assets/31936815/517a4781-96ef-4b34-a221-5aa9f20dfe9f)

Ahora se ve que está asi:

![image](https://github.com/solop-develop/frontend-core/assets/31936815/ebc1a72d-1a1c-4c8f-ac50-e67667c83dfd)

#### Describe the solution you'd like

Debe quedar así:

![image](https://github.com/solop-develop/frontend-core/assets/31936815/873ebfe0-0deb-4530-814f-6ffb2327d266)

**Comment by EdwinBetanc0urt** [comment]
Esto fue corregido, ya esta montado en https://vue-develop.solopcloud.com/#/Issues

![image](https://github.com/solop-develop/frontend-core/assets/20288327/2951e4ee-b893-447f-b8dc-38c02e9320e6)
