### ISSUE TITLE
Ventana: Pestañas tipo Árbol > Listar Registros (Soporte a clausura WHERE)

### ISSUE THREAD

**Issue by EdwinBetanc0urt** [solop-develop/vue-1.0#1046]
#### Describe the solution you'd like
Si una pestaña tipo `árbol`, tiene clausura where en su definición, este no era considerado al listar el Árbol de la pestaña, por lo que no aplicaba correctamente el filtro de registros.

**Comment by niclopup** [comment]
no se define como verificarlo
