### ISSUE TITLE
Ventana Proyecto toma considerada como "IsoTrx=Y"

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#1048]
## Bug report
Según se analiza, la ventana de Proyuecto que está definida como "IsSoTrx=Y" es conside4rada por el campo de SDN como "IsSoTrx=N" por lo que considera los SDN que sean IsVendor=Y

**Comment by EdwinBetanc0urt** [comment]
En el menú esta marcado como falso, por lo que al cargar la ventana en el contexto sera `IsSOTrx=N`

![image](https://github.com/solop-develop/frontend-core/assets/20288327/7f40aa8b-c426-4554-bdef-54ec5718e1df)

**Comment by EdwinBetanc0urt** [comment]
Se modifica para la que se tome la siguiente jerarquia:
1. Valor de campo.
2. Ventana (si aplica, ya que en reportes/procesos/consultas inteligentes no aplica).
3. Menú.
