### ISSUE TITLE
Error al abrir ventana de Documentos por Cobrar y Socio del Negocio

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#1049]
## Bug report

Se intenta verificar la Forma de Asignación de Pagos y pero al intentar buscar un Documento por Cobrar, se ve que la ventana está funcionando de manera érronea. 

No se logra ver el SDN "Juan Pablo" en la ventana Socio del negocio

![Peek 2023-06-13 10-22](https://github.com/solop-develop/frontend-core/assets/31936815/0f3d18ee-1e87-4eff-bfd1-d4ca10e729f6)

Se busca una Factura documetnos por cobrar y se ve todo menos la dirección

![2023-06-13_10-23](https://github.com/solop-develop/frontend-core/assets/31936815/8ca8261a-0b2a-4551-95d9-8afe64ea15ec)

![Peek 2023-06-13 10-25](https://github.com/solop-develop/frontend-core/assets/31936815/e7bc43bf-f91b-4ef1-8312-9ee390071768)

se intenta completar un Documento porpagar pero no se ve la opción y si se intenta completar desde el proceso da error de Network al rato

![image](https://github.com/solop-develop/frontend-core/assets/31936815/ced5d945-fea3-46e2-ac53-0833ed9b2cd2)

#### Steps to reproduce

1. [xxx]
2. [xxx]
3. [xxxx]

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:

**Comment by EdwinBetanc0urt** [comment]
Esto ya fue corregido

![imagen](https://github.com/solop-develop/frontend-core/assets/20288327/408f76d4-d638-4632-8b5c-2cd4667097c5)


https://github.com/solop-develop/frontend-core/assets/20288327/8cd513b5-a5c8-43f0-ab43-0fd810de0ed9
