### ISSUE TITLE
Moneda en Campos de Importe no cambia según moneda del Documento

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#1055]
## Bug report

Se está definiendo en todos los campos de Importe de todas las ventanas, el ISO de la moneda USD siempre sin considerar la moneda que tenga definida cada documento. 

Según se conversa con Edwin esto es por qeu se está tomando la moneda a mostrar en los campos de importe según la moneda del Esquema Contable, esto está incorrecto ya que cada documento tiene un campo de "C_Currency" que se define según la Lista de precios que se seleccione. Es según esta moneda el ISO de la moneda que se debería mostrar en cada uno de los campos de Importes de cada una de las ventanas. 

![image](https://github.com/solop-develop/frontend-core/assets/31936815/dd5a44ef-d882-41ff-bc2c-88368b522b5c)

#### Steps to reproduce

1. [xxx]
2. [xxx]
3. [xxxx]

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:

**Comment by niclopup** [comment]
Según vemo en la línea no está actualizando correctamente la moneda.

Si no se logra corregir en la línea es mejor que No muestre ninguna moneda, sólo el importe si no tiene moneda en la tabla.

**Comment by EdwinBetanc0urt** [comment]
En caso de no existir moneda en la ventana, no se mostrara la moneda, sino solo el monto, ya que anteriormente buscaba el moneda de la compañía para darle el formato.

![imagen](https://github.com/solop-develop/frontend-default-theme/assets/20288327/9c53faa4-a71d-4cd2-9874-f685725b6e50)
