### ISSUE TITLE
Conciliación Bancaria en VUE

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#1056]
## Bug report

Se desea poder contar con el proceso de Conciliación bancaria en VUE

Actualmente en VUE Se ve la Forma de Conciliación con los filtros, pero no está trayendo data:

![Conciliación Bancaria en VUE](https://github.com/solop-develop/frontend-core/assets/31936815/83251a4a-99e2-4bb1-bd6f-0f026e6c8e16)

En ZK el mismo ejemplo se muestra como si trae data, más allá que por alguna trazón no está haciendo el MATCH AUTOMÁTICO

![Conciliación Bancaria en ZK](https://github.com/solop-develop/frontend-core/assets/31936815/d6cf97f8-aab3-45f8-a854-74a4fa3b2d90)

**Comment by EdwinBetanc0urt** [comment]
Duplicado con https://github.com/solop-develop/frontend-core/issues/943
