### ISSUE TITLE
[Bug Report] Error Campo Texto largo

### ISSUE THREAD

**Issue by elsiosanchez** [solop-develop/vue-1.0#1069]
## Bug report
Error en cargar el panel con el campo Texto largo

#### Screenshot or Gif（截图或动态图）

![ERROR](https://github.com/solop-develop/frontend-core/assets/45974454/04cc6202-33f6-443e-af18-31c0dd1cae52)

**Comment by EdwinBetanc0urt** [comment]
![Peek 2023-06-01 12-09](https://github.com/solop-develop/frontend-default-theme/assets/45974454/fb3b6f20-abce-4d8e-b2b8-01422d56e9e6)
