### ISSUE TITLE
[Bug Report] Copiar Salida en el Histórico Procesos

### ISSUE THREAD

**Issue by elsiosanchez** [solop-develop/vue-1.0#1072]
## Bug report

Actualmente cuando uno ejecuta un processo o reporte en el **Histórico Procesos** no hay manera de copiar el  log  del proceso o reporte ejecutado

#### Steps to reproduce

1. Ejecute un Proceso o Reporte
2. Diríjase a la ventana **Histórico Procesos**
3. Trate de copiar el log

#### Screenshot or Gif（截图或动态图）

![ERROR](https://github.com/solop-develop/frontend-core/assets/45974454/0558b273-d68a-4c47-bb2c-bb10e2bf6859)

**Comment by niclopup** [comment]
no se que sería exactamente la solución pero intento copiar la respuesta de un proceso y no me copia nada


https://github.com/solop-develop/frontend-core/assets/31936815/04d05700-f9b5-4aa6-9257-6e62f05a267f

**Comment by Ricargame** [comment]
Cambios disponibles apartir de la versión: https://github.com/solop-develop/frontend-core/releases/tag/3.8.3

https://github.com/solop-develop/frontend-core/assets/78000356/3dcb35ad-31bd-42ec-8225-56b6ef83eb19


https://github.com/solop-develop/frontend-core/assets/78000356/f358133f-931e-4e89-ab42-fe1aa4af9c8a

**Comment by niclopup** [comment]
Se ve la opción de Copiar pero sólo en Procesos finalizados OK.

En la sección de errores no se puede copiar y entiendo sería de gran utilidad tamnbién ahi poder copiar.

![image](https://github.com/user-attachments/assets/d9c6e04a-3b8f-4e3b-b5ba-c0fb4ba50dbe)

**Comment by elsiosanchez** [comment]
Se agregor la opcion de copiar la pestana de errores en la siguiente version https://github.com/solop-develop/frontend-core/releases/tag/4.4.019-rc-3

https://github.com/user-attachments/assets/a84ed1e9-91b8-4ff2-8c8a-53f2a741f14d
