### ISSUE TITLE
[Bug Report] Recargar la tabla al cambiar el tamaño de la página

### ISSUE THREAD

**Issue by elsiosanchez** [solop-develop/vue-1.0#1073]
## Bug report

Abra una ventana con muchos registro intente incrementar la cantidad de registro por pagina al hacerlo se logra apreciar que cambia al panel **Monovista** y luego pone de nuevo la vista de **Multi-Registro**

#### Steps to reproduce

1. Abar una ventana que contega muchos registro
2. Colo la ventana en modo **Multi-Registro**
3. Cambia el tamaño de la página

#### Screenshot or Gif（截图或动态图）

![ERROR](https://github.com/solop-develop/frontend-core/assets/45974454/b2d086d5-80e3-4e79-895d-43f57b1f8e0e)

**Comment by EdwinBetanc0urt** [comment]
![Peek 2023-06-01 12-09](https://github.com/solop-develop/frontend-default-theme/assets/45974454/cfc59f86-6b6e-4e0d-bda0-6f6fa82baedc)

**Comment by niclopup** [comment]
no entiendo bien lo qeu aplica pero si se agranda la paginación y luego se refresca la pestñaa, se vuelve a mostrar la paginación en 15 y no mantiene lo definido inicialmente.




https://github.com/solop-develop/frontend-core/assets/31936815/14c11691-3483-4cc3-aba7-3e72a5765a42

**Comment by EdwinBetanc0urt** [comment]
Esto también esta sucediendo en las consultas inteligentes.

**Comment by EdwinBetanc0urt** [comment]
cambios disponibles a partir de la versión https://github.com/solop-develop/frontend-core/releases/tag/4.0.5

https://github.com/solop-develop/frontend-core/assets/78000356/820d4a72-3820-4e0d-8693-d8b6a731f8a8
