### ISSUE TITLE
[Bug Report] Al guardar una línea de un documento, no se actualiza el encabezado

### ISSUE THREAD

**Issue by EdwinBetanc0urt** [solop-develop/vue-1.0#1084]
#### Steps to reproduce

1. Abrir la ventana `Documentos por Cobrar`.
2. Seleccionar un registro en borrador.
3. Llenar la linea y guardar.
4. Cambiar la cantidad a 100 y guardar.

#### Screenshot or Gif（截图或动态图）

https://github.com/solop-develop/frontend-core/assets/20288327/d5f955ff-f25b-45e1-8c80-3b5bdcc8bea2

#### Expected behavior
El campo total del encabezado debería actualizarse.

**Comment by niclopup** [comment]
Para ver el dato actualiaxdo en el cabezal es necesario ir al cabezal y actualizar el registro. 

Es posible que etso se haga automáticamente?

**Comment by Ricargame** [comment]
Cambios disponibles a partir de la versión del frontend: https://github.com/solop-develop/frontend-core/releases/tag/4.4.017

https://github.com/user-attachments/assets/e2a05a16-5cba-4f1c-a8af-a59010e3d375
