### ISSUE TITLE
[Bug Report] Comportamientos diferentes en WorkFlow de vue

### ISSUE THREAD

**Issue by rcapecce** [solop-develop/vue-1.0#1088]
## Bug report

Al completar una requisición se obtienen diferentes resultados al obtenerlo desde los diferentes botones de completar
Se toma como base la requisición 900050 que quedó suspendida hasta aprobarla

En ZK

Step 1: Crear e intentar Completar con GardenAdmin
Nodos del Flujo: Start -> DocPrepare -> "Please Approve Requisition"
![image](https://github.com/solop-develop/frontend-core/assets/14218144/1da7d592-0e20-4940-bd2b-0c1863d5eef3)

Step 2: Aprobar Flujo con SuperUser
![image](https://github.com/solop-develop/frontend-core/assets/14218144/3a81db79-29d2-4195-a9d8-15201c20c537)
Nodos del Flujo: Start -> DocPrepare -> "Please Approve Requisition" (Aprobado) -> DocComplete -> "Requisiciones Abiertas"
![image](https://github.com/solop-develop/frontend-core/assets/14218144/0a1ff5f7-72b8-4cb6-bcdf-bcb18a4880df)

En Vue - Requisición 900052 - Boton DocAction

Al ejecutar la acción retorna el siguiente error
![image](https://github.com/solop-develop/frontend-core/assets/14218144/923bed57-50de-4654-8947-bcfaa0b9302d)

Al procesar la petición da TimeOut y retorna error, no termina de procesarla
![image](https://github.com/solop-develop/frontend-core/assets/14218144/d2876a22-670e-4aed-8603-5ff918ed9e9a)

Carga Útil de esa petición

`{"process_uuid":"a42a552e-fb40-11e8-a479-7a0060f0aa01","table_name":"M_Requisition","uuid":"7453f065-6820-4f46-875f-08da8e71cec3","parameters":[],"selections":[]}`

Se observa que el estado de ese documento sigue siendo DR pero también se observa que el documento tiene el siguiente flujo

![image](https://github.com/solop-develop/frontend-core/assets/14218144/44c87505-7b75-4eb5-a687-93b091e577ca)

![Peek 2023-06-23 11-12](https://github.com/solop-develop/frontend-core/assets/14218144/913a6cd7-4962-4b12-a7f2-482e6e9ea117)

En Vue - Requisición 900052 - Menú de Documento - Proceso DocAction

![Peek 2023-06-23 11-16](https://github.com/solop-develop/frontend-core/assets/14218144/a9782bf9-3cd7-4378-a66a-8a1a60456729)

Para la Requisición 900052 se puede ver como quedó corriendo el nodo y no terminó, acorde con el timeout de la petición.

![image](https://github.com/solop-develop/frontend-core/assets/14218144/759ad513-a596-4f2d-81c5-6c2f13622c29)

En Vue - Requisición 900053 - Botón Completar de toolbar

![Peek 2023-06-23 11-19](https://github.com/solop-develop/frontend-core/assets/14218144/f5cc1a35-2f8e-429a-ae3c-842d6c80f922)

---

**Comportamiento esperado**

Las tres formas de accionar flujos con los documentos transaccionales deberían seguir la misma lógica como en zk.
En una de las reuniones también comentó Edwin que el Botón Completar de la Toolbar realizaba primero la acción processit pasando de DR a CO y después ejecutaba el flujo de trabajo, en este último gif se puede ver como el documento queda CL, esto en otras ocaciones se ha visto de que pasa a CL cuando se ejecuta un Completar 2 veces, puede ser debido a que el documento al ejecutar el flujo estando en estado Completo, por mas que se quiera ir al estado completo, lo deje en estado Cerrado como es en este caso de este documento.

**Comment by EdwinBetanc0urt** [comment]
Se revirtieron los cambios hechos ya que en ocasiones colgaba la transacción en base de datos, se va a evaluar a fondo como replicar el comportamiento del Zk/Swing
