### ISSUE TITLE
Imprimir documento no muestra PDF

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#1090]
## Bug report

Se intenta ver el formato de impresión de una orden de compra o cualquier otro documento y pero no sale el PDF

#### Screenshot or Gif（截图或动态图）

![Peek 2023-06-23 12-20](https://github.com/solop-develop/frontend-core/assets/31936815/91cc1a61-0ab1-4652-a3ce-32d15dee8eef)

**Comment by EdwinBetanc0urt** [comment]
![Peek 2023-06-01 12-09](https://github.com/solop-develop/frontend-core/assets/45974454/c53c01be-641e-43bd-94ee-892c8cbaf0dc)

**Comment by niclopup** [comment]
no se ven reportes de impresión de documentos

**Comment by EdwinBetanc0urt** [comment]
Corregido a partir de la versión del frontend https://github.com/solop-develop/frontend-core/releases/tag/3.6.0

https://github.com/solop-develop/frontend-core/assets/20288327/1aa99474-2d7c-4889-b453-b59c8939dd72
