### ISSUE TITLE
[Bug Report]Imprimir Factura

### ISSUE THREAD

**Issue by elsiosanchez** [solop-develop/vue-1.0#1091]
## Bug report
No permite imprimer factura desde la ventana Factura 
#### Steps to reproduce

1. Abra la ventana Documento Por Cobrar (Factura)
2. Despliegue el menú y Ejecute el Proceso Imprimir Factura
3. Nunca Imprimir la Factura

#### Screenshot or Gif（截图或动态图）

![ERROR](https://github.com/solop-develop/frontend-core/assets/45974454/c4b23547-8454-43a3-94d6-c6523d2f75e2)

**Comment by niclopup** [comment]
No funciona en Transcoding

LEGACY OK

![image](https://github.com/solop-develop/frontend-core/assets/31936815/66e2c25d-d90e-493e-b49d-0071eb765893)


TRANSCODING

![image](https://github.com/solop-develop/frontend-core/assets/31936815/d2912fa7-f955-4003-8bf0-ffe58016f389)

**Comment by EdwinBetanc0urt** [comment]
Se corrige que no mostraba el pdf al faltar `Arial` en las fuentes sin embargo el error que genera es de adempiere, ya que intenta pre-visualizar el reporte, pero el backend no tiene un previsualizador ya que de eso se encarga vue.

https://github.com/EdwinBetanc0urt/adempiere/blob/develop/JasperReports/src/org/compiere/jr/report/ReportStarter.java#L670-L679



https://github.com/solop-develop/frontend-core/assets/20288327/e77113c3-c0f3-45ed-ab9a-4f33877ca58f
