### ISSUE TITLE
Proceso: Carga > Valor por Defecto

### ISSUE THREAD

**Issue by elsiosanchez** [solop-develop/vue-1.0#11]
Saludos, actualmente en el cliente ZK para ADempiere se manejan valores por defecto los cuales se pueden configurar a nivel de cliente, organización, usuario y ventana

**Comment by elsiosanchez** [comment]
En ADempiere-Vue no se trae el visor por defecto de los campos tipo moneda

![image](https://user-images.githubusercontent.com/45974454/166821777-cea9ec7c-dd76-4fd4-b693-0bcf014c698b.png)

Interfaz ZK
![image](https://user-images.githubusercontent.com/45974454/166821968-be963e00-15a7-4f23-a13d-b25582842518.png)

**Comment by elsiosanchez** [comment]
el servicio de `default-value` no trae nada por eso no muestra el valor por defecto en el campo tipo moneda 

### Service
[default-value](https://github.com/adempiere/proxy-adempiere-api/blob/master/src/modules/adempiere-api/api/extensions/adempiere/user-interface/window/index.js#L301)
![image](https://user-images.githubusercontent.com/45974454/167010455-b21b0f25-7895-4c9a-a219-b17fb4fff14a.png)


### Curl

```Shell
curl --location --request GET 'https://api.erpya.com/api/adempiere/user-interface/window/default-value?process_parameter_uuid=a43a6c98-fb40-11e8-a479-7a0060f0aa01&id=53256&token=ba799911-7b90-400a-9731-12f5644526fb&language=es'
```

### GIF
En el siguiente gif se puede observar que hay  busqueda del service `default-value` el cual una trae valor y la otra no 
![errorvue gif](https://user-images.githubusercontent.com/45974454/167010713-8d8ab644-bc1a-40b8-a1e1-8428656bfdbe.gif)

**Comment by EdwinBetanc0urt** [comment]
Para el caso de uso de pruebas ver:
https://solop-develop.github.io/frontend-core/es/guide/use-cases/process.html#valor-por-defecto

**Comment by niclopup** [comment]
El caso presentado se valida correctamente.

**Comment by niclopup** [comment]
de todas maneras no se logra definir un Valor de Preferencia por el usuario desde un parámetro del proceso... pero entiendo qeu esto puede ser diferente a la lógica por defecto que definis en esta issue. no @EdwinBetanc0urt ?

**Comment by EdwinBetanc0urt** [comment]
El valor de preferencia es una funcionalidad diferente. También puede verificar si existe un valor por defecto en la información del campo

https://user-images.githubusercontent.com/20288327/174897256-c8e96e78-9c1a-4285-a7dd-bcd728461e3d.mp4

**Comment by niclopup** [comment]
Bien gracias! 
Hasta ayer pude verificarlo pero hoy ya no, ni en los procesos  y tampoco en las ventanas por eso consultaba.

Crearé una Issue pero comento que no funciona la Información de los campos en vue-develop

https://user-images.githubusercontent.com/31936815/174898431-d4acbf52-3cef-4703-aec8-f906e497b5c2.mp4

Esta tarea la damos por entregada

**Comment by EdwinBetanc0urt** [comment]
Esto fue corregido y actualizado en https://vue-develop.solopcloud.com por favor verificar y notificar
