### ISSUE TITLE
[Feature Request] Mostrar Campos por Defecto (Carga Incial de Visualización)

### ISSUE THREAD

**Issue by elsiosanchez** [solop-develop/vue-1.0#1103]
## Feature request

Actualmente no hay manera de mostrar los campos por defecto. Modifica la vista de los campos o selecciona (Vista Minimalista o Mostrar Todos Los Campos) para poner la vista de los campo por defecto se tiene que agregar de manera manual 

#### Describe the solution you'd like

Se requiere Agregar una nueva Opcion (Mostrar Campos Por Defecto)

**Comment by EdwinBetanc0urt** [comment]
![Peek 2023-06-20 14-39](https://github.com/solop-develop/frontend-default-theme/assets/45974454/b1d9762c-f22e-48bd-8d80-565888035a89)
