### ISSUE TITLE
Aumentar paginación no funciona con Búsqueda avanzada 

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#1104]
## Bug report

si se aplica una búsqueda avanzada  en una ventana, cuando se quiere aumentar la cantidad de registors a mostrar en una página, se pierde la búsqueda avanzada definida.

**Comment by EdwinBetanc0urt** [comment]
https://github.com/solop-develop/frontend-core/assets/20288327/b0417286-b123-4b78-9ea2-95d48713e964
