### ISSUE TITLE
[Feature Request] Valor de visualización en campo `Record_ID` si es tipo botón.

### ISSUE THREAD

**Issue by EdwinBetanc0urt** [solop-develop/vue-1.0#1107]
## Feature request

Se desea agregar el valor de visualización en los campos `Record_ID` tipo botón, de manera que se pueda identificar de manera mas sencilla cual es el registro al que se esta asociado.

![imagen](https://github.com/solop-develop/frontend-core/assets/20288327/4dbced38-51af-4088-946c-e1504a2c0b1f)

**Comment by EdwinBetanc0urt** [comment]
![imagen](https://github.com/solop-develop/adempiere-grpc-server/assets/20288327/4605e2da-5b06-481c-9950-b2b1051c8c49)

**Comment by niclopup** [comment]
Si se le hace click en el boto´n de ID de Registro no navega a la ventana de dicho registro como si lo hace en ZK

![image](https://github.com/solop-develop/frontend-core/assets/31936815/cd69346f-81bc-499d-8e1c-299993358902)

**Comment by EdwinBetanc0urt** [comment]
Se hará un servicio para obtener los acercadores de los campos incluyendo los tipo lista, tabla, tabla directa búsqueda y en este caso botón cuando aplique.

Quizás deba llevarse en un hilo (issue) distinto donde se defina el alcance, ya que el alcance inicial de este issue entiendo esta culminado.

**Comment by EdwinBetanc0urt** [comment]
Disponible a partir de la versión del frontend https://github.com/solop-develop/frontend-core/releases/tag/4.3.3

https://github.com/user-attachments/assets/24951d40-1803-4c73-b7ce-d06838f3ce15
