### ISSUE TITLE
[Feature Request] Mostrar/Ocultar columnas en función de `Desplegar información de documento`, `Desplegar información fuente` y `Desplegar cantidad`.

### ISSUE THREAD

**Issue by elsiosanchez** [solop-develop/vue-1.0#1112]
## Feature request

Se requiere que la pestaña de contabilidad tenga el mismo funcionamiento que en el **_Adempiere-ZK_** y permita ocultar y mostrar columnas segun la opción seleccionada
### _**GIF**_

![Peek 2023-06-20 14-39](https://github.com/solop-develop/frontend-core/assets/45974454/e7e0a718-2ff0-4fc2-9c1e-879708eb2def)

**Comment by EdwinBetanc0urt** [comment]
![Peek 2023-06-20 14-39](https://github.com/solop-develop/frontend-default-theme/assets/45974454/f2b9d40b-dd4e-4ad8-8149-c076cb75ea5d)
