### ISSUE TITLE
[Feature Request]Mover el buscador de Registro

### ISSUE THREAD

**Issue by elsiosanchez** [solop-develop/vue-1.0#1115]
## Feature request

Se Requiere cambiar de posicion el buscador de registro en la Ventana

![image](https://github.com/solop-develop/frontend-core/assets/45974454/3008d5ab-a78d-4981-b9b3-22d9f2d6e6d0)

**Comment by EdwinBetanc0urt** [comment]
![Peek 2023-06-20 14-39](https://github.com/solop-develop/frontend-default-theme/assets/45974454/016b6eea-88d4-45ea-8f92-6b5e93d8b25a)
