### ISSUE TITLE
Consulta Inteligente: Apertura > Árbol de Menú

### ISSUE THREAD

**Issue by EdwinBetanc0urt** [solop-develop/vue-1.0#112]
### Consulta Inteligente: Apertura > Árbol de Menú

Aperturar una Consulta Inteligente desde el árbol de menú:

1. Desplegar el árbol de menú en **Gestión de Ventas** > **Ordenes de Venta**.
2. Seleccionar la consulta inteligente **Procesar Órdenes en Lote**.

#### Visualización en la interfaz Zk:

https://user-images.githubusercontent.com/20288327/170698030-83465d77-fe23-47d7-adbd-228e9bff6501.mp4

**Comment by EdwinBetanc0urt** [comment]
#### Visualizacion en la interfaz Vue:

https://user-images.githubusercontent.com/20288327/170736845-6781f9c8-d9b1-4532-bca3-96cec5eb2b5a.mp4

**Comment by niclopup** [comment]
No se logra que desplegue las columnas.


https://user-images.githubusercontent.com/31936815/175378215-b7eb7abd-7fab-48c7-9a64-f6dd73a45723.mp4

**Comment by niclopup** [comment]
> No se logra que desplegue las columnas.
> 
>  Smart.Browser.no.desplega.columnas.mp4

Si bien no funciona las columnas, entiendo que no es un problema de esta Issue, ya que el SB abre correctamente desde el menú. Abro nueva Issue de error por esto
