### ISSUE TITLE
Ventana búsqueda sdn desaparece al intentar filtrar

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#1121]
## Bug report

mismo problema que pasaba con el buscador de productos.

se intentan buscar desde el buscador y al definir una letra en el nombre, la ventana desaparece o se esconde lo que no permite buscar correctamente.

![image](https://github.com/solop-develop/frontend-core/assets/31936815/76a5a2c1-0553-46eb-9f03-bdf88e533587)

![image](https://github.com/solop-develop/frontend-core/assets/31936815/eee872cc-933a-41d5-849e-98542e239b04)

#### Steps to reproduce

1. [xxx]
2. [xxx]
3. [xxxx]

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:

**Comment by EdwinBetanc0urt** [comment]
Corregido

https://github.com/solop-develop/frontend-core/assets/20288327/c77be5d4-dce0-4820-a322-a75cf87ccb62
