### ISSUE TITLE
Ventana Pago/Cobro: Pago no ve proveedor. Transacción de ventas según Documento y no según Ventana

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#1122]
## Bug report

Desde la ventana Pago/Cobro se intenta generar un pago desde la ventna pago cobro pero no se logra encontrr el sdn "Proveedor" .este se define como proveedor SI y Cliente NO

![image](https://github.com/solop-develop/frontend-core/assets/31936815/9192f95e-39e1-4b45-b739-b391b2669248)

analizar motivo pero posiblemente el motivo se ue l ventna está definida como Trnasacción de Ventas SI pero esta ventana es un caso especial ya que se puede generar tanto PAGOS (IsSoTrx=N) como también COBROS (IsSoTrx=Y) por lo que no se podrí definir sólo según la ventana sino que se debería tomar según el tipo de documento.

![image](https://github.com/solop-develop/frontend-core/assets/31936815/d5ab7ae8-d685-4803-933b-43d740d16a43)

![image](https://github.com/solop-develop/frontend-core/assets/31936815/23792c69-03b8-4a5d-8dfe-7b2720314ff6)

![image](https://github.com/solop-develop/frontend-core/assets/31936815/a82c1a73-81c2-4c70-b960-8183cb6ff625)

#### Steps to reproduce

1. [xxx]
2. [xxx]
3. [xxxx]

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:

**Comment by niclopup** [comment]
Esto ahora como se debería comportar? 

VEo que muestra los mismos registsos si se define un pago o un Cobro. 
En ZK había un check que cambiaba. 
* transacción de ventas SI mostraba el check de "Es Cliente" en SI
* transacción de ventas NO mostraba el check de "Es Proveedor" en SI

**Comment by EdwinBetanc0urt** [comment]
Esto ya esta corregido disponible a partir de la versión del backend https://github.com/solop-develop/adempiere-grpc-server/releases/tag/3.0.3


https://github.com/solop-develop/adempiere-grpc-server/assets/20288327/2092ed04-6e8c-4e10-8ac4-1bd6517626d0
