### ISSUE TITLE
Copiar registro desde ventana

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#1123]
## Feature request

no se encuentra la opción de "Copiar Registro" desde ventana

![image](https://github.com/solop-develop/frontend-core/assets/31936815/bb4db226-946c-4ad6-9eab-d58f71202541)

![image](https://github.com/solop-develop/frontend-core/assets/31936815/9206885f-7df8-41d9-a98b-e54034e5292d)

**Comment by EdwinBetanc0urt** [comment]
issue duplicado con https://github.com/solop-develop/frontend-core/issues/1119
