### ISSUE TITLE
[Feature Request] Mostar/Ocultar campos/columnas no guardan y se pierden al refrescar

### ISSUE THREAD

**Issue by EdwinBetanc0urt** [solop-develop/vue-1.0#1129]
## Feature request
Actualmente en cualquiera de los paneles (Proceso, Reporte, Consulta Inteligente, Ventana), al cargar los campos, se cargan con la vista minimalista, es decir los campo que cumplan con las siguientes condiciones:
- Cumple con las visualización.
- No tiene valor por defecto.
- Es obligatorio.
- Es un campo `Código` (`Value`) o `Estado de Documento` (`DocStatus`).
- Si el campo no es tipo `Si No`.

Un usuario puede mostrar/ocultar algunos campos, para ver según sea mas cómodo, sin embargo no se guarda la configuración, y al refrescarse se pierde la configuración de visualización hecha.

#### Describe the solution you'd like
Se deben agregar las campos tipo `SiNo` en lista (para tener valor vació), en las definiciones de los campos de ventana, procesos/reporte, consultas inteligentes, para guardar los atributos que se manejan en el cliente Si Es Mostrado Por Usuario `isShowedFromUser` que define el comportamiento para mostrar/ocultar en mono registro, y Si Es Mostrado Por Tabla `isShowedFromTable` que define el comportamiento en la tabla.

##### Ventana:
- `isShowedFromUser` > Panel de campos `Mono registro`.
- `isShowedFromTable` > Tabla `Multi registro`.

##### Consulta Inteligente:
- `isShowedFromUser` > Panel de campos `Criterio de búsqueda`.
- `isShowedFromTable` > Resultado de búsqueda.

##### Proceso/Reporte
- `isShowedFromUser` > Panel de campos de `Parámetros`.

Estos atributos pueden cambiarse el nombre si se desea, pero debe existir en base de datos para porder almacenar y gestionar esos valores.

#### Additional context
También deben ser agregados a las tablas ASP de campo.

**Comment by rcapecce** [comment]
@EdwinBetanc0urt estas son las columnas agregadas a la instancia de testing en nuestra instancia de pruebas.
Actualmente sigue sin poderse acceder a la instancia de zk por el error del paquete que no encuentra.
Te paso el packout que pasé por discord el otro día para hacer pruebas locales.
[IsDisplayedAsASPFields.zip](https://github.com/solop-develop/frontend-core/files/12454402/IsDisplayedAsASPFields.zip)

**Comment by niclopup** [comment]
Agrego comentarios en esta issue sobre el testing de la funcionalidad

En resumen creo que funciona bien cuando se realiza una lógica de "Ventana de Usuario" para un "Usuario" y en Modo Panel (Mono Registro).

Se encontró que no funciona las siguientes condiciones:

1. Cuando los campos definidos se guardan para un ROL, no se le guarda correctamente el campo "IsDisplayedAsPanel" con el SI/NO cuando se guarda una Modificación de secuencia de Campos. Estos campos quedan sin mofificar.
2. No hay manera de definir desde el proceso de "Modificar Secuencia de Campos" el despliege de los campos en modo Grilla. Si uno está en modo edición, no se puede mover del "mono reguistro" para ir a modificar en modo grilla.
3. Si uno va por la ventana de "Ventana de Usuario" desde ZK y define manualmente campo por campo el SI/NO en el campo "isDisplayedAsSingleRecord". tampoco funciona. Con este cambio se encuentra un accionar raro en la grilla de los campos disponibles para ver en modo grilla, hay veces que se ocultan algunos campos por ejemplo. No funciona la lógica de ver campos por defecto en formato Grilla.

![image](https://github.com/solop-develop/frontend-core/assets/31936815/a24dac66-83d3-4a1a-8089-9f702db1067e)

![image](https://github.com/solop-develop/frontend-core/assets/31936815/7b5dc1e9-156e-42bb-a35c-52fe1c42b2fb)

En grilla se definen 3 campos dentro de los cuales se incluye el "Nombre" pero no se ve para seleccionar dicho campo

![image](https://github.com/solop-develop/frontend-core/assets/31936815/c90a2873-74c9-4d44-8f81-56fee12cbae8)

**Comment by EdwinBetanc0urt** [comment]
@rcapecce Se deben cambiar los nombres de columnas del diccionario de aplicación.
- Campo Desplegado en Panel `IsDisplayedAsPanel` (mono registro).
- Campo Desplegado en Grilla (o Campo Desplegado en Tabla): `IsDisplayedAsTable` (multi registro o grilla).

**Comment by EdwinBetanc0urt** [comment]
Ademas existe un error al guardar la personalización para un rol, que guarda la personalización para usuario (no especificado).

**Comment by niclopup** [comment]
defini todos los campos manualmente para que no se vean en la grilla pero no logro que lo respete

![mostrar ocultar campos en grilla no respeta](https://github.com/solop-develop/frontend-core/assets/31936815/bf513a74-f501-43ad-96e5-3b5c5f97ab5b)

es más, ni los veo para seleccionar

estos son los campos que tengo marcados para que se vean en grilla

![image](https://github.com/solop-develop/frontend-core/assets/31936815/a74d54e1-7423-4b3f-970c-39bb39fd1437)


veo que ninguno de ellos los veo como posibles de seleccionar para que se vean en la ventana ni siquiera... 

![image](https://github.com/solop-develop/frontend-core/assets/31936815/dc078f17-a92a-400e-8c2b-5b563e03e367)
