### ISSUE TITLE
[Bug Report] Error de Visualización en el Dashboard en Modo Móvil

### ISSUE THREAD

**Issue by elsiosanchez** [solop-develop/vue-1.0#1146]
## Bug report
Se requiere mejorar la Visualización del Panel Principal (Dashboard) en Modo Móvil 

#### Steps to reproduce

- [x] Visualización del Panel Principal (Dashboard) 

#### Screenshot or Gif（截图或动态图）
![image](https://github.com/solop-develop/frontend-core/assets/45974454/7363d7be-e33a-4162-bcb3-dfed0c150e98)

#### Link to minimal reproduction（最小可在线还原demo）

[Demo](https://vue-develop.solopcloud.com/#/ProcessActivity/index)

#### Other relevant information
- Your OS: Linux Mint
- Web Browser: Chrome
- Node.js version: v14.21.

**Comment by niclopup** [comment]
Se ven mal los nuevos secciones que se agregaron en el panel de control

![Screenshot_20240402_180916_Chrome](https://github.com/solop-develop/frontend-core/assets/31936815/8f3225e1-5717-4316-8c7c-c4cbb47b42fd)
