### ISSUE TITLE
[Bug Report] Error en la Navegación en la Tabla en Modo Movil

### ISSUE THREAD

**Issue by elsiosanchez** [solop-develop/vue-1.0#1150]
## Bug report

Problema en la Navegación de Registro en la Tabla en Modo Móvil. Por lo cual en cuanto se cambia de registro en modo movil se cambia de modo panel automaticamente

#### Steps to reproduce

- [x] Cambie a registro múltiple con un solo toque en modo móvil
#### Screenshot or Gif（截图或动态图）

![ERROR](https://github.com/solop-develop/frontend-core/assets/45974454/0a4a8078-53d2-49b5-8101-0944a1bd77a8)

#### Link to minimal reproduction（最小可在线还原demo）

[Demo](https://vue-develop.solopcloud.com/#/ProcessActivity/index)

#### Other relevant information
- Your OS: Linux Mint
- Web Browser: Chrome
- Node.js version: v14.21.1

**Comment by niclopup** [comment]
Los procesos definidos en las ventanas se ven mal


https://github.com/solop-develop/frontend-core/assets/31936815/e4041bc3-97f4-4b88-8e1a-b8f7ac6655b7
