### ISSUE TITLE
[Bug Report] Problema con el Menú en modo Móvil

### ISSUE THREAD

**Issue by elsiosanchez** [solop-develop/vue-1.0#1151]
## Bug report

Se dificulta al usar las opciones de la ventanas en modo movil ya que son muchas

#### Steps to reproduce

- [x] Navegacion del Menu de la Ventana en Modo Mobil

#### Screenshot or Gif（截图或动态图）
![ERROR](https://github.com/solop-develop/frontend-core/assets/45974454/bab65d7e-9d70-46f8-a84c-913e2be23300)

#### Link to minimal reproduction（最小可在线还原demo）

[Demo](https://vue-develop.solopcloud.com/#/ProcessActivity/index)

#### Other relevant information
- Your OS: Linux Mint
- Web Browser: Chrome
- Node.js version: v14.21.1

**Comment by niclopup** [comment]
Los procesos definidos en las ventanas se ven mal


https://github.com/solop-develop/frontend-core/assets/31936815/e4041bc3-97f4-4b88-8e1a-b8f7ac6655b7

**Comment by Ricargame** [comment]
Cambios disponibles apartir de la versión: https://github.com/solop-develop/frontend-core/releases/tag/3.8.5


![Image](https://github.com/solop-develop/frontend-core/assets/78000356/093ea2c9-d825-494c-bd51-20824a9d4441)

**Comment by EdwinBetanc0urt** [comment]
En el icono de descarga no se ve la etiqueta `Exportar`.

**Comment by Ricargame** [comment]
Cambios disponibles apartir de la versión: https://github.com/solop-develop/frontend-core/releases/tag/3.9.3

https://github.com/solop-develop/frontend-core/assets/78000356/c42b5bc3-3833-4458-9fa0-b4ab2ebf0553
