### ISSUE TITLE
[Bug Report] Filtrar campos y alineación del menú de acciones

### ISSUE THREAD

**Issue by elsiosanchez** [solop-develop/vue-1.0#1157]
## Bug report

Problema Filtrar campos y alineación del menú de acciones

#### Steps to reproduce

- [x] Filtrar campos y alineación del menú de acciones

#### Screenshot or Gif（截图或动态图）

![image](https://github.com/solop-develop/frontend-core/assets/45974454/0eb291e2-99ce-4bdc-a000-b8451be7367b)

#### Link to minimal reproduction（最小可在线还原demo）

[Demo](https://vue-develop.solopcloud.com/#/ProcessActivity/index)

#### Other relevant information
- Your OS: Linux Mint
- Web Browser: Chrome
- Node.js version: v14.21.1

**Comment by EdwinBetanc0urt** [comment]
![image](https://github.com/solop-develop/frontend-core/assets/45974454/442ff7a2-0e24-4985-85a3-f8658527f368)
