### ISSUE TITLE
[Bug Report] Soporte a Modo Móvil

### ISSUE THREAD

**Issue by elsiosanchez** [solop-develop/vue-1.0#1159]
## Bug report
Se requiere dar Soporte a Modo Móvil

#### Steps to reproduce

- [x] https://github.com/solop-develop/frontend-core/issues/1156
- [x] https://github.com/solop-develop/frontend-core/issues/1154
- [x] https://github.com/solop-develop/frontend-core/issues/1150
- [x] https://github.com/solop-develop/frontend-core/issues/1146
- [x] https://github.com/solop-develop/frontend-core/issues/1166

#### Link to minimal reproduction（最小可在线还原demo）

[Demo](https://vue-develop.solopcloud.com/#/ProcessActivity/index)

#### Other relevant information
- Your OS: Linux Mint
- Web Browser: Chrome
- Node.js version: v14.21.1

**Comment by Ricargame** [comment]
Cambios disponibles a partir de la versión https://github.com/solop-develop/frontend-core/releases/tag/4.3.2

https://github.com/user-attachments/assets/396ffea1-74ae-4001-bb72-efa57e32cda4
