### ISSUE TITLE
Consulta Inteligente: Apertura > Asociado a Proceso de Ventana

### ISSUE THREAD

**Issue by EdwinBetanc0urt** [solop-develop/vue-1.0#116]
### Consulta Inteligente: Apertura > Asociado a Proceso de Ventana

Aperturar una consulta inteligente desde el proceso asociado en la ventana:

1. Abrir la ventana `Selección de Pago`.
2. En la parte superior en los procesos asociados seleccionar `Crear desde Órden`.

#### Visualización en la interfaz Zk:

https://user-images.githubusercontent.com/20288327/170731840-f654e529-7078-4212-8960-b1e8ced4d0a4.mp4

**Comment by EdwinBetanc0urt** [comment]
Cambios relacionados:
https://github.com/solop-develop/backend/pull/11
https://github.com/solop-develop/gRPC-API/pull/1
https://github.com/solop-develop/frontend-core/pull/100

**Comment by niclopup** [comment]
No se logra ver un registro en las ventanas

![image](https://user-images.githubusercontent.com/31936815/175379684-0e052e9c-2ada-4e99-867b-e89e1c1ba4a3.png)

**Comment by EdwinBetanc0urt** [comment]
Saludos adjunto la visualización de como realizarlo:

https://user-images.githubusercontent.com/20288327/178816791-d4211190-0665-45b4-8a93-f578579fe412.mp4

**Comment by niclopup** [comment]
Ok, el SB abre bien desde el Proceso. 
pero no se ven datos.

Se define error en #117
