### ISSUE TITLE
[Bug Report] Consulta Inteligente: Operadores `IN` y `NOT IN` no establecen el valor correctamente.

### ISSUE THREAD

**Issue by EdwinBetanc0urt** [solop-develop/vue-1.0#1164]
#### Steps to reproduce

1. Iniciar sesión con `GardenAdmin`.
2. Abrir la consulta inteligente `Procesar Órdenes en Lote`.
3. Ir al campo del criterio de búsqueda `Agente Comercial`.
4. Cambiar el operador a `Incluye ()`.
5. Seleccionar cualquier agente comercial de la lista.

#### Screenshot or Gif（截图或动态图）

https://github.com/solop-develop/frontend-default-theme/assets/20288327/76835db7-9093-4bbc-9d57-89a61c2c18c6

#### Expected behavior
Se espera que el valor seleccionado se mantenga y permita seleccionar múltiples registros para la búsqueda.

**Comment by EdwinBetanc0urt** [comment]
Adicionalmente se agrega soporte para permitir seleccionar registros vacíos en la lista.

https://github.com/solop-develop/frontend-default-theme/assets/20288327/f038c36d-b033-42b7-b833-ddc23d829e1d

**Comment by niclopup** [comment]
No estaría funcionando
![image](https://github.com/solop-develop/frontend-core/assets/31936815/bd204d55-227d-455c-8248-ccda5f1ed78c)

**Comment by Ricargame** [comment]
Error solucionado a partir de la versión:

Frontend
https://github.com/solop-develop/frontend-core/releases/tag/3.7.5

Backend
https://github.com/solop-develop/adempiere-grpc-server/releases/tag/3.1.6

https://github.com/solop-develop/frontend-core/assets/78000356/68f6cf3a-4c13-4380-9609-d277fc9d602d
