### ISSUE TITLE
[Bug Report] Abrir Pestañas de Secuencia en Modo Móvil

### ISSUE THREAD

**Issue by elsiosanchez** [solop-develop/vue-1.0#1166]
## Bug report
Se requiere una mejor visualizacion de la Secuencia de Pestaña en Modo Móvil
#### Steps to reproduce

- [x] Abrir Secuencia de Pestaña en Modo Móvil

#### Screenshot or Gif（截图或动态图）

![ERROR](https://github.com/solop-develop/frontend-core/assets/45974454/f5468fee-39cc-41b0-b456-25f5f3b9c7e2)

#### Link to minimal reproduction（最小可在线还原demo）

[Demo](https://vue-develop.solopcloud.com/#/ProcessActivity/index)

#### Other relevant information
- Your OS: Linux Mint
- Web Browser: Chrome
- Node.js version: v14.21.1

**Comment by EdwinBetanc0urt** [comment]
https://github.com/solop-develop/frontend-default-theme/assets/45974454/29185bed-1ac1-41db-9881-534984e89820

**Comment by niclopup** [comment]
No se visualiza ningún registro en TabSecuence ni FieldSecuence

![Screenshot_20240402_181802_Chrome](https://github.com/solop-develop/frontend-core/assets/31936815/e04b2c9b-c986-41fa-ba1a-d87f05cbed18)


El formato está correcto pero no se ven datos.

**Comment by EdwinBetanc0urt** [comment]
Se aplico una solución parcial, se va a mejorar los datos de la pestaña para que tenga la columna de filtro para enviar el id del registro.

**Comment by EdwinBetanc0urt** [comment]
cambios disponibles a partir de la versión https://github.com/solop-develop/frontend-core/releases/tag/4.0.5


https://github.com/solop-develop/frontend-core/assets/78000356/0cd3664d-c5b9-469f-9fd9-88a490d04acc
