### ISSUE TITLE
[Bug Report] Consulta Inteligente: Error de Paginación 

### ISSUE THREAD

**Issue by elsiosanchez** [solop-develop/vue-1.0#1167]
## Bug report
Al Abrir el Smart Browser arroja un error en la paginacion
#### Steps to reproduce

- [x] Error de Paginación en los **_Navegador inteligente (Smart Browser)_**

#### Screenshot or Gif（截图或动态图）
![ERROR](https://github.com/solop-develop/frontend-core/assets/45974454/cea78dd6-99f5-4204-9808-ba48c085812f)

#### Link to minimal reproduction（最小可在线还原demo）

[Demo](https://vue-develop.solopcloud.com/#/ProcessActivity/index)

#### Other relevant information
- Your OS: Linux Mint
- Web Browser: Chrome
- Node.js version: v14.21.1

**Comment by EdwinBetanc0urt** [comment]
![Peek 2023-07-04 11-28](https://github.com/solop-develop/frontend-default-theme/assets/45974454/656f2b87-ce09-446e-abd7-aa69dc8bcb8f)

**Comment by niclopup** [comment]
Ahora si bien se muestra la paginación, si se cambia de 15 a 25, se siguen mostrando los mismos registros. No cambia la barra para bajar a ver más registros

15 registros
![image](https://github.com/solop-develop/frontend-core/assets/31936815/b681de5a-8319-46ee-8aaa-351c8b42eeb4)

50 registros
![image](https://github.com/solop-develop/frontend-core/assets/31936815/a5567c94-0c1d-4a71-93d5-e38d70d1ced8)


ADemás, si se ven los 15 registros sólo muestra 12
![image](https://github.com/solop-develop/frontend-core/assets/31936815/01b3bab9-3985-481c-92f3-a4e30118ec02)

y si se hace menos zoom si se ven los 15 registros.
![image](https://github.com/solop-develop/frontend-core/assets/31936815/4ae05f67-f2dc-432d-91d1-903592d5927c)

si se hace con este mismo zoom el caso de 25 registors. queda igual los registos, no agranda
![image](https://github.com/solop-develop/frontend-core/assets/31936815/fbc136ae-1a0f-422a-8d6f-12629d49b8e3)

**Comment by elsiosanchez** [comment]
### _**GIF**_

https://github.com/solop-develop/frontend-core/assets/45974454/e4419666-742b-40b1-a1d8-1f055847de69
