### ISSUE TITLE
[Bug Report]Campos Obligatorio  Asignación de Pagos (Payment Allocation)

### ISSUE THREAD

**Issue by elsiosanchez** [solop-develop/vue-1.0#1169]
## Bug report

Campos Obligatorio Asignación de Pagos (Payment Allocation).

La forma que se seleccionan los parametros iniciales no es l mejor. El SDN debería ser obligatorio como la moneda

el SDN debería tener una búsqueda igual como en las ventanas

la fecha debería ser por defecto la del día y siempre debería mostrarse también en la segunda parte ya que se modifica según los documentos q se seleccionen.

### Screenshot or Gif（截图或动态图）

![image](https://github.com/solop-develop/frontend-core/assets/45974454/a70daf7b-2125-4e62-8998-1b75b4953606)

### Link to minimal reproduction（最小可在线还原demo）

[Demo](https://vue-develop.solopcloud.com/#/ProcessActivity/index)

### Other relevant information
- Your OS: Linux Mint
- Web Browser: Chrome
- Node.js version: v14.21.3

**Comment by EdwinBetanc0urt** [comment]
![Peek 2023-07-04 11-28](https://github.com/solop-develop/frontend-default-theme/assets/45974454/e1c5a483-e723-452c-a020-5fb9fc051cb4)
