### ISSUE TITLE
Consulta Inteligente: Apertura > Asociado a Campo tipo Botón

### ISSUE THREAD

**Issue by EdwinBetanc0urt** [solop-develop/vue-1.0#117]
### Consulta Inteligente: Apertura > Asociado a Campo tipo Botón de la Ventana

Aperturar una consulta inteligente desde el proceso asociado a un botón en la ventana:

1. Abrir la ventana `Selección de Pago`.
2. Seleccionar el campo tipo botón `Crear desde Órden`.

#### Visualización en la interfaz Zk:

https://user-images.githubusercontent.com/20288327/170732211-f60b544b-6665-4b6f-9203-bfa36591c984.mp4

**Comment by EdwinBetanc0urt** [comment]
Cambios relacionados:
https://github.com/solop-develop/backend/pull/11
https://github.com/solop-develop/gRPC-API/pull/1
https://github.com/solop-develop/frontend-default-theme/pull/25

**Comment by niclopup** [comment]
No se logra ver un registro en una ventana

![image](https://user-images.githubusercontent.com/31936815/175379836-788cd496-4ede-4412-9de8-8415d12207f7.png)

**Comment by EdwinBetanc0urt** [comment]
Saludos @niclopup solucionado

https://user-images.githubusercontent.com/20288327/178816793-95f091a9-19db-4127-acdd-66dd51e25a6e.mp4

**Comment by niclopup** [comment]
Se logra ver la ventana, pero no se logra guardar un registro en la ventana "Selección de Pagos" desde VUE. 

Se guarda un registro en la ventana "Selección de Pagos" desde ZK y se intenta obtener datos desde el SB "Create From Invoice" desde VUE. No se logra obtener datos desde VUE, pero si se ven ok en ZK

https://user-images.githubusercontent.com/31936815/179789827-2048a457-7e92-469d-87c6-c235ada06502.mp4

**Comment by EdwinBetanc0urt** [comment]
Se debe verificar si se esta enviando el contexto de la ventana desde donde se apertura a la consulta inteligente.

**Comment by EdwinBetanc0urt** [comment]
https://user-images.githubusercontent.com/20288327/218088052-c0c2dccf-fdf0-4fab-aff0-5cf3a29ca72e.mp4
