### ISSUE TITLE
[Bug Report] Cambiar orientación de vertical a horizontal en la sección de "Pagos" y de "Facturas"

### ISSUE THREAD

**Issue by elsiosanchez** [solop-develop/vue-1.0#1170]
## Bug report

No es practico ue se muestren de manera vertical la sección de "Pagos" y de "Facturas" ya q tienen más datos a ver en columnas por cada registro que para abjo. es mejor si se definen cada sección de manera horizontal como esta en ZK

### Screenshot or Gif（截图或动态图）
https://user-images.githubusercontent.com/31936815/251018102-f1f408cc-939b-49a3-bebe-bb456584397e.png

En este ejemplo se ve como no se visauliza el total asignado en la primer pantall sino ue tengo que mover el scroll horiz a la derecha para ver el campo, si lo muevo, ya no veo los documentos ue tengo seleccionados.

![image](https://github.com/solop-develop/frontend-core/assets/45974454/116d40ce-ac0e-4474-a5d5-046f41f7ed90)
![image](https://github.com/solop-develop/frontend-core/assets/45974454/d81badca-54f7-4fe3-b2b9-505d50630f84)

### Link to minimal reproduction（最小可在线还原demo）

[Demo](https://vue-develop.solopcloud.com/#/ProcessActivity/index)

### Other relevant information
- Your OS: Linux Mint
- Web Browser: Chrome
- Node.js version: v14.21.3

**Comment by EdwinBetanc0urt** [comment]
![image](https://github.com/solop-develop/frontend-default-theme/assets/45974454/cc42524b-8070-44f9-b1ed-347d22f14319)
