### ISSUE TITLE
Consulta Inteligente: Apertura

### ISSUE THREAD

**Issue by EdwinBetanc0urt** [solop-develop/vue-1.0#118]
- [x] #112
- [x] #114
- [x] #115
- [x] #116
- [x] #117

**Comment by EdwinBetanc0urt** [comment]
https://solop-develop.github.io/frontend-core/es/guide/use-cases/process.html#carga

**Comment by elsiosanchez** [comment]
![Peek 2022-06-16 10-38](https://user-images.githubusercontent.com/45974454/174095002-7bf8ba4c-b361-437b-8639-3925ae6a2cae.gif)

**Comment by niclopup** [comment]
Se verifican todas menos los SB desde ventanas ya que no se puede ver registros desde ventanas

**Comment by EdwinBetanc0urt** [comment]
Saludos adjunto la visualización de como realizarlo:

https://user-images.githubusercontent.com/20288327/178816791-d4211190-0665-45b4-8a93-f578579fe412.mp4
