### ISSUE TITLE
[Bug Report] From: Payment Allocation (Validate Business Partner)

### ISSUE THREAD

**Issue by elsiosanchez** [solop-develop/vue-1.0#1180]
#### Screenshot or Gif（截图或动态图）

![ERROR](https://github.com/solop-develop/frontend-core/assets/45974454/01b0a271-ed67-47c3-8f88-e435811ad390)

**Comment by EdwinBetanc0urt** [comment]
duplicado con https://github.com/solop-develop/frontend-core/issues/1179
