### ISSUE TITLE
SB Crear desde OC/Factura en Recepción de Productos no trae líneas

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#1181]
## Bug report

Se crea una OC y luego se intenta Recepción de Productos a partir de ella. 

Se selecciona la OC nro 800022

![image](https://github.com/solop-develop/frontend-core/assets/31936815/4b244963-8934-4ac3-aa39-b71ddf689c9d)

OC Está completa y con cantidad pendiente de recibir.

![image](https://github.com/solop-develop/frontend-core/assets/31936815/12d5498f-5fc8-4616-92ae-f0124a3c32b7)

**Comment by EdwinBetanc0urt** [comment]
https://github.com/solop-develop/adempiere-grpc-server/assets/20288327/462611cf-aa56-401d-8eaf-2d51ce190583
