### ISSUE TITLE
Reporte se lanza automáticamente desde pestaña Proveedor Ventana SDN

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#1190]
## Bug report

Se navega al SDN desde un DxP y cuando se hace click en la pestaña "Proveedor" se corre uno de los procesos automáticamente. No se puede salir ya que se lanza una y otra vez 

![Proceso se lanza automáticamente desde Ventana SDN pestaña Proveedor](https://github.com/solop-develop/frontend-core/assets/31936815/51e092ed-6416-4bd9-a0b3-acc6107ad580)

#### Steps to reproduce

1. [xxx]
2. [xxx]
3. [xxxx]

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:

**Comment by EdwinBetanc0urt** [comment]
![ERROR](https://github.com/solop-develop/frontend-default-theme/assets/45974454/50e162bf-c737-4a98-93dc-8d03fe1d149e)
