### ISSUE TITLE
Acercar en Cuenta Bancaria no lleva al registro correctamente

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#1192]
## Bug report

Si desde un Pago/Cobro se desea acercar a una Cuenta Bancaria, el sistema te lleva hasta la ventana de Banco (correcto) pero muestra un registro vacío. 

Esto podría ser ya que la cuenta bancaria está debajo de la C_Bank. No se cómo se piensa solucionar cuando se navega a un hijo y no a un cabezal de una ventana.

![Acercar en Cuenta Bancaria no llega a registro](https://github.com/solop-develop/frontend-core/assets/31936815/356bc347-a592-401c-8d67-d7476250865a)

**Comment by Ricargame** [comment]
Cambios disponibles apartir de la versión: https://github.com/solop-develop/frontend-core/releases/tag/3.9.8



https://github.com/solop-develop/frontend-core/assets/78000356/283ce955-7a04-4511-a11e-fa9eb607e5b5

**Comment by Ricargame** [comment]
Cambios disponibles apartir de la versión: https://github.com/solop-develop/frontend-core/releases/tag/4.0.3

https://github.com/solop-develop/frontend-core/assets/78000356/86a596a7-25e5-4be6-b7bf-ed1489d87d9d

**Comment by mgarciaQ76** [comment]
Verificado. Se realizan pruebas con resultado exitoso ok


https://github.com/user-attachments/assets/563fe690-ddc9-4ddd-9ddb-26e18fab33e8
