### ISSUE TITLE
Forma: Cargador de Archivos > Procesar importación de datos.

### ISSUE THREAD

**Issue by EdwinBetanc0urt** [solop-develop/vue-1.0#1218]
Permite ejecutar el proceso seleccionado para ejecutar la importación de datos luego de guardar registros en la tabla de importación.

https://github.com/solop-develop/frontend-core/assets/20288327/858cbc59-042f-4ae0-9cf2-389b77243c6f

**Comment by EdwinBetanc0urt** [comment]
Se debe dar soporte para que el procese el archivo enviando el enlace para que lo descargue

**Comment by elsiosanchez** [comment]
Solventado en el siguiente PR https://github.com/solop-develop/frontend-core/pull/2598

**Comment by EdwinBetanc0urt** [comment]
Cambios disponibles a partir de la versión del backend https://github.com/solop-develop/adempiere-grpc-server/releases/tag/3.6.8 y del frontend https://github.com/solop-develop/frontend-core/releases/tag/4.3.2

https://github.com/user-attachments/assets/82dd170e-628d-4b07-9597-688f5a3eb958
