### ISSUE TITLE
Consulta Inteligente: Manejo

### ISSUE THREAD

**Issue by elsiosanchez** [solop-develop/vue-1.0#122]
- [x] #127
- [x] https://github.com/solop-develop/frontend-core/issues/129
- [x]  #128
- [x] #130
- [x] #458

**Comment by EdwinBetanc0urt** [comment]
https://solop-develop.github.io/frontend-core/es/guide/use-cases/process.html#carga

**Comment by niclopup** [comment]
No se logra obtener datos

se crea Issue: 
https://github.com/solop-develop/frontend-core/issues/200

**Comment by EdwinBetanc0urt** [comment]
Corregido en los cambios del pull request https://github.com/solop-develop/frontend-core/pull/201

**Comment by niclopup** [comment]
se encuentran errores detallado en Issue hijas.

**Comment by EdwinBetanc0urt** [comment]
@niclopup La carga de datos en la tabla fue corregida. Sin embargo existe un comentario https://github.com/solop-develop/frontend-core/issues/129#issuecomment-1263067060 acerca de la edición, quizás se pueda ampliar en otro issue o reabrir y cambiar el estatus el mismo issue
