### ISSUE TITLE
Forma: Cargador de Archivos > Mostrar campos en función del formato de importación.

### ISSUE THREAD

**Issue by elsiosanchez** [solop-develop/vue-1.0#1220]
Mostrar los Campos segun el **_Formatos de Importación_** seleccionado
### _**GIF**_

![ERROR](https://github.com/solop-develop/frontend-core/assets/45974454/9df65afa-c01d-48f2-bf98-ae591a8f388a)

**Comment by EdwinBetanc0urt** [comment]
https://github.com/solop-develop/frontend-core/assets/20288327/ec5bad49-9149-4587-8ed9-f8040b38ca08
