### ISSUE TITLE
Forma: Cargador de Archivos > Generar pre-visualización de los primeros 100 datos.

### ISSUE THREAD

**Issue by elsiosanchez** [solop-develop/vue-1.0#1223]
Luego de seleccionar el archivo, el conjunto de caracteres y el formato de importación, se puede ver la previsualización de las primeras 100 filas, ademas de establecer los valores en los campos del formato de importación.

https://github.com/solop-develop/frontend-core/assets/20288327/6d61e212-f0f2-44a5-9b15-f3271f675857

Ademas en vue, se genera una previsualización de los registros en forma de tabla para que pueda ser mas entendible al usuario.

https://github.com/solop-develop/frontend-core/assets/20288327/4e2a4301-5ee4-45ce-8aed-1b348498c4e8

**Comment by EdwinBetanc0urt** [comment]
Cambios disponibles a partir de la versión del backend https://github.com/solop-develop/adempiere-grpc-server/releases/tag/3.6.8 y del frontend https://github.com/solop-develop/frontend-core/releases/tag/4.3.2


https://github.com/user-attachments/assets/f5585eff-6438-400d-89d1-b674bf13a83e
