### ISSUE TITLE
[Feature Request] Cambiar la Visualización de la Tabla

### ISSUE THREAD

**Issue by elsiosanchez** [solop-develop/vue-1.0#1229]
## Feature request

Por lo momento en modo tabla no se pueden quitar las columnas que están tildadas como obligatorio 

_**Ejemplo**_
Si en la ventana _**(Tipo Relación)**_ en modo tabla quiero ver solo la columna de Activo no se puede ya que siempre se queda siempre el campo _**(Nombre)**_ y no se puede ocultar de la tabla

### _**GIF**_

![ERROR](https://github.com/solop-develop/frontend-core/assets/45974454/e347442a-793d-49a7-821a-5ce69d5dabdc)

**Comment by niclopup** [comment]
No se logra replicar corrección. Se mantiene lo que reporta el error.

![Cambiar visualización de Tabla (Ventana tipo relacion) no esconde campo en grilla](https://github.com/solop-develop/frontend-core/assets/31936815/a577275e-6f07-4bc5-b9c5-c942c201af26)

**Comment by EdwinBetanc0urt** [comment]
cambios disponibles a partir de la versión https://github.com/solop-develop/frontend-core/releases/tag/4.0.5

https://github.com/solop-develop/frontend-core/assets/78000356/d3be6b74-501e-443f-81b2-b013b1fd34c5
