### ISSUE TITLE
Ventanas más limpias con pestañas minimizadas y en la parte inferior de la ventana

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#1232]
## Bug report

Las ventanas vistas en modo "Mono-Registro" muestra la información demasiado apretada. mejor si está más espaciada, mostrando sólo datos del cabezal, minimizando siempre las pestañas hijas en la parte inferior de la ventana.

![image](https://github.com/solop-develop/frontend-core/assets/31936815/bb1397da-65f9-40c3-950e-e99db315ed58)

**Comment by niclopup** [comment]
Ok, funciona pero aún mantenemos visible una pequeña aprte de las pestañas que no debería aparecer.

Esto es con Zoom 100%
![image](https://github.com/solop-develop/frontend-core/assets/31936815/b487491d-b237-42b7-9bc8-60cc8f1ee0d1)

Ahi lo tengo con Zoom 125 y queda mejor.

![image](https://github.com/solop-develop/frontend-core/assets/31936815/ca25e20e-c0fe-4401-9565-eb60e25ea020)

**Comment by Ricargame** [comment]
Cambios disponibles apartir de la versión: https://github.com/solop-develop/frontend-core/releases/tag/3.9.3


https://github.com/solop-develop/frontend-core/assets/78000356/e76a2584-8dc5-42fd-85e8-6f7bbff84cff
