### ISSUE TITLE
Campo > Imagen > Subida de Imagen como adjunto.

### ISSUE THREAD

**Issue by EdwinBetanc0urt** [solop-develop/vue-1.0#1238]
En los campos tipo imagen como en la ventana `Usuario` o `Socio` existe el campo `Logo` donde se puede agregar una imagen, esta es creada en la tabla `AD_Image` (ventana `Imagen del Sistema`) donde si se tiene configurado el manejador de archivos, se crea automáticamente la referencia de adjunto.

![ERROR](https://github.com/solop-develop/frontend-core/assets/45974454/9c2570ad-d0c6-471f-8ab9-e889defb4d28)

**Comment by EdwinBetanc0urt** [comment]
https://github.com/solop-develop/frontend-default-theme/assets/20288327/7f79bd0b-60fd-4cb9-b75c-e1c19f36a67a

**Comment by niclopup** [comment]
para tener visibilidad q está faltando los adjuntos en VUE Transcoding paso este issue a Revisión

**Comment by EdwinBetanc0urt** [comment]
Corregido

![imagen](https://github.com/solop-develop/frontend-core/assets/20288327/aa91a5bc-abb7-4dbe-a3e1-d057deb3f962)

**Comment by niclopup** [comment]
No se muestra la imagen cargada en el campo, muestra la imagen que se cargue como adjunto al registro desde las pestañas laterales

![Imagen del Logo de SDN muestra un adjunto del registro y no el que se cargó en el campo LOGO](https://github.com/solop-develop/frontend-core/assets/31936815/b1f7dea3-5c92-450f-8f13-c77d3785cb6a)

**Comment by elsiosanchez** [comment]
@niclopup Solventado

https://github.com/solop-develop/frontend-core/assets/45974454/df1c4ccd-75de-4b13-baf7-40a66e432aa1
