### ISSUE TITLE
Importe del Gráfico no se visualiza en ventana emergente

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#1239]
## Bug report

No se visualiza los importes de cada Barra del gráfico en la ventana donde antes si lo decía en Nro.

![image](https://github.com/solop-develop/frontend-core/assets/31936815/ae924ddb-f485-4f4a-a0d9-111048a49fe4)

**Comment by EdwinBetanc0urt** [comment]
![ERROR](https://github.com/solop-develop/frontend-core/assets/45974454/22ca8f55-ac76-40cb-b9fa-0264cff73547)
