### ISSUE TITLE
Campo > Imagen > Pre-visualización en mono registro.

### ISSUE THREAD

**Issue by EdwinBetanc0urt** [solop-develop/vue-1.0#1241]
Si el campo de imagen tiene un valor, visualizar la imagen con una baja resolución (200 x 200 pixeles) para ahorrar ancho de banda, y hacer zoom para ver con una resolución mucho mejor si la imagen original la tiene (1024 x 1024 pixeles).

https://github.com/solop-develop/frontend-core/assets/20288327/b56fe42d-92db-4fb1-a19e-de1512ef0580

**Comment by niclopup** [comment]
No se visualiza ok en versión del Front  3.6.1

Parecería que la adjunta bien pero no la muiestra

Luego de pruebas se ve que muestra si se adjunta desde la pestaña lateral y no desde el campo mismo.

![Cargar Imagen en Campo LOGO tabla SDN No se visualiza ](https://github.com/solop-develop/frontend-core/assets/31936815/17e02d1c-5cc1-4284-9fc1-b848d29d8319)


Si voy a la pestaña de Adjuntos del registro si lo muestra bien.

![image](https://github.com/solop-develop/frontend-core/assets/31936815/fd9ef666-ea47-4ca0-8092-25db89c251fc)

![Imagen del Logo de SDN muestra un adjunto del registro y no el que se cargó en el campo LOGO](https://github.com/solop-develop/frontend-core/assets/31936815/499a9152-cd00-442b-bd86-b9531de44525)
