### ISSUE TITLE
Campo > Imagen > Reemplazo de Imagen.

### ISSUE THREAD

**Issue by EdwinBetanc0urt** [solop-develop/vue-1.0#1247]
Esta opción no esta disponible en el zk, ya que se asocia la imagen al registro una sola vez, aca con re-subir la imagen al campo, crea una nueva referencia de adjunto con la imagen, y asocia ese nuevo valor al registro.

https://github.com/solop-develop/frontend-core/assets/20288327/1e4bcad3-06d1-48dc-8392-07bcf840c3d3

#### Información Adicional
Esto no elimina la imagen anterior, sin embargo quizás deba hacerse un proceso en ADempiere que limpie las imágenes y por ende sus referencia de adjuntos y archivos físicos, que no estén asociados a ningún registro y que su fecha de creación sea mayor a 24/48 horas, para evitar que el tamaño almacenamiento s3 crezca innecesariamente.

**Comment by niclopup** [comment]
no se carga cdesde el campo

**Comment by EdwinBetanc0urt** [comment]
La funcionalidad de limpiar la imagen se elimina, debido a que ya no existe la referencia de adjunto para saber que esta asociada la imagen a un adjunto, ahora solo la descarga del s3 o se elimina directamente.
