### ISSUE TITLE
Vista > Perfil > Registros de Actividades

### ISSUE THREAD

**Issue by elsiosanchez** [solop-develop/vue-1.0#1262]
### _**Solicitud**_

Se requiere Mostrar el Registro de **_Actividades del Usuario_**

### _**Describe la solución que te gustaría**_

Debe mostrar  todas las  del **_Actividades del Usuario_** con una Línea de Tiempo

### _**Caracteristica**_

El Historico de **_Actividades del Usuario_** debe tener 
- [x] Fecha
- [x] Tipo de Actividad ( _**Ventana, Proceso y Reporte**_ )
- [x] Descripción de la **_Actividades del Usuario_**

**Comment by EdwinBetanc0urt** [comment]
![image](https://github.com/solop-develop/frontend-core/assets/20288327/2f0e42a4-fdb6-46be-bea3-1b0f23cba51a)
