### ISSUE TITLE
Consulta Inteligente: Manejo > Búsqueda

### ISSUE THREAD

**Issue by EdwinBetanc0urt** [solop-develop/vue-1.0#127]
La búsqueda se debe realizar al llenar todos los campos obligatorios, al realizar un cambio en cualquier campo, al ocultar/mostrar un campo con un valor.

En los resultados debe manejar selección.

Debe tener soporte para la paginación.

- [x] https://github.com/solop-develop/frontend-core/issues/1066

**Comment by elsiosanchez** [comment]
Se agrego un panel de Criterio de busqueda el cual esta conformado por lo parametros con los cual se realiza la busqueda de los registro 

### Version Escritorio
![search-record-ui](https://user-images.githubusercontent.com/45974454/171045268-ca19bce7-a8de-4245-972d-8871208e7b7e.gif)


### Version Movil

![search-record-ui-mobile](https://user-images.githubusercontent.com/45974454/171045321-1247fc57-beed-44eb-8584-5a14225e9755.gif)

**Comment by EdwinBetanc0urt** [comment]
Cambios relacionados:
https://github.com/solop-develop/backend/pull/10
https://github.com/solop-develop/backend/pull/14
https://github.com/solop-develop/gRPC-API/pull/2
https://github.com/solop-develop/proxy-adempiere-api/pull/1
https://github.com/solop-develop/frontend-core/pull/93
https://github.com/solop-develop/frontend-default-theme/pull/22
https://github.com/solop-develop/frontend-default-theme/pull/24

**Comment by niclopup** [comment]
No se logra ver datos 

https://user-images.githubusercontent.com/31936815/175383039-a87ed402-778b-4fb8-9ed6-9e64aa69b9ce.mp4

**Comment by EdwinBetanc0urt** [comment]
Corregido en los cambios del pull request https://github.com/solop-develop/frontend-core/pull/201
