### ISSUE TITLE
[Question] Cambio en Impresión de Tiket de POS para poder mostrar un reporte pdf obtenido de un proceso

### ISSUE THREAD

**Issue by rcapecce** [solop-develop/vue-1.0#1275]
Se requiere ver como a partir de un proceso que obtiene un PDF de un webservice ejecutado en el momento, visualizarlo por pantalla como ticket del proveedor de factura electónica.

Actualmente se está mostrando un reportview
![image](https://github.com/solop-develop/frontend-core/assets/14218144/5f81fd89-0ea7-4f8c-bea1-9c5257baac08)

Se requiere poder configurar para que el mismo ejecute un InformeYProceso y tome el PDF.

https://github.com/solop-develop/adempiere-grpc-server/blob/413f3106c10e5a844598e937dda36cacfded6a8e/src/main/java/org/spin/grpc/service/PointOfSalesServiceImplementation.java#L772
Entiendo sería por acá la modificación pero no estoy logrando que entre en esta sección.

**Comment by rcapecce** [comment]
Se cierra para seguir en #1396

**Comment by EdwinBetanc0urt** [comment]
![error](https://github.com/solop-develop/frontend-core/assets/45974454/5445d4a9-c21a-4447-ba94-ae9c41666ecf)
