### ISSUE TITLE
Solicitudes: Agregar Imagen al Asignado

### ISSUE THREAD

**Issue by elsiosanchez** [solop-develop/vue-1.0#1277]
### _**Screenshot**_

![image](https://github.com/solop-develop/frontend-core/assets/45974454/1b176ac2-3401-47e2-a4d6-71c92a7e8f64)

![image](https://github.com/solop-develop/frontend-core/assets/45974454/4846ffed-33ec-4096-98b6-0cb12e1b5516)

**Comment by niclopup** [comment]
Falla igual que en el usuario

![image](https://github.com/solop-develop/frontend-core/assets/31936815/3d0a3b68-b6d4-45a2-87a3-42822db51bc4)

**Comment by niclopup** [comment]
no se visualiza el avantar del usuario. el mismo que cargó el usuario como su foto. 

Se puede?

![image](https://github.com/user-attachments/assets/d69702d3-72ba-4386-9da6-be1ea58e6a7b)

**Comment by elsiosanchez** [comment]
https://github.com/solop-develop/frontend-core/pull/2851

**Comment by Ricargame** [comment]
Cambios disponibles partir de la versión del front https://github.com/solop-develop/frontend-core/releases/tag/4.4.020

https://github.com/user-attachments/assets/2649f075-a877-4fe2-abe6-1ff108cc612d

**Comment by niclopup** [comment]
se ve bien la imagen del usuario, pero parece que este cambio rompio el logo que tenía antes para los Proyectos en la vista de todas las solicitudes

![image](https://github.com/user-attachments/assets/16ad6ea6-a3cd-452f-b1a0-cb49afb3b797)

por otro lado, cuando un usuario NO TIENE imagen, se ve un msj feo como si fuese un error. sería mejor si podemos poner un avantar agnóstico bien típico de "Usuario" para definir como genérico si no tiene imagen.

![image](https://github.com/user-attachments/assets/b4cee460-97f3-40c8-8c1a-afe7645d03c5)

el mismo que se le pone en el usuario

![image](https://github.com/user-attachments/assets/89c49eae-d563-4e95-ae59-73616ac0e0da)

**Comment by EdwinBetanc0urt** [comment]
Cambios disponibles a partir de la versión del frontend `4.4.022`.

https://github.com/user-attachments/assets/594a467a-d6b3-4b58-bdb1-8f69b2fa04fa
