### ISSUE TITLE
Agregar Imagen al Usuario

### ISSUE THREAD

**Issue by elsiosanchez** [solop-develop/vue-1.0#1278]
### _**Screenshot**_

![image](https://github.com/solop-develop/frontend-core/assets/45974454/9c4a0235-29bd-45e4-bf52-adc34b85650c)

**Comment by EdwinBetanc0urt** [comment]
![image](https://github.com/solop-develop/frontend-default-theme/assets/45974454/b597cf47-2f75-4afe-bf76-e1191922522f)

**Comment by niclopup** [comment]
no se visualiza el avantar del usuario. el mismo que cargó el usuario como su foto. 

Se puede?

![image](https://github.com/user-attachments/assets/d69702d3-72ba-4386-9da6-be1ea58e6a7b)

**Comment by elsiosanchez** [comment]
https://github.com/solop-develop/frontend-core/pull/2851

**Comment by Ricargame** [comment]
Cambios disponibles partir de la versión del front https://github.com/solop-develop/frontend-core/releases/tag/4.4.020

https://github.com/user-attachments/assets/2649f075-a877-4fe2-abe6-1ff108cc612d
