### ISSUE TITLE
Issues > Formato Fecha de Siguiente Acción

### ISSUE THREAD

**Issue by elsiosanchez** [solop-develop/vue-1.0#1279]
### _**Screenshot**_

![image](https://github.com/solop-develop/frontend-core/assets/45974454/7bea3172-01e5-43d6-be67-8550b422d501)

![image](https://github.com/solop-develop/frontend-core/assets/45974454/8346331d-dae0-432b-9cdc-0c86b2417d87)

**Comment by EdwinBetanc0urt** [comment]
![image](https://github.com/solop-develop/frontend-default-theme/assets/45974454/b597cf47-2f75-4afe-bf76-e1191922522f)
