### ISSUE TITLE
Consulta Inteligente: Manejo > Eliminación de Registros

### ISSUE THREAD

**Issue by EdwinBetanc0urt** [solop-develop/vue-1.0#128]
Para eliminar un registro es necesario que la definición de la consulta inteligente tenga una tabla y este marcado como eliminable, y que tenga una selección de al menos registro de los resultados de la tabla.

**Comment by elsiosanchez** [comment]
Agregar soporte para eliminar registro desde las **_Consultas Inteligente (Smart Browser)_** 

![sb](https://user-images.githubusercontent.com/45974454/170362074-b9284da3-81a7-44fb-9c22-ef1799490f09.gif)


Solventado en el SIguiente PR #102

**Comment by EdwinBetanc0urt** [comment]
Cambios relacionados
https://github.com/solop-develop/backend/pull/15
https://github.com/solop-develop/gRPC-API/pull/3
https://github.com/solop-develop/proxy-adempiere-api/pull/2

**Comment by niclopup** [comment]
No se logra ver datos

https://user-images.githubusercontent.com/31936815/175383222-c904f2c1-3beb-4eaf-8196-03ad27184e12.mp4

**Comment by EdwinBetanc0urt** [comment]
Corregido en los cambios del pull request https://github.com/solop-develop/frontend-core/pull/201

**Comment by niclopup** [comment]
Ok, ahora si se ven las columnas y los datos. 

Gracias!

**Comment by niclopup** [comment]
No se logra eliminar registro desde SB

https://user-images.githubusercontent.com/31936815/179797434-f27e5972-8633-484e-a903-7ee3d98d6d8a.mp4

**Comment by EdwinBetanc0urt** [comment]
@niclopup debe establecerse una tabla en la definición del smart browser para que sepa en donde eliminará registros.

![Image](https://user-images.githubusercontent.com/20288327/179864597-ec47848c-d2f3-4d4f-9727-60a3e766848a.png)

Sin embargo se agregaron validaciones (https://github.com/solop-develop/backend/pull/36 y https://github.com/solop-develop/frontend-core/pull/263) para que no este habilitada la opción de eliminar registros hasta que este marcado el check de eliminable y la tabla en el smart browser



https://user-images.githubusercontent.com/20288327/179865204-aae36a4c-5386-4ea0-a03f-7c721913f9ea.mp4

**Comment by niclopup** [comment]
ok, gracias!

agregue la tabla e intenté eliminar el registro y aún no me permitió. 

![image](https://user-images.githubusercontent.com/31936815/179872341-69e84d37-6f56-4859-af5c-2b5b2ff1e89e.png)

![image](https://user-images.githubusercontent.com/31936815/179872399-aedd9ebe-cf40-41a3-91b5-b3512ec0de10.png)

No se como les parece de manejar en este caso. 

Si me preguntás, para darlo como entregado se debería verificar que definiendo correctamente se pueda permitir eliminar

Por otro lado el hecho de eliminar registros en adempiere nunca es muy simple, no se si queremos darle el soporte a eliminar desde un SB o no. 

De momento lo devuelvo y cualquier cosa hablamos

**Comment by EdwinBetanc0urt** [comment]
Ejecuta el proceso `Reinicia Cache` desde vue, para que el backend grpc limpie el cache cargado en su diccionario de aplicación y tome los cambios de la consulta inteligente, se agrego un "acceso rápido" en el menú del perfil de usuario.

![Screenshot_20220720_091641](https://user-images.githubusercontent.com/20288327/179992655-1595cf2c-ec67-4dd0-b4bb-7a0f0e7fa1af.png)

**Comment by niclopup** [comment]
ok

se verifica que permite borrar correctamente
