### ISSUE TITLE
Forma: Cargador de Archivos > Gestionar archivos subidos asociados al formato de importación.

### ISSUE THREAD

**Issue by EdwinBetanc0urt** [solop-develop/vue-1.0#1283]
En el zk/swing no existe una manera de ver que archivos fueron usados para importar los datos, sin embargo se agrega la opción a través de la gestión de adjuntos asociados al formato de importación, agregando previsualización luego de seleccionarlo.

https://github.com/solop-develop/frontend-core/assets/20288327/62a0e60a-3ad1-49ea-b0f1-45ff4437c56e

**Comment by niclopup** [comment]
No se logra importar ningún archivo al Cargador de Archivos.

**Comment by elsiosanchez** [comment]
Solventado en el siguiente PR https://github.com/solop-develop/frontend-core/pull/2598

**Comment by EdwinBetanc0urt** [comment]
Cambios disponibles a partir de la versión del backend https://github.com/solop-develop/adempiere-grpc-server/releases/tag/3.6.8 y del frontend https://github.com/solop-develop/frontend-core/releases/tag/4.3.2

https://github.com/user-attachments/assets/09214b22-bc3a-4ba6-9207-9a95d146446c

**Comment by niclopup** [comment]
se intenta cargar en el cargador de archivos cargar el archivo TSV: 

pero da el siguiente error:

![image](https://github.com/user-attachments/assets/f578dd65-9652-45e9-b12d-d789c637ac40)

![image](https://github.com/user-attachments/assets/0b76b27d-27f8-4cf3-9a61-f7d6a8c217bd)


se prueba con un CSV

[Carga Socios de Negocio Solop - CAC Producción - Importar SDN (CAC).csv](https://github.com/user-attachments/files/17441829/Carga.Socios.de.Negocio.Solop.-.CAC.Produccion.-.Importar.SDN.CAC.csv)


![image](https://github.com/user-attachments/assets/7b6359a9-d2e7-48fe-9f1a-a902a5992d68)


![image](https://github.com/user-attachments/assets/9a4ba80c-10ef-469f-bbea-7dc617be2b15)
