### ISSUE TITLE
Consulta Inteligente: Manejo > Edición de Registros

### ISSUE THREAD

**Issue by EdwinBetanc0urt** [solop-develop/vue-1.0#129]
Al tener un resultado en la tabla, y en la definición de la consulta inteligente se tiene una tabla y es editable, y en la definición de los campos están marcados como editables, al ser seleccionada la fila debe colocar dichos campos como editables y al pulsar el botón de actualizar deben cambiar los registros en la tabla definida en la consulta inteligente.

Version en Swing

https://user-images.githubusercontent.com/20288327/172236164-7facdcce-dfd8-4309-a8b2-004c2f6a8b5b.mp4

**Comment by niclopup** [comment]
No se logra ver datos en los SB

**Comment by EdwinBetanc0urt** [comment]
Corregido en los cambios del pull request https://github.com/solop-develop/frontend-core/pull/201

**Comment by niclopup** [comment]
no se logra replicar en VUE

https://user-images.githubusercontent.com/31936815/179800871-939abfbf-0fb9-4eeb-9feb-20cecb82cf5a.mp4


Tampoco se encuentra el botón de "Guardar" que muestran en Swing

![image](https://user-images.githubusercontent.com/31936815/179800846-88c35525-0550-4f04-906d-ea05f6dab79a.png)

**Comment by EdwinBetanc0urt** [comment]
En la definición de la consulta inteligente no estaba marcado el check de `Actualizable` para editar los registros.

![Screenshot_20220801_142706](https://user-images.githubusercontent.com/20288327/182219439-180c98cf-849b-42af-804b-e918b2a43c0b.png)

En la interfaz vue se debe dar doble clic sobre la fila editada para guardar el registro y editarlo, debe aparecer el mensaje `Registro Actualizado` notificando que el registro fue cambiado exitosamente.

https://user-images.githubusercontent.com/20288327/182220002-9406d411-fa5e-449c-b2c8-068ac8263612.mp4

**Comment by niclopup** [comment]
ok, se logra modifcar un registro desde un SB.

El único tema es que me parece raro que se guarde con un Doble Click sobre la línea.
