### ISSUE TITLE
Formulario: Conciliación de Estado de Cuenta > Listar Pagos con Coincidencia (Simular Conciliación).

### ISSUE THREAD

**Issue by EdwinBetanc0urt** [solop-develop/vue-1.0#1296]
![imagen](https://github.com/solop-develop/frontend-core/assets/20288327/6460f19e-e4f8-4a33-a0b3-3d7c75b40eff)

![imagen](https://github.com/solop-develop/frontend-core/assets/20288327/a09b333a-a6e5-48de-9226-48029c825cf0)

**Comment by niclopup** [comment]
Esto no está funcionando

**Comment by EdwinBetanc0urt** [comment]
![imagen](https://github.com/solop-develop/frontend-core/assets/20288327/249ecbbd-30a9-49ff-ad20-3dfb6d9ae53c)

**Comment by niclopup** [comment]
OK

![Match entre Movimiento y Pago y creación de Bankstatementline](https://github.com/solop-develop/frontend-core/assets/31936815/b860f418-f279-4bcb-9b3b-50070c764903)
