### ISSUE TITLE
Consulta Inteligente: Manejo > Ejecucion de Proceso

### ISSUE THREAD

**Issue by EdwinBetanc0urt** [solop-develop/vue-1.0#130]

**Comment by elsiosanchez** [comment]
Para ejecutar un proceso asociado a un Navegador Inteligente (Smart Browser) primero se debe seleccionar un registro luego dirigirse a la parte superior a la izquierda en el menú de acciones. seleccione el proceso llene los parámetros obligatorios y ejecute el proceso asociado


### Vista del Menú en Versión Escritorio ADempiere-Vue
![run-desktop-vue](https://user-images.githubusercontent.com/45974454/171046137-d2f7f910-8316-4f85-8c71-1b8a69ebc375.gif)

### Vista del Menú en Versión Móvil ADempiere-Vue
![run-mobile-vue](https://user-images.githubusercontent.com/45974454/171046147-3df4477f-3509-4e60-acaa-b56c01e69a13.gif)

**Comment by niclopup** [comment]
No se ven datos en SB

**Comment by EdwinBetanc0urt** [comment]
Corregido en los cambios del pull request https://github.com/solop-develop/frontend-core/pull/201

**Comment by niclopup** [comment]
No se logra ver el Campo de "Acción en el Documento" desde el PRoceso del SmartBrowser



![Image](https://user-images.githubusercontent.com/31936815/176008614-bbba9321-c07a-49eb-a890-bb16646ea552.png)



https://user-images.githubusercontent.com/31936815/176008664-23f518cb-61c5-4952-afe8-b8913dbb48ad.mp4

**Comment by EdwinBetanc0urt** [comment]
@niclopup Saludos esto ya fue solucionado y eventualmente actualizado en en https://vue-develop.solopcloud.com



https://user-images.githubusercontent.com/20288327/179261320-d7c5671d-85c0-4b77-bc34-af440285f15b.mp4

**Comment by niclopup** [comment]
Ok, se verifica que el SB "Procesar Ordenes en Lote" funciona bien.


https://user-images.githubusercontent.com/31936815/179802310-8edbd5a6-538f-417e-b8df-ac2bd89f1c5c.mp4
