### ISSUE TITLE
[Bug Report] Ajustar imagen al campo

### ISSUE THREAD

**Issue by elsiosanchez** [solop-develop/vue-1.0#1302]
#### Screenshot or Gif（截图或动态图）

![image](https://github.com/solop-develop/frontend-core/assets/45974454/bcc37c7b-87bf-45a0-963f-d80ab2e2f823)

**Comment by EdwinBetanc0urt** [comment]
duplicado con https://github.com/solop-develop/frontend-core/issues/1241
