### ISSUE TITLE
Formulario: Conciliación de Estado de Cuenta > Listar Cuentas Bancarias.

### ISSUE THREAD

**Issue by EdwinBetanc0urt** [solop-develop/vue-1.0#1308]
Listar la cuenta bancaria, considerando que es el único campo obligatorio para las operaciones.

https://github.com/solop-develop/frontend-core/assets/20288327/dac53912-e529-4bdb-81ce-f83b083c4672

https://github.com/solop-develop/frontend-core/assets/20288327/c73d71d7-da1e-4661-856a-3cd7578775f4

**Comment by niclopup** [comment]
están cómo sólo lectura así q no aplica
