### ISSUE TITLE
Paginación no funciona 

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#1310]
## Bug report

Se intenta cambiar de 15 registros a 50 pero no cambia la ventana y no se ven los demás registros.

![image](https://github.com/solop-develop/frontend-core/assets/31936815/76d14671-8c12-4283-985f-9bf916b8b3d9)

**Comment by elsiosanchez** [comment]
![ERROR](https://github.com/solop-develop/frontend-core/assets/45974454/bea0a7a5-178d-4872-b531-b28da46c6024)
