### ISSUE TITLE
No se ven productos desde Línea de OV

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#1311]
## Bug report

Se intenta agregar un producto en la línea de una OV pero no se visualiza ningun producto de los definidos en la lista de precios.

Ver ejemplo de OV 50019

![image](https://github.com/solop-develop/frontend-core/assets/31936815/1ca8c395-75a2-4a1d-be2f-8a9ead253e11)

**Comment by EdwinBetanc0urt** [comment]
Funciona correctamente en https://vue-develop.solopcloud.com

https://github.com/solop-develop/frontend-core/assets/20288327/ae0e1460-945b-4bf8-baa8-ba1168c9c117


existen pasos adicionales para replicar?
