### ISSUE TITLE
[Bug Report] Forma: Asignación de Pagos: Definir la Organización

### ISSUE THREAD

**Issue by elsiosanchez** [solop-develop/vue-1.0#1314]
> ## _**Bug Report**_
> **Organización Obligatoria**
>
> Organización obligatoria pese a que no haya diferencia. En este caso en ZK no pide que vuelvas a definir la organización en  cada asignación. Si no hay diferencia no es necesaria por que ya la definiste en el filtro inicial, se debe tomar dicha organización
> ### _**Screenshot or Gif**_
>![image](https://github.com/solop-develop/frontend-core/assets/31936815/52909f5f-ba2d-42b6-a7c7-f73f6c6a4a74)
>

**Comment by niclopup** [comment]
por defecto abre vacio el campo de Organización y no trae ningún registro. Si está vacío debería traer todo sin filtrar como si fuese Organización *.

Creo que lo mejor igual sería que por defecto te defina la organización logueada en el contexto así se evita un check 

![Asignación de pagos - Organización vacia no trae registros 2](https://github.com/solop-develop/frontend-core/assets/31936815/2c5bfe09-85b0-4a26-b604-b966085d4dc1)


![Asignación de pagos - Organización vacia no trae registros](https://github.com/solop-develop/frontend-core/assets/31936815/87042fbc-dcad-4e69-83e4-cf651f67137b)

**Comment by Ricargame** [comment]
cambios disponibles a partir de la versión https://github.com/solop-develop/frontend-core/releases/tag/4.0.7


https://github.com/solop-develop/frontend-core/assets/78000356/76db7a06-7f2a-4aeb-aba7-86032c47e843
