### ISSUE TITLE
[Bug Report] Forma: Asignación de Pagos: Acción (Procesar Asignacion)

### ISSUE THREAD

**Issue by elsiosanchez** [solop-develop/vue-1.0#1315]
> ## _**Bug Report (Acción) **_
>
> Se seleccionan un pago y una DxP que suman diferencia 0 pero al hacer click en el check no realiza ninguna acción. No genera asignación alguna pese a que da un resultado como que lo realizó.
>
>### _**Screenshot or Gif**_
>![image](https://github.com/solop-develop/frontend-core/assets/45974454/6b5af9a5-f018-4b0b-8b61-5435f96f3d7f)
>

**Comment by niclopup** [comment]
ok
