### ISSUE TITLE
Consulta Inteligente: Documentación > Caso de Uso

### ISSUE THREAD

**Issue by EdwinBetanc0urt** [solop-develop/vue-1.0#132]

**Comment by elsiosanchez** [comment]
Se creo una documentacion para el Caso de Uso  de la  _**Consulta Inteligente (Smart Browser) **_  en ingles y español
![caso-use-sb](https://user-images.githubusercontent.com/45974454/171046984-391162b1-e306-4390-b81a-151e37303833.gif)

**Comment by EdwinBetanc0urt** [comment]
https://solop-develop.github.io/frontend-core/guide/use-cases/smartBrowser.html
