### ISSUE TITLE
Error al definir PIN del usuario en el POS

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#1321]
## Bug report
Se intenta aplicar un descuento pero antes pide PIN del usuario para aplicar el descuento.

Se define el PIN pero da el siguiente error:

org.postgresql.util.PSQLException: ERROR: error de sintaxis al final de la entrada Position: 388, SQL=SELECT AD_User_ID FROM AD_User WHERE ((EXISTS( SELECT 1 FROM C_POSSellerAllocation AS seller WHERE seller.C_POS_ID = ? AND seller.SalesRep_ID = AD_User.AD_User_ID AND seller.IsActive = 'Y' AND seller.IsAllowsPOSManager = 'Y' AND seller.IsAllowsModifyDiscount= 'Y' AND (seller.MaximumLineDiscountAllowed >= ? OR seller.MaximumLineDiscountAllowed = 0)) AND UserPIN = ? ) AND IsActive=?

![Error PIN de Usuario](https://github.com/solop-develop/frontend-core/assets/31936815/caccd9c1-582a-4a08-9554-561e5a59a30d)

#### Screenshot or Gif（截图或动态图）
![POS Error Pin de Usuario](https://github.com/solop-develop/frontend-core/assets/31936815/3800b04d-2414-40da-a6f7-55a39308a11d)

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:

**Comment by EdwinBetanc0urt** [comment]
Esto fue corregido en el backend.
