### ISSUE TITLE
Formulario: Abrir desde un proceso asociado a la pestaña.

### ISSUE THREAD

**Issue by EdwinBetanc0urt** [solop-develop/vue-1.0#1325]
Actualmente existen formularios que se asocian en los procesos de la pestaña, se requiere dar soporte, y enviar el ID del registro hacia el formulario.

https://user-images.githubusercontent.com/20288327/260887632-156cb0b8-7273-4ba9-8907-73da3309a7d4.mp4

**Comment by EdwinBetanc0urt** [comment]
En el menú de procesos asociados se agrega con el icono que distingue cuando es un formulario del menú principal

![imagen](https://github.com/solop-develop/frontend-core/assets/20288327/b6558f23-c902-4335-b9ed-8843cc0f0fb9)

https://github.com/solop-develop/frontend-core/assets/20288327/c658615f-771f-487b-897d-61379f7ffa13

**Comment by niclopup** [comment]
Se intenta repetir ejemplo y no abre ninguna ventana. Queda página en blanco

https://github.com/solop-develop/frontend-core/assets/31936815/7bc90548-efb2-4d61-852c-aa7905dbe9b3

**Comment by Ricargame** [comment]
Cambios disponibles apartir de la versión: https://github.com/solop-develop/frontend-core/releases/tag/4.0.3

https://github.com/solop-develop/frontend-core/assets/78000356/53100af9-0eca-4380-8c3b-6d101eb175c5
