### ISSUE TITLE
Consulta Inteligente: Documentación > Componente

### ISSUE THREAD

**Issue by EdwinBetanc0urt** [solop-develop/vue-1.0#133]

**Comment by elsiosanchez** [comment]
Se creo una documentacion para el componente de _**Consulta Inteligente (Smart Browser) **_  en ingles y español
![sb](https://user-images.githubusercontent.com/45974454/171046920-f133dcaa-bc60-47d5-80b1-c77e8e8878a0.gif)

**Comment by EdwinBetanc0urt** [comment]
https://solop-develop.github.io/frontend-core/guide/components/smart-browser.html
