### ISSUE TITLE
POS Registro de Socio de Negocio: Tipo de Contribuyente y Email

### ISSUE THREAD

**Issue by MarianaGallardo** [solop-develop/vue-1.0#1330]
Se registra el socio de negocio: **Mariana** y se configura seleccionando el tipo de contribuyente y se coloca el correo electrónico, se procede a guardar. A chequear, en ZK guarda la información y se visualiza, sin embargo, en la UI no queda la información, no se visualiza.

**Comment by EdwinBetanc0urt** [comment]
https://github.com/solop-develop/frontend-core/assets/20288327/fd96f212-51ac-4ea7-bb44-26d2a7c72fc6
