### ISSUE TITLE
POS: Retención con Organización Errada

### ISSUE THREAD

**Issue by wdtz** [solop-develop/vue-1.0#1331]
Se ingresa al sistema con usuarioAU y se coloca organización Austral, al entrar al PDV seleccione caja 01 Boleita.
El resultado de esta prueba al hacer una ov y cobrarla en dólares y generar igtf es que la retención queda con la organización del contexto

**Comment by EdwinBetanc0urt** [comment]
[organización-errada-en-retención.webm](https://github.com/solop-develop/frontend-core/assets/20288327/1fd2c7bd-311d-4630-9d81-d22614e3826d)
