### ISSUE TITLE
POS: Validar Disponibilidad

### ISSUE THREAD

**Issue by wdtz** [solop-develop/vue-1.0#1335]
Al crear una orden de venta con un producto cuya disponibilidad es 0 deja generar la orden y la factura.

Ejemplo:
El producto CAR1100I81J510150  tiene disponibilidad 0 y deja generar la orden de venta sin generar error.

![imagen](https://github.com/solop-develop/frontend-core/assets/20288327/faeddb01-1569-4c60-8960-3750bc7462fc)

**Comment by EdwinBetanc0urt** [comment]
[validate-avalability.webm](https://github.com/solop-develop/frontend-core/assets/20288327/3b85a64b-1029-459e-97f9-1291eede77bb)
