### ISSUE TITLE
Proceso: Carga > Validaciones Dinámicas

### ISSUE THREAD

**Issue by EdwinBetanc0urt** [solop-develop/vue-1.0#134]
Abrir el proceso `Transferencia Bancaria`.

* Listar los valores del campo `Cuenta Bancaria desde`.
* Seleccionar un valor.
* Listar los valores del campo `Cuenta Bancaria a Transferir`, y verificar que el valor seleccionado en el campo anterior esta excuildo del resultado.

https://user-images.githubusercontent.com/20288327/171196439-82ec9e5c-1360-4300-a3fb-5a3cae7ed8ae.mp4

**Comment by EdwinBetanc0urt** [comment]
Caso de uso disponible en la documentación:
https://solop-develop.github.io/frontend-core/guide/use-cases/process.html#dynamic-validations

https://user-images.githubusercontent.com/20288327/171196680-3c0a6158-973e-4ffb-a1fe-7ff582931b78.mp4

**Comment by niclopup** [comment]
Se verifica correcto el funcionamiento
