### ISSUE TITLE
POS: Error en Campaña

### ISSUE THREAD

**Issue by wdtz** [solop-develop/vue-1.0#1340]
Al crear una orden de venta indica que no tiene campaña aún cuando si lo tiene asignado el pdv, por otro lado, al listarlo muestra campañas inactivas(Ver GIF)
Al crear la orden lo establece en el encabezado, pero no en las lineas, lo cual trae problemas al consultar el detalle de factura y margen.

![Image](https://github.com/solop-develop/frontend-core/assets/20288327/0b59883e-4e14-4a43-a66d-b627c868b67d)

**Comment by EdwinBetanc0urt** [comment]
https://github.com/solop-develop/frontend-core/assets/20288327/406fd1d0-7501-4e43-852f-09d7e27a0f06
