### ISSUE TITLE
POS: Error al Realizar Reembolso (mensaje de alerta de N de Cuenta)

### ISSUE THREAD

**Issue by jaur25** [solop-develop/vue-1.0#1345]
Buenas Tardes, al momento de realizar un reembolso de una factura selecciono, que el reembolso sera de manera efectivo, aparece un mensaje de error solicitando numero de cuenta bancaria, pero luego de arrojar el mensaje agrega el reembolso seleccionado. 

![image](https://github.com/solop-develop/frontend-core/assets/132361717/1530aac0-ed4d-4cb8-b5d3-431c63c2340f)

![image](https://github.com/solop-develop/frontend-core/assets/132361717/f4388307-16b6-4f5e-b595-ce534ba1a2fa)

**Comment by EdwinBetanc0urt** [comment]
[refund-fix.webm](https://github.com/solop-develop/frontend-core/assets/20288327/ed548897-02fb-4d62-a29e-be33955c52cd)
