### ISSUE TITLE
POS: Error al cambiar el tipo de documento con PIN

### ISSUE THREAD

**Issue by jaur25** [solop-develop/vue-1.0#1349]
Hola Cuando se configura en el punto de venta para cambiar el tipo de documento con PIN no lo cambia aún cuando dice que si lo cambia.

![document-type-with-pin-error](https://github.com/solop-develop/frontend-core/assets/20288327/f33d9a40-5679-46d3-8077-7be1d50fc2dc)

**Comment by EdwinBetanc0urt** [comment]
Corregido

[document-type-with-pin-fixed.webm](https://github.com/solop-develop/frontend-core/assets/20288327/1444b001-17e5-4e94-84b3-ce83a29d143f)
