### ISSUE TITLE
Reporte: Apertura > Asociado a Ventana

### ISSUE THREAD

**Issue by EdwinBetanc0urt** [solop-develop/vue-1.0#135]
Se deben abrir los reportes asociados a la ventana similar a los procesos.

1. Abrir la ventana `Informe Financiero`.
2. Dar clic en el botón de con icono engranaje en la parte superior a la derecha para listar procesos asociados en la ventana.
3. Seleccionar `Crear Reporte`, se mostraran los parámetros del reporte asociado.

https://user-images.githubusercontent.com/20288327/171212286-a088ddab-31ad-430a-8584-9323deff4ac1.mp4

- [x] #689

**Comment by EdwinBetanc0urt** [comment]
En la interfaz vue esta soportada esta funcionalidad, los reportes asociados se visualizan en el menú de acciones (de color azul) en la parte superior a la derecha, cabe destacar que a diferencia de la interfaz zk, se tienen iconos en la lista de reportes/procesos asociados para que el usuario lo relacione de manera mas sencilla.

Para el caso de los reportes el icono es el siguiente:

![Image](https://user-images.githubusercontent.com/20288327/171214075-fe77433d-933e-4afd-a9ff-e6db7862b7ea.png)


Pasos para reproducir:


https://user-images.githubusercontent.com/20288327/171212978-5742adaf-32a7-4191-a76e-82cc1f939230.mp4

**Comment by niclopup** [comment]
Se intenta verificar pero no se logra ver bien la ventana de "Informe Financiero"

Entiendo que cuando se entregue las ventanas se podrá validar correctamente esta issue. 

![image](https://user-images.githubusercontent.com/31936815/174896835-7b2c2fb5-c4af-452c-a20f-3588c4d8507e.png)

**Comment by EdwinBetanc0urt** [comment]
Corregido en los cambios del backend https://github.com/solop-develop/backend/pull/27
