### ISSUE TITLE
Columna de Actividad no se ve desde Asiento de un Documento desde VUE

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#1351]
## Bug report

Se genera una distribución contable en un documento que distribuye la dimensión "Actividad". La distribución de aplica correctamente y se reparte según lo definido, pero el problema es que el asiento que se ve bien desde ZK con la dimensión (Columna) Actividad, no se visualiza en la grilla del asiento desde VUE.

#### Steps to reproduce
![No se ve columna  Actividad  en Asiento desde un Documento en VUE](https://github.com/solop-develop/frontend-core/assets/31936815/42076ac1-c5d4-4f9d-8828-7885d5752020)

![image](https://github.com/solop-develop/frontend-core/assets/31936815/6327befa-b3fc-428a-8c0a-cdf2af8acf95)

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:

**Comment by EdwinBetanc0urt** [comment]
Que criterio o configuración se utiliza para mostrar la columna `Actividad`?

**Comment by EdwinBetanc0urt** [comment]
![image](https://github.com/solop-develop/frontend-core/assets/20288327/014d7eef-cef6-4b06-96d6-d3a235f21461)


![image](https://github.com/solop-develop/frontend-core/assets/20288327/1648f7a3-7f26-428c-a021-bebf703ca97c)
