### ISSUE TITLE
Formulario: Solicitudes > No establece valores por defecto al crear uno nuevo

### ISSUE THREAD

**Issue by EdwinBetanc0urt** [solop-develop/vue-1.0#1354]
Al seleccionar el `Tipo de Solicitud`, debe seleccionar el `Estatus` predeterminado establecido en el tipo de solicitud o en su defecto establecer el primero, la `Prioridad` debe estar en `Media`, y en `Asignado` colocar por defecto el usuario de la sesión.

**Comment by niclopup** [comment]
al definir un tipo de solicitud no define automáticamente ningun campo

**Comment by Ricargame** [comment]
Cambios disponibles apartir de la versión: https://github.com/solop-develop/frontend-core/releases/tag/4.0.3

https://github.com/solop-develop/frontend-core/assets/78000356/6e0df8c1-3585-4c2b-8d5e-f1bfcbdc04e7
