### ISSUE TITLE
POS: Permite agregar cobro en "0".

### ISSUE THREAD

**Issue by jaur25** [solop-develop/vue-1.0#1356]
Permite agregar un cobro en "0", aun así ya se agregara el cobro completo de la factura y por el ZK aparece registrado el cobro en 0 en cobro.

![image](https://github.com/solop-develop/frontend-core/assets/132361717/66453155-6171-4561-a186-3da58ecdd255)

![image](https://github.com/solop-develop/frontend-core/assets/132361717/f14be943-28b9-4a34-b4eb-004f55a592b8)

**Orden de Venta: OVT-14762**

**Comment by EdwinBetanc0urt** [comment]
corregido y duplicado con https://github.com/solop-develop/frontend-core/issues/1357


[cobro-en-cero-corregido.webm](https://github.com/solop-develop/frontend-core/assets/20288327/7c7b2273-6653-481b-adcd-988ebf59dc0b)
