### ISSUE TITLE
POS: Permite Agregar Cobros en Cero

### ISSUE THREAD

**Issue by jaur25** [solop-develop/vue-1.0#1357]
El problema es que permite que se agreguen cobros en cero, para hacer esta prueba se debe tomar en cuenta lo siguiente en el ambiente:

**No debe existir una tasa a la fecha**

**Los pasos a seguir son:**
**Cree un pedido**
**Agregue una línea: ARG1012L85CH71010**
**Agregue un Cobro: Note que el cobro lo agregué en ZELLE-USD**

![Permite_Agregar_Pago_En_Cero](https://github.com/solop-develop/frontend-core/assets/20288327/0e19c9d9-33a8-43d0-bc65-d279e7e90e40)

**Comment by EdwinBetanc0urt** [comment]
Corregido

[cobro-en-cero-corregido.webm](https://github.com/solop-develop/frontend-core/assets/20288327/fcc75f1e-5cce-4c14-9488-f090fa09f661)
