### ISSUE TITLE
POS: Deja completar Facturas sin Cobro

### ISSUE THREAD

**Issue by jaur25** [solop-develop/vue-1.0#1358]
Al crear una orden de venta sin cobro y se trata de ajustar no crea el ajuste y queda la factura abierta.

![payment-without-collet-error](https://github.com/solop-develop/frontend-core/assets/20288327/8c48939b-4983-4842-bdf0-4e22cfc4b131)

**Comment by EdwinBetanc0urt** [comment]
Corregido

[invoice-without-collet-fixed.webm](https://github.com/solop-develop/frontend-core/assets/20288327/067966de-b703-4b47-9453-455fc97aa29d)
