### ISSUE TITLE
POS: Referencia de pago con Diferente Organización 

### ISSUE THREAD

**Issue by jaur25** [solop-develop/vue-1.0#1361]
La referencia de pago está quedando con diferencia de organización
 
![imagen](https://github.com/solop-develop/frontend-core/assets/20288327/76fa90a5-66a2-4765-9ef9-a2f0cb17eefc)

**Comment by EdwinBetanc0urt** [comment]
![imagen](https://github.com/solop-develop/frontend-core/assets/20288327/422f1403-ad13-4cf1-b712-d8a1f6917e3d)
