### ISSUE TITLE
POS: Info de entrega Completa

### ISSUE THREAD

**Issue by jaur25** [solop-develop/vue-1.0#1363]
Al dar clik en información se genera el siguiente error:

![image](https://github.com/solop-develop/frontend-core/assets/132361717/665eab34-2e71-4c0a-8f1d-9ad4149bde6c)

**Comment by EdwinBetanc0urt** [comment]
![imagen](https://github.com/solop-develop/frontend-core/assets/20288327/8845fa62-8b81-40d8-bf8c-e3e2b5e887c0)
