### ISSUE TITLE
POS: Recalculo de m2 a Caja en Entrega

### ISSUE THREAD

**Issue by jaur25** [solop-develop/vue-1.0#1364]
Al tratar de entregar en la opción entregar completo muestra las cantidades en M2 pero al colocar la cantidad en m2 re-calcula a caja

![Image](https://github.com/solop-develop/frontend-core/assets/20288327/9e05713d-7dd9-409a-a20c-15fb0188bbca)

**Comment by EdwinBetanc0urt** [comment]
![Image](https://github.com/solop-develop/frontend-core/assets/20288327/456a7e20-06e1-4dab-9e26-98c4ffaca36b)
