### ISSUE TITLE
[Bug Report] Entrada de Morosidad no pasa correctamente parámetro a proceso

### ISSUE THREAD

**Issue by rcapecce** [solop-develop/vue-1.0#1366]
## Bug report

Se encuentra que en la ventana Cálculo de Morosidad, en la entrada, al ejecutar en determinados casos llamar a un proceso de impresión, el mismo no pasa correctamente el parámetro que recibe.

**Comment by EdwinBetanc0urt** [comment]
Corregido

https://github.com/solop-develop/frontend-core/assets/20288327/352816a1-b650-40c6-b9f9-271685023a0a

**Comment by niclopup** [comment]
quedo resuelto. gracias!
|
