### ISSUE TITLE
[Bug Report] POS Al poner foco en Tarjeta de Crédito no logra encontrar referencia por UUID

### ISSUE THREAD

**Issue by rcapecce** [solop-develop/vue-1.0#1368]
## Bug report

En POS, al momento de agregar medio de pago, y seleccionar como "Método de Pago" "Tarjeta de Crédito", se completan campos de Banco, Teléfono y al poner foco en campo "Tarjeta de Crédito" no logra encontrar por UUID la columna ingresada.

Se detecta en backend que el UUID pasado como AD_Field en realidad es un UUID de AD_Element

![image](https://github.com/solop-develop/frontend-core/assets/14218144/73ef2e89-9932-453a-aa17-a851929972e4)

**Comment by EdwinBetanc0urt** [comment]
Corregido


![ERROR](https://github.com/solop-develop/frontend-default-theme/assets/45974454/71e024c6-1f4e-4aa3-a4bf-6ef1e342abdb)
