### ISSUE TITLE
Error al Asignar Fecha

### ISSUE THREAD

**Issue by elsiosanchez** [solop-develop/vue-1.0#1371]
> Se logra generar una asignación correctamente
> 
> El único detalle que encontré es un tema con la fecha: 
> 
> 1. faltaría un Callout (o no se exactamente que es) que en ZK se actualiza automáticamente la Fecha definida según la máxima fecha de los documentos que se vayan seleccionando. ahora no puedo hacer gif para mostrles peromañana les paso.
> 
> ![Al seleccionar una Factura cambia automáticamente la fecha](https://github.com/solop-develop/frontend-core/assets/31936815/9bdddc78-7c17-4bd7-86a5-5555dc34d258)
![Control fecha automático](https://github.com/solop-develop/frontend-core/assets/31936815/3ce74196-2849-4ad1-92c0-7204b874503b)
> 
> 2. la fecha que se define por alguna razón al digitarla manualmente, la fecha que se ve se considera el día anterior y no la fecha definida,. por esta razón se debe poner una fecha del día siguiente a la de los documentos y no la fecha del día exacto de los documentos como debería ser

**Comment by EdwinBetanc0urt** [comment]
Ambos puntos de la asignación de pago estan listos para pruebas

**Comment by niclopup** [comment]
OK
