### ISSUE TITLE
Tableros en formato GAUGE

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#1376]
## Feature request

- Tableros en formato GAUGE

https://echarts.apache.org/examples/en/editor.html?c=gauge-grade

Todos los objetivos de desempeño en la página de inicio se deberán ver cómo Gauge.

Si se desea ver la gráfica se deberá ir a la págian de "Panel de Control".

https://echarts.apache.org/examples/en/editor.html?c=gauge-grade

**Comment by elsiosanchez** [comment]
https://github.com/adempiere/adempiere-dashboard-improvements/pull/9

![image](https://github.com/solop-develop/frontend-core/assets/45974454/f5abc148-a8b1-42b3-82f7-9943bc140b42)
