### ISSUE TITLE
[Bug Report] Abrir tabla en las ventanas informativas

### ISSUE THREAD

**Issue by elsiosanchez** [solop-develop/vue-1.0#138]
## Bug report
Al Abrir la tabla de navegaccion de registro en la ventanas de informacion no se pueden ver los registro
#### Steps to reproduce

1. Abra la ventana **Información de Socio del Negocio**
2. Abra la Tabla de navegaccion de registro
3. Observe el error 

#### Screenshot or Gif（截图或动态图）
![Error](https://user-images.githubusercontent.com/45974454/171661677-5a42daa9-740e-4c0c-bf45-7e6eb1d0f6b9.gif)

#### Other relevant information
- Your OS: Kubunto
- Web Browser: Chrome
- Node.js version: v 14.0.0

**Comment by EdwinBetanc0urt** [comment]
fixes with https://github.com/solop-develop/frontend-core/pull/156/files#diff-e74573655f3f0695eda4593eb85472baf2dbbbff6997444fa386b4e659b52c46L70

![Screenshot_20220613_094933](https://user-images.githubusercontent.com/20288327/173368441-7dca90e7-ac5c-47b2-850f-a441a6c1441d.png)
