### ISSUE TITLE
Agregar Createdby y UpdatedBy en auditoría de Registros

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#1389]
## Feature request

Se debe dejar igual a la información que actualmente se cuenta en ZK que es de gran utilidad.

Ahora faltan los campos de "CreatedBy" y "UpdatedBy"

![image](https://github.com/solop-develop/frontend-core/assets/31936815/a178f099-eb77-4793-856e-f5cf656aa1a7)

![image](https://github.com/solop-develop/frontend-core/assets/31936815/302e3f40-d0a0-4dc4-a2e6-62b2d92e59ea)

**Comment by EdwinBetanc0urt** [comment]
![2023-11-10_15-31](https://github.com/solop-develop/frontend-core/assets/20288327/cb89f6e8-471e-4f6f-a7e0-2e27974c5c4e)

**Comment by niclopup** [comment]
En transcoding puede ser que se hay vuelvo a modificar esto?

No vel el CreatedBY ni el Updated cuando un registro es creado.

![image](https://github.com/solop-develop/frontend-core/assets/31936815/5e88499b-473d-47c5-929e-ce6f84c88ab8)

Analizando esto veo que sucede sólo con registros nuevos creados. se modifican y luego no se ven nada de la auditoría de cambios

![image](https://github.com/solop-develop/frontend-core/assets/31936815/6b10bacf-28f3-4720-b6e8-f21d4fc87d3b)

![Auditoría de registro en ventana no muestra creado](https://github.com/solop-develop/frontend-core/assets/31936815/f8eb563c-e5e8-4492-a346-6fb3d07ad460)

**Comment by EdwinBetanc0urt** [comment]
Se deben actualizar las instancias, ya que existen correcciones en el log

![imagen](https://github.com/solop-develop/frontend-core/assets/20288327/252a85a2-72bb-4e3c-b947-f6736a93aa90)
