### ISSUE TITLE
Error al intentar abrir SmartBrowser Procesar órdenes en Lote

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#1391]
## Bug report

![image](https://github.com/solop-develop/frontend-core/assets/31936815/eed861e7-34a1-4885-886c-149cde080a4c)

![image](https://github.com/solop-develop/frontend-core/assets/31936815/293da8fd-3fae-418b-bcd8-769ab7d960cb)

pasa lo mismo con el SB "Consultas de órdenes"

![image](https://github.com/solop-develop/frontend-core/assets/31936815/eefe1db7-18eb-48f3-837c-c42939f0d4de)

![image](https://github.com/solop-develop/frontend-core/assets/31936815/f5e5cc0e-8d54-4bb4-b3ee-769edd3b68db)

#### Steps to reproduce

1. [xxx]
2. [xxx]
3. [xxxx]

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:

**Comment by EdwinBetanc0urt** [comment]
La sesión se expiro, debes iniciar sesión nuevamente!
