### ISSUE TITLE
[Bug Report] Ventana no muestra columnas SQL

### ISSUE THREAD

**Issue by rcapecce** [solop-develop/vue-1.0#1393]
## Bug report

Se habla con Edwin y muestra que la ventana Bandeja CFE tiene unas columnas SQL que no se están sumarizando en el cabezal.

Se proporciona base de testing para que pueda replicar localmente.

#### Steps to reproduce

Abrir con vue la ventana de Bandeja CFE, constatar que muestra 0 la cantidad de registros
Abrir con zk la Ventana de Bandeja CFE, constatar que muestra cantidades diferentes de 0 para diferentes registros.

#### Screenshot or Gif（截图或动态图）

![image](https://github.com/solop-develop/frontend-core/assets/14218144/52fdd04c-71dd-4627-88de-bd02b320621e)

![image](https://github.com/solop-develop/frontend-core/assets/14218144/5158cd4c-9b9d-41a4-8944-f7549ede27f5)

**Comment by EdwinBetanc0urt** [comment]
![imagen](https://github.com/solop-develop/adempiere-grpc-server/assets/20288327/c7ddb23b-f5fa-49e5-aeed-53d39afaeb5f)
