### ISSUE TITLE
POS: No realiza la Búsqueda en Consulta de Precio

### ISSUE THREAD

**Issue by jaur25** [solop-develop/vue-1.0#1394]
Al momento de realizar la búsqueda de un producto queda allí procesando y no realiza la búsquedas del mismo

![image](https://github.com/solop-develop/frontend-core/assets/132361717/ce2e472f-fd9b-42ce-beb7-7545c7e2b5e3)

**Comment by EdwinBetanc0urt** [comment]
![imagen](https://github.com/solop-develop/frontend-core/assets/20288327/fa6010d9-e319-452a-8e63-c8a7e8cc90fa)
