### ISSUE TITLE
POS: Listar Propuestas

### ISSUE THREAD

**Issue by jaur25** [solop-develop/vue-1.0#1395]
No se están visualizando las órdenes de ventas tipo propuestas, tomando en cuenta que estas tienen como Sub tipo ov:  Propuesta (DocSubTypeSO=ON) Cotización (DocSubTypeSO=OB)

**Comment by EdwinBetanc0urt** [comment]
![imagen](https://github.com/solop-develop/frontend-core/assets/20288327/848d130b-99fb-4724-acd2-ebe071d0181b)
