### ISSUE TITLE
[Feature Request] Parametrizar interfaz POSTicketHandler para obtención del PDF ticket al completar OV en el POS

### ISSUE THREAD

**Issue by rcapecce** [solop-develop/vue-1.0#1396]
## Feature request

Actualmente se cuenta con POSTicketHandler.printTicket() para programar como se va a imprimir el ticket.

Se requiere otro método en POSTicketHandler para indicar de donde se obtiene el PDF.
Si es de forma estandar, entonces como se hace ahora desde el proceso de la Orden o de la Factura.
Sin embargo nosotros también obtenemos el PDF desde nuestro Proveedor de Facturacón Electróncia.

#### Describe the solution you'd like

Se requiere poder programar un método en POSTicketHandler que permita retornar un PDF, tanto de forma tradiccional, programado desde la case abstracta, como desde una implementación que valla al WebService u otra forma.

Ese método, posteriormente será llamado tanto desde el Preview para mostrar por pantalla el ticket, como desde el método de impresión.

Adicionalmente se requiere que al Completar al OV y DxC, se realice la previsualización del DxC en el POS (una pestaña nueva de VUE)

**Comment by yamelsenih** [comment]
Hola, eso ya se tiene cubierto con el servicio de printTicket. Por favor revisa el ejemplo y el `PrintTicketResult`

**Comment by EdwinBetanc0urt** [comment]
Quizás deba agregarse la clase de "Previsualización de Ticket".

![image](https://github.com/solop-develop/frontend-core/assets/20288327/b190e308-1fed-4dc5-9676-030a820bff3b)


> Adicionalmente se requiere que al Completar al OV y DxC, se realice la previsualización del DxC en el POS (una pestaña nueva de VUE)

Para este punto creo que serviría un check que indique si se desea pre-visualizar luego de imprimir asi al mandar la impresión se visualizaría el archivo en vue.

**Comment by EdwinBetanc0urt** [comment]
![error](https://github.com/solop-develop/frontend-default-theme/assets/45974454/60c0177c-c984-4ee4-9594-5e792be2e109)
