### ISSUE TITLE
Proceso: Manejo > Validación

### ISSUE THREAD

**Issue by elsiosanchez** [solop-develop/vue-1.0#14]
Para la ejecución del proceso debe cumplir todas las validaciones. Para no mandar una petición al servidor que pueda dar error por una validación que lo permitió el front-end

**Comment by elsiosanchez** [comment]
Como se puede apreciar se valida en el Frond-End que no se puedan ejecutar los procesas hasta que llene todos los campos obligatorios. También ahorra un mensaje descriptivo con los campos que falta por llenar para que pueda ejecutarse el proceso 

### GIF
![validation](https://user-images.githubusercontent.com/45974454/166939330-9e134112-c888-4dfe-930e-909fe681c9ce.gif)

**Comment by elsiosanchez** [comment]
https://github.com/solop-develop/frontend-default-theme/pull/3

**Comment by EdwinBetanc0urt** [comment]
Para el caso de uso de pruebas ver:
https://solop-develop.github.io/frontend-core/es/guide/use-cases/process.html#validacion
