### ISSUE TITLE
POS: Permite hacer una devolución de un pedido en borrador

### ISSUE THREAD

**Issue by jaur25** [solop-develop/vue-1.0#1400]
Permite hacer una devolución de un pedido en borrador
Paso a paso:
Crear un pedido nuevo
Agregar un producto
Ir a la opción Orden de Venta -> Anular Transacción de Ventas
Confirmar

Al hacer esto se intenta hacer una devolución y deja el documento en proceso.
![Permite_Devolver_Orden_Borrador](https://github.com/solop-develop/frontend-core/assets/132361717/967aa43e-a14e-468a-b0b2-c07b07470751)

**Comment by EdwinBetanc0urt** [comment]
El botón no está habilitado cuando es una orden en borrador

![imagen](https://github.com/solop-develop/frontend-core/assets/20288327/7c766976-7454-461a-93d6-5ccad08f0a0f)

![imagen](https://github.com/solop-develop/frontend-core/assets/20288327/8718aa26-3d1f-44f4-aaac-6fb813cb37ba)
