### ISSUE TITLE
POS: Cantidad de Disponibilidad en Búsqueda de Producto

### ISSUE THREAD

**Issue by jaur25** [solop-develop/vue-1.0#1403]
Al momento de realizar la búsqueda de un producto en el buscador, sale refleja es la cantidad la cantidad de Existencia mas no la cantidad disponible como debería. Anexo Capt de Ejemplo.

![image](https://github.com/solop-develop/frontend-core/assets/132361717/e6929d59-dae6-434d-b8ce-6c67c829e867)

![image](https://github.com/solop-develop/frontend-core/assets/132361717/80c4d808-5869-43b8-aaac-321fac6202e8)

![image](https://github.com/solop-develop/frontend-core/assets/132361717/d61a6e22-e7e1-4abb-b44a-a436543182b0)

**Comment by EdwinBetanc0urt** [comment]
![imagen](https://github.com/solop-develop/frontend-core/assets/20288327/8544d1a9-3fc8-469b-9b85-bab3941407c9)

![imagen](https://github.com/solop-develop/frontend-core/assets/20288327/efeda6ef-56a1-4dd8-9d26-264c889564ec)

![imagen](https://github.com/solop-develop/frontend-core/assets/20288327/1a194a9e-ed28-40b6-9da2-6ba545358b1c)
