### ISSUE TITLE
Apertura de Caja no genera Salida desde Cuenta bancaria Origen

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#1409]
## Bug report
Cuando se genera una apertura desde el Punto de Venta, el cobro se genera correctamente y crea una Conciliación Bancaria para la de la terminal PDV correspondiente. esto está correcto.

Ahora en ningún momento genera una salida (Pago) desde una cuenta bancaria Origen de dichos fondos. Sale de la nada y no logro comprender donde se debería de definir. 

![Apertura no genera Salida desde cuenta origen](https://github.com/solop-develop/frontend-core/assets/31936815/609b79db-d45f-493d-9796-c65c45b6e2bb)

**Comment by elsiosanchez** [comment]
Saludos @niclopup las cuenta bancaria de donde genera la salida es la que tu coloca en la pestana `Asignación de Cajas` en el campo de `Cuenta Bancaria`  esto es en el kz 

En el pos cuandoen la opcion de `Apertura` a tildar el check `Usar Fondo de Caja` aparece el campo `Cuenta Bancaria` el cual listara todas la que se encuentren `Asignación de Cajas` a ese Punto de Venta

### _**GIF**_

![image](https://github.com/solop-develop/frontend-core/assets/45974454/e9d0fcde-19f9-4511-a14a-0680318f2662)

**Comment by niclopup** [comment]
Gracias por tu respuesta.
