### ISSUE TITLE
Consultas Acciones del Punto de Venta

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#1439]
Question
Asking questions about use

## Question

Cómo se configura para que un Usuario pueda generar las acciones del Punto de venta?

* Asignar Vendedor
* Desasignar vendedor
* Ingreso de dinero
* Cierre de Caja
* Cierre de Caja Detallado

![image](https://github.com/solop-develop/frontend-core/assets/31936815/ab25eeac-06e2-4758-93db-1633d70eedef)

![image](https://github.com/solop-develop/frontend-core/assets/31936815/3a701fbb-e0cd-4993-915b-9074ff7cea5a)

**Vendedores asignados en la Terminal PDV**
Tengo esta definición y no comprendo por que no veo esas opciones

![image](https://github.com/solop-develop/frontend-core/assets/31936815/fe10821a-8546-42ba-ac55-401efd154bfb)

Por otro lado por favor podrían aclarar que realiza las siguientes acciones?

* Asignar Vendedor
* Desasignar vendedor
* Ingreso de dinero
* Cierre de Caja
* Cierre de Caja Detallado

**Comment by elsiosanchez** [comment]
https://github.com/solop-develop/frontend-core/assets/45974454/72b538ef-91a2-4662-90ea-f930f047881d

**Comment by yamelsenih** [comment]
Hola está actividad es general, no es parte de este entregable

**Comment by EdwinBetanc0urt** [comment]
Esto ya estaba resuelto desde el 27 de diciembre @yamelsenih @niclopup
