### ISSUE TITLE
Gráfico asociado a ventana no toma ID del contexto

### ISSUE THREAD

**Issue by nsarlabos** [solop-develop/vue-1.0#1454]
Se define un tablero el cual se desea que se ejecute desde la ventana de Proyectos, para el C_Project_ID del proyecto actual, tomando su C_Project_ID desde el contexto.

A pesar de haberse realizado correctamente todas las parametrizaciones, esto no sucede y el gráfico no toma el C_Project_ID del contexto.

![image](https://github.com/solop-develop/frontend-core/assets/29130825/0c00ec98-1b53-4519-a95f-7026ecbddbeb)

Gráfico asociado a ventana de "Proyectos"

![image](https://github.com/solop-develop/frontend-core/assets/29130825/705c0a1d-29f6-4ff5-a927-ce47a9463f37)

Este caso se vió con @EdwinBetanc0urt y @elsiosanchez

**Comment by EdwinBetanc0urt** [comment]
Esto ya fue corregido en pull request https://github.com/solop-develop/frontend-default-theme/pull/850
