### ISSUE TITLE
Edición de Logos VUE

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#1456]
## Feature request

realizar los siguientes cambios para poder editar los logos del sistema:

* El texto ADempiere dentro del panel al lado del logo habría que quitarlo, que no quede nada.
* El logo al lado del texto deberíamos ver porque nosotros lo tenemos con el logo de ADempiere y en zk-develop está con el * logo de solop, revisé la AD_Client y no tiene cargado logos.
* En el Login, debería aparecer el logo de Solop.

**Comment by EdwinBetanc0urt** [comment]
> El texto ADempiere dentro del panel al lado del logo habría que quitarlo, que no quede nada.

Se colocara el nombre del sistema para que sea parametrizable

![image](https://github.com/solop-develop/frontend-core/assets/20288327/ef088a49-f0ba-455c-9398-ed82fcc67cc1)

> El logo al lado del texto deberíamos ver porque nosotros lo tenemos con el logo de ADempiere y en zk-develop está con el * logo de solop, revisé la AD_Client y no tiene cargado logos.

En la compañía `GardenWorld` tiene configurado todos los logos, se guardan en la tabla `AD_ClientInfo`.

![image](https://github.com/solop-develop/frontend-core/assets/20288327/f0cca6ed-73f0-492f-8359-01969d8df3eb)


> En el Login, debería aparecer el logo de Solop.

Como no existe un campo en base de datos para el logo del sistema, se manejara con variables de entorno para que sea establecido por contenedor a través de una url de una imagen.

**Comment by niclopup** [comment]
Se define ok el Logo del System pero no se logra modificar el Texto de "ADempiere"

**Comment by EdwinBetanc0urt** [comment]
Por algún motivo el reiniciar cache no elimina el cache de `MSystem` (`AD_System`), al cambiar el nombre o versión, se debe reiniciar el servicio del backend grpc para que tome los cambios.

![imagen](https://github.com/solop-develop/frontend-core/assets/20288327/15aa411a-959e-4618-b55a-0a11236fd910)

**Comment by niclopup** [comment]
Bien muchas gracias Edwin.

otra consulta, cómo se define el nombre de la pestaña y el iso que aparece?

![image](https://github.com/solop-develop/frontend-core/assets/31936815/2fbd4201-7061-43c7-b6e4-2f941042140d)

**Comment by EdwinBetanc0urt** [comment]
> Bien muchas gracias Edwin.
> 
> otra consulta, cómo se define el nombre de la pestaña y el iso que aparece?
> 
> ![image](https://user-images.githubusercontent.com/31936815/272678137-2fbd4201-7061-43c7-b6e4-2f941042140d.png)

El titulo y favicon de la pestaña del navegador, no es dinámico como tal, se configura antes de la compilación, por lo que no se sobreescribe con el valor del servicio que trae el nombre del sistema y la imagen, que ocurre en tiempo de ejecución.

Aca se establece el titulo de la pestaña del navegador:
https://github.com/solop-develop/frontend-core/blob/experimental/vue.config.js#L13
https://github.com/solop-develop/frontend-core/blob/experimental/src/settings.js#L2

Aca la ruta del favicon que muestra en la pestaña del navegador:
https://github.com/solop-develop/frontend-core/blob/experimental/public/index.html#L9
https://github.com/solop-develop/frontend-core/blob/experimental/public/favicon.ico


Quizás con variables de entorno en el contenedor se puedan sobreescribir al crear el contenedor docker.
