### ISSUE TITLE
[Bug Report] Al momento de login no se establece AD_Org_ID en el contexto

### ISSUE THREAD

**Issue by rcapecce** [solop-develop/vue-1.0#1466]
## Bug report

Cuando se hace login y no se tiene el acceso a org *, por mas que en el popup del avatar aparece la organización seleccionada, en el contexto no se carga la variable AD_Org_ID

Esto se prueba en vue-develop, habitualmente no se ve este caso porque siempre se entra con * y al cambiar de org si se cambia, pero cuando se hace directo del login, es ahí que no se carga.

#### Steps to reproduce

1. Asegurarse de tener desactivado en el rol del usuario que se logea, la organización *
2. Iniciar sesión
3. Abrir Documentos por Cobrar y constatar en un registro nuevo que el campo AD_Org_ID es 0

**Comment by EdwinBetanc0urt** [comment]
https://github.com/solop-develop/adempiere-grpc-server/assets/20288327/097990e0-db86-4bb8-bad9-f6d309dac9fa
