### ISSUE TITLE
[Bug Report] Consulta Inteligente: Crear desde DxP no muestra campos según selección

### ISSUE THREAD

**Issue by rcapecce** [solop-develop/vue-1.0#1477]
DxP (estado borrador) -> SB Crear desde DxP

Al seleccionar "Create From Type" Orden o Factura el mismo no hace aparecer los campos C_Invoice_ID y C_Order_ID para filtrar

![image](https://github.com/solop-develop/adempiere-grpc-server/assets/14218144/d3312393-5f8d-46e9-bf61-f2972e4427b0)

Probar en http://host.solopapp.com:24145/

**Comment by elsiosanchez** [comment]
> DxP (estado borrador) -> SB Crear desde DxP
> 
> Al seleccionar "Create From Type" Orden o Factura el mismo no hace aparecer los campos C_Invoice_ID y C_Order_ID para filtrar
> 
> ![image](https://user-images.githubusercontent.com/14218144/269989233-d3312393-5f8d-46e9-bf61-f2972e4427b0.png)
> 
> Probar en http://host.solopapp.com:24145/

Realice la prueba y funciona correctamente
![ERROR](https://github.com/solop-develop/frontend-core/assets/45974454/06e94948-f6d0-483a-a248-4da0f6d7c8af)

Probe en la siguiente servicio  http://host.solopapp.com:24145/

**Comment by rcapecce** [comment]
Perdón, colocamos el SB estandar para una demo, ahora volvimos a colocar el que nos está dando el comportamiento indicado

**Comment by EdwinBetanc0urt** [comment]
Corregido

https://github.com/solop-develop/frontend-core/assets/20288327/ddd7f741-93e8-4e47-b325-a785469ba329

**Comment by mgarciaQ76** [comment]
Realizo la validación comparando VUE con ZK con el siguiente resultado: No habilita los campos correspondientes si selecciono crear desde invoice, order ni delivery receipt

VUE delivery

![delivery receipt vue](https://github.com/solop-develop/frontend-core/assets/139590879/2cec6036-2549-48fb-913d-df2b6d8063d5)

ZK delivery

![create from delivery receipt zk](https://github.com/solop-develop/frontend-core/assets/139590879/014c0737-12f5-47b9-ab43-8e9ff58f7f78)

VUE invoice

![invoice vue](https://github.com/solop-develop/frontend-core/assets/139590879/1cc6ab62-4585-4b31-b23e-e5511ec499c3)

ZK invoice

![create from invoice](https://github.com/solop-develop/frontend-core/assets/139590879/50f8ea50-8a5e-419f-8114-c43debd4736f)

VUE order

![order vue](https://github.com/solop-develop/frontend-core/assets/139590879/29da054c-0c53-4ff7-b63e-58a968b3a67f)

ZK order

![create from order](https://github.com/solop-develop/frontend-core/assets/139590879/b92ace2e-2acf-4b8d-9117-af15ec27cbff)

**Comment by elsiosanchez** [comment]
Saludos! @mgarciaQ76 revise en la instancia [24610](http://spdev01.solopapp.com:24610/vue#/) y funciona correctamente


https://github.com/solop-develop/frontend-core/assets/45974454/deebf4dd-4f32-4631-b43a-08cd539a5d22

**Comment by Ricargame** [comment]
Cambios disponibles apartir de la versión: https://github.com/solop-develop/frontend-core/releases/tag/4.0.3

https://github.com/solop-develop/frontend-core/assets/78000356/1453b483-53e4-47d1-9b9c-b9d6981b6509
