### ISSUE TITLE
To-Do List en Panel de Control 

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#1491]
## Feature request

Habilitar la funcionalidad de "To-do" que vemos que está soportada en VUE

![image](https://github.com/solop-develop/frontend-core/assets/31936815/23bf4799-d269-49ec-b4d1-f962a3e89d83)

https://panjiachen.github.io/vue-element-admin

#### Describe the solution you'd like

Creo que para una primera etapa le daría soporte con que muestre sólo el "Asunto" de la R_Request. Si se acciona se debería actualizar el estado de la misma pasando a "Cerrada"

Para determinar que solicitudes se podrían mostrar en este panel de "To-Do" se podría definir que sólo muestre las Solicitudes que tengan un Tipo de Solicitud con el check de "Predeterminado=SI"

![image](https://github.com/solop-develop/frontend-core/assets/31936815/642fcfbb-eee5-4c94-815e-edfa80babc0d)

#### Additional context

Se toma la idea desde este link:

https://panjiachen.github.io/vue-element-admin

**Comment by niclopup** [comment]
ok pero se debe poder QUITRAR de alguna manera

Por favor si no se puede ver como quitar por diccionario, entonces sacarlo por completo hasta que tengamos una manera de poder definirlo desde parametrización

**Comment by EdwinBetanc0urt** [comment]
Listo para pruebas a partir de la versión del frontend https://github.com/solop-develop/frontend-core/releases/tag/3.7.0


![2024-04-11_09-56](https://github.com/solop-develop/frontend-core/assets/20288327/ac526172-1f9c-45b0-876a-91e14fc225f2)
