### ISSUE TITLE
Issues (Solicitudes) Drag Kanban

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#1492]
## Feature request

Board Kanban

Se desea contar con una sección como se creó de "Gráficas" pero que se visualice sólo un tablero con columnas según el Estado de Solicitudes que esté definido como "Predefinido" (o ver la manera que quede como se necesite para dejar fijas o no las columnas). 

![Drag Kanban](https://github.com/solop-develop/frontend-core/assets/31936815/cf7090e5-08bd-4bfa-947f-aa6c858b0084)

La idea es que se defina una columna según ESTADO, en cada columna se deberían ver en cada Tarjeta los Registros de Solicitudes (R_Request) que estén asignadas a mi usuario (Aplicar la misma condición que tiene el formulario nuevo de Issues, se deberían ver las mismas) 

Acción: al mover los registros de Solicitudes a una columna diferente la idea es que actualice el ESTADO de la Solicitud.

Datos a definir en las "Tarjetas": 

![image](https://github.com/solop-develop/frontend-core/assets/31936815/365f708f-f564-4f7a-aee7-eac535f7528f)

1.  Color según Vencimiento: Igual a como se muestra en el formulario de Issues
2. Nombre del Proyecto que está asociada la R_Request
3. No. Documento de la Solicitud
4. asignado a quien (este campo ver como se puede definir con lo qe hay acualmente) si se piuede poner el Avatar sería ideal
5. Asunto de la Solicitud

![image](https://github.com/solop-develop/frontend-core/assets/31936815/f1a7400b-b90e-4378-87b3-79d23bbc1855)

#### Additional context

https://panjiachen.github.io/vue-element-admin/#/components/drag-kanban

**Comment by EdwinBetanc0urt** [comment]
Para el kanban de los estados de los request, debe colocarse el filtro de la categoría de estados de solicitudes, para ver estados por categoría.

Esta misma idea del kanban podría aplicarse para una vista en las ventanas y ver los estados de documentos.

**Comment by niclopup** [comment]
Esto funciona? no logro hacer drag n Drop y que cambie el estado.

**Comment by EdwinBetanc0urt** [comment]
Esto funciona con el Dag and drop

https://github.com/solop-develop/frontend-core/assets/45974454/38a387ea-d3fc-465b-baf0-8336090c8a62
