### ISSUE TITLE
Proceso: Manejo > Envio de Parámetros

### ISSUE THREAD

**Issue by elsiosanchez** [solop-develop/vue-1.0#15]
se requiere migrar procesos de ADempiere al Framework reactivo de Javascript Vue.js. Verificar que los parámetros seleccionados se manden al servidor correctamente

### ADempiere(**ZK**)

![image](https://user-images.githubusercontent.com/45974454/166825258-6a118466-911e-474b-959e-40d2a4d25663.png)

### ADempiere-UI
![image](https://user-images.githubusercontent.com/45974454/166825425-7a318ee5-b5f8-4f63-a56d-d8e30ef58046.png)

**Comment by elsiosanchez** [comment]
Se mapean los parámetros como lo espera el servidor [52](https://github.com/adempiere/adempiere-vue/blob/develop/src/api/ADempiere/process.js#L52)

![image](https://user-images.githubusercontent.com/45974454/166942168-f5293fc4-0485-433b-a2ef-c55413eb98cc.png)


![image](https://user-images.githubusercontent.com/45974454/166942472-211ef9ea-693c-4e4b-8f80-c0a8e0ce5082.png)

**Comment by EdwinBetanc0urt** [comment]
Para el caso de uso de pruebas ver: 
https://solop-develop.github.io/frontend-core/es/guide/use-cases/process.html#validacion
