### ISSUE TITLE
Ventana: Apertura > Árbol de Menú

### ISSUE THREAD

**Issue by elsiosanchez** [solop-develop/vue-1.0#150]
### Árbol de Menú
Aperturar un reporte dede el arbol de menú:
1. Desplegar el árbol de menu en **Diccionario de la Aplicación**.
2. Seleccione **Vista**.

#### Actualmente en la interfaz de ADempiere-Vue se le dio soporte para abrir los reporte desde el menu

![open-menu-desktop-vue](https://user-images.githubusercontent.com/45974454/172889224-1fb93278-2156-40a9-953f-a05adc14a3c0.gif)

### Versión Movil Vue:
![open-menu-mobile-vue](https://user-images.githubusercontent.com/45974454/172889084-5d873b05-f33c-4f7b-a90c-92df01ee30be.gif)

**Comment by niclopup** [comment]
ok
