### ISSUE TITLE
Ventana: Apertura > Buscador de Menú

### ISSUE THREAD

**Issue by elsiosanchez** [solop-develop/vue-1.0#151]
Apertura una **Ventana** desde el buscador del árbol de menú:

1. Enfocar la entrada de texto encima del menú.
2. Escribir el nombre de la **Ventana** que desea buscar.
3. Seleccionar **Vistas**

Versión Escritorio Vue:
![open-search-desktop vue](https://user-images.githubusercontent.com/45974454/172892119-19e4728b-748c-4910-8d7e-83aa46e65f30.gif)

Versión Movil Vue:
![open-search-mobile](https://user-images.githubusercontent.com/45974454/172892849-68dbc496-7dcc-4352-a3fd-9886a9828221.gif)

**Comment by niclopup** [comment]
ok
