### ISSUE TITLE
Ventana: Apertura > Elementos Recientes

### ISSUE THREAD

**Issue by elsiosanchez** [solop-develop/vue-1.0#153]
Abrir una Ventana desde el tablero de elementos recientes:

- Iniciar sesión como GardenAdmin.
- Ubicar el tablero de elementos recientes.
- Seleccionar cualquier **Ventana** que recientemente se haya abierto.

### Versión Escritorio Vue:
![open-recient-item-desktop-vue](https://user-images.githubusercontent.com/45974454/172891058-0cdca314-5ddf-4307-9f53-31569026b56a.gif)

### Versión Movil Vue:
![open-recient-item-mobile-vue](https://user-images.githubusercontent.com/45974454/172891004-8a738165-7818-4697-8c19-9beb5526b687.gif)

**Comment by niclopup** [comment]
ok
