### ISSUE TITLE
Check en texto no convierte correctamente en VUE

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#1537]
## Bug report

Se desea utilizar la misma lógica que se puede aplicar en GIT con la creación de Checks automáticamente simplemente mediante texto en un comentario de una Request pero no se logra que convierta correctamente

#### Steps to reproduce

1. abrir cualquier texto que se pueda escribir como GIT y probar

- [ ] check ejemplo

- [ ] Hola

- [ ] 

#### Screenshot or Gif（截图或动态图）

![Check en Texto no convierte correctamente](https://github.com/solop-develop/frontend-core/assets/31936815/a5df38c9-672d-427a-9e78-0915930b0d7a)

![image](https://github.com/solop-develop/frontend-core/assets/31936815/c029db91-7280-419a-98ec-6aed1817a3ba)

**Comment by EdwinBetanc0urt** [comment]
Corregido

![error](https://github.com/solop-develop/frontend-core/assets/45974454/08f64d28-54c5-478a-a946-6d28680a06cb)
