### ISSUE TITLE
Ventana: Apertura > Acercar desde Criterio de la Busqueda Inteligente

### ISSUE THREAD

**Issue by elsiosanchez** [solop-develop/vue-1.0#154]
Abrir una ventana desde un criterio de búsqueda de las consultas inteligentes

#### Pasos para Reproducir:

1. Iniciar sesión con `GardenAdmin`.
2. Abrir la consulta inteligente `Consulta de Usuarios`.
3. Mostrar el campo `Grupo de Socio de Negocio`.
4. Listar y seleccionar una de las opciones.
5. Pulsar sobre el nombre del campo para mostrar las opciones del campo.
6. Seleccionar `Acercar`.

#### Capturas de Pantalla:

https://user-images.githubusercontent.com/20288327/178884763-4ed66293-5583-450c-85b3-9bcd8106a7af.mp4

#### Comportamiento Esperado:

Abrir la ventana con el registro que se selecciono en el campo tipo lista seleccionable.

**Comment by niclopup** [comment]
la acción de Acercar funciona ok abriendo la ventana y el registro correspondiente, pero sólo funciona si se tiene la ventana Cerrada.

Si se cuenta con la ventana abierta, vuelve a mostrar el mismo registro sin actualizar el registro que se navegó exactamente.

Se muestra el caso en el siguiente GIF

https://user-images.githubusercontent.com/31936815/179798592-9618b19b-a10b-457b-9d64-9d575650fc05.mp4

**Comment by EdwinBetanc0urt** [comment]
@niclopup esto debe resolverse con el abrir múltiples ventanas a la vez, ya que si se tienen cambios sin guardar en la ventana y se acerca para establecer o filtrar los registros se perderán los cambios que el usuario pudo hacer. Por eso solo establece/filtra registros al acercar en ventanas cerradas, si ya esta abierta solo la abrirá.

**Comment by niclopup** [comment]
ok
se sigue este detalle en la issue https://github.com/solop-develop/frontend-core/issues/199
