### ISSUE TITLE
Forma Balance de Prueba Navegable (Sólo WEB)

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#1554]
## Feature request

Veo que no se le dió soporte a esta forma (Formulario) de Adempiere que actualmente sólo tiene soporte con ZK (no por swing). 

Creo que sería muy útil si le podemos dar soporte a ella para que se pueda visualizar desde VUE.

Sobre su diseño, me gustaría ver si podemos aprovechar y dejar variable las líneas a aplicar, dando la posibilidad de definir diferentes "líneas de Informes Financieros" y no sólo cuentas contables quemadas como está ahora.

![Balance de Prueba Navegable](https://github.com/solop-develop/frontend-core/assets/31936815/3a8b81b5-f3d1-4cca-aaec-1e89aafd4bb3)

![image](https://github.com/solop-develop/frontend-core/assets/31936815/14e16035-e197-4fcf-afab-e917e85fb71a)

#### Describe the solution you'd like

La idea sería contar con algo así: 

![image](https://github.com/solop-develop/frontend-core/assets/31936815/6040e623-20f6-409d-a978-0e1da9ad2607)

**Comment by niclopup** [comment]
No carga ningún dato los campos para generar un balance d prueba navegable
 

La prueba se realiza con Rol "Administrador" Organización "Agencia"
![image](https://github.com/solop-develop/frontend-core/assets/31936815/ac3d1b00-bb5f-47e0-b61b-0046fa770c7e)


Se debe hacer alguna configuración especial?

**Comment by EdwinBetanc0urt** [comment]
Era error en la actualización del proxy

**Comment by niclopup** [comment]
Se ven los siguientes detalles:

- [ ] Filtro de Cuentas Contables no muestra todas: Parecería que la lista tiene un tope de registros ya que no se ven las cuetna de mayor nro lo que hace que no se pueda filtrar por todas las cuentas de resultado (desde el 4 - 8) Por ejemplo la cuenta 79600 que se ve que tiene dato no se puede seleccionar.

![Balance de Prueba Navegable - Filtro de Cuentas no muestra todas](https://github.com/solop-develop/frontend-core/assets/31936815/b9ffe804-e11e-4f60-a88d-f6fc51f51b9d)


- [x] Ocultar Columna "Usuario 1": sabrían por que motivo se muestra esta columna en ZK? que mira en la configuración? Se podría dejar configurable si se muestra o no según el Cubo que se seleccione? En los cubos se define que dimensiones se desea manejar por eso creo que seriá bueno definirlo a partir de ahi.

![image](https://github.com/solop-develop/frontend-core/assets/31936815/02604edb-b871-42bc-acf5-7c163be012d3)


- [x] Ajustes en algunas traducciones de columnas:
- Nombre de Columna "Período Real": Cambiar traduccción a "Período Actual"
- Nombre de Columna "Hasta la Fecha Real": Cambiar traduccción a "Acumulado Actual (YTD)"
- Nombre del "Presupuesto hasta la fecha":  Cambiar traduccción a "Presupuesto Acumulado (YTD)"

- [x] Agregar check de "Mostrar período" y "mostrar Acumulado" para mostrar o no las columnas del Período o Acumuladas

![image](https://github.com/solop-develop/frontend-core/assets/31936815/1c0396d2-0ac3-4c26-a816-55fbee357008)

- [x] Color en campos de Variación importe: los improtes según sean positivos ostrarlos en Verde, negativos en rojo

![image](https://github.com/solop-develop/frontend-core/assets/31936815/ec26f217-d69f-48a6-b17a-8bae54674620)

- [x] Nueva Columna % Varianza: Se desea agregar una columna que salga de la formula "Variación del Período / Presupuesto del Período" el resultado multiplicarlo por 100 y definirlo con el signo de % adelante.

![image](https://github.com/solop-develop/frontend-core/assets/31936815/bf3e18f6-c645-4629-8e1c-fe5c81b2d416)

![image](https://github.com/solop-develop/frontend-core/assets/31936815/47ee5838-fedb-4c82-8e44-73d9b18c0e6d)

**Comment by niclopup** [comment]
Se desean dejar los filtors que se puedan ocultar. igual a como es en el SmartBrowser.

Se desea qiue los cabezales de las columnas queden siempre visibles. No importa si se hace sctroll pasra abajo se debe ver que es cada columna. 


![image](https://github.com/solop-develop/frontend-core/assets/31936815/3978efe4-db7f-4b6a-a05d-9013a2ad4b74)

![image](https://github.com/solop-develop/frontend-core/assets/31936815/66a2acba-f93e-44eb-8e75-c6cf80d5bd14)

**Comment by EdwinBetanc0urt** [comment]
También se debe agregar que se refresquen los registros de manera automática con cada cambio del filrto siempre que estén llenos los campos obligatorios como mínimo.

**Comment by Ricargame** [comment]
Cambios disponibles apartir de la versión: https://github.com/solop-develop/frontend-core/releases/tag/3.8.3

Se culminaron los siguientes puntos: 
- Ocultar Columna "Usuario 1"
- Ajustes en algunas traducciones de columnas
- Agregar check de "Mostrar período" y "mostrar Acumulado" 
- Color en campos de Variación importe
- Nueva Columna % Varianza
- Cabezal de columna fijo 
- Búsqueda automática al cambiar de filtro

https://github.com/solop-develop/frontend-core/assets/78000356/c88d391f-17cc-4f96-ac14-789189566df1
