### ISSUE TITLE
Acción "Acercar" da error en Vue Transcoding

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#1580]
## Bug report

1. Se intenta acercar desde una tarjeta de "Document Status Indicator" y da error por "Parametro(s) con valores vacios" 
2. Se intenta acercar en un campo SDN desde la ventana OV y da mismo error. 

#### Screenshot or Gif（截图或动态图）
![Acercar a Tarjeta da error en VUE NUEVO](https://github.com/solop-develop/frontend-core/assets/31936815/1104603d-0345-4d19-9f4e-0ced6576f7bc)

![Acercar campo SDN desde ventana OV da error](https://github.com/solop-develop/frontend-core/assets/31936815/9d8d0332-34ab-4972-9f21-a20bc898260d)

Ahora intento repetir esto en VUE Develop y no da error. Hay algún cambio nuevo en esto?

![Acercar desde VUE Develop nuevo ok](https://github.com/solop-develop/frontend-core/assets/31936815/c51bd824-1c74-4079-bb71-46a2207abd41)

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:

**Comment by EdwinBetanc0urt** [comment]
Esto fue corregido en espera para pruebas.
