### ISSUE TITLE
SB no hace Scroll para abajo con 50 registros

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#1584]
## Bug report

SB no hace Scroll para abajo con la Paginación de más de 25 registros

#### Steps to reproduce

1. Abrir Scroll de "Consulta Ordenes de Venta"
2. Quitar todos los filtros del buscador
3. Cambiar paginación a 50 registros

#### Screenshot or Gif（截图或动态图）

![SB no hace Scroll para abajo con la Paginación de más de 25 registros](https://github.com/solop-develop/frontend-core/assets/31936815/6dfd9c22-c285-4ffc-815e-0102de40f0c2)

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version: Transcoding

**Comment by EdwinBetanc0urt** [comment]
@elsiosanchez Esto se debe corregir en la rama `experimental` y luego del release llevarse a la rama `transcoding`.

**Comment by EdwinBetanc0urt** [comment]
Esto ya esta en `develop` (rama anteriormente `transcoding`), la rama `experimental` ya no tendra soporte por lo que se da por corregido a nivel de desarrollo, en espera de pruebas.
