### ISSUE TITLE
Filtro de Lista de Precios en Buscador de Producto

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#1586]
## Bug report

Cuando se realiza una búsqueda con el Buscador de productos desde una línea de un documento, se debe definir en sus fuiltris por defecto la lista deprecios que tenga definida al documento correspondiente para que sólo muestre los Productos que estén definidos en dicha lista de precios. Opcionalmente se podría quitar para aplicar la búsqueda sin pero esto no tiene mucho sentido yaque luego se controla que el producto esté en la lista de precios al guardar la línea. 

#### Screenshot or Gif（截图或动态图）
Ejemplo VUE
![Buscador de productos no filtra por Lista de Precios del Documento](https://github.com/solop-develop/frontend-core/assets/31936815/7f5a63fe-fcf8-4ccf-b6ae-143a9bddd782)

Ejemplo ZK

![Buscador de productos SI filtra por Lista de Precios del Documento en ZK](https://github.com/solop-develop/frontend-core/assets/31936815/254a7baf-ccaf-4d22-8614-f808308d41eb)

**Comment by EdwinBetanc0urt** [comment]
Ya se agrego el campo y filtra por la lista de precios ademas de mostrar columnas de precios, sin embargo aun no se establece el valor que viene del contexto por defecto.

**Comment by EdwinBetanc0urt** [comment]
Se agrego el establecer la lista de precio disponible a partir de la version del frontend https://github.com/solop-develop/frontend-core/releases/tag/3.6.1 y del backend https://github.com/solop-develop/adempiere-grpc-server/releases/tag/3.0.5

https://github.com/solop-develop/adempiere-grpc-server/assets/20288327/0a69de5e-3b30-4f7c-8e14-ec47051d12ec
