### ISSUE TITLE
Lista de Productos al seleccionar desde campo en línea hacer más ancha

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#1587]
## Bug report

Cuando se realiza una búsqueda en formato lista de un producto cuando las líneas de la Orden de Venta está en modo Grilla, el ancho de la lista es muy pequeño, sería bueno que sea más grande.

Si se define un producto en modo "Mono Registro" se puede ver más ancho la línea que puede ser suficiente para dejarlo para que se vea igual en modo grilla y mono registro.

#### Steps to reproduce

1. [xxx]
2. [xxx]
3. [xxxx]

#### Screenshot or Gif（截图或动态图）
![Lineas de orden seleccion de Producto](https://github.com/solop-develop/frontend-core/assets/31936815/56566703-175a-4882-b292-ae4a4118ca16)

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:

**Comment by EdwinBetanc0urt** [comment]
Corregido

![imagen](https://github.com/solop-develop/frontend-core/assets/20288327/e60185ff-e4de-4960-879f-ab877ad1a457)
