### ISSUE TITLE
Ventana de Usuario para ROL con errores en transcoding

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#1593]
## Bug report

Se intenta ver una ventana que tiene una configuración de Ventana de Usuario para el Rol "Field Services" pero no se ve correctamente. 

Ventana: Proyecto de Servicios
Rol: Field Services

h2. Ejemplo Correcto en VUE Legacy

![Ventana con personalización para ROL OK (Legacy)](https://github.com/solop-develop/frontend-core/assets/31936815/dcf99f64-f59c-424f-a177-7137a60833e9)

h2. Ejemplo Error en VUE Transcoding

No se ve campo de Agente comercial por ejemplo. Varios más como fechas tampoco

![Ventana con personalización para ROL Error (Transcoding)](https://github.com/solop-develop/frontend-core/assets/31936815/48c6eedc-ad02-4974-8e4b-4a1d8a10a05a)

Configuración de ventana de usuario:

![Campos visibles en Grilla Registro Ventana de Usuario Proyeto de servicios](https://github.com/solop-develop/frontend-core/assets/31936815/b62ef804-47c0-4126-a7be-369bb8f37c21)
![Campos visibles en mono Registro Ventana de Usuario Proyeto de servicios](https://github.com/solop-develop/frontend-core/assets/31936815/02ec8956-e65c-4e5a-b229-02d0792aab70)

h2. Campos de Impotes de Proyecto Obligatorios aparcen por defecto cuando no deberían

![image](https://github.com/solop-develop/frontend-core/assets/31936815/fb140e22-c0b7-4f8d-b306-6d3c0ab6d623)

Link para ver error:
http://host.solopapp.com:24157/

Link para ver OK
http://host.solopapp.com:24145

**Comment by EdwinBetanc0urt** [comment]
Se corrigió el formato de los valores de montos.

![imagen](https://github.com/solop-develop/frontend-core/assets/20288327/5290b861-aab1-4e19-bd4c-8b408f33c7dd)
