### ISSUE TITLE
[Bug Report] Ruta desactualizada en endpoint de acción de flujo de trabajo

### ISSUE THREAD

**Issue by rcapecce** [solop-develop/vue-1.0#1595]
## Bug report

Se detecta que la ruta en el frontend para accionar los flujos de trabajo está desactualizada.

Ejemplo de ruta utalizada
http://0.0.0.0:8081/api/workflow/run-document-action?table_name=C_Order&uuid=2661da38-2e4a-4de4-9003-cb039417f1a0&document_action=CO

#### Steps to reproduce

1. Completar una OV
2. Obtener mensaje de error

#### Expected behavior
Realizar un flujo de documento desde Draft a Complete

**Comment by EdwinBetanc0urt** [comment]
Esto ya fue corregido.
