### ISSUE TITLE
Proceso: Manejo > Cierre del Proceso al Ejecutarse

### ISSUE THREAD

**Issue by elsiosanchez** [solop-develop/vue-1.0#16]
Se requiere que el comportamiento al ejecutarse un proceso sea como el de la interfaz del (ZK)
![zk](https://user-images.githubusercontent.com/45974454/166944964-a63289e4-1982-4635-9af5-50a7a78f4d21.gif)

**Comment by elsiosanchez** [comment]
Se agrego soporte al ejecutarse los proceso de ADempiere-Vue

Antes de ejecutarse primero se evalúa que cumpla las validaciones y que envíe los parámetros de forma correctas al servidor. 

El comportamiento es similar al de la Interfaz ZK, sin embargo el paso adicional que tiene la interfaz ZK, que una vez ejecutado el proceso de igual manera se debe pulsar el botón aceptar o cancelar para cerrar el proceso fue eliminado en la interfaz Vue, al ejecutar el proceso se cierra el proceso, muestra dos notificaciones una indicando que el proceso se está iniciando y otro mostrando el resultado de la respuesta.

### GIF

![Ui](https://user-images.githubusercontent.com/45974454/166944989-a6f6e1c2-9cdf-41a9-a558-85fb2fd56c55.gif)

### Mensaje al Ejecutar Proceso

![image](https://user-images.githubusercontent.com/45974454/166945225-fa8c3827-211f-4653-a1b5-82c74cb8debb.png)

### Mensaje con el Resultado del Proceso

![image](https://user-images.githubusercontent.com/45974454/166945398-ebdbabf3-377d-4960-8dad-5d296a93f934.png)

**Comment by EdwinBetanc0urt** [comment]
Para el caso de uso de pruebas ver:
https://solop-develop.github.io/frontend-core/es/guide/use-cases/process.html#cierre-del-proceso-al-ejecutarse
