### ISSUE TITLE
Paginación en Búsqueda de Orden de Salida

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#1605]
## Bug report
Cuando se quiere hacer una búsqueda de órdenes de salida en un SB, no funciona la paginación de documentos, sólo motrando 15 registros, si hay más no se pueden encontrar

El error se encontró en Legacy

#### Steps to reproduce

Desde un SB que tenga como campo de filtro la orden de salida y que este esté como "Búsqueda" no funciona la paginación.

#### Screenshot or Gif（截图或动态图）

![image](https://github.com/solop-develop/frontend-core/assets/31936815/49bdc5f1-3686-4bbe-b834-e64f9ee8a829)

**Comment by EdwinBetanc0urt** [comment]
@elsiosanchez  Esto se debe corregir en la rama `experimental` y luego del release llevarse a la rama `transcoding`.

**Comment by Ricargame** [comment]
Cambios disponibles apartir de la versión: https://github.com/solop-develop/frontend-core/releases/tag/3.9.4


https://github.com/solop-develop/adempiere-grpc-server/assets/78000356/108ad17b-4952-4198-ac10-a90cd2b2725e
