### ISSUE TITLE
[Bug Report] Pestaña Gráficos no scrollea

### ISSUE THREAD

**Issue by rcapecce** [solop-develop/vue-1.0#1630]
## Bug report

En el menú lateral de vue, al abrir Gráficos, se logra ver que dicho panel no scrollea

#### Steps to reproduce

1. Abrir menú lateral
2. Opción Gráficos

#### Screenshot or Gif（截图或动态图）

![2023-11-16_12-10](https://github.com/solop-develop/frontend-core/assets/14218144/79c3ca26-2d0d-4400-a584-f891b577fa5f)

![2023-11-16_12-10_1](https://github.com/solop-develop/frontend-core/assets/14218144/479cc53d-e9ca-4618-8fcf-87c3d710bde3)

**Comment by niclopup** [comment]
No funciona aún el scroll en gráficos

https://github.com/solop-develop/frontend-core/issues/1630
