### ISSUE TITLE
Pago no completa

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#1635]
## Bug report
Se intenta completar un pago Cobro, si bien da "Terminado" pero el pago sigue en estado borrador.

Cobro: 238

#### Screenshot or Gif（截图或动态图）
![image](https://github.com/solop-develop/frontend-core/assets/31936815/78ef7a41-f0e8-4755-ac75-5b864424efbe)!

![cobro no completa](https://github.com/solop-develop/frontend-core/assets/31936815/b3208d78-ef2c-4393-84d9-45c7735158fc)

#### Other relevant information
- Web Browser:  Chrome
- adempiere-vue version: Transcoring
- Base: http://host.solopapp.com:24157

**Comment by elsiosanchez** [comment]
Hola @niclopup no se puede replicar este error con su data

![Peek 2023-11-15 19-25](https://github.com/solop-develop/frontend-core/assets/45974454/90f8723c-d71c-43ce-8f9f-6468f0e0226c)

**Comment by niclopup** [comment]
me paso lo mismo q la vez pasada. me dice completed  pero en vue no lo veo completo.



![Captura de pantalla 2023-11-21 094844](https://github.com/solop-develop/frontend-core/assets/31936815/225ad556-7426-4295-a9a7-acbbe0f79ac2)
![Captura de pantalla 2023-11-21 094934](https://github.com/solop-develop/frontend-core/assets/31936815/f44634ba-d106-4153-8903-f6849730ab4a)


ahora fui a zk y veo el mismo pago pero completo si.

![Captura de pantalla 2023-11-21 094916](https://github.com/solop-develop/frontend-core/assets/31936815/01fb582c-e613-412a-8403-978c8130128d)

![Captura de pantalla 2023-11-21 094858](https://github.com/solop-develop/frontend-core/assets/31936815/3dddb454-7826-429c-aaeb-c78fe30ff77d)

se ve q es un tema q no actualiza el estado en vue o algo asi


Para confirmar la teoría, entré como Incógnito y veo el pago en estado completo si

![image](https://github.com/solop-develop/frontend-core/assets/31936815/7e40ce56-7065-497f-92ac-e63c84f2a5fa)

**Comment by EdwinBetanc0urt** [comment]
El problema de refrescar el registro se detalla en el issue https://github.com/solop-develop/frontend-core/issues/1644
