### ISSUE TITLE
Errores varios en Asignación de Pagos 

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#1636]
## Bug report

1. No muestra Saldo Abierto en columna "Aplicado"

Se realiza una búisqueda para un SDN que tiene cobros sin asignar, se selecciona un cobro para asignar y no aparece el importe "Aplicado"

#### Steps to reproduce

Abrir ventana "Asignación de Pagos" y buscar pagos para el SDN "Toyota S.A." en moneda UYU Organización "Agencia"

#### Screenshot or Gif（截图或动态图）

![image](https://github.com/solop-develop/frontend-core/assets/31936815/80ea8eb3-a28a-45f0-adf8-6315e5a8e75b)

2. No muestra suma al seleccionar Facturas.

Se selecciona una factura con saldo abierto y abajo en la sección de "Diferencia" no se ve el nro sino que pone "NaN"

#### Screenshot or Gif（截图或动态图）

![image](https://github.com/solop-develop/frontend-core/assets/31936815/21dd2a3f-14ed-49c4-a007-01ccf08857ac)

#### Link to minimal reproduction（最小可在线还原demo）

http://host.solopapp.com:24157/

#### Other relevant information
- Your OS:
- Web Browser: Chrome
- Node.js version:
- adempiere-vue version: Transcoding

**Comment by niclopup** [comment]
Errores reportados inicialmente corregidos.

ahora se encuentran nuevos erroers. 


**Campos de Importes sin formato correcto**

![image](https://github.com/solop-develop/frontend-core/assets/31936815/58d72262-942d-48ed-81fe-e9f05b03777c)

los campos de importes son todos diferentes.

no muestra puntos decimales ni puntos de miles.

debe ser igual a como presenta los importes en los documentos. 

![image](https://github.com/solop-develop/frontend-core/assets/31936815/541fffe1-b8ae-4637-a00e-ac739dfdced6)


tampoco dice la moneda de los documentos.

**Fecha con formato incorrecto**

la fecha debe ser la definida en los documentos dd/MM/yyyy

**Comment by niclopup** [comment]
Esto se sigue visualizando igual con los improtes de los PAGOS sin corregir 

![image](https://github.com/solop-develop/frontend-core/assets/31936815/789757ed-f0d8-4b15-b1cc-e030d644689c)


Además agregaría que todas estas líneas sean bastante más pequeñas para que se puedan visulizar correctamente todas las columnas sin tener que hacer Scroll lateralmente y entren más registros.


asi queda si pongo el ZOOM a 75%. entiendo qu no aparecerán todos los registros pero creo que se puede ahiccar un poco más para que se va más datos.
![image](https://github.com/solop-develop/frontend-core/assets/31936815/c8264c07-ed26-43a1-9b02-1257b19b14e4)

**Comment by EdwinBetanc0urt** [comment]
Corregido y disponible a partir del release https://github.com/solop-develop/frontend-core/releases/tag/3.3.8 del frontend

**Comment by niclopup** [comment]
bien, está ok.

sólo veo que faltaría unos detalles 

**Texto no se lee bien:**  en las línas no se por que pero parece que los textos están cortando la parte inferior de las letras. Veo que ésto sólo pasa con letras que bajan del nivel normal  como "pjg" 

![image](https://github.com/solop-develop/frontend-core/assets/31936815/b7b055f7-fb88-4821-8fe1-c77e280b09fd)

 **Msj de Respuesta de acción**

En ZK el proceso respondía abajo el Nro de Asignación que generó.

![image](https://github.com/solop-develop/frontend-core/assets/31936815/a2da55ee-dc88-4cac-84fc-3870814039b9)

ahora en VUE no está respondiendo nada más que OK, lo que hace dificil saber o poder ir a ver la asignación que generó. Estoy abierto a mostrarlo de la manera que nos sea más fácil, pero de aguna manera tenemos que mostrar el nro de la Asignación (C_Allocation)

![Asignación de Pagos - Msj de respuesta no dice Nro de Asignación](https://github.com/solop-develop/frontend-core/assets/31936815/f5db691d-4e9c-4a29-a08f-248cb1e0caba)

**Comment by EdwinBetanc0urt** [comment]
El servicio devuelve el mensaje al procesar, debe ser corregido en el frontend
