### ISSUE TITLE
Ventana: Apertura > Asociados a una Consulta Inteligente

### ISSUE THREAD

**Issue by EdwinBetanc0urt** [solop-develop/vue-1.0#164]
### Ventana asociada a Consulta Inteligente

Aperturar una Ventana asociada a una Consulta Inteligente:

1. Desplegar el árbol de menú en **Gestión de Ventas** > **Ordenes de Venta**.
2. Seleccionar la consulta inteligente **Procesar Órdenes en Lote**.
3. Llenar el campo de criterio de búsqueda `Estado del Documento` con el valor `Completo`.
4. Seleccionar dos registros.
5. Pulsar el botón `Acercar` ubicado en la parte superior a la izquierda de la Consulta Inteligente.
6. Al abrir la Ventana colocar en modo `multi registro` y verificar que estén solamente los registros seleccionados.

#### Visualización en la interfaz ZK:

https://user-images.githubusercontent.com/20288327/173371276-66676734-b94f-4c2e-b652-64dea4733480.mp4

**Comment by EdwinBetanc0urt** [comment]
#### Visualización en la interfaz Vue:

Aperturar una Ventana asociada a una Consulta Inteligente:

1. Abrir la consulta inteligente **Consulta de Usuarios**.
2. Seleccionar dos registros.
3. Desplegar el menú de acciones ubicado en la parte superior a la izquierda de la Consulta Inteligente.
4. y seleccionar `Acercar Ventana` 
5. Al abrir la Ventana colocar en modo `multi registro` y verificar que estén solamente los registros seleccionados.

https://user-images.githubusercontent.com/20288327/178823130-93b92d24-5441-4710-81f1-ddf919da8e60.mp4

**Comment by niclopup** [comment]
ok
