### ISSUE TITLE
Error al navegar entre pestañas SDN

### ISSUE THREAD

**Issue by mgarciaQ76** [solop-develop/vue-1.0#1651]
## Bug report
al navegar entre pestañas. quedan trabadas sin poder navegar, se debe presionar en la ventana padre para que se desbloqueen

#### Steps to reproduce

1. [Crear SDN]
2. [Grabar]
3. [navegar a pestaña cliente o proveedor, o empleado]

#### Screenshot or Gif（截图或动态图）
https://soporte.solop.uy/attachments/download/15684/error%20al%20navegar%20entre%20pesta%C3%B1as.png

#### Link to minimal reproduction（最小可在线还原demo）
![error al navegar entre pestañas](https://github.com/solop-develop/frontend-core/assets/139590879/096c790e-5b6c-42fc-99af-6de6a5d09561)

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:
Todas las pruebas las realizo desde http://host.solopapp.com:24157/
Rol distribucion y logistica
Organizacion Distribucion

**Comment by Ricargame** [comment]
Buenas tades @mgarciaQ76 realice la prueba en ambas instancias y no logre replicar el error 

https://github.com/solop-develop/frontend-core/assets/78000356/eedf9c14-27fd-49f3-9240-15cd41404411

**Comment by Ricargame** [comment]
Cambios disponibles a partir de la versión https://github.com/solop-develop/frontend-core/releases/tag/4.3.2

https://github.com/user-attachments/assets/19cf8681-7f19-4a8e-9634-d1c02dcc5600
