### ISSUE TITLE
Error al refrescar SDN

### ISSUE THREAD

**Issue by mgarciaQ76** [solop-develop/vue-1.0#1652]
## Bug report
Genera error 400 al refrescar

#### Steps to reproduce

1. [Crear o consultar SDN]
2. [Refrescar]

#### Screenshot or Gif（截图或动态图）
https://soporte.solop.uy/attachments/download/15683/Error%20al%20refrescar.png

#### Link to minimal reproduction（最小可在线还原demo）
![Error al refrescar](https://github.com/solop-develop/frontend-core/assets/139590879/a0e97716-45bc-4edb-8c68-35eccf3e7546)

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:

#### Additional context
Todas las pruebas las realizo desde http://host.solopapp.com:24157/
Rol distribucion y logistica
Organizacion Distribucion

**Comment by EdwinBetanc0urt** [comment]
Este error fue corregido en el PR https://github.com/solop-develop/frontend-core/pull/1643 estará disponible en el próximo release.

**Comment by mgarciaQ76** [comment]
Verificado
