### ISSUE TITLE
[Bug Report] No se ve el acceso rápido de adjuntos

### ISSUE THREAD

**Issue by EdwinBetanc0urt** [solop-develop/vue-1.0#1666]
#### Steps to reproduce

1. Abrir una ventana con adjuntos asociados.

Notar que el icono de adjuntos (clip) no tiene la cantidad de adjuntos asociados al registro

#### Screenshot or Gif（截图或动态图）

![imagen](https://github.com/solop-develop/frontend-core/assets/20288327/7afa0cf7-5647-4ef3-897c-649d3eb146bb)

**Comment by niclopup** [comment]
se ve el icono pero no se ven los adjuntos


legacy
![image](https://github.com/solop-develop/frontend-core/assets/31936815/0eb0c27f-54be-4045-b235-9e15ff9e94af)

transcoding
![image](https://github.com/solop-develop/frontend-core/assets/31936815/f8ea3470-79f1-460a-8847-29633eb7fa35)

**Comment by elsiosanchez** [comment]
Corregido

https://github.com/solop-develop/frontend-core/assets/45974454/4faa9884-acfd-4abe-8448-913e2d6833f2
