### ISSUE TITLE
Error 500 al grabar fase de proyecto de medios

### ISSUE THREAD

**Issue by mgarciaQ76** [solop-develop/vue-1.0#1674]
## Bug report
Al grabar fase de Proyecto de medios genera error 500 (igual graba el registro)

#### Steps to reproduce

1. [Generar proyecto de medios]
2. [Generar Fase de proyecto]
3. [Grabar Fase]

#### Screenshot or Gif（截图或动态图）
![error 500 al grabar fase](https://github.com/solop-develop/frontend-core/assets/139590879/f9c5ce72-887e-4ece-9766-21902f486e25)

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:
Ocurre en la instancia 24157 (en la 24145 no se reproduce)
Organizacion Agencia SA
Rol agencia admin

**Comment by Ricargame** [comment]
https://github.com/user-attachments/assets/092713c2-c617-4e2b-aef2-27d45e976e07
