### ISSUE TITLE
Error al cargar archivo desde cargador de archivo

### ISSUE THREAD

**Issue by mgarciaQ76** [solop-develop/vue-1.0#1675]
## Bug report
Al intentar cargar archivo desde el cargador de archivo genera error 

#### Steps to reproduce

1. [Ingresar a cargador de archivo y seleccionar tabla]
2. [cargar archivo]

#### Screenshot or Gif（截图或动态图）
![error al cargar archivo 145](https://github.com/solop-develop/frontend-core/assets/139590879/3ee28da2-7066-428c-bff0-a364e2ef9914)
![error al cargar archivo](https://github.com/solop-develop/frontend-core/assets/139590879/ba3ccca1-f433-4b6a-8cbc-8adbbed46cf9)

#### Expected behavior
Que se adjunte el archivo

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:
Se probó en instancia 24157 y en la 24145 (dio error diferente en ambas)
Organización Constructora
Rol Administrador

#### Additional context
[Importacion materiales electricos.txt](https://github.com/solop-develop/frontend-core/files/13480240/Importacion.materiales.electricos.txt)
archivo que se intentó adjuntar (se seleccionó "carga de productos")

**Comment by EdwinBetanc0urt** [comment]
Falta gestionar la previsualización en el backend.

**Comment by niclopup** [comment]
Se seguirá en ISsue #1172
