### ISSUE TITLE
Error al grabar línea de Fase de proyecto de medios

### ISSUE THREAD

**Issue by mgarciaQ76** [solop-develop/vue-1.0#1676]
## Bug report
Al intentar grabar línea de fase de proyecto de medios genera mensaje de restricción indicando que faltan completar campos. pero son campos que no están habilitados para edición.

#### Steps to reproduce

1. [Generar proyecto de Medios]
2. [Generar Fase de proyecto]
3. [Generar línea de Fase y grabar]

#### Screenshot or Gif（截图或动态图）
![error en linea de fase de proyecto de medios](https://github.com/solop-develop/frontend-core/assets/139590879/62e8ecf9-9030-4ed2-bb98-1d2ed46e9f6c)

#### Expected behavior
Poder grabar. No debe controlar la existencia de datos en campos no editables.

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:
instancia 24157
Organización Agencia SA
Rol: admin agencia

#### Additional context
En la instancia 24145 este problema no se genera (graba ok línea de fase)

**Comment by EdwinBetanc0urt** [comment]
Cambios disponibles a partir del frontend `4.4.021-rc-1`

https://github.com/user-attachments/assets/a0b44780-8a10-4366-a8d4-6a476887f4c2
