### ISSUE TITLE
Error al seleccionar en un filtro "no tiene valor"

### ISSUE THREAD

**Issue by mgarciaQ76** [solop-develop/vue-1.0#1679]
## Bug report
En órdenes de venta si quiero filtrar y en Fecha orden selecciono "no tiene valor" queda el filtro quemado y sin luego poder modificar nada. Probé entrar y salir, reiniciar cache. Pero queda ya con esa selección definitiva sin poder cambiar

#### Steps to reproduce

1. [Ingresar a ordenes de venta]
2. [Seleccionar filtro fecha orden no tiene valor]

#### Screenshot or Gif（截图或动态图）
![error al seleccionar no tiene valor](https://github.com/solop-develop/frontend-core/assets/139590879/5e96efd2-113a-45a1-9dbf-be48a2888195)

#### Expected behavior
Permitir utilizar el filtro y luego modificar dicha seleccion

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:
instancia 24157 (tambien ocurre en la 24145)
Organización Agencia SA
Rol admin agencia 

#### Additional context
Esto ocurre también en rol field services de Org demo en work order

**Comment by EdwinBetanc0urt** [comment]
Esto esta relacionado con este issue https://github.com/solop-develop/frontend-core/issues/1657 y fue corregido en este cambio https://github.com/solop-develop/frontend-core/pull/1665 aun esta en estatus por montar, al generar release les sera notificado para que monten los cambios
