### ISSUE TITLE
Cambios en Vista de una Solicitud "Issue" como Mono-Registro en Forma Issues

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#1682]
## Feature request

Se desean aplicar los siguientes cambios en la issue cuando se ve como mono registros para que se logre mostrar todos los datos que un usuario necesite ver y no tenga que navegar a la ventana de Request.

**Cambios a agregar en Mono registro:**

- Categoría de Solicitud
- Grupo de Solicitud
- SDN
- Solicitud Relacionada
- Proyecto
- 

#### Describe the solution you'd like

Un ejemplo que podemos tomar como referencia puede ser el siguiente:

![COR Crear Nueva Tarea completa](https://github.com/solop-develop/frontend-core/assets/31936815/c6d413aa-0b6b-4431-a2f4-503298bf6aed)

1. Detalle
2. Mensajes: Tabla R_RequestUpdate
4. Adjuntos
5. Historial: Entiendo que esto es lo que ahora se ve en el Feed. Está perfecto cmo se ve actualmente pero está bueno verlo en una pestaña en el lateral así no queda muy cargado.
7. Tiempo Dedicado: Actualmente no existe nada en ADempiere. Pendiente de definir. Crearía sólo la pestaña para cargar info más adelante.
9. Descripción
10. Checklist: Entiendo que si damos soporte a esta petición podría ser suficiente de momento. https://github.com/solop-develop/frontend-core/issues/1537 . Lo que si creo que estaría bueno es ver si se puede hacer una SUMA de los checks que estén en “Y” y  los que estén en “N” para saber cuando falta de avance de esta Tarea.
13. Subtareas
14. Información general Tarea 

> 15. Comienzo 
> 16. Fecha siguiente acción
> 17. Estado
> 18. Prioridad
> 19. Categoría
> 20. Estado
> 21. Asignado a (
> 22. Miembros (Tabla R_RequestUpdates)
> 

Ver ejemplo
https://youtu.be/gPoqEVvOqiQ?si=6mVnPlgJnvMFbC0b&t=46

**Comment by EdwinBetanc0urt** [comment]
![imagen](https://github.com/solop-develop/frontend-core/assets/20288327/bc2a679e-7db0-4ed1-bdf7-668750d36df4)
