### ISSUE TITLE
Bandeja de entrada (Histórico de Avisos en la Home)

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#1683]
## Feature request

Se desea poder darle una mejor utilización a la pagina de inicio (home) mostrando por ejemplo un resumen de lo último que sucedió en la organización que le sea de interés a cada usuario. entiendo que esto en alguna medida actualmente se está transmitiendo en la ventana "Avisos" que se puede acceder desde las actividades de ZK.

Se desea reutilizar el diseño que actualmente tiene en la sección de Perfil, Histórico de Procesos, pero mostrar de esta manera los registros que se muestra a cada usuario en la ventana  "Avisos".

![historico de e procesos](https://github.com/solop-develop/frontend-core/assets/31936815/03a2d49f-0c14-4457-a496-263d22ac07e9)

![botón avisos](https://github.com/solop-develop/frontend-core/assets/31936815/6fccf09d-6fa7-4be8-921b-9d9d6df73b9b)
![ventana avisos](https://github.com/solop-develop/frontend-core/assets/31936815/e456033d-8fc7-43c6-8777-6fac8c43a601)

la iudea es que esto se muestre en una ventana especial de Avisos si se hace click en el botón de avisos:

![image](https://github.com/solop-develop/frontend-core/assets/31936815/6e2a34fa-7897-4235-be98-78482678e15d)

pero también que se muestre en donde ahora es la primer opción a los Tableros. Es mucho más rico ver esta información de lo último que sucedió en la organización que ver una gráfica.

![Cambios de Bandeja de Entrada en panel de control](https://github.com/solop-develop/frontend-core/assets/31936815/cc6e71bb-e4bd-4135-bdfd-b233e4205480)

![Bandeja de Entrada en usuarios en el Panel de Control](https://github.com/solop-develop/frontend-core/assets/31936815/9db9b050-2196-488f-b809-1f882a88e450)

**Comment by niclopup** [comment]
Se desea aplicar una vista más clara de la forma que se muestran los avisos:

La idea es que se parezca más a esto y no a una tabla directamente.

![image](https://github.com/solop-develop/frontend-core/assets/31936815/fb077af9-5e72-4865-a4db-28a94e88085e)

Creo que muchos campos que ahora se ven en ineas podemos darle una vuelta para que queden más lindos.

Comentar que les parece y si hay una manera que se acerca más a esta nueva idea que a una tabla comentar también asi podemos ver de hacer algo por el momento. 

notar también que falta el check de "Processed" para que no aparezca más esos avisos. Sería un "Leído"


Se detalla en este jamboard.

https://jamboard.google.com/d/1IuYUF5KEDWlwcz-FDk-aWt5yUELxUUM8Rnz34umLZUM/edit?usp=sharing

**Comment by EdwinBetanc0urt** [comment]
Cambios disponibles a partir del backend https://github.com/solop-develop/adempiere-grpc-server/releases/tag/3.6.0 y del frontend https://github.com/solop-develop/frontend-core/releases/tag/4.3.2



https://github.com/user-attachments/assets/71647da3-322e-48d4-a7d3-9e3548fcf56d
