### ISSUE TITLE
Permite seleccionar Producto inactivo

### ISSUE THREAD

**Issue by mgarciaQ76** [solop-develop/vue-1.0#1685]
## Bug report
Ingreso a work order y me permite seleccionar un producto que se encuentra inactivo

#### Steps to reproduce

1. [crear o consultar work order]
2. [vincular producto]
3. [seleccionar producto inactivo]

#### Screenshot or Gif（截图或动态图）

https://github.com/solop-develop/frontend-core/assets/139590879/7db81b91-eeb1-4a4d-9f70-1fe0e59ecef1

#### Expected behavior
Que filtre los inactivos y no me los permite seleccionar

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:
Instancia 24157 
Org DEMO
Rol Field services

**Comment by EdwinBetanc0urt** [comment]
Analizando como lo hace el zk/swing (debido a el backend-grpc ejecuta la consulta sql que genera adempiere) luego de listar los registros recorre todos los elemento para eliminar aquellos que están inactivos (lo cual es ineficiente ya que debería filtrarlos directamente en la consulta sql).

![imagen](https://github.com/solop-develop/frontend-core/assets/20288327/3798ed9e-958f-461a-a74a-bb39dabb1fb8)

Se tiene que buscar la forma de agregar la restricción `IsActive='Y'` a la consulta sql que genera adempiere en el backend.
