### ISSUE TITLE
Proceso: Manejo > Salida

### ISSUE THREAD

**Issue by elsiosanchez** [solop-develop/vue-1.0#17]
Se requiere ver la respuesta o la salida del proceso ejecutado. Actualmente en la interfaz ZK al terminar de ejecutar el proceso te muestra una ventana con la respuesta o la salida del proceso 

![zk](https://user-images.githubusercontent.com/45974454/166947334-425f38a7-2ebe-4bcb-a0e8-0da7c8401512.gif)

**Comment by elsiosanchez** [comment]
En la interfaz de ADempiere-vue para ver la respuesta o la salida del proceso ejecutado hay 2 formas


1 Ejemplo Al terminar la ejecución se muestra una notificación y dentro en del dialogo muestra la respuesta del proceso

![image](https://user-images.githubusercontent.com/45974454/166950322-cddd9931-318f-4ad8-b9fb-a4d0f467b488.png)


2 Ejemplo Puede dirigirse a la ventana del Histórico Procesos donde tendrá el historia de todos los proceso ejecutados durante la sesión, también podrá ver la salida o el detalle del proceso, también tiene la opción de acercarse al proceso ejecutado

![image](https://user-images.githubusercontent.com/45974454/166950485-9d2c813e-4596-43fc-911a-99b8b4387360.png)

**Comment by EdwinBetanc0urt** [comment]
Para el caso de uso de pruebas ver:
https://solop-develop.github.io/frontend-core/es/guide/use-cases/process.html#salida
