### ISSUE TITLE
No permite completar orden de venta (y el estado del doc está en inglés)

### ISSUE THREAD

**Issue by mgarciaQ76** [solop-develop/vue-1.0#1700]
## Bug report
Se generó una orden de venta desde proyecto de medios. Al consultar la ov no se habilita el bóton para completar la ov. A su vez, el estado de la ov está en inglés, cuando se seleccionó idioma español.

#### Steps to reproduce

1. [Genero orden de venta desde proyecto de medios]
2. [consultar la ov para completarla]

#### Screenshot or Gif（截图或动态图）

https://github.com/solop-develop/frontend-core/assets/139590879/6266fdb0-b4a4-4322-a039-374858413a03

Uploading No permite completar ov y estado doc en ingles ‐ Hecho con Clipchamp.mp4…

Link para ver el video
https://clipchamp.com/watch/BTqhX9AeO0y

#### Expected behavior
Que permita selecciionar el botón para completar la ov (y ver estado de doc en español)

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:
instancia 24157
rol admin agencia
orden de venta 12321
Esto ocurre también en la 24145 (en zk habilita ok el botón para completar)

**Comment by niclopup** [comment]
el problema fue el check de "IsDocument" en la Tabla "C_Order"
