### ISSUE TITLE
Formato incorrecto de fecha en pestaña órdenes de venta, proyecto de servicio, WO (en español)

### ISSUE THREAD

**Issue by mgarciaQ76** [solop-develop/vue-1.0#1702]
## Bug report
En la pestaña cuotas de contrato servicio educación está el formato fecha al revés (en español) si comparamos con zk. 

#### Steps to reproduce

1. [Cosultar Contrato de servicio]
2. [consultar pestaña cuotas]

#### Screenshot or Gif（截图或动态图）

https://github.com/solop-develop/frontend-core/assets/139590879/d5dc2cf0-312b-49d7-ac17-fe582e76e70c

#### Link to minimal reproduction（最小可在线还原demo）
!https://cdn.discordapp.com/attachments/1056933419415769208/1181332733243433041/image.png?ex=6580acd7&is=656e37d7&hm=1eb25dae0177be030ddac51d09531b0d5195877c7515ac382237eb5847890d1b&!

#### Expected behavior
Mostrar la fecha en mismo formato que en zk (esto se probó en otras ventanas y está en el mismo formato como en proyecto de servicio y órdenes de venta

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:
instancia 24157 
Pestaña Cuotas en COntrato de Servicio con rol "Educación Admin"
Org Colegio

**Comment by EdwinBetanc0urt** [comment]
Corregido y disponible a partir del release https://github.com/solop-develop/frontend-core/releases/tag/3.3.9 del frontend

**Comment by mgarciaQ76** [comment]
Verificado ok
