### ISSUE TITLE
Ordenamiento por fecha según grilla no funciona

### ISSUE THREAD

**Issue by mgarciaQ76** [solop-develop/vue-1.0#1707]
## Bug report
En proyecto de servicio se prueba ordenamiento ascendente/descendiente en formato grilla, pero por fecha no estaría funcionando

#### Steps to reproduce

1. [ingresar a Proyecto de servicio]
2. [seleccionar formato grilla]
3. [cambiar ordenamiento por fecha]

#### Screenshot or Gif（截图或动态图）
https://cdn.discordapp.com/attachments/1056933419415769208/1181346258330333224/Ordenamiento_por_Fecha_segun_Grilla_no_funciona.gif?ex=6580b970&is=656e4470&hm=d7b734c46f82274405f5b5d9a3732fb122acc8c3ff88dcfaccb7a9784135c43e&

#### Link to minimal reproduction（最小可在线还原demo）
!https://cdn.discordapp.com/attachments/1056933419415769208/1181346258330333224/Ordenamiento_por_Fecha_segun_Grilla_no_funciona.gif?ex=6580b970&is=656e4470&hm=d7b734c46f82274405f5b5d9a3732fb122acc8c3ff88dcfaccb7a9784135c43e&!

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:
instancia 24157
rol field services

**Comment by niclopup** [comment]
funciona ok
