### ISSUE TITLE
Errores varios al iniciar sesión y abrir ventana Issues

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#1712]
## Bug report
Al iniciar sesión aparecen muchos carteles de errores. También sucede al abrir ventana de issues

#### Screenshot or Gif（截图或动态图）

https://github.com/solop-develop/frontend-core/assets/31936815/2b490e02-5f78-4c2f-8cfc-4a0619617a17

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version: http://host.solopapp.com:24157/#/Issues

**Comment by EdwinBetanc0urt** [comment]
Uno de los errores es que no consigue el serivicio http://host.solopapp.com:24158/api/general-ledger/accounts/schemas/1000001/elements para los elementos contables.

Otro de los errores es al consultar la imagen http://host.solopapp.com:24158/api/file-management/resources/file-name/0670de31-e6a3-4a82-9f86-9a0ca4534ffa-ISO-Solop-Blanco.png?width=50&height=50
