### ISSUE TITLE
Solicitud creada desde Zk no se visualiza en pestaña "Request" en VUE

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#1713]
## Bug report

Si se crea una solicitud desde ZK donde se vincula con un proyecto (C_Project_ID) esto hace que desde la ventana Proyectos se pueda visualziar la solicitud correspondiente desde el botón de "Solicitudes"

![image](https://github.com/solop-develop/frontend-core/assets/31936815/c28182c3-0c7d-43d5-a597-94bdbc567fd6)

Ahora se intenta visualizar esta información desde VUE pero por alguna razón no las muestra. Sólo muestra solicitudes que hayan sido creadas desde VUE

![image](https://github.com/solop-develop/frontend-core/assets/31936815/11d1cad1-c730-4d4b-aaae-5efd4db16277)

#### Steps to reproduce

1. Abrir ventana Projectos desde ZK
2. Crear una solicitud desde el botón de "Solicitudes"
3. ver si se visualiza desde el proyecto en VUE

#### Screenshot or Gif（截图或动态图）
![Solicitud creada desde ZK no se visualiza vinculada a proyecto en VUE](https://github.com/solop-develop/frontend-core/assets/31936815/6dface16-3317-420d-8073-57313c433188)

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version: http://host.solopapp.com:24157/

**Comment by elsiosanchez** [comment]
@niclopup esto se solvento por favor volver a probar http://spdev02.solopapp.com:24810/vue#/

https://github.com/user-attachments/assets/e46d9deb-909e-4aa2-be56-d660c09a11d0
