### ISSUE TITLE
Error al grabar línea de ov

### ISSUE THREAD

**Issue by mgarciaQ76** [solop-develop/vue-1.0#1717]
## Bug report
Luego de grabar el cabezal de la orden de venta, intento grabar la línea de ov y genera error 500

#### Steps to reproduce

1. [Generar orden de venta, cabezal]
2. [generar nueva línea y grabar]

#### Screenshot or Gif（截图或动态图）

https://github.com/solop-develop/frontend-core/assets/139590879/94340b85-8a11-49d1-a2e3-ef5591fc2ade

#### Expected behavior
Que permita grabar la línea de la orden

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:
Instancia 24157
Rol Distribucion y logistica
ventana órdenes de venta
En 24145 graba ok

**Comment by EdwinBetanc0urt** [comment]
No puedo replicar el error, alguna consideración especifica?

https://github.com/solop-develop/frontend-core/assets/20288327/c81725dc-f3f2-49e3-86e2-a1ca8220d829

**Comment by EdwinBetanc0urt** [comment]
Se hizo la prueba en la ventana equivocada

![imagen](https://github.com/solop-develop/frontend-core/assets/20288327/bbc60751-9d18-4877-ab97-ade5385eb011)

El error es el siguiente: `"Producto no esta en lista de precios - No. Línea:10, Producto:25 VASOS DE PP FLUO COLOR ROJO DE 330ML, Lista de Precios:Sales Apartments, Fecha:06/12/2023"` sin embargo no se le esta notificando correctamente al usuario.
