### ISSUE TITLE
Error 400 al aceptar asignación de pago

### ISSUE THREAD

**Issue by mgarciaQ76** [solop-develop/vue-1.0#1718]
## Bug report
Al aceptar una asignación de pagos genera error 400

#### Steps to reproduce

1. [Seleccionar documento por cobrar y pago a asignar]
2. [aceptar]

#### Screenshot or Gif（截图或动态图）
https://cdn.discordapp.com/attachments/1181675694258929694/1181676215308922890/Error_al_procesar_Asignacion_de_Pagos_vue_trranscoding.gif?ex=6581ecbc&is=656f77bc&hm=9b3eab3367a7bb973ab6fa4670a8c87b1ea0a4d5cd5d7f33bcacd05a3bb3630f&

#### Expected behavior
Permitir generar la asignación de pago

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:
instancia 24157
Org: agencia SA
rol administrador

**Comment by niclopup** [comment]
reutilizo esta issue sobre asignación de pagos. 

en transcoding se ve mal la forma de "asignación de pagos", no se ven bien los campos tanto de manera horizontal (se tiene que hacer scroll lateral para ver el importe asignado) y tampoco se ven los totales y los botones de acción contra abajo de la ventana. estos deberían verse siempre y si hay datos se debe agregar scroll  para abajo.

![image](https://github.com/solop-develop/frontend-core/assets/31936815/504991e8-d893-46eb-9720-44a6dc960e48)


https://github.com/solop-develop/frontend-core/assets/31936815/ba385a0b-a2b1-4217-bbde-66bc94c0182e

**Comment by EdwinBetanc0urt** [comment]
Corregido

https://github.com/solop-develop/frontend-core/assets/45974454/42d2e0eb-000b-430f-8d56-18f19421ef00
