### ISSUE TITLE
No permite completar DXC

### ISSUE THREAD

**Issue by mgarciaQ76** [solop-develop/vue-1.0#1720]
## Bug report
Luego de grabar cabezal y línea del documento por cobrar, no permite seleccionar el procesar (completar) el documento.

#### Steps to reproduce

1. [grabar cabezal y línea del DXC]
2. [Completar DXC]

#### Screenshot or Gif（截图或动态图）

https://github.com/solop-develop/frontend-core/assets/139590879/37d0c742-bc89-4796-b652-ac9b0661fc39

#### Expected behavior
Que permita completar el DXC

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:
Instancia 24157
Rol Distribución y logística
Documento por cobrar DR- 1037
Esto ocurre también con los documentos por pagar

**Comment by EdwinBetanc0urt** [comment]
El error esta en la tabla `C_Invoice` que no esta marcada como documento

![imagen](https://github.com/solop-develop/frontend-core/assets/20288327/0d3f3e8b-db1b-4ee8-a8a1-098045c80975)


https://github.com/solop-develop/frontend-core/issues/1700#issuecomment-1839328643
