### ISSUE TITLE
Error al completar DXC

### ISSUE THREAD

**Issue by mgarciaQ76** [solop-develop/vue-1.0#1723]
## Bug report
Al intentar completar un DXC genera error. 
Se intentó desde el botón de procesar factura. Luego se probó desde el botón de command bar (en un caso desde esta opción permitió completar y en otro caso volvió a generar error, adjunto ambos videos)
Esto ocurre también en Documento por Pagar.

Aclaración: esto ocurre completando desde el botón de la command bar, o bien, desde el botón que se habilita desde la ventana (adjunto imagen donde marco ambas opciones)

#### Steps to reproduce

1. [Consultar DXC en borrador]
2. [Completar]

#### Screenshot or Gif（截图或动态图）
https://cdn.discordapp.com/attachments/954070691987193976/1182427567400177766/image.png?ex=6584a87c&is=6572337c&hm=ea506de0244f7fdf341d1bd07cee23000018c6fe8c76d7a61cd9acda29b0286b&

https://github.com/solop-develop/frontend-core/assets/139590879/919a1b7e-d74c-4e74-89a2-d52302ec43b4

https://github.com/solop-develop/frontend-core/assets/139590879/b8edc5e4-c08b-4606-8137-8a2bbda9f8a5

#### Expected behavior
Permitir completar DXC

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:
instancia 24157
Rol Distribucion y logistica

**Comment by EdwinBetanc0urt** [comment]
Se debe sincronizar la columna `DateDoc` en la tabla `C_Invoice`.

```json
{
	"code": 13,
	"message": "org.postgresql.util.PSQLException: ERROR: column \"datedoc\" does not exist\n  Hint: Perhaps you meant to reference the column \"c_invoice.dateacct\".\n  Position: 534, SQL=SELECT AD_Client_ID,AD_OrgTrx_ID,AD_Org_ID,(SELECT AD_SysConfig_ID FROM AD_SysConfig WHERE name = 'test') AS AD_SysConfig_ID,AD_User_ID,BOMDrop,CFEAdenda,CFEBillingCriteria,C_Activity_ID,C_BPartner_ID,C_BPartner_Location_ID,C_Campaign_ID,C_CashLine_ID,C_Charge_ID,C_ConversionType_ID,C_Currency_ID,C_DocTypeTarget_ID,C_DocType_ID,C_DunningLevel_ID,C_Invoice_ID,C_Order_ID,C_POS_ID,C_PaymentTerm_ID,C_Payment_ID,C_ProjectPhase_ID,C_ProjectTask_ID,C_Project_ID,C_SalesRegion_ID,ChargeAmt,CopyFrom,CreateFrom,Created,CreatedBy,DateAcct,DateDoc,DateInvoiced,DateOrdered,DatePrinted,Description,DocAction,(select DocBaseType from c_doctype where c_doctype_id = C_Invoice.C_DocTypeTarget_ID) AS DocBaseType,DocStatus,DocumentNo,DunningGrace,ExecuteAction,FM_Account_ID,FM_Agreement_ID,GenerateTo,GrandTotal,DocumentNo || '_' || (select C_DocType.printname from C_DocType where C_DocType.C_DocType_ID = C_Invoice.C_DocTypeTarget_ID) AS Info,(SELECT TO_CHAR(DateInvoiced, 'YYYY-MM-DD') FROM C_Invoice inv WHERE inv.C_Invoice_ID=C_Invoice.C_Invoice_ID) AS Info_To,InvoiceCollectionType,IsActive,IsAllowToVoid,IsApproved,IsDiscountPrinted,IsFixedAssetInvoice,IsInDispute,IsPaid,IsPayScheduleValid,IsPrinted,IsSOTrx,IsSelfService,IsTaxIncluded,IsTransferred,IsUpdateable,M_PriceList_ID,M_RMAType_ID,M_RMA_ID,POReference,PaymentRule,Posted,Processed,ProcessedOn,Processing,Ref_Invoice_ID,Reversal_ID,S_Contract_ID,SalesRep_ID,SendEMail,TotalLines,UUID,UY_PayReceipt_ID,UY_ViaLoan_ID,Updated,UpdatedBy,User1_ID,User2_ID,User3_ID,User4_ID FROM C_Invoice WHERE (C_Invoice_ID = ?)",
	"details": []
}
```

**Comment by EdwinBetanc0urt** [comment]
Lo mismo al intentar guardar 

```json
{
	"code": 13,
	"message": "ERROR: column \"datedoc\" of relation \"c_invoice\" does not exist\n  Position: 217",
	"details": []
}
```

**Comment by EdwinBetanc0urt** [comment]
Anteriormente no indicaba el error del servidor, sin embargo pude completar varios documentos.
