### ISSUE TITLE
Scroll no se ve en ventana de "Productos" ni "Categoría de Productos"

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#1744]
## Bug report

Se encuenta un error que cuando se aumenta la cantidad de registros a visualizar en la Ventana "Productos" o "Cateogría de Productos" el scroll no se visualiza y no permite bajar a los registros inferiores.

lo raro es que en la ventana órdenes de venta por ejemplo si se ve el scroll y se puede bajar sin problema.

#### Steps to reproduce

1. abrir ventana "Productos"
2. Aumentar cantidad de registros a 50
3. intentar hacer srcoll

#### Screenshot or Gif（截图或动态图）
![Scroll no anda en ventana producto](https://github.com/solop-develop/frontend-core/assets/31936815/1d15f20f-03dd-4081-8fc1-bd786e6be0dc)

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version: Transcoding

**Comment by elsiosanchez** [comment]
https://github.com/solop-develop/frontend-core/assets/45974454/06e5c6bb-6d2c-478f-8153-38511c920ae6

Corregido
