### ISSUE TITLE
generar DxP desde Orden de Compra no funciona

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#1747]
## Bug report

Se intenta generar un DxP desde una Orden de Compra pero no se logra.

Se abre el SB de "Crear dede OC/Recepcion", se busca por orden y se encuentra la Orden de Compra que etsá pendiente de recepcionar, se marcan las líneas pero al darle OK no genera las líneas de la factura en base a las líneas de la OC seleccionada.

#### Screenshot or Gif（截图或动态图）
![Generar Documento por Pagar Desde OC no funciona Transcoding](https://github.com/solop-develop/frontend-core/assets/31936815/5e9d3871-45b7-41f9-b1dc-39ef5eed93fe)

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version: Transcoding

**Comment by EdwinBetanc0urt** [comment]
Directamente relacionado con https://github.com/adempiere/adempiere/pull/4285

**Comment by EdwinBetanc0urt** [comment]
Corregido y disponible a partir del release https://github.com/solop-develop/frontend-core/releases/tag/3.3.9 del frontend
