### ISSUE TITLE
Mejorar panel de control (Pantalla inicial)

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#1748]
## Feature request

Se desea aplicar una actualización a la pantalla de entrada donde ingresa un usuario de manera que se pueda brindar una mayor eficiencia en mostrar toda la información que un usuario necesite para hacer fácilmente su trabajo. 

Dentro de las modificaciones que se desean más que nada está la ditribución de lo que se muestra y el tamaño de los diferentes portlets 

pendiente de definir los cambios con exactitud.

**Comment by EdwinBetanc0urt** [comment]
Agregado

https://github.com/solop-develop/frontend-core/assets/45974454/c7597490-99fd-47c7-8558-580df38d6f17

**Comment by niclopup** [comment]
![image](https://github.com/solop-develop/frontend-core/assets/31936815/436bf83d-fa92-40be-a254-451a4b8cfcbb)

Conversando con yamel coincidimos que esta configuración estaría bueno dejarlo centralizado en la edición del perfil del usuario y no agregar un nuevo panel de gestión.

Por otro lado hago los siguientes comentarios de las opciones que se agregaron actualmente:

* **Habilitar Tags-View:** esta opción entiendo que lo que realiza es ocultar las pestañas de las ventanas que se tienen abiertas. puede ser? de ser así, si se ocultan, cómo podemos navegar a las ventanas que tenemos abiertas? no le veo mucha utilidad a esta opción.
* **Logotipo barra lateral:** esto es simple y debería estar definido de manera centralizada, no creo que a los usuarios les interese ocultar o mostrar esto y a nosotros nos interesa que se vea el logo del ERP. no lo dejaría editable y que siempre se muestre. Al hacer click en el logotipo barra lateral, es como mostrar el Panbel de Control no? hace la misma acción. Por eso sugiero ocultar el botón de "Panel de Control" y que si alguien quiere navegar al panel de control deberá hacer click en el logo y te va directo a la pantalla iniciial. Así quitamos un ícono que está duplicando funcionalidad (icono de panel de control)
* **Tarjeta Principal de Dashboard:** Esto lo definiría por Rol y no por usuario, pero esto lo podemos hacer luego. No veo la opción de agregar una Gráfica a esta seeción que antes si lo permitía y en algún caso estaría bueno agregar.
* Numero de Columnas: veo que este campo cambia solamente el anchon de las columnas, pero no modifica en nada el tamaño de todo lo demás, me refiero al tamaño de la fuente por ejemplo. si sólo cambiamos el ancho de la columna, los campos texto se verán más apretados. El cambio debería hacerse todo manteniendo la misma relación de tamaños. Si se pone 4 se debe reducir el tamaño de todo. 

Analizando algunos eejmplos realizo el siguiente diseño a ver cuanto nos podemos acercar

https://docs.google.com/spreadsheets/d/1oWQI6ooS-gT0PmdifC3Gg8SGnBvV5XlCmjd1jaZW36c/edit?usp=sharing


![Captura de pantalla 2024-01-09 222533](https://github.com/solop-develop/frontend-core/assets/31936815/08c48774-e6e8-4f62-8e6d-edbc37e58bd8)



Paneles actuales:

**últimos documentos**

Agregar estas líneas con un tamaño de fuente y de cada línea más pequeño. 
Fecha no le agregaría, o pondría sólo una fecha entre paréntesis siguiendo el nombre de la ventana y no en una línea aparte. todo para que quede más reducido el espacio que necesite. 



![image](https://github.com/solop-develop/frontend-core/assets/31936815/51a6aed4-ffe3-478b-bd56-b404321457ba)

**Comment by EdwinBetanc0urt** [comment]
- Eliminar el tablero de actividades (ya es redundante).
- Agregar tamaños hasta 12 de tareas pendientes, reduciendo el logo, y colocando el titulo arriba.
- Agregar hasta 6 elementos (columnas) de tableros gaguge.
- Agregar hasta 6 elementos (columnas) de tableros indicadores (nuevo `PT` `PA_DashboardContent`).
- Las vistas crear un sumario de menú y pasar allí todo lo remarcado excepto calendario y graficos.
![imagen](https://github.com/solop-develop/frontend-core/assets/20288327/3d513560-1b12-4eeb-8757-51b40af63739)
- Agrupar los gráficos de Pie (torta) a la derecha con 1/3 de tamaño a la derecha, junto a los demás tableros como recent items, actividades.
- Agrupar los gráficos con tamaño horizontal grande a la izquierda ocupando 2/3 de tamaño como barras, lineas, cascada y tableros como portlet y actividades.

![imagen](https://github.com/solop-develop/frontend-core/assets/20288327/5c201cf8-953f-4dee-9378-b22659416957)

**Comment by niclopup** [comment]
Se encuentran los siguientes detalles:

* La configuración del panel de Control no se recuerda según la definición del usuario. Si se hace cambios, la próxima vez que ingresa los mismos ya no están aplicados y el usuario debe volver a definirlos. JHay manera de dejarlos por defecto de alguna manera? si no hay manera de que el usuario los configure, cómo se puede definir por nostoros de manera general para todos los usuarios? o definirlo por Rol?

* Nombres de las columnas de Gráfico de Barras no se visualiza: en algunos casos por alguna razón el nombre del dato que se muestra en una columna no es visualizado cuando en realidad se ve bien que el mismo existe pero simplemente no lo muestra abajo 
![image](https://github.com/solop-develop/frontend-core/assets/31936815/0296c3bb-397a-4d1c-9c1a-d2ecfd68adee)

![image](https://github.com/solop-develop/frontend-core/assets/31936815/1b8a230a-3cf9-4fd9-b63d-7fe4ec058a52)

* Tamaño de los Paneles de "Favoritos" y "últimos Documentos" sigue muy grande y no eficiente. 

* La configuración de Columnas de las gráficas no responde bien.

* se ve la configuración del panel de control tanto en el panel de control como en el perfil del usuario. Donde quedará? se debería definir en un único lugar, como la configuración del usuario y que sólo ahi se defina. quuitar la configuración del Panel de control.

* Gráfico Central: estaría bueno dar la posibilidad de definir un gráfico como Central y agregarlo arriba del todo y que ocupe todo el ancho de la ventana. Esto entiendo que podría ser modificado con el botón:

![image](https://github.com/solop-develop/frontend-core/assets/31936815/7184ccfc-73ca-43b4-84f0-7bf72321b62b)

**Comment by niclopup** [comment]
relacionada con #2098

**Comment by EdwinBetanc0urt** [comment]
Disponible a partir de la versión del frontend https://github.com/solop-develop/frontend-core/releases/tag/3.8.3


https://github.com/solop-develop/frontend-core/assets/20288327/40363031-5dc6-4806-8ee6-7cc3f90752bc
