### ISSUE TITLE
smart browser sin traducción

### ISSUE THREAD

**Issue by mgarciaQ76** [solop-develop/vue-1.0#1751]
## Bug report
Detectamos que los smart browser no poseen traducción en español (como ejemplo agrego imagen de consulta de usuarios/contactos

#### Steps to reproduce

1. [ingresar al smart browser]

#### Screenshot or Gif（截图或动态图）
![Captura de pantalla 2023-12-14 095611](https://github.com/solop-develop/frontend-core/assets/139590879/2dc6fe80-7347-466d-9297-aa25620d6e94)

![Captura de pantalla 2023-12-14 095829](https://github.com/solop-develop/frontend-core/assets/139590879/c6b9d156-1a63-4a50-95f7-bffa71edc78a)

#### Expected behavior
Visualizar el nombre con traducción de acuerdo al idioma

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:
instancia 24145
rol Administrador

**Comment by yamelsenih** [comment]
Hola, esto no forma parte de este entregable

**Comment by EdwinBetanc0urt** [comment]
Directamente relacionado con https://github.com/solop-develop/adempiere-grpc-server/issues/28

**Comment by EdwinBetanc0urt** [comment]
Corregido



![Image](https://github.com/solop-develop/frontend-core/assets/20288327/d2fb8be8-5ee7-4b20-8b8f-f4efa10762e4)
