### ISSUE TITLE
Diferencias en auditoría de registro

### ISSUE THREAD

**Issue by mgarciaQ76** [solop-develop/vue-1.0#1752]
## Bug report
Agregar fechas en los datos generales de quien fue que creó el documento y también fecha en quién lo actuaolizó por último (tal como se visualiza en zk)

#### Steps to reproduce

1. [consultar registro]
2. [Visualizar su auditoría]

#### Screenshot or Gif（截图或动态图）
![screenshot (1)](https://github.com/solop-develop/frontend-core/assets/139590879/eb924ecc-a8ca-448b-a847-c4deb76c39e6)
![screenshot](https://github.com/solop-develop/frontend-core/assets/139590879/9c9cdeb4-a643-4885-b2a1-cca826906c0b)

#### Expected behavior
Visualizar la auditoría de registros con las mismas características que en zk

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:
instancia 24145
Org agencia SA
Rol administrador
orden de venta 50116

**Comment by EdwinBetanc0urt** [comment]
![imagen](https://github.com/solop-develop/frontend-core/assets/20288327/5683643c-c4fb-48fb-bbfd-51c6663ca86a)

**Comment by EdwinBetanc0urt** [comment]
Corregido y disponible a partir del release https://github.com/solop-develop/adempiere-grpc-server/releases/tag/2.1.9 del backend y https://github.com/solop-develop/frontend-core/releases/tag/3.3.9 del frontend

**Comment by mgarciaQ76** [comment]
verificado ok
