### ISSUE TITLE
Error en auditoría de registro

### ISSUE THREAD

**Issue by mgarciaQ76** [solop-develop/vue-1.0#1753]
## Bug report
Detectamos que secuencialmente no se muestran los mismos movimientos en la auditoría de un registro comparando zk con VUE.
y adicionalmente vemos que el último registro de zk, en VUE lo muestra como primer registro.
A modo de ejemplo en la imagen adjunta agrego los dos primeros movimientos de auditoría y los dos últimos de VUE comparando con zk para evidenciar que no coinciden.

#### Steps to reproduce

1. [Consultar registro]
2. [revisar auditoria]

#### Screenshot or Gif（截图或动态图）
![error en auditoria de registro](https://github.com/solop-develop/frontend-core/assets/139590879/d2f7a7a3-32f6-459c-86fe-d3e2e496a2c6)

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:
24145 (se reviso lo mismo en 24157)
Org Agencia SA
Rol Administrador

**Comment by EdwinBetanc0urt** [comment]
![imagen](https://github.com/solop-develop/frontend-core/assets/20288327/5683643c-c4fb-48fb-bbfd-51c6663ca86a)

**Comment by EdwinBetanc0urt** [comment]
Corregido y disponible a partir del release https://github.com/solop-develop/adempiere-grpc-server/releases/tag/2.1.9 del backend y https://github.com/solop-develop/frontend-core/releases/tag/3.3.9 del frontend

**Comment by mgarciaQ76** [comment]
Verificado ok
