### ISSUE TITLE
No genera entrega

### ISSUE THREAD

**Issue by mgarciaQ76** [solop-develop/vue-1.0#1754]
## Bug report
Se intenta generar una entrega desde Transcoding y no genera nada

#### Steps to reproduce

1. [Abrir proceso "Generar Entregas desde Linea de Orden"]
2. [Filtrar por SDN "Cliente Ejemplo"]
3. [Entregar Orden "50117"]

#### Screenshot or Gif（截图或动态图）
![Captura de pantalla 2023-12-14 105451](https://github.com/solop-develop/frontend-core/assets/139590879/e83e1a05-ce7d-45c1-8be2-260545b84ce4)
![Captura de pantalla 2023-12-14 105403](https://github.com/solop-develop/frontend-core/assets/139590879/0cbd170e-4988-4cd3-bec9-bbbdaf0382d8)

#### Link to minimal reproduction（最小可在线还原demo）

https://github.com/solop-develop/frontend-core/assets/139590879/2289ed36-0bfa-4630-8917-2568de4eaab1

#### Expected behavior
Que genere la entrega o indique motivo por el cual no lo genera

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:
instancia 24157
Rol Logistica y distribucion
Org Casa Central

**Comment by EdwinBetanc0urt** [comment]
El error estaba en la selección, ya fue corregido
