### ISSUE TITLE
opciones duplicadas en command bar y procesos

### ISSUE THREAD

**Issue by mgarciaQ76** [solop-develop/vue-1.0#1756]
## Bug report
hay opciones que se muestran en los Procesos que como tienen su botón en la commandbar estos quedan duplicados. la idea sería sacarlos para que sólo se puedan accionar desde la command Bar (Procesar, Nuevo registro, etc.)

Consulta, el botón de impresión, no estaría bueno agregarlo con un botón extra en la command bar de impresora que sólo aparezca cuadno el documento en cuestión tenga un formato de impresión definido?
esto sucedería con ordenes de venta, Compra, DxC DxP, etc.

#### Steps to reproduce

1. [Entrar en la ventana]
2. [comparar opciones de command bar con opciones de procesos]

#### Screenshot or Gif（截图或动态图）
![procesos](https://github.com/solop-develop/frontend-core/assets/139590879/16caabaa-3f2a-4e4c-8555-e247399062b6)

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:
instancia 24157
Rol distribucion y logistica
Org casa central

**Comment by EdwinBetanc0urt** [comment]
Se agrega el botón para impresión, disponible a partir de las versiones del backend https://github.com/solop-develop/adempiere-grpc-server/releases/tag/3.0.4 y del frontend https://github.com/solop-develop/frontend-core/releases/tag/3.6.1


https://github.com/solop-develop/frontend-core/assets/45974454/9823d56b-e483-4306-939e-95a1d8002ffc

**Comment by niclopup** [comment]
ok pero se deberia sacar de los procesos tambien

![image](https://github.com/solop-develop/frontend-core/assets/31936815/cb455ab4-3b75-4b98-b7f2-9e0b62c9a28c)

**Comment by EdwinBetanc0urt** [comment]
Creo que no, ya que hay pestañas que tienen muchos procesos asociados (sea a través de la asignación por tabla, o por procesos de campos botones), el caso de impresión es mas puntual ya que esta asociado directamente en la pestaña, podría verse muy sobrecargado.
