### ISSUE TITLE
Error POS Transcoding: No permite definir descuentos en líneas desde el POS

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#1759]
## Bug report

No se permite definir descuentos en las lienas desde el Punto de ventas desde Transcoding.

Tampoco permite definir el descuento a todas las líneas desde el proceso de "Aplicar Descuento a todas las líneas"

#### Screenshot or Gif（截图或动态图）

![image](https://github.com/solop-develop/frontend-core/assets/31936815/1f9b150a-43ac-4d5d-874d-1191a298f482)

![Dificil digitación en líneas del POS](https://github.com/solop-develop/frontend-core/assets/31936815/9f7b0128-a744-4a2a-9dc8-4406c69cfbe0)

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:

**Comment by EdwinBetanc0urt** [comment]
Corregido
