### ISSUE TITLE
Crear SDN desde POS no funciona

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#1760]
## Bug report

Se intenta crear un nuevo SDN desde un punto de venta y se encuentran los siguientes errores:

1. no permite guardar sólo con 1 dirección, se debe definir las dos. No copia dirección de entreega al parecer.

2.  Se definen las dos direcciones y al guardar da error 404

#### Screenshot or Gif（截图或动态图）

![Error crear SDN desde POS](https://github.com/solop-develop/frontend-core/assets/31936815/b10a0443-59ad-4e7b-be32-86af517f595f)

![Error crear SDN desde POS 2](https://github.com/solop-develop/frontend-core/assets/31936815/dbbd45eb-9ee0-4c9e-95c3-c6768be34cc3)

![Crear nuevo sdn desde POS no funciona](https://github.com/solop-develop/frontend-core/assets/31936815/1261db2e-6df8-48db-8359-1b727b643db5)

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:

**Comment by EdwinBetanc0urt** [comment]
Corregido

**Comment by niclopup** [comment]
sigue igual error
 da error 404 
![Error crear SDN desdE POS](https://github.com/solop-develop/frontend-core/assets/31936815/63697b4a-4feb-48aa-9be8-69c6cfb66d70)

**Comment by EdwinBetanc0urt** [comment]
Corregido
