### ISSUE TITLE
[Bug Report] Consulta de Precios con endpoints no encontrados

### ISSUE THREAD

**Issue by rcapecce** [solop-develop/vue-1.0#1761]
## Bug report

Consulta de Precios en transcoding reporta endpoints con código 404 no encontrados, aparentemente apuntan a endpoints de POS por la url aunque esta forma se abre desde fuera del pos.

**Endpoints obtenidos con error**

Al abrir Forma

* Error 500 referente al manejador de adjuntos, eso no, debemos revisarlo acá primero
* Error 404 http://host.solopapp.com:24160/api/point-of-sales/selling-points?user_uuid=&page_size=15

Al pegar desde Portapapeles un M_Product.value (obtenido desde el POS)

* Error 404 http://host.solopapp.com:24160/api/point-of-sales/product-price?search_value=P22401

En este último endpoint además se informa "Producto No Disponible"

Esto fue encontrado en Instancia Transcoding http://host.solopapp.com:24159
En Legacy http://host.solopapp.com:24148 la forma anda bien y consulta el mismo producto

Ambas instancias apuntan a la misma base de datos.

#### Steps to reproduce

1. Desde VUE abrir forma "Consulta de Precios"
2. Observar error 404 en toast
3. Pegar desde portapapeles un value obtenido del pos, puede ser en instancias de Testing el value P22401
4. Ver como informa "Producto No Encontrado"
5. Revisar pestaña Network donde se observan los 404

#### Expected behavior

Pegar value desde el portapapeles y encontrar Producto

**Comment by EdwinBetanc0urt** [comment]
Corregido
