### ISSUE TITLE
Consulta de precios e Información de Producto no se ve desde Transcoding

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#1765]
## Bug report
No se visualiza la "Consulta de precios" ni "Información Producto" desde Transcoding

Tampoco se ve Accounting Viewer pero no es tan necesario por ahora

LEGACY

![image](https://github.com/solop-develop/frontend-core/assets/31936815/d4b37306-e070-460f-bc2d-ac1af9cd17ff)

TRANSCODING

![image](https://github.com/solop-develop/frontend-core/assets/31936815/9633e5d4-f4a5-4c4c-a9d7-ee85ed5abd12)

**Comment by EdwinBetanc0urt** [comment]
Ya fue corregido, cabe destacar que el acceso se controla en el rol con el check `Allow Info Product`



![Image](https://github.com/solop-develop/frontend-core/assets/20288327/9846b22e-1fb2-4459-9bde-1781fa3670b7)
