### ISSUE TITLE
Mejorar vista del POS en Transcoding

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#1766]
## Bug report

Actualmente si se crea una nueva orden desde el pos se ven los siguientes inconvenientes:

1. Anchos incorrectos de columnas de las líneas. El ancho del producto es igual a la columna de cantidad o de descuento? Esto no debería ser así ya que un campo de nombre de producto puede ser muy extenso cuando un descuento, cantidad o precio normalmente no debería ser tanto.

**Transcoding**

![image](https://github.com/solop-develop/frontend-core/assets/31936815/da3d4cdb-ecd6-481d-912c-c2903966ac7c)

**Legacy**

![image](https://github.com/solop-develop/frontend-core/assets/31936815/b97e8949-1392-4b73-8d64-627574dd810f)

2. Información de la orden no se visualiza ok

La información de la orden, siempre debería estar contra la parte inferior de la ventana para que nunca se deba hacer scroll para ver los datos de la orden

![image](https://github.com/solop-develop/frontend-core/assets/31936815/e9c5397d-0adb-4b43-875b-d8ead6f0f2f5)

#### Steps to reproduce

1. [xxx]
2. [xxx]
4. [xxxx]

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:

**Comment by niclopup** [comment]
esto ya estaba montado para verificar correcto?

agrego algunos cambios más

1. Espacio libre entre las líneas del POS y la información de la orden. Reducir al minimo de que quede libre.

![Espacio libre lineas en POS](https://github.com/solop-develop/frontend-core/assets/31936815/6a12fcdd-0ce4-499c-bede-6e07e419e143)

2. Mejorar más espacio de Columnas en líneas de POS

![Mejroar tamaño Columnas POS](https://github.com/solop-develop/frontend-core/assets/31936815/b3327da8-022c-4881-abbd-05a6009608d2)

**Comment by yamelsenih** [comment]
Hola, está actividad no corresponde a este entregable, la voy a sacar de aquí. Si ya se hizo algo se queda hasta donde se hizo pero no corresponde al entregable

**Comment by EdwinBetanc0urt** [comment]
Esto ya se había resuelto el 18 de diciembre, esta `Por Entregar`.
