### ISSUE TITLE
Anular Transacción de Ventas no funciona desde Transcoding

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#1767]
## Bug report

Se intenta correr el proceso pero no se visualiza para poner el comentario y darle OK

Transcoding

![image](https://github.com/solop-develop/frontend-core/assets/31936815/199830b2-72b3-47c5-a440-57d5c505ffcd)

Legacy

![image](https://github.com/solop-develop/frontend-core/assets/31936815/1e0d8313-8ee7-4ec6-a774-38f4fad6e74f)

#### Steps to reproduce

1. [xxx]
2. [xxx]
3. [xxxx]

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:

**Comment by EdwinBetanc0urt** [comment]
Corregido
