### ISSUE TITLE
[Bug Report] Forma Consulta de Precios cierra sesión después de un tiempo

### ISSUE THREAD

**Issue by rcapecce** [solop-develop/vue-1.0#1768]
## Bug report

Actualmente la forma Consulta de Precios al igual que el resto de ventanas, después de un tiempo de inactividad cierra sesión en vue y requiere volver a logearse para interactuar.

Esto en un escaner de gondola no es viable que se requiera a un operario que inicie sesión cada un tiempo.

---

Sería para algo como esto pero con la forma de Vue en pantalla

![image](https://github.com/solop-develop/frontend-core/assets/14218144/93d833fb-bc73-44f8-a15a-268ba24309ec)

---

Hay forma de configurar o modificar para que solo esa forma requiera login pero su sesión no expire?
(El resto de ventana si es correcto que expire con el tiempo)

**Comment by yamelsenih** [comment]
Hola, nosotros hicimos todo lo posible para que la forma de vue se adaptara pero el problema no es la sesión sino adaptarlo. Te recomiendo que consumas el API desde una app en android o flutter, eso fue lo que hice. Lo hice con flutter y Rust porque no teníamos el Envoy proxy
