### ISSUE TITLE
POS: Botón del Retiro del Punto de venta no funciona

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#1770]
## Bug report

Se intenta hacer un retiro del punto de venta desde el POS pero no realiza ninguna acción al hacer click en el botón.

#### Screenshot or Gif（截图或动态图）

![image](https://github.com/solop-develop/frontend-core/assets/31936815/06ab896d-fec9-44f2-8627-7a41e80e9c7a)

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version: Transcoding VUE

**Comment by EdwinBetanc0urt** [comment]
Corregido
