### ISSUE TITLE
POS: Moneda en Apertura muestra ID en vez de Nombre

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#1771]
## Bug report

En moneda dice 142 en vez de UYU

también se consulta por que cuando genera el pago, muestra el importe definido en 5000 ok pero luego muestra UYU 0,00 

#### Steps to reproduce

Apertura de Caja desde un Punto de ventas

#### Screenshot or Gif（截图或动态图）

![image](https://github.com/solop-develop/frontend-core/assets/31936815/52ef9fb2-5ed5-4bf4-8478-cc64abaa86b6)

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version: Transcoding

**Comment by EdwinBetanc0urt** [comment]
Por favor verificar si existe tasa de cambio registrada, ya que al parecer no esta devolviendo el monto convertido

![imagen](https://github.com/solop-develop/frontend-core/assets/20288327/78a4c1b1-5ddf-4ba7-be13-2fa4dc72674f)

**Comment by niclopup** [comment]
pero por que habría de mostrar el monto convertido? en este caso sólo queremos mostrar los importes en l amoneda de la lista de precios que es PESO URUGUAYO. no se desea ver nada convertido a dólares.
Hay manera de configurar para definir si una terminal de PDV desea utilizar la conversión o no?

Más allá de esto, el cartel sigue mostrando la moneda del pago según el ID y no el nombre

![image](https://github.com/solop-develop/frontend-core/assets/31936815/e52a6930-e456-4425-b87f-e205a0f6ca57)

**Comment by elsiosanchez** [comment]
![image](https://github.com/solop-develop/frontend-core/assets/45974454/1f266551-4170-48a3-8aeb-e959b3b85a42)

@niclopup @yamelsenih 
![image](https://github.com/solop-develop/frontend-core/assets/45974454/d50ecd9f-03b3-4358-ac5c-83298cc1b460)

Si no se genera una taza de conversion con el tipo de converision asociado del  punto de venta. El servicio `ListAvailableCurrencies` lo trae vacio

**Comment by EdwinBetanc0urt** [comment]
Se corrigió con una via alterna desde vue, estableciendo los valores de la moneda del método de pago si el id de esa moneda coincide con el del campo
