### ISSUE TITLE
POS: Corrección de Campos Totales

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#1773]
## Bug report
Se visualizan dos errores en los campos de totales del Punto de Vetnas. 

estos son: 

* Fecha: se muestra con formato raro de y no se ve con formato de dd/MM/yyyy
* Convertido: debería haber una manera de configurar si un punto de vneta desea mostrar el campo convertido o no. En nuestro caso no se utilziará por lo que deberíamos configurar la terminal PDV de una manera para que el campo no se visualice nunca.

#### Screenshot or Gif（截图或动态图）

![image](https://github.com/solop-develop/frontend-core/assets/31936815/008b3022-70f1-4050-a88a-061b2381638c)

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:

**Comment by EdwinBetanc0urt** [comment]
Se corrigió el formato de la fecha, se debe definir todo lo que tiene el monto convertido, para el caso de totales de la orden, pagos y apertura/cierre de caja.
