### ISSUE TITLE
POS: Cobro con importe diferente a orden

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#1774]
## Bug report
Se crea una orden definiendo un único producto, se modifica la cantidad desde las líneas utilizando el las flechas del campo de cantidad. se procede a pagar y veo que el iomporte no se actualizó por el total de la orden sino que sigue conel importe de 1 unidad del producto en vez de las 4 que defini. 

#### Screenshot or Gif（截图或动态图）

https://github.com/solop-develop/frontend-core/assets/31936815/c5c5f973-0935-4d11-b4a9-0f3d2f03f388

La ov la veo bien en ZK

![image](https://github.com/solop-develop/frontend-core/assets/31936815/876523e6-247d-4fac-b19b-0db4a89139e5)

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:

**Comment by EdwinBetanc0urt** [comment]
Corregido
