### ISSUE TITLE
POS: Detalles del Pago no se visualizan

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#1775]
## Bug report

Al momento de realizar el pago desde el punto de venta, no se está visuaizando el detalle del pago, esto estaba bueno ya que puede auyudar al usuario a ver algún error.

En cuanto a los campos a mostrar, al igual a lo que pasaba con el campo "Convertido" en el total de la orden, los campos de "Tasa del Día" no se debería mostrar si no se tiene conversión. Esto como sugerencia, si o s epuede no hay problema. 

#### Screenshot or Gif（截图或动态图）

VUE Transcoding

![image](https://github.com/solop-develop/frontend-core/assets/31936815/795a25c4-c140-4f7f-826a-f6fa059abc31)

**Vue Legeacy**

![image](https://github.com/solop-develop/frontend-core/assets/31936815/6dac4f99-d81b-4be3-8bf1-2317c616b8d2)

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:

**Comment by EdwinBetanc0urt** [comment]
Si se visualizan
![imagen](https://github.com/solop-develop/frontend-core/assets/20288327/96c08a11-4c5a-42b7-b7c2-cde2d79b4729)
