### ISSUE TITLE
POS: Aplicar Descuento a todas las líneas no funciona acción

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#1783]
## Bug report
No funciona acción (Botón)

#### Screenshot or Gif（截图或动态图）

![image](https://github.com/solop-develop/frontend-core/assets/31936815/b9ca048b-9ca8-4158-b559-f054664ada84)

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version: Transcoding
-

**Comment by EdwinBetanc0urt** [comment]
Corregido
