### ISSUE TITLE
Retiro dice "Caja Aperturada" al finalizar proceso

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#1793]
## Bug report
Se realiza el procesoo de Retiro de caja correctamente pero al finalizar el cartel dice "Caja Aperturada" que hace confundir al usuario.

![image](https://github.com/solop-develop/frontend-core/assets/31936815/5d17db4f-1b5a-45c8-9e53-7d666d727ab2)

#### Screenshot or Gif（截图或动态图）
![Retiro dice  Caja aperturada  en Msj del proceso](https://github.com/solop-develop/frontend-core/assets/31936815/9392d518-513c-4ef2-bb49-dfce0da3b8d2)

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version: Transcoding

**Comment by EdwinBetanc0urt** [comment]
Corregido
