### ISSUE TITLE
Proceso: Manejo > Ejecución

### ISSUE THREAD

**Issue by elsiosanchez** [solop-develop/vue-1.0#18]
Actualmente en la interfaz ZK  al ejecutar el proceso queda la ventana cargando hasta que acabe la ejecución de dicho proceso el cual no permite al usuario realizar otras tareas hasta que se termine el proceso 

### GIF
![zk](https://user-images.githubusercontent.com/45974454/166952162-8ca15dfc-1c21-47b5-9d5a-b48b1bbd9983.gif)

**Comment by elsiosanchez** [comment]
En ADempiere-Vue al ejecutar un proceso se cierra la ventana y el proceso queda ejecutándose en segundo plano. Esto le permite al usuario realizar otra acción o tarea dentro del sistema sin interrupción al terminar de ejecutarse el proceso le enviara una notificación al usuario informando el resultado

### GIF
![Ui](https://user-images.githubusercontent.com/45974454/166953003-b54a4753-b13b-480c-9ac2-f9cdad9356f4.gif)

**Comment by EdwinBetanc0urt** [comment]
Para el caso de uso de pruebas ver:
https://solop-develop.github.io/frontend-core/es/guide/use-cases/process.html#ejecucion-2
