### ISSUE TITLE
Actividades del Flujo de trabajo en Transcoding mal

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#1800]
## Bug report

Se perdió lo que habíamos ordenado en Legacy. Las actividades de flujo de trabajo en transcoding se ven mal

#### Screenshot or Gif（截图或动态图）
El mismo ejemplo en uno y en otro.

En transcoding ni muestra los registros.

Caso: Rol "Aprobador"

agregarse para poder verlo para aprobar

**Legacy**
![image](https://github.com/solop-develop/frontend-core/assets/31936815/331050dc-11b0-4d04-9a10-3f915b375f1d)

**Transcoding**

![image](https://github.com/solop-develop/frontend-core/assets/31936815/b70a7143-5240-4cfd-ba96-be6685615d22)

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:

**Comment by EdwinBetanc0urt** [comment]
Corregido

![Image](https://github.com/solop-develop/frontend-core/assets/20288327/1714dcfd-0c43-4ff4-8bbe-d097a10c0f9a)

**Comment by niclopup** [comment]
No funciona el Acercar al Documento


![image](https://github.com/solop-develop/frontend-core/assets/31936815/b179e8a0-4ea3-404a-8132-4a5532b132b9)

**Comment by EdwinBetanc0urt** [comment]
Corregido y disponible a partir del release https://github.com/solop-develop/frontend-core/releases/tag/3.3.9 del frontend

**Comment by EdwinBetanc0urt** [comment]
![Image](https://github.com/solop-develop/frontend-core/assets/20288327/707d0d25-ce66-4003-a27c-c7beac183fd1)
