### ISSUE TITLE
Crear SDN desde POS: Campo Ciudad no muestra lista 

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#1813]
## Bug report
Al momento de crear un SDN, cuando se va a definir Ciudad como no muestra un listado, si uno escribe la ciudad con una pequeña diferencia (letra minúscula en vez de mayúscula) no lo definirá según el listado.

![image](https://github.com/solop-develop/frontend-core/assets/31936815/3c76c741-b8a1-42bd-b659-5d87dc8d245d)

Se puede hacer que en este campo se muestre el mismo listado que aparece al crear una dirección desde la pestaña localización de la ventana SDN?

![image](https://github.com/solop-develop/frontend-core/assets/31936815/e3e39e6a-c86f-40bf-abb5-702ab5a17ae7)

Si le erras entonces define la ciudad en 0
![image](https://github.com/solop-develop/frontend-core/assets/31936815/7ac5c4a5-02ed-4111-8df7-258456dc884c)

**Comment by EdwinBetanc0urt** [comment]
En la definición del país (Uruguay) tiene habilitado para permitir guardar ciudades fuera de la lista, cuando eso ocurre no muestra la lista desplegable sino un campo de texto


![imagen](https://github.com/solop-develop/frontend-core/assets/20288327/613106b3-39ef-4ad0-8681-a949a6ad1788)

**Comment by EdwinBetanc0urt** [comment]
Al estar en falso el check de `Permite Ciudades Fuera de la Lista` en la definición del País, el campo ciudad pasa de campo de texto a campo de lista desplegable:

![imagen](https://github.com/solop-develop/frontend-core/assets/20288327/7f355f48-acc1-430c-8b51-dd8dd5f31079)
