### ISSUE TITLE
Tiempo de respuesta POS Transcoding

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#1815]
## Bug report

Se encuentra que el POS está presentando una demora importante que hace dificil trabajar con el POS en Transcoding teniendo el sistema hosteado en Digital Ocean.

Ambos Transconding tienen el mismo código

A continuación van los ejemplos:

**Legacy en Digital Ocean**

![image](https://github.com/solop-develop/frontend-core/assets/31936815/3053e0f6-693d-4600-be89-fd68c5919bd4)

**Transcoding en Digital Ocean**

![image](https://github.com/solop-develop/frontend-core/assets/31936815/47d493c5-9057-40cd-ae4d-72c22b23805e)

**Transconding en DataCenter Uruguay**

![image](https://github.com/solop-develop/frontend-core/assets/31936815/960e2702-0f62-462b-a711-21b2c0d99f06)

https://github.com/solop-develop/frontend-core/assets/31936815/17f46910-2b2a-4911-871e-d3dd9bd4b41e

Los pasos más importantes para que se mejore la respuesta del POS son:

#### Agregar nuevo Producto: 

1. Al leer un código de barra se debe cargar lo más rápido posible la línea con el Producto seleccionado y la Cantidad definda.
2. Actualizar Precio. Tanto unitario como de la línea
3. Actualizar totales de la Orden.

**Errores:**
Actualmente lo primeor que carga es el total de la orden, cuando en realidad es lo último que importa que se actualice. 

Si se lee un código de Barra y luego se lee uno nuevamente antes que cargue el primero, el buscador no busca.

Si se 

#### Completar Orden

Demora cerca de 12 segundos completar una orden.

**Comment by EdwinBetanc0urt** [comment]
Entiendo que esto esta corregido.
