### ISSUE TITLE
Consulta avanzada. incluye no incluye no tiene funcionalidad

### ISSUE THREAD

**Issue by mgarciaQ76** [solop-develop/vue-1.0#1823]
## Bug report
detectamos que en la consulta avanzada, las opciones de cada filtro están ok, excepto el de incluye / no incluye. En este caso el campo se mantiene editable pero cualquier dato que ingreso lo borra. Si solicito la busqueda con una u otra opcion me trae los mismos registros. Por esto parece no tener funcionalidad

#### Steps to reproduce

1. [Ingresar a ventana (ejemplo SDN)]
2. [Desplegar consulta avanzada]
3. [Desde un filtro definir incluye o no incluye]

#### Screenshot or Gif（截图或动态图）
![image (3)](https://github.com/solop-develop/frontend-core/assets/139590879/b791bca3-b627-4f15-97e6-4dd45cd9260e)

#### Expected behavior
observar un resultado diferente al seleccionar incluye o no incluye. O establecer cual es el comportamiento esperado por ese filtro.

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:
Instancia 24157
Rol distribucion y logistica
Org Sucursal Este

**Comment by EdwinBetanc0urt** [comment]
Corregido 

https://github.com/solop-develop/frontend-core/assets/20288327/61fb70c3-cefe-43e2-94bf-9486abbebc06
