### ISSUE TITLE
Proceso Asignar OC recibo factura no estaría funcionando. Los filtros no traen nada

### ISSUE THREAD

**Issue by mgarciaQ76** [solop-develop/vue-1.0#1824]
## Bug report
Detectamos que en este proceso de Asignar OC recibo Factura, no está siendo posible ejecutarlo. Ningún filtro trae información.
En zk vemos que está funcionando ok

#### Steps to reproduce

1. [Ingreso al proceso]
2. [Intento completar filtros]
3. [intento ejecutar]

#### Screenshot or Gif（截图或动态图）

![image (2)](https://github.com/solop-develop/frontend-core/assets/139590879/b5dc833a-b2fc-4079-b69e-02870eb5f668)
![image (1)](https://github.com/solop-develop/frontend-core/assets/139590879/386f6523-1e59-48c3-a54c-369240f89c1c)

#### Expected behavior
Que los filtros muestren info consistente con la instancia y poder ejecutar el proceso

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:
instancia 24157
rol logistica y distribucion
Org Sucursal Este

**Comment by EdwinBetanc0urt** [comment]
Corregido y disponible a partir del release https://github.com/solop-develop/adempiere-grpc-server/releases/tag/2.1.6 del backend y https://github.com/solop-develop/frontend-core/releases/tag/3.3.7 del frontend
