### ISSUE TITLE
VUE documentos por pagar no muestra ningun SDN para definir

### ISSUE THREAD

**Issue by mgarciaQ76** [solop-develop/vue-1.0#1828]
## Bug report
no muestra ningun SDN, en zk 24144 los muestra ok
en VUE no estan los check de solo proveedores  y todos cualquiera
Comentario de NicoL: no logro buscar un SDN desde un Reporte de Saldos Abiertos. Aparece todo blanco la lista desplegable y si busco en el buscador tampoco muestra  nada. 

#### Steps to reproduce

1. [Generar DXP]
2. [Intentar seleccionar SDN]

#### Screenshot or Gif（截图或动态图）
![image (5)](https://github.com/solop-develop/frontend-core/assets/139590879/b3ef8a2a-f320-4df0-9b69-b6ccb3a8feae)
![image (4)](https://github.com/solop-develop/frontend-core/assets/139590879/6c6b1e64-251f-4dba-8ab3-c399fdfc4dfc)

#### Expected behavior
Poder seleccionar SDN

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:
instancia 24157
Rol distribucion y logistica
Org Distribucion

**Comment by EdwinBetanc0urt** [comment]
Corregido y disponible a partir del release https://github.com/solop-develop/frontend-core/releases/tag/3.3.8 del frontend

**Comment by EdwinBetanc0urt** [comment]
Falta corregir que filtre por los campos del criterio

**Comment by EdwinBetanc0urt** [comment]
Corregido

https://github.com/solop-develop/frontend-core/assets/20288327/a25b34fa-3563-4d0f-a833-8c647131ef7b

**Comment by mgarciaQ76** [comment]
Verificado. Se realizan pruebas con resultado exitoso ok


https://github.com/user-attachments/assets/df3ee4ef-52a2-4aca-afcb-a5e435fb8c46
