### ISSUE TITLE
No funciona Crear Desde en DXC

### ISSUE THREAD

**Issue by mgarciaQ76** [solop-develop/vue-1.0#1829]
## Bug report
El proceso de crear desde en DXC no está funcionando en VUE. Hice el mismo camino (con mismas entidades en zk y funcionó ok.

#### Steps to reproduce

1. [Generar OC y completar]
2. [generar DXC a mismo SDN]
3. [seleccionar crear desde, elegir orden y seleccionar orden creada]

#### Screenshot or Gif（截图或动态图）
https://clipchamp.com/watch/dwFfm1zDVSR

#### Expected behavior
Que permita generar el DXC desde orden.

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:
instancia 24157
Rol distribucion y logistica
Org Distribucion
DXC: 1001471 (se generó desde orden desde zk)
OC: 10858

**Comment by EdwinBetanc0urt** [comment]
Corregido y disponible a partir del release https://github.com/solop-develop/frontend-core/releases/tag/3.3.8 del frontend
