### ISSUE TITLE
Pestaña lateral, solapa informacion contable no muestra ninguna info

### ISSUE THREAD

**Issue by mgarciaQ76** [solop-develop/vue-1.0#1835]
## Bug report
Entrando a la pestaña lateral, en la solapa información contable no se visualiza ninguna información en VUE.
En zk, con el mismo documento se visualiza ok

#### Steps to reproduce

1. [consultar registro]
2. [consultar información contable]

#### Screenshot or Gif（截图或动态图）
En VUE
![image (4)](https://github.com/solop-develop/frontend-core/assets/139590879/c8a10fe9-3bf4-4d47-a188-d16d0439ffd0)

En zk
![image (5)](https://github.com/solop-develop/frontend-core/assets/139590879/533a8a60-1b13-4133-9f5c-b737cd5505e5)

#### Expected behavior
Poder visualizar la información contable del registro

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:
instancia 24157
Rol administrador
Org sucursal este
Orden de compra 10766

**Comment by niclopup** [comment]
Agrego que no se ven bien los Esquemas contables ni el Tipo de Aplicación. 
el ejemplo presentado se muestra que tiene un asiento de Compromiso ya que es una Orden de Compra. 

![image](https://github.com/solop-develop/frontend-core/assets/31936815/61b3f120-9f95-4ac1-bbb9-9e5529712824)

Busque un DxP que tiene tipo de aplicación "Actual" y tampoco se ven los asientos

![image](https://github.com/solop-develop/frontend-core/assets/31936815/ccbd63ea-935a-4e4b-b54a-34e17575fd4b)

**Comment by niclopup** [comment]
Muestra datos pero no actualiza bien cuando uno se cambia de registro

https://github.com/solop-develop/frontend-core/assets/31936815/577c7bc3-7adf-4c42-b266-bb380f82cf9c

**Comment by niclopup** [comment]
No se ve asientos contables

![No ve ve Asiento Contable en Ventana](https://github.com/solop-develop/frontend-core/assets/31936815/c94d7771-e454-4aaf-b6ed-58fe8418dd6d)

**Comment by EdwinBetanc0urt** [comment]
Esta corrección esta disponible a partir de la versión del frontend  https://github.com/solop-develop/frontend-core/releases/tag/3.7.6

https://github.com/solop-develop/frontend-core/assets/20288327/1f0985cf-9336-4c11-b3ed-b9fbcc775b40
