### ISSUE TITLE
Ventana Entregas, no permite definir SDN

### ISSUE THREAD

**Issue by mgarciaQ76** [solop-develop/vue-1.0#1837]
## Bug report
En ventana Entregas no me permite definir el SDN, ni ingresando el nombre, ni buscando ni ingresando el codigo (comparto video)

#### Steps to reproduce

1. [crear entrega]
2. [definir SDN]

#### Screenshot or Gif（截图或动态图）

https://github.com/solop-develop/frontend-core/assets/139590879/06cc1f30-5732-4864-9c3c-8d0db9ce4759

#### Expected behavior
Permitir definir SDN

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:
instancia 24157
Rol: distribucion y logistica
Org: Distribucion

**Comment by EdwinBetanc0urt** [comment]
Corregido y disponible a partir del release https://github.com/solop-develop/frontend-core/releases/tag/3.3.8 del frontend

**Comment by EdwinBetanc0urt** [comment]
Falta corregir que filtre por los campos del criterio

**Comment by EdwinBetanc0urt** [comment]
Corregido

https://github.com/solop-develop/frontend-core/assets/20288327/414b8092-7c9a-457c-889b-7d1281b0a330
