### ISSUE TITLE
Parámetro de Fechas en Smart Browser no funciona

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#1846]
## Bug report
Si se cuenta con un campo de fechas ecomo parámetro en un SB no encontrará ningún registro. No importa si se le defina fecha o no, si está visible no muestra ningún registro.

#### Steps to reproduce

1. Abrir SB Browse Sales Order
2. Agregar el campo Fecha de la Orden a los parámetros.

#### Screenshot or Gif（截图或动态图）

https://github.com/solop-develop/frontend-core/assets/31936815/98fb271c-38f7-41ee-89ea-71117f4dcb42

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:

**Comment by rcapecce** [comment]
Se logra observar que por ejemplo agregando el campo Fehca de la Orden y seleccionar una fecha, dicha fecha no queda seleccionada en el input y al hacer la petición, dicho valor de fecha (between, ambas inicio y fin) van en null.

Array de parámetros del filtro (los enviados en la petición):

```
[
   {
      "name":"O_M_Warehouse_ID",
      "operator":"equal",
      "values":1000079
   },
   {
      "name":"O_SalesRep_ID",
      "operator":"equal",
      "values":1000012
   },
   {
      "name":"O_DateOrdered",
      "operator":"between",
      "values":[
         null,
         null
      ]
   },
   {
      "name":"O_GrandTotal",
      "operator":"greater_equal",
      "values":0
   },
   {
      "name":"O_GrandTotal_To",
      "operator":"less_equal",
      "values":999999999
   }
]
```

**Comment by niclopup** [comment]
Se corrigió parcialmente.

Busca bien si uno borra los datos del campo y define fecha desde y Hasta.

Ahora si se intenta utilizar un acceso rápido de "Mes Pasado" está definiendo sólo la "Fecha Desde" y sin definir "Fecha Hasta" por lo que trae sin límite de fecha hasta.


https://github.com/solop-develop/frontend-core/assets/31936815/c8036e89-88c7-431a-9d74-c4e345abad29
