### ISSUE TITLE
Se borra campo de Estado de proyecto al guardar

### ISSUE THREAD

**Issue by nsarlabos** [solop-develop/vue-1.0#1852]
## Bug report
En ventana de proyecto, se tiene el campo de tipo de proyecto establecido con valor por defecto (C_ProjectType_ID = 1000023).

![image](https://github.com/solop-develop/frontend-core/assets/29130825/aca98533-e073-4eb7-bf6a-41035617128d)

En base a ese valor establecido, se setea mediante lógica predeterminada en el campo de Estado del proyecto, el estado predeterminado para ese tipo de proyecto.

![image](https://github.com/solop-develop/frontend-core/assets/29130825/fa5eea3b-901f-43dc-837b-627e8f98d0f8)

![image](https://github.com/solop-develop/frontend-core/assets/29130825/739475ba-caf4-42ff-9ce0-c4f2fdf245f4)

Lo que sucede es que en ZK esto funciona bien, y se asigna el Estado por defecto "Nuevo" en el proyecto, pero en VUE luego de guardar el registro se pone vacío el campo de Estado.
 

#### Screenshot or Gif

Ejemplo de funcionamiento correcto en ZK

![ejemplo_zk](https://github.com/solop-develop/frontend-core/assets/29130825/a5f4f9f3-d321-4791-825b-164ee6330de8)

Ejemplo de funcionamiento incorrecto en VUE

![ejemplo_vue](https://github.com/solop-develop/frontend-core/assets/29130825/c58bd0ab-ef3c-4f6e-ba52-cfa60f6b8cf5)

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:

**Comment by EdwinBetanc0urt** [comment]
Se ha determinado que si establece el valor, pero al guardar el backend devuelve el valor de visualización en null, posiblemente esta limpiando el valor a mostrar en el front, dando la impresión al usuario que esta vació.

Debemos seguir buscando una solución.

**Comment by nsarlabos** [comment]
Ok @EdwinBetanc0urt , muchas gracias, quedamos a la espera.
