### ISSUE TITLE
Tableros: Mostrar varias líneas según el campo requerido

### ISSUE THREAD

**Issue by nsarlabos** [solop-develop/vue-1.0#1859]
## Bug report
Se cuenta con un tablero definido el cual muestra la información de cuentas contables e importes en base a la tabla T_Report, la cual es cargada previamente luego de ejecutarse un informe financiero.

Si bien los datos se están obteniendo correctamente en el tablero, no se están mostrando de la manera deseada.

La necesidad es ver la información de la misma manera que se muestra en el tablero de "Facturas Abiertas":

![facturas abiertas](https://github.com/solop-develop/frontend-core/assets/29130825/e15cc3a3-1e1b-48bf-8dcf-fc8b83dda2d5)

Este tablero muestra una línea por cada año, por lo que cada año sería una columna.

![facturas abiertas data](https://github.com/solop-develop/frontend-core/assets/29130825/21dd18cd-92a3-4d7c-945f-3ba2052e3b61)

Pero en el caso de nuestro tablero queda a la inversa, y la idea es que cada línea sea una cuenta contable en este caso (cuentas 61, 64 y 69), y no la fecha.

![contable](https://github.com/solop-develop/frontend-core/assets/29130825/1d42c2e3-8838-4c9e-8937-f8f4426f0ad9)

![contable data](https://github.com/solop-develop/frontend-core/assets/29130825/8c387348-b3b8-4a20-b279-a4e6bec343a7)

Cabe destacar que el campo de fecha es un campo de TEXTO, de momento quemado para esta prueba, por lo que no es un formato de fecha tipo Timestamp o Date (lo comento por si esto pudiera afectar en algo).

Por otro lado, hemos modificado el tablero de "Ventas por Categoría de Productos" y en ZK logramos que se muestre de la manera deseada, no así en VUE.

A continuación los links de las instancias usadas:

ZK 
http://host.solopapp.com:24144/webui/index.zul

VUE Legacy
http://host.solopapp.com:24145/#/Charts/index

**Comment by elsiosanchez** [comment]
Saludos @nsarlabos  y @niclopup 

El error que tienen a nivel de las consultas SQL  

_**Greafico (Información Contable (T_Report))**_

![image](https://github.com/solop-develop/frontend-core/assets/45974454/593338dd-f74a-4fc2-80e5-5a6b554ced0d)
![image](https://github.com/solop-develop/frontend-core/assets/45974454/f8f0c4f9-8ba4-45c4-bd82-b1be8ddcbc27)
![image](https://github.com/solop-develop/frontend-core/assets/45974454/ea5c7a12-9d04-4552-a626-50361c645546)
![image](https://github.com/solop-develop/frontend-core/assets/45974454/8e9798fe-73e6-4a16-9595-fd2b6b2defbf)


_**Greafico (Facturas Abiertas)**_

![image](https://github.com/solop-develop/frontend-core/assets/45974454/634d0110-9d48-4eee-8a50-3679fd0a490c)
![image](https://github.com/solop-develop/frontend-core/assets/45974454/c0f2097c-f2ed-4ead-a7dd-691f70731c3b)
![image](https://github.com/solop-develop/frontend-core/assets/45974454/9c29ba0a-9008-4554-9846-de8be6ce330f)

**Comment by nsarlabos** [comment]
@elsiosanchez viendo lo que comentas no me queda claro el error, porque entiendo que es correcto que el gráfico de información contable tenga una sóla serie, ya que tiene info solamente para el año 2022.

El tema es que en verdad las series deberían apuntar a las cuentas contables (para tener 3 líneas, una por cada cuenta), y no al año, eso es lo que no estamos logrando cambiar.

**Comment by EdwinBetanc0urt** [comment]
cambio relacionado directamente https://github.com/adempiere/adempiere-dashboard-improvements/pull/11

**Comment by elsiosanchez** [comment]
https://github.com/solop-develop/frontend-core/assets/45974454/c5bca0be-65d5-4a30-b8ed-b3291a6c12d7

**Comment by nsarlabos** [comment]
Hola @elsiosanchez viendo el video entiendo que no estaría bien, ya que sigue teniendo las cuentas contables abajo, y no arriba para hacer una por cada línea del gráfico.

![image](https://github.com/solop-develop/frontend-core/assets/29130825/a6cebbad-5e9f-4ec3-9082-8f48d187c493)

No veo cambios en nuestra base, esto lo habrás hecho en tu backup que nos pediste el otro día?

Por otro lado, te comento que al parecer estaría correcto el cambio que hicieron para el gráfico del POS en https://github.com/solop-develop/frontend-core/issues/1860

**Comment by elsiosanchez** [comment]
Saludos!  @nsarlabos hay ya hay que modificar la consulta en el dataSource como puedes observar en el video 


https://github.com/solop-develop/frontend-core/assets/45974454/609ca66b-3cd9-4fa3-b211-f71d9ddcd452

**Comment by nsarlabos** [comment]
Hola @elsiosanchez sabes que sigo con el problema de que me muestra una sóla cuenta contable, a pesar de que estamos usando el release 2.2.3 

![image](https://github.com/solop-develop/frontend-core/assets/29130825/687b03a1-77dd-4964-beb3-c949ceee4046)

![image](https://github.com/solop-develop/frontend-core/assets/29130825/6855cf45-98a0-4037-b4b6-1490addf35b3)

**Comment by nsarlabos** [comment]
@EdwinBetanc0urt Ahora tenemos el problema de que no se está mostrando bien los datos.
Por ejemplo en Febrero esos serían los datos pero no se ven correctamente reflejados en las líneas.

![image](https://github.com/solop-develop/frontend-core/assets/29130825/fb9b04a8-5032-43ca-9c4b-c81300a5f387)

![image](https://github.com/solop-develop/frontend-core/assets/29130825/8f41db0a-94ad-4727-9bcf-7c2918a8b473)

No sólo pasa en este tablero si no en todos, por ejemplo éste. No muestra los puntos correctamente.
Este último es "Facturas Abiertas" que sería el original de Adempiere.

![image](https://github.com/solop-develop/frontend-core/assets/29130825/88995b2e-7bfa-49c3-8425-5db4eac9d122)

**Comment by EdwinBetanc0urt** [comment]
Corregido, estará disponible en el próximo release.

**Comment by EdwinBetanc0urt** [comment]
Disponible a partir de la versión del frontend https://github.com/solop-develop/frontend-core/releases/tag/3.6.1

![image](https://github.com/solop-develop/frontend-core/assets/45974454/ea68ae42-d1cc-436c-958e-485e58bdb969)
