### ISSUE TITLE
Tableros: No se logra agrupar correctamente en VUE

### ISSUE THREAD

**Issue by nsarlabos** [solop-develop/vue-1.0#1860]
## Bug report
Se cuenta con un tablero que muestra las ventas totales por POS, en el cual se debe primero agrupar el MES y dentro de cada mes separar en cada POS,  de esta manera es más fácil de comparar entre mismo mes y diferente POS. 

Esto se muestra correctamente en ZK, pero no así en VUE:

ZK

![ventas POS mes ZK](https://github.com/solop-develop/frontend-core/assets/29130825/c344cb46-3e73-4002-bfa3-09f4392524f9)

VUE

![ventas POS mes VUE](https://github.com/solop-develop/frontend-core/assets/29130825/5934a5df-1db0-4d15-884c-8a0b1a401e88)

![ventas POS mes VUE data](https://github.com/solop-develop/frontend-core/assets/29130825/c7a33481-9f66-42d0-af9f-079584260d5c)

A continuación los links de las instancias usadas:

ZK
http://host.solopapp.com:24144/webui/index.zul

VUE Legacy
http://host.solopapp.com:24145/#/Charts/index

**Comment by EdwinBetanc0urt** [comment]
cambio relacionado directamente https://github.com/adempiere/adempiere-dashboard-improvements/pull/11

**Comment by elsiosanchez** [comment]
https://github.com/solop-develop/frontend-core/assets/45974454/c5bca0be-65d5-4a30-b8ed-b3291a6c12d7
