### ISSUE TITLE
Campos SQL en Ventana no funcionan en Transcoding

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#1866]
## Bug report

Se encuentra que los campos SQL definidos en ventanas no realizan al cálculo correctamente y muestran todos en "0"

#### Steps to reproduce

1. Abrir ventana "Bandeja CFE" desde Organización "Educación - Admin"

#### Screenshot or Gif（截图或动态图）

**Ejemplo VUE Transcoding**
![image](https://github.com/solop-develop/frontend-core/assets/31936815/37cd1b87-0f99-4574-bb6c-45a490b17efa)

**Ejemplo VUE Legacy**
![image](https://github.com/solop-develop/frontend-core/assets/31936815/bbda8765-047b-4094-9fbe-5109f1f6b2c5)

**Ejemplo en ZK**

![image](https://github.com/solop-develop/frontend-core/assets/31936815/1020356f-6205-4d02-9f47-631a98646bd3)

![image](https://github.com/solop-develop/frontend-core/assets/31936815/354d6da6-9bbb-4c78-b709-5142ab0b18d1)

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version: Transcoding

**Comment by EdwinBetanc0urt** [comment]
Esto esta directamente relacionado con https://github.com/solop-develop/frontend-core/issues/1393 y fue corregido en el cambio https://github.com/solop-develop/adempiere-grpc-server/pull/470, se revisara que pudo ocurrir para que el error volviera a aparecer

**Comment by EdwinBetanc0urt** [comment]
Estos cambios https://github.com/adempiere/adempiere-grpc-utils/pull/19 corrigen este comportamiento inesperado
