### ISSUE TITLE
Selección masiva en SB no selecciona todos los registros

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#1880]
## Feature request

Si en un SB se encuientran más registros de la paginación más grande, no tenemos una opción para "Seleccionar todos los registros" para poder hacer un proceso sobre todos ellos.

Una solución para esto que vi que hace Gmail es darte la opción aparte de "seleccionar todos los registros que entren en esta búsqueda"

![image](https://github.com/solop-develop/frontend-core/assets/31936815/6af32b20-8013-4fe4-9b20-9e3bc7c6cc74)

De esta manera solucionaríamos el caso de que se quiera generar un proceso para todos los registros de la búsquda.

**Comment by Ricargame** [comment]
Cambios disponibles apartir de la versión: https://github.com/solop-develop/frontend-core/releases/tag/4.1.1

![imagen](https://github.com/solop-develop/frontend-core/assets/78000356/321737d9-ea7d-482a-abb2-69740578a372)

![imagen](https://github.com/solop-develop/frontend-core/assets/78000356/29ef5f4d-d3a5-4f1a-8536-fcae9ea43427)
