### ISSUE TITLE
Error al navegar en ventana Proyecto de Medios

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#1896]
## Bug report

al intentar navegar dentro de algunos proyectos el botón de bajar al siguiente registro no funciona. Esto se ve que sucede con ciertos proyectos pero con otros no.

este problema no lo logré replicar en la ventana de "Proyectos" genérica de ADempiere. 

No se que es bien pero intenanto replicar con un mismo proyecto, el error parecería que sucede muy aleatorio. Si un proyecto me da error para seguir navegando al siguiente registro, luego abro la ventana en modo Grilla, selecciono otro proyecto y comienzo a bajar, el error no sucede nuevamente en el mismo proyecto.

#### Steps to reproduce

1. [xxx]
2. [xxx]
3. [xxxx]

#### Screenshot or Gif（截图或动态图）

https://github.com/solop-develop/frontend-core/assets/31936815/cf63da75-3678-4b22-83e1-cc807429daeb

https://github.com/solop-develop/frontend-core/assets/31936815/5f0ccff6-0037-4347-a1ea-f84fe6178b9f

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:

**Comment by Ricargame** [comment]
Cambios disponibles apartir de la versión: https://github.com/solop-develop/frontend-core/releases/tag/4.2.0

https://github.com/user-attachments/assets/36445c3b-12c2-4e97-82ba-f31c4964521c

**Comment by mgarciaQ76** [comment]
Verificado. Se realizan pruebas con resultado exitoso ok


https://github.com/user-attachments/assets/b9b1255f-6598-4ca1-bb4d-28cc50ee5c75
