### ISSUE TITLE
[Feature Request] Add Generic Logic Authentication support for KeyCloak

### ISSUE THREAD

**Issue by elsiosanchez** [solop-develop/vue-1.0#1915]
#### _**Support for login with KeyCloak  with generic logic OpenID**_

With this functionality it's possible login with [KeyCloak](https://www.keycloak.org/documentation)  see this example:

### **_KeyCloak:_**
Setting:

![295238140-3c23c209-30a9-4dfe-b7fa-6735cde2c447](https://github.com/solop-develop/frontend-core/assets/45974454/b77091a7-f3dd-434d-9718-7413472e000e)

### _**Login Sample:**_
![image](https://github.com/solop-develop/frontend-core/assets/45974454/a892eca3-a6e4-4237-9857-fe31d3dc0965)

**Comment by EdwinBetanc0urt** [comment]
https://github.com/solop-develop/frontend-core/assets/45974454/3aa5159d-c6cf-4e22-936c-499faf3d2509
