### ISSUE TITLE
[Feature Request] Implementar Link Compartido de Archivos

### ISSUE THREAD

**Issue by yamelsenih** [solop-develop/vue-1.0#1916]
## Feature request
Dado que ya manejamos completamente la conexión con plataformas tipo S3 para el manejo de archivos, existe una marcada diferencia entre el manejo tradicional de ADempiere donde prácticamente los archivos son manipulados por el servidor, cargando en memoria cada uno de los archivos (esto provoca caídas del servicio si el archivo es muy pesado).

Cuando se manejan archivos con S3 se tienen muchas características como:
- Almacenamiento de archivos muy grandes
- Manejo de seguridad
- Manejo de acceso temporal con URL's firmados
- Entre otros

Una lista de alguno de los beneficios puede verse [aquí](https://min.io/docs/minio/linux/operations/concepts/thresholds.html)

Este issue pretente generar un URL para compartir un archivo desde al servicio de [s3_gateway_rs](https://github.com/adempiere/s3_gateway_rs), la idea es que sea lo más similar posible a un manejador de archivos tradicional.

#### Describe the solution you'd like
Como solución ya existen endpoinds para generar url's firmados. Simplemente falta agregar esto desde el frontend.

#### Additional context
Como un ejemplo a seguir sugiero que sea el siguiente, dado que es una de las formas más amigables y comunes que existen:

https://github.com/solop-develop/frontend-core/assets/2333092/966def40-c20a-4662-a6d9-9b3cd9f079f8

**Comment by elsiosanchez** [comment]
Saludos aqui se muestra como compartir el link de una imagen 

https://github.com/solop-develop/frontend-core/assets/45974454/cbd1856e-5818-4299-81fc-5e6676e474fd
