### ISSUE TITLE
Simplificar información de Solicitudes en Forma "Issues"

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#1920]
## Feature request

Para poder simplificar aún más la forma de presentaciónl de las Solicitudes se solicita los siguientes ajustes:

- Quitar nombre de campos “Proyecto” y “Socio del Negocio” para que queden sólo los íconos que ya es suficiente para que se entienda
- Quitar el Número de la Solicitud: mejor si sólo se ve el Nombre del Asunto de la Solicitud

![image](https://github.com/solop-develop/frontend-core/assets/31936815/6c98696e-6d83-48fd-a0af-51a5218977fc)

**Comment by EdwinBetanc0urt** [comment]
Corregido

![imagen](https://github.com/solop-develop/frontend-core/assets/20288327/8870550e-3c26-4d8d-b537-938f8d7a9415)
