### ISSUE TITLE
Mejorar Información de Solicitudes vinculadas desde una Ventana

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#1921]
## Feature request

Se desea dejar igual de limpia que está la información de las Solicitudes en la forma de "Issues". Ahora las solicitude4s vinculadas a una ventana se ven con la forma "Vieja" y para ver las solicitudes de un proyecto no se está viendo muy prolijo.

Actualmente se ve así:

![Captura de pantalla 2024-02-15 010715](https://github.com/solop-develop/frontend-core/assets/31936815/c3c631d2-f8bc-4d83-90e2-cccaf8f30223)

Dejar sólo los campos que se marcan en rojo y se subrraya.

![Captura de pantalla 2024-02-15 010843](https://github.com/solop-develop/frontend-core/assets/31936815/3f288493-129b-446e-ac2d-fe9e17cf0f3f)

Dudo si vale la pena agregar los últimos dos campos del tiempo y el acercar directo en esta vista. Tal vez dado que no hay mucho espacio podríamos quitarlos también y si se desea realizarlos se puede hacer al abrir la solicitud.

**Comment by EdwinBetanc0urt** [comment]
![imagen](https://github.com/solop-develop/frontend-core/assets/20288327/2a56f2db-0785-40d2-b716-e319885a1625)

![imagen](https://github.com/solop-develop/frontend-core/assets/20288327/f7a63828-7738-4e9e-be61-8b120db76d63)


Adicionalmente en nuevo registro se corrige que muestra el cero en las listas desplegables al estar vacías, y que no muestra el asterisco rojo que indique los campos obligatorios.

![imagen](https://github.com/solop-develop/frontend-core/assets/20288327/b0324bb2-e58f-4cc2-800f-78bfacde29dd)
