### ISSUE TITLE
Cronómetro para crear tiempo dedicado en Solicitudes

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#1922]
## Feature request

Se desea contar con alguna función de VUE que permite comenzar a correr un Cronómetro desde una Solicitud (Issue). ya sea en mono registro como también desde issue en modo grilla.

De momento sólo es suficiente mostrar la funcionalidad y que no genere ningún registro en ninguna tabla su acción. Luego podemos darle un cierre también junto con el issue #923 que está relacionado.

Para tener una idea de lo que se busca sería algo similar a esto: 

https://trackingtime.co/es/time-tracking-para-asana

Comentar por favor que opciones podríamos tener

**Comment by EdwinBetanc0urt** [comment]
Corregido


https://github.com/solop-develop/frontend-core/assets/20288327/8ea0cbe1-481f-46b4-b2ca-f4e4b40f3349
