### ISSUE TITLE
Tableros: tablero se muestra vacío al ejecutar desde ventana

### ISSUE THREAD

**Issue by nsarlabos** [solop-develop/vue-1.0#1938]
## Bug report

Se tiene el tablero "Tiempo Dedicado" (AD_Chart_ID=1000016), el cual se muestra correctamente desde la pestaña "Gráficos", pero al asociar el tablero a una ventana, en este caso a la ventana "Orden de Trabajo" y "Proyecto de Medios", el tablero se muestra pero vacío.

Al asociar el tablero a las ventanas no se definieron parámetros, ya que de momento no se necesita.

![image](https://github.com/solop-develop/frontend-core/assets/29130825/2b710d97-26ee-4d7b-a28e-4079dc651d3e)

![image](https://github.com/solop-develop/frontend-core/assets/29130825/0bc43a59-a3f0-4d81-8032-cb3d56c73707)

![image](https://github.com/solop-develop/frontend-core/assets/29130825/fdf87e64-17c2-45eb-81f7-b10d7d7dbb23)

ZK

http://demo1.solopcloud.com/webui

VUE

http://demo1.solopcloud.com/

**Comment by nsarlabos** [comment]
Estimados, al parecer esto no pasa solamente con este gráfico, sino con todos los gráficos asociados a ventanas

**Comment by EdwinBetanc0urt** [comment]
Corregido

![2024-02-21_18-03_1](https://github.com/solop-develop/adempiere-grpc-server/assets/20288327/f0d0e25f-d8f6-4fa1-bec6-f122509ae15d)
