### ISSUE TITLE
"Información" o "Preferencia" de un Campo/Parámetro no carga

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#194]
Hasta el día de ayer se podía ver sin problema la "Información" de un campo o un parámetro de un proceso/reporte, hoy ya no.

Vinculado a https://github.com/solop-develop/frontend-core/issues/67

https://user-images.githubusercontent.com/31936815/174901528-1f1e54f5-8d08-4507-96f9-6fb9bd4a7cfe.mp4

**Comment by EdwinBetanc0urt** [comment]
Corregido en https://github.com/solop-develop/frontend-default-theme/pull/56


https://user-images.githubusercontent.com/20288327/174921533-98a445ff-088d-4728-9d42-180ed6fb3e11.mp4

**Comment by niclopup** [comment]
@EdwinBetanc0urt muchas gracias
Correcto funcionamiento verificado!
en este caso te parece bien que cierre esta issue?

**Comment by EdwinBetanc0urt** [comment]
Si, sí esta operando correctamente
