### ISSUE TITLE
Formato de Fecha incorrecto en SB "Crear Registo de Asistencia (Manual)"

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#1940]
## Bug report

Se abre el SB de "Crear Registo de Asistencia (Manual)" y las fechas las despliega en un formato incorrecto.

![image](https://github.com/solop-develop/frontend-core/assets/31936815/fd222ec8-ab60-41a4-8de2-bb31d4edb7c2)

ZK
![image](https://github.com/solop-develop/frontend-core/assets/31936815/a5f05948-773a-426f-8e26-5f0dd05ebe0e)

#### Steps to reproduce

1. [xxx]
2. [xxx]
3. [xxxx]

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:

**Comment by EdwinBetanc0urt** [comment]
Corregido

![image](https://github.com/solop-develop/frontend-core/assets/45974454/c09ea337-cce3-42d5-ae57-95ecc8d9c904)
