### ISSUE TITLE
Tasa de cambio la muestra a dos decimales

### ISSUE THREAD

**Issue by mgarciaQ76** [solop-develop/vue-1.0#1942]
## Bug report
Al consultar tasa de cambio en mono registro la muestra a dos decimales.
A su vez, al generar nueva tasa de cambio tambien la genera a dos decimales (solo se ve completo en multi registro)
En zk la genera a doce decimales

#### Steps to reproduce

1. [Consultar tasa mono registro]
2. [Dar de alta tasa de cambio]

#### Screenshot or Gif（截图或动态图）
Consulta tasa de cambio

https://github.com/solop-develop/frontend-core/assets/139590879/03d11e52-5100-4971-84c9-16dbdb9ab45d

Nueva tasa de cambio

https://github.com/solop-develop/frontend-core/assets/139590879/77bf9198-9e3a-42fe-a8ea-e485be4f3873

#### Expected behavior
Que se muestre en consulta y al dar de alta la tasa a 12 decimales como en zk

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:
Se probó en instancia 24157 y en [demo1](http://demo1.solopcloud.com/)
Rol distribucion y logistica
Org casa central

**Comment by EdwinBetanc0urt** [comment]
Corregido

![2024-02-22_12-22](https://github.com/solop-develop/frontend-core/assets/20288327/250c6900-1e80-4a54-bd80-c157d5736179)

**Comment by niclopup** [comment]
No veo esto corregido:

![image](https://github.com/solop-develop/frontend-core/assets/31936815/aaf60e04-4ad1-4530-8fa9-7bebdcdfd0fc)

Se debería ver igual de como se ve en ZK. Una tasa de cambio tiene muchos decimales

![image](https://github.com/solop-develop/frontend-core/assets/31936815/78b1abf0-249a-4d5e-b3c9-363aed9f36ad)

![image](https://github.com/solop-develop/frontend-core/assets/31936815/61351739-d935-4a85-b4ab-b19ee37a885e)

**Comment by EdwinBetanc0urt** [comment]
Lo que noto es que tiene tipo de visualización `Number` por lo que entiendo no debería hacer redondeo. El redondeo aplica solo a los tipos de visualizaciones `Amount` y a `Cost+Price` (que manejan redondeo por la precisión de la moneda).

![imagen](https://github.com/solop-develop/frontend-core/assets/20288327/11adae5d-a92f-414b-9ebd-c801b7e7a6b8)

**Comment by Ricargame** [comment]
Cambios disponibles apartir de la versión: https://github.com/solop-develop/frontend-core/releases/tag/3.8.5



https://github.com/solop-develop/frontend-core/assets/78000356/61da8265-dc67-44c1-be47-706a4ea97b4b

**Comment by niclopup** [comment]
![Image](https://github.com/user-attachments/assets/539a3cf4-c6a3-4b39-a6f3-84e021c75b69)

![Image](https://github.com/user-attachments/assets/7f13015c-d72d-416e-85e8-238000f0ca30)

**Comment by EdwinBetanc0urt** [comment]
Cambios disponibles a partir de la versión del frontend `4.4.022`.

https://github.com/user-attachments/assets/caeabee9-a6c4-4dcf-bf7a-69a99afb1d76
