### ISSUE TITLE
Filtro incorrecto aplicado en Ventana abierta desde "Tareas Pendientes"

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#1946]
## Bug report

Al hacer click en una Tarea Pendiente, se está abriendo la ventana correcta pero no está aplicando el filtro que debería. Esto si funciona correctamente en ZK pero no en VUE

#### Screenshot or Gif（截图或动态图）

**ZK**

![Ventana abierta desde Tareas Pendientes en ZK](https://github.com/solop-develop/frontend-core/assets/31936815/aef74963-5fc3-40c8-b05b-c45cea00dc7a)

**VUE**

![Ventana abierta desde Tareas Pendientes en VUE](https://github.com/solop-develop/frontend-core/assets/31936815/ac2fc103-7e5e-455f-a341-ca0b07f3b582)

#### Expected behavior
Aplicar mismo filtro que aplica en ZK

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version: 
- 
![image](https://github.com/solop-develop/frontend-core/assets/31936815/4a08f626-dfa0-4d63-88ce-0e23d6b91037)

**Comment by niclopup** [comment]
Creo que ya esta resuelta en otro Issue

**Comment by EdwinBetanc0urt** [comment]
Corrección disponible a partir de la versión del frontend https://github.com/solop-develop/frontend-core/releases/tag/3.7.5 y del backend https://github.com/solop-develop/adempiere-grpc-server/releases/tag/3.1.6

https://github.com/solop-develop/frontend-core/assets/45974454/a7c0f193-63ba-4bff-be06-a8c0ceb1aadd

**Comment by niclopup** [comment]
No se logra verificar como se muestra en el gif 

![Filtro desde Tareas Pendientes con error](https://github.com/solop-develop/frontend-core/assets/31936815/c9bfec1b-6660-464a-ba92-925bc83341ed)
![2024-04-22_15-47_1](https://github.com/solop-develop/frontend-core/assets/31936815/479dae06-eea2-4729-972d-3335b926ac06)
![2024-04-22_15-47](https://github.com/solop-develop/frontend-core/assets/31936815/5a2fadd4-b46d-4199-b4a8-400a7a5300bc)

![image](https://github.com/solop-develop/frontend-core/assets/31936815/f0fe41e4-463a-447b-a5ee-bf8e4dd89c3b)

**Comment by Ricargame** [comment]
Cambios disponibles apartir de la versión: https://github.com/solop-develop/frontend-core/releases/tag/4.0.3

https://github.com/solop-develop/frontend-core/assets/78000356/052e487e-5f41-4c75-8c29-d2e4912bb8ac
