### ISSUE TITLE
Acercar desde campo SDN no lleva al registro correcto en ventana ya abierta

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#1949]
## Bug report

Acercar desde campo SDN no lleva al registro correcto en ventana ya abierta

#### Steps to reproduce

1. Acercar desde ventana Proycetos a un registro desde campo "Socio del Negocio"
2. una vez abre la ventana, ir a otro Proyecto con otro SDN y acercar.
3. el sistema irá a la ventana ya abierta y mostrará el mismo SDN que antes mostraba

#### Screenshot or Gif（截图或动态图）

![Acercar desde campo SDN no registro en ventana ya abierta](https://github.com/solop-develop/frontend-core/assets/31936815/353e0a4e-94f8-4cee-9de2-a371c8e7dfef)

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:   3.5.5-rt-1

**Comment by EdwinBetanc0urt** [comment]
Esto esta resuelto, disponible a partir del release https://github.com/solop-develop/frontend-core/releases/tag/3.5.7


https://github.com/solop-develop/frontend-core/assets/45974454/f09016f6-cd7e-411e-8014-88c6b86f9784
