### ISSUE TITLE
Nombre de los Parámetros de Reportes muy pequeño corta el nombre de los campos

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#195]
Se encuentra que en el reporte "Bank transfer" el espacio para los nombres de los parámetros en ocasiones queda muy chico y corta el nombre del campo.

![Espacio Nombre de parámetro](https://user-images.githubusercontent.com/31936815/174902248-74158c28-4948-4f61-8079-fcd09058190b.png)

Vinculado a https://github.com/solop-develop/frontend-core/issues/65

**Comment by EdwinBetanc0urt** [comment]
Corregido y Actualizado en la nube https://vue-develop.solopcloud.com/#/6b1c00f8-a762-48c1-9e30-b634ff2953ba/a3e5c878-fb40-11e8-a479-7a0060f0aa01/process/53190

![Screenshot_20220801_145512](https://user-images.githubusercontent.com/20288327/182222894-d14e55fc-b5aa-4cec-9794-022371c0fd9c.png)
