### ISSUE TITLE
Mejorar representación de Avisos

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#1950]
## Feature request

Se desea aplicar una vista más clara de la forma que se muestran los avisos:

La idea es que se parezca más a esto y no a una tabla directamente.

![image](https://github.com/solop-develop/frontend-core/assets/31936815/fb077af9-5e72-4865-a4db-28a94e88085e)

Creo que muchos campos que ahora se ven en ineas podemos darle una vuelta para que queden más lindos.

Comentar que les parece y si hay una manera que se acerca más a esta nueva idea que a una tabla comentar también asi podemos ver de hacer algo por el momento. 

notar también que falta el check de "Processed" para que no aparezca más esos avisos. Sería un "Leído"

Se detalla en este jamboard.

https://jamboard.google.com/d/1IuYUF5KEDWlwcz-FDk-aWt5yUELxUUM8Rnz34umLZUM/edit?usp=sharing

Relacionado con #1683

**Comment by EdwinBetanc0urt** [comment]
Cambios disponibles a partir del backend https://github.com/solop-develop/adempiere-grpc-server/releases/tag/3.6.0 y del frontend https://github.com/solop-develop/frontend-core/releases/tag/4.3.2



https://github.com/user-attachments/assets/71647da3-322e-48d4-a7d3-9e3548fcf56d
