### ISSUE TITLE
Traducción de Menú "Vistas"

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#1951]
## Bug report

Cómo se debería definir la tradcción de este menú de "Vistas" para que si se abre el sistema en idioma inglés, muestre también en ingles este campo: "Views"

![image](https://github.com/solop-develop/frontend-core/assets/31936815/f29f4381-345f-49be-8373-46cb27a500c3)

**Comment by EdwinBetanc0urt** [comment]
Esto ya esta corregido disponible a partir del release https://github.com/solop-develop/frontend-core/releases/tag/3.5.6


![image](https://github.com/solop-develop/frontend-core/assets/45974454/b6c5d5e8-fee6-4f3d-8484-098cf9c31dbd)

**Comment by niclopup** [comment]
Ok en Inglés.

![image](https://github.com/solop-develop/frontend-core/assets/31936815/59ca0e58-a4dc-4dfd-bcff-a0f0f35c586e)


faltaría corregir el nombre de "Accounting Viewer" para uqe se vea bien en idioma Español

Defini traducción: "Navegador Contable"

![image](https://github.com/solop-develop/frontend-core/assets/31936815/e3064f3a-62bf-4106-9f04-b9d8ba3c6818)
