### ISSUE TITLE
Velocidad apertura de Ventanas

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#1958]
## Bug report
Se está teniendo mucha demora en abrir ventanas con muchas pestañlas hijas. 

Es prácticamente imposible abrir una ventana con varias pestañas sin desactivarlas por ASP.

Ejemplo: 
* Proyectos
* Documentos por Pagar
* Socio del Negocio
* Productos

Estas ventanas demoran tanto que al parecer como que se cae la transacción y desiste en su apertura.

Es vital que esta velocidad sea mejorada.

**Comment by EdwinBetanc0urt** [comment]
Este issue depende directamente del cache que se implementara utilizando `OpenSearch` https://github.com/solop-develop/frontend-core/issues/1965

**Comment by EdwinBetanc0urt** [comment]
Se han hecho mejoras en el backend `Adempiere-gRPC-Server` actual para que mejore el rendimiento implementando `parallelStream` al recorrer las pestañas y campos, nos dimos cuenta que uno de los puntos críticos y que era lento era el método de generar los campos dependientes (necesario para las lógicas de visualización, solo lectura y obligatoriedad) https://github.com/solop-develop/adempiere-grpc-server/blob/develop/src/main/java/org/spin/grpc/service/dictionary/WindowConvertUtil.java#L560 que por cada campo que tenga lógica configurada, recorre cada pestaña y cada campo de esas pestañas para evaluar si es un campo dependiente, disponible partir de la versión del backend https://github.com/solop-develop/adempiere-grpc-server/releases/tag/3.1.2 


Esto también se mejorara aún más el rendimiento con `OpenSearch`.
