### ISSUE TITLE
[Feature Request] MS Cache

### ISSUE THREAD

**Issue by yamelsenih** [solop-develop/vue-1.0#1965]
## Descripción de la Característica
Un caché genérico para almacenar documentos de acceso rápido sin necesidad de consultar al backend. Algunas de las entidades a considerar son:

**Diccionario**
- [x] https://github.com/solop-develop/frontend-core/issues/2025
- [x] #1996
- [x] #2026
- [x] #1995
- [x] #1994

**POS**
- Productos
- Definición de Puntos de Ventas

**Dashboard**
- Definición
- Favoritos

**Personalizaciones**
- Ventana
- Proceso
- Smart Browser
- Reportes
- Menú
- Favoritos
- Preferencias de usuario
- Busqueda

#### Propuesta de Solución

Como solución para esta característica propongo el uso de OpenSearch, un fiel de ElasticSearch que actualmente mantiene una gran comunidad de Amazon

#### Alternativas a Considerar 

- Herramientas como ElasticSearch
- Reddit 

#### Contexto Adicional

Esto es interesante ya que podemos comenzar a eliminar el caché de ADempiere y usarlo con un microservicio especial para eso.

https://opensearch.org/

**Comment by elsiosanchez** [comment]
Saludos. 

Se ha estado avanzando en la implementación de la característica del caché genérico, centrándonos en la parte relacionada con el **Diccionario**:

Durante el desarrollo de la característica del caché genérico, hemos hecho avances significativos en la parte del **Diccionario**. Hemos completado exitosamente la implementación de puntos clave como el **Menú**, los **Reportes** y los **Proceso**, lo que nos ha permitido lograr un importante hito en este proyecto.

Sin embargo, aún estamos trabajando activamente en los **Smart Browser** y las **Ventanas**. Estos elementos son cruciales para la funcionalidad completa del caché genérico
