### ISSUE TITLE
[Feature Request] Autenticación con Keycloak 

### ISSUE THREAD

**Issue by yamelsenih** [solop-develop/vue-1.0#1968]
## Descripción de la Característica
Como característica principal, los sistemas llevados a microservicios requieren una autenticación centralizada, por lo general se usan servicios como keycloak para validar las peticiones 

#### Propuesta de Solución
Usar keycloak como servicio de autenticación para unificar las peticiones de seguridad. Dentro de sus ventajas principales se encuentran las siguientes gestiones:
- Crear usuario
- Validar Correo
- Establecer Autenticación por Dos Vías
- Reinicio de Contraseña
- Expiración de Contraseña
- Expiración de sesión
- Expiración de token
- Protocolo OpenID
- Mapeo de Roles

Este servicio sumado al nginx como proxy invertido permiten validar cada una de las peticiones que se hacen al servidor.

#### Alternativas a Considerar 
- [Kong](https://konghq.com/)

#### Contexto Adicional

Dado que los microservicios actúan de manera separada, es imprescindible tener este servicio para poder avanzar con el siguiente microservicio de manera segura 

https://www.keycloak.org/
https://konghq.com/

**Comment by EdwinBetanc0urt** [comment]
Esta mejora esta disponible a partir de la versión del backend https://github.com/solop-develop/adempiere-grpc-server/releases/tag/3.0.3

Cabe destacar que requiere cambios a nivel de diccionario

![imagen](https://github.com/adempiere/adempiere-grpc-utils/assets/20288327/1a2881c2-78d9-46cc-bea7-36097029d5f0)

![imagen](https://github.com/adempiere/adempiere-grpc-utils/assets/20288327/69f5f5a5-158f-423c-a2ef-849cf656b00f)

[open-id-session-id.xml.zip](https://github.com/adempiere/adempiere-grpc-utils/files/14578780/open-id-session-id.xml.zip)
