### ISSUE TITLE
Configuración de visibilidad de Procesos en Ventanas

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#1981]
## Bug report

Actualmente si quitamos acceso a un proceso a nivel de ROL el mism no se está considernado en las ventanas de VUE.

![image](https://github.com/solop-develop/frontend-core/assets/31936815/5b8bb03f-4de8-454b-a8d0-67d622263b5f)

![image](https://github.com/solop-develop/frontend-core/assets/31936815/e9e1973e-504a-49f5-b49a-85b4533564a8)

![image](https://github.com/solop-develop/frontend-core/assets/31936815/96c318ba-7391-4939-b9a5-19a7fec9dec7)

![image](https://github.com/solop-develop/frontend-core/assets/31936815/638d7251-6873-48ac-a96f-9e1e6bb88178)

Sölo se está considerando que el prceoso esté activo en la ventana a nivel de System
si se define con activo=NO acá entonces ahi si deja de mostrarlo.

![image](https://github.com/solop-develop/frontend-core/assets/31936815/4ed1290a-53e9-442e-9961-16716113d69b)

#### Screenshot or Gif（截图或动态图）
![Configuración de Procesos en Ventanas Inactivar proceso en Ventana System](https://github.com/solop-develop/frontend-core/assets/31936815/be539042-73a6-45a6-930b-f9c916209254)
![Configuración de Procesos en Ventanas](https://github.com/solop-develop/frontend-core/assets/31936815/edd572bc-2578-4dd5-9aea-6a33ff9d7dd8)

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:    
- Back-End Version: spuy-rc-4.29
- Front-End Version:  3.5.5-rt-1

**Comment by EdwinBetanc0urt** [comment]
Esto fue corregido en el cambio https://github.com/solop-develop/adempiere-grpc-server/pull/713/files#diff-6cbb4d7da8ee45e50faf61a4f7ba03923396eba38a991e484cfdd62e8069ef87R223-R224

**Comment by EdwinBetanc0urt** [comment]
Cierro este issue al tener estatus entregado
