### ISSUE TITLE
Smart Browser no muestra registros

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#1983]
## Bug report

Se intenta abrir cualquier SB desde la última actualización y no muestra registros y tampoco da error... 

SB "Consulta de Usuarios/Contactos"

#### ZK

![image](https://github.com/solop-develop/frontend-core/assets/31936815/9e8d5ad6-c06f-4226-8222-afc415390f1e)

#### VUE

![image](https://github.com/solop-develop/frontend-core/assets/31936815/5f12f15b-5b4d-471c-9e3c-59817743271f)

Entrando sólo tenemos este error q no se si tiene que ver

TypeError: e.containerManager.getPageSize is not a function at o.<anonymous> (http://demo1.solopcloud.com/static/js/chunk-13dcabf6.c68775a3.js:1:8602) at rr.get (http://demo1.solopcloud.com/static/js/chunk-libs.278e8467.js:70:30788) at rr.evaluate (http://demo1.solopcloud.com/static/js/chunk-libs.278e8467.js:70:31777) at e.i [as value] (http://demo1.solopcloud.com/static/js/chunk-libs.278e8467.js:420:20056) at o.get [as currentPageSize] (http://demo1.solopcloud.com/static/js/chunk-libs.278e8467.js:420:22219) at o.a (http://demo1.solopcloud.com/static/js/chunk-13dcabf6.c68775a3.js:1:5886) at http://demo1.solopcloud.com/static/js/chunk-libs.278e8467.js:420:23874 at Qt (http://demo1.solopcloud.com/static/js/chunk-libs.278e8467.js:420:23626) at t.render (http://demo1.solopcloud.com/static/js/chunk-libs.278e8467.js:420:23845) at e._render (http://demo1.solopcloud.com/static/js/chunk-libs.278e8467.js:70:23862)

#### Steps to reproduce

1. [xxx]
2. [xxx]
3. [xxxx]

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:  3.5.8

**Comment by EdwinBetanc0urt** [comment]
Corregido disponible a partir de la versión del frontend https://github.com/solop-develop/frontend-core/releases/tag/3.5.9

![imagen](https://github.com/solop-develop/frontend-core/assets/20288327/715b1568-5490-4d54-826b-531df448cbc9)
