### ISSUE TITLE
Nombre de campos en Registros de SB muestra siempre el ID y no el nombre

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#1987]
## Bug report

No se logra ver los registros como se veían anteriormente.

Los IDs no los convierte a la referencia que se desea definir de ninguna manera. 

#### Steps to reproduce

1. Abrir SB "Consulta de Usuarios/Contactos" 
2. ver campos Socio del Negocio y Grupo de Socio del Negocio q se muestra el ID y no el nombre

#### Screenshot or Gif（截图或动态图）

**SB Consulta de Usuarios/Contactos**

![image](https://github.com/solop-develop/frontend-core/assets/31936815/90f8c03a-fe7c-4d78-ac41-4898c78f5a2c)

![image](https://github.com/solop-develop/frontend-core/assets/31936815/8d25885c-6a5e-419b-8501-4b58e71c7e82)

![image](https://github.com/solop-develop/frontend-core/assets/31936815/9ccb0d26-e2ac-420f-b531-f64a184ebdaf)

![image](https://github.com/solop-develop/frontend-core/assets/31936815/7596f9de-fbb3-4432-be52-80c88c12a361)

![image](https://github.com/solop-develop/frontend-core/assets/31936815/9ea2f855-b4ff-4595-8cd6-3555da8b8442)

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version: 3.5.9
- Back  spuy-rc-4.34

**Comment by EdwinBetanc0urt** [comment]
Corregido disponible a partir de la versión del backend https://github.com/solop-develop/adempiere-grpc-server/releases/tag/3.0.3

![imagen](https://github.com/solop-develop/adempiere-grpc-server/assets/20288327/b7957b41-bd56-4eaa-bb02-df8158ae9892)
