### ISSUE TITLE
no se puede generar el formato de impresión de ninguna Orden de Compra / Venta 

### ISSUE THREAD

**Issue by mgarciaQ76** [solop-develop/vue-1.0#1989]
## Bug report
Al intentar generar impresión de Orden de venta u orden de compra, genera error.

#### Steps to reproduce

1. [Consultar Orden]
2. [Imprimir orden]

#### Screenshot or Gif（截图或动态图）
![proceso imprimir orden](https://github.com/solop-develop/frontend-core/assets/139590879/ed5372c1-df3f-4546-9444-cfc1b4866ee2)

![error al imprimir orden de venta compra](https://github.com/solop-develop/frontend-core/assets/139590879/e116783a-1a84-492c-bca2-82efa8ccb0be)

#### Expected behavior
Generar la impresión de la orden (compra o venta)

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:
instancia http://cac.solopcloud.com/#
Rol Admin

**Comment by EdwinBetanc0urt** [comment]
Corregido a partir de la versión del frontend https://github.com/solop-develop/frontend-core/releases/tag/3.6.0

https://github.com/solop-develop/frontend-core/assets/20288327/1aa99474-2d7c-4889-b453-b59c8939dd72
