### ISSUE TITLE
Falla filtro fecha

### ISSUE THREAD

**Issue by mgarciaQ76** [solop-develop/vue-1.0#1990]
## Bug report
Al intentar filtrar por fecha, se selecciona una fecha determinada y el sistema asigna el día anterior. Ejemplo: selecciono 08/03/2024 o selecciono el filtro "HOY" pero el sistema asigna 07/03/2024
Ocurre en todas las ventanas con el filtro fecha

#### Steps to reproduce

1. [Realizar consulta avanzada]
2. [Filtrar por fecha]

#### Screenshot or Gif（截图或动态图）
![filtro fecha](https://github.com/solop-develop/frontend-core/assets/139590879/ceb659f2-b83d-453b-b012-1195f3ba718a)

#### Expected behavior
Que el sistema defina la fecha seleccionada por el usuario

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:
Instancia http://cac.solopcloud.com/#
Rol admin

**Comment by EdwinBetanc0urt** [comment]
Corregido a partir de la versión del frontend https://github.com/solop-develop/frontend-core/releases/tag/3.6.0


https://github.com/solop-develop/frontend-core/assets/45974454/a394fa56-4fac-4516-8837-5f5f50c1e69c


https://github.com/solop-develop/frontend-core/assets/45974454/2f628c4b-89ec-42b6-814a-ed52400ae280

**Comment by mgarciaQ76** [comment]
Buen dia.

Revisando esto detecto que si pruebo busqueda avanzada en orden de trabajo, el problema persiste.

Lo mismo en ventana SDN, primera venta, asi como en busqueda avanzada de ov y al generar nueva orden (seteo fecha de hoy y me ingresa la de ayer)
Instancia cac
Rol admin

https://github.com/solop-develop/frontend-core/assets/139590879/50cf4ad3-504e-47d4-bccd-7c0c6ba617ce

**Comment by elsiosanchez** [comment]
Saludos @mgarciaQ76 

El problema es que no tienen la version del `Versión del Front-End` Actualizado
![image](https://github.com/solop-develop/frontend-core/assets/45974454/8f8fa6a6-ea51-4d20-ae80-7edd6db7f220)


![image](https://github.com/solop-develop/frontend-core/assets/45974454/f534381f-55fb-429b-80d8-5e7a11639f8e)

**Comment by niclopup** [comment]
Se sube versión del Front 3.6.5 y se ve que sigue el problema. Busca bien pero no define bien la fecha.

Al intentar definir el 1/9 define un día antes en el campo de busqueda pero aplica la busqueda para el 2/9

![image](https://github.com/solop-develop/frontend-core/assets/31936815/b5ab3a44-e14f-45b7-845b-f46dddced404)

![Busqueda de Registro en ventana por fecha mal](https://github.com/solop-develop/frontend-core/assets/31936815/b8bba6c2-bc4d-407d-94bc-bba41010899e)
