### ISSUE TITLE
Limpia filtros al ir a otra ventana

### ISSUE THREAD

**Issue by mgarciaQ76** [solop-develop/vue-1.0#1991]
## Bug report
si en orden de trabajo (por ejemplo) tengo un filtro determinado (ejemplo, orden de trabajo con fecha hoy) si consulto otra ventana y vuelvo a orden de trabajo me cambia el filtro default y me muestra el ultimo registro de la seleccion que tenia (en este caso el ultimo registro del dia de hoy).

#### Steps to reproduce

1. [Busqueda por filtro en ventana]
2. [Consultar otra ventana

#### Screenshot or Gif（截图或动态图）

https://github.com/solop-develop/frontend-core/assets/139590879/036f7436-f026-430e-9e38-678a506f29cf

#### Expected behavior
Que mantenga los filtros seteados en la primera ventana aun cuando consulte otra ventana

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:
Instancia http://cac.solopcloud.com/#
Rol Admin

**Comment by EdwinBetanc0urt** [comment]
Corregido a partir de la versión del frontend https://github.com/solop-develop/frontend-core/releases/tag/3.6.0

https://github.com/solop-develop/frontend-core/assets/45974454/810985cd-338e-4ea8-b253-c2d6ec62b9b2

**Comment by EdwinBetanc0urt** [comment]
Corregido a partir de la versión del frontend https://github.com/solop-develop/frontend-core/releases/tag/3.6.0

https://github.com/solop-develop/frontend-core/assets/45974454/810985cd-338e-4ea8-b253-c2d6ec62b9b2
