### ISSUE TITLE
MS Cache > Diccionario > Menú

### ISSUE THREAD

**Issue by elsiosanchez** [solop-develop/vue-1.0#1994]
### **Descripción**:
Actualmente, estamos trabajando en la implementación de un caché genérico para mejorar el rendimiento y la eficiencia del sistema. Por lo cual necesitamos implementar el caché para el **Menú** en el **Diccionario**.

### **Objetivo**:
El objetivo de este issue es diseñar e implementar un mecanismo de caché para el Menú en el Diccionario, lo que permitirá acceder a los datos de manera más rápida y eficiente, sin la necesidad de consultar constantemente al backend.

**Comment by EdwinBetanc0urt** [comment]
El menú fue migrado a `OpenSearch`, actualmente puede funcionar tanto con el backend java como con el gateway de open search en rust, sin embargo los endpoints son distintos.
