### ISSUE TITLE
MS Cache > Diccionario > Proceso

### ISSUE THREAD

**Issue by elsiosanchez** [solop-develop/vue-1.0#1996]
### Descripción:
Se requiere implementación de un caché  genérico para mejorar el rendimiento y la eficiencia del sistema, es necesario implementar un caché para los **Procesos** en el **Diccionario**.

### Objetivo:
El objetivo de este issue es diseñar e implementar un mecanismo de caché para los **Procesos** en el **Diccionario**. Esto permitirá acceder a los datos de los **Procesos** de manera más rápida y eficiente

**Comment by EdwinBetanc0urt** [comment]
Disponible a partir de las versiones de `OpenSearch Gateway RS` https://github.com/adempiere/opensearch_gateway_rs/releases/tag/1.1.3, `Backend` https://github.com/solop-develop/adempiere-grpc-server/releases/tag/3.0.9, `UI Gateway` https://github.com/adempiere/adempiere-ui-gateway/releases/tag/1.0.9 y `Frontend` https://github.com/solop-develop/frontend-core/releases/tag/3.6.3


https://github.com/solop-develop/frontend-core/assets/45974454/391ba781-1b9b-4e4b-9628-b71265ad726e
