### ISSUE TITLE
Proceso: Apertura > Árbol de Menú

### ISSUE THREAD

**Issue by elsiosanchez** [solop-develop/vue-1.0#20]
Requiere dar soporte para abrir los procesos desde el menú como actualmente se realiza en la interfaz ZK

![zk](https://user-images.githubusercontent.com/45974454/166957884-12c1626c-8aef-49aa-adde-ad89bb872ca5.gif)

**Comment by elsiosanchez** [comment]
Actualmente en la interfaz de ADempiere-Vue se le dio soporte para abrir los procesos desde el menu
![Ui](https://user-images.githubusercontent.com/45974454/166958300-504bcf60-7c28-46c2-a91a-545092868f2d.gif)

**Comment by EdwinBetanc0urt** [comment]
Los casos de uso para esta funcionalidad se pueden ver aquí: 
https://solop-develop.github.io/frontend-core/es/guide/use-cases/process.html#arbol-de-menu
