### ISSUE TITLE
Smart Browser no muestra columnas ni datos

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#200]
Se intenta visualizar el SB "Procesar Ordenes en lote" pero no se tiene exito.

https://user-images.githubusercontent.com/31936815/175379332-ad436da9-bba9-419e-a578-7fff1fdaea3d.mp4

**Comment by EdwinBetanc0urt** [comment]
Corregido en los cambios del pull request https://github.com/solop-develop/frontend-core/pull/201 y del pull request https://github.com/solop-develop/frontend-default-theme/pull/60
