### ISSUE TITLE
"Búsqueda" en campo "C_Project".

### ISSUE THREAD

**Issue by mgarciaQ76** [solop-develop/vue-1.0#2005]
## Bug report

En costos de Proyecto, al buscar por proyecto queda procesando. En zk realiza la búsqueda ok

#### Steps to reproduce

1. [entrar en costos de proyecto]
2. buscar por proyecto]

#### Screenshot or Gif（截图或动态图）

![costos de proyecto procesando en vue](https://github.com/solop-develop/frontend-core/assets/139590879/626cfeb2-4d9b-416d-baec-5c678c06607b)
![costos de proyecto mensaje al buscar](https://github.com/solop-develop/frontend-core/assets/139590879/3ed83f73-b789-4aca-9e87-6de64f76dfcf)
![costos de proyecto busqueda por proyecto en zk](https://github.com/solop-develop/frontend-core/assets/139590879/d51671ab-3f05-4011-8bb3-ea4da2eb3c6a)

#### Expected behavior
Que VUE realice la busqueda tal como en zk

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:
instancia http://cac.solopcloud.com/

Rol admin

**Comment by Ricargame** [comment]
Cambios disponibles apartir de la versión: https://github.com/solop-develop/frontend-core/releases/tag/3.9.3


https://github.com/solop-develop/frontend-core/assets/78000356/1f5885fd-2703-4841-a759-ee847ff1b51b
