### ISSUE TITLE
[Bug Report] Traducción de la pestaña de grafico de ventana en español

### ISSUE THREAD

**Issue by Ricargame** [solop-develop/vue-1.0#2006]
#### Steps to reproduce

1. Iniciar sesión con el rol "GardenWorld Admin"
2. Ir a la ventana de productos 
3. Abrir la panel lateral 

#### Screenshot or Gif（截图或动态图）

![image](https://github.com/solop-develop/frontend-core/assets/78000356/85613c61-512e-456e-ac30-7b5c06413c4a)

#### Expected behavior
Se espera que en lugar de "Panel de control" la traduccion diga "Graficos, Graficos asociados o Graficos de ventana" 

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:

**Comment by EdwinBetanc0urt** [comment]
Cambios disponibles a partir de la versión del frontend https://github.com/solop-develop/frontend-core/releases/tag/3.6.3
![image](https://github.com/solop-develop/frontend-core/assets/78000356/7a927765-49fe-44e9-9896-1577d8cca87a)

![image](https://github.com/solop-develop/frontend-core/assets/78000356/40d4b62f-126e-43b4-9511-2b34e55f7d11)
