### ISSUE TITLE
Configuración de Tableros a mostrar en Panel de Control

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#2007]
## Bug report

No se ve ninguna manera de poder configurar por ROL o de alguna manera genérica si se desea utilizar o no tableros en el Panel de Control (INICIO) de los usuarios.

Se debería considerar la definiicón del rol para mostrar o no un tablero con sus datos.

AD_Role_ID=1000002 - PA_DashboardContent_ID
![image](https://github.com/solop-develop/frontend-core/assets/31936815/cc86b598-0258-4d46-bbd7-b50b93805d32)

Esto está relacionado con la #1748 

#### Screenshot or Gif（截图或动态图）

Si se realiza la edición de los permisos para un mismo usuario el cambio es aplicado correctamente, pero sólo mientras no reinicie cache y utilice la misma PC.

![Tableros Visibilidad por defecto mismo usuario](https://github.com/solop-develop/frontend-core/assets/31936815/5ad06a8a-8640-4e78-a77c-82f2f2d4ed02)

Si se entra con otro usuario o con el mismo como incógnito, muestra de nuevo la configuración por defecto.

![Tableros Visibilidad por defecto mismo usuario como incógnito](https://github.com/solop-develop/frontend-core/assets/31936815/54413d72-9fc9-4733-86d9-3d930141f1fc)
![Tableros Visibilidad por defecto](https://github.com/solop-develop/frontend-core/assets/31936815/32478dfb-a13c-4ff1-80f2-8fabc7fd0514)

**Comment by EdwinBetanc0urt** [comment]
Disponible a partir de la versión del frontend https://github.com/solop-develop/frontend-core/releases/tag/3.8.3


https://github.com/solop-develop/frontend-core/assets/20288327/40363031-5dc6-4806-8ee6-7cc3f90752bc

**Comment by niclopup** [comment]
perdón pero no comprendo como se puyede definir que no se desea mostrar para cierto ROL el panel de "AVISOS"

Veo que está editable y configurable desde la sesión, pero eso no se guarda en el usuario ni en el rol para cada vez que entre. 

Lo que se desea es poder configurar cuando se debe mostrar los avisos y cuando no según ROL

**Comment by niclopup** [comment]
Se soluciona los avisos en la #2128
