### ISSUE TITLE
Orden de Actualizaciones en Feed de Issues incorrecto

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#2008]
## Bug report

Encontré un problema que no se visualizaban los comentarios que hacía sobre las solicitudes, ánalizando el mismo veo que al parecer el orden está considerando el órden cronológico de las actualizaciones, sino algún otro criterio q no comprendo.

![image](https://github.com/solop-develop/frontend-core/assets/31936815/c7f6d0ec-85b6-4221-8abe-4c6c9bdf150e)

Agrego video 

#### Steps to reproduce

Ver Solicitud 1000040 
Organización: Agencia SA

#### Screenshot or Gif（截图或动态图）

https://github.com/solop-develop/frontend-core/assets/31936815/7414e49a-e616-489c-9307-ff536d2fd16f

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:

**Comment by EdwinBetanc0urt** [comment]
Corrección disponible a partir de la versión del backend  https://github.com/solop-develop/adempiere-grpc-server/releases/tag/3.1.6

https://github.com/solop-develop/adempiere-grpc-server/assets/20288327/458ead8d-3a41-40a8-8606-a1403163078f
