### ISSUE TITLE
Cambio Visual en Changelog del Feed de las Issues

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#2009]
## Feature request

Los cambios que son por Changelog se están definiendo en **"Negria"** y esta mostranod el nombre del campo en la tabla cuando no es necesario que lo vea un usuario. Basta sólo dejar el nombre del campo, sin el ID.

Dejar solo:
Socio del Negocio

no :
Socio del Negocio (C_BPartner_ID)

![image](https://github.com/solop-develop/frontend-core/assets/31936815/3153c695-2475-42c6-ae37-5c5b3f09a6a7)

**Comment by EdwinBetanc0urt** [comment]
Cambios disponibles a partir de la versión del frontend https://github.com/solop-develop/frontend-core/releases/tag/3.6.3

![image](https://github.com/solop-develop/frontend-core/assets/78000356/669f1882-416c-41ad-976a-8f46ea307f5c)0

**Comment by EdwinBetanc0urt** [comment]
Este issue se abre debido a que no se cambio la fuente y tamaño para el feed cuando es comentario.

![imagen](https://github.com/solop-develop/frontend-core/assets/20288327/80f0e7d3-8d17-4807-bd0e-49de39ef73e8)

**Comment by EdwinBetanc0urt** [comment]
Corrección disponible a partir de la versión del frontend https://github.com/solop-develop/frontend-core/releases/tag/3.7.5

![image](https://github.com/solop-develop/frontend-core/assets/20288327/6d4e6353-3183-4e07-a0a8-65756fdfc15b)
