### ISSUE TITLE
Error al abrir ventana de Orden de Trabajo (Proyecto)

### ISSUE THREAD

**Issue by nsarlabos** [solop-develop/vue-1.0#2011]
Se observa el siguiente error al abrir la ventana de Orden de Trabajo:

![error](https://github.com/solop-develop/adempiere-grpc-server/assets/29130825/d93df90a-d10d-46cf-b6d4-d3c2cc84a065)

[log_error.txt](https://github.com/solop-develop/adempiere-grpc-server/files/14640919/log_error.txt)

Instancia ADempiere:

http://demo1.solopcloud.com/

**Comment by EdwinBetanc0urt** [comment]
Corregido en espera de ser mezclado para generar release


![imagen](https://github.com/solop-develop/adempiere-grpc-server/assets/20288327/6d7729bb-7ba1-41a7-9359-00e797a46672)

**Comment by EdwinBetanc0urt** [comment]
Disponible a partir de la version del backend https://github.com/solop-develop/adempiere-grpc-server/releases/tag/3.0.4
