### ISSUE TITLE
Error al elegir cuenta bancaria en selección de pagos

### ISSUE THREAD

**Issue by nsarlabos** [solop-develop/vue-1.0#2012]
## Bug report

En ventana de selección de pagos, al elegir la cuenta bancaria se produce este error

![error](https://github.com/solop-develop/frontend-core/assets/29130825/a626e343-b2f9-4551-9ed8-528dae44ad63)

#### Screenshot or Gif（截图或动态图）

![ejemplo](https://github.com/solop-develop/frontend-core/assets/29130825/00a40a84-33ba-4b32-8f7e-e81ccc6de9c5)

**Comment by EdwinBetanc0urt** [comment]
Corregido disponible a partir de la versión del backend https://github.com/solop-develop/adempiere-grpc-server/releases/tag/3.0.5


https://github.com/adempiere/adempiere-grpc-utils/assets/20288327/375ef408-f9f4-4443-83b2-5d33335627bc

**Comment by nsarlabos** [comment]
@EdwinBetanc0urt ahora estamos teniendo estos errores al momento de seleccionar la cuenta bancaria:

![error sdp](https://github.com/solop-develop/frontend-core/assets/29130825/7e9cc803-4c85-4086-b7c8-5621c80ed81a)

**Comment by EdwinBetanc0urt** [comment]
@nsarlabos este error es distinto al alcance originalmente reportado, sin embargo ya fue reportado en otro issue https://github.com/solop-develop/frontend-core/issues/2023 y resuelto a partir del release del backend https://github.com/solop-develop/adempiere-grpc-server/releases/tag/3.0.6

**Comment by nsarlabos** [comment]
Hola @EdwinBetanc0urt si, vi el #2023, pero al seleccionar la cuenta bancaria aparece un error 500, y luego de eso sí, viene el error al elegir el tipo de documento.

**Comment by EdwinBetanc0urt** [comment]
Si el error es por un NPE de callouts corregido aca https://github.com/solop-develop/adempiere-grpc-server/pull/723 disponible a partir de la versión https://github.com/solop-develop/adempiere-grpc-server/releases/tag/3.0.6 del backend

**Comment by nsarlabos** [comment]
@EdwinBetanc0urt ok perfecto, cierro este issue.
