### ISSUE TITLE
Error al abrir ventana de Documentos por Pagar/Cobrar

### ISSUE THREAD

**Issue by nsarlabos** [solop-develop/vue-1.0#2013]
## Bug report
Se da el siguiente error al abrir ventana de documentos por pagar/cobrar, y no se logra ver los documentos

![image](https://github.com/solop-develop/frontend-core/assets/29130825/63fdacc6-89ab-42f8-a610-4820f6e19630)

http://demo1.solopcloud.com/

**Comment by EdwinBetanc0urt** [comment]
Este error no es replicable en una base de datos semilla, puede que exista una definición incorrecta en alguna de las columnas o campos del encabezado.

**Comment by nsarlabos** [comment]
Hola @EdwinBetanc0urt si, en principio pensé que podria ser algo de eso, pero el tema es que funciona bien en ZK, el problema es sólo con VUE.

VUE

![vue](https://github.com/solop-develop/frontend-core/assets/29130825/13726e1a-433f-4289-9296-f0efa1894759)

ZK

![zk](https://github.com/solop-develop/frontend-core/assets/29130825/82945488-d308-4101-8f32-5ced65d0f67e)

Si te parece, en todo caso podemos verlo en una llamada.

**Comment by EdwinBetanc0urt** [comment]
Se corrigió un error con respecto a la columna que trae el valor de visualización del registro, sin embargo el ejecutar la consulta generada indica que tiene múltiples registros

```log
 SQL Error [21000]: ERROR: more than one row returned by a subquery used as an expression
```
Específicamente con respecto a la columna `AD_SysConfig_ID` que tiene valor en `ColumnSQL`

![imagen](https://github.com/solop-develop/frontend-core/assets/20288327/cc3ef61a-ce71-4649-a33a-902d73051d88)

Se corrige agregando un `LIMIT 1` en el valor de `ColumnaSQL` quedando de la siguiente mangera

```sql
SELECT AD_SysConfig_ID FROM AD_SysConfig WHERE Name = 'test' LIMIT 1
```

![imagen](https://github.com/solop-develop/frontend-core/assets/20288327/f4ac9100-699c-42be-b76c-7f35a2dfa5d4)


![imagen](https://github.com/solop-develop/frontend-core/assets/20288327/7916fc41-3c3c-43cb-9e12-c486248ebdd0)

**Comment by EdwinBetanc0urt** [comment]
Corregido listo para pruebas a partir de la versión del backend  https://github.com/solop-develop/adempiere-grpc-server/releases/tag/3.0.9

![imagen](https://github.com/solop-develop/frontend-core/assets/20288327/7916fc41-3c3c-43cb-9e12-c486248ebdd0)
