### ISSUE TITLE
No se puede cargar Adjunto en Logos de la Compañía ni a la Organización

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#2020]
## Bug report

![image](https://github.com/solop-develop/frontend-core/assets/31936815/fb81d884-11d2-4e68-8f39-e797fa6f3500)

Se oprime sobre el campo del adjunto del logo, se selecciona el archivo pero no carga nada. 

Tampoco se ven los comandos típicos de los adjuntos que si se ven en otros campos.

Lo mismop pasa con ventana "Organización"

![image](https://github.com/solop-develop/frontend-core/assets/31936815/c5f175bc-4b74-4829-9231-f0a663549353)

#### Steps to reproduce

1. [xxx]
2. [xxx]
3. [xxxx]

#### Screenshot or Gif（截图或动态图）

https://github.com/solop-develop/frontend-core/assets/31936815/b2930df9-84bb-458e-bf75-36df3cec6d7a

https://github.com/solop-develop/frontend-core/assets/31936815/df52058b-acaf-41ee-aecd-e2bc5c41036b

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:

**Comment by EdwinBetanc0urt** [comment]
El problema que se presenta es que en la pestaña donde se trata de adjuntar no tiene una columna como clave es decir `AD_ClientInfo_ID` o `AD_OrgInfo_ID`. Se debe evaluar como proceder con tablas de este tipo o tablas de claves compuestas.

**Comment by Ricargame** [comment]
Cambios disponibles apartir de la versión: https://github.com/solop-develop/frontend-core/releases/tag/3.8.5


https://github.com/solop-develop/frontend-core/assets/78000356/b43cefb6-0107-46e0-9988-ec19d2879cdd

**Comment by Ricargame** [comment]
Cambios disponibles apartir de la versión: https://github.com/solop-develop/frontend-core/releases/tag/3.9.3


https://github.com/solop-develop/frontend-core/assets/78000356/50b6d730-dbb1-459b-9444-947d0f443287
