### ISSUE TITLE
Errores en Buscador de Productos

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#2021]
## Bug report

Se encontraron los siguientes errores en el buscador de productos en orden de prioridad:
- Busqueda por nombre no funciona.
- busqeuda por Código funciona mal. Copia en SKU cuando no debería
- cambiar de pagina vuelve para la paginación (cantidad de registros) por defecto
- Ordenar por columna no permite hacer click. no se puede ordenar por Producto,  nombre categoría, precios, etc.
- Cerrar abrir buscador de productos meustra lista de precios con ID.

#### Screenshot or Gif（截图或动态图）

https://github.com/solop-develop/frontend-core/assets/31936815/84d2bf3f-eeb2-4909-b384-26aa6415e06b

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:

**Comment by EdwinBetanc0urt** [comment]
Corregido, estará disponible en la siguiente versión https://github.com/solop-develop/frontend-core/releases/tag/3.6.3

https://github.com/solop-develop/frontend-core/assets/20288327/852aca70-4c3a-4363-9b40-5bfc94b3718a
