### ISSUE TITLE
Error lista desplegable campos Tipo de Documento y Acción de Documento

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#2023]
## Bug report
Está saltando el siguiente cartel al seleccionar una lista desplegable desde un campo:
Esto aparece en diferentes campos 

**Tipo de Documento**

`
Se ha producido un error inesperado, intente nuevamente org.postgresql.util.PSQLException: ERROR: syntax error at or near "WHERE" Position: 338, SQL=SELECT COUNT(*) FROM C_DocType INNER JOIN C_DocType_TRL ON (C_DocType.C_DocType_ID=C_DocType_Trl.C_DocType_ID AND C_DocType_Trl.AD_Language='es_MX') WHERE C_DocType.DocBaseType='POO' AND C_DocType.AD_Client_ID=1000001 AND (C_DocType.DocBaseType IN ('SOO', 'POO') AND C_DocType.IsSOTrx='N' AND COALESCE(C_DocType.DocSubTypeSO,' ')<>'RM') WHERE C_DocType.IsActive = 'Y' AND C_DocType.AD_Client_ID IN(0,1000001) AND C_DocType.AD_Org_ID IN(0,1000004) AND (C_DocType.C_DocType_ID IS NULL OR C_DocType.C_DocType_ID NOT IN ( SELECT Record_ID FROM AD_Private_Access WHERE AD_Table_ID = 217 AND AD_User_ID <> 1000004 AND IsActive = 'Y' ))`

![image](https://github.com/solop-develop/frontend-core/assets/31936815/96cf10b8-b4bc-4f02-99e9-0e1c974a2639)

![image](https://github.com/solop-develop/frontend-core/assets/31936815/47d83aca-21c6-45d7-8136-45ec4725bca2)

https://github.com/solop-develop/frontend-core/assets/31936815/f5c36e3d-10dc-4fb6-aa29-2e318ba4dc77

**Acción de Documento:**
Esto salta al intentar seleccionar un Acción sobnre tipo de documento en un proceso desde un SB (Generar factura desde linea de Orden) 

https://github.com/solop-develop/frontend-core/assets/31936815/48bb3a32-119e-4795-95b0-62fa6d753574

`Se ha producido un error inesperado, intente nuevamente org.postgresql.util.PSQLException: ERROR: syntax error at or near "WHERE" Position: 186, SQL=SELECT COUNT(*) FROM AD_Ref_List INNER JOIN AD_Ref_List_Trl trl ON (AD_Ref_List.AD_Ref_List_ID=trl.AD_Ref_List_ID AND trl.AD_Language='es_MX') WHERE AD_Ref_List.AD_Reference_ID=2000036 WHERE AD_Ref_List.IsActive = 'Y' AND AD_Ref_List.AD_Client_ID IN(0,1000001) AND AD_Ref_List.AD_Org_ID IN(0,1000004) AND (AD_Ref_List.AD_Ref_List_ID IS NULL OR AD_Ref_List.AD_Ref_List_ID NOT IN ( SELECT Record_ID FROM AD_Private_Access WHERE AD_Table_ID = 104 AND AD_User_ID <> 1000004 AND IsActive = 'Y' ))
`

#### Steps to reproduce

1. [xxx]
2. [xxx]
3. [xxxx]

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:  3.6.1

**Comment by EdwinBetanc0urt** [comment]
Cambios disponibles a partir de la versión del `backend` https://github.com/solop-develop/adempiere-grpc-server/releases/tag/3.0.9 y de la libreria `adempiere-grc-utils` https://github.com/adempiere/adempiere-grpc-utils/releases/tag/1.3.5

https://github.com/adempiere/adempiere-grpc-utils/assets/20288327/375ef408-f9f4-4443-83b2-5d33335627bc
