### ISSUE TITLE
Edición de Precio de Producto en Pestaña hija no toma CERO

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#2031]
## Bug report

Al querer modificar el precio en un registro de la pestaña hija de "Precio de Producto" en la ventan alsita de ,precios, si se ve en modo GRILLA no considera que se cambió el registro si se define PRECIO CERO, en cambio si se define precio diferente al existente y diferente a 0 si toma el cambio. Esto sólo pasaría en modo grilla, en mono registro funciona OK

#### Screenshot or Gif（截图或动态图）

![Edición de Pestaña en Grilla no permite precio CERO en Precio de producto](https://github.com/solop-develop/frontend-core/assets/31936815/b538d276-b0ca-4827-8788-3a22a4ebfef2)
![Edición de Pestaña en Grilla no permite en Precio de procuto](https://github.com/solop-develop/frontend-core/assets/31936815/26feb749-7a99-4524-9528-b15039aa38e8)

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version: 3.6.1

**Comment by EdwinBetanc0urt** [comment]
Disponible a partir de la version del frontend https://github.com/solop-develop/frontend-core/releases/tag/4.1.2

**Comment by niclopup** [comment]
Se prueba en la 24610 y no se guarda ok el precio nuevo cuando un producto tiene 0 en la lista de precios. 

![#2031 precio no guarda en linea OC](https://github.com/solop-develop/frontend-core/assets/31936815/bb53dd4e-49e7-4295-945a-50c2891b01a7)

**Comment by EdwinBetanc0urt** [comment]
corregido y actualizado en la instancia 24610

https://github.com/solop-develop/frontend-core/assets/20288327/2bdcd9ef-9545-4767-a687-404000cd5db3

**Comment by niclopup** [comment]
@EdwinBetanc0urt el caso que mostras no llegas nunca a replicar lo q fallaba que es al momento de guardar el precio difernte al precio de lista que tenga.

En estos casos el precio de lista de los productos es 0, para que se edite en cada documento el precio que corresponda. 

El ERROR es que no se puede digitar un precio y guardar, siempre lo deja nuevamente en 0

Mirar el ejemplo:

![Linea OC no GUARDA precio sin precio de lista](https://github.com/solop-develop/frontend-core/assets/31936815/eb0b44d0-f298-48c7-b58f-501dd8dc1b34)

**Comment by Ricargame** [comment]
Cambios disponibles apartir de la versión: https://github.com/solop-develop/frontend-core/releases/tag/4.2.0

https://github.com/user-attachments/assets/edbea89d-76a2-4829-953b-b0999ada3da5
