### ISSUE TITLE
Ventana Pago/Ciobro no muestra registros

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#2033]
## Bug report

Se abre la ventana de "pago/Cobro" pero no muestra ningún registro, pese a que los carga al parecer según se ve el total de registros que muestra la ventana.

Aparece como para guardar un nuevo pago pero si quiero ir para ver todos no puedo. 

#### Screenshot or Gif（截图或动态图）

![Ventana Pago Cobro no muestra registros](https://github.com/solop-develop/frontend-core/assets/31936815/cb5c2a94-8ab0-43d8-ad9b-3b78d57f3e30)

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version: 3.6.1

**Comment by Ricargame** [comment]
Cambios disponibles apartir de la versión: https://github.com/solop-develop/frontend-core/releases/tag/3.9.8


https://github.com/solop-develop/frontend-core/assets/78000356/6801627a-7f0a-47e1-9832-9b3392b07c3b

**Comment by mgarciaQ76** [comment]
Esto quedó ok. Se realizan pruebas con resultado exitoso ok


https://github.com/user-attachments/assets/8dfff51f-b704-4c30-8185-5f82324edbda
