### ISSUE TITLE
Error al guardar un Cobro

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#2034]
## Bug report
No se puede guardar un cobro desde la ventana Pago/Cobro

Error: 

> Cannot read properties of undefined (reading 'C_DocType_ID')

#### Screenshot or Gif（截图或动态图）

![image](https://github.com/solop-develop/frontend-core/assets/31936815/2125c35c-8c92-4496-8d40-7cc939365573)

![Error al querer guardar un Cobro](https://github.com/solop-develop/frontend-core/assets/31936815/45d0ce97-30f5-45b4-b3a5-f21afc505313)

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version: 3.6.1

**Comment by Ricargame** [comment]
Cambios disponibles apartir de la versión: https://github.com/solop-develop/frontend-core/releases/tag/3.9.8


https://github.com/solop-develop/frontend-core/assets/78000356/84304313-4cf7-455c-a749-96b64f32ea9b

**Comment by mgarciaQ76** [comment]
Esto quedó ok. Se realizan pruebas con resultado exitoso ok


https://github.com/user-attachments/assets/73e95c3e-dc20-477a-b038-fd39220fc2af
