### ISSUE TITLE
Forma: Asignación de Pagos > Listar Monedas.

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#2036]

**Comment by EdwinBetanc0urt** [comment]
Alguna observación? ya que no tiene descripción o captura este issue y esta listando las monedas.

![imagen](https://github.com/solop-develop/frontend-core/assets/20288327/99a87c82-6131-4458-bb51-4b501fd3600a)

**Comment by niclopup** [comment]
Perdón, se ve que no quedó mi comentario

Aparecen todas las monedas, pero si se quiere filtrar por UYU o USD no se encuentra la misma. NO está buscando si la moneda no está en la lista inicial que tiene el campo.

![Moneda en Asignación de Pagos](https://github.com/solop-develop/frontend-core/assets/31936815/65f980e1-5de1-4b13-8da7-13e825dba784)


Además, esta lista debería listar SOLO las monedas ACTIVAS

![image](https://github.com/solop-develop/frontend-core/assets/31936815/173ec9f0-5301-4d87-8bf7-b94c6ad073f8)

**Comment by EdwinBetanc0urt** [comment]
Disponible para pruebas


https://github.com/solop-develop/frontend-core/assets/20288327/6dd1495a-c425-46d3-a4ae-6e712e6698ff
