### ISSUE TITLE
Información de Producto completa

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#2043]
## Feature request

Se define que el **buscador de productos** será utilizado para poder buscar productos fácilmente, no para ver información general de productos como lo hace ahora ZK q en una misma ventana rinde para las dos necesidades diferentes.

Para estas necesidades de ver información general de productos, le daremos más funcionalidad a la forma **"Información de Productos"** que ahora está muy ligado al punto de venta pero en realidad no debería ser así, dejandolo libre para que toda organización pueda ver la información de sus productos desde este visor. Para esto crearé una nueva issue:

![image](https://github.com/solop-develop/frontend-core/assets/31936815/819ed4d9-34b0-4176-b843-1446d1c2b9e8)

![image](https://github.com/solop-develop/frontend-core/assets/31936815/cec06a1f-8930-402b-bbb1-2ba6f8be126d)

#### Describe alternatives you've considered

![Información de Producto completa](https://github.com/solop-develop/frontend-core/assets/31936815/0c901404-c74f-4d65-b85f-e8038fd62e63)

**Comment by EdwinBetanc0urt** [comment]
Queda pendiente agregar los filtros como almacén, y lista de precios

**Comment by Ricargame** [comment]
Cambios disponibles apartir de la versión: https://github.com/solop-develop/frontend-core/releases/tag/3.8.3

https://github.com/solop-develop/frontend-core/assets/78000356/f7f15a0e-ee9e-4203-a75e-332ec032fd36

**Comment by EdwinBetanc0urt** [comment]
Disponible a partir de la versión del front https://github.com/solop-develop/frontend-core/releases/tag/3.8.3


![Image](https://github.com/solop-develop/frontend-core/assets/20288327/5c2b5c7e-74ce-4a72-8a47-e17707fb2ac6)

**Comment by Ricargame** [comment]
Cambios disponibles apartir de la versión: https://github.com/solop-develop/frontend-core/releases/tag/3.8.5


https://github.com/solop-develop/frontend-core/assets/78000356/b44a19c0-fbd5-43d1-82de-dbc2df094802

**Comment by niclopup** [comment]
![Uploading image.png…]()

**Comment by niclopup** [comment]
![image](https://github.com/solop-develop/frontend-core/assets/31936815/62979235-752a-4864-b945-b80d83d1477a)

**Comment by Ricargame** [comment]
Cambios disponibles apartir de la versión: https://github.com/solop-develop/frontend-core/releases/tag/3.9.3

https://github.com/solop-develop/frontend-core/assets/78000356/98336c36-3da5-40d9-b78e-f8168fee1e8e
