### ISSUE TITLE
[Bug Report] Error Multiples Reportes

### ISSUE THREAD

**Issue by elsiosanchez** [solop-develop/vue-1.0#2068]
## Bug report
No se puede previsualización mas de un reporte a la ves
#### Steps to reproduce

1. ejecute el reporte de Saldos Abiertos
2. previsualización el reporte 
3. ejecute el reporte de Saldos de Socio del Negocio
4. Observe el error
#### Screenshot or Gif（截图或动态图）

https://github.com/solop-develop/frontend-core/assets/45974454/4c66cea3-821b-46fd-b216-27173fe955e4

**Comment by EdwinBetanc0urt** [comment]
Corregido y listo para pruebas

![imagen](https://github.com/solop-develop/frontend-core/assets/20288327/39b75520-f2ea-438b-a981-c1e7ecbfa349)
