### ISSUE TITLE
Forma: Asignación de Pagos > Listar Socios de Negocio.

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#2074]
Campo "Socio del Negocio" aparece oculto por defecto, aparece al hacer click sobre el campo organización recién.

![Asignación de pagos - Organización vacia no trae registros 2](https://github.com/solop-develop/frontend-core/assets/31936815/5be88e0b-6fa0-45ec-a2e9-bb283319c4b6)

**Comment by EdwinBetanc0urt** [comment]
Esto fue corregido en espera por montar

**Comment by EdwinBetanc0urt** [comment]
Corrección disponible a partir de la versión del frontend-core https://github.com/solop-develop/frontend-core/releases/tag/3.7.5

![image](https://github.com/solop-develop/frontend-core/assets/20288327/7d1a40c0-fbea-4147-9d38-650ec39fc809)
