### ISSUE TITLE
Editar Descripción desde Asignación de Pagos no permite escribir

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#2076]
## Bug report
Editar Descripción desde Asignación de Pagos no permite escribir

![image](https://github.com/solop-develop/frontend-core/assets/31936815/1f8bb036-e289-4466-9697-f9515f1835a6)

**Comment by EdwinBetanc0urt** [comment]
Disponible a partir de la versión del frontend-core https://github.com/solop-develop/frontend-core/releases/tag/3.7.3

https://github.com/solop-develop/frontend-core/assets/20288327/c4d1509b-2e3f-4f2f-8f31-d8dd00390f08
