### ISSUE TITLE
Error búsqueda de SDN y Productos desde Campo

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#2077]
## Bug report

Se intenta buscar un SDN desde la venana órdenes de venta y da error al abrir el buscador

TypeError: e.value.startsWith is not a function at http://demo1.solopcloud.com/static/js/chunk-f7c6530e.ffdbd8f1.js:1:10136 at Array.map (<anonymous>) at o.getListSearchRecords (http://demo1.solopcloud.com/static/js/chunk-f7c6530e.ffdbd8f1.js:1:10104) at o.created (http://demo1.solopcloud.com/static/js/chunk-f7c6530e.ffdbd8f1.js:1:8703) at rt (http://demo1.solopcloud.com/static/js/chunk-libs.278e8467.js:70:11687) at Bn (http://demo1.solopcloud.com/static/js/chunk-libs.278e8467.js:70:29249) at e._init (http://demo1.solopcloud.com/static/js/chunk-libs.278e8467.js:70:34602) at new o (http://demo1.solopcloud.com/static/js/chunk-libs.278e8467.js:70:35862) at sn (http://demo1.solopcloud.com/static/js/chunk-libs.278e8467.js:70:21799) at init (http://demo1.solopcloud.com/static/js/chunk-libs.278e8467.js:70:20665)

![Error búsqueda de SDN desde Campo](https://github.com/solop-develop/frontend-core/assets/31936815/babb42d5-b8da-45af-ad5d-fd77a26d99f2)

**Tampoco funciona el buscador de Productos**

![Error búsqueda de Producto desde Campo](https://github.com/solop-develop/frontend-core/assets/31936815/b8763304-4a22-43eb-bcb3-3b929788d43e)

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version: Back  spuy-rc-4.41
- Front 3.6.5

**Comment by EdwinBetanc0urt** [comment]
Corregido listo para pruebas


https://github.com/solop-develop/frontend-core/assets/20288327/f56143f0-8cc3-44c2-b26c-4b23547244e2
