### ISSUE TITLE
no se visualiza opción de Acercar Registro desde Campo 

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#2078]
## Bug report

![no se ve opción de Acercar Regstro desde Campo](https://github.com/solop-develop/frontend-core/assets/31936815/9b3f9319-1c7e-4275-995f-5cd3899a2ea8)

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:  3.6.5

**Comment by EdwinBetanc0urt** [comment]
Corregido listo para pruebas

![imagen](https://github.com/solop-develop/frontend-core/assets/20288327/ac27e030-acf6-4876-91df-19df26b59d59)


![imagen](https://github.com/solop-develop/frontend-core/assets/20288327/c1954df6-49bf-4b9a-98be-19559a9df97e)

**Comment by EdwinBetanc0urt** [comment]
Hay que cambiar el servicio para que los acercadores de campo busquen las ventanas solo al abrir la información del campo

**Comment by niclopup** [comment]
Entiendo que ya lo agregaron esto en la versión 3.9.4 no? 

![image](https://github.com/solop-develop/frontend-core/assets/31936815/4408f217-0cfe-46d1-9c7a-1f9289816887)

Intenté acercar desde un campo de "Socio del negocio" y da error

TypeError: Cannot read properties of null (reading 'zoom_windows') at Object.executeMethod (http://spdev01.solopapp.com:24610/vue/static/js/chunk-commons.d5b8641e.js:1:78008) at A (http://spdev01.solopapp.com:24610/vue/static/js/chunk-commons.d5b8641e.js:1:304416) at o.D (http://spdev01.solopapp.com:24610/vue/static/js/chunk-commons.d5b8641e.js:1:304255) at rt (http://spdev01.solopapp.com:24610/vue/static/js/chunk-libs.278e8467.js:70:11674) at o.n (http://spdev01.solopapp.com:24610/vue/static/js/chunk-libs.278e8467.js:70:13494) at rt (http://spdev01.solopapp.com:24610/vue/static/js/chunk-libs.278e8467.js:70:11674) at Dn.e.$emit (http://spdev01.solopapp.com:24610/vue/static/js/chunk-libs.278e8467.js:70:26570) at o.handleItemClick (http://spdev01.solopapp.com:24610/vue/static/js/chunk-elementUI.2689c4ff.js:9:112710) at rt (http://spdev01.solopapp.com:24610/vue/static/js/chunk-libs.278e8467.js:70:11674) at Dn.e.$emit (http://spdev01.solopapp.com:24610/vue/static/js/chunk-libs.278e8467.js:70:26570)

![image](https://github.com/solop-develop/frontend-core/assets/31936815/59cd63da-d018-4df1-856d-62ed8f7f96e7)

**Comment by elsiosanchez** [comment]
Saludos @niclopup probe en la instacia y si me funciono [24610](http://spdev01.solopapp.com:24610/vue#)


https://github.com/solop-develop/frontend-core/assets/45974454/1b4772f3-1bb3-41c6-ac02-4e77751110b9
