### ISSUE TITLE
No se visualiza Estado ni Acciones en Barra de herramientas de la ventana

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#2079]
## Bug report

No se visualiza Estado, ni Acción ni refrescar en Barra de herramientas de la ventana. tampoco la impresora q se agregó en #1756

![image](https://github.com/solop-develop/frontend-core/assets/31936815/c1fed43b-8c2c-4f3f-87d3-4c1b5e8d01cc)

Antes
![image](https://github.com/solop-develop/frontend-core/assets/31936815/802b691a-6c47-4939-b369-62995a1f98f0)

#### Steps to reproduce

1. [xxx]
2. [xxx]
3. [xxxx]

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:  3.6.5

**Comment by niclopup** [comment]
Ok, las acciones y el estado se ven

la impresora no se verá más?
#1756

**Comment by EdwinBetanc0urt** [comment]
Corregido listo para pruebas

![imagen](https://github.com/solop-develop/frontend-core/assets/20288327/dc1ea0cd-dd9b-494f-9c52-13cc7199fde2)
