### ISSUE TITLE
Error al abir SB

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#2080]
## Bug report

Error al abir SB

#### Steps to reproduce

1. Abrir SB "Consulta de Usuarios/Contactos"

#### Screenshot or Gif（截图或动态图）

![Peek 2024-04-04 12-11](https://github.com/solop-develop/frontend-core/assets/31936815/e524246c-9a66-4203-be3c-edc6eed12c32)

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version: 3.6.5

**Comment by EdwinBetanc0urt** [comment]
Corregido listo para pruebas


https://github.com/solop-develop/frontend-core/assets/20288327/c834b292-8637-4394-ab6d-9658edcb4ae0
