### ISSUE TITLE
Auditoría: Ver todos los cambios detallados abiertos

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#2081]
## Feature request

Ahora si vemos los cambios qeu tiene un registro, muestra cada uno de los Cambios realizados pero sin mostrar el detalle visible. Se debe hacer click en cada uno de ellos y si tiene muchos cambios esto puede ser medio engorroso.

![Asignación de Pagos ](https://github.com/solop-develop/frontend-core/assets/31936815/62399a85-a216-4ef6-a361-0e5408ebd4c6)

#### Describe the solution you'd like

Se solicita agregar un check o un botón de alguna manera en la parte general de la auditoría para poder Abir todos los cambios detalladamente a la vez y así evitar tener que hacr click uno a uno. 

A su vez, también se podría cabiar para que si se abre uno te cierre el otro como ahora veo que lo está haciendo

![image](https://github.com/solop-develop/frontend-core/assets/31936815/61b03858-2ceb-40f2-9ef6-309caaa3f7aa)

**Comment by EdwinBetanc0urt** [comment]
Funcionalidad disponible a partir de las versión del frontend https://github.com/solop-develop/frontend-core/releases/tag/3.7.5


https://github.com/solop-develop/frontend-core/assets/20288327/2bc3dbdb-4c60-478c-8546-380365502073


Considerar que en la definición de la tabla debe estar marcado el check de `Mantienen Bitácora de Cambios`.


![image](https://github.com/solop-develop/frontend-core/assets/20288327/bc583606-d10d-411f-8d6d-68afabcecd37)
