### ISSUE TITLE
´Filtros Cliente o Proveedor en ventana Socio del Negocio

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#2083]
## Bug report
Al parecer no hay manera de poder agregar en la búsqueda de un Socil deL Negocio según los checks de "Es Proveedor" o "Es Cliente" para ver en una búsqueda sólo los clientes o sólo los proveedores.

Tal vez es por que no están estos campos visibles en la pestaña padre, pero son campos que son de la misma tabla.

En ZK si se puede filtrar por ellos sin problema.

Entiendo que los filtros deberían ser según toda la tabla y no sólo según los campos que estén visibles.

#### Screenshot or Gif（截图或动态图）

https://github.com/solop-develop/frontend-core/assets/31936815/a1a3741a-27d1-4ebb-aff5-533beee13c86

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:

**Comment by EdwinBetanc0urt** [comment]
Aca existe un inconveniente, actualmente para la lista de campos de la búsqueda avanzada se toman los campos ya existentes en su pestaña (los visualizados), ademas del id y uuid que son básicos en cualquier pestaña, ahora se desea tener la lista de campos no visibles al nivel de la pestaña?

De ser así, debe agregarse un nuevo servicio que devuelva la lista completa de campos a nivel de tabla y mostrar por defecto los que están visualizados. Esto solo al desplegar la busqueda avanzada para no agregar peso en la carga inicial de la ventana.

**Comment by EdwinBetanc0urt** [comment]
Ahora se envían todos los campos activos de la pestaña, independientemente si están visualizados o no.

![imagen](https://github.com/solop-develop/frontend-core/assets/20288327/0a80b15f-a263-44f9-b23d-e52e2deaf299)

**Comment by Ricargame** [comment]
Cambios disponibles apartir de la versión: https://github.com/solop-develop/frontend-core/releases/tag/3.9.3


https://github.com/solop-develop/frontend-core/assets/78000356/197c0111-46ee-4ec5-93db-7493710683d5
