### ISSUE TITLE
Traducción del Panel de Control

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#2096]
## Bug report

Los portlet de "Favoritos" y "Ultimos documentos" se ven en idioma español pese a estar viendo con idioma inglés el sistema

![image](https://github.com/solop-develop/frontend-core/assets/31936815/6fdf4a67-e094-4a35-b089-5284076d183e)

![image](https://github.com/solop-develop/frontend-core/assets/31936815/03e7b343-c0e8-4261-8f30-aace2736b93b)

#### Steps to reproduce

1. [xxx]
2. [xxx]
3. [xxxx]

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:

**Comment by EdwinBetanc0urt** [comment]
Se le añadió soporte a la traducción mediante el diccionario de aplicación a partir de la versión del backend  https://github.com/solop-develop/adempiere-grpc-server/releases/tag/3.1.6


Antes del cambio de traducción:
![image](https://github.com/solop-develop/frontend-core/assets/20288327/1e4c2f77-431d-422e-9c72-eda1e1308bf3)

Despues del cambio de traducción:
![image](https://github.com/solop-develop/frontend-core/assets/20288327/f0b09d90-2413-4aaf-8c08-51cfe9185388)

![imagen](https://github.com/solop-develop/adempiere-grpc-server/assets/20288327/c22246be-8afe-4be5-8d3d-a62e99541797)
