### ISSUE TITLE
Botones de Acercar a ventana desde Favoritos no acciona correctamente

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#2098]
## Bug report

Al acercar a una ventana y pedir listar todos los registors, abre la ventana pero creando un registro nuevo en vez de mostrar todos los existentes

![image](https://github.com/solop-develop/frontend-core/assets/31936815/5c843551-33da-4c89-9b60-7716a2525d74)

#### Screenshot or Gif（截图或动态图）

https://github.com/solop-develop/frontend-core/assets/31936815/53b8a89d-6e19-4fb0-bddf-194e48155ab3

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:

**Comment by EdwinBetanc0urt** [comment]
Funciona bien con otras ventanas que no son de tipo documentos, sin embargo falla con ordenes de venta.

**Comment by Ricargame** [comment]
Cambios disponibles apartir de la versión: https://github.com/solop-develop/frontend-core/releases/tag/4.1.4


https://github.com/solop-develop/frontend-core/assets/78000356/9f232bf8-4b73-4c2d-8f69-3ac045e1b8f2

**Comment by Ricargame** [comment]
Cambios disponibles apartir de la versión: https://github.com/solop-develop/frontend-core/releases/tag/4.2.0

https://github.com/user-attachments/assets/0da26c91-8753-4424-a779-fa21ada49894
