### ISSUE TITLE
Proceso: Apertura > Buscador del Menú

### ISSUE THREAD

**Issue by elsiosanchez** [solop-develop/vue-1.0#21]
Requiere dar soporte para abrir los procesos desde el buscador del menú como actualmente se realiza en la interfaz ZK
![zk-search-menu](https://user-images.githubusercontent.com/45974454/166958606-06d38a9a-b214-4f7d-8f4b-a8b56cc871d4.gif)

**Comment by elsiosanchez** [comment]
Actualmente en la interfaz de ADempiere-Vue se le dio soporte para abrir los procesos desde el buscador del menú. Tambien se cambio de ubicación del buscador del menú al encabezado de la interfaz de ADempiere-Vue para una busqueda mas rapida y agradable para los usuarios

![vue-search-menu](https://user-images.githubusercontent.com/45974454/166958889-d1aae8e9-13e0-4320-9c90-2b47f1a0a261.gif)

**Comment by EdwinBetanc0urt** [comment]
Para el caso de uso de pruebas ver: 
https://solop-develop.github.io/frontend-core/es/guide/use-cases/process.html#buscador-del-menu
