### ISSUE TITLE
LLevar la configuración del panel lateral al perfil

### ISSUE THREAD

**Issue by elsiosanchez** [solop-develop/vue-1.0#2100]
Se requiere que las opciones de la configuracion este en el perfil del usuario

![image](https://github.com/solop-develop/frontend-core/assets/45974454/89a8abed-b000-472d-848c-cbf90dc8496a)

![image](https://github.com/solop-develop/frontend-core/assets/45974454/1df183fd-b067-4c17-b428-2c9234984a43)

**Comment by EdwinBetanc0urt** [comment]
Listo para pruebas a partir de la versión del frontend https://github.com/solop-develop/frontend-core/releases/tag/3.7.0

![imagen](https://github.com/solop-develop/frontend-core/assets/20288327/d7b62fdf-6a10-4096-989e-c41ae317dd9b)

![imagen](https://github.com/solop-develop/frontend-core/assets/20288327/467e2b08-ef0f-4ee1-9616-a0ce8accb9ae)
