### ISSUE TITLE
Ocultar panel lateral de configuración

### ISSUE THREAD

**Issue by elsiosanchez** [solop-develop/vue-1.0#2101]
Se requiere ocultar la configuracion del panel de configuracion el cual se despliega a la derecha 

![image](https://github.com/solop-develop/frontend-core/assets/45974454/9f849914-e492-42f8-9331-afa40816b361)

![image](https://github.com/solop-develop/frontend-core/assets/45974454/a79349c8-cf06-4ec8-8016-0fe08af00e02)

**Comment by EdwinBetanc0urt** [comment]
Listo para pruebas a partir de la versión del frontend https://github.com/solop-develop/frontend-core/releases/tag/3.7.0

![imagen](https://github.com/solop-develop/frontend-core/assets/20288327/d7b62fdf-6a10-4096-989e-c41ae317dd9b)
