### ISSUE TITLE
Ocultar tablero de `Por Hacer`

### ISSUE THREAD

**Issue by elsiosanchez** [solop-develop/vue-1.0#2102]
Se requiere ocultar el panel por hacer 

![image](https://github.com/solop-develop/frontend-core/assets/45974454/d25d7697-7ba0-4395-bcf5-61768214ed80)

**Comment by EdwinBetanc0urt** [comment]
Listo para pruebas a partir de la versión del frontend https://github.com/solop-develop/frontend-core/releases/tag/3.7.0


![2024-04-11_09-56](https://github.com/solop-develop/frontend-core/assets/20288327/ac526172-1f9c-45b0-876a-91e14fc225f2)
