### ISSUE TITLE
Error: No funciona las opciones del panel de `Favorites (User)`

### ISSUE THREAD

**Issue by elsiosanchez** [solop-develop/vue-1.0#2103]
Error no funciona las opciones rapidad del panel de `Favorites (User)`  

![image](https://github.com/solop-develop/frontend-core/assets/45974454/1d16431f-313a-4fb3-a5cc-8e3db3a5ee15)

**Comment by EdwinBetanc0urt** [comment]
Al acercar en nuevo no esta operando correctamente

**Comment by EdwinBetanc0urt** [comment]
Disponible a partir de la versión del front https://github.com/solop-develop/frontend-core/releases/tag/3.8.3



https://github.com/solop-develop/frontend-core/assets/20288327/0db30510-78c9-4bca-90e7-340d34ab1299

**Comment by niclopup** [comment]
No parece funcionar

Prueba realizada en SPDEV:24600

![Peek 2024-06-04 15-27](https://github.com/solop-develop/frontend-core/assets/31936815/5c7de6e2-5312-475f-9a81-fd283343f3ac)

**Comment by EdwinBetanc0urt** [comment]
cambios disponibles a partir de la versión https://github.com/solop-develop/frontend-core/releases/tag/4.0.5



https://github.com/solop-develop/frontend-core/assets/78000356/252dbde0-ba22-400b-8940-68e33c515026
