### ISSUE TITLE
Error al guardar Ordenamiento de Campos para ROL

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#2106]
## Bug report

aparece el siguiente error al intentar guardar una

org.postgresql.util.PSQLException: ERROR: transacción abortada, las órdenes serán ignoradas hasta el fin de bloque de transacción, SQL=SELECT AD_Client_ID,AD_Column_ID,AD_ContextInfo_ID,AD_FieldDefinition_ID,AD_FieldGroup_ID,AD_Field_ID,AD_Image_ID,AD_Org_ID,AD_Reference_ID,AD_Reference_Value_ID,AD_Tab_ID,AD_Val_Rule_ID,Created,CreatedBy,DefaultValue,Description,DisplayLength,DisplayLogic,EntityType,Help,Included_Tab_ID,InfoFactoryClass,IsActive,IsAllowCopy,IsCentrallyMaintained,IsDisplayed,IsDisplayedGrid,IsEmbedded,IsEncrypted,IsFieldOnly,IsHeading,IsMandatory,IsQuickEntry,IsReadOnly,IsSameLine,Name,ObscureType,PreferredWidth,SeqNo,SeqNoGrid,SortNo,Updated,UpdatedBy,UUID FROM AD_Field WHERE (AD_Column_ID = ? AND AD_Tab_ID = ?) AND IsActive=?

#### Screenshot or Gif（截图或动态图）
 
![Error al guardar un ordenamiento de campos en ventana](https://github.com/solop-develop/frontend-core/assets/31936815/7e2c0b9a-1f3b-41bb-8d53-2e2e8e96cbb5)

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:  3.6.8

**Comment by niclopup** [comment]
Instancia de pruebas (Con Opensearch)

http://host.solopapp.com:24160/vue

ZK

http://host.solopapp.com:24144/webui/index.zul


Orden "ventana de usuario"
Ventana: Producto
Rol: Distribución y Logística


![image](https://github.com/solop-develop/frontend-core/assets/31936815/808a2463-50cf-4069-a0aa-da60f33b50da)

![image](https://github.com/solop-develop/frontend-core/assets/31936815/13bd7a37-317b-46e5-91a6-035fbacb9fcf)

**Comment by niclopup** [comment]
@EdwinBetanc0urt no se si ya se subió por completo esto pero intenté guardar una modificación y saltó el mismo error.

![image](https://github.com/solop-develop/frontend-core/assets/31936815/12c6263a-4cda-45a2-8dd8-11dd5e712093)

Además me pareció raro que al intentsar seleccionar todos los Roles, no veía todos los existentes. 

La visiiulida de los campos está correcta tanto en mono registro como en grilla.

**Comment by EdwinBetanc0urt** [comment]
Localmente funciona correctamente, conversando con @rcapecce aparentemente no se integro correctamente el cambio que se subio de solop-develop al backend spuy.
