### ISSUE TITLE
Traducción de Consulta Avanzada

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#2112]
## Bug report

Si se utiliza el idioma inglés en el ERP, si se abre para ver una "Consulta Avanzada" desde una Ventana, está incorrecta la traducción del título de la ventana "Consulta Avanzada". Lo dice todo en español cuando debería seguir la traducción del idioma definida. 

#### Screenshot or Gif（截图或动态图）

![image](https://github.com/solop-develop/frontend-core/assets/31936815/345c27ad-bea6-4845-ad2f-2931ea176040)

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:

**Comment by EdwinBetanc0urt** [comment]
Corregido a partir de las versión del frontend https://github.com/solop-develop/frontend-core/releases/tag/3.7.5

![image](https://github.com/solop-develop/frontend-core/assets/20288327/e7415bb6-c8f3-4714-979d-60f9e88dcf04)
