### ISSUE TITLE
Error al abrir algunos SB

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#2113]
## Bug report

Se encuentra que algunos SB está dando error al intentar abrirlos. Esto al parecer no sucede con todos sino que algunos abre correctamente.

Abre ok:
- Consulta de Contactos/Usuarios
- Proceso de Aprobación de Requisiciones
- Generar Entregas desde linea de orden
- procesar orderners en lote

Error al abrir:
- Consulta requisiciones de material
- Crear orden de compra desde lineas de la requisicion
- Generar factura desde linea de orden

#### Screenshot or Gif（截图或动态图）

https://github.com/solop-develop/frontend-core/assets/31936815/d5213778-f0e7-4f77-a1a9-08a9265580e3

https://github.com/solop-develop/frontend-core/assets/31936815/2dbf851e-113e-4e3d-b233-a1bce9649acf

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:
![image](https://github.com/solop-develop/frontend-core/assets/31936815/9c8e3da5-9552-4e72-8051-a2bea40d2f8a)

**Comment by EdwinBetanc0urt** [comment]
Corrección disponible a partir de la versión del frontend  https://github.com/solop-develop/frontend-core/releases/tag/3.7.5
