### ISSUE TITLE
Logotipo de barra latera, isotipo de la pestaña chrome y Avatar pequeño no se ven correctametne

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#2116]
## Bug report

Se encuentran que algunos logos no se están despleganbdo correctamente

1. Logotipo Barra lateral. No se está cargando correctamente., se ve como un error de carga.
2. Isotipo de la pestaña. se debe definir un isotipo que no sea el de Adempiere sino uno de solop
3. texto que dice la pestaña "Perfil - ADempiere VUE" se debe cambiar por "Perfil - Solop"
4. Foto de Avatar del usuariuo en pequeño. Se muestra con error.

![image](https://github.com/solop-develop/frontend-core/assets/31936815/7f5c60cb-c37f-416e-8d07-0cb788aefc2c)

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:

**Comment by EdwinBetanc0urt** [comment]
Usuario

![Image](https://github.com/solop-develop/frontend-core/assets/20288327/e7902adf-81c4-44ff-af0b-80ecd88ce8b9)

Compañía

![Image](https://github.com/solop-develop/frontend-core/assets/20288327/8995af01-d5d9-4159-a051-051a9e3544db)

**Comment by niclopup** [comment]
![image](https://github.com/solop-develop/frontend-core/assets/31936815/8b82b9af-8439-440c-b082-8db4c3bb9f90)

Veo que volvieron a quitar el logo quemado como lo teníamos. 
Ahora no comprendo cuál es la lógica aplicada ya que en Seed veo un logo definido que no se ve en la ventana de Compañía y tampoco es coherente con el logo del FavIcon de la pestaña de Chrome

![image](https://github.com/solop-develop/frontend-core/assets/31936815/1d991266-d12e-4736-832d-b904da03c1f0)

El nombre de la pestaña "Adempiere VUE" no se desde donde se está obteniendo.

Según recuerdo habían comentado que era desde la ventana "Sistema" pero acá lo muestro y no veo en ningún lugar donde diga "Adempiere VUE".

Esto está variable o está quemado?
 
![image](https://github.com/solop-develop/frontend-core/assets/31936815/aef99be3-81a5-4901-ac63-d960853112de)

**Comment by niclopup** [comment]
Agrego lo que entiendo sería un minimo a poder definir en los logos de VUE


https://github.com/solop-develop/frontend-core/assets/31936815/ce7060c8-4ab1-448b-9231-3dfa64924b15
