### ISSUE TITLE
Error al Abrir SB desde Pestaña Hija nivel 1 (fase de proyecto)

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#2119]
## Bug report
Error al abrir SB desde una pestaña hija de una ventana

<html>
<body>

TypeError: Cannot read properties of undefined (reading 'uuid') at Object.start (http://host.solopapp.com:24160/vue/static/js/chunk-7464d335.9a1c3a26.js:1:7780) at o.startProcess (http://host.solopapp.com:24160/vue/static/js/chunk-7464d335.9a1c3a26.js:1:9445) at rt (http://host.solopapp.com:24160/vue/static/js/chunk-libs.278e8467.js:70:11674) at o.n (http://host.solopapp.com:24160/vue/static/js/chunk-libs.278e8467.js:70:13494) at rt (http://host.solopapp.com:24160/vue/static/js/chunk-libs.278e8467.js:70:11674) at Dn.e.$emit (http://host.solopapp.com:24160/vue/static/js/chunk-libs.278e8467.js:70:26570) at o.handleClick (http://host.solopapp.com:24160/vue/static/js/chunk-elementUI.2689c4ff.js:9:187855) at rt (http://host.solopapp.com:24160/vue/static/js/chunk-libs.278e8467.js:70:11674) at HTMLButtonElement.n (http://host.solopapp.com:24160/vue/static/js/chunk-libs.278e8467.js:70:13494) at Ji.a._wrapper (http://host.solopapp.com:24160/vue/static/js/chunk-libs.278e8467.js:70:52151)
--
 

<br class="Apple-interchange-newline">
</body>
</html>

#### Steps to reproduce

1. [xxx]
2. [xxx]
3. [xxxx]

#### Screenshot or Gif（截图或动态图）

https://github.com/solop-develop/frontend-core/assets/31936815/39080df4-eab6-4bf4-a82b-3e04a843ab83

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:  3.7.2

**Comment by EdwinBetanc0urt** [comment]
Corrección disponible a partir de la versión del frontend https://github.com/solop-develop/frontend-core/releases/tag/3.7.5

https://github.com/solop-develop/frontend-core/assets/20288327/16cfaf78-9cec-4899-8ffb-ee015b516595
