### ISSUE TITLE
Error al correr proceso desde Proyecto (Customizado)

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#2120]
## Bug report

Error al correr un proceso desde un SB seleccionando algunas líneas 

![image](https://github.com/solop-develop/frontend-core/assets/31936815/927cc53e-8446-4bb9-a34c-e4194ee6afd7)

<html>
<body>
<div data-v-be34583a="" class="el-dialog__wrapper" style="box-sizing: inherit; position: fixed; inset: 0px; overflow: auto; margin: 0px; color: rgb(0, 0, 0); font-family: &quot;Helvetica Neue&quot;, Helvetica, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; z-index: 2178;"><div role="dialog" aria-modal="true" aria-label="dialog" class="el-dialog" style="box-sizing: border-box; margin: 15vh auto 0px; background: rgb(255, 255, 255); border-radius: 2px; box-shadow: rgba(0, 0, 0, 0.3) 0px 1px 3px; width: 1536px; transform: none; left: 0px; position: relative;"><div class="el-dialog__body" style="box-sizing: inherit; padding: 10px 20px; color: rgb(96, 98, 102); font-size: 14px; word-break: break-all; max-height: 90%; overflow: auto;"><div data-v-be34583a="" class="el-table el-table--fit el-table--border el-table--enable-row-hover el-table--enable-row-transition el-table--medium" style="box-sizing: border-box; position: relative; overflow: hidden; -webkit-box-flex: 1; flex: 1 1 0%; width: 1496px; max-width: 100%; background-color: rgb(255, 255, 255); font-size: 14px; color: rgb(96, 98, 102); border-right: none; border-bottom: none; border-top: 1px solid rgb(223, 230, 236); border-left: 1px solid rgb(223, 230, 236); border-image: initial;"><div class="el-table__body-wrapper is-scrolling-none" style="box-sizing: inherit; width: 1495px; overflow: hidden; position: relative;">
TypeError: s.a.getters.getStordTab is not a function at o.<anonymous> (http://host.solopapp.com:24160/vue/static/js/chunk-commons.6bd36b90.js:1:43158) at rr.get (http://host.solopapp.com:24160/vue/static/js/chunk-libs.278e8467.js:70:30788) at rr.evaluate (http://host.solopapp.com:24160/vue/static/js/chunk-libs.278e8467.js:70:31777) at e.i [as value] (http://host.solopapp.com:24160/vue/static/js/chunk-libs.278e8467.js:420:20056) at o.<anonymous> (http://host.solopapp.com:24160/vue/static/js/chunk-commons.6bd36b90.js:1:43322) at rr.get (http://host.solopapp.com:24160/vue/static/js/chunk-libs.278e8467.js:70:30788) at rr.evaluate (http://host.solopapp.com:24160/vue/static/js/chunk-libs.278e8467.js:70:31777) at e.i [as value] (http://host.solopapp.com:24160/vue/static/js/chunk-libs.278e8467.js:420:20056) at o.w (http://host.solopapp.com:24160/vue/static/js/chunk-commons.6bd36b90.js:1:44113) at rt (http://host.solopapp.com:24160/vue/static/js/chunk-libs.278e8467.js:70:11674)
--

</div></div></div></div></div><br class="Apple-interchange-newline">
</body>
</html>

#### Steps to reproduce

1. [xxx]
2. [xxx]
3. [xxxx]

#### Screenshot or Gif（截图或动态图）

https://github.com/solop-develop/frontend-core/assets/31936815/d1d71df2-4df1-4ed1-bd76-4ee65058c313

el parámetro del proceso sería este visto desde ZK

![image](https://github.com/solop-develop/frontend-core/assets/31936815/9e9cf7f2-c487-46c7-9a14-e39442cb639e)

#### Link to minimal reproduction（最小可在线还原demo）

ZK:http://host.solopapp.com:24144/webui/index.zul
VUE: http://host.solopapp.com:24160/vue

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version: 3.7.2

**Comment by EdwinBetanc0urt** [comment]
Corrección disponible a partir de la versión del frontend  https://github.com/solop-develop/frontend-core/releases/tag/3.7.5

https://github.com/solop-develop/frontend-core/assets/20288327/9540c317-751e-4e4c-bc39-b6fd22760ba2
