### ISSUE TITLE
Fechas en formato grilla con formato incorrecto

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#2121]
## Bug report

Fechas en formato grilla con formato incorrecto

se debe ver de igual manera tanto como mono registro como Grilla. 

Sólo la fecha, sin hora.

#### Steps to reproduce

1. Abrir ventana Ordenes de Compra en modo grilla

#### Screenshot or Gif（截图或动态图）

![image](https://github.com/solop-develop/frontend-core/assets/31936815/930608cd-b5fa-4e51-b5d6-0e95e89532a9)

![image](https://github.com/solop-develop/frontend-core/assets/31936815/811dd120-5e9a-4f43-bc85-3d1f810f0790)

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:

**Comment by elsiosanchez** [comment]
Solventado @niclopup 

![image](https://github.com/solop-develop/frontend-core/assets/45974454/d51482a5-82b7-4586-94c2-d23c96110282)

**Comment by Ricargame** [comment]
Error solucionado a partir de la versión:

Frontend
https://github.com/solop-develop/frontend-core/releases/tag/3.7.5

Backend
https://github.com/solop-develop/adempiere-grpc-server/releases/tag/3.1.6

![image](https://github.com/solop-develop/frontend-core/assets/78000356/262e4024-505f-49fc-8c5d-84f582210832)
