### ISSUE TITLE
SB "Crear Desde" en Documentos por Pagar con parámetros incorrectos

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#2124]
## Bug report

se abre el SB pero no está aplicando la lógica de condición de según le "Tipo de Documento" desde que se elija, se debería pedir que defina uno de los datos de "ordenes", "Facturas" o "RMA".
Ahora uno abre el SB y le pide todos los campos obligatoriamente y eso sería imposible,
Sólo debería mostrar un campo si se define el tipo de documento correspondiente. 

#### Steps to reproduce

1. [xxx]
2. [xxx]
3. [xxxx]

#### Screenshot or Gif（截图或动态图）

![image](https://github.com/solop-develop/frontend-core/assets/31936815/b6fe0299-b904-4584-8a65-f101c5cff36a)

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:

**Comment by niclopup** [comment]
sucede lo mismo para el SB "Crear Desde Orden/RMA" en Recepción de Productos

![image](https://github.com/solop-develop/frontend-core/assets/31936815/9c4d8000-88d4-4c79-ad2c-d83274ec2930)

**Comment by EdwinBetanc0urt** [comment]
Corrección disponible a partir de la versión del frontend https://github.com/solop-develop/adempiere-grpc-server/releases/tag/3.1.6

https://github.com/solop-develop/frontend-core/assets/20288327/9264c1c3-b412-47dd-b734-a082287fc42c
