### ISSUE TITLE
No se visualiza pestaña del Asiento contable en los documentos

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#2125]
## Bug report

Se  busca la pestaña y no se ve en las pestañas laterales

![image](https://github.com/solop-develop/frontend-core/assets/31936815/09eb2ab2-0523-4105-bde3-45753bb1109e)

Se apreta el boton de "Contabilizado" y abre una pestaña lateral vacía.

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:

**Comment by EdwinBetanc0urt** [comment]
Esta corrección esta disponible a partir de la versión del frontend  https://github.com/solop-develop/frontend-core/releases/tag/3.7.6

https://github.com/solop-develop/frontend-core/assets/20288327/1f0985cf-9336-4c11-b3ed-b9fbcc775b40
