### ISSUE TITLE
No se asigna fecha en smart browser

### ISSUE THREAD

**Issue by nsarlabos** [solop-develop/vue-1.0#2126]
## Bug report
En el smart browser de "Consulta de Usuarios", por ejemplo, se define la fecha de cumpleaños, pero la misma no es asignada al usuario, a pesar de que el proceso devuelve mensaje como exitoso.

Esto funciona bien desde ZK.

#### Screenshot or Gif

![error fecha sb](https://github.com/solop-develop/frontend-core/assets/29130825/6a71ccd9-310e-42a5-9f93-ae7fd7d69680)

#### Additional context

http://host.solopapp.com:24160/vue#

**Comment by Ricargame** [comment]
Error solucionado a partir de la versión:

Frontend
https://github.com/solop-develop/frontend-core/releases/tag/3.7.5

Backend
https://github.com/solop-develop/adempiere-grpc-server/releases/tag/3.1.7

https://github.com/solop-develop/frontend-core/assets/78000356/eb5c4d2d-7216-453d-a9ba-aa34400e3914

**Comment by niclopup** [comment]
No se logra verificar con éxito

![Actualizar Fecha desde SB con Error](https://github.com/solop-develop/frontend-core/assets/31936815/89e2c501-8995-4125-8c8b-38cd3f7a353a)


![image](https://github.com/solop-develop/frontend-core/assets/31936815/a0928b72-4f28-43e2-8c38-efd74e1a3a9d)

**Comment by EdwinBetanc0urt** [comment]
El guardar (para editar registro) funciona dándole doble clic en la fila para salir de la edición, quizás deba hacerse un cambio a nivel visual para agregar el botón de guardado.

Considerando que aunque existan columnas editables, solo se guardaran aquellas que son de la tabla configurada, como el caso de `Cumpleaños` que existe en el smart browse tanto para usuario como `CONTACT_Birthday` y para socio de negocio como `PARTNER_Birthday`, hay que saber cual de las 2 esta visualizado en el smart browse para saber que efectivamente si se esta guardando el cambio en el campo correcto.

**Comment by elsiosanchez** [comment]
Saludos! @nsarlabos  https://github.com/solop-develop/adempiere-grpc-server/blob/develop/src/main/java/org/spin/grpc/service/BusinessData.java#L338 en esta linea es a donde tienen que colocar el punto de interrupción al momento de depurar para que evaluen lo del proceso en la fecha
