### ISSUE TITLE
Visualisacion del panel de `Aviso`

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#2128]
Definido en #2007 

Se desea dar la opcion de poder ociultar ver los avisos según Rol

**Comment by EdwinBetanc0urt** [comment]
Disponible a partir de la versión del frontend https://github.com/solop-develop/frontend-core/releases/tag/3.8.3


https://github.com/solop-develop/frontend-core/assets/20288327/40363031-5dc6-4806-8ee6-7cc3f90752bc

**Comment by niclopup** [comment]
perdón pero no comprendo como se puyede definir que no se desea mostrar para cierto ROL el panel de "AVISOS"

Veo que está editable y configurable desde la sesión, pero eso no se guarda en el usuario ni en el rol para cada vez que entre. 

Lo que se desea es poder configurar cuando se debe mostrar los avisos y cuando no según ROL

**Comment by EdwinBetanc0urt** [comment]
Como esta funcionalidad no esta en ADempiere (Zk/Swing) se debe validar si existe en el menú para visualizarla.
