### ISSUE TITLE
Nuevo Filtro en la Forma "Issues"

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#2130]
## Feature request

Actualmente entiendo que la Forma "Issues" está cumpliendo la siguiente condición para mostrar las Issues:

`(R_Request.SalesRep_ID=@#AD_User_ID@ OR R_Request.AD_Role_ID=@#AD_Role_ID@) AND (R_Request.R_Status_ID IS NULL OR R_Request.R_Status_ID IN (SELECT R_Status_ID FROM R_Status WHERE IsClosed='N'))
`

![image](https://github.com/solop-develop/frontend-core/assets/31936815/946788fb-fce7-4c64-b9fb-32bf6b8eff06)

Se desea poder visualizar también aquellas Solicitudes que están abiertas y cumplan también la siguiente condición:

R_Request WHERE R_Category_ID
Tal que el usuario esté defindo en la tabla -> R_CategoryUpdates WHERE AD_User_ID=1000004

R_RequestType_ID
Tal que el usuario esté defindo en la tabla -> R_RequestTypeUpdates WHERE AD_User_ID

R_Group_ID
Tal que el usuario esté defindo en la tabla -> R_GroupUpdates WHERE AD_User_ID

#### Describe the solution you'd like

Creo que lo mejor sería modificar directamente la condición que se aplica para mostrar las issues en esta forma.

Otra opción que tenemos es crear otra forma igual a esta pero agregarle un nuevo filtro. Esto no creo que sea la mejor opción yua que estaríamos repitiendo una funcionalidad. En el día de mañana se podrá aplicar diferentes filtros editables ne esta forma para poder filtrar más aún las ssues a mostrar. Ej: Contrato, Proyecto, Grupo, Clasificación

**Comment by EdwinBetanc0urt** [comment]
Se debe agregar al menú de vistas



![Image](https://github.com/solop-develop/frontend-core/assets/20288327/3e27a9b0-777d-43a8-9d11-a9d1dea6c18a)

y se debe verificar si en el menú existe la ventana `Request (All)` para mostrar u ocultar.

**Comment by Ricargame** [comment]
Cambios disponibles apartir de la versión: https://github.com/solop-develop/frontend-core/releases/tag/3.9.3


https://github.com/solop-develop/frontend-core/assets/78000356/32ba5dbb-b9d0-48f3-95b7-11fa254bff24
