### ISSUE TITLE
Ventana modo grilla muestra campos de registro seleccionado con los ID en vez del Nombre

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#2144]
## Bug report

Se abre la ventana Requisición con datos y se ve que la primer línea que aparece como seleccionada muestra los campos no con el nombre sino con el ID

![image](https://github.com/solop-develop/frontend-core/assets/31936815/8afcce49-a07d-4e95-8a5e-3462074d82f9)

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:  3.7.2

**Comment by Ricargame** [comment]
buenos dias señor @niclopup realice la misma prueba en su instancia y no me salio el error, podría volver a revisar


https://github.com/solop-develop/frontend-core/assets/78000356/d8e9bac5-bc2f-4963-b921-41fd06daa4ee
