### ISSUE TITLE
Precio en línea de Orden de Compra no se guarda

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#2145]
## Bug report
Se intenta crear una orden de compra manualmente desde la ventana pero no permite definir de ninguna manera un precio en la línea de la orden.

Se actualiza bien el LineNetAmt pero al guardar lo lleva de nuevo a cero

#### Screenshot or Gif（截图或动态图）

![Linea OC no actualiza total de linea](https://github.com/solop-develop/frontend-core/assets/31936815/dc63b041-ac69-44e3-9ac6-eb9b52a2c649)

En zk veo que guardó todo menos el "Precio Actual" 

![image](https://github.com/solop-develop/frontend-core/assets/31936815/1d8f104f-a0ec-4322-844f-8a33695da7ac)

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:  3.7.2

**Comment by Ricargame** [comment]
buenos dias señor @niclopup  realice la misma prueba en su instancia y no me salio el error, podría volver a revisar 

https://github.com/solop-develop/frontend-core/assets/78000356/de1fb1fc-2f9b-49d4-89a8-8266cdddbd66
