### ISSUE TITLE
Asiento Diario desde ventana muestra mal el Importe de Crédito Contabilizado

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#2164]
## Bug report

Se abre un asiento desde un Documento y muestra en las columnas de "Débito Contabilizado" y "Crédito Contabilizado", el "Crédito Contabilizaod" lo muestra con el importe de lo que sería el "Crédito FUENTE", es decrie en l a moneda del documento en vez de mostrar el importe en moneda contable.

Si se ve el asiento desde ZK se visualiza claramente el error

ZK
![image](https://github.com/solop-develop/frontend-core/assets/31936815/24d75e6f-0623-4df4-a193-a5a10d95f2b9)

VUE

![image](https://github.com/solop-develop/frontend-core/assets/31936815/5ce15729-1f5c-44c5-8ae2-863cf7449346)

#### Steps to reproduce

1. [xxx]
2. [xxx]
3. [xxxx]

#### Screenshot or Gif（截图或动态图）

![Asiento Diario muestra mal el Crédito Contabilizado](https://github.com/solop-develop/frontend-core/assets/31936815/e977d7b0-a7e5-43d2-84f3-34350129b2cb)

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:

**Comment by Ricargame** [comment]
Cambios disponibles apartir de la versión: https://github.com/solop-develop/frontend-core/releases/tag/3.9.3


https://github.com/solop-develop/frontend-core/assets/78000356/c8c21cfa-64f7-42ec-9deb-447a04552a41

**Comment by niclopup** [comment]
persiste el error con asientos en moneda extranjera. Con Moneda del documento diferente al esquema contable.

**Comment by yamelsenih** [comment]
Hola @Ricargame el problema aquí es que la tabla no está mostrando las columnas correctas.

Si ejecutas esto local lo puedes ver
```
http://0.0.0.0/api/general-ledger/accounts/facts/1000001/document/M_InOut/1000625?table_name=M_InOut&record_id=1000625&record_uuid=d79b2d38-e643-4375-b4a0-47c83b2b896b&organization_id=1000010&page_size=15
```

La respuesta de la petición por cada fila debe devolver algo como esto

```Json
"AmtSourceDr": {
                    "type": "decimal",
                    "value": "0.00"
                },
                "AmtSourceCr": {
                    "type": "decimal",
                    "value": "5000.00"
                },
                "AmtAcctDr": {
                    "type": "decimal",
                    "value": "0.00"
                },
                "AmtAcctCr": {
                    "type": "decimal",
                    "value": "193805.00"
                },
```

Debes mostrar en la tabla son los valores de:

- Débito Contabilizado: `AmtAcctDr`
- Crédito Contabilizado: `AmtAcctCr`

Ahora mismo está mostrando es el crédito fuente que es el monto en la modeda del documento y no en la moneda del esquema contable donde se contabilizó

**Comment by Ricargame** [comment]
Cambios disponibles partir de la versión del front https://github.com/solop-develop/frontend-core/releases/tag/4.4.020

https://github.com/user-attachments/assets/351b0938-f902-4be1-82f4-33274619d511

**Comment by niclopup** [comment]
no se como probé esto.. pero claramente no fue bien validado.

EL asiento ahora sólo muestra el Importe Contabilizado pero no el "importe fuente"

![image](https://github.com/user-attachments/assets/ce2f1fba-182a-477a-8947-8edc58f7a1a0)


para verificar el caso correctamente se debe ver un documento que sea en moneda extranjera. USD por ejemplo 
como el esquema contable está en UYU deberá mostrar diferentes importes en la columna de "Débito Contabilizado" a "Débito Fuente"

![image](https://github.com/user-attachments/assets/4f8d75bf-a8a1-4906-9732-552f87e3fd6a)

![image](https://github.com/user-attachments/assets/a9c7ac14-d10b-417c-be7b-b6fcecaa848d)



https://github.com/user-attachments/assets/4359fbd7-439c-4f36-ab88-6631e82d466c

**Comment by Ricargame** [comment]
Cambios disponibles a partir de la versión del frontend: https://github.com/solop-develop/frontend-core/releases/tag/4.4.025

https://github.com/user-attachments/assets/fa12c2a1-d8ef-4709-9368-9c31863db307
