### ISSUE TITLE
Localización: Campos de Geo-localización no se visualizan ni acciona nada

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#2169]
## Bug report

No se puede definir una Geo-localización desde una dirección en VUE

No abre la ventana de definir los 3 campos

No abre un mapa dentro de la aplicación donde muestre googlemaps y la ubicación

#### Screenshot or Gif（截图或动态图）

![Geo Localización no funciona en VUE como ZK](https://github.com/solop-develop/frontend-core/assets/31936815/2f1ffb12-55ba-49ce-b13d-2bc3f242c1a2)

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:

**Comment by EdwinBetanc0urt** [comment]
Son necesarias las coordenadas para abrir el mapa de google. Se deben agregar nuevamente para que funcione, o en su defecto hacer una búsqueda en los mapas de google con los datos de la ubicación.

**Comment by Ricargame** [comment]
El campo de geolocalización ya filtrar por: país, región, ciudad, coordenadas, dirección, región

**Comment by Ricargame** [comment]
Cambios disponibles apartir de la versión: https://github.com/solop-develop/frontend-core/releases/tag/3.8.5



https://github.com/solop-develop/frontend-core/assets/78000356/3a7180e7-7b7c-48a3-925e-af00e77d6632
