### ISSUE TITLE
Notas en Documento no se guardan

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#2184]
## Bug report

Se intenta crear una nota en un documento desde la pestaña lateral pero no llega a guardar el msj y no da ningún error.

luego se intenta desde la ventana "Ordenes de Venta" y tampoco guarda pero si da un error

![image](https://github.com/solop-develop/frontend-core/assets/31936815/3c8c6521-ab11-4dbc-a0e3-2a82db3a8aad)

#### Screenshot or Gif（截图或动态图）

https://github.com/solop-develop/frontend-core/assets/31936815/34bcd093-3e4f-4124-9342-37ae59a29e67

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:  3.7.6

**Comment by Ricargame** [comment]
Cambios disponibles apartir de la versión: https://github.com/solop-develop/frontend-core/releases/tag/3.8.3

https://github.com/solop-develop/frontend-core/assets/78000356/d32b6fc9-7677-41e1-9aea-5e0d6d769a66

**Comment by mgarciaQ76** [comment]
Esto quedó pronto. Se realizan pruebas con resultado exitoso ok


https://github.com/user-attachments/assets/84cf0697-dd9a-4859-abc3-56e975ceef12
