### ISSUE TITLE
Smart Browser se cierra luego de realizar acción sobre registros

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#2195]
## Bug report

Se descubre que los SB luego de realizar una acción en el proceso que tengan definido, los mismos se cierran. Este comportamiento estaría correcto si el SB está definido dentor de una ventana, como el "Crear Desde" pero si el SB está desde el menú, en realidad podría ser muy útil que el mismo no se cierre automáticamente, dando lugar para poder continuar con las acciones a realizar.

Esto puntualmente en ZK es un error que existe dado que no se estaría encontrando los registros del SB luego de haber procesado una vez el proceso del SB. Si bien no se cierra el SB automáticamente, si volves a hacer una búsqueda e intentas correr el proceso nuevamente, da error siempre ya que no encuentra nada sobre donde ejecutar el proceso.

Este problema entiendo que en VUE podríamos evitarlo, si dejamos el SB abierto podemos apliucar una nueva búsuqeda y correr nuevamente el proceso 

Comentar que les parece si es posible y te paso un ejemplo.

#### Screenshot or Gif（截图或动态图）
Acá les muestro como se está comportando ahora y la idea es poder dejarlo abierto y generar N veces un proceso desde un SB 

https://github.com/solop-develop/frontend-core/assets/31936815/834bed35-1688-44aa-84ef-d242ca00acae

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:

**Comment by EdwinBetanc0urt** [comment]
La lógica esa invertida.

**Comment by EdwinBetanc0urt** [comment]
Corregido

https://github.com/solop-develop/frontend-core/assets/78000356/bed39331-d37f-4e74-935a-b7eef631e1d6

**Comment by Ricargame** [comment]
Cambios disponibles apartir de la versión: https://github.com/solop-develop/frontend-core/releases/tag/3.9.3

https://github.com/solop-develop/frontend-core/assets/78000356/95c942e3-322e-4879-b66a-f9125960644f

**Comment by Ricargame** [comment]
Los SB que no son abiertos desde ventana, se deben mantener abiertos y se debe de poder ejecutar múltiples veces el proceso, asegurándose de que los registros sean actualizados después de cada ejecución 

https://github.com/solop-develop/frontend-core/assets/78000356/9b3f525a-f773-4469-85f9-f3169f7e1c62

De igual manera luego de terminar la ejecución el proceso refresca automáticamente los registros del sb

**Comment by Ricargame** [comment]
cambios disponibles a partir de la versión https://github.com/solop-develop/frontend-core/releases/tag/4.0.7


https://github.com/solop-develop/frontend-core/assets/78000356/1e86d0a9-532e-4320-a5bb-b3d56be8bc50

**Comment by mgarciaQ76** [comment]
Esto quedó ok. Se realizan pruebas con resultado exitoso ok


https://github.com/user-attachments/assets/2995bc98-3011-403d-b290-63182af6bf90
