### ISSUE TITLE
Exportar Registros desde un SB genera archivo vacío

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#2196]
## Bug report

Se abre un SB y se aplica un filtro. se selecciona todos los registros y se intenta exportar en formato xlsx

Se genera un archivo en el equipo descargando ok pero al abrir el mismo no tiene líneas.

Si se realiza una exportación de registros desde una ventana funciona correctamente

#### Screenshot or Gif（截图或动态图）

https://github.com/solop-develop/frontend-core/assets/31936815/5a136caa-dee1-453c-8dae-7d69b3987e4e

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:

**Comment by mgarciaQ76** [comment]
Esto de exportar desde SB quedó ok. Se realizan pruebas con resultado exitoso ok


https://github.com/user-attachments/assets/96b12857-28f5-4df5-bcdd-ac0c49564421

[Navegador de Proyectos 2024-10-10 14_58_41.xlsx](https://github.com/user-attachments/files/17316830/Navegador.de.Proyectos.2024-10-10.14_58_41.xlsx)
