### ISSUE TITLE
Acercar Registro desde SB abre ventana sin aplicar filtro

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#2198]
## Bug report

Se acerca desde un registro y se abre la ventana correcta pero sin aplicar el filtro correctamente. Muestra todos los registros de la ventana.

#### Screenshot or Gif（截图或动态图）

ZK

![Acercar Registro desde SB (ZK)](https://github.com/solop-develop/frontend-core/assets/31936815/bc42379e-835c-4e72-815a-dffa96f45552)

VUE

![Acercar Registro desde SB (VUE)](https://github.com/solop-develop/frontend-core/assets/31936815/f0378b10-64d7-405f-a6db-89795c89aaf3)

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:

**Comment by Ricargame** [comment]
Cambios disponibles apartir de la versión: https://github.com/solop-develop/frontend-core/releases/tag/4.0.3

https://github.com/solop-develop/frontend-core/assets/78000356/053bcd35-e08a-496b-acc5-06421f9c9668
