### ISSUE TITLE
Proceso: Apertura > Elementos Recientes

### ISSUE THREAD

**Issue by elsiosanchez** [solop-develop/vue-1.0#22]
Requiere dar soporte para abrir los procesos desde los favoritos o elementos recientes como actualmente se realiza en la interfaz ZK

![zk-recien-item-menu](https://user-images.githubusercontent.com/45974454/166959174-0a00fe94-9cff-47e1-ae72-33201dfb8907.gif)

**Comment by elsiosanchez** [comment]
Actualmente en la interfaz de ADempiere-Vue se le dio soporte para abrir los procesos desde los favoritos o elementos recientes. También se cambió la visualización ya que ahora son unas tarjetas y el cual puedes realizar búsquedas rápidas dentro de ellas para mejor la experiencia del usuario a abrir un proceso desde los favoritos o Artículos recientes
![vue-recien-item-menu](https://user-images.githubusercontent.com/45974454/166959720-5cfbe1e9-3e60-48fd-9e2c-a2c97d2b4e67.gif)

**Comment by EdwinBetanc0urt** [comment]
Los casos de uso para esta funcionalidad se pueden ver aquí: https://solop-develop.github.io/frontend-core/es/guide/use-cases/process.html#items-recientes
