### ISSUE TITLE
Error al abrir SB

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#2207]
## Bug report

se intenta abrir un SB de Crear desde en ventana "DxP" y da el siguiente error.

![image](https://github.com/solop-develop/frontend-core/assets/31936815/3e11223f-bfcf-4aa8-9e39-297f75e76da0)

#### Steps to reproduce

1. [xxx]
2. [xxx]
3. [xxxx]

#### Screenshot or Gif（截图或动态图）

![Error al abrir SB en Seed VUE DEV](https://github.com/solop-develop/frontend-core/assets/31936815/66c74916-ab15-47e7-9d9d-069c4aacfc41)

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:

**Comment by EdwinBetanc0urt** [comment]
Esto esta operando a partir de la versión del `frontend` https://github.com/solop-develop/frontend-core/releases/tag/3.8.3 y de `dicionary rs` https://github.com/adempiere/dictionary_rs/releases/tag/1.2.1



![Image](https://github.com/solop-develop/frontend-core/assets/20288327/434fa1fe-8136-4aaf-a310-3e7bbe977039)
