### ISSUE TITLE
Filtro Mal en SB "Crear Desde" en DxP

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#2211]
## Bug report

Al intentar crear un DxP desde "Crear Desde" seleccionando una Orden de Compra... el filtro que aplica el SB está incorrecto, trae al parecer tdoas las líneas de ORdenes de compra pendientes y no está filtrando por el de la OC que se seleccionó

#### Screenshot or Gif（截图或动态图）

DxP 800008

![image](https://github.com/solop-develop/frontend-core/assets/31936815/601a1544-eac3-4859-9d2c-843431772c96)

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:

**Comment by EdwinBetanc0urt** [comment]
Cambios disponibles a partir de la versión https://github.com/solop-develop/adempiere-grpc-server/releases/tag/3.2.4 del backend
