### ISSUE TITLE
Proceso de Smart Browser siempre visible

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#2212]
## Feature request

Actualmente en los SB el proceso de accion sobre los registros seleccionados se encuentra ubicado arriba del todo y al hacer scroll este no se visualiza más, por lo qeu si se cuenta con muchos registros, luego de seleccionar lo qeu se quiere aplicar, se debe hacer nuevamente scroll para arriba para ejecutrar el proceso. Sería ideal que no se deba volver para arriba para ejecutar el proceso correspondiente.

![Proceso de los SB dejar fijo visible](https://github.com/solop-develop/frontend-core/assets/31936815/40552ed3-eeca-4536-8124-b528fc241e3f)

#### Describe the solution you'd like

Una solución que se me ocurre es dejar fijo (como vi que sucede en otras ventanas) esta sección superior para que pese a hacer scroll este se visualice siempre.

![Proceso fijo en SB](https://github.com/solop-develop/frontend-core/assets/31936815/c70efddf-6b70-4e26-9746-eebbf884a1cd)

También creo que sería útil que se vean los títulos de las columas 

![image](https://github.com/solop-develop/frontend-core/assets/31936815/35224512-c684-48ea-986f-907576c3f777)

**Comment by Ricargame** [comment]
Cambios disponibles apartir de la versión: https://github.com/solop-develop/frontend-core/releases/tag/3.8.5

https://github.com/solop-develop/frontend-core/assets/78000356/733689a7-9bc6-4b03-921b-5391bffede85

**Comment by niclopup** [comment]
agrego otros cambios para ver más registros
![image](https://github.com/solop-develop/frontend-core/assets/31936815/cf7e6202-2722-4e25-8097-7be88f968a05)

**Comment by Ricargame** [comment]
Cambios disponibles apartir de la versión: https://github.com/solop-develop/frontend-core/releases/tag/3.9.3


https://github.com/solop-develop/frontend-core/assets/78000356/9fedd8e4-0998-4d5d-9c7f-f3a5dde8d557

**Comment by niclopup** [comment]
> agrego otros cambios para ver más registros ![image](https://private-user-images.githubusercontent.com/31936815/330927060-cf7e6202-2722-4e25-8097-7be88f968a05.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3ODMwOTUsIm5iZiI6MTcxNzc4Mjc5NSwicGF0aCI6Ii8zMTkzNjgxNS8zMzA5MjcwNjAtY2Y3ZTYyMDItMjcyMi00ZTI1LTgwOTctN2JlODhmOTY4YTA1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA3VDE3NTMxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5NTFhY2I4ODY0MGI4M2IyMTQ0NWZlMmJkODUzMTAxMzAzODE4NGIxM2VhNDA4YjVlMTdhZjJlYjk3NmY0M2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kBECiE_7zd_iDwLysx6kPLu_-MFdllwbRTH-tNVDnM0)

Los cambios en general quedaron muy buenos del SB!
Ahora está mucho más ágil de visualizar y de operar con.

Solo hay un temita que me lo comentó un cliente, een este comentario se incluyó quitar el filtro de mostrar las columnas que se quieren visualizar para que si hay alguna que se quiera quitar, el usuario pueda fácilmente ocultarlas. Esto al parecer era muy útil para el cliente y ahora no hay manera de hacerlo.

![image](https://github.com/solop-develop/frontend-core/assets/31936815/269512d5-f220-4c5e-8d4b-a63475c785c2)



Se podría volver a activar para que se visualicen? Esto entiendo que sería código no?

**Comment by Ricargame** [comment]
Cambios disponibles apartir de la versión: https://github.com/solop-develop/frontend-core/releases/tag/4.0.3

https://github.com/solop-develop/frontend-core/assets/78000356/2927d9c8-39ff-4921-a610-6b6dc90b4a9f
