### ISSUE TITLE
Visualización Ventanas VUE desde diccionario

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#2215]
## Bug report

Se configura la Ventana "órdenes de Venta" para visualizarla desde VUE como se desea. 

La vista en Grilla se ve correcta según la definición de diccionario:

![image](https://github.com/solop-develop/frontend-core/assets/31936815/72b39a5c-c023-4aed-afb8-83f7f74d1a1c)

![image](https://github.com/solop-develop/frontend-core/assets/31936815/4fa7b52c-8320-4865-9712-838a5ea56771)

Ahora en mono registro el ordenamiento es el correcto pero por alguna razón, ha algunos campos que no se ven cuando entiendo que deberían

**No se ven cuando se deberían ver:**

* Campo: Usuario
* Campo: Región de Ventas

![image](https://github.com/solop-develop/frontend-core/assets/31936815/ce5b9672-2b16-4706-9a76-3cfe392b32ff)

![image](https://github.com/solop-develop/frontend-core/assets/31936815/6f7b6881-d6cb-48cf-a7a5-a6c1f828c285)

Otro campo que no se logra visualizar cuando entiendo si se debería ver dado que en este ejemplo se tiene definido un Tipo de Orden de Venta que tiene definido en el tipo de documento que es una "Orden estándar" (SO), pero no se visualiza el check de "Entrega Directa"

* Campo: Entrega Directa

![image](https://github.com/solop-develop/frontend-core/assets/31936815/4b759000-a8c7-49cf-b0a1-685e85c043eb)

![image](https://github.com/solop-develop/frontend-core/assets/31936815/ae365d3d-62e6-4932-90ca-e3c52b4114a2)

En resumen, entiendo que se debería de visualizar en la ventana como mono Registro todos los camposq ue se visualizan en la ventana en ZK. Correcto?

![image](https://github.com/solop-develop/frontend-core/assets/31936815/4ba369b5-d5a9-490f-81d9-6bf1e348b4bd)

Ahora veo que al quitar un campo el check de "Desplegado" no se visualiza más el campo en la pestñaa "Campo" en la definición de la ventana. No estaría quedando del todo claro como se manejarán esos campos que habíamos dicho que serían "Activo:SI" "Desplegado:NO" "Displayed in Grid: NO". Ya qye al marcarlo como NO Desplegado, no se vería más si sólo está "Activo".

![image](https://github.com/solop-develop/frontend-core/assets/31936815/af7a41ca-12f3-46a6-b0f1-af2871fd5979)

![image](https://github.com/solop-develop/frontend-core/assets/31936815/0a2aa27f-7abf-4ffa-90f2-ce7417f7a6e9)

Esto me hace dudar de como definimos que sean los campos que se puedan seleccionar pero q no estén visibles en mono registro por defeceto. 

Analizar y comentar

**Comment by EdwinBetanc0urt** [comment]
Esto fue corregido, estaba fallando un redireccionamiento de `Nginx` que apuntaba el diccionario al `Backend gRPC` en lugar de `OpenSearch`.

Cuando sea confirmado cerrar y cambiar el estatus de este issue.
