### ISSUE TITLE
Acercar a Lista de Precios ni Producto

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#2226]
## Bug report
Se intenta acercar desde el campo "lista de precios" en ventana de orden de trabajo (C_Project) pero no da la opción de Acercar. 

Esto sabemos por que sería?

#### Screenshot or Gif（截图或动态图）

![image](https://github.com/solop-develop/frontend-core/assets/31936815/8ac166df-2bf5-47a6-a5d2-9a81b3b06647)

Tampoco a Producto desde la línea de Proyecto 

![image](https://github.com/solop-develop/frontend-core/assets/31936815/5ac2f4af-a107-4a7a-94c8-3c84c5657f13)

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:

**Comment by niclopup** [comment]
parece que ningún campo acerca


https://github.com/solop-develop/frontend-core/assets/31936815/4c1e1608-2ba1-41ae-a342-a87e7b9034d5

**Comment by Ricargame** [comment]
Cambios disponibles apartir de la versión: https://github.com/solop-develop/frontend-core/releases/tag/3.9.8


https://github.com/solop-develop/frontend-core/assets/78000356/4300a7fd-cd6f-4f9e-8453-021b8f235995

**Comment by Ricargame** [comment]
Cambios disponibles apartir de la versión: https://github.com/solop-develop/frontend-core/releases/tag/3.9.8


https://github.com/solop-develop/frontend-core/assets/78000356/4300a7fd-cd6f-4f9e-8453-021b8f235995

**Comment by Ricargame** [comment]
Cambios disponibles apartir de la versión: https://github.com/solop-develop/frontend-core/releases/tag/4.0.3

https://github.com/solop-develop/frontend-core/assets/78000356/fefcb3af-8859-48dc-8011-1e18191c695e
