### ISSUE TITLE
Guardar Precio en ventana Producto queda cargando y no Guarda

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#2227]
## Bug report

Se crea un producto, se guarda el cabezal, 

Se baja a la pestaña de Precio pero no se ve el ID de producto padre. Se va a otra ventana y se vuelve a la ventana de producto y ahi s ise ve el ID del Producto. Se crea una nueva línea, se define precio y se intenta guardar un precio. 

No termina nunca de guardar

![image](https://github.com/solop-develop/frontend-core/assets/31936815/14044aa1-1739-49e0-9f88-237e67501346)

https://github.com/solop-develop/frontend-core/assets/31936815/68526927-7f9f-4d4a-87f4-5f900f061419

#### Steps to reproduce

1. [xxx]
2. [xxx]
3. [xxxx]

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:

**Comment by Ricargame** [comment]
Cambios disponibles apartir de la versión: https://github.com/solop-develop/frontend-core/releases/tag/3.9.3

https://github.com/solop-develop/frontend-core/assets/78000356/4ae78447-098d-48b4-a23a-80b532580da6
