### ISSUE TITLE
Logo en Reporte Print Format

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#2230]
## Bug report

No se está pudiendo ver el logo en un formato de impresión desde VUE
Impresión de DxC desde VUE

EJemplo reporte con logo Estándar Seed ADempiere desde ZK 

![image](https://github.com/solop-develop/frontend-core/assets/31936815/bf3c3d0d-f74d-44c7-ba9c-26983397e8ba)

Reporte desde VUE
![image](https://github.com/solop-develop/frontend-core/assets/31936815/ff06113e-2804-4cdc-aa28-7192e4a007c7)

esto es utilizando la iomagen con un link

![image](https://github.com/solop-develop/frontend-core/assets/31936815/0018867a-8713-49ab-a313-2a82f43b286b)

https://github.com/solop-develop/frontend-core/assets/31936815/82c155be-77d9-47c5-89c9-03fe16b1c7f0

#### Steps to reproduce

1. [xxx]
2. [xxx]
3. [xxxx]

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:

**Comment by EdwinBetanc0urt** [comment]
Entiendo que esto fue resuelto agregando en el logo la url de una imagen. Reabrir y devolver a `Por Revisión` en caso contrario.
