### ISSUE TITLE
Error al lanzar SB desde Botón en ventana

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#2241]
## Bug report
Se intenta lanzar el SB de "Crear desde Orden/Recepción" en ventana DxP y salta este error en la consola.

TypeError: Cannot read properties of undefined (reading 'uuid') at Object.start (http://spdev01.solopapp.com:24610/vue/static/js/chunk-7464d335.afb534d2.js:1:7975) at o.startProcess (http://spdev01.solopapp.com:24610/vue/static/js/chunk-7464d335.afb534d2.js:1:9640) at rt (http://spdev01.solopapp.com:24610/vue/static/js/chunk-libs.278e8467.js:70:11674) at o.n (http://spdev01.solopapp.com:24610/vue/static/js/chunk-libs.278e8467.js:70:13494) at rt (http://spdev01.solopapp.com:24610/vue/static/js/chunk-libs.278e8467.js:70:11674) at Dn.e.$emit (http://spdev01.solopapp.com:24610/vue/static/js/chunk-libs.278e8467.js:70:26570) at o.handleClick (http://spdev01.solopapp.com:24610/vue/static/js/chunk-elementUI.2689c4ff.js:9:187855) at rt (http://spdev01.solopapp.com:24610/vue/static/js/chunk-libs.278e8467.js:70:11674) at HTMLButtonElement.n (http://spdev01.solopapp.com:24610/vue/static/js/chunk-libs.278e8467.js:70:13494) at Ji.a._wrapper (http://spdev01.solopapp.com:24610/vue/static/js/chunk-libs.278e8467.js:70:52151)

Si se lanza desde los procesos abre correctamente. 

#### Screenshot or Gif（截图或动态图）
![Error al lanzar SB desde Botón en Ventana](https://github.com/solop-develop/frontend-core/assets/31936815/445b26df-22ee-415a-8f82-b1f776b303f7)

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:
- 
![image](https://github.com/solop-develop/frontend-core/assets/31936815/312f2fbd-48c7-40c2-a7b9-1919b4efdb85)

**Comment by EdwinBetanc0urt** [comment]
Se deben exportar las ventanas para corregir el problema

https://github.com/solop-develop/frontend-core/assets/20288327/b9c291d1-8dd2-4a8f-a5ab-837cd8d00123
