### ISSUE TITLE
Grilla de SB muestra pocos registros

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#2254]
## Bug report
La grilla del SB ahora que quedó fijo el cabezal, quedó con muy poca visibilidad de líneas. Sólo se pueden ver 9 línas de SB cuando deberíamos poder mostrar la mayor cantidad de línas posible. 

Esto entiendo q se debe a que la altura de la grilla de líneas está muy pequeña, no utilizando el alto total de la pantalla. 

#### Screenshot or Gif（截图或动态图）

![image](https://github.com/solop-develop/frontend-core/assets/31936815/8cd2e888-1240-4e1e-972d-8451dcf9d055)

![Lineas de SB con errores](https://github.com/solop-develop/frontend-core/assets/31936815/73abd5f4-1287-405f-961f-4e7a6cf909f1)

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:

![image](https://github.com/solop-develop/frontend-core/assets/31936815/24311025-7fa7-4080-bcb6-b6bb6095c2e7)

**Comment by Ricargame** [comment]
Cambios disponibles apartir de la versión: https://github.com/solop-develop/frontend-core/releases/tag/3.9.3


https://github.com/solop-develop/frontend-core/assets/78000356/577fea22-0036-4559-a38b-581aa5d0a71d
