### ISSUE TITLE
Buscador de Producto no filtra por Acceso a Organización del ROL

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#2259]
## Bug report
Si entro con un rol que no tiene acceso a organización "Agencia  S.A" no me debería mostrar nunca un producto de dicha Organización

![image](https://github.com/solop-develop/frontend-core/assets/31936815/e515c755-177c-44e9-a613-58ab8d0d77a3)

![image](https://github.com/solop-develop/frontend-core/assets/31936815/64d56e69-910a-4bcd-8e3c-3fefb0c61845)

![image](https://github.com/solop-develop/frontend-core/assets/31936815/6ea762f2-7736-4bf4-b1a6-749732b213e4)

#### Steps to reproduce

1. [xxx]
2. [xxx]
3. [xxxx]

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:

**Comment by EdwinBetanc0urt** [comment]
Cambios disponibles a partir del backend https://github.com/solop-develop/adempiere-grpc-server/releases/tag/3.4.4


https://github.com/user-attachments/assets/d6b3b1d4-078f-44b1-87eb-cba0e12b832a
