### ISSUE TITLE
Asiento Contable se visualiza sólo si Campo "Contabilizado" está visible

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#2261]
## Bug report

Actualmente sólo se puede visualizar un asiento en un documento si el campo "Contabilizado" está visibile. Esto sería bueno que no sea así sino que siempre muestre el asiento si el registro tiene un Fact_Acct creado o algo del estilo y no obligar a mostrar el botón de "Contabilizado" para poder mostrar o no un asiento.

En algunas ventanas para que queden más limpias los registros se procedió a ocultar el botón y eso hace que no se vean los asientos en la pestaña latareal cuando en realidad si existe

#### Screenshot or Gif（截图或动态图）

![Peek 2024-05-21 11-39](https://github.com/solop-develop/frontend-core/assets/31936815/957f65f8-3ae7-4233-822f-98e203759f8a)

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:

**Comment by EdwinBetanc0urt** [comment]
Correcto, actualmente se muestra si es un documento y si el campo `Contabilizado` (`Posted`) esta visible, lo otro es que se puede hacer es evaluar solo si el campo existe en la ventana.

En resumen las 2 alternativas posibles son:
- Evaluar si el campo `Posted` existe en la ventana, aunque este oculto. La opción mas rápida pero creo que la menos idónea.
- Crear un servicio que devuelva un booleano si el registro es un documento, esta procesado y si tiene un `Fact_Acct` asociado. La opción mas compleja pero la mas acertada quizás.

**Comment by EdwinBetanc0urt** [comment]
cambios disponibles a partir de la versión https://github.com/solop-develop/frontend-core/releases/tag/4.0.5

https://github.com/solop-develop/frontend-core/assets/78000356/3fdd839a-2412-4a2b-be14-1592ceb803b3
