### ISSUE TITLE
Menu no corresponde al definido en Rol

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#2274]
## Bug report

El menú que actualmente está cargando desde VUE no se corresponde al menú que tiene definido el Rol que se tiene seleccionado.

#### Steps to reproduce

Ver ejemplo en 24610 ingresando con Rol "Admin-Agencia" como desde ZK se ve un rol determinado y desde VUE se ve el Menú General. 

#### Screenshot or Gif（截图或动态图）

![image](https://github.com/solop-develop/frontend-core/assets/31936815/5df967be-852b-447f-bb77-a654f6a941e2)

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:

**Comment by EdwinBetanc0urt** [comment]
Esto esta corregido queda pendiente el ordenado de los nodos del menú.

![imagen](https://github.com/solop-develop/frontend-core/assets/20288327/a28a51ef-89ad-42c6-a673-175276cd159e)

**Comment by EdwinBetanc0urt** [comment]
En caso de error con el menú, eliminar los indices de `OpenSearch` con `OpenSearch Dashboards` que es la interfaz gráfica:
- Abrir el proceso de `Exportar Definición de Diccionario`, en caso de ser la primera vez y no se tenga nada en la ruta abrir el acceso directo `/export-dictionary` ejemolo `http://localhost:9572/#/export-dictionary`.
- Dejar marcado todos los check menos el del campo `Exportar Menú`.
- Abrir `OpenSearch Dasboards`.
- Ir a `Index Management`.
- Luego a `Indexes` escribir el ID de la compañía para filtrar.
- Seleccionar los indices del menú solamente.
- Ir a `Actions`.
- Seleccionar `Delete`.
- Validar que los indices a ser eliminados comiencen con `menu` y contengan luego del idioma el id de la compañía.
- Ir al proceso y ejecutar.


https://github.com/solop-develop/frontend-core/assets/20288327/57cd5624-386f-45c6-a4cd-c50322f4d70f

Se deben esperar algunos minutos, ya que transcurre un tiempo desde que adempiere envía los elementos a ser exportados (menu) a la cola de `kafka`, luego los servicios que están suscritos a esta cola (en este caso `dictionary_rs`) reciben una notificación para leer los datos de esa cola, procesarlos y empezar a escribir datos en `OpenSearch`.
