### ISSUE TITLE
Error al Abrir Ventana de DxP

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#2286]
## Bug report

Al intentar abrir la ventana de Documentos por Pagar salta el siguiente error. 

`Cannot read properties of undefined (reading 'sort')
`

#### Steps to reproduce
![ERror al abrir Ventana DxP](https://github.com/solop-develop/frontend-core/assets/31936815/365c98c0-7475-43d9-9fc1-6fc341849b2d)

#### Screenshot or Gif（截图或动态图）

![image](https://github.com/solop-develop/frontend-core/assets/31936815/91b277b1-2b7c-4756-94a2-86dd5e7a78bd)

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:  3.8.8
- http://spdev01.solopapp.com:24700/vue#/dashboard

**Comment by elsiosanchez** [comment]
Saludos @niclopup rebice en ambas instancia y no pude replicar el error



### **_Screenshot or Gif（截图或动态图）_**

https://github.com/solop-develop/frontend-core/assets/45974454/d2a1fc84-6f9e-42e6-9151-fccc2d08af3d


### **_Other relevant information_**

http://spdev01.solopapp.com:24610/vue#/1000001/1000002/1000010/206/window/183?recordId=1000453

http://spdev01.solopapp.com:24600/vue#/11/102/50006/206/window/183?recordId=1000001

**Comment by EdwinBetanc0urt** [comment]
Fue corregido con https://github.com/solop-develop/frontend-core/pull/2312
