### ISSUE TITLE
Selección de Pagos: Error en SB "Create From Invoice" 

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#2294]
## Bug report
No se logra hacer que funcione el SB de "Create from Invoice" desde la ventana Selcción de Pagos.

Primero da error al hacer click en el botón, pero si se lanza desde el proceso si abre el SB, pero da error q no puede terminar la consulta. 

![image](https://github.com/solop-develop/frontend-core/assets/31936815/62fecc60-9508-4a67-ab93-97a135485824)

#### Screenshot or Gif（截图或动态图）

![Error SB de Create from Invoice en  Selección de Pagos](https://github.com/solop-develop/frontend-core/assets/31936815/e8c3db1b-e2a8-4574-997c-72a2f3d909fa)

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:

**Comment by Ricargame** [comment]
Cambios disponibles apartir de la versión: https://github.com/solop-develop/frontend-core/releases/tag/3.9.8


https://github.com/solop-develop/frontend-core/assets/78000356/d2b9e9ce-1fec-4ad1-a822-b54c57b10020

**Comment by niclopup** [comment]
No se logra validar esto en SEED SPDEV:24600

No llega a buscar registros y además queda trancado todo el sistema.


![SB Create from Invoice ERROR](https://github.com/solop-develop/frontend-core/assets/31936815/bebcbfa9-66fd-447c-be1a-8c9b51d86242)

**Comment by Ricargame** [comment]
Cambios disponibles apartir de la versión: https://github.com/solop-develop/frontend-core/releases/tag/4.2.0

https://github.com/user-attachments/assets/fd62b288-dc8f-424f-9eee-e6d00619bdd2

**Comment by nsarlabos** [comment]
@EdwinBetanc0urt según lo que hablamos reabro este isssue, por error al ejecutar el SB desde http://spdev01.solopapp.com:24610/vue

El error es al usar el botón "Seleccionar DxP" y "Seleccionar DxP con Control"

![error](https://github.com/user-attachments/assets/a54908cb-78d6-4ad5-a402-e663862e04d8)

**Comment by EdwinBetanc0urt** [comment]
Cambios disponibles apartir de la versión: https://github.com/solop-develop/frontend-core/releases/tag/4.2.1

https://github.com/user-attachments/assets/0324d6cd-d81f-4fdb-a7dc-1695ef5f7424
