### ISSUE TITLE
Checks selección SB no se mueven con registros al hacer scroll

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#2295]
## Bug report

al Hacer scroll en un sb los checks de selección no acompañan por lo que sólo se puede seleccionar los que aparecen inicialmente cuando deberían acompañar al scroll

#### Steps to reproduce

![image](https://github.com/solop-develop/frontend-core/assets/31936815/9697c6b6-21de-4bc9-a054-c845cac54ed0)

#### Screenshot or Gif（截图或动态图）

![Checks selección SB no se mueven con registros al hacer scroll](https://github.com/solop-develop/frontend-core/assets/31936815/b881d0b0-13d9-4790-9aa0-0ca272c48e33)

#### Expected behavior

Los checks de selección de cada registro deben acompañar al registro en cuestión al hacer scroll

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:
- 
![image](https://github.com/solop-develop/frontend-core/assets/31936815/24d4f997-1d0c-42d8-af31-410d9ef4b18b)

**Comment by Ricargame** [comment]
Cambios disponibles apartir de la versión: https://github.com/solop-develop/frontend-core/releases/tag/3.9.8


https://github.com/solop-develop/frontend-core/assets/78000356/3074673a-67c2-4bec-af76-43a5e52bcb75
