### ISSUE TITLE
[Bug Report] Columnas Duplicadas en tabla de Smart Browser

### ISSUE THREAD

**Issue by elsiosanchez** [solop-develop/vue-1.0#2299]
## Bug report

Error en la tabla de los Smart Browser cuando la columnas son Tipo Rango se duplican en la tabla
#### Screenshot or Gif（截图或动态图）
![image](https://github.com/solop-develop/frontend-core/assets/45974454/7ee7c951-f73b-48e3-bc99-465e47260918)

**Comment by EdwinBetanc0urt** [comment]
Esto se valido desde el front, sin embargo también tenia marcado como `Rango` pero no se veía el check al estar oculto ya que no era criterio de búsqueda

**Comment by Ricargame** [comment]
Cambios disponibles apartir de la versión: https://github.com/solop-develop/frontend-core/releases/tag/3.9.8


![image](https://github.com/solop-develop/frontend-core/assets/78000356/d3f0b5a2-f86a-4ea5-95c1-60cf39d26db6)
