### ISSUE TITLE
Proceso: Apertura > Asociado a Ventana

### ISSUE THREAD

**Issue by elsiosanchez** [solop-develop/vue-1.0#23]
Requiere dar soporte para abrir o ejecutar los procesos desde la ventanas como actualmente se realiza en la interfaz ZK

![zk-Re Abrir Vista de Proceso desde la Ventana](https://user-images.githubusercontent.com/45974454/166960233-dd787cde-a82d-4969-b57b-73c25b381c18.gif)

**Comment by EdwinBetanc0urt** [comment]
Los casos de uso para esta funcionalidad se pueden ver aquí: 
https://solop-develop.github.io/frontend-core/es/guide/use-cases/process.html#proceso-relacionado-a-la-ventana

**Comment by niclopup** [comment]
el proceso se abre correctamente desde la ventana pero no logré correr ningun proceso desde la ventana. Siempre dice Class Not Found.
Entiendo que es otra acción por lo que dejo esta como Entregada y agrego comentario en una Tarea al correr desde ventana.

**Comment by EdwinBetanc0urt** [comment]
Saludos, por favor especifica que proceso presenta error al ejecutar de clase no encontrada en el issue https://github.com/solop-develop/frontend-core/issues/77 para agregar los paquetes que puedan tener esos procesos en la definición de dependencias del gradle.
