### ISSUE TITLE
Nuevo Motor de Reportes (Fase 1)

### ISSUE THREAD

**Issue by Ricargame** [solop-develop/vue-1.0#2305]
## Bug report

- [x] #2343
- [x] #2396
- [x] #2424
- [x] #2425

#### Additional context
fixed: https://github.com/adempiere/adempiere-report-engine-service

**Comment by yamelsenih** [comment]
## Observaciones

- [x] El Patrón de correo cuando se selecciona no reemplaza todo el texto
- [x] Cuando se envía por correo no genera un URL de descarga usando el servicio de `S3` como en las demás opciones. El proceso debería ser:
  - Hace una petición para exportar el reporte al formato seleccionado `XLSX`
  - Con la respuesta solicita un URL de Descarga al serrcicio `S3`
  - Reemplaza el texto predeterminado `[Click to go to the Link](www.123892138.com)` por nada (`""`)
  - Con la respuesta del servicio `S3` agrega al final del texto de envío justo antes de hacer la petición de envío de notificación el URL generado por el servicio de `S3` enmascarado en markdown, algo como esto (`[Click to go to the Link](<url-de-respuesta-s3>)`)
- [x] Al llamar el servicio para exportar no se le está enviando como parte del request los datos actuales del reporte (`filters`, `print_format_id`, `view_id`, `page_size` y `page_token` en caso de ser la pagina actual)
- [x] Al intentar enviar da error `Error
Errors in the recipient list: Recipient does not have a valid Contact ID (0) Account Name () Recipient does not have a valid Contact ID (0) Account Name ()`
- [x] Las opciones del panel superior deben estar solo lectura cuando se está cargando el reporte
- [x] Cuando se selecciona la opción compartir da error, el servicio y todo lo ejecuta bien pero no agrega el link al portapapeles y da error `Error exporting report: b.replace is not a function.`
- [x] Cuando se selecciona la opción enviar hace el envío pero nunca notifica al usuario que la notificación se agregó a la cola de notificaciones
- [x] Cuando se selecciona la opción enviar hace el envío pero no sustituye el url temporal por el URL compartido que genera el S3
![Envio_Malo](https://github.com/user-attachments/assets/b1ea7305-3740-4ebf-af50-0bc01f3841ee)
- [x] La opción **Preview** sólo debe aparecer al presionar la opción **Enviar**, está apareciendo en todos lados
![image](https://github.com/user-attachments/assets/7c3178c3-4e96-43bd-b55c-67b22b01ebf0)
- [x] No está mostrando los totales al hacer click derecho sobre una fila sumaria
- [x] Al cambiar una página no muestra la opción para selecciona una página o por lo menos darle a la siguiente página
- [x] Al seleccionar la plantilla no sobrescribe todo sino que agrega el texto
![Plantilla](https://github.com/user-attachments/assets/9217271d-928d-40db-92ed-aab401ed0b1d)
- [x] A pesar de que existe un error muestra un mensaje como que todo está bien
![image](https://github.com/user-attachments/assets/2a873a33-7886-43f2-8683-2d4aca19093a)
- [x] Muestra dos campos que no debería
![image](https://github.com/user-attachments/assets/b478ba79-6586-45d7-a40b-8c49311f714e)
- [x] Quitar el botón **Generate (PDF)** 
![image](https://github.com/user-attachments/assets/2f921981-3638-4177-9edf-4336475fe521)
- [x] Al recargar toda la app se queda cargando eternamente
- [x] Al hacer click derecho sobre algún **Resumen** no está mostrando el popover de **Totales**
- [x] Cuando se presiona la opción Resumir debería colapsar todos los del tipo `is_parent` que estén en el último nivel solamente
- [x] Al cambiar parámetros no muestra el cargando
![image](https://github.com/user-attachments/assets/382f9458-e46e-4378-8805-de38ed71ebac)
- [x] Agregar un botón para **Refrescar** entre la **Vista del Reporte** y **Ver Resumen** ![image](https://github.com/user-attachments/assets/06c8bf21-2abf-4460-9825-a2652e501197)
- [x] Cuando el `display_type` es 10 (String) se debe mostrar el `display_value` y si no tiene entonces mostrar el `value`: Por eso no muestra el Numero de Documento 
![image](https://github.com/user-attachments/assets/c942df6b-4146-4aaa-9613-32a37fed102b)
- [x] Al ejecutar el reporte no le manda los parámetros correctamente y no muestra nada la primera vez, para que muestre hay que cambiar el formato
https://github.com/user-attachments/assets/06ab084c-3bc5-485a-a73e-8f644a9e2e1a
- [x] Cuando se Cambia el Formato de Impresión, la Página o la vista no se le está enviando los parámetros originales
![image](https://github.com/user-attachments/assets/e62b831f-6c5e-462a-9581-a39120b6b2cd)
- [x] Cuando se cambia el Formato de Impresión no está llamando al servicio `views` sino que vuelve a ejecutar el servicio `reports`
![image](https://github.com/user-attachments/assets/e66959d9-4cf5-4ba8-a09e-3eb067e34f0d)
- [x] Los títulos no están alineados verticalmente
![image](https://github.com/user-attachments/assets/20204c37-574a-4b40-af85-ed44089e83d6)
- [x] El Exportar / Compartir
  - [x] No predetermina el formato XLSX
![image](https://github.com/user-attachments/assets/42b1fa75-d617-4570-8d16-f0b4422d32ae)
  - [x] No tienen padding en el compartir
![image](https://github.com/user-attachments/assets/7fed0fb8-5b6b-44f1-b51f-2dc5fa5afe76)
![image](https://github.com/user-attachments/assets/c4254ee3-40c6-4dd6-97f0-24871a52c654)
  - [x] Está ejecutando un request cada vez que se selecciona la duración del link (http://spdev01.solopapp.com:24610/api/resources/download-url/Detalles%20del%20Pago%20(Agrupado%20Yamel)?seconds=86400)
![image](https://github.com/user-attachments/assets/84dd7823-bbab-4945-bcfb-8dbe49ad793e)
- [x] Las columnas que tienen el atributo `is_group_column` se deben mostrar fijas

## Flujo de Proceso del Compartir
 ### Cuando es Descarga
   - Se ejecuta el servicio: report-engine/export/<process_id>/xlsx
   - Si el servicio se ejecuta con éxito se toma el `file_name` que devuelve el servicio
   - Con el `file_name` se debe llamar el servicio de S3 `/api/resources/download-url/<file_name>?seconds=<esto es lo que previamente seleccionó el usuario>`
   - Si la respuesta del S3 es correcta se toma el URL de descarga y se manda a descargar desde el navegador directamente

### Cuando es Enviar
   - Se debe validar que se tenga seleccionado el `Tipo de Notificación` y al menos un usuario o un nombre de cuenta
   - Se debe mostrar lo siguiente:
     - Campo `Asunto`: es texto y por defecto debe mostrar el nombre del formato de impresión actual
     - Campo `Texto`: es el texto que se le enviará, debe ser un campo igual al de `Notas` 
   - Si todo está Ok
   - Se ejecuta el servicio: report-engine/export/<process_id>/xlsx
   - Si el servicio se ejecuta con éxito se toma el `file_name` que devuelve el servicio
   - Se debe ejecutar el servicio de send-notification con los siguienes datos:
     - Title: Aquí se agrega lo que dice el asunto
     - Body: Aquí se agrega lo que está en el campo Texto
     - Recipients: Es una lista donde se envía el id del usuario o el nombre de la cuenta o las cuentas agregadas
     - Attachments: Aqui se agrega lo que devuelve el servicio de exportar reporte `file_name`
     - Si todo está Ok se notifica al usuario cuando el servicio de notificación responda

### Cuando es Copiar Link
   - Se ejecuta el servicio: report-engine/export/<process_id>/xlsx
   - Si el servicio se ejecuta con éxito se toma el `file_name` que devuelve el servicio
   - Con el `file_name` se debe llamar el servicio de S3 `/api/resources/download-url/<file_name>?seconds=<esto es lo que previamente seleccionó el usuario>`
   - Si la respuesta del S3 es correcta se toma el URL de descarga y se debe copiar al portapapeles
   - Por último se debe mostrar un mensaje en la parte inferior derecha que permita saber que ya se tiene el link de descarga y que se le puede dar click para abrir

### Común para Todos

- Se debe validar que todo esté cargado y sino entonces el botón ok debe estar deshabilitado
- Siempre se debe ejecutar el servicio `report-engine/export/<process_id>/xlsx` después del Ok
- Si alguno de los servicios da error se debe reportar al usuario en forma de tool tips y se debe volver a mostrar el diálogo de `Compartir / Descargar`
