### ISSUE TITLE
Contraseña de Usuarios se ve desde ventana

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#2308]
## Bug report

Si se entra a la ventana de usuario se puede ver las contraseñas de los usuarios. Entiendo que debería tener un formato similar a como tiene en ZK

![image](https://github.com/solop-develop/frontend-core/assets/31936815/a27020e8-3c81-42b7-a22d-91bf6874f2e8)

#### Screenshot or Gif（截图或动态图）

![image](https://github.com/solop-develop/frontend-core/assets/31936815/40875280-a0a9-4ddc-8a75-c3a87618527c)

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:

**Comment by Ricargame** [comment]
Buenos dias señor @niclopup  probé en ambas instancias y no logre replicar el error, podria volver a verificar porfavor 


https://github.com/solop-develop/frontend-core/assets/78000356/6ceffb62-99a2-42db-8d1f-18a2ef411926

**Comment by Ricargame** [comment]
Cambios disponibles apartir de la versión: https://github.com/solop-develop/frontend-core/releases/tag/3.9.8

![image](https://github.com/solop-develop/frontend-core/assets/78000356/6ce0fa25-1f30-4087-a710-c3a0178313c6)

**Comment by niclopup** [comment]
ok con la ventana en mono registro y con el registro seleccionado en ventana en modo Grilla. 

pero no se ven bien las PSW de los usuarios no seleccionados

Si  bien no está mostrando la psw, no muestra como debería sino que muestra el campo con caracteres raros. debe mostrar todos los registros como se ve el primer registro

![Image](https://github.com/user-attachments/assets/93fdc8a6-aff4-42b1-a461-a951f40198a0)

**Comment by Ricargame** [comment]
Cambios disponibles a partir de la versión del frontend: https://github.com/solop-develop/frontend-core/releases/tag/4.4.025

![Image](https://github.com/user-attachments/assets/805b6558-2df5-4064-b958-e809d184be20)
