### ISSUE TITLE
Copiar Registro no funciona desde ventana

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#2309]
## Bug report
Copiar Registro no funciona desde ventana

#### Screenshot or Gif（截图或动态图）

![Copiar registro no funciona desde ventana](https://github.com/solop-develop/frontend-core/assets/31936815/da4eec03-cb82-4ceb-8a11-7c6f81f484b0)

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:

**Comment by Ricargame** [comment]
Cambios disponibles apartir de la versión: https://github.com/solop-develop/frontend-core/releases/tag/3.9.8


https://github.com/solop-develop/frontend-core/assets/78000356/18ae6fd3-f89e-4839-ac9b-8c9d87a724f2
