### ISSUE TITLE
Ventanas: Fecha en modo Grilla muestra siempre Fecha+Hora

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#2326]
## Bug report
Pese a que un campo esté definido como sólo "FECHA" en modo grilla siempre está mostrando tabmién la HORA

![image](https://github.com/solop-develop/frontend-core/assets/31936815/b6532ab7-56ca-4257-8c12-016a7ad3514a)

En Modo Mono Registro está ok

![image](https://github.com/solop-develop/frontend-core/assets/31936815/69540ba2-6f15-4fe0-96af-7c42777fa932)

En System está definido como DATE el campo

![image](https://github.com/solop-develop/frontend-core/assets/31936815/50970c4b-4905-4f83-9ee5-a5af4082e95b)

#### Steps to reproduce

1. Abrir Ventana "Proyectos"
2. Modo grilla ver campo "Contract Date"
3. Modo Mono ver campo "Contract Date" 

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version: 3.9.9

**Comment by Ricargame** [comment]
Cambios disponibles apartir de la versión: https://github.com/solop-develop/frontend-core/releases/tag/4.0.3

![image](https://github.com/solop-develop/frontend-core/assets/78000356/313ea3c4-9ad6-4da8-a418-5fd686b478a6)
