### ISSUE TITLE
Agregar soporte para ver la versión de `Dictionary RS`

### ISSUE THREAD

**Issue by Ricargame** [solop-develop/vue-1.0#2336]
#### Steps to reproduce

1. [xxx]
2. [xxx]
3. [xxxx]

#### Screenshot or Gif（截图或动态图）
![image](https://github.com/solop-develop/frontend-core/assets/78000356/83adc605-08e0-4573-84cb-be29b7f2b2e2)

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:

**Comment by EdwinBetanc0urt** [comment]
cambios disponibles a partir de la versión https://github.com/solop-develop/frontend-core/releases/tag/4.0.5

![image](https://github.com/solop-develop/frontend-core/assets/78000356/1f3b6bb7-71eb-41d0-97cc-4f216622c71b)
