### ISSUE TITLE
Agregar soporte para ver la versión del `S3 Gateway RS`.

### ISSUE THREAD

**Issue by Ricargame** [solop-develop/vue-1.0#2337]
#### Steps to reproduce

1. [xxx]
2. [xxx]
3. [xxxx]

#### Screenshot or Gif（截图或动态图）
![image](https://github.com/solop-develop/frontend-core/assets/78000356/470ac7eb-0bba-4fcc-b882-44e926c2cf36)

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:

**Comment by EdwinBetanc0urt** [comment]
cambios disponibles a partir de la versión https://github.com/solop-develop/frontend-core/releases/tag/4.0.5

![image](https://github.com/solop-develop/frontend-core/assets/78000356/528ed70f-d3d9-44b8-a5b3-6aec1efb4ec7)
