### ISSUE TITLE
Punto de venta corta la ventana y no se ven totales

### ISSUE THREAD

**Issue by mgarciaQ76** [solop-develop/vue-1.0#2349]
## Bug report

Verificando punto de venta en custom, se detecta que corta la ventana y no permite visualizar totales (no habilita scroll). La unica forma de poder ver la ventana completa es achicar el zoom.
Independientemente de la resolución de pantalla, este corte de ventana me ocurre solo en Punto de venta (y el problema es que no habilite scroll)

#### Steps to reproduce

1. [Ingresar a punto de venta]
2. [Intentar ver totales]

#### Screenshot or Gif（截图或动态图）

![punto de venta1](https://github.com/solop-develop/frontend-core/assets/139590879/26ac0bf0-df61-4a4d-aa7e-da219025e23b)

Resolución pantalla

![resolucion pantalla1](https://github.com/solop-develop/frontend-core/assets/139590879/e9302fce-31d1-4b29-a690-98530038fec3)

#### Expected behavior

Poder visualizar la ventana completa

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:
http://spdev01.solopapp.com:24610/vue
Rol distribuidora admin
Org: sucursal Este

**Comment by EdwinBetanc0urt** [comment]
cambios disponibles a partir de la versión https://github.com/solop-develop/frontend-core/releases/tag/4.0.5

![image](https://github.com/solop-develop/frontend-core/assets/78000356/434a7fb3-2b57-48fb-ac23-5b8d7f40430c)

**Comment by mgarciaQ76** [comment]
En este caso probando me ocurre que para ver completa la ventana tengo que bajar zoom a 80

![punto de venta zoom 80](https://github.com/user-attachments/assets/d99bba18-eea3-4cc3-9957-3d5d616a1032)


Si dejo el zoom al 100 me sigue cortando los totales. Continúo con la misma resolución de pantalla que indica el issue

![punto de venta zoom 100](https://github.com/user-attachments/assets/7b3d1583-2524-4a65-bdef-59d7d589ad71)

reactivo y devuelvo de acuerdo a lo conversado con Edwin en hilo discord  https://discord.com/channels/954056226579308624/1293590468214395022

**Comment by Ricargame** [comment]
Cambios disponibles a partir de la versión del frontend: https://github.com/solop-develop/frontend-core/releases/tag/4.4.017


https://github.com/user-attachments/assets/818f6818-2271-4881-92c5-52fd7aa78f72
