### ISSUE TITLE
Buscador de ventana/proceso/reporte deja trabado el sistema

### ISSUE THREAD

**Issue by mgarciaQ76** [solop-develop/vue-1.0#2350]
## Bug report

Al intentar realizar búsqueda de determinadas opciones queda colgado el sistema y se debe refrescar el navegador (no deja seguir operando).
Por ejemplo al buscar reporte de proyectos

#### Steps to reproduce

1. [ingreso al sistema]
2. [utilizar buscador para ubicar ventana o proceso]

#### Screenshot or Gif（截图或动态图）

https://github.com/solop-develop/frontend-core/assets/139590879/99e49d9b-8b3d-46aa-afac-ea9966b74a7e

#### Expected behavior

Realizar la búsqueda deseada y poder seguir operando

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:

http://cac.solopapp.com/vue
Rol admin
Org cac

**Comment by niclopup** [comment]
@EdwinBetanc0urt esto me sigue pasando. han podido analizarlo ? 

![image](https://github.com/user-attachments/assets/0492ac9b-9a65-452f-942b-164d96be3052)

**Comment by mgarciaQ76** [comment]
Esto continúa replicandose en instancia 24700. Buscando casi cualquier opción se cuelga y se debe refrescar navegador para poder seguir operando


https://github.com/user-attachments/assets/2bbebb9b-4eae-4d5d-b14a-6c55351b5593

**Comment by EdwinBetanc0urt** [comment]
Hola @mgarciaQ76 las instancias de pruebas son http://spdev02.solopapp.com:24814/vue que tiene un backend sin parches y http://spdev02.solopapp.com:24810/vue que tiene el backend con parches `SP-UY`, en caso de que esa instancia falle verificar la versión para que sea actualizada.
