### ISSUE TITLE
al exportar project browser muestra agente comercial con nombre y otros con número ID

### ISSUE THREAD

**Issue by mgarciaQ76** [solop-develop/vue-1.0#2351]
## Bug report

Se detectó que al realizar búsqueda de project browser y exportar a excel se ven registros con el nombre del agente comercial y en otros casos el ID (solo quieren ver el nombre).
Adjunto excel de la prueba donde puede confirmarse que un mismo agente comercial en la primera línea lo muestra con nombre, y en la segunda con ID (Nelson Paguada)

#### Steps to reproduce

1. [realizar búsqueda en el project browser]
2. [exportar a excel]

#### Screenshot or Gif（截图或动态图）

[Excel exportado del Project Browser Agentes salen con codigo (1).pptx](https://github.com/user-attachments/files/15838436/Excel.exportado.del.Project.Browser.Agentes.salen.con.codigo.1.pptx)

[Navegador de Proyectos 2024-06-15 9_49_51.xlsx](https://github.com/user-attachments/files/15838439/Navegador.de.Proyectos.2024-06-15.9_49_51.xlsx)

#### Expected behavior

Visualizar el nombre de agente comercial en todos los registros

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:
http://cac.solopapp.com/vue
rol admin
org cac

**Comment by EdwinBetanc0urt** [comment]
cambios disponibles a partir de la versión del frontend https://github.com/solop-develop/frontend-core/releases/tag/4.0.5

**Comment by mgarciaQ76** [comment]
Esto quedó pronto. Se realizan pruebas con resultado exitoso ok


https://github.com/user-attachments/assets/1cf5b7c3-e83e-4e02-96af-369eb7da1b52

[Navegador de Proyectos 2024-10-10 14_58_41.xlsx](https://github.com/user-attachments/files/17316909/Navegador.de.Proyectos.2024-10-10.14_58_41.xlsx)
