### ISSUE TITLE
Recontabilizar documentos no lista asientos contables correctamente 

### ISSUE THREAD

**Issue by Ricargame** [solop-develop/vue-1.0#2354]
#### Steps to reproduce

1. [Abrir documentos por cobrar]
2. [Buscar un registro con estado de documento completo]
3. [Abrir informacion contable]
4. [Precionar el boton de re-contabilizar]

#### Screenshot or Gif（截图或动态图）

https://github.com/solop-develop/frontend-core/assets/78000356/82e5193d-f9fa-4f6c-a5ab-a7957d2bc68b

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:

**Comment by EdwinBetanc0urt** [comment]
Al parecer luego de re-contabilizar no envía la tabla e identificador del registro actual en la petición de listar asientos contables.

**Comment by EdwinBetanc0urt** [comment]
cambios disponibles a partir de la versión https://github.com/solop-develop/frontend-core/releases/tag/4.0.5


https://github.com/solop-develop/frontend-core/assets/78000356/6d2d5bc5-cf21-46e9-affe-14f1861f917d
