### ISSUE TITLE
segunda busqueda de project browser no genera cambios al ejecutar

### ISSUE THREAD

**Issue by mgarciaQ76** [solop-develop/vue-1.0#2357]
## Bug report

Realizo una busqueda por agente comercial en project browser, ejecuto cambio y queda grabado. Segunda busqueda de otro agente comercial, tildo y al ejecutar no graba el cambio (a partir de segunda busqueda ya no ejecuta correctamente)

#### Steps to reproduce

1. [busqueda por agente comercial y ejecutar cambio]
2. [segunda busqueda y ejecutar cambio]

#### Screenshot or Gif（截图或动态图）

https://github.com/solop-develop/frontend-core/assets/139590879/fb0a50a8-71a2-467e-8ffe-6be2d2986736

Segunda prueba, video completo:

https://github.com/solop-develop/frontend-core/assets/139590879/71ee4ef1-4a96-43ca-80a1-7a404cb03aae

#### Expected behavior

Poder realizar múltiples busquedas y ejecuciones del browser

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:
http://spdev01.solopapp.com:24700/vue
rol admin
org cac

**Comment by Ricargame** [comment]
cambios disponibles a partir de la versión https://github.com/solop-develop/frontend-core/releases/tag/4.0.7

https://github.com/solop-develop/frontend-core/assets/78000356/ec47b0a0-11cd-4e1e-b3ad-b342ff55f2ad
