### ISSUE TITLE
[Bug Report]Refresca un registro actual

### ISSUE THREAD

**Issue by elsiosanchez** [solop-develop/vue-1.0#236]
## Bug report
Cuando se refresca un registro actual en lugar de refrescar los datos solamente de ese registro refresca la tabla y se ubica en el primer registro. Esto simplemente debe hacer un getEntity y refrescar el registro actual

#### Screenshot or Gif

https://user-images.githubusercontent.com/20288327/180034947-d15e1d7b-681f-40ac-a0ca-baab28a8ec7c.mp4

#### Other relevant information
- Your OS: Debian 9
- Web Browser: Chrome
- Node.js version: v 14.0.0

**Comment by niclopup** [comment]
ok
