### ISSUE TITLE
Al exportar al excel el Project Browser baja algunos agentes con el codigo y no el nombre

### ISSUE THREAD

**Issue by mgarciaQ76** [solop-develop/vue-1.0#2365]
## Bug report
Se detectó que al seleccionar desde el project browser registros en algunos casos muestra el agente comercial con el nombre y otros con el número.

#### Steps to reproduce

1. [ingresar a project browser]
2. [seleccionar registros]
3. [exportar a excel]

#### Screenshot or Gif（截图或动态图）

prueba en 610;

https://github.com/solop-develop/frontend-core/assets/139590879/ad2d28a1-24e7-4327-b93b-3000acb510c3

[Navegador de Proyectos 2024-06-20 16_25_10 exportacion de 610.xlsx](https://github.com/user-attachments/files/15905377/Navegador.de.Proyectos.2024-06-20.16_25_10.exportacion.de.610.xlsx)

#### Expected behavior

visualizar siempre el nombre de agente comercial

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:  4.0.4
rol admin
org cac

**Comment by EdwinBetanc0urt** [comment]
cambios disponibles a partir de la versión del frontend https://github.com/solop-develop/frontend-core/releases/tag/4.0.5
