### ISSUE TITLE
Error en smart browser por campo definido tipo BUSQUEDA

### ISSUE THREAD

**Issue by nsarlabos** [solop-develop/vue-1.0#2366]
## Bug report

En el smart browser "Reabastecimiento desde Línea de Proyecto" se presenta un error, por el cual no logra realizar la búsqueda de registros, relacionado al parecer con  el campo "PD_C_BPartner_ID"

![columna SB](https://github.com/solop-develop/frontend-core/assets/29130825/0032a063-f629-4a4b-b9be-62695ded74e9)

![error](https://github.com/solop-develop/frontend-core/assets/29130825/2ae7dad0-016e-4131-a8bf-6f3f8ffa32c4)

Este browser funciona bien en ZK

![SB ok](https://github.com/solop-develop/frontend-core/assets/29130825/edcd5647-f0a5-4619-8f09-8bf22f3f7891)

Aquí se muestra el error desde VUE

![Error SB](https://github.com/solop-develop/frontend-core/assets/29130825/8ae5f785-fad5-4cc5-842e-69e882c7375b)

#### Additional context
http://spdev01.solopapp.com:24610/vue
http://spdev01.solopapp.com:24612/webui

**Comment by EdwinBetanc0urt** [comment]
Esta solución requiere desarrollar un servicio para obtener datos necesarios para desplegar el buscador correctamente (ya que cambio con el OpenSearch). Sin embargo para solucionar en producción se puede cambiar el tipo de campo a `Tabla Directa` o `Tabla`, y tener la versión del frontend https://github.com/solop-develop/frontend-core/releases/tag/4.0.5

**Comment by Ricargame** [comment]
Cambios disponibles apartir de la versión: https://github.com/solop-develop/frontend-core/releases/tag/4.1.1

https://github.com/solop-develop/frontend-core/assets/78000356/dcf9db24-8009-47c0-afcd-922abc14d75e
