### ISSUE TITLE
Exportar Registros desde VUE limitado en la paginación

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#2371]
## Bug report

Si se desea exportar TODOS los registros que devuelve un SmartBrowser actualmente no es posible ya que sólo puede exportar a todos los seleccionados y ellos sólo son máximo 100. 

Si tenes más registros ,no podrás exportarlo desde un SB

Inicialmente recuerdo que se había contado con otro proceso que era Exportar Registros (No los seleccionados) que entiendo que con eso se solucionaría este problema. 

Creo qeu acá yo solicité que se quite cuando en realidad está mal ya que nos hace perder esta opción. 

Podemos agregarlo?

https://github.com/solop-develop/frontend-core/issues/295#issuecomment-1291224669

#### Steps to reproduce

1. [xxx]
2. [xxx]
3. [xxxx]

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:

**Comment by Ricargame** [comment]
cambios disponibles a partir de la versión https://github.com/solop-develop/frontend-core/releases/tag/4.0.7


https://github.com/solop-develop/frontend-core/assets/78000356/db9a33c5-6113-4ca3-bdea-a1e2e70d56fd

[Procesar Órdenes en Lote 2024-06-27 15_10_29.xlsx](https://github.com/user-attachments/files/15994171/Procesar.Ordenes.en.Lote.2024-06-27.15_10_29.xlsx)

**Comment by mgarciaQ76** [comment]
[Procesar Órdenes en Lote 2024-10-10 13_25_54.xls](https://github.com/user-attachments/files/17311602/Procesar.Ordenes.en.Lote.2024-10-10.13_25_54.xls)
Esto quedó pronto, pruebas con resultado exitoso ok


https://github.com/user-attachments/assets/c807aa2f-3952-4e9a-b997-262aac367825
