### ISSUE TITLE
Error en smart browser por Null Pointer Exception

### ISSUE THREAD

**Issue by nsarlabos** [solop-develop/vue-1.0#2374]
## Bug report

En el smart browser "Agregar Productos a Fase de Proyecto", el cual se ejecuta desde la ventana de "Proyectos", se presenta error de null pointer al procesar.

![sb productos fase](https://github.com/solop-develop/frontend-core/assets/29130825/5fd85074-a26f-4c7f-aa4d-1f07cabd6c45)

![error](https://github.com/solop-develop/frontend-core/assets/29130825/a88f269f-76e0-4ef1-8315-1fb95c402dd6)

#### Additional context
Código del SB: UY_SB_ProductSelection
Código del Proceso: UY_P_CreatePhaseLineFromProduct

Instancias:

http://spdev01.solopapp.com:24610/vue
http://spdev01.solopapp.com:24612/webui

**Comment by EdwinBetanc0urt** [comment]
Revisando con @nsarlabos había un detalle en una de las clases del proceso `Agregar Productos a Fase de Proyecto`, ya que se establecía en la selección como `Integer`, al leerla en la clase del proceso se recibía como `BigDecimal` ocasionando el `Null Pointer Exception`.

**Comment by rcapecce** [comment]
Hola @EdwinBetanc0urt 
Cuando editas un SB, a @nsarlabos no le trae un dato as BigDecimal y le da NPE
Esto es por lo que le manda el front, no lo está enviando correctamente, hay dos casos a validar en el ejemplo de @nsarlabos .

1) El dato le mandas 0 al QtyEntered: llega como BigDecimal, y revienta dentro del proceso por una lógica controlada del NS.

2) Digitas una cantidad en la linea seleccionada del SB en el campo QtyEntered: ahí se envía como Integer
Acá se puede ver como lo formatea como integer https://github.com/solop-develop/adempiere-grpc-server/blob/9d11bdb122de896fed6650fc526676d08bd800e7/src/main/java/org/spin/grpc/service/BusinessData.java#L304
Y acá se puede ver como al obtenerlo como Integer, no logra castearlo a BigDecimal porque no es del tipo de la clase (es Integer) y retorna Null https://github.com/adempiere/adempiere/blob/fc1110ff0bfe08c0f4bc711cbec9298597a5c685/base/src/org/compiere/process/ProcessInfo.java#L1326
esto es lo que le ocurre al proceso.

En esta imagen se puede ver como formatea el QtyEntered sin una estructura decimal
![image](https://github.com/solop-develop/frontend-core/assets/14218144/81bc4e65-2791-4a15-bcfb-1e9df39e25b4)

En este otro gif se puede ver como si lo envía correctamente la estructura del dato como devimal
![image](https://github.com/solop-develop/frontend-core/assets/14218144/808706c6-42c0-4927-bc82-13d10ae3799e)

**Comment by EdwinBetanc0urt** [comment]
Corregido disponible a partir de la versión del frontend https://github.com/solop-develop/frontend-core/releases/4.1.1


https://github.com/solop-develop/frontend-core/assets/20288327/69a33dbb-db22-4144-80d3-14ca05f34571
