### ISSUE TITLE
Criterio de ordenamiento en SB no se cumple al aplicar Filtros

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#2379]
## Bug report

Estoy encontrando un tema con el criterio del ordenamiento de los Registros en los SB para VUE.

La lógica que defino y es apliocada correctamente en ZK, no me está respetando en VUE cuando se aplican varioos filtros.
este es el ejemplo q pude replicar en Producción (spprod01:24700 VUE y 24702 zk)

![image](https://github.com/solop-develop/frontend-core/assets/31936815/a05a0943-8c42-47f4-8167-1126a5aa0af6)

Son estos dos los campos que se editan al modificar el "Sort Order"

![image](https://github.com/solop-develop/frontend-core/assets/31936815/f0978a7e-ea1f-464c-9944-d63096bad0dd)

#### Steps to reproduce

1. [xxx]
2. [xxx]
3. [xxxx]

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:

**Comment by EdwinBetanc0urt** [comment]
Cambios disponibles a partir del backend https://github.com/solop-develop/adempiere-grpc-server/releases/tag/3.5.9

![imagen](https://github.com/user-attachments/assets/df89dc30-2d08-4ba0-9402-da12b89a38d8)
