### ISSUE TITLE
Cambios de parámetros en Reporte no funcionan

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#2380]
## Bug report

La sección lateral de los reportes para cambiar un parámetro no funciona.

https://github.com/solop-develop/frontend-core/assets/31936815/8b3284bc-893c-4014-ab03-a9ae82a8cb24

#### Steps to reproduce

1. [xxx]
2. [xxx]
3. [xxxx]

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:
![image](https://github.com/solop-develop/frontend-core/assets/31936815/bf9034dc-000d-4644-91a0-20e31f6c39be)

**Comment by Ricargame** [comment]
Cambios disponibles a partir de la versión: https://github.com/solop-develop/frontend-core/releases/tag/4.4.006

https://github.com/user-attachments/assets/07e39bba-3f15-444e-ab41-a81b3e9ce0a1
