### ISSUE TITLE
Cambiar formato de impresión desde Reporte no funciona

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#2381]
## Bug report
Cambiar formato de impresión desde Reporte no funciona

https://github.com/solop-develop/frontend-core/assets/31936815/02675380-34ab-4d5e-be77-7387302b2e28

#### Steps to reproduce

1. [xxx]
2. [xxx]
3. [xxxx]

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:

**Comment by Ricargame** [comment]
Cambios disponibles a partir de la versión https://github.com/solop-develop/frontend-core/releases/tag/4.3.2

https://github.com/user-attachments/assets/706a443b-a069-4971-be87-d92a30763529

**Comment by Ricargame** [comment]
Cambios disponibles a partir de la versión: https://github.com/solop-develop/frontend-core/releases/tag/4.4.006

https://github.com/user-attachments/assets/503c2f60-7a81-4c82-9a87-f3b7dfeb58c8
