### ISSUE TITLE
Acción de proceso en SB no funciona al cambiar ordenamiento de registros

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#2382]
## Bug report
Si se aplica un cambio del ordenamiento de los registros utilizando el ordenamiento haciendo click en cualquier cabezal de columna del SB, cualquiera acción que se intente generar posteriormente no será aplicada por el proceso del SB.

Se hace la validación en una llamada con Edwin donde se ve como respondía la consola  mover el ordenamiento de los registros:

![image](https://github.com/solop-develop/frontend-core/assets/31936815/3a22afa6-89ca-4e30-a4a5-0d1e57944618)

esta acción no aplicó ningún cambio en el proyecto que se seleccionó y modificó un campo.

Luego se replicó lo mismo pero sin modificar el ordenamiento

![image](https://github.com/solop-develop/frontend-core/assets/31936815/f094c905-ee26-4702-a9f2-6aec6fa80b86)

esta acción no aplicó ningún cambio en el proyecto que se seleccionó y modificó un campo.

SB: Navegador de Proyecto

Tener en cuenta que esto siempre falló en ZK 

El problema existe en cualquier SB.

#### Steps to reproduce

1. [xxx]
2. [xxx]
3. [xxxx]

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:

![image](https://github.com/solop-develop/frontend-core/assets/31936815/c386fd73-1b63-468d-a761-382e1ec85e51)

**Comment by Ricargame** [comment]
cambios disponibles a partir de la versión https://github.com/solop-develop/frontend-core/releases/tag/4.0.7

https://github.com/solop-develop/frontend-core/assets/78000356/4dfde619-50d8-4afd-b069-4d1cb879fb0e
