### ISSUE TITLE
No se muestran documentos relacionados en pestañas

### ISSUE THREAD

**Issue by nsarlabos** [solop-develop/vue-1.0#2389]
## Bug report
Se observa que al definir nuevas relaciones de documentos, las mismas sólo se muestran a nivel del cabezal del documento, y no en las pestañas inferiores.

Ejemplo: se crearon tipos de relación para poder navegar desde el Proyecto, Fase y Línea hasta los documentos de "Salidas de Proyecto" relacionados. Esto funciona bien desde ZK, pudiendo navegar tanto desde el cabezal de proyecto, como desde las fases y líneas de fase. Sin embargo, desde VUE sólo funciona a nivel del cabezal de proyecto, sin mostrar los docs relacionados en Fase y Línea.

#### Screenshot or Gif（截图或动态图）

Funcionamiento correcto en ZK

![Relaciones ZK](https://github.com/solop-develop/frontend-core/assets/29130825/d38ff3a8-9f73-4aec-bb6e-428b9a1823ed)

No funciona en VUE

![Relaciones VUE](https://github.com/solop-develop/frontend-core/assets/29130825/6f252253-6a0c-4372-af38-92e82acc87a5)

**Comment by Ricargame** [comment]
Cambios disponibles apartir de la versión: https://github.com/solop-develop/frontend-core/releases/tag/4.1.1

https://github.com/solop-develop/frontend-core/assets/78000356/48b6db53-cde5-4a7d-99fb-c1d9ed95c206
