### ISSUE TITLE
[Bug Report] Error en la tabla

### ISSUE THREAD

**Issue by elsiosanchez** [solop-develop/vue-1.0#239]
## Bug report
Al hacer click sobre una fila de la tabla no se está marcando como seleccionado el registro y si se cambia a mono vista aparece otro.

#### Screenshot or Gif（截图或动态图）

https://user-images.githubusercontent.com/45974454/178280794-6341c52a-dcaa-4a51-b0d0-bdae4639f210.mp4

**Comment by niclopup** [comment]
ok
