### ISSUE TITLE
[Bug Report] Error Campo tipo Fecha Tiempo 

### ISSUE THREAD

**Issue by elsiosanchez** [solop-develop/vue-1.0#2399]
Error en el formato tipo fecha y tiempo en modo panel
#### Screenshot or Gif（截图或动态图）

![image](https://github.com/solop-develop/frontend-core/assets/45974454/676eaf71-9db8-4a4e-93a3-20ff50c53896)

![image](https://github.com/solop-develop/frontend-core/assets/45974454/538bdc30-2f38-4b10-9751-9845a88dffa1)

**Comment by Ricargame** [comment]
Cambios disponibles apartir de la versión: https://github.com/solop-develop/frontend-core/releases/tag/4.1.1

![imagen](https://github.com/solop-develop/frontend-core/assets/78000356/d88c693d-476d-4611-a2b3-394b1c99fa1a)
