### ISSUE TITLE
Proceso: Apertura > Menú de Relaciones

### ISSUE THREAD

**Issue by elsiosanchez** [solop-develop/vue-1.0#24]
Se agrego soporte para la interfaz de ADempiere-Vue para que desde el menú de acciones en la opcion de relaciones pueda dirigirse a los procesos relacionado con esa vista de forma rápida y sencilla

![vue-relaciones](https://user-images.githubusercontent.com/45974454/166961011-8c16d410-21ba-43f3-b242-310b7051e134.gif)

**Comment by EdwinBetanc0urt** [comment]
Los casos de uso para esta funcionalidad se pueden ver aquí: 
https://solop-develop.github.io/frontend-core/es/guide/use-cases/process.html#relaciones

**Comment by EdwinBetanc0urt** [comment]
Este componente queda depreciado al ser redundante con la funcionalidad y sobrecargar la vista al usuario.


https://user-images.githubusercontent.com/20288327/173905609-73d36efb-b7c6-4f04-8230-b4192d738022.mp4
