### ISSUE TITLE
[Bug Report] Error maximizado de la tabla

### ISSUE THREAD

**Issue by elsiosanchez** [solop-develop/vue-1.0#240]
## Bug report
La configuración de maximizado no la mantiene cuando te pasas entre pestañas, ahora incluso debes presionar dos veces maximizar y adicional a esto el scroll se va al final y es molesto

#### Screenshot or Gif（截图或动态图）
https://user-images.githubusercontent.com/45974454/178281020-0a4027bd-10c7-4623-a2f2-04eec8b18700.mp4

**Comment by niclopup** [comment]
En varias ocasiones funcionó ok, pero se logra romper si en vez de hacer doble click para pasar de Grilla a Mono, utilizar el botón de "Mono Registro"

https://user-images.githubusercontent.com/31936815/180059253-ed14977d-e334-419a-937d-d9b0cd3c340e.mp4

**Comment by elsiosanchez** [comment]
https://user-images.githubusercontent.com/45974454/180079103-9a654172-1a7e-4913-8ec5-44e5b2c56efd.mp4

**Comment by niclopup** [comment]
Se mantiene la opción de maximizar, por lo que doy por entregado el Issue

Ahora hay otro problema que creare un nuevo issue, cuando se vuelve al modo grilla, se para la grilla arriba del todo y si el registro era de los de abajo no aparece en la grilla por lo que hay que scrolear, que también es molesto.
