### ISSUE TITLE
Problema con fechas en smart browsers

### ISSUE THREAD

**Issue by nsarlabos** [solop-develop/vue-1.0#2407]
## Bug report
Vemos que al querer ingresar una fecha la misma se borra, y por ende no se actualiza el registro.

#### Screenshot or Gif（截图或动态图）

![fechas](https://github.com/solop-develop/frontend-core/assets/29130825/91b9ca16-9969-4025-ab7f-e2c6be8664c7)

#### Additional context
http://spdev01.solopapp.com:24700/vue

**Comment by EdwinBetanc0urt** [comment]
Disponible a partir de la version del frontend https://github.com/solop-develop/frontend-core/releases/tag/4.1.2
