### ISSUE TITLE
Localización no carga del SDN en Pestaña nivel 1

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#2409]
## Bug report

No se logra seleccionar un SDN Entrega Directa desde una Fase de Proyecto ya que no muestra bien la localización del SDN seleccionado y al ser un dato obligatorio no permite guardar la fase. 

![image](https://github.com/solop-develop/frontend-core/assets/31936815/68456b4e-b0c6-4715-821f-ea78cc6d9399)

![image](https://github.com/solop-develop/frontend-core/assets/31936815/5e3c8a52-481a-4a53-935e-53ec0f190b25)

#### Steps to reproduce

1. [xxx]
2. [xxx]
3. [xxxx]

#### Screenshot or Gif（截图或动态图）

![Pestaña nivel 1 no carga dirección SDN Entrega Directa](https://github.com/solop-develop/frontend-core/assets/31936815/1b3cfe6e-5d7c-426b-a2fd-d48e4f721243)

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:

**Comment by EdwinBetanc0urt** [comment]
Disponible a partir de la version del frontend https://github.com/solop-develop/frontend-core/releases/tag/4.1.2
