### ISSUE TITLE
Se permite borrar registro en tabla sin check de "Registros Eliminables"

### ISSUE THREAD

**Issue by nsarlabos** [solop-develop/vue-1.0#2415]
## Bug report
Desde VUE, por ejemplo en ventana de "Orden de Trabajo" o "Proyectos",  se permite borrar un registro a pesar de que la tabla C_Project tiene desmarcado el check de "Registros Eliminables".

Luego de desmcarcar el check en la tabla se hizo la exportación de la ventana, pero al parecer VUE no toma este cambio.

#### Screenshot or GIF

![ejemplo proyecto borrar](https://github.com/solop-develop/frontend-core/assets/29130825/29fd93f7-1429-4dd1-8183-086ee5bc76dc)

#### Additional context
http://spdev01.solopapp.com:24700/vue
http://spdev01.solopapp.com:24702/webui

**Comment by nsarlabos** [comment]
@EdwinBetanc0urt esto al parecer se solucionó luego de liberar espacio en disco, ahora veo que el botón ELIMINAR ya no aparece en la ventana de orden de trabajo en VUE.

**Comment by EdwinBetanc0urt** [comment]
Se entiende que esta solucionado por lo que cierro este tema
