### ISSUE TITLE
Descargar Registros Seleccionados desde Ventana no considera campo

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#2416]
## Bug report

Tenemos un tema raro q no me había percatado antes.
Descargamos a excel registros seleccionados en una ventana y hay un campo (Agente comercial) que no lo agrega en el Excel y no le encuentro explicación.

[Orden de Trabajo 2024-06-21 9_5_9.xlsx](https://github.com/user-attachments/files/16128964/Orden.de.Trabajo.2024-06-21.9_5_9.xlsx)

#### Steps to reproduce

1. [xxx]
2. [xxx]
3. [xxxx]

#### Screenshot or Gif（截图或动态图）

https://github.com/solop-develop/frontend-core/assets/31936815/68097b43-0d93-435b-8d09-57d27c204847

![image](https://github.com/solop-develop/frontend-core/assets/31936815/de102cde-da55-4d42-8402-d82e5c1d57f1)

![image](https://github.com/solop-develop/frontend-core/assets/31936815/69bbc30e-8d00-47b3-9b1a-77d99d9d4423)

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:

**Comment by Ricargame** [comment]
Cambios disponibles apartir de la versión: https://github.com/solop-develop/frontend-core/releases/tag/4.2.0

https://github.com/user-attachments/assets/e145f2d7-1c4a-4a22-a62f-281ff9f1cdae
