### ISSUE TITLE
Precio en linea de OC / OV no se guarda si el producto tiene precio 0 en Lista de Precio

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#2419]
## Bug report

estoy teniendo un problema con la definición de precios en una orden de compra. Intento definir manualmente el precio en una líunea y bno está guardando correctamente. Parecería que sólo funciona si tiene unprecio de lista definido pero si el precio de lista de Compra es 0$ entonces no te permite definirlo manualmente.

![Precio en Linea de OC no Guarda](https://github.com/solop-develop/frontend-core/assets/31936815/6cc0a2ed-db90-4587-b1b0-936e372e3ba2)

por otro lado, lo intento replicar en el SEED no me permite seleccionar un producto al crear la línea,, aparece siempre sólo lectura.

![PO en Seed no selecciona producto](https://github.com/solop-develop/frontend-core/assets/31936815/c70e6cd6-b088-4253-b6c2-a362f702bb6c)

#### Steps to reproduce

1. [xxx]
2. [xxx]
3. [xxxx]

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version: 4.1.2.

**Comment by Ricargame** [comment]
Cambios disponibles apartir de la versión: https://github.com/solop-develop/frontend-core/releases/tag/4.1.4

https://github.com/solop-develop/frontend-core/assets/78000356/31b8e831-78e4-4b17-9ff9-8505dddeb6ea

**Comment by EdwinBetanc0urt** [comment]
Adjunto el resultado

https://github.com/user-attachments/assets/e34877b1-9dbb-4a7c-86d2-d27ef60fd914

**Comment by Ricargame** [comment]
Cambios disponibles apartir de la versión: https://github.com/solop-develop/frontend-core/releases/tag/4.2.0

https://github.com/user-attachments/assets/a317f716-f607-4752-a9a3-e89e921238bb
