### ISSUE TITLE
Nuevo Motor de Reportes > Paginación de datos

### ISSUE THREAD

**Issue by EdwinBetanc0urt** [solop-develop/vue-1.0#2424]
- [x] Cuando el servicio de reportes retorna los datos se está tomando la cantidad de registros y se coloca en el list de nímero de registros por página 
![image_2024-07-30_01-13-14](https://github.com/user-attachments/assets/1801ee06-386b-445b-a55b-ce29e6f00758)
- [x] Cuando haces la primera consulta es ok, pero si seleccionas exportar y luego seleccionas la opción "Todo el Reporte" y luego refrescas el reporte le manda como tamaño de página tooooodo el tamaño del reporte
https://github.com/user-attachments/assets/dc88d97e-c426-45aa-81a9-796304156c52

**Comment by Ricargame** [comment]
Cambios disponibles a partir de la versión https://github.com/solop-develop/frontend-core/releases/tag/report-0.3.6

https://github.com/user-attachments/assets/4796fbf6-9b52-4320-88fc-e9ce44043e5e
