### ISSUE TITLE
Paginación por defecto a 50 registros

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#2426]
## Feature request

Se desea definir en cada Compañía o como se pueda el tamaño de la paginación por defecto en las ventanas y SB.

Sugerir diferentes opciones, si en el usuario o en la compañía pero se debe poder dejar fijo para la empresa.

**Comment by EdwinBetanc0urt** [comment]
Cambios disponibles a partir de la versión del frontend `4.4.022`.

https://github.com/user-attachments/assets/b6452a9d-e50d-49c7-a7d2-ce12013c695f
