### ISSUE TITLE
Busqueda avanzada Proyecto por Estado de Proyecto no aparecen valores

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#2428]
## Bug report

Se intenta hacer una búsqueda avanzada desde la ventana "Orden de Trabajo" (lo mismo pasa con ventana Proyectos)

ZK
![image](https://github.com/solop-develop/frontend-core/assets/31936815/5753990c-84a8-4eb6-aceb-c916f13fa0df)

VUE
![image](https://github.com/solop-develop/frontend-core/assets/31936815/c0f4fd15-2772-47dc-83bd-5653afb0083b)

#### Steps to reproduce

1. [xxx]
2. [xxx]
3. [xxxx]

#### Screenshot or Gif（截图或动态图）

https://github.com/solop-develop/frontend-core/assets/31936815/3be7233b-6ae8-4c87-9f66-33be8bda20bf

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:  4.1.3

Instancia 
http://spdev01.solopapp.com:24700/vue#/profile/index
http://spdev01.solopapp.com:24702/webui/index.zul

**Comment by Ricargame** [comment]
La busqueda avanzada del estatus del proyecto tiene una validacion que depende del tipo del proyecto, por ende hay registros que al no tener el tipo de proyecto, no logra traer ningun dato 

![image](https://github.com/solop-develop/frontend-core/assets/78000356/c770a39e-d606-4d4a-9ed2-cfc5454e2fd3)

cabe destacar que en zk ocurre el mismo problema
![image](https://github.com/solop-develop/frontend-core/assets/78000356/c734f660-9b1c-432c-855f-b4fa455f2b96)

**Comment by niclopup** [comment]
@Ricargame es correcto lo que decis, pero en el ejemplo que les presenté si me traía datos en ZK y no en VUE. 

Más allá de esto, es verdadq hay veces que no se muestran los datos para hacer la consulta avanzada en ZK tampoco.

Ahora el tema es cómo podríamos hacer para aplicar alguna otra validación más simple para que SI se muestre ok los estados en un cliente.

Considerar que el cliente sólo tiene 1 Tipo de Proyecto definido con sólo 1 categoría de estados activa.

Si se muestran todos los estados activos ya es suficiente.

**Comment by niclopup** [comment]
si bien en algun caso no se veían todos los estados.


https://github.com/user-attachments/assets/f364cb19-2224-4b90-80f8-bda6eb4c8b72


luego active y genere una búsqueda y si mostró todos. 

![image](https://github.com/user-attachments/assets/d0c0c7c6-67d7-4691-bff2-0eb9cc385101)
