### ISSUE TITLE
Filtos en Forma "Todas las Solicitudes"

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#2436]
## Feature request

Se desea agregar diferntes filtros sobre la forma de "Todas las Solicitudes" #2130

Se desea poder filtrar por:

- Socio del Negocio
- Proyecto
- Contrato
- Organización
- Grupo de Solicitudes
- Categoría de Solicitudes
- Usuario

Creo que una buena opción de hacer variable esto es agregar los filtos según se tengan activadas las diferentes Dimensiones en el Esquema contable. 

- [x] #2855 
- [x] #2856

**Comment by EdwinBetanc0urt** [comment]
Tambien se podrian agregar fechas.

**Comment by elsiosanchez** [comment]
https://github.com/solop-develop/frontend-core/pull/2761

**Comment by elsiosanchez** [comment]
Cambios disponibles a partir de la versión del frontend: https://github.com/solop-develop/frontend-core/releases/tag/4.4.017



https://github.com/user-attachments/assets/f4a802a8-630e-4c77-9746-1aa175f68792

**Comment by niclopup** [comment]
parece que no está funcionando el filtro de ningún campo

Ej. Socio del Negocio : Zara

![image](https://github.com/user-attachments/assets/2dab0616-e599-44a5-bb49-36baaf891ada)

se muestra como existen varias solicitudes creadas para ese SDN

![image](https://github.com/user-attachments/assets/627919e4-b297-4c85-b641-4d0bc67ee1dd)


Viendo el video de la prueba, veo que si funcion ahi.. pero me llama la atención las pocas solicitudes que se ven en formato Kanban y las que se ven con la lista. La lista inciial es lo que realmente existe. Por qie se están viendo tantas menos?


![image](https://github.com/user-attachments/assets/9bc5ad05-14d7-4997-9cf6-7636f965c024)


Se desea aplicar un filtro en esta vista

![image](https://github.com/user-attachments/assets/c256b9e9-afdd-4fcb-af98-e2d47b6058e9)

**Comment by elsiosanchez** [comment]
Solventado en el siguiente PR https://github.com/solop-develop/frontend-core/pull/2843

**Comment by elsiosanchez** [comment]
https://github.com/solop-develop/adempiere-grpc-server/pull/907
