### ISSUE TITLE
[Bug Report] Campos Numéricos tipo rango no se visualizan.

### ISSUE THREAD

**Issue by EdwinBetanc0urt** [solop-develop/vue-1.0#2443]
#### Steps to reproduce

1. Abrir reporte de `Saldos Abiertos`.

El campo de  `Días de Vencimiento` debe tener otro llamado `Días de Vencimiento Hasta` con el valor por defecto hasta.

#### Screenshot or Gif（截图或动态图）

https://github.com/user-attachments/assets/e4d3bc03-d02f-4f24-a2ca-7a4307edf7a1

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:

**Comment by Ricargame** [comment]
Cambios disponibles apartir de la versión: https://github.com/solop-develop/frontend-core/releases/tag/4.2.0

https://github.com/user-attachments/assets/bc086cc3-4263-4eb1-88c1-16d664e3c5eb
