### ISSUE TITLE
Ventana: Manejo > Panel > Crear Registro

### ISSUE THREAD

**Issue by EdwinBetanc0urt** [solop-develop/vue-1.0#245]
Permitir crear nuevos registros en el modo solo registro o modo panel.

#### Pasos para reproducir:

1. Abrir cualquier ventana.
2. Pulsar el botón `Nuevo`.
3. Llenar los campos obligatorios.
4. Pulsar el botón `Guardar`.

#### Capturas de pantalla

https://user-images.githubusercontent.com/20288327/178315062-0ef501a3-4dea-4a7d-b8ae-a64b2e7b267b.mp4

**Comment by EdwinBetanc0urt** [comment]
En una ventana con múltiples pestañas, al crear un registro padre debe refrescar los registros en las pestañas hijas.



https://user-images.githubusercontent.com/20288327/178351090-21d44aa7-78f0-4971-8334-bebffabbfa11.mp4

**Comment by niclopup** [comment]
Encontré varios errores o dificultades verificando este punto.

No logró crear un SDN y definirle bien la Localización desde la ventana SDN.


https://user-images.githubusercontent.com/31936815/180052795-a1244d9c-abd7-4add-a1b6-6ff32742ce5d.mp4

Luego de crear el Registro del SDN (C_BPartner) intento navegar a su pestñaa de Localización y también es dificil. mostrando las pestañas de "SDN Padre" se logra verificar más claro el problema. Muestra un registro que no tiene SDN, tal vez fue un registro que intenté generar anteriormente en otro SDN pero quedó sin SDN definido tal vez.

https://user-images.githubusercontent.com/31936815/180053032-ae35a281-da9d-4fac-9569-fc640077b06a.mp4

Por otro lado, se intenta navegar entre registros de la pestaña padre y sus pestañas hijas y se encuentra problemas de actualizar el registro correspondiente.

Al parecer, la única manera segura de que actualice el registro es seleccionando el registro de la pestaña padre con DOBLE CLICK de manera que se pueda ver como Mono Registro. De esta manera si se tiene visible el campo de "SDN" en la tabla de la pestaña hija se ve claramente si el registro está correcto o no.

https://user-images.githubusercontent.com/31936815/180053959-5be0b819-b028-4566-928b-59cb63e83814.mp4

Pregunta, no sería mejor tal vez no contar con las 2 grillas en simultáneo? es decir que las pestañas hijas sólo se muestren si se está viendo un registro como Mono Registro?

**Comment by EdwinBetanc0urt** [comment]
Saludos, el crear registros en socio de negocio esta corregido, para la grillas en mono registro crear un issue distinto, ya que no es especifico de la creación de registros.
