### ISSUE TITLE
Contrato se quita de Proyecto al cambiar dato en registro

### ISSUE THREAD

**Issue by nsarlabos** [solop-develop/vue-1.0#2451]
## Bug report
Ocurre que a veces, cuando se cambia un dato en el proyecto, en ventana de "Orden de Trabajo", se quita el contrato que estaba asignado en el registro anteriormente (esto no pasa en ZK).

#### Steps to reproduce

1. Crear o editar proyecto existente
2. Cambiar un dato del proyecto, cualquiera menos el contrato

#### Screenshot or Gif

https://github.com/user-attachments/assets/b9381829-0e0f-4222-9f84-9a58a60b9554

#### Additional context
http://spdev01.solopapp.com:24700/vue

**Comment by Ricargame** [comment]
Buenas tardes señor @nsarlabos realice las mismas pruebas pero no logre replicar el error 


https://github.com/user-attachments/assets/ddb4081f-eb2f-43db-81d4-5c2ca82f3029
