### ISSUE TITLE
Error al generar reporte invoice transactions (doc)

### ISSUE THREAD

**Issue by mgarciaQ76** [solop-develop/vue-1.0#2456]
## Bug report

Se está generando un error en producción. Es al intentar crear reporte de invoice transactions (doc).
Genera error de llave duplicada
Solo se produce en VUE, en zk se genera ok
parámetros:

sales transactions SI
date invoice 01/07/2024 al 17/07/2024
account date 01/07/2024 al 17/07/2024  (este filtro es el que genera el error, si no se setea sale ok)
document status completed

#### Steps to reproduce

1. ingresar al reporte]
2. [setear parámetros]
3. [ejecutar]

#### Screenshot or Gif（截图或动态图）

![error reporte](https://github.com/user-attachments/assets/c46291f5-f108-433a-ba5b-ddf505d5fc81)

https://github.com/user-attachments/assets/07b82c05-80a2-411d-a782-402adb916f3e

#### Expected behavior

Permitir generar reporte

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:
front end  4.0.8
rol admin
instancia cac

**Comment by EdwinBetanc0urt** [comment]
Esto aplica la misma corrección del comentario https://github.com/solop-develop/frontend-core/issues/2579#issuecomment-2298910461

**Comment by mgarciaQ76** [comment]
En instancia 24700 estoy replicando el error que se dio en producción.

Parámetros: account date 01/7/2024 al 17/07/2024
                    date invoiced 01/7/2024 al 17/07/2024
                    sales transactions SI
                    Document status Complete


https://github.com/user-attachments/assets/91b1dbaa-4c8a-4d8b-bfa5-4cfb989f8045

**Comment by EdwinBetanc0urt** [comment]
Esto se corrige con un parche agregado en la libreria de `adempiere-solop`.
