### ISSUE TITLE
[Bug Report] No se abren los flujos de trabajo desde el menú.

### ISSUE THREAD

**Issue by EdwinBetanc0urt** [solop-develop/vue-1.0#2459]
#### Steps to reproduce

1. Inciar sesión con compañia.
2. Expandir `Relación con Socios del Negocio` > `Reglas de Socios del Negocio`.
3. Abrir `Configuración de Socios del Negocio`.

#### Screenshot or Gif（截图或动态图）

https://github.com/user-attachments/assets/15d44987-3d05-464e-aea4-abe19b4eff9e

#### Expected behavior
Se espera que se abra el diagrama de nodos del flujo de trabajo

#### Additional context
Al parecer esta haciendo la petición a un viejo endpoint.

**Comment by Ricargame** [comment]
Cambios disponibles apartir de la versión: https://github.com/solop-develop/frontend-core/releases/tag/4.2.0

https://github.com/user-attachments/assets/1aa58c9f-2a7c-4f97-a464-b7f43dc91b39
