### ISSUE TITLE
Ventana: Manejo > Panel > Editar Registro

### ISSUE THREAD

**Issue by EdwinBetanc0urt** [solop-develop/vue-1.0#247]
Cuando existen cambios en un registro debe aparecer el botón `Guardar`, y al seleccionar dicho botón y recibir respuesta exitosa del servidor tanto en modo panel como en modo tabla deben sincronizarse los valores.

Los cambios son tomados luego de establecer el nuevo valor, y pulsar la tecla enter o al perder el foco del campo.

Si se cambio un valor y manualmente se vuelve a establecer el valor anterior, no sera tomado como campo cambiado, es decir en el campo se tiene el valor A, y se cambio al valor B, entonces aparecerá el botón de guardar y descartar, pero sin darle al botón de guardar se vuelve a establecer el valor A, no sera tomado como cambios en el campo y desaparecen los campos deshacer y guardar.

#### Pasos para reproducir

1. Abrir cualquier ventana.
2. Seleccionar un registro de la misma compañía.
3. Colocar en modo mono registro.
4. Cambiar algún valor.
5. Pulsar el botón guardar.
6. Mostrar modo multi registro y verificar que el valor cambiado en el campo también cambio en la celda.

#### Capturas de pantalla.

https://user-images.githubusercontent.com/20288327/178325406-a86127db-8993-4883-b649-ce6a31e0b970.mp4

**Comment by niclopup** [comment]
si se quiere deshacer un cambio antes de guardar y se apreta el botón "Deshacer" se vuelve el registro como estaba antes = OK

Ahora la siguiente frase no está sucediendo tal como se explica:

> Si se cambio un valor y manualmente se vuelve a establecer el valor anterior, no sera tomado como campo cambiado, es decir en el campo se tiene el valor A, y se cambio al valor B, entonces aparecerá el botón de guardar y descartar, pero sin darle al botón de guardar se vuelve a establecer el valor A, no sera tomado como cambios en el campo y desaparecen los campos deshacer y guardar.

https://user-images.githubusercontent.com/31936815/180061122-3a96a4bf-deaa-4778-8bdc-3744f7e04b6a.mp4


@EdwinBetanc0urt comentar si debería suceder así o está bien como está ahora.

**Comment by EdwinBetanc0urt** [comment]
@niclopup corregido en el cambio https://github.com/solop-develop/frontend-core/pull/276 ya actualizado en el servicio de la nube https://vue-develop.solopcloud.com

https://user-images.githubusercontent.com/20288327/182215427-f2d50e8a-7201-4544-a787-9d6f963a270b.mp4
