### ISSUE TITLE
Ventana: Carga > Pestañas > Visualización

### ISSUE THREAD

**Issue by EdwinBetanc0urt** [solop-develop/vue-1.0#251]
En la interrfaz vue las pestañas se componen de pestañas padres (superiores) y pestañas hijas (inferiores), las pestañas padres están comprendidas por la primera pestaña y todas las pestañas siguientes que tengan la misma tabla, como en socio de negocio las pestañas padres se componen de `Socio de Negocio`, `Cliente`, `Proveedor` y `Empleado`, y las pestañas hijas consideran las pestañas de contabilidad, `Contacto`, `Localización`, `Cuenta Bancaria`, entre otras.

Este componente soporta lógica de visualización.

#### Pasos para reproducir:
1. Iniciar sesión con `GardenAdmin`.
2. Abrir la ventana `Socio de Negocio`.
3. Ir a la pestaña `Proveedor`.
4. Intercambiar el valor del campo si-no `Proveedor`.

Observe como la pestaña hija de `Productos Comprados` se visualiza u oculta en función del valor del campo `Proveedor`.

#### Capturas de pantalla
Versión Zk:

https://user-images.githubusercontent.com/20288327/179264352-e88055e5-52f9-425d-a749-604f83f98594.mp4

Versión Vue:

https://user-images.githubusercontent.com/20288327/179264358-db98f1c1-b164-4866-a2ca-374f74808afd.mp4

**Comment by niclopup** [comment]
también rechazo esta issue debido a que es dificil navegar entre registros de la pestaña padre con sus hijos sin errores

https://user-images.githubusercontent.com/31936815/180055120-7e38d3ed-8870-4fd3-b804-0cfd0211f6be.mp4

**Comment by EdwinBetanc0urt** [comment]
Esto esta listo para pruebas en https://vue-develop.solopcloud.com

**Comment by niclopup** [comment]
Se hace muy dificil estar seguro de a que registro corresponde las pestañas. La selección del Cabezal con modo grilla se mueve al seleccionarlo y se hace que se pierda de vista

al no tener el Campo desde donde se vincula la pestaña con el cabezal, no se exactamente a que Padre corresponde, por lo que estoy definiendo una localización que no se bien a que SDN estoy parado.

La única que vi el campo de "Business Partner" en la pestaña veo que está referenciado un SDN que en teoría no estaba parado en él

![image](https://user-images.githubusercontent.com/31936815/193176233-f30a4f4f-978c-4b4e-a082-9dfd0cda5181.png)

Creo que hay que darle una vuelta a las ventanas para que sean más fáciles de utilizar, editar y navegar entre registros.

**Comment by EdwinBetanc0urt** [comment]
El cambiar entre registros ya no hace que el scroll se pierda, por favor confirmar

https://user-images.githubusercontent.com/45974454/196723353-096efcc6-fb60-4ee7-bac8-feb82ab3c2f8.mp4
