### ISSUE TITLE
Campos de ID no se muestran en mono registro

### ISSUE THREAD

**Issue by nsarlabos** [solop-develop/vue-1.0#2528]
## Bug report
Se observa que por ejemplo en la ventana "Versión de Lista de Precio", en los campos que apuntan a un ID de registro, no se está mostrando el dato cuando se pone en vista de mono registro, pero sí se muestra correctamente en vista de grilla.

#### Screenshot or Gif（截图或动态图）

https://github.com/user-attachments/assets/4d2b0ddc-32ac-4615-9e9f-15314696bc9d

#### Additional context

http://spdev01.solopapp.com:24700/vue
Rol: Administrador

**Comment by elsiosanchez** [comment]
Esto esta solucionado en la siguiente version de BackEnd ` 3.7.1-r-17.10-v-4`

https://github.com/user-attachments/assets/a276d67e-6ed5-4186-bef9-d97763a3eacf



![image](https://github.com/user-attachments/assets/67a7d3c4-7cbb-4699-a59b-a3f339e844fd)


Actualmente esa instancia tiene una version mas vieja  ` 3.5.6-r-17.10-v-1`

![image](https://github.com/user-attachments/assets/19986811-d319-48d1-af6a-343d4f5f93a2)

**Comment by nsarlabos** [comment]
@elsiosanchez perfecto, verificado con versión '3.7.1-r-17.10-v-4' en http://spdev02.solopapp.com:24810/vue#

![prueba](https://github.com/user-attachments/assets/35e13988-8312-4c7f-9feb-ad19db841180)

Cierro este issue
