### ISSUE TITLE
Ventana: Carga > Pestañas

### ISSUE THREAD

**Issue by EdwinBetanc0urt** [solop-develop/vue-1.0#254]
- [x] https://github.com/solop-develop/frontend-core/issues/251
- [x] https://github.com/solop-develop/frontend-core/issues/260

**Comment by niclopup** [comment]
errores en #251

**Comment by elsiosanchez** [comment]
Saludos @niclopup Ese error ya fue solventado

**Comment by niclopup** [comment]
Sigo encontrando errores en la navegación entre el cabezal y las pestañas.
Muy dificil de navegar

**Comment by EdwinBetanc0urt** [comment]
Existe mas información para identificar el inconveniente?

> Sigo encontrando errores en la navegación entre el cabezal y las pestañas. Muy dificil de navegar

**Comment by niclopup** [comment]
Tal como mostré en la reunión junto con Yamel, es muy dificil navegar entre registros viendo las dos grillas de cabezal y líneas en simultáneo

**Comment by EdwinBetanc0urt** [comment]
Se agrego la opcion para permitir solo pestañas hijas en mono registros:


https://user-images.githubusercontent.com/45974454/196723353-096efcc6-fb60-4ee7-bac8-feb82ab3c2f8.mp4

Se detallan en el issue https://github.com/solop-develop/frontend-core/issues/251
