### ISSUE TITLE
Nuevo Motor de Reportes > Informe Financiero 

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#2540]
## Feature request

Se realiza una prueba de un informe financiero y si bien muestra datos correctos, existen muchos detalles a corregir:

- [x] #2777

https://github.com/user-attachments/assets/cc452590-473d-479d-a5e4-380b1023ccde

https://github.com/user-attachments/assets/999805ec-5b29-4bd5-b8e2-678bc03fc642

- [x] **Cambiar Paginación rompe el reporte:** La paginación por defecto viene en 15 y este informe normalmente tenga muchas más líneas. Al intentar cambiarle la paginación se rompe el reporte y trae cualquier línea e importes.

https://github.com/user-attachments/assets/d3812cfe-1a5d-4836-bac9-e7821e402c47

- [x] **Sumarización no funciona:** en este reporte la sumarización funcionaría diferente a como funcionan normalemnte otros print Format. Ver como podemos hacer.

- [x] **Líneas Padre no son diferenciadas con lineas fuentes:** Ver ZK como lo hace

![image](https://github.com/user-attachments/assets/175bc4b3-2f47-4849-916a-9e82be3b6343)

![image](https://github.com/user-attachments/assets/b0b3665c-cb00-4320-98e8-146e5bdaca56)

![image](https://github.com/user-attachments/assets/35a1b2f3-a9db-4639-a1d2-62bfce19abcb)

**Comment by Ricargame** [comment]
Buen día señor @niclopup no es necesario volver a generar otro reporte con parmetros nuevos, puede cambiar los parametros directamente desde el mismo reporte 

https://github.com/user-attachments/assets/25efe107-22a4-4a82-a5da-a13b58885ec8

**Comment by niclopup** [comment]
> Buen día señor @niclopup no es necesario volver a generar otro reporte con parmetros nuevos, puede cambiar los parametros directamente desde el mismo reporte
> 
>  Peek.2024-07-31.11-25.mp4

Hola Ricardo, cómo estás?

Si, entiendo que eso puede ser una opción viable en un reporte Print Format como el que mostras. 

Ahora lo que estoy presentando es un reporte generado mediante un Informe Financiero, que tiene una lógica diferente q corre con un proceso desde cada uno de los registros. Si bien veo que hay parámetros en este reporte también en la pestaña lateral, podría quere generar un Informe financiero difernte y por eso entiendoq  debería permitir seleccionar haciendo click en el registro de la ventana "Informe Financiero"

**Comment by EdwinBetanc0urt** [comment]
Hola @niclopup si conversamos con @yamelsenih y en este caso debe regenerar el reporte completamente, vamos a trabajar en las correcciones.

**Comment by Ricargame** [comment]
Señor @niclopup una pregunta, con respecto a este punto, podria brindarme algun ejemplo por favor 

-**Sumarización no funciona: en este reporte la sumarización funcionaría diferente a como funcionan normalemnte otros print Format. Ver como podemos hacer.**

**Comment by Ricargame** [comment]
https://github.com/user-attachments/assets/5df42a3f-305c-408e-b7db-53fc821c3d62
