### ISSUE TITLE
Nuevo Motor de Reportes > Print Report

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#2542]
## Feature request

Se analiza el reporte y se encuentran los siguientes detalles: 

- [x] Anchos fijos en columnas 

![Ancho de Columnas por defecto](https://github.com/user-attachments/assets/f457e516-f17d-4342-9902-d629d45a52bb)

- [ ] Suma total de todos los registros

![image](https://github.com/user-attachments/assets/bad104cb-e51e-43e0-aac3-bae6cce29fe5)

- [x] Columna sin dato muestra en 0

![Columna sin dato muestra 0](https://github.com/user-attachments/assets/c7a4ae0d-43fd-4642-b1a3-0a28d794b0a0)

- [x] Campos muy grandes no permite ver buena visibilidad de reportes

![Tamaño de registros muy grande](https://github.com/user-attachments/assets/190722f4-12f0-4cd6-a089-57f808caefd0)

- [ ] Nombres en Títulos nivel 2 duplicados

![Títuos de Lineas sumarizadas nivel 2 duplicados](https://github.com/user-attachments/assets/9e1f8aca-9404-4fb0-81ca-b326ae8d03a9)

- [ ] Descarga de XSLX sin Nombres

https://github.com/user-attachments/assets/8d6500b0-f7ea-45b1-8230-e131a7c160ce

[report_engine_17910836391559396528.xlsx](https://github.com/user-attachments/files/16444383/report_engine_17910836391559396528.xlsx)

- [x] Check de "Resumen" al reves

![Check Resumido al reves](https://github.com/user-attachments/assets/6df867dc-3cfb-40e4-b50f-9861042ed6fe)

- [ ] Lineas diferentes entre columnas fijas y movibles. 

![Lineas diferente entre columnas fijas y movibles](https://github.com/user-attachments/assets/a5dabba4-d1ba-4b42-8baa-8bb9755ba74c)

https://github.com/user-attachments/assets/88507bce-50f6-4a1d-a09a-f5256711ea6d

**Comment by Ricargame** [comment]
https://github.com/user-attachments/assets/60c0987e-2626-4f9a-b23c-76d9c9648195

**Comment by Ricargame** [comment]
https://github.com/user-attachments/assets/524efdba-f4e8-4078-bd92-43791fc22aef

![imagen](https://github.com/user-attachments/assets/b05ea39f-accd-4519-83db-ba5b2f2e5966)

![imagen](https://github.com/user-attachments/assets/a87df74f-b67f-48dd-85c5-7941eae0d868)

https://github.com/user-attachments/assets/b1b2219f-3468-4062-a8af-733ec7daa9e7

![imagen](https://github.com/user-attachments/assets/216e7b74-4bc5-4ee1-8127-3c2fa05be12b)

https://github.com/user-attachments/assets/52c5a638-b41f-44d2-bdfe-84bbff59b0d4

[report_engine_9870836799425233770.xlsx](https://github.com/user-attachments/files/16876706/report_engine_9870836799425233770.xlsx)

Uploading Peek 2024-09-04 15-30.mp4…

**Comment by Ricargame** [comment]
Cambios disponibles a partir de la versión: https://github.com/solop-develop/frontend-core/releases/tag/4.4.006

https://github.com/user-attachments/assets/f3f0b41d-5a91-426c-acf2-0b4295a39ee5
