### ISSUE TITLE
Ventana: Apertura > Referencias

### ISSUE THREAD

**Issue by EdwinBetanc0urt** [solop-develop/vue-1.0#255]
Acercar a ventanas donde el registro actual ha sido utilizado.

#### Pasos para reproducir
1. Abrir la ventana `Grupo de Socio de Negocio`.
2. Buscar un registro que ha sido utilizado como `Vendors`.
3. Desplegar el menú de acciones.
4. Colocar el cursor sobre la opción de `Referencias`.
5. Acercar a la ventana.

https://user-images.githubusercontent.com/20288327/179368953-10437d4d-ee55-436b-9762-be47938d7726.mp4

**Comment by niclopup** [comment]
Ok si se ve las relaciones sin tener una ventana de SDN abierta.

https://user-images.githubusercontent.com/31936815/180066823-f86d573b-315c-48e1-9510-19b75560ee37.mp4


**Única apertura de ventana**
Ahora, si se cuenta con la ventana abierta, a misma sigue mostrando lo que anteriormente mostraba. no abre una ventana nueva, esto ocurre también al acercar de cualquier registro, utiliza siempre la misma ventana una única vez lo cuál es incorrecto.

https://user-images.githubusercontent.com/31936815/180067389-1e63a415-c61d-4dd2-be0b-c86d271615b4.mp4

**Comment by EdwinBetanc0urt** [comment]
Esto se corregirá al darle soporte a abrir ventanas/consultas inteligentes/reportes/procesos múltiples (https://github.com/solop-develop/frontend-core/issues/199), de lo contrario si la ventana a acercar ya esta abierta, y tiene cambios sin guardar, sea por edición o un nuevo registro, pueden perderse los datos.

Es poco viable invertir tiempo en recargar una ventana ya abierta, y adicionalmente en la agregar validación si existen cambios pendientes por guardar (https://github.com/solop-develop/frontend-core/issues/427).
