### ISSUE TITLE
Al utilizar filtro en un campo queda default

### ISSUE THREAD

**Issue by mgarciaQ76** [solop-develop/vue-1.0#2557]
## Bug report

Se detectó al definir producto en línea de orden de trabajo. Se eligió filtro, selecciono y grabo. Si navego a otra orden de trabajo me sigue manteniendo ese filtro en el campo producto.

#### Steps to reproduce

1. [en orden de trabajo buscar producto con filtro aplicado]
2. [navegar a otra orden]
3. [volver a buscar producto]

#### Screenshot or Gif（截图或动态图）

https://github.com/user-attachments/assets/162b34c3-d2b2-43b4-818e-289c06386e01

#### Expected behavior

El filtro utilizado en una orden de trabajo no debería quedar marcado default para todos los casos

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:  
Versión del Back-End: 3.5.6-r-17.8-v-4
 Versión del Dictionary RS: 1.3.2
 Versión del S3 Gateway RS: 1.2.7
 Versión del Front-End:  4.2.5

Rol: admin
Org: Field services

**Comment by Ricargame** [comment]
Cambios disponibles a partir de la versión https://github.com/solop-develop/frontend-core/releases/tag/4.3.2

https://github.com/user-attachments/assets/4ee86781-ccad-40ec-84ee-38a437b3fed5
