### ISSUE TITLE
No se Visualiza Adjuntos con el Usuario System

### ISSUE THREAD

**Issue by Ricargame** [solop-develop/vue-1.0#2561]
## Bug report
Cuando se adjunta algo en un campo tipo logo de un registro de 'System' como por ejemplo el usuario 'SuperUser' y luego se intenta abrir desde una compañia no se logra visualizar el adjunto ya que se registra con el uuid de la compañia de la sesión y no con el uuid de la compañia del registro

#### Steps to reproduce
1. [Inicia sesión como system]
2. [Realizar un adjunto en un campo de tipo logo]
3. [Intentar visualizar ese adjunto desde una compañia]

#### Screenshot or Gif（截图或动态图）

https://github.com/user-attachments/assets/fc121119-a17a-4e91-90a5-9fa3f1a175a2

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:

**Comment by EdwinBetanc0urt** [comment]
Cambios disponible a partir del `backend` https://github.com/solop-develop/adempiere-grpc-server/releases/tag/3.5.8, `s3 gateway rs` https://github.com/adempiere/s3_gateway_rs/releases/tag/1.2.7 y `frontend` https://github.com/solop-develop/frontend-core/releases/tag/4.2.8

https://github.com/user-attachments/assets/c241a6ac-669a-4cdb-8d47-9c8323ec6bda
