### ISSUE TITLE
ASP afecta funcionamiento de smart browser

### ISSUE THREAD

**Issue by nsarlabos** [solop-develop/vue-1.0#2565]
## Bug report
Se observó que un campo de un SB se mostraba vacío al ingresar con un rol, pero con otro rol se veía correctamente.

Al comentar el caso a @EdwinBetanc0urt se vió que el rol en el cual no se veía el campo, tenía definido un ASP para dicho browser, en el cual el campo en cuestión no estaba presente.

Finalmente se resolvió al inactivar el ASP para los SB.

Se crea este issue porque si bien actualmente no se usa ASP a nivel de diccionario, está afectando de cierta manera a nivel de datos.

Al buscar el smart browser aca https://github.com/solop-develop/adempiere-grpc-server/blob/develop/src/main/java/org/spin/grpc/service/UserInterface.java#L2475 busca su asp 

Aca genera el sql https://github.com/solop-develop/adempiere-grpc-server/blob/develop/src/main/java/org/spin/grpc/service/UserInterface.java#L2493

Pasando por la lista de campos visualizados https://github.com/solop-develop/adempiere-grpc-server/blob/develop/src/main/java/org/spin/base/db/QueryUtil.java#L335 considerando el asp

**Comment by EdwinBetanc0urt** [comment]
Si bien actualmente para el diccionario no se esta usando el ASP, ya que con el cache en `OpenSearch` se envía es lo que esta en las tablas diccionario de system, para generar los sql en las consultas considera el ASP, y si en algún punto alguna columna (`P_DateLastAction`) no esta visualizada por ASP, no lo incluirá en las columnas del select.

Sin columna oculta por ASP:
![imagen](https://github.com/user-attachments/assets/357a70f3-29c9-45b5-8eef-6a45854d19eb)
![imagen](https://github.com/user-attachments/assets/500aeb4d-1f50-46f7-a23b-9ed23a413287)

Con columna oculta por ASP:
![imagen](https://github.com/user-attachments/assets/cd446e46-17d4-4039-a426-424a7f546442)
![imagen](https://github.com/user-attachments/assets/2b29126a-4ef2-4695-bcf4-cc00f75eaffe)

**Comment by Ricargame** [comment]
Cambios disponibles a partir de la versión https://github.com/solop-develop/frontend-core/releases/tag/4.3.2

https://github.com/user-attachments/assets/e170a320-d9c8-4e80-aefb-3b959b2d2a54
