### ISSUE TITLE
En reportes se ven ID de entidades y no los nombres

### ISSUE THREAD

**Issue by mgarciaQ76** [solop-develop/vue-1.0#2579]
## Bug report

Los Reportes de PDF de Print Format (Pending Balance por ejemplo).. no se ven los nombres del SDN sino el ID.
Si lo saco en cambio desde ZK se ve bien
Comentario de Elsio: Sería un problema de grpc-server
https://discord.com/channels/954056226579308624/954070691987193976/1273649755716583469

#### Steps to reproduce

1. [Ingresar al reporte]
2. [Ejecutarlo]

#### Screenshot or Gif（截图或动态图）

![reporte](https://github.com/user-attachments/assets/bc44b985-ac96-4b83-a252-c7c1a9d88258)

#### Expected behavior

Generar el reporte con el nombre de entidades (y no los ID) y quitar los datos marcados en amarillo (símbolo de suma y número 21 en la parte de totales columna Currency)

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:
Org: field services
rol: admin

**Comment by EdwinBetanc0urt** [comment]
Esto se corrige desde adempiere con este cambio https://github.com/adempiere/adempiere/pull/4324 y esta corregido en el backend de vue mediante la libreria de parches https://github.com/solop-develop/adempiere-solop

**Comment by EdwinBetanc0urt** [comment]
Cambios disponibles a partir del frontend Cambios disponibles a partir de la versión https://github.com/solop-develop/frontend-core/releases/tag/4.3.3.

https://github.com/user-attachments/assets/ef671184-a849-45a1-be94-e55eac08ed4f
