### ISSUE TITLE
[Bug Report] Error Asientos Contable

### ISSUE THREAD

**Issue by elsiosanchez** [solop-develop/vue-1.0#2583]
## Bug report
Error no se visualiza los asientos contable de los registros en la ventana
#### Screenshot or Gif（截图或动态图）

![image](https://github.com/user-attachments/assets/1fd71bb4-f9d2-4c6b-9888-97b6275ad1d4)

**Comment by Ricargame** [comment]
Cambios disponibles a partir de la versión https://github.com/solop-develop/frontend-core/releases/tag/4.3.2

https://github.com/user-attachments/assets/03cc3462-e983-42cf-a118-a56ebfb20464
