### ISSUE TITLE
[Bug Report] Si ya fue cargado un registro con columnas de lista no traduce al cambiar idioma

### ISSUE THREAD

**Issue by EdwinBetanc0urt** [solop-develop/vue-1.0#2593]
#### Steps to reproduce

1. Iniciar sesión en ingles.
2. Abrir alguna ventana de documento que tenga el estatus.
3. Verificar que los estados de documento estén en ingles como la sesión.
4. Cambiar a idioma español.
5. Abrir nuevamente la ventana de documento.
6. Verificar que los nombres de estados de documentos no están traducidos.

#### Screenshot or Gif（截图或动态图）

https://github.com/user-attachments/assets/1a999bc5-d43f-4e0d-8a63-171876ab795b

#### Additional context
Al parecer si esta ya cargado en cache la lista de referencia no actualiza con el nuevo idioma.

**Comment by Ricargame** [comment]
Cambios disponibles a partir de la versión https://github.com/solop-develop/frontend-core/releases/tag/4.3.2

https://github.com/user-attachments/assets/0fae2e52-6623-4276-9bfd-e4bbd07aa263
