### ISSUE TITLE
[Bug Report] En ventanas cuya pestaña es tipo vista, aparece el boton de guardar cuando es solo lectura.

### ISSUE THREAD

**Issue by EdwinBetanc0urt** [solop-develop/vue-1.0#2595]
#### Steps to reproduce

1. Abrir la ventana `Documentos sin Aplicar`.
2. Colocar como `Mono Registro`.
3. Ver que aparece el botón de guardar como si existieran modificaciones en el registro.

#### Screenshot or Gif（截图或动态图）

![imagen](https://github.com/user-attachments/assets/144f2fad-5bfe-42b5-b3e2-25e87b3e2420)

![imagen](https://github.com/user-attachments/assets/fcae7cd0-e4d7-452b-98f0-d85f60df82b1)

#### Expected behavior
Si la tabla esta marcada como vista no debería permitir modificar (que no lo hace ya que esta solo lectura) y por ende guardar.

**Comment by Ricargame** [comment]
Cambios disponibles a partir de la versión https://github.com/solop-develop/frontend-core/releases/tag/4.3.2

https://github.com/user-attachments/assets/80173102-3d8d-43b3-972e-777808e92b48
