### ISSUE TITLE
[Bug Report] Error cantidad de registros en los Documento Pendiente

### ISSUE THREAD

**Issue by elsiosanchez** [solop-develop/vue-1.0#2601]
#### Screenshot or Gif（截图或动态图）
![image](https://github.com/user-attachments/assets/04cac575-5a60-45aa-bbfa-7e4f162f4c70)

![image](https://github.com/user-attachments/assets/40dedfc8-6225-4894-8068-bdbd98cfff87)

**Comment by EdwinBetanc0urt** [comment]
Cambios disponibles a partir del backend https://github.com/solop-develop/adempiere-grpc-server/releases/tag/3.6.9


![image](https://github.com/user-attachments/assets/40dedfc8-6225-4894-8068-bdbd98cfff87)
