### ISSUE TITLE
Acción Proceso DUPLICA si se hace doble Click

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#2615]
## Bug report

Cualquier proceso que sea lanzado desde un Botón en el FRONT (VUE) si lo apretamos DOS VECES, por ejemplo hacer doble click, el proceso en cuestión se genera 2 veces. 2 o tantas veces como se haga click en el botón!!!!

esto es un error muy importante que debemos corregir

Originalmente se había resuelto pero sólo se encontró el problema en el Punto de Venta, que luego de hacer 1 vez click en el botón del Carrito para completar la orden, se pasaba el botón a "cargando" para que no permita nunca hacer doble click

Esto es para todos los PROCESOS

#### Screenshot or Gif（截图或动态图）

Agrego una prueba donde se ve claramente que funciona mal los procesos.

https://github.com/user-attachments/assets/772e5031-ed1f-4bf0-80a3-5abdbea3722d

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:

**Comment by yamelsenih** [comment]
Esto se debe corregir como hicimos en el POS:
- Al momento de presionar el botón Ok simplemente se debe validar si se llenaron los campos obligatorios y si está ok para ejecutar
- Si todo está bien entonces:
  - Se debe poner solo lectura el panel de selección
  - Se debe poner solo lectura el botón
  - Se debe cambiar el ícono del botón para que muestre un cargando
  - Se debe ejecutar la petición
  - al terminar la ejecución debe volver a la normalidad todo y recargar la consulta

**Comment by niclopup** [comment]
Agrego los 2 casos que vimos con Elsio de que está el error:

1. Proceso desde SB
2. Proceso desde Punto de Venta -> Completar orden preparada

https://github.com/user-attachments/assets/022c8da3-3c73-4252-990c-99a0c18c3eaa


https://github.com/user-attachments/assets/62a0fd67-68e4-4c96-9a42-3c31d64a0d83

**Comment by Ricargame** [comment]
Cambios disponibles a partir de la versión: https://github.com/solop-develop/frontend-core/releases/tag/4.4.006

https://github.com/user-attachments/assets/30e60c86-5a5d-47be-b050-e6be32506b46
