### ISSUE TITLE
Tableros: Definir columnas solapadas o Independientes

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#262]
## Permitir definir Tableros con Columnas Independientes en las agrupaciones

Actualmente se intenta replicar el ejemplo presentado por Yamel para poder presentar datos en diferentes agrupaciones que no sean sólo por Fechas e Importes. El ejemplo que seguimos para su diseño en VUE fue el siguiente:

![Definición Datasource Chart](https://user-images.githubusercontent.com/31936815/179783077-bf502cec-9ef0-441d-806a-b1dd422bff8c.png)

![Definición Chart](https://user-images.githubusercontent.com/31936815/179783082-5e9bb621-4987-4b97-84b7-6a8e6892f8bc.png)

Se realiza definición en instancia de Pruebas

![Objetivo de Desempeño - venta por Grupo de Producto](https://user-images.githubusercontent.com/31936815/179784217-eab14493-2f34-41d2-ad96-f1507e93b1de.png)

Se logra visualizar de esta manera en ZK

![grafico2 ZK](https://user-images.githubusercontent.com/31936815/179784237-2064e431-77a4-4098-acda-fde5561f316c.png)

Pero en VUE se solapan y se suman los importes por Fechas, si bien están separados cada importe, el total sólo se muestra sumando todo cuando deberíamos tener la opción de mostrarlo así o independientemente cada dato en una columna independiente.

![vue](https://user-images.githubusercontent.com/31936815/179784557-7f0874ee-e7d5-4b07-9a5a-02d9f3c0df5b.PNG)

Se comenta esto en el canal de Tableros y la respuesta de @EdwinBetanc0urt  fue la siguiente:

> @Nico López aca hay un ejemplo en vivo, donde puedes modificar los datos y actualizara el gráfico https://apache.github.io/echarts-handbook/en/concepts/dataset
> [Handbook - Apache ECharts](https://apache.github.io/echarts-handbook/en/concepts/dataset)
> la respuesta que genera el proxy https://api-develop.solopcloud.com/api/adempiere/dashboard/addons/charts/metrics?id=1000000&token=78407040-2efd-4eca-a295-ea530bd76c3c&language=es
> Imagen
> aca en el metodo loadChartMetrics es donde transforma la respuesta del proxy lo que pide la libreria eCharts https://github.com/solop-develop/frontend-default-theme/blob/experimental/components/ADempiere/Dashboard/charts/BarChart.vue#L94
> 
> la bandera que dijiste para solapar las barras del dashboard en diccionario de adempiere. En vue agregar un metodo casi igual al de loadChartMetrics para que transforme la respuesta y dependiendo de esa bandera llamara a loadChartMetrics o al metodo a crear "loadChartMetricsOverlapping", seguira siendo el mismo componente de graficos de barras solo que con dos formas de presentar los valores

Se comentó esto a @yamelsenih en una reunión y comentó que no es necesario hacer ningún cambio de código en teoría, que esta funcionalidad ya estaba considerada en VUE actualmente. Buscamos cambiar el tipo de gráfica pero no logramos encontrar una manera que si se tome en columnas independientes.

Por favor podrías confirmar si es necesario realizar un desarrollo para darle soporte a esto o si ya está actualmente considerado?

en caso de ser necesario realizar un cambio, por favor podrías confirmar el enfoque? de manera de poder asignar esta tarea a Raúl Capecce y podamos continuar con la definición de tableros.

gracias!

**Comment by yamelsenih** [comment]
Estos los tengo definido y no se ven así, voy a agregar las imágenes como se ven aquí
![Screenshot from 2022-07-27 12-21-24](https://user-images.githubusercontent.com/2333092/181298889-25f2ccfc-2fa2-40c1-8ee4-43cb29013af9.png)
![Screenshot from 2022-07-27 12-21-17](https://user-images.githubusercontent.com/2333092/181298891-72a2daf0-17e4-4e6f-990b-484ad42be808.png)
![Screenshot from 2022-07-27 12-20-35](https://user-images.githubusercontent.com/2333092/181298906-73453562-e13d-4ae1-a00b-46a94cbaa933.png)
![Screenshot from 2022-07-27 12-20-27](https://user-images.githubusercontent.com/2333092/181298908-6ae8fc14-354a-4820-9fb4-1ffe0cedb3ff.png)
![Screenshot from 2022-07-27 12-21-11](https://user-images.githubusercontent.com/2333092/181298896-5571702d-3a3e-465d-9436-8c944183ee5f.png)
![Screenshot from 2022-07-27 12-21-05](https://user-images.githubusercontent.com/2333092/181298899-d2fe62e0-bc4c-4254-a805-092d511ff926.png)
![Screenshot from 2022-07-27 12-21-00](https://user-images.githubusercontent.com/2333092/181298900-8dcafad8-1fb4-4046-a861-5bf3e2c53afa.png)
![Screenshot from 2022-07-27 12-20-50](https://user-images.githubusercontent.com/2333092/181298901-ff3623f3-050f-455c-ad6e-126096a53927.png)
![Screenshot from 2022-07-27 12-20-45](https://user-images.githubusercontent.com/2333092/181298902-d231c1f2-cadd-4cbb-b732-4242676dc6f1.png)

![Screenshot from 2022-07-27 12-21-30](https://user-images.githubusercontent.com/2333092/181298874-3b0121f7-819f-442a-864b-26a5930e2453.png)

**Comment by yamelsenih** [comment]
El resultado es este:
![photo_2022-07-27_12-25-32](https://user-images.githubusercontent.com/2333092/181299777-e7944995-5801-4cca-82b7-882c7e07e92e.jpg)
![photo_2022-07-27_12-25-28](https://user-images.githubusercontent.com/2333092/181299779-aa86303a-7f9c-48ee-b88a-9734b3c32232.jpg)
![photo_2022-07-27_12-25-12](https://user-images.githubusercontent.com/2333092/181299783-5c0e946f-0ddf-44f3-b0ab-563653671cb9.jpg)

**Comment by nsarlabos** [comment]
@yamelsenih Respecto a tus ejemplos, te comento los que he probado.

**Actividad por Hora (Del Mes)**

Al configurarlo como tipo "Area Chart" no me queda igual al tuyo, sino de la siguiente manera:

![dashboard1](https://user-images.githubusercontent.com/29130825/182402269-fa7106c3-802f-41ee-824f-b22564a78ef3.PNG)

También lo definí como "Area Chart" en ventana de objetivo de desempeño. Sin embargo, si le defino que sea del tipo "Pie Chart", se visualiza así:

![dashboard2](https://user-images.githubusercontent.com/29130825/182402881-86709a06-b81c-4ee3-b1b2-93dbd5b8edac.PNG)

Creo que sería de ayuda si también adjuntas capturas para ver como está configurado en la ventana de "Objetivo de Desempeño".

**Ventas por Grupo de Producto**

Tal como comentó @niclopup el gráfico se muestra de la siguiente manera:

![dashboard3](https://user-images.githubusercontent.com/29130825/182405946-92b0e011-6cb2-4419-9c94-4df01c645960.PNG)

Cuando en ZK se visualiza así de manera correcta:

![dashboard4](https://user-images.githubusercontent.com/29130825/182407276-59f8aa78-2a81-4120-9ccf-3c6f1d304f82.PNG)

Es decir, en VUE no toma la separación en distintas barras para los meses de una categoría de producto, sino que los apila en una misma barra para cada categoría. 

Lo que se desea es separar en columnas diferentes según una segmentación de "Categoría de Productos", como en este caso  por ejemplo.

**Resumen de Ventas**

Este caso no me queda claro, ya que la foto del gráfico está tapada, y en la definición del chart tiene tipo "Area chart", pero sin embargo parece mostrarse como gráfico de barras.

![dashboard5](https://user-images.githubusercontent.com/29130825/182409161-978c7a18-2e0b-4283-bef4-48c0ed702797.PNG)

**Volumen de Ventas**

Entiendo que no hay capturas de pantalla para la definición de este tablero, pero de todos modos parece no tener una agrupación definida, sino simplemente muestra el importe de ventas para cada mes.
