### ISSUE TITLE
Orden de venta no permite cambiar regla de pago

### ISSUE THREAD

**Issue by mgarciaQ76** [solop-develop/vue-1.0#2622]
## Bug report

En la ventana de órdenes de venta no es posible modificar la regla de pago (esto en zk se puede modificar ok)

#### Steps to reproduce

1. [Consultar ov]
2. [Modificar regla de pago]

#### Screenshot or Gif（截图或动态图）

![ordenes de venta regla de pago zk](https://github.com/user-attachments/assets/0085b000-cd93-4516-b78e-de9fe25a2e33)
![ordenes de venta regla de pago vue](https://github.com/user-attachments/assets/16e40ae0-7cc9-46b4-a287-7bc5dfeb79bd)

#### Expected behavior

Que permita modificar la regla de pago

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version: 
 Número de versión:

 3.9.4
 Versión del Back-End:

 multi-tenants-0.0.9-r-17.10-v-5-i-21835-v-9
 Versión del Dictionary RS:

 1.4.6
 Versión del S3 Gateway RS:

 1.2.7
 Versión del Front-End:

 multi-tenants-0.1.0

rol: administrador
Org: casa matriz

#### Additional context

Este problema de que no permite cambiar regla de pago ocurre en la 24810 y en 24610

**Comment by EdwinBetanc0urt** [comment]
Este tipo de campo/columna tiene un comportamiento especial, al igual que `DocAction` que abre el procesar una acción de documento, `Record_ID` que acerca a un registro, o `Posted` que abre el visor contable.

Actualmente no existe esta funcionalidad, acá algunos enlaces para replicar el comportamiento en vue:

https://github.com/adempiere/adempiere/blob/59557cc2ee85ac938cd4f31a246d891bc2b15b8f/base/src/org/compiere/model/GridField.java#L536


#### Swing UI:
- Boton: https://github.com/adempiere/adempiere/blob/develop/client/src/org/compiere/grid/ed/VButton.java#L89
- Panel: https://github.com/adempiere/adempiere/blob/develop/client/src/org/compiere/apps/APanel.java#L2507
- Modal de Pago: https://github.com/adempiere/adempiere/blob/develop/client/src/org/compiere/grid/VPayment.java#L72


#### Zk UI:
- Botón: https://github.com/adempiere/adempiere/blob/develop/zkwebui/WEB-INF/src/org/adempiere/webui/editor/WButtonEditor.java#L105
- Panel: https://github.com/adempiere/adempiere/blob/develop/zkwebui/WEB-INF/src/org/adempiere/webui/panel/AbstractADWindowPanel.java#L2057
- Modal de Pago: https://github.com/adempiere/adempiere/blob/develop/zkwebui/WEB-INF/src/org/adempiere/webui/apps/form/WPayment.java#L99


### Nota:
Verificar que hace la columna `CreateFrom`.

**Comment by EdwinBetanc0urt** [comment]
Si es tipo botón y la columna es `PaymentRule` se debe mostrar tipo lista.

**Comment by EdwinBetanc0urt** [comment]
Cambios disponibles a partir del forntend `4.4.017` y del backend  `3.8.005`.


https://github.com/user-attachments/assets/43b14fe7-0221-424e-ad3d-9477d6e1cf4f
