### ISSUE TITLE
Error al guardar Localización

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#2627]
## Bug report
Se intenta guardar una localización pero da error ya que dice no tener el campo completado.

![image](https://github.com/user-attachments/assets/cbdf079d-976e-46cd-a118-052d845ab504)

Lo raro es que luego de un ratito, me moví de la ventana y luego volvi y si me permitió guardarlo. Al menos sólo en SDN, en almacén no.

![image](https://github.com/user-attachments/assets/973c0e0e-0f44-4946-9a13-98bd7519a2bd)

este error si bien se mantiene con el código actual de la 24810, también estaba presente en versiones anteriores

#### Screenshot or Gif（截图或动态图）

https://github.com/user-attachments/assets/409a7036-2b68-4587-8616-1fc081576b5e

https://github.com/user-attachments/assets/f51cbf9e-1687-4822-a79a-898814e6759d

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:
- http://spdev02.solopapp.com:24810/vue#/profile/index
![image](https://github.com/user-attachments/assets/76850922-5ce4-49df-8f49-151311babc51)

**Comment by Ricargame** [comment]
Cambios disponibles a partir de la versión: https://github.com/solop-develop/frontend-core/releases/tag/4.4.006

**Warehouse and Location**

https://github.com/user-attachments/assets/8daf3282-82dd-4999-a852-9f4481ced3c9


**Business Partner**

https://github.com/user-attachments/assets/08b74f71-2c36-47ff-8dbf-be27da3bfbe5
