### ISSUE TITLE
Ordenamiento ventana por campo sólo toma Pagina actual

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#2630]
## Bug report

Ordenamiento ventana por campo sólo toma Pagina actual

Si se realiza una búsqueda en una ventana que trae 2000 registros, si se desea aplicar un ordenamiento según cierto campo, el orden se debe aplicar sobre todos los registros. 

Actualmente sólo está ordenando la página que se muestra. Esto hace muy dificil ordenar correctamente los datos para encontrar lo que uno desea encontrar. 

Se debe aplicar un criterio de que el ordenamiento aplique sobre todos los registros encontrados por el filtro aplicado. 

#### Steps to reproduce

1. Abrir ventana Ordenes de Venta
2. ver como Multi Registro
3. hacer click sobre columna Fecha hasta q ordene ascendentemente
4. ver que sólo toma registros de la página actual y no todos los datos

#### Screenshot or Gif（截图或动态图）

https://github.com/user-attachments/assets/c9a7ef0c-1f91-4c14-b6ab-a4fab9461420

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version: 
- 
![image](https://github.com/user-attachments/assets/efd3b65a-ac8e-4476-996c-f282316b1b09)

http://spdev02.solopapp.com:24810/vue#/profile/index

**Comment by EdwinBetanc0urt** [comment]
@Ricargame actualmente esta ordendando solo de forma ascendente, falta agregar soporte de forma descendente

**Comment by Ricargame** [comment]
https://github.com/user-attachments/assets/20ac1a40-fa47-415e-88f1-e45efad66877

**Comment by EdwinBetanc0urt** [comment]
En ventana de `Ordenes de Venta` no esta haciendo ordenado descendente en las fechas.

**Comment by Ricargame** [comment]
Actualmente el ordenamiento está funcionando, el problema ocurre cuando se quiere hacer un ordenamiento descendente, ya que si no se le da en la flecha que apunta hacia abajo element no reconoce que es descendente, sé ira trabajando así mientras se consigue una solución 

https://github.com/user-attachments/assets/7e5cb1ae-13c1-47dd-8240-987683a761a4

**Comment by Ricargame** [comment]
Cambios disponibles a partir de la versión del front: https://github.com/solop-develop/frontend-core/releases/tag/4.4.017

https://github.com/user-attachments/assets/0603d183-fb78-454f-9227-11ad3721936c
