### ISSUE TITLE
[Bug Report] Combinanción contable pide esquema contable obligatorio

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#2631]
## Bug report
No está simple la definición de una combiación contable en un campo de cuenta contable. 

Cuando uno define una cuenta y una organización al intentar guardar salta un error de "Esquema Contable" 

![image](https://github.com/user-attachments/assets/478337b0-391e-4953-b9c2-f449e1d24c74)

No se ve donde se podría seleccionar. 

#### Steps to reproduce

1. [xxx]
2. [xxx]
3. [xxxx]

#### Screenshot or Gif（截图或动态图）

primera prueba, no cargaba listado de Organizaciones

https://github.com/user-attachments/assets/95ea2c81-d5d8-4ae8-bbd6-eb06fcffdee2

Segunda prueba si cargaba listado de organizaciones pero no encontraba Esquema Contable

https://github.com/user-attachments/assets/dd5bbc01-80c9-4836-97c1-4db0bf671fd7

En ZK se puede sin problema

https://github.com/user-attachments/assets/3cb0728d-b8f4-498d-b5aa-0f244ac162f6

Esta parecería ser la combinación que definió al aplicar ese caso en ZK

![image](https://github.com/user-attachments/assets/71abea6f-86ed-4225-a89e-164069da4922)

veo que la misma ya existía anteriormente y tenía definido el esquema contable

![image](https://github.com/user-attachments/assets/43858429-c140-46af-a8c0-6970786525d2)

Habría que ver un caso de cuando se crea una nueva combinación contable a ver que sucede pero esta cuenta es la misma que intnté seleccionar desde VUE

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:

**Comment by Ricargame** [comment]
Cambios disponibles a partir de la versión: https://github.com/solop-develop/frontend-core/releases/tag/4.4.006

https://github.com/user-attachments/assets/5b3a9e3e-f906-40fe-9158-1860a4bccf49

**Comment by niclopup** [comment]
se verifica y no se encuentra este mismo error, pero el error de que la primera vez que se quiere guardar una nueva combinación no se encuentra una Organización se repite.
Luego se vuelve a intentar nuevamente y si trae las org. 
sin definir una org no se puede definir nueva combinación contable
 

https://github.com/user-attachments/assets/8e5e2a7d-7501-442f-a65f-623b16ee8c1a

**Comment by Ricargame** [comment]
Cambios disponibles a partir de la versión del back-end https://github.com/solop-develop/adempiere-grpc-server/releases/tag/3.10.002

https://github.com/user-attachments/assets/82c4b3f5-94ea-4f6a-b361-654850329388
