### ISSUE TITLE
Ubicación de Almacén no se puede buscar

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#2650]
## Bug report
Se intenta seleccionar un campo de "Ubicación" pero no funciona el buscador. 

#### Steps to reproduce

1. Abrir ventana Orden de salida
2. Ir a sus línaes e intentar modificar la ubicación

#### Screenshot or Gif（截图或动态图）

https://github.com/user-attachments/assets/1f39fe9a-cb90-4afb-96e5-57952ac560bc

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:   4.4.004

**Comment by Ricargame** [comment]
Cambios disponibles a partir de la versión: https://github.com/solop-develop/frontend-core/releases/tag/4.4.006

https://github.com/user-attachments/assets/2f01c3ad-8abb-4697-b38b-1c035415dcd6
