### ISSUE TITLE
BUGFIX para Versión VUE anterior (Corregir proceso duplicado)

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#2652]
## Bug report

Necestiamos corregir este error reportado en issue #2615 para poder subir el cambio a la instancia del cliente.

Actualmente el cliente tiene la  **Versión del Front-End:  4.2.5**

Producción: http://cac.solopapp.com/vue#/profile/index

![image](https://github.com/user-attachments/assets/41278f6c-62d9-4a9a-955d-65ebcb55d988)

Testing (Misma Versión): http://spdev01.solopapp.com:24700/vue#/profile/index

Recordar que aún está en SPDEV01

![image](https://github.com/user-attachments/assets/b013f558-86ae-453a-b42a-91ee2a9c14fb)

#### Screenshot or Gif（截图或动态图）

https://github.com/user-attachments/assets/4ebd3ab4-b309-43d3-afe0-4baa3dfc4679

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version: Versión del Front-End:  4.2.5

**Comment by EdwinBetanc0urt** [comment]
La instancia esta actualizada


![imagen](https://github.com/user-attachments/assets/f3edf794-2e90-4fae-a68e-9a0b2733ca57)
