### ISSUE TITLE
Motor de Reportes > Página y Número no se ven si los parámetros están desplegados

### ISSUE THREAD

**Issue by Ricargame** [solop-develop/vue-1.0#2658]
## Bug report
Actualmente, con el nuevo formato de reporte, si se despliegan los criterios de búsqueda, el pie de página no se alcanza a visualizar 
#### Steps to reproduce

1. [Generar Reporte Detalle del Pago]
2. [Expandir Criterios de Búsqueda]

#### Screenshot or Gif（截图或动态图）

![imagen](https://github.com/user-attachments/assets/a65a2dde-b1c4-492b-972a-f8ec9c89f9ad)

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:

**Comment by EdwinBetanc0urt** [comment]
Corregido a partir de la versión del frontend `4.4.009`

![Image](https://github.com/user-attachments/assets/9c8be268-16d3-441e-bb6f-88eba8330c08)

**Comment by niclopup** [comment]
ok
