### ISSUE TITLE
Error de Visualización en Reporte

### ISSUE THREAD

**Issue by Ricargame** [solop-develop/vue-1.0#2664]
## Bug report
Se esta visualizando el objeto completo y no su valor 
#### Steps to reproduce

1. [Generar Reporte de Listado de órdenes Completas]
2. [Cambiar formato de Impresión ha Listado de Órdenes Simples de Distribución]
3. [Ir a la Columna Cantidad a Entregar]

#### Screenshot or Gif（截图或动态图）

![imagen](https://github.com/user-attachments/assets/682ec149-53fc-4b3f-9620-860b5c2bb2dd)

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:

**Comment by EdwinBetanc0urt** [comment]
Corregido a partir de la version del frontend `4.4.009`:


![Image](https://github.com/user-attachments/assets/0aecce0f-b078-40c5-9757-61f7e29c438d)
