### ISSUE TITLE
Ordenamiento de Registros desde ventana con filtro (abierta desde Documentos relacionados)

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#2668]
## Bug report

 error al realizar un ordenamiento de regisotrso sobre una ventana que tenía un filtro aplicado automático yua que se navegó a la ventana desde Documentos Relacionados desde un Proyecto

#### Screenshot or Gif（截图或动态图）

https://github.com/user-attachments/assets/d8169906-c7c4-40ae-9b71-2f9093557233

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:

![image](https://github.com/user-attachments/assets/6a93db46-fb22-40e3-971b-222168f334bd)

**Comment by Ricargame** [comment]
Cambios disponibles a partir de la versión del front: https://github.com/solop-develop/frontend-core/releases/tag/4.4.017

https://github.com/user-attachments/assets/ad68a068-bfa1-4a9c-94e3-af3dc4e41377

**Comment by niclopup** [comment]
ok
