### ISSUE TITLE
parametros en Reporte no hace Scroll

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#267]
#### Steps to reproduce

1. Abrir el Reporte de "Detalle de la Orden" desde una pantalla no muy grande
2. Habilitar todos los parámetros existentes a que estén visibles.
3. los parámtros de más de abajo, si no se muestran en pantalla no se pueden acceder ya que no hace scroll

**Comment by elsiosanchez** [comment]
Solventado 


https://user-images.githubusercontent.com/45974454/194946729-a8506097-6d7f-4cea-9755-b98cc7671834.mp4



https://vue-develop.solopcloud.com/#/
