### ISSUE TITLE
Ampliar visibilidad en Balance de Prueba Navegable

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#2673]
## Feature request

Se desea mejorar la visual de esta forma para que se logre visualizar la mayor cantidad de líneas y Columnas en una misma pantalla. 

Para ello se sugieren los siguientes cambios:

- [x] #2775
aplicar mismo diseño que tiene actualmente los reportes nuevos, consideranod los últimos cambios solicitados para mejorar la altura de las líneas. En este caso el tamaño de letra lo veo bien pero podemos ver como queda dejando igual a los reportes. 

- [x] #2776
Se desea poder generar rápidamente mediante una acción (Acción doble click o Acercar) que se genere un reporte de Balance de Prueba (Trial Balance) para dicha cuenta consideranod el período que se está definido en los parámetros. Esta funcionalidad es igual a como funciona actualmente en ZK

**3. Líneas hasta el final de la ventana**

Actualmente si se esconden los parámetros no se están viendo las líneas hasta el final de la ventana sino que se corta la imagen de lineas antes y no se aprovecha el total de la altura de la ventana.

![image](https://github.com/user-attachments/assets/2bb1ed0f-f831-428f-a2b5-0f1bad1b2450)

**Comment by Ricargame** [comment]
Cambios disponibles a partir de la versión del frontend: https://github.com/solop-develop/frontend-core/releases/tag/4.4.017

https://github.com/user-attachments/assets/bb9c77ff-34e7-47ee-8e04-c0d67e041084

**Comment by niclopup** [comment]
este lo cierro pero creo otro q no está resuelto aún
