### ISSUE TITLE
Jerarquias en Informe Financiero

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#2674]
## Feature request

Ver como manejar las jerarquias en los Informes financieros para analizar como podría ser implementado

**Comment by yamelsenih** [comment]
Esto ya hice cambios en la imagen del backend: [1.0.3](https://github.com/solop-develop/adempiere-report-engine-service/releases/tag/1.0.3)

Este issue está relacionado con este otro https://github.com/solop-develop/frontend-core/issues/2620

**Comment by yamelsenih** [comment]
Hace falta el cambio en el frontend para que permita ver los informes financieros con la funcionalidad nueva de reportes

**Comment by yamelsenih** [comment]
Este es el pull request del fronmtend: https://github.com/solop-develop/frontend-core/pull/2694

**Comment by yamelsenih** [comment]
Hola, podemos agregar un ejemplo aquí?
Con los parámetros del proceso y asegurarse que funcionen en ZK bastaría

**Comment by Ricargame** [comment]
Cambios disponibles a partir de la versión del front: https://github.com/solop-develop/frontend-core/releases/tag/4.4.017

https://github.com/user-attachments/assets/67679a2a-675c-4862-ba37-af0c94fae48f
