### ISSUE TITLE
Ampliar visualización Líneas Smart Browser

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#2678]
## Feature request

Se puede ver la manera de reducir un poco más la altura de las líneas del SB? 

Entiendoq eu en un momento me dijiste q está al minimo posible debido a la edición de las líneas. Esto se mantiene así? este es el mínimo?

#### Describe alternatives you've considered

![Altura lineas Registros de SB](https://github.com/user-attachments/assets/e2db07e0-6bdf-4f34-9a10-aabeec32157e)

**Comment by Ricargame** [comment]
Cambios disponibles a partir de la versión del front: https://github.com/solop-develop/frontend-core/releases/tag/4.4.017

https://github.com/user-attachments/assets/39a57968-2010-46c2-8153-2cd2b763094c

**Comment by niclopup** [comment]
en general bien, sólo que se debe ajustar por defecto que los campos de "Producto" "Socio del Negocio" "Usuario" "Descripción" "Nombre" siempre tengann un ancho más grande por defecto y q no siga la misma lógica del ancho del texto del título de la columna

Ej: sb Generar Factura desde Línea de Orden
instancia:24816

![image](https://github.com/user-attachments/assets/1875ed41-4003-4abe-a204-ea4964601bb6)

**Comment by Ricargame** [comment]
Buenas tardes, señor @niclopup lo que comenta creo que es lo que se menciona en estos issues

- https://github.com/solop-develop/frontend-core/issues/2677
- https://github.com/solop-develop/frontend-core/issues/2687

creo que el alcance de este issue en cuestión ya fue abarcado

**Comment by Ricargame** [comment]
Cambios disponibles a partir de la versión del Front: https://github.com/solop-develop/frontend-core/releases/tag/4.4.018

https://github.com/user-attachments/assets/dcb4953c-993e-48f4-91bc-274271b4810a
