### ISSUE TITLE
Ventana: Carga > Tabla > Paginación

### ISSUE THREAD

**Issue by EdwinBetanc0urt** [solop-develop/vue-1.0#268]
La lista de registros tiene una paginación del tamaño de 15 registros por página, de manera que el usuario en la parte inferior a la derecha puede navegar entre las páginas disponibles de los registros:

https://user-images.githubusercontent.com/20288327/179983844-52ed9b45-5bad-4a07-ad22-2e78772ba7c5.mp4

**Comment by niclopup** [comment]
Se muestra como se desea buscar el SDN de nombre "dd" navegando entre los registros y la paginación de la primer pestaña.

No se logra encontrar entre  los registros que aparecen sin ningún filtro en ninguna de las 3 páginas.

ahora si se búsca "dd" si aparece, al igual que más SDN que tienen código numérico en vez de letras.

https://user-images.githubusercontent.com/31936815/180056691-23c03c40-2cea-4807-8d52-b7791a994879.mp4

El único que aparece con código numérico es el de nombre "test"

![image](https://user-images.githubusercontent.com/31936815/180057188-7f9af594-e768-492e-ac8e-32bb9086d451.png)

**Comment by elsiosanchez** [comment]
Saludos, este problema esta resuelto en https://vue-develop.solopcloud.com/ por favor revisar que todo este ok y cerrar el issue.


https://user-images.githubusercontent.com/45974454/192623525-f6e1fcb7-4652-4876-8e3a-825eca6b7559.mp4
