### ISSUE TITLE
[Bug Report] Redundancia Acercador de Reporte

### ISSUE THREAD

**Issue by elsiosanchez** [solop-develop/vue-1.0#2680]
## Bug report
se requeire que en caso de que tenga 2 ventanas filtrar la ventana que tenga is_sales_transaction igual al valor del campo IsSOTrx

#### Screenshot or Gif（截图或动态图）

![image](https://github.com/user-attachments/assets/d16e7f1d-08b2-4931-8a5a-b6c932d402b3)

**Comment by elsiosanchez** [comment]
Solventado en el siguiente PR https://github.com/solop-develop/frontend-core/pull/2684

**Comment by Ricargame** [comment]
Cambios disponibles a partir de la versión del front: https://github.com/solop-develop/frontend-core/releases/tag/4.4.017

https://github.com/user-attachments/assets/ed741ef1-94a9-4bd9-ac31-7cc6d1bd4fbc
