### ISSUE TITLE
Histórico de Procesos no muestra historial

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#2685]
## Bug report
Se intenta ver el el histórico de procesos que generó un usuario pero no se logra acceder al historial

Sería útil ver por estado o situación:

- Completos
- con error
- Corriendo

#### Screenshot or Gif（截图或动态图）
![image](https://github.com/user-attachments/assets/e98c65c1-ec5b-4219-b13f-940781a61df4)

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:

**Comment by elsiosanchez** [comment]
Esto fue solventado en el siguiente PR https://github.com/solop-develop/frontend-core/pull/2706

**Comment by EdwinBetanc0urt** [comment]
Cambios disponibles a partir de la versión del frontend `4.4.017`

![image](https://github.com/user-attachments/assets/8be64c0b-8ae0-4a07-9353-08ce27f8b839)
