### ISSUE TITLE
Ancho de columnas en Modo Grilla

### ISSUE THREAD

**Issue by yamelsenih** [solop-develop/vue-1.0#2687]
Al cambiar ancho de Columnas de una grilla, que al guardar o al editar no se vuelva a cargar los anchos por defecto sino que se mantenga los cambios aplicados en el ancho de las columnas.

**Comment by yamelsenih** [comment]
Esto simplemente bastaría con implementar lo que ya existe para el nuevo motor de reportes en el ćalculo de ancho máximo de columnas, únicamente contando los caracteres del encabezado de la columna

**Comment by niclopup** [comment]
Habíamos quedado en que el ancho de estas columnas se definirá según el nombre del Título del campo/columna para todos los campos , excepto para:
Los que sean de tipo Texto o SDN o Producto o Proyecto o Cuenta bancaria. En este caso deberíamos considerar otro ancho FIJO

Ej: Línea de Orden de Compra (aplica para todas las líneas de todos los documentos)
![image](https://github.com/user-attachments/assets/9c62a1e1-cef6-44d6-8b10-990fd74717cd)

Proyecto de Medios
![image](https://github.com/user-attachments/assets/4919d501-bbb2-4de7-a661-06a285c4c392)

**Comment by yamelsenih** [comment]
Para los campos del tipo:
- Producto
- Socio de Negocio
- Cuenta Bancaria
- Proyecto

Se debe definir un tamaño fijo que pueda ser agradable al usuario. Propongo abrir cualquier ventana, abrir la orden de ventas y ampliar el primer producto o campo para que sea más claro y colocar ese tamaño.

Hacer este ejercicio para cada uno

**Comment by yamelsenih** [comment]
Ejemplo
![image](https://github.com/user-attachments/assets/353cc58c-f1bb-4247-998b-c2a4b83a80fb)
debería ser sólo la parte que usa el component

**Comment by Ricargame** [comment]
Cambios disponibles a partir de la versión del Front: https://github.com/solop-develop/frontend-core/releases/tag/4.4.018

https://github.com/user-attachments/assets/9d90c5e6-ea5a-4667-b6d8-ec4b982a27db

**Comment by niclopup** [comment]
Los anchos están muy grandes. no se aplica la lógica primera definida.

**Comment by niclopup** [comment]
Está funcionando mal el ancho de columnas. 

- Si no da para mostrar todo el nombre sólo debería mostrar lo q puede, tal como hacía antes.
- Si tiene texto muy largo idem, nunca debería dejar de mostrar el nombre
- Altura de Líneas. Creo que con esta última versión quedó muy baja, podríamos agrandarla un poco más? pero que quede menor a como estaba antes. 

![image](https://github.com/user-attachments/assets/c6338e10-78f8-4e11-9253-a3ec72d7940c)


https://github.com/user-attachments/assets/e86dca07-9406-4bdd-98f3-6d9b80aa4377

Si les parece por favor ni  bien hagan los cambios, ya sea localmente me avisan y lo validamos.

**Comment by Ricargame** [comment]
Cambios disponibles a partir de la version del front: https://github.com/solop-develop/frontend-core/releases/tag/4.4.023

https://github.com/user-attachments/assets/732f209d-c4d6-4f73-b1eb-ecce9da0e8ba
