### ISSUE TITLE
Ventana: Carga > Tabla > Registros

### ISSUE THREAD

**Issue by EdwinBetanc0urt** [solop-develop/vue-1.0#269]
Así como se tiene soportado la vista de campos mono registros, se soporta la vista multi registros done se visualizara una tabla con las columnas disponibles para visualización, intercambiando con el botón `Multi Registro` ubicado en la parte superior a la derecha, cuando se esta en modo panel o mono registro.

Versión Zk:

https://user-images.githubusercontent.com/20288327/179985592-ba67bc59-277f-406a-a783-1b046d73b926.mp4

Versión Vue:

https://user-images.githubusercontent.com/20288327/179985593-48fbe2a4-407f-4ac5-9852-376bc77833f8.mp4

**Comment by niclopup** [comment]
por que cuando se abre la ventana y se pone "Multi Registro" sólo muestra 15 registros?

![image](https://user-images.githubusercontent.com/31936815/193289658-b058db5d-ca61-4b25-8601-4de3b5a2c10b.png)

Lo raro es que si cuando en tu ejemplo apretas en la "Página 1" ves más registros. pero ahora si intento queda como máximo en 15, que es la mitad de la página, no se utiliza ni todo el alto de una página al máximo.

Entiendo que si se desea ver Multi Registro, no es para ver sólo 15. En caso de sólo mostrar 15 por defecto (para no cargar la consulta entiendo que es), se debería permitir una opción de cambiar eso a 50 o hasta 100 registros. Casi todas las páginas que manejan esto de la paginación tienen estas opciones.

Viendo Openproject veo que ahora ni ponen las opciones pero limitan los registros por página a 250!

https://user-images.githubusercontent.com/31936815/193291004-09d6c10d-eb4b-43b3-8eca-43fa78534568.mp4

**Comment by EdwinBetanc0urt** [comment]
> por que cuando se abre la ventana y se pone "Multi Registro" sólo muestra 15 registros?
> 
> ![image](https://user-images.githubusercontent.com/31936815/193289658-b058db5d-ca61-4b25-8601-4de3b5a2c10b.png)
> 
> Lo raro es que si cuando en tu ejemplo apretas en la "Página 1" ves más registros. pero ahora si intento queda como máximo en 15, que es la mitad de la página, no se utiliza ni todo el alto de una página al máximo.
> 
> Entiendo que si se desea ver Multi Registro, no es para ver sólo 15. En caso de sólo mostrar 15 por defecto (para no cargar la consulta entiendo que es), se debería permitir una opción de cambiar eso a 50 o hasta 100 registros. Casi todas las páginas que manejan esto de la paginación tienen estas opciones.
> 
> Viendo Openproject veo que ahora ni ponen las opciones pero limitan los registros por página a 250!
> Ejemplo.de.Paginacion.250.registros.Open.Project.mp4

La cantidad de registros por página actualmente está establecido en 15, se ampliará la funcionalidad siguiendo el hilo de forma separada en el issue https://github.com/solop-develop/frontend-core/issues/457.

Si este issue cumple con lo descrito, cerrarlo y cambiar el estatus.

**Comment by niclopup** [comment]
Ok muchas gracias!
