### ISSUE TITLE
Reporte: Quitar la sección de "Parámetros" del Reporte

### ISSUE THREAD

**Issue by yamelsenih** [solop-develop/vue-1.0#2695]
Quitar la sección de "Parámetros" de la parte superior del reporte para que sólo quede dicha edición en la pestaña lateral existente.
![image](https://github.com/user-attachments/assets/53acad28-ae46-41d4-9b5f-e84d2ebde266)

**Comment by EdwinBetanc0urt** [comment]
Cambios disponibles a partir de la versión del frontend `3.8.005`

![image](https://github.com/user-attachments/assets/e66a55ae-776f-43ed-a12f-dc0f80e2a0a6)

este issue esta relacionado con https://github.com/solop-develop/frontend-core/issues/2702
