### ISSUE TITLE
Reporte: Reducir altura de las líneas

### ISSUE THREAD

**Issue by yamelsenih** [solop-develop/vue-1.0#2697]
Reducir altura de las líneas para que se ajuste lo más posible al nuevo tamaño de letra para que entre la mayor información posible. Tener cuidado por que la idea es que se reduzca la altura pero tampoco tanto para q no se pueda leer correctamente.

**Comment by EdwinBetanc0urt** [comment]
Cambios disponibles a partir de la versión del frontend `4.4.017`

![image](https://github.com/user-attachments/assets/a5545b73-aa14-4b73-829b-869e91bfc815)
