### ISSUE TITLE
Reporte: Ancho de Columnas de Cantidades o Importes

### ISSUE THREAD

**Issue by yamelsenih** [solop-develop/vue-1.0#2698]
Ancho de Columnas de Cantidades o Importes reducirlas al máximo para que se vea bien el Texto del titulo  y las cantidades según ancho máximo del los datos.

**Comment by Ricargame** [comment]
Cambios disponibles a partir de la versión del front: https://github.com/solop-develop/frontend-core/releases/tag/4.4.017

https://github.com/user-attachments/assets/e570ef31-486f-49cd-870a-1544968b82dc
