### ISSUE TITLE
Reportes: Cambio de Preferencias de reporte no cambia Formato de impresión

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#2701]
## Bug report

Se va a la pestaña lateral a cambiar el formato pero no actualiza el cambio. una vez si me lo tomómluego de varias veces de intentarlo

![image](https://github.com/user-attachments/assets/b8cd7cfc-cf3f-4d4f-8c15-848a453d4f08)

#### Screenshot or Gif（截图或动态图）

https://github.com/user-attachments/assets/83140872-0f76-4c9e-86ec-a1f36c42d2ac

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:
- 
![image](https://github.com/user-attachments/assets/17ee6b59-bc0f-47df-a7c1-991f8d7fe697)

**Comment by Ricargame** [comment]
Cambios disponibles a partir de la versión del front: https://github.com/solop-develop/frontend-core/releases/tag/4.4.017

https://github.com/user-attachments/assets/ae2f713f-db95-47c1-8d9e-e7798c3c6355
