### ISSUE TITLE
Preferencias en misma ventana abajo en vez de en pestaña lateral

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#2702]
## Feature request

El cambio de las preferencias en pestaña lateral no queda tan práctico en cuanto a la usabilidad.

#### Describe the solution you'd like

Creo que sería mejor aprovechar el espacio que nos quead libre abajo del todo que ya estamos ocupando con la numeración y la paginación

además es necesario ver q formato de impresión se está utilizando cuando se ve el reporte, si esta en la pestña dereecha siempre deberemos hacer varios clicks más.

![image](https://github.com/user-attachments/assets/e1e5c67e-be70-4a33-b98c-efb6ee7d96c9)

poner acá lo más pequeño posible lo que antes estaba arriba en la sección colapsable.

Estaría bueno que también con el cambio de cualquier dato de estos se actualice el repote automáticamente y no que sea necesario hacer click en actualizar. 

Además ver como se puede poner el check de Resumido mucho más pequeño. algo así:

- [ ] Resumen

**Comment by EdwinBetanc0urt** [comment]
Cambios disponibles a partir de la versión del frontend `3.8.005`

![image](https://github.com/user-attachments/assets/e66a55ae-776f-43ed-a12f-dc0f80e2a0a6)
