### ISSUE TITLE
Demora en operación desde Punto de Venta

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#2712]
## Bug report

Se encuentran demoras en la utilización del Punto de ventas en cuanto a la creación de líneas y definición de Cantidades

![image](https://github.com/user-attachments/assets/0643b057-6178-46cd-8e31-5acb8192c51c)

Tiempo atrás esto se manejó en las issues: solop-develop/vue-1.0#1815 

Se resolvió moviendo este cliente y trayendolo a un datacenter local ya que al parecer con menos latencia este tiempo se veía notoriamente mejorado.

#### Screenshot or Gif（截图或动态图）

https://github.com/user-attachments/assets/bfad4a35-84ea-4cd8-b2e2-b9731af4e349

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:

![image](https://github.com/user-attachments/assets/d96bd864-3051-4657-ab55-9ac223d882d0)

**Comment by niclopup** [comment]
Agrego ejemplo de como demora en la 24814

Rol: Administrador
Organzación: Casa Central


https://github.com/user-attachments/assets/1d8d2a28-d61a-47dd-98f0-c4abcc087cf7

**Comment by yamelsenih** [comment]
## Primera revisión local
![image](https://github.com/user-attachments/assets/58db0c5f-112f-4442-8f9e-43a18b390677)

### Columnas virtuales (hacen que las consultas sean más lentas)
La tabla `C_OrderLine` tiene columnas virtuales que no ayudan mucho, aparte de tener columnas virtuales están marcadas como `Table Direct` y eso hace otro sub-query.

- **M_Product_Group_ID**: `(SELECT M_Product_Group_ID FROM M_Product WHERE M_Product_ID = C_OrderLine.M_Product_ID)`
- **M_Product_Classification_ID**: (`SELECT M_Product_Classification_ID FROM M_Product WHERE M_Product_ID = C_OrderLine.M_Product_ID)`
- **M_Product_Class_ID**: `(SELECT M_Product_Class_ID FROM M_Product WHERE M_Product_ID = C_OrderLine.M_Product_ID)`
- **M_Product_Category_ID**: `(SELECT M_Product_Category_ID FROM M_Product WHERE M_Product_ID = C_OrderLine.M_Product_ID)`
- **Info**: `(SELECT C_OrderLine.Line || '-' || (SELECT name FROM M_Product WHERE m_product_id = C_OrderLine.M_Product_ID))`
- **Info_To**: `(SELECT (SELECT documentNo FROM C_Order WHERE C_Order_ID = C_OrderLine.C_Order_ID) || ' - ' || C_OrderLine.Line)`

### Indice
Por el momento solo veo que debería estar un índice para `C_OrderLine_ID` ya que tiene muchos constraints incluyendo uno de referencia de la misma tabla y los contraints no crean índices automáticamente.

```SQL
CREATE INDEX idx_c_orderline_id ON C_OrderLine (C_OrderLine_ID);
```

### Consultas algo lentas (afecta a todos)
Agregué un parche con [esto](https://github.com/adempiere/adempiere/pull/4353) que ya tenemos para limitar las consultas SQL a 1 registro cuando se use el método `first`, `firstOnly` y `firstId`

### Histórico de Cambios para `C_Order` y `C_OrderLine`
Para ambas tablas está habilitado el histórico de cambio para todas sus columnas, esto si que le da lentitud al persistir los datos

Hice un SQL para quitarlo (opcional)
```SQL
-- Remove ChangeLog C_Order, C_OrderLine
UPDATE AD_Table SET IsChangeLog = 'N' WHERE AD_Table_ID IN(260, 259);
UPDATE AD_Column SET IsAllowLogging = 'N' WHERE AD_Table_ID IN(260, 259);
```

### Consulta de Tasa de Cambio
Esta tabla no tiene indice y se consulta cada vez que se lee datos de la orden

```SQL
-- C_Conversion_Rate
CREATE INDEX idx_C_Conversion_Rate_ValidFrom ON C_Conversion_Rate (ValidFrom);
CREATE INDEX idx_C_Conversion_Rate_ValidTo ON C_Conversion_Rate (ValidTo);
CREATE INDEX idx_C_Conversion_Rate_C_Currency_ID ON C_Conversion_Rate (C_Currency_ID);
CREATE INDEX idx_C_Conversion_Rate_C_Currency_ID_To ON C_Conversion_Rate (C_Currency_ID_To);
CREATE INDEX idx_C_Conversion_Rate_C_ConversionType_ID ON C_Conversion_Rate (C_ConversionType_ID);
```

### Consulta de Precio

Esta tabla no tiene índice por los campos de búsqueda y se consulta al crear o actualizar precios

```SQL
-- M_ProductPrice
CREATE INDEX idx_M_ProductPrice_M_Product_ID ON M_ProductPrice (M_Product_ID);
CREATE INDEX idx_M_ProductPrice_M_PriceList_Version_ID ON M_ProductPrice (M_PriceList_Version_ID);
```

## Resultado
Los `INSERT` bajaron **100 ms**, el delete está aún lento pero hay que probar en un ambiente diferente a ver
![image](https://github.com/user-attachments/assets/19aee149-e4df-4ec8-81f1-239d2d02ce13)


## Cambios a realizar en el frontend
![image](https://github.com/user-attachments/assets/61a847f9-99f1-4784-a656-d05b09e4fe0d)
Por cada operación ejecuta tres peticiones:
- La petición de acción: `POST`, `PUT`, `DELETE` dependiendo de si es un `INSERT`, `UPDATE` o `DELETE`
- La petición para refrescar el pedido: `GET`
- La petición para refrescar las lineas: `GET`

Considero que la petición para refrescar la línea está demás, tanto el `POST` como el `PUT` devuelven el objeto ya con los mismos datos que devolvería el listar líneas, para el caso del `DELETE` devuelve empty si todo está ok.

Lo que hay que hacer es:
- `POST`: Debe agregar el registro a la table si no existe
- `PUT`: Debe actualizar los datos del registro en la tabla
- `DELETE`: Remueve el registro de la tabla

Nota: Los cambios de backend [están](https://github.com/solop-develop/adempiere-grpc-server/releases/tag/3.9.003) en esta versión

@rcapecce

**Comment by elsiosanchez** [comment]
Cambios disponibles a partir de la versión del Front

https://github.com/solop-develop/frontend-core/releases/tag/4.4.018

https://github.com/user-attachments/assets/cf9c7dab-f02a-4137-b11c-8cdbd37573e0

**Comment by niclopup** [comment]
@yamelsenih la velocidad la verdad que lo veo bastante bien ahora.

Apliquemos estos cambios en nuestra instancia de teting del cliente así validamos con muchos más datos reales a ver como se comporta.

**Comment by yamelsenih** [comment]
Hola, sólo para complementar hice una prueba ya con datos reales aquí y quitando el histórico de cambios en el rol: https://github.com/solop-develop/frontend-core/issues/2894#issuecomment-2445549626
