### ISSUE TITLE
Mejora en Buscador de Producto

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#2713]
## Bug report

Se desea agregar las siguientes mejoras en el buscador de productos:

* aplicar mejoras visuales para que se vea más eficiente el espacio. Ver de aplicar misma lógica que se aplicó para el Balance de Prueba navegable y los reportes. las columnas con ancho por defecto según el ancho del texto o 
* Ampliar visibilidad al esconder criterios de búsqueda
* Agregar acercar a ventana de producto
* Agregar check de "Ver sólo Disponibles" para que filtre por productos con Cantidad en Existencia MAYOR a 0

![image](https://github.com/user-attachments/assets/34a00269-b7cd-4885-93a4-c80c8d8e801f)

![image](https://github.com/user-attachments/assets/f0f3e78a-40b7-489f-8e4a-6fd10a06f63a)

**Comment by elsiosanchez** [comment]
Cambios disponibles a partir de la versión del frontend: https://github.com/solop-develop/frontend-core/releases/tag/4.4.017


https://github.com/user-attachments/assets/5daf87c0-d030-48e6-be08-665f82b3297b
