### ISSUE TITLE
Los UUID nulos, detienen la exportación de diccionario a OpenSearch

### ISSUE THREAD

**Issue by EdwinBetanc0urt** [solop-develop/vue-1.0#2715]
Si en una base de datos existen `UUID` nulos en los registros de las tablas usadas para exportar, hasta ahora:
#### Diccionario:
- `AD_Table`.
- `AD_Column`.
- `AD_Window`.
- `AD_Tab`.
- `AD_Field`.
- `AD_Process`.
- `AD_ProcessPara`.
- `AD_View`.
- `AD_ViewDefinition`.
- `AD_ViewColumn`.
- `AD_Browse`.
- `AD_BrowseField`.
- `AD_Form`.
#### Compañia/Acceso:
- `AD_Client`.
- `AD_Role`.
- `AD_Menu`.
- `AD_Tree`.
- `AD_TreeNode`.

### Error
Esto genera un `thead 'tokio-runtime-worker' panicked` deteniendo completamente la suscripción de ese tópico kafka que tiene el `UUID` nulo.

![Image](https://github.com/user-attachments/assets/c76a3574-5199-459c-b408-658b7f71c512)

Sin embargo no marca la cola como leída, por lo que al reiniciar o reconectar la suscripción a kafka vuelve a leer esa cola con errores y genera nuevamente el error.

**Comment by elsiosanchez** [comment]
Se requiere tener la siguiente version

`
 Versión del Back-End: 3.8.005
 Versión del Dictionary RS: 1.4.9
`

![image](https://github.com/user-attachments/assets/7fa89a85-58cd-485b-8619-f6715f1c63b9)
