### ISSUE TITLE
Ventana: Complementos > Notas (Chat)

### ISSUE THREAD

**Issue by elsiosanchez** [solop-develop/vue-1.0#272]
Se requiere agregar soporte al componentes para agregar notas en la ventana 

_**Pasos a Seguir:**_

1. Abra una ventana 
2. Diríjase al lado derecho de la ventana
3. Abra el panel de información 
4. Seleccione la pestaña de notas

### ADempiere-zk

https://user-images.githubusercontent.com/45974454/180075514-1139e414-9cba-4ffb-9e80-1426d7586034.mp4

### ADempiere-Vue

https://user-images.githubusercontent.com/45974454/180072671-787d5b57-8bf4-4a2c-81c0-3d9bbb335a93.mp4

**Comment by niclopup** [comment]
Muy  bueno, para que sirve estas opciones?
![image](https://user-images.githubusercontent.com/31936815/195364599-d4956a90-cc22-4982-b8c0-4d758588ea42.png)

**Comment by niclopup** [comment]
Muy bueno!

sólo un detalle, paga agregar una foto o archivo, no se logra ver completa la ventana y se debe bajar con el tabulador. Sería bueno que se pueda ver toda la ventana completa

![image](https://user-images.githubusercontent.com/31936815/195365805-130cbe79-4e3b-465d-a00b-a3b5abb4c856.png)

https://user-images.githubusercontent.com/31936815/195365833-c1c428ef-d1c0-44a4-b3e7-b772faa27465.mp4


Otro punto es que no hay manera de darse cuenta si un registro tiene o no una Nota o un Anexo sin entrar a la pestaña en cuestión.

Estaría bueno que se pueda visualizar desde el Registro sin entrar a la sección lateral.
![image](https://user-images.githubusercontent.com/31936815/195366760-8c212acd-ff20-450c-be35-a68bf9891b66.png)

Ejemplo sin Comentario
![image](https://user-images.githubusercontent.com/31936815/195366879-b9a1b466-53ac-40e0-8cd9-fe31f37f1ad6.png)

Ejemplo con comentario
![image](https://user-images.githubusercontent.com/31936815/195366999-9a99d1fa-67de-43fd-af94-7d3ce1dc0ded.png)

**Comment by EdwinBetanc0urt** [comment]
Como se observa en el video, se agrego un scroll para poder ver los botones al agregar imágenes


https://user-images.githubusercontent.com/45974454/196481491-286ed24d-8010-4166-b021-5c9b93b5758f.mp4

De igual manera en los pull request enlazados a este issue, se detallan las nuevas características como soporte a:
* Enlaces
* Imágenes
* Gráficos
* Tablas
* Markdown
* HTML
