### ISSUE TITLE
Redondeo predeterminado en campos

### ISSUE THREAD

**Issue by yamelsenih** [solop-develop/vue-1.0#2728]
Los campos numericos tienen muchos dígitos al mostrarse, esto no es del todo correcto.
![Image](https://github.com/user-attachments/assets/9ad01c4f-db37-44cf-9ec8-a09438bfd76d)

# Recomiendo lo Siguiente
- Si se tiene moneda el contexto (Ejemplo en una Orden de Venta): debe mostrar el monto redondeado a la precisión de la moneda
- Si no se tiene moneda en el contexto: Se debe usar la precisión de la moneda por defecto de la compañía `$C_Currency_ID`

La visualización debe ser redondeada, la persistencia debe ser tal como se escribe

**Comment by Ricargame** [comment]
Cambios disponibles partir de la versión del front https://github.com/solop-develop/frontend-core/releases/tag/4.4.020
Cambios disponibles partir de la versión del back-end https://github.com/solop-develop/adempiere-grpc-server/releases/tag/3.10.001

https://github.com/user-attachments/assets/63ad1571-9862-45b5-b9bd-5e26a280ddc5

**Comment by EdwinBetanc0urt** [comment]
Se regresa esto para verlo a detalle

**Comment by EdwinBetanc0urt** [comment]
Cambios disponibles a partir de la versión del frontend `4.4.022`.

![Image](https://github.com/user-attachments/assets/2f902917-70b6-4d87-bff3-3227e2928826)

**Comment by niclopup** [comment]
Se aplicó esto para campos de Importe pero también para campos de CANTIDAD

![image](https://github.com/user-attachments/assets/6ca8a0aa-a013-4539-88cd-ffa11a4a1f4a)

eso está mal

sólo debe aplicarse para IMPORTES.
}
ahora se cambia a mono registro y muestra con 2 decimales los precios pero no los importes

![image](https://github.com/user-attachments/assets/4403bb2b-5def-4ec5-b4ba-b728071c5bc4)

se podría dejar que siempre muestre los precios con los decimales que muestra como grilla?

sólo se definiría los NETOS de linea como 2 decimales así como los totales de documentos.

**Comment by elsiosanchez** [comment]
Cambios disponibles a partir de la versión del frontend ` 4.4.023-rc-6`

![image](https://github.com/user-attachments/assets/d008030c-8093-4cbf-8e98-3f948c0b585f)
