### ISSUE TITLE
Error al abrir ventanas en instancia 24816

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#2729]
## Bug report

Error al abrir ventanas en instancia 24816

Si se ve la ventana en modo Tablet o algo más pequeño que el monitor, las ventanas abren bien
![image](https://github.com/user-attachments/assets/02641a37-f57a-42c7-b3f6-a533c40bb1ad)

Cuando se ve normal como monitor, se rompe y se cierra

![image](https://github.com/user-attachments/assets/61aad8af-99f8-47c5-b97e-54eee80753cb)

 "status": 500,
    "message": "Error finding record by ID Ok(\"{\\\"_index\\\":\\\"process_es_mx_dan\\\",\\\"_id\\\":\\\"a42ab3b6-fb40-11e8-a479-7a0060f0aa01\\\",\\\"found\\\":false}\")"
}

#### Screenshot or Gif（截图或动态图）

https://github.com/user-attachments/assets/521a40b7-4ae4-4ee4-9a52-ecfc5817296b

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:

![image](https://github.com/user-attachments/assets/3ed736e7-2d89-4429-90b9-e36f74ce11d2)

**Comment by EdwinBetanc0urt** [comment]
Ya esta el tema de procesos/reportes:

![image](https://github.com/user-attachments/assets/d758588d-ee5d-48ff-b745-a99a54a89a4e)


![image](https://github.com/user-attachments/assets/5de36527-69d6-4c26-8887-3c9392941cad)


Existen otros errores pero es porque no consigue las tablas de gráficos, es probable que no tenga importado los xml del proyecto https://github.com/adempiere/adempiere-dashboard-improvements

![image](https://github.com/user-attachments/assets/97f68c83-c9d5-4c0e-8e3a-0b48858da0a9)
