### ISSUE TITLE
Forma: Búsqueda > Socio de Negocio

### ISSUE THREAD

**Issue by EdwinBetanc0urt** [solop-develop/vue-1.0#273]
Se requiere dar soporte a los campos tipo búsqueda cuando sea socio de negocio debe tener un comportamiento similar al del Zk:

https://user-images.githubusercontent.com/20288327/179983021-3d9a8cea-2381-4536-b9ef-05b6f8c610d7.mp4

https://user-images.githubusercontent.com/20288327/180309713-59e3a1d8-af7c-4555-b65f-af3971708c4b.mp4

**Comment by niclopup** [comment]
No se controla si el documento desde donde se busca un SDN es Transacción de Ventas Y/N lo que hace mostrar SDN Proveedores en por ejemplo una Orden de Venta o viceversa.

https://user-images.githubusercontent.com/31936815/188989262-7b0244c0-2e1f-4c7b-ae6a-e3f04f9aa17e.mp4

**Comment by EdwinBetanc0urt** [comment]
Corregido y listo para pruebas en https://vue-develop.solopcloud.com

https://user-images.githubusercontent.com/20288327/192617262-67d6da34-f80b-43a7-853a-a7aee837b15d.mp4
