### ISSUE TITLE
Error buscando SDN en Pestñaa "Fase" de Ventana "Proyecto de Medios" (24816)

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#2731]
## Bug report

Error buscando SDN en Pestñaa "Fase" de Ventana "Proyecto de Medios"

no se encuentran SDN

si preferis te voy pasando todo Issues de cada caso sino...

#### Steps to reproduce

1. Abrir ventana Proyecto de Medios. Ir a Proyecto nro 2291
2. Bajar a Pestaña Fase, crear una nueva e intentar definir un SDN

#### Screenshot or Gif（截图或动态图）

https://github.com/user-attachments/assets/1cce8070-a0e2-434d-9566-5edb3ddd4297

#### Expected behavior

Debe buscar SDN como sucede en la 24810 y en esta instancia en Zk

#### Other relevant information
- Instancia: SPDEV02:24816
- Web Browser:
- Node.js version:
- adempiere-vue version: 
![image](https://github.com/user-attachments/assets/a7b58e0d-80f0-4c15-842a-7d1a293b6585)

**Comment by elsiosanchez** [comment]
Se agregor la opcion de copiar la pestana de errores en la siguiente version https://github.com/solop-develop/frontend-core/releases/tag/4.4.019-rc-3

https://github.com/user-attachments/assets/a84ed1e9-91b8-4ff2-8c8a-53f2a741f14d


https://github.com/user-attachments/assets/a39ad719-8b62-4f10-a510-8e42f99f7791
