### ISSUE TITLE
En línea de OC quema dos decimales en precio y no permite cuatro

### ISSUE THREAD

**Issue by mgarciaQ76** [solop-develop/vue-1.0#2733]
## Bug report

Realizando pruebas en instancia 24815 se detecta este problema al generar Orden de Compra:

* Genera una diferencia si comparamos el sistema con el caso puntual (puede ser el redondeo a dos decimales) calculo iva 40.92 en sistema

En VUE corta el costo del producto a dos decimales, mientras que en zk mantiene la cantidad de decimales original (en zk no genera diferencia, solo en VUE)

La precisión de precio en lista de precio es 5 (solo que lo está respetando en zk y no en VUE)

#### Steps to reproduce

1. [Generar orden de compra]
2. [Generar linea de orden de compra con importe de 4 decimales]
3. [Consultar importes de linea de oc]

#### Screenshot or Gif（截图或动态图）

![diferencia en totales](https://github.com/user-attachments/assets/94d07956-752a-46c5-be07-1edf7963456d)

![oc en zk](https://github.com/user-attachments/assets/d7bae048-7878-4447-818e-b6c771039bb3)

![OC en vue](https://github.com/user-attachments/assets/ed8c47e5-a3ca-4d10-897b-e9baf99362a6)

![precision precio de lista de precio](https://github.com/user-attachments/assets/404e763a-4ffd-4a68-8e15-89dbe14797b2)

#### Expected behavior

Que en VUE presente el mismo funcionamiento que zk y permita la cantidad de decimales en costo original y no que lo corte a dos decimales generando diferencia en totales

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:

 Solop
 Nombre de Implementación:

 ${ADEMPIERE_VERSION} 20231226-1819
 Fecha Versión:

 miércoles, 02 de octubre de 2024, 12:00:00 a. m.
 Número de versión:

 3.9.4
 Versión del Back-End:

 3.8.005-r-17.10-v-1
 Versión del Dictionary RS:

 1.4.9
 Versión del Motor de Reporte:

 1.0.0-dev
 Versión del S3 Gateway RS:

 1.2.7
 Versión del Front-End:

 4.4.017

**Comment by elsiosanchez** [comment]
Por el momento la precision lo lo toma del contexto 

![image](https://github.com/user-attachments/assets/10516073-87ab-4c80-831c-63711fcdef88)

**Comment by EdwinBetanc0urt** [comment]
Permite guardar mas de dos decimales, pero para visualización o formateo solo muestra los que indique la precisión. Cambios disponibles a partir de la versión del frontend `4.4.022`.

https://github.com/user-attachments/assets/27e871f7-8a52-4456-ab88-acf819ab324e

**Comment by niclopup** [comment]
está ok

se define según la precisión de la MONEDA. correcto? 

![image](https://github.com/user-attachments/assets/9b4cb8bb-0f52-4a27-905e-c13383c8fe20)

No según la precisión de la lista de precios. 

![image](https://github.com/user-attachments/assets/9ff5a45d-ff4f-4140-bbf6-68f0a63fa5be)


Ahora un detalle. La precisión de las CANTIDADES se está tomando de la misma manera y no debe ser así. La precisión de las cantidades se debe definir según la UNIDAD DE MEDIDA

![image](https://github.com/user-attachments/assets/fc2e3038-c386-4644-abcc-d2bf6e894a2a)
![image](https://github.com/user-attachments/assets/fd41660f-27b8-4ec3-b371-921b295a31d4)

**Comment by Ricargame** [comment]
Cambios disponibles a partir de la version del front: https://github.com/solop-develop/frontend-core/releases/tag/4.4.023

https://github.com/user-attachments/assets/52986797-cc18-4623-b3dc-4bdb80e870ba
