### ISSUE TITLE
reporte Balance de Prueba no muestra registros y da error

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#2735]
## Bug report

Desde ZK se ve ok el reporte de "Balance de Prueba" 

![image](https://github.com/user-attachments/assets/404c15f4-4a25-4ce0-8dcc-3e19bb82a51d)

Desde VUE con estos parámetros

![image](https://github.com/user-attachments/assets/6c30b649-5a50-41f9-affd-5dd450ff4cb4)

![image](https://github.com/user-attachments/assets/51b17fd2-c6e7-4571-9886-6e3c2b7a39b7)

Sale el siguiente error

<html>
<body>

TypeError: Cannot read properties of undefined (reading 'display_value') at http://spdev02.solopapp.com:24810/vue/static/js/chunk-62a5ebea.f789752d.js:1:16471 at Array.map (<anonymous>) at C (http://spdev02.solopapp.com:24810/vue/static/js/chunk-62a5ebea.f789752d.js:1:16253) at http://spdev02.solopapp.com:24810/vue/static/js/chunk-62a5ebea.f789752d.js:1:15267 at Array.map (<anonymous>) at o.<anonymous> (http://spdev02.solopapp.com:24810/vue/static/js/chunk-62a5ebea.f789752d.js:1:15047) at rr.get (http://spdev02.solopapp.com:24810/vue/static/js/chunk-libs.278e8467.js:70:30788) at rr.evaluate (http://spdev02.solopapp.com:24810/vue/static/js/chunk-libs.278e8467.js:70:31777) at e.i [as value] (http://spdev02.solopapp.com:24810/vue/static/js/chunk-libs.278e8467.js:420:20056) at o.get [as dataList] (http://spdev02.solopapp.com:24810/vue/static/js/chunk-libs.278e8467.js:420:22219)
--

 

<br class="Apple-interchange-newline">
</body>
</html>

#### Steps to reproduce

1. [xxx]
2. [xxx]
3. [xxxx]

#### Screenshot or Gif（截图或动态图）

https://github.com/user-attachments/assets/9e6d9478-49d2-4e05-9400-60ee1aacaeec

https://github.com/user-attachments/assets/357e0e37-bfab-4d57-a463-465a36243189

#### Other relevant information
- instancia: 24810
- Web Browser:
- Node.js version:
- adempiere-vue version:

![image](https://github.com/user-attachments/assets/0639a95e-2011-4c2b-8c46-0866f971ca1c)

**Comment by Ricargame** [comment]
Cambios disponibles a partir de la versión del frontend: https://github.com/solop-develop/frontend-core/releases/tag/4.4.017

https://github.com/user-attachments/assets/536b3ba3-7f36-4521-b7f5-308f92749978
