### ISSUE TITLE
No se muestra el boton de imprimir reporte en pestaña `Entrada` de ventana `Cálculo de Morosidad`.

### ISSUE THREAD

**Issue by EdwinBetanc0urt** [solop-develop/vue-1.0#2740]
Pese a que en la definición de la pestaña tiene un reporte asociado:

![Image](https://github.com/user-attachments/assets/f39ff7dc-db56-4782-b265-bcf9ae3e51fd)

No se visualiza el botón de acceso directo a imprimir:

https://github.com/user-attachments/assets/7f024c40-2cff-4541-a8fc-c018fff4875f

![imagen](https://github.com/user-attachments/assets/e369ed14-e345-4564-9e96-24952db753a9)

**Comment by Ricargame** [comment]
Cambios disponibles a partir de la versión del frontend: https://github.com/solop-develop/frontend-core/releases/tag/4.4.017

https://github.com/user-attachments/assets/8153b6da-021f-4066-9834-c1364e31573e
