### ISSUE TITLE
SDN queda guardado en buscador al crear nuevo Documento

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#2743]
## Bug report

SDN queda guardado en buscador al crear nuevo Documento

#### Screenshot or Gif（截图或动态图）

https://github.com/user-attachments/assets/301dd315-740e-4897-8b00-a2de42d5a54d

#### Other relevant information
- Instancia: 24810
- Web Browser:
- Node.js version:
- adempiere-vue version:

![image](https://github.com/user-attachments/assets/3efe47dd-56cb-4fb7-a589-a897eba5d09a)

**Comment by elsiosanchez** [comment]
https://github.com/solop-develop/frontend-core/pull/2732

**Comment by Ricargame** [comment]
Cambios disponibles a partir de la versión del frontend: https://github.com/solop-develop/frontend-core/releases/tag/4.4.017

https://github.com/user-attachments/assets/e9a492b3-f8d8-40e2-8c19-fec6de46efc2
