### ISSUE TITLE
Corta título de columnas de todas las ventanas en multi registro

### ISSUE THREAD

**Issue by mgarciaQ76** [solop-develop/vue-1.0#2745]
## Bug report

Se detecta que en Ordenes de compra visualizando cabezal o líneas en multi registro está cortando el nombre de las columnas (aun ampliando el tamaño de columna).
Revisando otras ventanas vemos que es un problema que se está dando en general en todas las ventanas
Se reportó en instancia 24816 pero también está replicandose en 24810

#### Steps to reproduce

1. [Consultar ordenes de compra cabezal o linea]
2. [visualizar multi registro]
3. [Ver nombre de columnas]

#### Screenshot or Gif（截图或动态图）

![corta titulo de columnas en OC](https://github.com/user-attachments/assets/23d24f52-452f-4e91-9ef8-8c58e8427427)

#### Expected behavior

Que los títulos de columna  se ajuste al tamaño de columna y se vea completo (hoy se ve cortado)

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:

 Solop
 Nombre de Implementación:

 ${ADEMPIERE_VERSION} 20240912-1419
 Fecha Versión:

 miércoles, 02 de octubre de 2024, 12:00:00 a. m.
 Número de versión:

 3.9.4
 Versión del Back-End:

 3.8.005-r-17.10-v-1
 Versión del Dictionary RS:

 1.4.9
 Versión del Motor de Reporte:

 1.0.0-dev
 Versión del S3 Gateway RS:

 1.2.7
 Versión del Front-End:

 4.4.017

**Comment by niclopup** [comment]
![image](https://github.com/user-attachments/assets/c9a0c8fa-1937-456c-a7ff-937f450dcce0)

resuelta en siguiente versión
