### ISSUE TITLE
Error PeriodClose al completar Ordenes de Compra/Venta

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#2746]
## Bug report

Se intenta completar una orden de compra y da error por período cerrado. 

Ahora voy a ZK y puedo completar sin problemas ya que el período está abierto.

Analizando ahora veo que en ZK la contbialidad queda como No Contabilizado por no tener TASA. Esto puede ser que haga fallar a VUE? Deberían comportarse igual ZK y VUE.

**Confirmado que es por que no encuentra TASA DE CAMBIO**

El problema sucede por que no encuentra TASA DE CAMBIO y por eso no Completa.

ahora lo q si está incorrecto es que de ese error y no sea más exacto de que es por que no hay tasa.

#### Screenshot or Gif（截图或动态图）

![image](https://github.com/user-attachments/assets/25b2424f-c110-48a7-9f55-238d024ffa23)

![image](https://github.com/user-attachments/assets/eef83114-6ed6-4117-bc91-675e87201ac0)

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:  4.4.017

**Comment by yamelsenih** [comment]
Al reiniciar caché funciona. Esto pasa igual en ZK cuando un período está cerrado.

**Paso a Paso final**
- Verifique que el período asociado al documento se encuentre cerrado
- Cree e intente completar un documento
- Vea el error de período cerrado
- Vaya a la ventana **Calendario, Año y Período** y abra el período para el documento de prueba
- Intente nuevamente completar el documento => Persiste el error
- Reinicie caché
- Intente nuevamente completar el documento => El error desaparece

**Comment by niclopup** [comment]
cierro pero aún no se resolvió problema de raíz
