### ISSUE TITLE
No se habilita botón nuevo en recibo de pago/cobro

### ISSUE THREAD

**Issue by mgarciaQ76** [solop-develop/vue-1.0#2751]
## Bug report

No habilita en VUE botón nuevo
Ocurre lo mismo en Recibo de Cobro (en zk esto no ocurre)
Adjunto video.
Detectado en instancia 24816

#### Steps to reproduce

1. [ingresar en Recibo de cobro, o recibo de pago]
2. [Intentar seleccionar nuevo]

#### Screenshot or Gif（截图或动态图）

https://github.com/user-attachments/assets/d21fbbd7-eb65-41b6-8839-f5efe51c3bee

#### Expected behavior

Que permita generar nuevo registro de recibo de cobro o pago

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:

 Solop
 Nombre de Implementación:

 ${ADEMPIERE_VERSION} 20240912-1419
 Fecha Versión:

 miércoles, 02 de octubre de 2024, 12:00:00 a. m.
 Número de versión:

 3.9.4
 Versión del Back-End:

 3.8.005-r-17.10-v-1
 Versión del Dictionary RS:

 1.4.9
 Versión del Motor de Reporte:

 1.0.0-dev
 Versión del S3 Gateway RS:

 1.2.7
 Versión del Front-End:

 4.4.017

**Comment by EdwinBetanc0urt** [comment]
Saludos, el problema es que los registros no tienen `UUID`, lo cual es obligatorio para el correcto funcionamiento en vue.

![imagen](https://github.com/user-attachments/assets/bfcecd2b-fa3c-4fad-8eb9-71fecf464385)

Recomiendo correr el proceso de generar UUIDs.
