### ISSUE TITLE
busqueda de ov por tipo documento destino trae otros doc como facturas cobros, etc

### ISSUE THREAD

**Issue by mgarciaQ76** [solop-develop/vue-1.0#2759]
## Bug report

Se detecta en ordenes de venta no está filtrando ok los tipos de documento destino (trae facturas, cobros, etc) en búsqueda avanzada parámetro tipo documento destino
Esto en zk se filtra ok
Detectado en instancia 24812  (también se reporta en 24810)

#### Steps to reproduce

1. Ingresar en ordenes de venta
2. Intentar filtrar por tipo documento destino

#### Screenshot or Gif（截图或动态图）

![tipo de documento destino en consulta avanzada de ov vue](https://github.com/user-attachments/assets/9387adc5-e1c9-48d3-8c7d-cf21f931a51c)
![tipos documentos ov en zk](https://github.com/user-attachments/assets/9cf64c04-629e-44e9-bb2d-21dcca5e81fb)

#### Expected behavior

Que realice correctamente el filtrado por los tipos de documento orden de venta (como en zk)

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:

 Solop
 Nombre de Implementación:

 ${ADEMPIERE_VERSION} 20231226-1819
 Fecha Versión:

 miércoles, 02 de octubre de 2024, 12:00:00 a. m.
 Número de versión:

 3.9.4
 Versión del Back-End:

 3.8.005-r-17.10-v-1
 Versión del Dictionary RS:

 1.4.9
 Versión del Motor de Reporte:

 1.0.0-dev
 Versión del S3 Gateway RS:

 1.2.7
 Versión del Front-End:

 4.4.017

**Comment by EdwinBetanc0urt** [comment]
En el caso de la búsqueda avanzada se agrego un cambio para omitir las validaciones dinámicas debido al reporte inicial de este issue https://github.com/solop-develop/frontend-core/issues/2428

**Comment by EdwinBetanc0urt** [comment]
Se debe agregar un check al lado de los botones de refrescar/limpiar que indique si `Ver Todos` para omitir las validaciones dinámicas, por defecto debe estar en falso o inactivo.

**Comment by elsiosanchez** [comment]
Solventado en el Siguiente PR https://github.com/solop-develop/frontend-core/pull/2793

**Comment by Ricargame** [comment]
Cambios disponibles a partir de la versión del Front: https://github.com/solop-develop/frontend-core/releases/tag/4.4.018

https://github.com/user-attachments/assets/729cb5fa-0da8-455d-9ed0-3c8b9ccd51af
