### ISSUE TITLE
Acción Aprobar un Flujo de Trabajo desde "Actividades de Flujo de Trabajo" no acciona 

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#2762]
## Bug report

Se intenta aprobar un documento desde la Forma "Actividades de Flujo de Trabajo" pero al darle Aporobado=SI y oprimir el botón de OK no genera ninguna acción, no aprueba el documento.

#### Steps to reproduce

1. Ingresar con Usuario: "victoria" psw "victoria" en instancia 24810
2. seleccionar Rol "Administrador"
3. Entrar a "Actividades de Flujo de Trabajo" 
4. seleccionar ultimo registro
5. intentar acercar al registro (no acciona)
6. Intentar aprobar con el check (no acciona)

#### Screenshot or Gif（截图或动态图）
![image](https://github.com/user-attachments/assets/bf16546f-ba8e-4e8b-a43d-736b4feeb360)

#### Other relevant information
- Instancia: 24810
- Web Browser:
- Node.js version:
- adempiere-vue version:  4.4.017

**Comment by elsiosanchez** [comment]
Esto se solvento en el siguiente PR https://github.com/solop-develop/frontend-core/pull/2791

**Comment by elsiosanchez** [comment]
Cambios disponibles a partir de la versión del Front

https://github.com/solop-develop/frontend-core/releases/tag/4.4.018

https://github.com/user-attachments/assets/70e3cf08-bec9-4736-9b9c-6b506c4aefca
