### ISSUE TITLE
Habilitar generar factura desde recibo en recepción de productos

### ISSUE THREAD

**Issue by mgarciaQ76** [solop-develop/vue-1.0#2764]
## Bug report

Habilitar generar factura desde recibo en recepción de productos (queda el botón inhabilitado al completar recepción)

#### Steps to reproduce

1. [Generar recepción de productos]
2. [Completar e intentar generar factura desde recibo]

#### Screenshot or Gif（截图或动态图）

![generar factura desde recibo inhabilitado boton](https://github.com/user-attachments/assets/98a4281b-aa90-43ec-938e-435bf9af45b7)

#### Expected behavior

Permitir generar factura desde recibo en una recepción estado completo

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:

 Solop
 Nombre de Implementación:

 ${ADEMPIERE_VERSION} 20231226-1819
 Fecha Versión:

 jueves, 03 de octubre de 2024, 12:00:00 a. m.
 Número de versión:

 3.9.4
 Versión del Back-End:

 3.8.005-r-17.12-v-1
 Versión del Dictionary RS:

 1.4.9
 Versión del Motor de Reporte:

 1.0.0-dev
 Versión del S3 Gateway RS:

 1.2.7
 Versión del Front-End:

 4.4.017

**Comment by Ricargame** [comment]
Cambios disponibles a partir de la versión del frontend: https://github.com/solop-develop/frontend-core/releases/tag/4.4.017

https://github.com/user-attachments/assets/a10e52aa-eae9-442a-a5d7-ee3717938975
