### ISSUE TITLE
Reporte de Almacenamiento Simple sale Vacío en VUE

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#2769]
## Bug report

Se intenta obtener el reporte de "Detalle de Almacenamiento Simple" desde VUE y no se ven los datos del reporte correctamente. Sale Vacío 

Desde ZK en cambio se ve ok

#### Steps to reproduce

Instancia: 24810
Rol: Administrador
Orgnización: Distribución
Almacén: Deepósito Central

#### Screenshot or Gif（截图或动态图）

https://github.com/user-attachments/assets/f84a1b8b-a456-4517-821a-a7fd23ba765d

https://github.com/user-attachments/assets/b7482c2f-4df2-4baa-8b62-178903cde736

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:

**Comment by Ricargame** [comment]
Con esta prueba no funciona 

```shell
curl 'http://spdev02.solopapp.com:24814/api/report-engine/reports/1000014?report_type=pdf&filters=[%7B%22name%22:%22M_Warehouse_ID%22,%22operator%22:%22equal%22,%22values%22:1000076%7D]&page_size=15&page_token=1&is_summary=true' --globoff -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:129.0) Gecko/20100101 Firefox/129.0' -H 'Accept: application/json, text/plain, */*' -H 'Accept-Language: es-ES,es;q=0.8,en-US;q=0.5,en;q=0.3' -H 'Accept-Encoding: gzip, deflate' -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiIyMDIyNzM4IiwiQURfQ2xpZW50X0lEIjoxMDAwMDAxLCJBRF9PcmdfSUQiOjEwMDAwMDcsIkFEX1JvbGVfSUQiOjEwMDAwMDIsIkFEX1VzZXJfSUQiOjEwMDEyMTIsIk1fV2FyZWhvdXNlX0lEIjoxMDAwMDc4LCJBRF9MYW5ndWFnZSI6ImVzX01YIiwiaWF0IjoxNzI4NTkxNzEzLCJleHAiOjE3Mjg2NzgxMTN9.Qiu_mwiE6SUEUF5HEBbvcrFD6CdUmfxPCWjAMG964X8' -H 'Origin: http://localhost:9527' -H 'Connection: keep-alive' -H 'Referer: http://localhost:9527/' -H 'Priority: u=0' 
```

**Comment by yamelsenih** [comment]
![image](https://github.com/user-attachments/assets/2210715f-0a4d-4126-8aa4-22ff6506d295)
Hay una columna que está agrupada y también está marcada como suma, esto no le di soporte en la nueva versión, no es muy intuitivo que haga eso. Entre las cosas que tengo por hacer es que las funcionalidades que tenemos de diccionario y dinamismo de reportes sean seguras y esta es una de ellas

**Comment by Ricargame** [comment]
Cambios disponibles a partir de la versión del Front: https://github.com/solop-develop/frontend-core/releases/tag/4.4.018

https://github.com/user-attachments/assets/c6da82f5-b58a-4522-b3fe-0be9f47cbb2a
