### ISSUE TITLE
Campo: Búsqueda > Órdenes de Compra/Venta

### ISSUE THREAD

**Issue by EdwinBetanc0urt** [solop-develop/vue-1.0#277]
Dar soporte al formulario de búsqueda de Órdenes de Compra/Venta

Versión ZK:

https://user-images.githubusercontent.com/20288327/194164696-a6d6d0cc-6ec0-4e21-83ca-13c98add3d85.mp4

**Comment by niclopup** [comment]
Error al abrir buscador de ordenes de venta 

https://user-images.githubusercontent.com/31936815/193285862-68a9281a-0f72-4c05-b359-2f5dce262f1e.mp4

**Comment by EdwinBetanc0urt** [comment]
Esto fue solucionado con los cambios del PR https://github.com/solop-develop/backend/pull/126, actualizado en https://vue-develop.solopcloud.com

**Comment by Ricargame** [comment]
Se visualiza el siguiente error de sql 

https://github.com/solop-develop/frontend-core/assets/78000356/b6dd51d5-cf04-4e68-8f76-dc56b5416ffd

**Comment by niclopup** [comment]
en un reporte se ve ok

![image](https://github.com/user-attachments/assets/ade14dff-4401-4dda-ac43-3069517efa54)

en una ventana da ERROR

![image](https://github.com/user-attachments/assets/67410329-f1db-418b-b274-e21bfb0cdfe9)


https://github.com/user-attachments/assets/f66cce3c-0189-4dcf-b407-9a8224995340

**Comment by Ricargame** [comment]
Cambios disponibles a partir de la versión https://github.com/solop-develop/frontend-core/releases/tag/4.3.2

https://github.com/user-attachments/assets/279c6e40-0f3a-4254-acef-427be9233df0
