### ISSUE TITLE
Cambio de Paginación borra la búsqueda

### ISSUE THREAD

**Issue by yamelsenih** [solop-develop/vue-1.0#2771]
Paso a Paso

- Entra en usuario
- Busca un usuario: Ejemplo `nico`
- Revisa la página (muestra 9)
- Cambia el tamaño de la página a **100**
- Se borra la búsqueda original

Si se intenta buscar otra vez el comportamiento es el mismo, si hay mas de 9 registros nunca voy a poder encontrar el registro número **10**

https://github.com/user-attachments/assets/9148685b-8243-44d7-9150-9001cd1be459

**Nota:** Probado en el ambiente de desarrollo sin patches

**Comment by elsiosanchez** [comment]
Cambios disponibles a partir de la versión del Front

https://github.com/solop-develop/frontend-core/releases/tag/4.4.018

https://github.com/user-attachments/assets/aa337e61-2702-41a7-b4aa-0ceeecaf7c5e
