### ISSUE TITLE
Error 404 al cargar POS

### ISSUE THREAD

**Issue by yamelsenih** [solop-develop/vue-1.0#2772]
Cuando se abre el punto de ventas da un error `404`

https://github.com/user-attachments/assets/3ec2d5cf-c983-42cb-9da5-ba6cb67d29e2

## Paso a Paso

- Entra en el POS
- Al cargar la primera vez se ve el error

- Usuario: `pos`
- Password: `pos`
- Servicio:`dev`

**Comment by Ricargame** [comment]
Cambios disponibles a partir de la versión del Front: https://github.com/solop-develop/frontend-core/releases/tag/4.4.018

https://github.com/user-attachments/assets/89fd0cc8-1115-4788-b2e5-f861bc16ab4d

**Comment by niclopup** [comment]
https://github.com/user-attachments/assets/f4e336c1-c468-4fed-801e-c5cc20411df3

![image](https://github.com/user-attachments/assets/7fca9127-1207-474d-8434-d7b5709ffe0a)
![image](https://github.com/user-attachments/assets/e775bc7b-2b64-4b3e-965b-b84ddb29f462)

**Comment by elsiosanchez** [comment]
https://github.com/solop-develop/frontend-core/pull/2828

**Comment by Ricargame** [comment]
Cambios disponibles partir de la versión del front https://github.com/solop-develop/frontend-core/releases/tag/4.4.020

https://github.com/user-attachments/assets/550bb265-9bfa-430c-9f47-b7e9ba93400b
