### ISSUE TITLE
Acción doble click o Acercar en Balande de Prueba Navegable

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#2776]
Se desea poder generar rápidamente mediante una acción (Acción doble click o Acercar) que se genere un reporte de Balance de Prueba (Trial Balance) para dicha cuenta consideranod el período que se está definido en los parámetros. Esta funcionalidad es igual a como funciona actualmente en ZK

https://github.com/user-attachments/assets/46ef1e4d-ec99-4c76-8801-d5896ec400dc

**Comment by EdwinBetanc0urt** [comment]
Cambios disponibles a partir de la versión del frontend `4.4.022`.

https://github.com/user-attachments/assets/3d000a56-4824-4b7b-ba96-c0a75e4a98de
