### ISSUE TITLE
Proceso de Parámetros sólo aparece la primera vez en Informe Financiero

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#2777]
: Si se dese ejecutrar otro Informe, la ventana de los parámetros no se visualiza más para pedir los filtros lo que no permite utilizar correctamente el informe. Se debería permitir generar tantos reportes como se desee cambiando los parámetros definidos.

https://github.com/user-attachments/assets/11bf29cf-c8ac-4002-ae50-fee6e47e6e8d

**Comment by Ricargame** [comment]
Cambios disponibles a partir de la versión del Front: https://github.com/solop-develop/frontend-core/releases/tag/4.4.018

https://github.com/user-attachments/assets/19a7ad0f-151e-4119-b6e6-86838159d283
