### ISSUE TITLE
Líneas de Asiento desde Ventana del Documento

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#2780]
## Bug report

Se desea pode visualizar de una manera más prolija y concreta los asientos desde las ventanas de los documentos.

Actualmente se está visualizando de esta manera 
![image](https://github.com/user-attachments/assets/cf586e39-c734-44b8-863c-143fe064b11f)

En un reporte se ve asi

![image](https://github.com/user-attachments/assets/e42510d1-67fa-4f55-bfe9-74a7becc38d3)

Diría de ponerle este mismo formato que está en los reportes.
Ver si vale la pena ponerle 1 tamaño más grande tal como se solicitó en los reportes.

Por otro lado, se desea visualizar de una manera más clara el asiento desde la ventana y creo que las siguientes modificaciones podrían ayudar:

1. Ampliar el espacio de mostrar el asiento bajando la barra del scroll horizontal para el final de la página bien abajo.
2. Bajar los botones para la parte bien baja de la ventana
3. Ampliar el ancho de la columna de la cuenta contable
4. Agregar el Nro de cuenta antes del nombre "12110 - Cuentas por Cobrar Comerciales" 

![image](https://github.com/user-attachments/assets/2ae0ed7e-b94a-43de-b35c-2655de0d1f41)

Ej así podría qeudar el ancho de las columnas

![image](https://github.com/user-attachments/assets/1485e48f-3ede-476e-9987-9a8ed5841f3f)

ver como está en ZK que es un poco la idea que sugiero

![image](https://github.com/user-attachments/assets/89886181-c949-41da-8511-5928a83c6da0)

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:

**Comment by EdwinBetanc0urt** [comment]
![imagen](https://github.com/user-attachments/assets/13730a0c-829e-45b6-8a26-3a43b36f4c11)


El punto 4 se corrige con configuración de diccionario de la siguiente manera:
- Iniciar sesión como `Super User`.
- Abrir la ventana `Tabla y Columna`.
- Ir al registro `Fact_Acct` en la pestaña `Tabla`.
- Ir a la pestaña `Columna`.
- Seleccionar el registro `Account_ID`.
- Acercar a la referencia de tabla `Account_ID (Trx)`.
![imagen](https://github.com/user-attachments/assets/90a440f8-0466-48d7-8eb5-2357b6b5df59)
- En la ventana de referencia ir a la pestaña `Validación de Tabla`.
- Marcar el check de `Mostrar Identificadores`.
![imagen](https://github.com/user-attachments/assets/108c27a0-a25c-479c-99ea-536713d4d8f0)
- Reiniciar cache en vue.

Se debe considerar que de esta manera se mostraran los identificadores de la tabla `C_ElementValue`.
![imagen](https://github.com/user-attachments/assets/7c3a68b4-a474-46a3-be65-cbd722d150b2)

Los cuales actualmente estan marcados `Value` con secuencia 1, y `Name` con secuencia 2.
![imagen](https://github.com/user-attachments/assets/eb6a2a61-437a-434f-8286-15e18f96deb5)

**Comment by Ricargame** [comment]
Cambios disponibles a partir de la version del front: https://github.com/solop-develop/frontend-core/releases/tag/4.4.023

https://github.com/user-attachments/assets/bfd89676-482b-4d11-9db6-bd002614ef40

**Comment by niclopup** [comment]
que bueno quedó!

Un detalle nada más, mejor si podemos los importes con dos decimales como están en todos lados. Un dato contable debe ser lo más exacto posible.

Se piuede dejar que siempre muestre dos decimales? así como está en la ventana de importes.
 
![image](https://github.com/user-attachments/assets/ebb2a331-c308-4156-ba87-7e66e876bf98)

**Comment by elsiosanchez** [comment]
Cambios disponibles a partir de la version del front: https://github.com/solop-develop/frontend-core/releases/tag/4.4.024

https://github.com/user-attachments/assets/ddc0559a-b2d0-4a91-b22c-f1469ba4366c

**Comment by niclopup** [comment]
ok en la 24814
