### ISSUE TITLE
Flechita para aumentar detalle en línea de Informe Financiero de Cuenta Contable

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#2782]
Flecha para aumentar detalle que no se comprende lógica.

![image](https://github.com/user-attachments/assets/3ff65e20-d30f-4462-a48e-7de215c0ebab)

Si no tiene nada para aumentar detalle, no debería mostarse ninguna flechita para abajo

Validado con los siguientes parámetros

Instancia 24814
![image](https://github.com/user-attachments/assets/9b61f793-955a-43fd-87ea-66b7562c0d68)

**Comment by Ricargame** [comment]
Cambios disponibles a partir de la versión del Front: https://github.com/solop-develop/frontend-core/releases/tag/4.4.018

![imagen](https://github.com/user-attachments/assets/1c104b4a-7eb0-48b8-b934-790e279902d0)
