### ISSUE TITLE
Color de fondo en líneas de informes financieros sin datos

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#2783]
Color de fondo en líneas de informes financieros igual a las que si tienen elementos con datos dentro 

![image](https://github.com/user-attachments/assets/e5f5ea15-e3b9-49b3-b424-ed5f31072401)

Caso validado con siguientes parámetros:

Instancia 24814
![image](https://github.com/user-attachments/assets/e53ec5ca-4e3f-470a-9244-8f197e711232)

**Comment by Ricargame** [comment]
Cambios disponibles a partir de la versión del Front: https://github.com/solop-develop/frontend-core/releases/tag/4.4.018

![imagen](https://github.com/user-attachments/assets/0dc3f173-d260-4f18-85b0-bdbd43a3d8a1)
