### ISSUE TITLE
Reporte de Informe Financiero utiliza misma ventana que reporte que el Mayor contable

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#2785]
Se genera un Reporte de Balance de Prueba donde se está analizando un dato. Para validarlo se lanza un informe financiero para poder compara rla información.

Se lanza el INforme financiero y cuando devuelve el reporte... el mismo sale en la misma ventana que Mayor contable (Balance de Prueba).

De esta manera hace imposible poder ver un reporte de un Informe financiero y a la vez un Balance de Prueba. 

Esto hay manera de solucionarlo?

https://github.com/user-attachments/assets/716b9551-da3a-44e1-a147-0a8b3d7f67d5

**Comment by EdwinBetanc0urt** [comment]
Cambios disponibles a partir de la versión del frontend `4.4.022` y del motor de reportes `1.0.8`.

https://github.com/user-attachments/assets/e54df576-86df-45a5-8d02-fdcbb07f4eaf
