### ISSUE TITLE
Columnas de Presupuesto opcionales

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#2786]
## Feature request

Habría manera de poder mostrar opcionalmente las columnas de Presupuesto si se define un presupuesto en el campo presupuesto?

Lo que veo es que este reporte que es muy bueno y ágil, no queda muy claro ya que tiene muchas columnas que en muchos casos no se utilizan.

#### Describe the solution you'd like

Estaría bueno agregar la opción así como tiene las columnas de "Mostrar Perído" o "Mostrar acumulado" pero también a todas las columnas que sean referente al presupuesto.

Esto tal vez no es necesario agraegar otro check y lo podemos hacer agregandole la ógiuca a que sólo lo muestre cuando las columnas sean difernte a Null. 

![image](https://github.com/user-attachments/assets/4e634cfd-5c00-4d14-8962-52f309b01d49)

**Comment by Ricargame** [comment]
Cambios disponibles partir de la versión del front https://github.com/solop-develop/frontend-core/releases/tag/4.4.020

https://github.com/user-attachments/assets/c77da2a2-aedf-4008-a347-33b853724c7f

**Comment by niclopup** [comment]
veo qeu se agregó la lógica que las columnas se muestren cuando se seleccione un presupuesto, eso está funcionando correcto.

Ahora el tema es que se deben ocutlar también las columans de "Varianza del Período" , "Varianza" y "% Varianza"

todas estas coilumnas están relacionadas también con el presupuesto.

Sólo deben quedar Período actual y Acumulado YTD


![image](https://github.com/user-attachments/assets/6ad529dd-37fb-4759-9a6b-43f271f4a11d)

**Comment by EdwinBetanc0urt** [comment]
Cambios disponibles a partir de la versión del frontend `4.4.022`.

https://github.com/user-attachments/assets/b5032a47-c922-4a31-92bd-3c082324cc0f
