### ISSUE TITLE
Botones en Búsqueda Avanzada Deberían ser Lista si Tienen Referencia

### ISSUE THREAD

**Issue by Ricargame** [solop-develop/vue-1.0#2795]
#### Screenshot or Gif（截图或动态图

![imagen](https://github.com/user-attachments/assets/eeafbf0d-ff6c-4594-9e48-95bd6ad972d3)

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:

**Comment by Ricargame** [comment]
Cambios disponibles partir de la versión del front https://github.com/solop-develop/frontend-core/releases/tag/4.4.020

![Image](https://github.com/user-attachments/assets/866b7e09-5250-44ea-84c1-4d83c3f14d34)

**Comment by EdwinBetanc0urt** [comment]
Cabe destacar que si no tiene referencia de tabla el campo de botón no se mostrara en la búsqueda avanzada.
