### ISSUE TITLE
Buscador de Productos

### ISSUE THREAD

**Issue by Ricargame** [solop-develop/vue-1.0#2796]
- [x] Eliminar el botón azul de Ok.
![imagen](https://github.com/user-attachments/assets/4c3945b7-7d58-41dc-9ced-c651d1f86f26)

- [x] Al darle doble clic para ver el detalle la `Existencia` sale en `NaN`.

- [ ] solop-develop/frontend-core#176

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:

**Comment by Ricargame** [comment]
Cambios disponibles a partir de la versión del Front: https://github.com/solop-develop/frontend-core/releases/tag/4.4.018

https://github.com/user-attachments/assets/1329bf28-e370-41cd-8a90-3e48c0ee0f95

**Comment by niclopup** [comment]
cierro pero queda un punto. se verá en otra issue
