### ISSUE TITLE
[Bug Report] Error al Abrir el formulario de Socio de Negocio

### ISSUE THREAD

**Issue by elsiosanchez** [solop-develop/vue-1.0#281]
## Bug report
Error al Abrir el formulario de Socio de Negocio
#### Steps to reproduce

1. Abra la ventana Entrega(clientte)
2. Abra el formulario de Orden de Venta
3. Filtre por Socio de Negocio

#### Screenshot or Gif（截图或动态图）

https://user-images.githubusercontent.com/45974454/180855968-dfa2e60b-9c7c-4e9f-bada-8088eaf36150.mp4

#### Other relevant information
- Your OS: Debian
- Web Browser: Chrome
- Node.js version: v 14.0.0

**Comment by niclopup** [comment]
No se puede probar. 

Al intentar seguir los pasos se encuentra un error al buscar una Orden de Venta desde la ventana Entregas (Cliente)

![image](https://user-images.githubusercontent.com/31936815/193181393-35fb7e9a-82b7-4351-b1a0-578fca56c9a9.png)

El error que sale es el siguiente:

`org.postgresql.util.PSQLException: ERROR: column reference "issotrx" is ambiguous Position: 5783, SQL=SELECT COUNT(*) FROM C_Order AS C_Order LEFT JOIN AD_Org AS AD_OrgTrx_ID_AD_Org ON(AD_OrgTrx_ID_AD_Org.AD_Org_ID = C_Order.AD_OrgTrx_ID) LEFT JOIN AD_User AS AssignedSalesRep_ID_AD_User ON(AssignedSalesRep_ID_AD_User.AD_User_ID = C_Order.AssignedSalesRep_ID) LEFT JOIN C_BPartner AS Bill_BPartner_ID_C_BPartner ON(Bill_BPartner_ID_C_BPartner.C_BPartner_ID = C_Order.Bill_BPartner_ID) LEFT JOIN C_BPartner_Location AS Bill_Location_ID_C_BPartner_Location ON(Bill_Location_ID_C_BPartner_Location.C_BPartner_Location_ID = C_Order.Bill_Location_ID) LEFT JOIN AD_User AS Bill_User_ID_AD_User ON(Bill_User_ID_AD_User.AD_User_ID = C_Order.Bill_User_ID) LEFT JOIN C_Charge AS C_Charge_ID_C_Charge ON(C_Charge_ID_C_Charge.C_Charge_ID = C_Order.C_Charge_ID) LEFT JOIN C_Charge_Trl AS C_Charge_ID_C_Charge_Trl ON(C_Charge_ID_C_Charge_Trl.C_Charge_ID = C_Charge_ID_C_Charge.C_Charge_ID AND C_Charge_ID_C_Charge_Trl.AD_Language = 'es_MX') LEFT JOIN C_DocType AS C_DocTypeTarget_ID_C_DocType ON(C_DocTypeTarget_ID_C_DocType.C_DocType_ID = C_Order.C_DocTypeTarget_ID) LEFT JOIN C_DocType_Trl AS C_DocTypeTarget_ID_C_DocType_Trl ON(C_DocTypeTarget_ID_C_DocType_Trl.C_DocType_ID = C_DocTypeTarget_ID_C_DocType.C_DocType_ID AND C_DocTypeTarget_ID_C_DocType_Trl.AD_Language = 'es_MX') LEFT JOIN AD_User AS CreatedBy_AD_User ON(CreatedBy_AD_User.AD_User_ID = C_Order.CreatedBy) LEFT JOIN AD_Ref_List AS DeliveryRule_AD_Ref_List ON(DeliveryRule_AD_Ref_List.Value = C_Order.DeliveryRule AND DeliveryRule_AD_Ref_List.AD_Reference_ID = 151) LEFT JOIN AD_Ref_List_Trl AS DeliveryRule_AD_Ref_List_Trl ON(DeliveryRule_AD_Ref_List_Trl.AD_Ref_List_ID = DeliveryRule_AD_Ref_List.AD_Ref_List_ID AND DeliveryRule_AD_Ref_List_Trl.AD_Language = 'es_MX') LEFT JOIN AD_Ref_List AS DeliveryViaRule_AD_Ref_List ON(DeliveryViaRule_AD_Ref_List.Value = C_Order.DeliveryViaRule AND DeliveryViaRule_AD_Ref_List.AD_Reference_ID = 152) LEFT JOIN AD_Ref_List_Trl AS DeliveryViaRule_AD_Ref_List_Trl ON(DeliveryViaRule_AD_Ref_List_Trl.AD_Ref_List_ID = DeliveryViaRule_AD_Ref_List.AD_Ref_List_ID AND DeliveryViaRule_AD_Ref_List_Trl.AD_Language = 'es_MX') LEFT JOIN AD_Ref_List AS DocStatus_AD_Ref_List ON(DocStatus_AD_Ref_List.Value = C_Order.DocStatus AND DocStatus_AD_Ref_List.AD_Reference_ID = 131) LEFT JOIN AD_Ref_List_Trl AS DocStatus_AD_Ref_List_Trl ON(DocStatus_AD_Ref_List_Trl.AD_Ref_List_ID = DocStatus_AD_Ref_List.AD_Ref_List_ID AND DocStatus_AD_Ref_List_Trl.AD_Language = 'es_MX') LEFT JOIN C_BPartner AS DropShip_BPartner_ID_C_BPartner ON(DropShip_BPartner_ID_C_BPartner.C_BPartner_ID = C_Order.DropShip_BPartner_ID) LEFT JOIN C_BPartner_Location AS DropShip_Location_ID_C_BPartner_Location ON(DropShip_Location_ID_C_BPartner_Location.C_BPartner_Location_ID = C_Order.DropShip_Location_ID) LEFT JOIN AD_User AS DropShip_User_ID_AD_User ON(DropShip_User_ID_AD_User.AD_User_ID = C_Order.DropShip_User_ID) LEFT JOIN AD_Ref_List AS FreightCostRule_AD_Ref_List ON(FreightCostRule_AD_Ref_List.Value = C_Order.FreightCostRule AND FreightCostRule_AD_Ref_List.AD_Reference_ID = 153) LEFT JOIN AD_Ref_List_Trl AS FreightCostRule_AD_Ref_List_Trl ON(FreightCostRule_AD_Ref_List_Trl.AD_Ref_List_ID = FreightCostRule_AD_Ref_List.AD_Ref_List_ID AND FreightCostRule_AD_Ref_List_Trl.AD_Language = 'es_MX') LEFT JOIN AD_Ref_List AS InvoiceRule_AD_Ref_List ON(InvoiceRule_AD_Ref_List.Value = C_Order.InvoiceRule AND InvoiceRule_AD_Ref_List.AD_Reference_ID = 150) LEFT JOIN AD_Ref_List_Trl AS InvoiceRule_AD_Ref_List_Trl ON(InvoiceRule_AD_Ref_List_Trl.AD_Ref_List_ID = InvoiceRule_AD_Ref_List.AD_Ref_List_ID AND InvoiceRule_AD_Ref_List_Trl.AD_Language = 'es_MX') LEFT JOIN C_Order AS Link_Order_ID_C_Order ON(Link_Order_ID_C_Order.C_Order_ID = C_Order.Link_Order_ID) LEFT JOIN AD_Ref_List AS PriorityRule_AD_Ref_List ON(PriorityRule_AD_Ref_List.Value = C_Order.PriorityRule AND PriorityRule_AD_Ref_List.AD_Reference_ID = 154) LEFT JOIN AD_Ref_List_Trl AS PriorityRule_AD_Ref_List_Trl ON(PriorityRule_AD_Ref_List_Trl.AD_Ref_List_ID = PriorityRule_AD_Ref_List.AD_Ref_List_ID AND PriorityRule_AD_Ref_List_Trl.AD_Language = 'es_MX') LEFT JOIN C_Order AS Ref_Order_ID_C_Order ON(Ref_Order_ID_C_Order.C_Order_ID = C_Order.Ref_Order_ID) LEFT JOIN AD_User AS SalesRep_ID_AD_User ON(SalesRep_ID_AD_User.AD_User_ID = C_Order.SalesRep_ID) LEFT JOIN AD_User AS UpdatedBy_AD_User ON(UpdatedBy_AD_User.AD_User_ID = C_Order.UpdatedBy) LEFT JOIN C_ElementValue AS User1_ID_C_ElementValue ON(User1_ID_C_ElementValue.C_ElementValue_ID = C_Order.User1_ID) LEFT JOIN C_ElementValue_Trl AS User1_ID_C_ElementValue_Trl ON(User1_ID_C_ElementValue_Trl.C_ElementValue_ID = User1_ID_C_ElementValue.C_ElementValue_ID AND User1_ID_C_ElementValue_Trl.AD_Language = 'es_MX') LEFT JOIN C_ElementValue AS User2_ID_C_ElementValue ON(User2_ID_C_ElementValue.C_ElementValue_ID = C_Order.User2_ID) LEFT JOIN C_ElementValue_Trl AS User2_ID_C_ElementValue_Trl ON(User2_ID_C_ElementValue_Trl.C_ElementValue_ID = User2_ID_C_ElementValue.C_ElementValue_ID AND User2_ID_C_ElementValue_Trl.AD_Language = 'es_MX') LEFT JOIN C_ElementValue AS User3_ID_C_ElementValue ON(User3_ID_C_ElementValue.C_ElementValue_ID = C_Order.User3_ID) LEFT JOIN C_ElementValue_Trl AS User3_ID_C_ElementValue_Trl ON(User3_ID_C_ElementValue_Trl.C_ElementValue_ID = User3_ID_C_ElementValue.C_ElementValue_ID AND User3_ID_C_ElementValue_Trl.AD_Language = 'es_MX') LEFT JOIN C_ElementValue AS User4_ID_C_ElementValue ON(User4_ID_C_ElementValue.C_ElementValue_ID = C_Order.User4_ID) LEFT JOIN C_ElementValue_Trl AS User4_ID_C_ElementValue_Trl ON(User4_ID_C_ElementValue_Trl.C_ElementValue_ID = User4_ID_C_ElementValue.C_ElementValue_ID AND User4_ID_C_ElementValue_Trl.AD_Language = 'es_MX') LEFT JOIN W_Basket AS W_Basket_ID_W_Basket ON(W_Basket_ID_W_Basket.W_Basket_ID = C_Order.W_Basket_ID) WHERE 1=1 AND ((IsSOTrx='Y' AND DocStatus='CO')) AND C_Order.AD_Client_ID IN(0,11) AND C_Order.AD_Org_ID IN(0,11,12,50000,50001,50007) AND (C_Order.C_Order_ID IS NULL OR C_Order.C_Order_ID NOT IN ( SELECT Record_ID FROM AD_Private_Access WHERE AD_Table_ID = 259 AND AD_User_ID <> 102 AND IsActive = 'Y' )) org.postgresql.util.PSQLException: ERROR: column reference "issotrx" is ambiguous Position: 5783, SQL=SELECT COUNT(*) FROM C_Order AS C_Order LEFT JOIN AD_Org AS AD_OrgTrx_ID_AD_Org ON(AD_OrgTrx_ID_AD_Org.AD_Org_ID = C_Order.AD_OrgTrx_ID) LEFT JOIN AD_User AS AssignedSalesRep_ID_AD_User ON(AssignedSalesRep_ID_AD_User.AD_User_ID = C_Order.AssignedSalesRep_ID) LEFT JOIN C_BPartner AS Bill_BPartner_ID_C_BPartner ON(Bill_BPartner_ID_C_BPartner.C_BPartner_ID = C_Order.Bill_BPartner_ID) LEFT JOIN C_BPartner_Location AS Bill_Location_ID_C_BPartner_Location ON(Bill_Location_ID_C_BPartner_Location.C_BPartner_Location_ID = C_Order.Bill_Location_ID) LEFT JOIN AD_User AS Bill_User_ID_AD_User ON(Bill_User_ID_AD_User.AD_User_ID = C_Order.Bill_User_ID) LEFT JOIN C_Charge AS C_Charge_ID_C_Charge ON(C_Charge_ID_C_Charge.C_Charge_ID = C_Order.C_Charge_ID) LEFT JOIN C_Charge_Trl AS C_Charge_ID_C_Charge_Trl ON(C_Charge_ID_C_Charge_Trl.C_Charge_ID = C_Charge_ID_C_Charge.C_Charge_ID AND C_Charge_ID_C_Charge_Trl.AD_Language = 'es_MX') LEFT JOIN C_DocType AS C_DocTypeTarget_ID_C_DocType ON(C_DocTypeTarget_ID_C_DocType.C_DocType_ID = C_Order.C_DocTypeTarget_ID) LEFT JOIN C_DocType_Trl AS C_DocTypeTarget_ID_C_DocType_Trl ON(C_DocTypeTarget_ID_C_DocType_Trl.C_DocType_ID = C_DocTypeTarget_ID_C_DocType.C_DocType_ID AND C_DocTypeTarget_ID_C_DocType_Trl.AD_Language = 'es_MX') LEFT JOIN AD_User AS CreatedBy_AD_User ON(CreatedBy_AD_User.AD_User_ID = C_Order.CreatedBy) LEFT JOIN AD_Ref_List AS DeliveryRule_AD_Ref_List ON(DeliveryRule_AD_Ref_List.Value = C_Order.DeliveryRule AND DeliveryRule_AD_Ref_List.AD_Reference_ID = 151) LEFT JOIN AD_Ref_List_Trl AS DeliveryRule_AD_Ref_List_Trl ON(DeliveryRule_AD_Ref_List_Trl.AD_Ref_List_ID = DeliveryRule_AD_Ref_List.AD_Ref_List_ID AND DeliveryRule_AD_Ref_List_Trl.AD_Language = 'es_MX') LEFT JOIN AD_Ref_List AS DeliveryViaRule_AD_Ref_List ON(DeliveryViaRule_AD_Ref_List.Value = C_Order.DeliveryViaRule AND DeliveryViaRule_AD_Ref_List.AD_Reference_ID = 152) LEFT JOIN AD_Ref_List_Trl AS DeliveryViaRule_AD_Ref_List_Trl ON(DeliveryViaRule_AD_Ref_List_Trl.AD_Ref_List_ID = DeliveryViaRule_AD_Ref_List.AD_Ref_List_ID AND DeliveryViaRule_AD_Ref_List_Trl.AD_Language = 'es_MX') LEFT JOIN AD_Ref_List AS DocStatus_AD_Ref_List ON(DocStatus_AD_Ref_List.Value = C_Order.DocStatus AND DocStatus_AD_Ref_List.AD_Reference_ID = 131) LEFT JOIN AD_Ref_List_Trl AS DocStatus_AD_Ref_List_Trl ON(DocStatus_AD_Ref_List_Trl.AD_Ref_List_ID = DocStatus_AD_Ref_List.AD_Ref_List_ID AND DocStatus_AD_Ref_List_Trl.AD_Language = 'es_MX') LEFT JOIN C_BPartner AS DropShip_BPartner_ID_C_BPartner ON(DropShip_BPartner_ID_C_BPartner.C_BPartner_ID = C_Order.DropShip_BPartner_ID) LEFT JOIN C_BPartner_Location AS DropShip_Location_ID_C_BPartner_Location ON(DropShip_Location_ID_C_BPartner_Location.C_BPartner_Location_ID = C_Order.DropShip_Location_ID) LEFT JOIN AD_User AS DropShip_User_ID_AD_User ON(DropShip_User_ID_AD_User.AD_User_ID = C_Order.DropShip_User_ID) LEFT JOIN AD_Ref_List AS FreightCostRule_AD_Ref_List ON(FreightCostRule_AD_Ref_List.Value = C_Order.FreightCostRule AND FreightCostRule_AD_Ref_List.AD_Reference_ID = 153) LEFT JOIN AD_Ref_List_Trl AS FreightCostRule_AD_Ref_List_Trl ON(FreightCostRule_AD_Ref_List_Trl.AD_Ref_List_ID = FreightCostRule_AD_Ref_List.AD_Ref_List_ID AND FreightCostRule_AD_Ref_List_Trl.AD_Language = 'es_MX') LEFT JOIN AD_Ref_List AS InvoiceRule_AD_Ref_List ON(InvoiceRule_AD_Ref_List.Value = C_Order.InvoiceRule AND InvoiceRule_AD_Ref_List.AD_Reference_ID = 150) LEFT JOIN AD_Ref_List_Trl AS InvoiceRule_AD_Ref_List_Trl ON(InvoiceRule_AD_Ref_List_Trl.AD_Ref_List_ID = InvoiceRule_AD_Ref_List.AD_Ref_List_ID AND InvoiceRule_AD_Ref_List_Trl.AD_Language = 'es_MX') LEFT JOIN C_Order AS Link_Order_ID_C_Order ON(Link_Order_ID_C_Order.C_Order_ID = C_Order.Link_Order_ID) LEFT JOIN AD_Ref_List AS PriorityRule_AD_Ref_List ON(PriorityRule_AD_Ref_List.Value = C_Order.PriorityRule AND PriorityRule_AD_Ref_List.AD_Reference_ID = 154) LEFT JOIN AD_Ref_List_Trl AS PriorityRule_AD_Ref_List_Trl ON(PriorityRule_AD_Ref_List_Trl.AD_Ref_List_ID = PriorityRule_AD_Ref_List.AD_Ref_List_ID AND PriorityRule_AD_Ref_List_Trl.AD_Language = 'es_MX') LEFT JOIN C_Order AS Ref_Order_ID_C_Order ON(Ref_Order_ID_C_Order.C_Order_ID = C_Order.Ref_Order_ID) LEFT JOIN AD_User AS SalesRep_ID_AD_User ON(SalesRep_ID_AD_User.AD_User_ID = C_Order.SalesRep_ID) LEFT JOIN AD_User AS UpdatedBy_AD_User ON(UpdatedBy_AD_User.AD_User_ID = C_Order.UpdatedBy) LEFT JOIN C_ElementValue AS User1_ID_C_ElementValue ON(User1_ID_C_ElementValue.C_ElementValue_ID = C_Order.User1_ID) LEFT JOIN C_ElementValue_Trl AS User1_ID_C_ElementValue_Trl ON(User1_ID_C_ElementValue_Trl.C_ElementValue_ID = User1_ID_C_ElementValue.C_ElementValue_ID AND User1_ID_C_ElementValue_Trl.AD_Language = 'es_MX') LEFT JOIN C_ElementValue AS User2_ID_C_ElementValue ON(User2_ID_C_ElementValue.C_ElementValue_ID = C_Order.User2_ID) LEFT JOIN C_ElementValue_Trl AS User2_ID_C_ElementValue_Trl ON(User2_ID_C_ElementValue_Trl.C_ElementValue_ID = User2_ID_C_ElementValue.C_ElementValue_ID AND User2_ID_C_ElementValue_Trl.AD_Language = 'es_MX') LEFT JOIN C_ElementValue AS User3_ID_C_ElementValue ON(User3_ID_C_ElementValue.C_ElementValue_ID = C_Order.User3_ID) LEFT JOIN C_ElementValue_Trl AS User3_ID_C_ElementValue_Trl ON(User3_ID_C_ElementValue_Trl.C_ElementValue_ID = User3_ID_C_ElementValue.C_ElementValue_ID AND User3_ID_C_ElementValue_Trl.AD_Language = 'es_MX') LEFT JOIN C_ElementValue AS User4_ID_C_ElementValue ON(User4_ID_C_ElementValue.C_ElementValue_ID = C_Order.User4_ID) LEFT JOIN C_ElementValue_Trl AS User4_ID_C_ElementValue_Trl ON(User4_ID_C_ElementValue_Trl.C_ElementValue_ID = User4_ID_C_ElementValue.C_ElementValue_ID AND User4_ID_C_ElementValue_Trl.AD_Language = 'es_MX') LEFT JOIN W_Basket AS W_Basket_ID_W_Basket ON(W_Basket_ID_W_Basket.W_Basket_ID = C_Order.W_Basket_ID) WHERE 1=1 AND ((IsSOTrx='Y' AND DocStatus='CO')) AND C_Order.AD_Client_ID IN(0,11) AND C_Order.AD_Org_ID IN(0,11,12,50000,50001,50007) AND (C_Order.C_Order_ID IS NULL OR C_Order.C_Order_ID NOT IN ( SELECT Record_ID FROM AD_Private_Access WHERE AD_Table_ID = 259 AND AD_User_ID <> 102 AND IsActive = 'Y' ))`
