### ISSUE TITLE
al crear recepcion desde OC deja en consulta registro diferente al creado

### ISSUE THREAD

**Issue by mgarciaQ76** [solop-develop/vue-1.0#2815]
## Bug report

Al guardar cabezal de recepción, se selecciona crear desde y habilita ventana emergente, se selecciona orden, luego el número de la OC y al volver a la ventana recepción muestra en consulta una recepción distinta a la que se estaba creando, o sea cambia el registro como si volviera a aplicar un filtro predeterminado.
 (se reproduce en 24812 y replica en 24814)

#### Steps to reproduce

1. [Guardar cabezal recepción]
2. [Crear desde orden]
3. [volver al cabezal recepción]

#### Screenshot or Gif（截图或动态图）

https://github.com/user-attachments/assets/e27e6fd2-a5f6-4cc2-a3bf-4576406c50a5

Agrego prueba en la 24814

[23_10_2024, 04_02_19 - Screen - Vídeo sin título.webm](https://github.com/user-attachments/assets/93ce6f52-c5c5-4496-a288-4ef841421897)

#### Expected behavior

Al crear desde, debería volver al cabezal de la recepción que se estaba creando

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:
Instancia 24812
 Solop
 Nombre de Implementación:

 ${ADEMPIERE_VERSION} 20230911-2042
 Fecha Versión:

 viernes, 11 de octubre de 2024, 12:00:00 a. m.
 Número de versión:

 3.9.4
 Versión del Back-End:

 3.9.002-r-17.12-v-2
 Versión del Dictionary RS:

 1.5.1
 Versión del Motor de Reporte:

 1.0.0-dev
 Versión del S3 Gateway RS:

 1.2.7
 Versión del Front-End:

 4.4.018

**Comment by Ricargame** [comment]
Cambios disponibles a partir de la version del front: https://github.com/solop-develop/frontend-core/releases/tag/4.4.023

https://github.com/user-attachments/assets/06de2b9f-38ca-4f65-a9f3-d02f9765be6d
