### ISSUE TITLE
Forma: Búsqueda > Información General

### ISSUE THREAD

**Issue by EdwinBetanc0urt** [solop-develop/vue-1.0#282]
Esta búsqueda aplica a aquellos campos que sean tipo búsqueda que no tengan formas personalizadas establecidas en la clase de `Info.java` https://github.com/adempiere/adempiere/blob/develop/client/src/org/compiere/apps/search/Info.java#L164-L188:
* `C_BPartner`
* `M_Product`
* `C_Invoice`
* `A_Asset`
* `C_Order`
* `M_InOut`
* `C_Payment`
* `C_CashLine`
* `S_ResourceAssigment`

En este caso se visualizara muy similar a una consulta inteligente, contemplando un criterio de búsqueda generado por los campos marcados como identificador, que no sean tipo oscuro, que no sean encriptado, y cuya referencia para visualización sea campos tipo texto.

En la tabla de resultados se visualizan los campos marcados como identificador, que no sean tipo oscuros ni encriptados.

https://user-images.githubusercontent.com/20288327/181053866-06abc957-661a-4894-8bd0-5de0d71dfa3e.mp4

**Comment by niclopup** [comment]
ok, se analizará cada búsqueda por separado. se da por entregada esta issue
