### ISSUE TITLE
Estado de cuenta corriente muestra id de org y no el nombre

### ISSUE THREAD

**Issue by mgarciaQ76** [solop-develop/vue-1.0#2830]
## Bug report

Al emitir estado de cuenta corriente muestra ID de Org y no el nombre
Se reporta en instancia 24812 y 24814

#### Steps to reproduce

1. [Emitir Estado de Cuenta corriente]

#### Screenshot or Gif（截图或动态图）

https://github.com/user-attachments/assets/86fef560-c4a1-470c-b8e8-52402d36a643

#### Expected behavior

Que muestre el nombre de la Org y no el ID

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:

 Solop
 Nombre de Implementación:

 ${ADEMPIERE_VERSION} 20230911-2042
 Fecha Versión:

 viernes, 11 de octubre de 2024, 12:00:00 a. m.
 Número de versión:

 3.9.4
 Versión del Back-End:

 3.9.002-r-17.12-v-2
 Versión del Dictionary RS:

 1.5.2
 Versión del Motor de Reporte:

 1.0.0-dev
 Versión del S3 Gateway RS:

 1.2.7
 Versión del Front-End:

 4.4.018

**Comment by EdwinBetanc0urt** [comment]
El problema era mas complejo, ya que de ser visualizados los campos `Organización` y `Compañía` están definidos como tipo `ID`, por lo que estaría bien que mostrara el entero (identificador) como valor al no no tener nombre o etiqueta de visualización, sin embargo ambos tienen lógicas de visualización `1=2` para que no se muestren, realmente no estaban funcionando las lógicas de visualización, solo lectura y obligatoriedad en los reportes y procesos.

![imagen](https://github.com/user-attachments/assets/2c115b93-bc3b-447d-b936-c3c46ff09097)
