### ISSUE TITLE
Balance de prueba trae datos 5 Veces

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#2836]
## Bug report
Se detecta que el Balance de prueba está mostrando las líneas de datos 5 veces cuando en realidad debería mostrarlo 1 vez.

#### Steps to reproduce

1. sacar balance de prueba con los siguientes parámetros

![image](https://github.com/user-attachments/assets/2f899946-fa0f-4ec6-aa9a-d1fcfcf2f946)

#### Screenshot or Gif（截图或动态图）

![Captura de pantalla 2024-10-17 230118](https://github.com/user-attachments/assets/696b3bbe-df25-42a2-90ab-a3e79c0b79a8)
![Captura de pantalla 2024-10-17 225956](https://github.com/user-attachments/assets/3ed32546-adb6-4949-a8dd-c99f913d9763)
![Captura de pantalla 2024-10-17 225907](https://github.com/user-attachments/assets/bbd56aeb-652b-4528-8752-1ef788b16029)

![Captura de pantalla 2024-10-17 225510](https://github.com/user-attachments/assets/fc0fb1da-e1b5-408e-a001-b1731d3fc858)
![Captura de pantalla 2024-10-17 225414](https://github.com/user-attachments/assets/5e7d85da-bc62-4b6b-80a3-c126212f9ae9)

#### Other relevant information
- instancia: 24814
- Web Browser:
- Node.js version:
- adempiere-vue version:  4.4.020-rc-2

**Comment by Ricargame** [comment]
@yamelsenih 
```shell
curl 'http://spdev02.solopapp.com:24814/api/report-engine/views/1000133?report_type=&filters=[%7B%22name%22:%22C_AcctSchema_ID%22,%22operator%22:%22equal%22,%22values%22:1000001%7D,%7B%22name%22:%22DateAcct%22,%22operator%22:%22between%22,%22values%22:[%222023-10-02%22,%222023-10-02%22]%7D,%7B%22name%22:%22AD_Org_ID%22,%22operator%22:%22equal%22,%22values%22:1000001%7D,%7B%22name%22:%22Account_ID%22,%22operator%22:%22equal%22,%22values%22:1000047%7D,%7B%22name%22:%22C_BPartner_ID%22,%22operator%22:%22equal%22,%22values%22:1000003%7D,%7B%22name%22:%22PostingType%22,%22operator%22:%22equal%22,%22values%22:%22A%22%7D,%7B%22name%22:%22isShowRetainedEarnings%22,%22operator%22:%22equal%22,%22values%22:false%7D]&page_size=15&page_token=1&print_format_id=1000133&report_view_id=153&is_summary=true' --globoff -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:129.0) Gecko/20100101 Firefox/129.0' -H 'Accept: application/json, text/plain, */*' -H 'Accept-Language: es-ES,es;q=0.8,en-US;q=0.5,en;q=0.3' -H 'Accept-Encoding: gzip, deflate' -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiIyMDIzMzA0IiwiQURfQ2xpZW50X0lEIjoxMDAwMDAxLCJBRF9PcmdfSUQiOjEwMDAwMDEsIkFEX1JvbGVfSUQiOjEwMDAwMTcsIkFEX1VzZXJfSUQiOjEwMDEyMTIsIk1fV2FyZWhvdXNlX0lEIjoxMDAwMDI4LCJBRF9MYW5ndWFnZSI6ImVzX01YIiwiaWF0IjoxNzI5MjYxMzE4LCJleHAiOjE3MjkzNDc3MTh9.r3mALyW3uUaOxQdP1EYOe7oR4uIU3k61RXs_QlncgVk' -H 'Connection: keep-alive' -H 'Referer: http://spdev02.solopapp.com:24814/vue' -H 'Cookie: sidebarStatus=0' -H 'Priority: u=0'
```


https://github.com/user-attachments/assets/31caff19-f8dc-406a-8d20-7989e64f7a90

**Comment by EdwinBetanc0urt** [comment]
Cambios disponibles a partir de la versión del frontend `4.4.022` y del motor de reportes `1.0.8`.

https://github.com/user-attachments/assets/a05e2b16-f456-41a2-8ade-5cee794f5d98
