### ISSUE TITLE
No se ven Tipos de Documento del Punto de venta

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#2841]
## Bug report

Se intenta cambiar el tipo de documento de la orden de venta del pedido que se está creando ene l punto de venta pero no semuestran los tipos de documento que tiene definido la terminal PDV en cuestión

#### Steps to reproduce

1. iniciar sesión con Usuario "pos"
2. Abrir punto de venta "Pos 1"
3. generar una orden de venta 
4. Intentar cambiar el tiop de documento de la orden.

#### Screenshot or Gif（截图或动态图）

![No se ven los tipos de documento de la terminal PDV](https://github.com/user-attachments/assets/b75fcfae-c239-482a-92f1-222bd26b5896)

![Tipos de doc de terminal pdv POS 1](https://github.com/user-attachments/assets/b6d6b5d4-1569-4293-b382-1e7c1d9f6011)

#### Link to minimal reproduction（最小可在线还原demo）

http://spdev02.solopapp.com:24814/vue#/

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:  4.4.020-rc-4

**Comment by elsiosanchez** [comment]
Saludos! @niclopup si cambia el tipo de documento el problema es que los 2 tipos de documento tienene el mismo nombre se recomienda cambiar poner nombre distintos

Aqui te dejo una documentacion sobre este tema
https://stackoverflowteams.com/c/solop/questions/37

https://github.com/user-attachments/assets/1e7a8963-1461-443f-855a-f5f5d517337a
