### ISSUE TITLE
[Bug Report] Agregar Paginacion a Solicitudes

### ISSUE THREAD

**Issue by elsiosanchez** [solop-develop/vue-1.0#2855]
## Bug report
Se requiere agregar paginacion a la vista de (Todas las Solicitudes)
#### Screenshot or Gif（截图或动态图）
![image](https://github.com/user-attachments/assets/f7bac8eb-1f34-4850-bf57-0e38808e560c)

**Comment by EdwinBetanc0urt** [comment]
Cambios disponibles a partir de la versión del frontend `4.4.022`.

https://github.com/user-attachments/assets/37c569fc-43d1-4a9d-beb5-04568ef7be50
