### ISSUE TITLE
Agregar Cargando en forma de Solicitudes

### ISSUE THREAD

**Issue by elsiosanchez** [solop-develop/vue-1.0#2856]
Se requiere Agregar un cargando en las Solicitudes 

https://github.com/user-attachments/assets/bc8de8a8-c20a-4605-a394-1a2a8ecf4a96

**Comment by Ricargame** [comment]
Cambios disponibles partir de la versión del front https://github.com/solop-develop/frontend-core/releases/tag/4.4.020

https://github.com/user-attachments/assets/81052908-c7c4-4a84-ac4c-7d8f74848968
