### ISSUE TITLE
Reporte: Resultado del Proyecto - Linea de reporte más alta para un proyecto

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#2861]
## Bug report

Estoy teniendo un tema raro enel reporte Resultados de proyecto 

Cuando eligo el Proyecto 1780 se ven más altas las líneas.
Cuando elijo el proyecto 1790 se ven más bajas.

#### Screenshot or Gif（截图或动态图）

Proyecto 1780
![image](https://github.com/user-attachments/assets/fee0bf04-963d-4103-b0b4-3c1916e17055)

Proyecto 1790
![image](https://github.com/user-attachments/assets/df83c4e8-deff-4396-98b7-46e55a01e690)

https://github.com/user-attachments/assets/4fedd796-4cfd-4500-ba79-cb2ea48bc961

#### Link to minimal reproduction（最小可在线还原demo）

Reporte:  Resultado de Proyecto
Instancia: http://spdev02.solopapp.com:24815/vue#/

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:  4.4.020

**Comment by EdwinBetanc0urt** [comment]
Cambios disponibles a partir de la versión del frontend `4.4.022`.

https://github.com/user-attachments/assets/63aa618c-0b60-4ea4-bdc4-f42bc3b0881b
