### ISSUE TITLE
No establece el Valor en modo Grilla

### ISSUE THREAD

**Issue by elsiosanchez** [solop-develop/vue-1.0#2865]
![imagen](https://github.com/user-attachments/assets/4627f167-1a43-4b10-b03f-291b2dfa9721)

Da error y no establece el producto

_Originally posted by @EdwinBetanc0urt in https://github.com/solop-develop/frontend-core/issues/2689#issuecomment-2433245846_

**Comment by EdwinBetanc0urt** [comment]
Cambios disponibles a partir de la versión del frontend `4.4.022`.

https://github.com/user-attachments/assets/d65e7604-dda3-4721-9e49-0434cf9fe022
