### ISSUE TITLE
Request a Logo múltiples veces

### ISSUE THREAD

**Issue by yamelsenih** [solop-develop/vue-1.0#2869]
Cuando se selecciona un registro en cualquier ventana o se refrescan los datos se estan haciendo muchas peticiones al logo. Esto es extraño porque en los únicos eventos donde el logo debería cargarse es en el login o al forzar el refresh de la página completa

**En total son 6 request por cada refresh**

https://github.com/user-attachments/assets/82ae72f9-87e7-432b-9486-c882b41abdfa

Las peticiones son
![Image](https://github.com/user-attachments/assets/b149ea61-6044-41e3-b950-fd7df9e915c8)

```curl
curl 'http://0.0.0.0/api/resources/302d30ee-741f-480a-9e52-4ffc4b9bcbe0/client/attachment/ad_clientinfo/1000001/logo_id/logo_id.png' \
  -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36' \
  -H 'Referer: http://0.0.0.0/vue' \
  --insecure
```

```curl
curl 'http://api.adempiere.io:9000/adempiere/302d30ee-741f-480a-9e52-4ffc4b9bcbe0/client/attachment/ad_clientinfo/1000001/logo_id/logo_id.png?X-Amz-Signature=05543718fe7e1f9a2bc2be6617c34a2ff7318759b84124b12271d12bd829e205&X-Amz-Date=20241024T131929Z&X-Amz-Credential=adempiere%2F20241024%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Expires=604800&X-Amz-SignedHeaders=host' \
  -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36' \
  -H 'Referer: http://0.0.0.0/'
```

**Comment by EdwinBetanc0urt** [comment]
Cambios disponibles a partir de la versión del frontend `4.4.022`.

https://github.com/user-attachments/assets/2a7782cb-6ee1-462c-a7ca-92d6c81d5afe
