### ISSUE TITLE
Flujo de Trabajo > Actividades del Flujo de Trabajo > Lista

### ISSUE THREAD

**Issue by elsiosanchez** [solop-develop/vue-1.0#288]
Hola, actualmente en el dashboard de ADempiere existe un acceso directo a las actividades del flujo de trabajo, en el cual el usuario tendrá acceso a las actividades realizadas en un flujo de trabajo
Ejemplo:

https://user-images.githubusercontent.com/45974454/181571120-f1960d09-6ed7-439e-9d23-15868b9fd789.mp4

**Comment by elsiosanchez** [comment]
https://user-images.githubusercontent.com/45974454/181571424-cc5ec8c5-6f99-4e96-a6f9-3468551c7346.mp4

**Comment by niclopup** [comment]
OK muy bueno!

**Comment by niclopup** [comment]
Muy bueno como se visualiza!

sólo encontré un detalle, el diseño en el caso que verifique con mi resolución, quedó solapado el Flujo con la bitácora de cambios

![image](https://user-images.githubusercontent.com/31936815/195370157-03713a63-cbd4-4594-afa5-116d7a9aac76.png)

**Comment by EdwinBetanc0urt** [comment]
El detalle visualización del diagrama con la bitácora ya esta resuelto

https://user-images.githubusercontent.com/45974454/196772173-744c1d30-45dd-434e-9728-2e6add255d2f.mp4
