### ISSUE TITLE
Control guardar cambios en ventana antes de procesarlo

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#2882]
## Feature request

Actualmente si se tiene cambios sin guardar y se completa el documento, el mismo se completa sin antes guardar los cambios. 

#### Describe the solution you'd like

En este caso se podría controlar para avisar que primero guarde los cambios antes de completar.

**Comment by EdwinBetanc0urt** [comment]
Cual seria el flujo? 
1. Guardar los cambios automáticamente antes de mandar a procesar.
2. Pedir guardar los cambios para procesar, como al cerrar la ventana cuando existen cambios.
3. Ocultar/Deshabilitar el botón de acciones de documento.

**Comment by Ricargame** [comment]
Cambios disponibles a partir de la versión del frontend: https://github.com/solop-develop/frontend-core/releases/tag/4.4.025

https://github.com/user-attachments/assets/c747f9b6-1549-4f7f-a393-332ba43464ca
