### ISSUE TITLE
Error Reportes - luego de acercar registro y cerrar ventana se va el reporte 

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#2891]
## Datos de Sesión
- Compañía: Solop
- Organización: JO Instalaciones
- Rol: Constructora - Admin
- Puerto: 24815
- Versión:  4.4.020
- Host / Servidor: SPDEV02
- Opción de Menú: Detalle de transacciones

### Parámetros

1. Proyecto: 1790

### Print de Pantalla o Video

https://github.com/user-attachments/assets/0909f593-0d09-4368-8b5e-9c520d3197cb

**Comment by EdwinBetanc0urt** [comment]
Una forma rápida de replicarlo era dándole clic derecho y actualizar en la vista del visor de reportes. 


https://github.com/user-attachments/assets/768751e1-5a1f-46bc-8cd9-d6321d859191



Cambios disponibles a partir de la versión del frontend `4.4.022` y del motor de reportes `1.0.8`. 
https://github.com/user-attachments/assets/1f967d25-f059-4961-96d6-47c064b05e91
