### ISSUE TITLE
Nombre del informe financiero generado

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#2913]
## Feature request

Actualmente no se puede ver que nombre del informe financiero se lanzó lo que puede generar confusión. no hay manera de saberlo. 

![image](https://github.com/user-attachments/assets/efdd8413-c4ad-4e6f-9f82-637ec5262ea8)

En ZK se podía ver sólo desde el PDF.

![image](https://github.com/user-attachments/assets/70744f54-1a4d-40cf-80f6-582e8064e1bd)

#### Describe the solution you'd like

Se ocurre alguna manera de poder mostrarlo?

sería ideal acá:
![image](https://github.com/user-attachments/assets/a5d0f9cd-c9b3-4640-86c7-a1607d8d9dc8)

**Comment by Ricargame** [comment]
Cambios disponibles a partir de la version del front: https://github.com/solop-develop/frontend-core/releases/tag/4.4.023

https://github.com/user-attachments/assets/49ab90d3-a779-4074-a7de-608948c1e281
