### ISSUE TITLE
muchos ceros después de la coma en Balance de prueba Navegable

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#2914]
## Datos de Sesión
- Compañía: Solop
- Rol: Administrador
- Puerto: 24814
- Versión: last
- Host / Servidor: spdev02
- Opción de Menú: Balance de prueba navegable

Debería ser por defecto 2 ceros nada más

### Print de Pantalla o Video

![image](https://github.com/user-attachments/assets/d6fc02f1-4e89-4cb2-acaf-6cfa91f034a9)

**Comment by Ricargame** [comment]
Cambios disponibles a partir de la version del front: https://github.com/solop-develop/frontend-core/releases/tag/4.4.023

https://github.com/user-attachments/assets/fbb1bb3a-95eb-4b34-8c7c-05d089058c9d
