### ISSUE TITLE
Pestaña CFE no se muestra en VUE

### ISSUE THREAD

**Issue by nsarlabos** [solop-develop/vue-1.0#2921]
## Breve Descripción
En ventana "Documentos por Cobrar" existe la pestaña "CFE", la cual se muestra correctamente en ZK, pero no así en VUE.

## Datos de Sesión
- Compañía: Agencia SA
- Rol: Administrador
- Puerto: 
- Versión: 
- Host / Servidor: http://spdev02.solopapp.com:24810/vue
- Opción de Menú: Documentos por Cobrar

### Datos del Registro (Si aplica)

1. Nro de Documento: A6260
2. Socio de Negocio: Zara
3. Fecha: 15/10/2024

### Print de Pantalla o Video

![cfe](https://github.com/user-attachments/assets/bfcafa19-9757-42ab-9bd1-c3406f3dc092)

**Comment by Ricargame** [comment]
Cambios disponibles a partir de la version del backend: https://github.com/solop-develop/adempiere-grpc-server/releases/tag/3.10.008

https://github.com/user-attachments/assets/313c3017-2fee-4cee-b7e6-9539a0e83587
