### ISSUE TITLE
Búsqueda rápida en Ventana DxC por de Nro de Factura no busca

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#2927]
## Datos de Sesión
- Compañía: Solop
- Rol: Administrador
- Puerto: 24814
- Versión: 023-rc-5
- Host / Servidor: SPDEV02
- Opción de Menú: Documentos por Cobrar

### Datos del Registro (Si aplica)

1. Nro de Documento: A6245
2. Socio de Negocio: NIKE
3. Fecha:

### Pasos para Reproducir

Se intenta buscar una factura por el nro de factura desdde el buscador rápido pero por alguna razón no está buscando por Nro de Documento? esto sería importante que si permita así es una búsqueda rápida bien ágil para aplicar. 

1. abrir ventana "Documentos por Cobrar"
2. Buscar en el campo de búsqueda rápida con el nro de factura en cuestión. 
3. 

### Print de Pantalla o Video

https://github.com/user-attachments/assets/f00aca34-915b-417f-8e3c-6ed55c51dfb0

https://github.com/user-attachments/assets/82a1db57-d72f-4fbc-afdd-d7656353bafe

**Comment by niclopup** [comment]
Tampoco busca por nombre

https://github.com/user-attachments/assets/a0dff264-d706-4935-aa7d-b0de6654c363

**Comment by Ricargame** [comment]
Cambios disponibles a partir de la versión del Backend: https://github.com/solop-develop/adempiere-grpc-server/releases/tag/3.10.008

https://github.com/user-attachments/assets/04d72ea0-d168-4046-82aa-b98ce2fec46f
