### ISSUE TITLE
[Bug: Report] Reporte Detalle de Orden con acercador duplicado o inexistente en producto.

### ISSUE THREAD

**Issue by EdwinBetanc0urt** [solop-develop/vue-1.0#2928]
## Datos de Sesión
- Compañía: Solop.
- Rol: Administrador.
- Puerto: 24814.
- Versión: 4.4.023.
- Host / Servidor: http://spdev02.solopapp.com:24814/vue
- Opción de Menú: `Detalle de Orden`.

### Parámetros

1. Transacción de Ventas.

### Pasos para Reproducir

1. Abrir reporte de `Detalle de Orden`.
2. Establecer el parametro de transacción de ventas `Si`.
3. Ejecutar.
4. Clic derecho para ver los acercadores sobre la columna producto.

### Print de Pantalla o Video

https://github.com/user-attachments/assets/1224aba0-c2fe-4547-b4d6-0fb70748e011

### Comportamiento Esperado
Debe mostrar solo un acercador no dos.

#### Contexto Adicional
Esto sucede debido a que si bien los acercadores apuntan a la misma ventana, se considera el la transacción de ventas de la ventana mas no del acercador.

![imagen](https://github.com/user-attachments/assets/c549b8c2-88ce-4c9f-88b0-6967087415c6)

**Comment by EdwinBetanc0urt** [comment]
cambios disponibles a partir del frontend https://github.com/solop-develop/frontend-core/releases/tag/4.4.024 y del backend https://github.com/solop-develop/adempiere-grpc-server/releases/tag/3.10.007

https://github.com/user-attachments/assets/071c99a0-97fe-407d-b256-16aed8def4d3

**Comment by Ricargame** [comment]
Cambios disponibles a partir de la version del front: https://github.com/solop-develop/frontend-core/releases/tag/4.4.023

https://github.com/user-attachments/assets/c150b935-662e-4ba7-9983-482dc2c8be5b
