### ISSUE TITLE
no navega desde un campo/entidad desde ventana

### ISSUE THREAD

**Issue by mgarciaQ76** [solop-develop/vue-1.0#2939]
## Breve Descripción

Al intentar navegar desde un campo/entidad, como por ejemplo desde orden de compra al Socio del negocio o al proyecto, no navega y da un error

## Datos de Sesión
- Compañía: 
- Rol:  Administrador
- Puerto: 
- Versión: 
instancia 24815 y 24820 se reporta igual
 Nombre de Implementación:

 ${ADEMPIERE_VERSION} 20231226-1819
 Fecha Versión:

 miércoles, 06 de noviembre de 2024, 01:00:00 a. m.
 Número de versión:

 3.9.4
 Versión del Back-End:

 spuy-0.0.1-rc-6
 Versión del Dictionary RS:

 1.5.2
 Versión del Motor de Reporte:

 1.0.0-dev
 Versión del S3 Gateway RS:

 1.2.7
 Versión del Front-End:

 4.4.023
- Host / Servidor: 
- Opción de Menú: Ejemplo ordenes de compra

### Datos del Registro (Si aplica)

1. Nro de Documento: en todo documento
2. Socio de Negocio:
3. Fecha:

### Pasos para Reproducir

1. [navegar de orden de compra desde el campo SDN o proyecto

### Print de Pantalla o Video

[6_11_2024, 02_07_28 - Screen - Vídeo sin título.webm](https://github.com/user-attachments/assets/7cff5734-21a9-4653-ab00-c8933db92054)

### Comportamiento Esperado

Poder navegar desde los campos de las ventanas a sus entidades

**Comment by Ricargame** [comment]
Cambios disponibles a partir de la versión del frontend: https://github.com/solop-develop/frontend-core/releases/tag/4.4.025

https://github.com/user-attachments/assets/da1b3891-da29-4fe5-8d64-e40871f77827
