### ISSUE TITLE
moneda en líneas no respeta moneda de cabezal

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#2940]
## Datos de Sesión
- Compañía: Solop
- Rol: Administrador
- Puerto: 24814
- Versión: 023
- Host / Servidor: SPDEV02 
- Opción de Menú: Ordenes de Compra

### Pasos para Reproducir

1. crear orden de compra en USD
2. Crear línea. ver moneda antes de guardar
3. ver moneda despues de guardar

### Print de Pantalla o Video

https://github.com/user-attachments/assets/2d10e770-94d2-4145-8acd-8351f65a5da8

**Comment by elsiosanchez** [comment]
Solventado en el siguiente PR #2971 

https://github.com/user-attachments/assets/c4328092-f59a-4c9f-afa7-1cafb5ad5363

**Comment by elsiosanchez** [comment]
Cambios disponibles a partir de la versión del Backend: https://github.com/solop-develop/frontend-core/releases/tag/4.4.024
 
 

https://github.com/user-attachments/assets/4e4093bb-9180-428a-854d-d1c6f53c3189
