### ISSUE TITLE
Ventana: Complementos > Exportar Registros

### ISSUE THREAD

**Issue by elsiosanchez** [solop-develop/vue-1.0#295]
Se Requiere agregar en el menú del panel una forma mas rápida de exportar un registro. En ADempiereZK Primero debe generar un Informe y luego Exportar

https://user-images.githubusercontent.com/45974454/182177565-7b769a8f-9d42-4d55-9d0b-8ab2cf36c81c.mp4

**Comment by elsiosanchez** [comment]
Saludos se agregaron 2 nuevas opciones en el menu del panel 

- Exportar Registro
- Exportar Registros Seleccionados 

#### Screenshot or Gif


https://user-images.githubusercontent.com/45974454/182179035-9f79f5e6-4679-40b6-b85a-8dfa339b8864.mp4

**Comment by niclopup** [comment]
Se selecciona todos los registros de la ventana SDN y se exporta registros en Excel, sólo se exportan los cabezales sin ningún registro

![image](https://user-images.githubusercontent.com/31936815/193182322-2491c3a2-e8cc-4a4e-96d9-1a1cc687361e.png)


![image](https://user-images.githubusercontent.com/31936815/193182241-cad3e28d-2a98-404f-b06e-421aec5790c4.png)


Analizando un poco más lo exportado, veo que exporta un sólo registro que es el que uno está parado.
![image](https://user-images.githubusercontent.com/31936815/193182716-bec88561-9f75-4340-a032-4334ad6b4e24.png)

El tema es que no está funcionando los checks de selección multiple para exportar más de un registro a excel (como normalmente se realiza)

En esta imagen se muestra que tengo seleccionado el SDN "Wood Inc" pero estoy parado sobre el SDN "Store South", como se ve el regisstro que exporto fue "Store South" 

![image](https://user-images.githubusercontent.com/31936815/193182949-48bd5227-0f1f-494b-b02b-084ff8e27ac6.png)


(https://user-images.githubusercontent.com/31936
[Socio del Negocio 2022-09-31 0_11_22.xlsx](https://github.com/solop-develop/frontend-core/files/9680392/Socio.del.Negocio.2022-09-31.0_11_22.xlsx)
[Socio del Negocio 2022-09-31 0_8_22.xls](https://github.com/solop-develop/frontend-core/files/9680393/Socio.del.Negocio.2022-09-31.0_8_22.xls)

**Comment by EdwinBetanc0urt** [comment]
El exportar registros de la ventana se ordena en función del orden de los campos, esta funcionalidad no esta presente en Zk, por ello quizás la diferencia de archivos exportados, ya que el que muestras es el informe del registro, que genera un reporte, y se exporta según el orden del formato de impresión.

En vue actualmente el informe de registros en la ventana no esta soportado, quizás deba agregarse el issue adicional si se requiere el soporte.

**Comment by niclopup** [comment]
Se verifica ok que desde un registro, se puede exportar el mismo desde el botón Exportar Registro, pero si se oprime este proceso habiendo seleccionado varios registros, sólo se exportará el registro donde uno está posicionado.

Ahora si se desea exportar varios registros seleccionados, entonces se deberá utilizar el proceso "Exportar Registros Seleccionados" que exporta correctamente si se seleccionan varios registros en simultáneo. 

![image](https://user-images.githubusercontent.com/31936815/197897131-33cf258b-c15d-4b88-a06a-55c5ef5235d5.png)

La pregunta es @EdwinBetanc0urt entonces por que dejaríamos el proceso de "Exportar Registro"? si se desea exportar sólo uno bastaría con simplemente marcar uno y entonces se exportaría entiendo. no? 

![image](https://user-images.githubusercontent.com/31936815/197896401-381068fd-622e-41d8-982d-bda1689c065f.png)

**Comment by EdwinBetanc0urt** [comment]
Se elimino la duplicidad del exportar registros asociados a la pestañá 

https://user-images.githubusercontent.com/20288327/203546872-8ac7ed01-0e2b-4d91-8dcb-be38ef860370.mp4



Adicionalmente se corrigen 2 errores:
El primero en el nombre de la etiqueta en la columna BE `Expansi&oacute;n LDM` ahora se muestra `Expansión LDM`.
El segundo en el formato de fechas anteriormente `2020-01-22T04:00:00.000Z` ahora `01/22/2020`

Archivo exportado antes de los cambios
[Orden 2022-11-23 20 44 52.xls](https://github.com/solop-develop/frontend-core/files/10075378/Orden.2022-11-23.20.44.52.xls)

Archivo exportado despues de los cambios
[Orden 2022-11-23 21 45 42.xls](https://github.com/solop-develop/frontend-core/files/10075384/Orden.2022-11-23.21.45.42.xls)
