### ISSUE TITLE
Error en importe columna total neto de listado de ordenes completo

### ISSUE THREAD

**Issue by mgarciaQ76** [solop-develop/vue-1.0#2952]
## Breve Descripción

Revisando el listado de ordenes completo se detecta que duplica el importe real. Porque suma el total del proyecto que se muestra en la primera línea. Ocurre tanto en 24815 como en 24814

## Datos de Sesión
- Compañía: Constructora
- Rol:  Administrador
- Puerto: 24815 y 24814
- Versión:  4.4.025-rc-1
- Host / Servidor: 
- Opción de Menú: Listado de órdenes completo

 Nombre de Implementación:

 ${ADEMPIERE_VERSION} 20231226-1819
 Fecha Versión:

 jueves, 07 de noviembre de 2024, 01:00:00 a. m.
 Número de versión:

 3.9.4
 Versión del Back-End:

 3.10.008-rc-1
 Versión del Dictionary RS:

 1.5.2
 Versión del Motor de Reporte:

 1.0.0-dev
 Versión del S3 Gateway RS:

 1.2.7
 Versión del Front-End:

 4.4.025-rc-1

### Parámetros

1. [xxx]
2. [xxx]

### Pasos para Reproducir

En 24814 parámetros: Proyecto 1758 y Proveedor Constructora

1. [Emitir listado de órdenes completo]

### Print de Pantalla o Video

![columna total neto dupplica importe 24814](https://github.com/user-attachments/assets/2845e433-7051-46cc-afed-d598ad15d9bd)

![listado de ordenes completo](https://github.com/user-attachments/assets/d1100479-10f2-4b38-8ae1-293ea1c608cc)

video parámetros y reporte

[8_11_2024, 10_18_13 - Screen - Vídeo sin título.webm](https://github.com/user-attachments/assets/8ab89b2a-891b-49d9-a437-3a9c2bcae06c)

### Comportamiento Esperado

Que sumarice órdenes, pero no el subtotal por proyecto

**Comment by Ricargame** [comment]
Cambios disponibles a partir de la versión del frontend: https://github.com/solop-develop/frontend-core/releases/tag/4.4.025

https://github.com/user-attachments/assets/741f6807-d528-4b01-b9d2-ed7e39f5b9df
