### ISSUE TITLE
[Bug: Report] Motor de Reportes: Alineación de Columnas

### ISSUE THREAD

**Issue by yamelsenih** [solop-develop/vue-1.0#2961]
## Breve Descripción
Al generar reportes con campos del tipo monto, número, entero y cualquier tipo de dato que haga referencia a un número no se está alineando a la derecha. Por definición siempre se deben alinear a la derecha los montos.

## Datos de Sesión
- Compañía: Solop
- Rol: Administrador
- Puerto: N/A
- Versión: N/A
- Host / Servidor: 
- Opción de Menú: Reporte de cualquier tipo usando la funcionalidad de report engine

### Print de Pantalla o Video
![image](https://github.com/user-attachments/assets/894aa572-f6d7-4025-8bb6-40e0cdf75d71)

### Comportamiento Esperado
La alineación de las columnas para los tipos de datos numéricos siempre van a la derecha

**Comment by Ricargame** [comment]
Cambios disponibles a partir de la versión del frontend: https://github.com/solop-develop/frontend-core/releases/tag/4.4.025

https://github.com/user-attachments/assets/0e1e470d-228a-4dab-8790-b605f338b92c
