### ISSUE TITLE
Alineación de Campo de Botón en Ventana

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#2969]
## Feature request

Alineación de Campo de Botón en Ventana

Actualmente se están vienod los botones en las ventanas con una alineación incorrecta, quedando mal cuando ha varios botones uno al lado del otro o bien muy sobre el campo superiori del mismo.

![image](https://github.com/user-attachments/assets/a04d4b91-141a-40f5-9808-913a4ed0d939)

#### Describe the solution you'd like

Se desea que el botón tenga una lógica muy similar a como se visualizan los demás campos, teniendo un despliegue centralizadoo en el espacio del campo.

Al parecer como el botoón no tiene un Título, el mismo queda muy pegado al campo superior. 

Se desea que quede más limpio y separado de los campos tanto arriba como abajo.

**Comment by Ricargame** [comment]
Cambios disponibles a partir de la versión del frontend: https://github.com/solop-develop/frontend-core/releases/tag/4.4.025

![Image](https://github.com/user-attachments/assets/f3afc87f-4391-4b26-b6e8-a68f51fa5cf2)
