### ISSUE TITLE
Flujo de Trabajo > Actividades del Flujo de Trabajo

### ISSUE THREAD

**Issue by EdwinBetanc0urt** [solop-develop/vue-1.0#297]
- [x] https://github.com/solop-develop/frontend-core/issues/288
- [x] https://github.com/solop-develop/frontend-core/issues/470
- [x] https://github.com/solop-develop/frontend-core/issues/471
- [x] https://github.com/solop-develop/frontend-core/issues/812

**Comment by niclopup** [comment]
Ok procesar y reenviar.
No se puede navegar al registro.
