### ISSUE TITLE
POS Agregar campo tipo de persona en el cliente

### ISSUE THREAD

**Issue by elsiosanchez** [solop-develop/vue-1.0#323]
## Bug report
Se requiere Agregar el campo tipo de persona al crear socio de negocio desde el punto de venta 
#### Screenshot or Gif（截图或动态图）
![image](https://user-images.githubusercontent.com/45974454/184638505-ca421c12-de39-458e-89b7-634d3d207ff3.png)

**Comment by niclopup** [comment]
NO se logra abrir un Punto de Venta

**Comment by EdwinBetanc0urt** [comment]
Se pasa al estatus `Por Validar` hasta que se implementen los cambios relacionados al punto de venta a nivel de diccionario y de código fuente de adempiere en solop.

**Comment by yamelsenih** [comment]
Esto ya fue enviado a @rcapecce y queda de parte de el

**Comment by niclopup** [comment]
No se ve el campo de "TIpo de Persona" al crear nuevo Socio del Negocio desde el punto de venta.

También se desearía agregar el campo "Grupo de Socio del Negocio", sería posible?

**Comment by EdwinBetanc0urt** [comment]
El campo tipo de persona es un campo agregado con el proyecto `LVE` especificamente en el xml https://github.com/adempiere/LVE/blob/master/xml/migration/0064_Add_Fields_to_Import_Business_Partner.xml

**Comment by EdwinBetanc0urt** [comment]
Con respecto a lo del campo de `Grupo de Socio del Negocio` toma el grupo que tenga asociado el socio de negocio establecido en el campo `Plantilla Socio de Negocio` de la ventana `Terminal PDV`.

![Screenshot_20221125_112255](https://user-images.githubusercontent.com/20288327/204015598-9d0557ee-d611-42a6-89cb-e8db22fd42c3.png)

![Screenshot_20221125_112934](https://user-images.githubusercontent.com/20288327/204016506-bf73fc5f-efe2-4c92-bf46-6a460862ef90.png)

Por temas de configuración, sobre todo en cuanto a la lista de precios, esquema de descuentos no se agrega el campo `Grupo de Socio` ya que un vendedor puede favorecer un cliente colocando un grupo de socio que tenga precios mas bajos.
