### ISSUE TITLE
[Feature Request] POS: Agregar parámetros del uuid del  punto de venta en todas las peticiones a servicios

### ISSUE THREAD

**Issue by elsiosanchez** [solop-develop/vue-1.0#331]
Agregar parámetro  a los servicios de punto de venta

### _**Servicios**_

- [ ] Crear orden 
- [ ] Orden de actualización
- [ ] Crear línea
- [ ] Línea de actualización
- [ ] Eliminar línea
- [ ] Eliminar pedido
- [ ] Tasa de cambio
- [ ] Agregar pago
- [ ] Actualizar pago
- [ ] Eliminar pago

**Comment by EdwinBetanc0urt** [comment]
Se pasa al estatus `Por Validar` hasta que se implementen los cambios relacionados al punto de venta a nivel de diccionario y de código fuente de adempiere en solop.

**Comment by yamelsenih** [comment]
Esto ya fue enviado a @rcapecce y queda de parte de el

**Comment by EdwinBetanc0urt** [comment]
Esto fue un cambio a nivel técnico. Dare por cerrada esta actividad
