### ISSUE TITLE
[Bug Report] POS Agregar Producto desde el Catalogo

### ISSUE THREAD

**Issue by elsiosanchez** [solop-develop/vue-1.0#332]
## Bug report
No permite agregar un producto desde el catalogo del punto de venta 
#### Steps to reproduce

1. Abra el Punto de Venta
2. Abra el catalogo del punto de venta (Ubicado en el lado derecho)
3. Seleccione un porducto del catalogo

#### Screenshot or Gif（截图或动态图）

https://user-images.githubusercontent.com/45974454/185256904-34c0618f-3c41-4964-9f2f-e6fa962e93e7.mp4

#### Expected behavior
Se requiere agregar el productos desde el panel del catalogo del punto de venta

**Comment by EdwinBetanc0urt** [comment]
Se pasa al estatus `Por Validar` hasta que se implementen los cambios relacionados al punto de venta a nivel de diccionario y de código fuente de adempiere en solop.

**Comment by yamelsenih** [comment]
Esto ya fue enviado a @rcapecce y queda de parte de el
