### ISSUE TITLE
Flujo de Trabajo > Ver Histórico de Flujo de Trabajo

### ISSUE THREAD

**Issue by elsiosanchez** [solop-develop/vue-1.0#333]
Se requiere ver desde las ventana tipo documento el historial del flujo de trabajo del registro o documento actual

### _Gif_

https://user-images.githubusercontent.com/45974454/197059406-01ee2f51-52e0-47e7-9442-dd81626ec824.mp4

### _**Nota**_

También se requiere saber el flujo de trabajo del documento actual

**Comment by niclopup** [comment]
No se ve un ejemplo donde se pueda verificar

No se logra completar una OV desde VUE.

**Comment by EdwinBetanc0urt** [comment]
En la ventana de `Órdenes de Venta` se pueden visualizar el histórico de flujo de trabajo. Si bien se conoce que aun no se pueden completar documentos desde vue, se pueden completar desde el servicio del Zk para efectos de prueba de esta funcionalidad.

https://user-images.githubusercontent.com/20288327/197224940-e0a530ed-fe1f-4f7e-8cf6-ca195ba150ef.mp4

El problema relacionado a completar documentos se detalla en el issue https://github.com/solop-develop/frontend-core/issues/496 como tarea separada.

**Comment by niclopup** [comment]
que diferencia hay entre "Histórico de Cambios" y "Histórico de WF" ?

![image](https://user-images.githubusercontent.com/31936815/198019667-934126ef-83ed-4fef-9442-a4afb3243e0c.png)

No veo diferencia suficiente que amerite una pestaña nueva. Tal vez sería mejor dejar todo en el Histórico de cambios y en todo caso si se desea darle más importancia a los cambios de Estado entonces detallarlos ahí mismo. como por ejemplo detallar aprobaciones y demás que tuvo para completar dicho documento.

**Comment by EdwinBetanc0urt** [comment]
La diferencia se discutió en una reunión, sin embargo para que quede documentado:

El `Histórico de Cambios`, hace referencia cada cambio de ese registro que se registro en la bitácora, sea nuevo valor o edición de viejos valores, y el usuario que hizo dicho cambio, el momento en que se hizo, y ademas de la tabla, el identificador (ID) y el identificador único universal (UUID) del registro.

El `Histórico de Flujo de Trabajo` solo hace referencia a los cambios a nivel de flujo de documentos, donde se ve el nodo del flujo de trabajo, quien autorizo, el mensaje que se genero, y el estatus, que a futuro pueden agregarse información que pueda ser de utilidad relacionada al flujo de trabajo y que no necesariamente tenga relación con el histórico de cambios.

Si bien ambos tienen correlación, y hasta cierto punto dicha información puede verse solo en el histórico, en el histórico de flujo de trabajo la información se presentan de manera distinta y tiene información adicional, se filtra solo en relación a los nodos que se han ejecutado para que un usuario final tenga una forma mas sencilla de ver solo el flujo del documento.
