### ISSUE TITLE
No se define Secuencia automática en Documento

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#382]
## Bug report
Cuando se crea un nuevo documento, se debería definir automáticamente el campo "Document No" o "Value" (según corresponda) según la siguiente secuencia que tenga definida. 

Actualmente no funciona para los Documentos pero tampoco para los Socios del Negocio o Productos cuando en ZK si es definido. 

Al intentar guardar tampoco lo define automáticamente, así podría ser una opción si no se puede definir la Siguiente secuencia como <8000> se mostraba en ZK en el campo antes de guardar.

#### Screenshot or Gif（截图或动态图）
VUE

https://user-images.githubusercontent.com/31936815/188975670-5b5df8d8-56f2-4d93-86a3-796b791329a1.mp4

ZK

https://user-images.githubusercontent.com/31936815/188975645-76fe2a78-bf27-4b68-b871-73686d969eb7.mp4

VUE SDN

https://user-images.githubusercontent.com/31936815/188976314-f909fba9-b33a-4d8e-8434-8683544379ba.mp4

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:

**Comment by EdwinBetanc0urt** [comment]
Se debe agregar soporte a los callouts para corregir este issue.

**Comment by niclopup** [comment]
ok 
![image](https://user-images.githubusercontent.com/31936815/194094446-64c85406-e833-4c68-a946-f63b7002bd58.png)
