### ISSUE TITLE
Búsqueda mono registro no es posible en ventana 

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#385]
## Bug report
No es posible realizar una búsqueda de un registro en una ventana si se está viendo como Mono Registro. Para ello se debe ir a Modo Grilla para ahí si buscarlo.

Se debería poder buscar en ambas vistas. 

#### Screenshot or Gif（截图或动态图）

https://user-images.githubusercontent.com/31936815/188981144-a636513b-6561-4d14-8dcf-6268e195855b.mp4

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:

**Comment by EdwinBetanc0urt** [comment]
@niclopup Se espera una lista de esa búsqueda, por lo que sólo se implementó en el modo Grilla o Multi-Registro, para visualizar la lista de resultados que coincide con la búsqueda.

**Comment by EdwinBetanc0urt** [comment]
Los cambios están disponibles para pruebas:

https://user-images.githubusercontent.com/45974454/197269898-5f8b4765-c11a-4029-aa73-0d10156bd379.mp4
