### ISSUE TITLE
Búsqueda de SDN desde Ventana transaccional no controla Transacción de Ventas Y/N

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#386]
## Bug report
Al crear una Orden de Compra, si se busca un Socio del Negocio desde el botón, no está filtrando correctamente entre "Transacción de Ventas" Y/N del documento origen que lo está llamando.

#### Screenshot or Gif（截图或动态图）
En el ejemplo se ve como se permite ver un SDN que es sólo Cliente para definir en una Orden de Compra

https://user-images.githubusercontent.com/31936815/188982266-aa60cc46-3547-444e-bcb0-03851e3b3efc.mp4

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:

**Comment by elsiosanchez** [comment]
Corregido en el Sigueinte #397 https://vue-develop.solopcloud.com/
