### ISSUE TITLE
No se ve Cantidad de Registros por página

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#387]
## Bug report
Actualmente el nro de Registros que se define abajo a la derecha en cada página no aclara cuantos registors o que nro se está visualizando actualmente

![image](https://user-images.githubusercontent.com/31936815/188983480-9c1a5029-09de-413d-9ea7-364b5d9e426f.png)

ZK

En ZK definia el nro del Registro de inicio de la página que está mostrando.

![image](https://user-images.githubusercontent.com/31936815/188984253-e85cc472-dc7e-443d-860c-2a1f7054f255.png)

#### Steps to reproduce

1. [xxx]
2. [xxx]
3. [xxxx]

#### Screenshot or Gif（截图或动态图）

https://user-images.githubusercontent.com/31936815/188984476-ae4060dc-c266-4383-a382-0605ac4f7ae6.mp4

**Comment by EdwinBetanc0urt** [comment]
Cambios disponibles en https://vue-develop.solopcloud.com, la selección queda alineada a la izquierda y registros en la pagina, total de registros y números de paginas quedan alineados a la derecha.

https://user-images.githubusercontent.com/20288327/192366999-a6a835f7-af44-4728-ac9e-e3a8578c5130.mp4
