### ISSUE TITLE
Seleccionar un SDN poniendo el código + Tab o Enter no funciona

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#388]
## Bug report
Si se desea definir un SDN en una Orden de Compra simplemente digitando el Código Exacto (EJ "N101") y poniendo tabulador o enter, no se selecciona el SDN automáticamente. Para que se seleccione se debe esperar a que aparezca el mimso en la lista desplegable debajo del campo o bien, hacer click en el botón de SDN para seleccionar uno desde la Forma de Selección SDN.

Esto no permite una creación ágil de Documentos. Entiendo que debe pasar lo mismo para los Productos.

Además, tuve problemas para que aparezca la lista desplegable debajo del campo. Aparece una vez pero luego le cuesta aparecer y queda cargando. (ver ejemplo de OV)

#### Screenshot or Gif（截图或动态图）

https://user-images.githubusercontent.com/31936815/188985812-5e806ecb-0262-47f2-ab67-de571486e283.mp4

https://user-images.githubusercontent.com/31936815/188986460-35bd22b5-f03a-4beb-962a-cf37e17a008f.mp4

https://user-images.githubusercontent.com/31936815/188986626-cbc51bbf-2f31-4186-833b-f588fd10aa19.mp4

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:

**Comment by elsiosanchez** [comment]
Saludos @niclopup esto ya se solvento en el siguiente PR [#289](https://github.com/solop-develop/frontend-default-theme/pull/289) y ya esta actualizado el servicio

https://user-images.githubusercontent.com/45974454/191821537-a89a3aca-502d-4af9-a294-7298c8496c31.mp4

Nota
El enter establece el producto solo cuando solo hay un registro en la lista y si consigue el registro

**Comment by niclopup** [comment]
Se confirma que si se espera a que aparezca el registro abajo del campo y se da "enter", el registro se define correctamente. Ahora entiendo que esto es muy lento para generar documento y seleccionar registros agilmente. 

https://user-images.githubusercontent.com/31936815/195373128-781d66e3-36ae-437f-a57c-c287586b34d3.mp4

Hay alguna manera que se pueda evitar la búsqueda si para el valor definido sólo existe un único registro que cumpla con dichos caracteres? si se escribe el nombre exacto y da enter, la idea es no esperar a que se cargue la lista de abajo del campo. asi se da más velocidad.

**Comment by EdwinBetanc0urt** [comment]
Se soluciono evaluando la cantidad de registros, si la cantidad es solo un registro establecerá los valores en el campo, por lo que se puede escribir el valor, y continuar editando otros campos

https://user-images.githubusercontent.com/20288327/197288526-ee5d5a83-42d3-49fb-8c9b-a78432a7cd5b.mp4
