### ISSUE TITLE
Búsqueda de Producto con Errores

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#391]
## Bug report

La búsqueda de productos tiene muchos errores. NO encontré un Paquete que maneje la "Búsqueda de Producto por eso lo defino en una nueva Issue-

Según lo conversado con Edwin en una reunión donde se entregó el buscador de Producto se acordó definir los mismos Parámetros que campos se muestran en las columnas. Esto con la idea de que siempre fueran POCOS y los más importantes:

- Código
- Nombre
- Categoría
- Tipo de Producto
- Alguno más que se me olvide

Actualmente los parámetros no cumplen con esto y además hay muchos definidos como Obligatorio cuando no debería definirse ninguno como obligatorio.

El parámetro "activo" está y por defecto en "N" lo cual no es muy lógico. Creo que no debería ni mostrarse como parámetro y siempre filtrar por Productos Activos=SI

Además de ello, no es posible seleccionar ningún producto. siempre aparece un cartel como "Prohibido" cuando se pasa el mouse por arriba.

Parámetros:
![image](https://user-images.githubusercontent.com/31936815/188990568-8905a1f8-f2b4-49f1-bc27-e61f30825e3c.png)

#### Steps to reproduce

1. Crear una OV y Guardarla
2. Crear una Línea e intentar elegir un producto desde el buscador de Producto

#### Screenshot or Gif（截图或动态图）

https://user-images.githubusercontent.com/31936815/188990424-6ac2b966-9a49-4bf0-8c58-69c109d5f4c5.mp4

**Comment by EdwinBetanc0urt** [comment]
Se ajusto el formulario de búsqueda de producto para que muestre solo los campos de texto, el cambio esta disponible para pruebas en https://vue-develop.solopcloud.com 

https://user-images.githubusercontent.com/20288327/192364860-55e8b647-6536-4f3b-be08-3cadb614ced3.mp4
