### ISSUE TITLE
Botón guardar no se ve en cabezal hasta que se pueda guardar un registro

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#392]
## Bug report
El botón Guardar del cabezal de la Orden de Venta sólo aparece cuando se tienen todos los campos obligatorios completos, es decir cuando ya se puede guardar un Registro. Ahora esto dificulta al usuario ya que no sabe que hacer si es que no ve el campo obligatorio que le falta definir, al no tener el botón de guardar, no entiende que debe hacer para seguir el proceso. 

Entiendo que debería aparecer siempre el botón de guardar, tal vez si no se puede guardar dejar como sólo lectura o mejor aún, si se oprime dar el error que está faltando un campo completar.

#### Screenshot or Gif（截图或动态图）

https://user-images.githubusercontent.com/31936815/188993599-a5881dbb-058d-4eee-9538-1cf351deb42b.mp4

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:

**Comment by EdwinBetanc0urt** [comment]
Se ha implementado así para hacerlo más limpio y evitar una botonera con acciones deshabilitadas en su mayoría, de manera que sólo aparece lo que está disponible, de otro modo tendríamos que colocar el botón de refrescar y borrar aunque sea un registro nuevo.

**Comment by EdwinBetanc0urt** [comment]
Se agrega el comportamiento solicitado, además de que si esta marcado en la configuración el auto-guardado, no muestra que campos faltan por ser llenados a menos que el botón de `Guardar` sea pulsado, ya que en ocasiones en ventanas con muchos campos obligatorios era incomodo el mensaje.


https://github.com/solop-develop/frontend-core/assets/20288327/9e0e694f-0bb4-42b4-b63d-34c8906ba22d
