### ISSUE TITLE
Buscador de Cuentas con muchas Columnas 

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#402]
## Bug report

El buscador de cuentas en la ventana de definición de Elementos Contables no está definiendo las columnas igual a los parámetros de búsqueda definidos, sino que agrega todas las columnas de la tabla C_ElementValue

Como se definió, en todas las ventanas se definirá las columnas según los campos definidos como filtros.

![image](https://user-images.githubusercontent.com/31936815/191591938-0b357ac6-93e3-433c-9b8a-8f50c4e8461f.png)

https://user-images.githubusercontent.com/31936815/191592783-08d1d5c1-820b-4698-8312-081598229634.mp4

#### Steps to reproduce

1. [xxx]
2. [xxx]
3. [xxxx]

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:

**Comment by EdwinBetanc0urt** [comment]
El formulario se ajusto, cambios disponibles en https://vue-develop.solopcloud.com

https://user-images.githubusercontent.com/20288327/192365998-6978ef13-c4bf-47da-93e8-eca22302857d.mp4
