### ISSUE TITLE
Problema al definir Cuentas Contables en Producto

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#403]
## Bug report

Se encuentran errores al intentar definir una cuenta contable en un producto.

Al navegar del Cabezal del Producto a la pestaña de "Contabilidad" no se encuentra correctamente el registro. Luego refrescando se logra ver bien las cuentas definidas.

Luego se intenta seleccionar una cuenta pero se hace dificil: 

Ver GIF:

https://user-images.githubusercontent.com/31936815/191593717-b0c2718b-dfd8-4366-a090-fbf127e380db.mp4

**Comment by EdwinBetanc0urt** [comment]
Este problema ya fue solucionado actualmente funcionando en https://vue-develop.solopcloud.com

https://user-images.githubusercontent.com/20288327/192360793-44894246-e435-4101-8911-4fa34748d181.mp4

**Comment by niclopup** [comment]
No funciona la búsqueda de Cuentas al querer aplicar un Filtro. 

Se desea buscar por ejemplo con el nro 4, todas las cuentas que COMIENZAN con el 4. Ahora sólo trae nro exacto y no debe ser así. 

Además se intenta buscar por nombre y no muestra la cuenta (Trade)

https://user-images.githubusercontent.com/31936815/195190896-68587d42-7917-4617-846d-d8d44f1d0735.mp4

**Comment by EdwinBetanc0urt** [comment]
Para búsquedas con coincidencias se utiliza el `%`, si se quieren todas las coincidencias que comienzan con el valor `4` seria `4%`

**Comment by niclopup** [comment]
ok ahi si se encuentra. 
No me parece muy práctico siempre tener que agregar el % pero ok
