### ISSUE TITLE
No se puede Seleccionar SDN en OV

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#404]
## Bug report

Se intenta generar una nueva OV pero no se puede definir un SDN de ninguna manera

https://user-images.githubusercontent.com/31936815/191595536-cc658cc9-ff2c-4149-a0a1-e32941ac109e.mp4

**Comment by EdwinBetanc0urt** [comment]
Saludos, este problema esta resuelto en https://vue-develop.solopcloud.com por favor revisar que todo este ok y cerrar el issue.

**Comment by niclopup** [comment]
sigue con error, no se ven SDN desde el buscador desde una ventana de documento

**Comment by EdwinBetanc0urt** [comment]
El error fue corregido, listo para pruebas
