### ISSUE TITLE
Se crea nuevo producto y pestañas hijas sigue referenciada a otro producto

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#423]
## Bug report
Se crea nuevo producto y no genera ID al guadar ni se relaciona correctamente con su pestaña HIJA.

Se crea un nuevo producto, se completa el Código y el Nombre y se oprime "Guardar". se guarda el registro pero al bajar a su pestaña hija, no se actualiza la referencia con el Nuevo Producto lo que hace dudar que esté correctamente creado.

Además, se intenta verificar con los ID del Nuevo producto creado y no se logra ya que no se ve ningún id en su 

https://user-images.githubusercontent.com/31936815/193296206-5f2c67c9-1565-4ca5-a834-1f2255716fce.mp4

Recién luego de darle Actualizar y un ratito despues aparece el ID

![image](https://user-images.githubusercontent.com/31936815/193296774-48074549-5083-4ce8-abca-8c6c26830d55.png)

Pero sigue referenciada a un producto incorrecto

![image](https://user-images.githubusercontent.com/31936815/193296942-d08e9fa7-b03d-417a-864c-199b465c2430.png)

Se intenta crear uno nuevo y la auditoría se confirma que no actualiza bien y las Pestañas hijas siguen mal

https://user-images.githubusercontent.com/31936815/193297679-c1754890-c54e-40e3-add9-1d5f8c75fd3f.mp4

#### Steps to reproduce

1. [xxx]
2. [xxx]
3. [xxxx]

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:

**Comment by EdwinBetanc0urt** [comment]
Adicionalmente a este problema reportado, se corrige que en la pestaña LDM el campo producto se visualiza en solo lectura.


https://user-images.githubusercontent.com/20288327/194091079-e0401970-84df-4fab-931a-1d1a6cd44c5e.mp4
