### ISSUE TITLE
Mejorar visualización de Reportes en HTML

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#425]
## Feature request

La vista en HTML en VUE no logra lo que ahora si logra ZK en referencia a la claridad de la información presentada en los reportes. 

Dentro de las características que no presenta en VUE podemos encontrar:

1. Mostrar celdas entre los datos o líneas para lograr una mejor comprensión de las líneas 
2. Resaltar las Agrupaciones con una línea más gruesa
3. Resaltar las sumarizaciones con Negrita y un color diferente en lo posible
4. Lograr navegar a los registros con ID

https://user-images.githubusercontent.com/31936815/193326811-66819c2b-5b9c-4ff2-8d3d-a0af8c29b4e2.mp4

**Comment by niclopup** [comment]
En realidad esta issue refiere a varios puntos más que los que se hicieron.

Si bien mejoró sustancialmente la vista HTML, aún faltan todas las acciones.
Cómo dices de hacer?

**Comment by EdwinBetanc0urt** [comment]
Se agregaron nuevos issues detallando las diferentes actividades, enlazadas al issue https://github.com/solop-develop/frontend-core/issues/56

Entre ellos el acercar a registros.

**Comment by EdwinBetanc0urt** [comment]
@niclopup el alcance de este issue se cumplió? de ser así por favor cerrar y dar por entregado. Considerando que las "acciones" faltantes se detallan como issues separados.
