### ISSUE TITLE
Reporte: Ejecución > Check de Resumen

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#426]
## Feature request

Actualmente no se permite ver un Reporte con la opción de Resumen "Summary" que si permite en ZK

![Summary](https://user-images.githubusercontent.com/31936815/193327478-8d434e31-acb7-4e5b-9f69-9294f608ad2b.png)

**Comment by EdwinBetanc0urt** [comment]
Se agregará con un panel a la derecha de los reportes para visualizar, formato de impresión, vista de informe, tipo de reporte, sumario, y parámetros.

Esto con la finalidad de enviar una sola petición al servidor, ya que actualmente si se quiere una combinación entre un tipo de reporte, vista de informe y un formato de impresión se debe esperar a que genere primero el reporte con el tipo seleccionado, generarlo nuevamente con la vista de informe y luego volver a generarlo con el formato de impresión a seleccionar, haciendo 3 peticiones y con tiempos de espera entre cada uno.

**Comment by niclopup** [comment]
https://user-images.githubusercontent.com/31936815/194339557-8e299987-1dfe-442f-a403-062d3217b6f9.mp4


https://user-images.githubusercontent.com/31936815/194339566-d5dd86f3-e3da-46bc-8646-c18259dec1a2.mp4
