### ISSUE TITLE
POS: No Editar el Socio de Negocio Plantilla

### ISSUE THREAD

**Issue by MarianaGallardo** [solop-develop/vue-1.0#435]
Se requiere colocar sólo lectura en el PDV al socio de negocio plantilla para que el mismo no sea editado por los usuarios. Actualmente, los usuarios pueden editar la información del socio de negocio plantilla y ésto genera errores en próximos registros debido que los crea según la configuración que tenga dicha plantilla.

![Screenshot 2022-10-03 12 12 24 PM](https://user-images.githubusercontent.com/44775211/193627015-37a2a0a1-159f-4b33-afcd-95431540aba8.png)

**Comment by EdwinBetanc0urt** [comment]
Se debe validar si el ` uuid / id / valor ` del socio de negocio de la `Orden de Venta` es igual al socio de negocio plantilla establecido en el `Terminal PDV`, deshabilitar la opción de editar cliente.

**Comment by MarianaGallardo** [comment]
El 13 de octubre se confirmó éste requerimiento. Se procede a cerrar!

**Comment by yamelsenih** [comment]
Esto ya está corregido y está en manos de @rcapecce
