### ISSUE TITLE
POS Columna Impuesto cuando es Exento

### ISSUE THREAD

**Issue by MarianaGallardo** [solop-develop/vue-1.0#436]
Existe un cliente donde el Idendificador de Impuesto está como ¨E¨, entonces en el punto de venta en la columna impuesto, cuando es exento, muestra un **_NaN%_** se requiere dar soporte para que no muestre el NaN% debido que en el Identificador de Impuesto, puede variar la información que se ingrese en ese campo. 

![Screenshot 2022-10-04 1 57 34 PM](https://user-images.githubusercontent.com/44775211/193892626-57b3e532-6096-4b4b-b0a0-50009961237b.png)
![Screenshot 2022-10-04 1 57 47 PM](https://user-images.githubusercontent.com/44775211/193892631-78924b1a-3fa4-4048-b949-34f7b61bf495.png)

**Comment by EdwinBetanc0urt** [comment]
Se pasa al estatus `Por Validar` hasta que se implementen los cambios relacionados al punto de venta a nivel de diccionario y de código fuente de adempiere en solop.

**Comment by MarianaGallardo** [comment]
El 13 de octubre se confirmó éste requerimiento. Se procede a cerrar!

**Comment by yamelsenih** [comment]
Esto ya está en manos de @rcapecce
