### ISSUE TITLE
Forma: Búsqueda > Producto

### ISSUE THREAD

**Issue by EdwinBetanc0urt** [solop-develop/vue-1.0#440]
Soporte al formulario de búsqueda de producto como campo

Versión ZK:

https://user-images.githubusercontent.com/20288327/194159792-be5cf0fe-c39d-4d69-ba2e-419780615b7c.mp4

Versión Vue:

https://user-images.githubusercontent.com/20288327/194162115-2e96b7b1-c469-4030-9c35-3d9c2a3e8e41.mp4

**Comment by EdwinBetanc0urt** [comment]
Disponible para pruebas en https://vue-develop.solopcloud.com

**Comment by niclopup** [comment]
Se ve bien el buscador, pero si se intenta aplicar un filtro según Código o Nombre no se muestra ningún registro


https://user-images.githubusercontent.com/31936815/195185100-27ff588c-07b0-422c-9ed3-6b7545a52431.mp4

**Comment by EdwinBetanc0urt** [comment]
Aplica lo mismo que el buscador de las cuentas contables, si el valor `Elm` estuviera en el campo `Search Key` conseguirá un único registro, al aplicarlo en la búsqueda, al no ser exacto seria `Elm%`

**Comment by niclopup** [comment]
ok, no me parece ágil ya que si hay 1 sólo registro que cumpla con las condiciones, debería definir el registro rápidamente sin tener que agregar ningún caracter ni nada más.
