### ISSUE TITLE
[Feature Request] Mejora Configuracion del Reporte

### ISSUE THREAD

**Issue by elsiosanchez** [solop-develop/vue-1.0#446]
## Solicitud de función

Mejorar la forma de cambiar parámetros, formatos de impresión, vista de reporte y tipo de reporte. Actualmente solo se puede seleccionar una opción a la vez el cual en ocasiones puede ser poco factible.
 
#### Describe la solución que te gustaría

Un panel donde se puede configurar el tipo de reporte, formatos de impresión, vista de reporte y parámetros.

https://user-images.githubusercontent.com/45974454/194647639-6ffd9636-d696-4ec4-b859-839e0b082803.mp4

**Comment by niclopup** [comment]
Entiendo qeu el cambio sólo aplica a que se pueda modificar los parámetros de un reporte que ya está abierto.
