### ISSUE TITLE
POS Actualizar cantidad de la línea de la orden de venta

### ISSUE THREAD

**Issue by MarianaGallardo** [solop-develop/vue-1.0#450]
Se registra una orden de venta, con 2 productos. Se procede a actualizar la cantidad de un producto y permite actualizar, pero al seleccionar el segundo producto para actualizar la cantidad muestra la cantidad del primer producto que se editó y cuando se posiciona el cursor para cambiar la cantidad, entonces dice inmediatamente Cantidad Actualizada. A su vez, entra como en un bucle indicando Cantidad Actualizada cada vez que se coloca el foco en el campo cantidad.

Adjunto ejemplo:
![Screenshot_20221010-135629](https://user-images.githubusercontent.com/44775211/194927194-7e2493da-78aa-403c-997f-f2cce8b06f17.png)
![Screenshot_20221010-135623](https://user-images.githubusercontent.com/44775211/194927200-df905d96-c089-4467-9272-783e4a2d375a.png)
![Screenshot_20221010-135639](https://user-images.githubusercontent.com/44775211/194927201-592074d7-60dd-4b5c-98df-9db2d07ced46.png)
![Screenshot_20221010-135559](https://user-images.githubusercontent.com/44775211/194927205-312116ba-3000-4b80-907c-4b1da4e7f5b5.png)

https://user-images.githubusercontent.com/44775211/194931406-5600923b-0ac0-481b-b158-a35c5cb4adba.mp4

**Comment by EdwinBetanc0urt** [comment]
Se pasa al estatus `Por Validar` hasta que se implementen los cambios relacionados al punto de venta a nivel de diccionario y de código fuente de adempiere en solop.

**Comment by yamelsenih** [comment]
Esto ya se envió a @rcapecce
