### ISSUE TITLE
[Feature Request] Cantidad de Registros por Página (Paginación)

### ISSUE THREAD

**Issue by elsiosanchez** [solop-develop/vue-1.0#457]
## Feature request

Actualmente en la versión de **_ADempiere-UI_** solo se visualizan 15 registros máximo por página.

Se requiere una forma mas sencilla para la cantidad de registros a mostrar.

### GIf

https://user-images.githubusercontent.com/45974454/195164398-794993c6-731f-4cc2-a641-c08f49a0d0b9.mp4

**Comment by EdwinBetanc0urt** [comment]
Issue relacionado https://github.com/solop-develop/frontend-core/issues/387

**Comment by EdwinBetanc0urt** [comment]
La nueva funcionalidad de paginación se vera de la siguiente manera:

https://user-images.githubusercontent.com/45974454/195163300-e39aa559-8289-4698-9511-019f3f5d510e.mp4

**Comment by niclopup** [comment]
Quedo muy bueno!
