### ISSUE TITLE
No se ven países al crear localización de Socio del Negocio

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#460]
## Bug report
No se ven países al crear localización de Socio del Negocio, sólo se ven pocos registros que comienzan con letra A pero si se busca no se encuentra ningún país más. Se buscó tanto en español como en inglés

https://user-images.githubusercontent.com/31936815/195183111-55dceedc-ad04-4d22-b06d-da3bc2b13ccc.mp4

**Comment by EdwinBetanc0urt** [comment]
Corregido y listo para pruebas>


https://user-images.githubusercontent.com/20288327/195186746-ecc6ebbe-8c0c-4e47-b13a-59f5338b9e54.mp4
