### ISSUE TITLE
Buscador de Cuentas no Filtra Según Código o Nombre

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#462]
## Bug report

Se intenta buscar una cuenta definiendo sólo el primer nro del código pero sólo aplica la búsqueda Exacta cuando no debería. Si pongo Código "4" debería traer toda slas cuentas que comienzan en 4. En caso del nombre, se busca con el nombre exacto de de "Trade" pero no se encuentran registros cuando si existe.

https://user-images.githubusercontent.com/31936815/195193368-4312ace4-f552-4bb4-ae65-005919999d2d.mp4

**Comment by niclopup** [comment]
no hay manera de permitir que la búsqueda no sea EXACTA con el Código de Cuenta?

de lo contrario se hace muy dificil la definición correcta y ágil de las cuentas contables, ya que uno no las conoce de memoria, busca según el capitulo o lo que recuerda que se llama. NUnca es una búsqueda exacta.

De lo contrario se debería tener un árbol de cuentas abierto al lado para ver el nro exacto y no es práctico

**Comment by EdwinBetanc0urt** [comment]
Podría agregarse los porcentajes en el servidor para que coincida tanto en inicio como al final, ejemplo al escribir 4 => `%4%`, lo que coincidiría con:
* 123**4**567
* **4**56789
* 0123**4**
