### ISSUE TITLE
Nro de Línea obligatorio no definido automáticamente en línea de OC

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#463]
## Bug report

Se intenta crear una nueva línea en una Orden de Compra pero no aparecía el botón de guardar. Esto era debido a que se tenía que digital el nro de línea cuando este debería ser automático. 

https://user-images.githubusercontent.com/31936815/195195170-9d39e1b0-dfb8-4186-91b1-a7567a96c003.mp4

**Comment by EdwinBetanc0urt** [comment]
Corregido y listo para pruebas

https://user-images.githubusercontent.com/20288327/195148524-6624219f-4dd1-457b-9f40-09ced6b7b562.mp4
