### ISSUE TITLE
Campo: Búsqueda > Pago/Cobro

### ISSUE THREAD

**Issue by EdwinBetanc0urt** [solop-develop/vue-1.0#465]
Soporte al formulario de búsqueda de Pago/Cobro como campo

###  _**Versión ZK:**_

https://user-images.githubusercontent.com/45974454/196736562-a0c6d8da-3438-4fa9-914a-33f2ce1e944c.mp4

### _**Versión Vue:**_

https://user-images.githubusercontent.com/45974454/196737004-4d1b3149-7793-4b26-84de-d159c84fa6a7.mp4

**Comment by niclopup** [comment]
Ok, pero falta definir correctamente la ventana de búsqueda del Pago/Cobro

![image](https://user-images.githubusercontent.com/31936815/197897495-9b1c699d-d6c9-4198-8960-886aa6c1d550.png)

1. Las columnas no están igual a los parámetros que permite filtrar
2. Agregaría como parámetros de filtro: Socio del Negocio, Importe, Fecha, Moneda, Cuenta Bancaria.

**Comment by EdwinBetanc0urt** [comment]
Se establecieron de manera general que los campos tipo búsqueda tendrán en el encabezado o criterio de búsqueda solo campos tipo texto que estén marcados como selección.

**Comment by niclopup** [comment]
no veo que esté corregido este buscador

![image](https://user-images.githubusercontent.com/31936815/215931506-b6b62b49-b9da-461f-8105-652d51d2b69e.png)

veo que hay muchos filtros y muchas columnas. cuando debería haber sólo las necesarias.

**Comment by Ricargame** [comment]
Cambios disponibles apartir de la versión: https://github.com/solop-develop/frontend-core/releases/tag/3.9.3


https://github.com/solop-develop/frontend-core/assets/78000356/4d782a79-cc49-46ce-aa73-37244c301404

**Comment by niclopup** [comment]
Se confirma que está ok el campo en el parámetro de un reporte


https://github.com/user-attachments/assets/f732c278-f78f-4c66-98e1-81ec8aa43b51

pero tiene error cuando es un campo de una ventana: 

Ej: Línea de Estado de Cuenta Bancario


https://github.com/user-attachments/assets/851f8d9a-c824-4500-818f-460267b045a8

**Comment by EdwinBetanc0urt** [comment]
Disponible a partir de la versión del frontend https://github.com/solop-develop/frontend-core/releases/tag/4.3.3 y del backend https://github.com/solop-develop/adempiere-grpc-server/releases/tag/3.7.0


https://github.com/user-attachments/assets/5784d2da-c54f-41a7-b5cf-a985aaccb19c

**Comment by niclopup** [comment]
![image](https://github.com/user-attachments/assets/88bc5698-4d8f-4f81-923a-b8f42cc4bf4e)

me pasa lo mismo q presetntaron,m donde se ve q no se visualiza correctamente la busqueda de pago/cobro

**Comment by EdwinBetanc0urt** [comment]
@niclopup fue un cache de la instancia con el proxy, ya esta corregido

![imagen](https://github.com/user-attachments/assets/dd929f3c-9c00-43c1-af09-c68357910eb1)

**Comment by mgarciaQ76** [comment]
Verificado. Se realizan pruebas con resultado exitoso ok


https://github.com/user-attachments/assets/cb5071f9-46c5-4616-be8d-5a2c0168fc9f
