### ISSUE TITLE
Forma: Búsqueda > Activo Fijo

### ISSUE THREAD

**Issue by EdwinBetanc0urt** [solop-develop/vue-1.0#467]
En la versión del Zk se visualizan de la siguiente manera los campos tipo búsqueda de `Activo Fijo`:

https://user-images.githubusercontent.com/20288327/205091879-a3a5c03d-c7ee-4de4-9e8e-f07a956fa09b.mp4

**Comment by niclopup** [comment]
no se puede crear un nuevo registro en la ventana "Adición de Activo FIjo" por lo que no se puede probar esto

![image](https://user-images.githubusercontent.com/31936815/215934335-4e8d4b35-28a0-49b8-b1e6-90cec9834f4f.png)

**Comment by EdwinBetanc0urt** [comment]
Corregido

https://user-images.githubusercontent.com/20288327/216164494-359f6d3d-11e6-4fd3-af70-6cd1d28440a7.mp4
