### ISSUE TITLE
Campo: Búsqueda > Factura Venta/Compra

### ISSUE THREAD

**Issue by EdwinBetanc0urt** [solop-develop/vue-1.0#468]
Soporte al formulario de búsqueda de Factura como campo

###  _**Versión ZK:**_

https://user-images.githubusercontent.com/45974454/196731841-1e5de380-4505-43ea-8a25-397ca9f46eb4.mp4

### _**Versión Vue:**_

https://user-images.githubusercontent.com/45974454/196731927-717881fc-5096-433d-84d5-20619511c10e.mp4

**Comment by niclopup** [comment]
se visualiza el Nro de Factura pero no dice que SDN corresponde? no tiene mucho sentido más aún sin haber definido el SDN antes.

Tampoco se ve el Importe de la factura en cuestión y la moneda.

![image](https://user-images.githubusercontent.com/31936815/197804250-bf8ee473-a591-4227-9031-e2a383de239a.png)


Por otro lado, se intenta definir un SDN para que filtre sólo las Facturas del SDN y no se logra encontrar.


https://user-images.githubusercontent.com/31936815/197804387-c7adc36d-ec6e-42bd-85eb-b1d5866d7ed5.mp4

**Comment by niclopup** [comment]
En un Parámetro de un reporte se ve ok:

![image](https://github.com/user-attachments/assets/d785cf6e-d5e3-4329-99e0-b8ac01a3a047)



Pero da error en la ventana Pago/Cobro:


https://github.com/user-attachments/assets/ac596149-0d39-4d7c-a0f8-b5d45739c67c


https://github.com/user-attachments/assets/b37ac301-3d95-441a-8a6d-9c1eedeb03ca

**Comment by niclopup** [comment]
@EdwinBetanc0urt confirmar si esto ya está arriba para validar o aún no. Haciendo la prueba salta el siguiente error todavía desde spdev:24610

![image](https://github.com/user-attachments/assets/98677565-8eaf-48cc-8dd6-1c9366635d8d)

**Comment by EdwinBetanc0urt** [comment]
El problema esta en la validación dinámica `UY_Val_InvoicePayment` que tiene el campo `Factura`

![imagen](https://github.com/user-attachments/assets/956a606d-08d6-4e86-b962-5a838be9bf0d)

![imagen](https://github.com/user-attachments/assets/be6abcee-bbb9-47e0-a19d-f56fd430fa72)

Actualmente el sql esta asi

```sql
C_Invoice.DocStatus IN ('CO', 'CL') AND C_Invoice.C_Currency_ID = @C_Currency_ID@ AND C_Invoice.C_DocTypeTarget_ID NOT IN (select c_doctype_id from c_doctype where docbasetype IN ('DRI','DPI','DRC','DPC'))
```

El problema es que en el backend necesitamos agregar alias de la tabla principal por lo que al no tener alias `c_doctype` intenta agregarla como `c_doctype AS C_Invoice` https://github.com/solop-develop/adempiere-grpc-server/blob/b80027f27d267c1bcf7fe94ea0e8055fcd1384ad/src/main/java/org/spin/grpc/service/field/invoice/InvoiceInfoLogic.java#L330, no tenemos forma de saber cuando es una sub-consulta dentro de la restricción.


Podría corregirse colocando alias al nuevo seqlect del subquery en la validación dinámica de la siguiente manera
```sql
C_Invoice.DocStatus IN ('CO', 'CL') AND C_Invoice.C_Currency_ID = @C_Currency_ID@ AND C_Invoice.C_DocTypeTarget_ID NOT IN (select dt.c_doctype_id from c_doctype AS dt where dt.docbasetype IN ('DRI','DPI','DRC','DPC'))
```
