### ISSUE TITLE
Error al modificar Fecha de la Orden en Borrador

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#478]
## Bug report
Se modifica la Fecha en una Orden de Venta en Borrador y aparece el siguiente error:

"Request message serialization failure: Assertion failed"

De todas formas permite guardar

https://user-images.githubusercontent.com/31936815/195361996-4eba09cd-1d75-4a6b-91a7-a8f3f13ebaa1.mp4

![Error en cambio de Fecha en Orden en Borrador](https://user-images.githubusercontent.com/31936815/195362003-8bd244e8-49e0-4b6e-b636-b8a4ceaed48e.png)

#### Steps to reproduce

1. [xxx]
2. [xxx]
3. [xxxx]

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:

**Comment by EdwinBetanc0urt** [comment]
Debemos verificar que tipo de datos se esta enviando al proxy (date, string, o long) para hacer su corrección.
