### ISSUE TITLE
Cantidad se define en 0 al guardar registro.

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#481]
## Bug report

Se intenta guardar cantidad 10 pero no guarda, deja cantidad en 0. Pero si se define cantidad 10.1 si lo guarda en 10.

https://user-images.githubusercontent.com/31936815/195394492-858d4d18-649f-4efa-ad35-d944b949be7a.mp4

**Comment by niclopup** [comment]
Ahora parece que permite guardar, pero en realidad no actualiza el Neto de la línea por lo que entiendo que no estaría guardando correctamente la cantidad

![image](https://user-images.githubusercontent.com/31936815/197906926-72c4dcd4-32c8-4617-9a22-88373cfe02ca.png)

Se define 20 unidades y el precio 57 y no se define el importe neto correcto
 
Inicialmente actualizó el Precio para que cierre con 20 unidades el 57 el neto de línea

Se logra replicar. Al parecer deja fijo el Neto de línea en 57 pero si se modifica la cantidad, se modifica el precio unitario para qeu cierre con el mismo Neto de línea, cuando debería actualziar el neto de línea según La cantidad x el Precio

![image](https://user-images.githubusercontent.com/31936815/197907086-817fb7f0-1f26-4c04-a631-b109a1825cf7.png)

**Comment by EdwinBetanc0urt** [comment]
En el log se detallan las siguientes advertencias

```log
-----------> GridTab.query: No link column [182]
===========> MProductPricing.calculatePriceBasedOnPriceList: No PriceList [182]
```

**Comment by EdwinBetanc0urt** [comment]
@niclopup El detalle de este issue esta en https://github.com/solop-develop/frontend-core/issues/561? Ya que el problema principal de este issue (Guardar en un campo definido Monto/Numero/Costo+Precio/Cantidad sin decimales) ya fue resuelto, si es así esta actividad puede darse por entregada y seguir el inconveniente que presenta con los callouts en el otro issue
