### ISSUE TITLE
Modificación en lógica minimalista de columnas en Ventanas

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#483]
## Bug report
Con la lógica que se aplicó actualmente existen algunos campos que considero que deberían mostrarse siempre, pero quedan fuera de la lógica que aplicaron para lo "Minimalista" de ser Obligatorio y no tener una lógica predeterminada. Por ejemplo en las órdenes de venta el campo "FECHA DE LA ORDEN" o "FECHA PROMETIDA" si bien tiene una lógica predeternimada y son obligatorios, si se desea modificar la fecha se debe primero agregar el capo y luego modifciarla lo cual no tiene mucho sentido. Lo mismo sucede con el campo "Cantidad" de las líneas de Orden.

En este sentido, y siguiendo el criterio definido para mostrar los campos por defecto en las formas de búsqueda de Socio del Negocio y Productos, se sugiere agregar a la lógica "Minimalista" también las olumnas que estén marcadas como "Columna Selección" (Selection Column)

De esta manera también se permite un ágil mantenimiento si se desea aplicar una modificación de los campos a mostrar en un cliente específico.

![image](https://user-images.githubusercontent.com/31936815/195425085-3fff81a1-be89-403a-b476-41781dabefd3.png)

**Comment by EdwinBetanc0urt** [comment]
Se establecerá una condición donde se evaluara si el tipo de ventana es documento, para determinar si se visualizara por defecto en la vista minimalista, ejemplos:
- Orden: Fecha de la Orden.
- Linea de la Orden: Producto, Cantidad.

Ya que el check de columna de selección es utilizado para los campos que se muestran al hacer una búsqueda.

A futuro es mas viable implementar una nueva columna para mejorar el soporte con el ASP y guardar la configuración de cada usuario, rol...

**Comment by niclopup** [comment]
ok si se puede avanzar con esa solución de manera momentánea avancemos

**Comment by EdwinBetanc0urt** [comment]
Se pueden visualizar en la primera carga de la ventana, los campos `Producto`, `Cantidad`, `Precio`, `Fecha de La Orden`, `Fecha Prometida`.

**Comment by niclopup** [comment]
Faltaría "Fecha de Transacción"

**Comment by EdwinBetanc0urt** [comment]
Se agrego `Fecha de Transacción` y `Fecha de Facturación`

**Comment by niclopup** [comment]
no se visualiza los campos de Fechas en la ventana "Ordenes de Venta"

![image](https://user-images.githubusercontent.com/31936815/203458734-3af1da08-0e0e-44cf-ad2c-6a20e8a9e256.png)


Lo raro es que al parecer si se visualiza la Fecha de la Orden en la vista Mono Registro. Esto es por que tiene diferente definición en GRilla o mono registro?

![image](https://user-images.githubusercontent.com/31936815/203458977-32ef9981-e99c-483a-8746-929e4a7df42b.png)


Se sugiere también agregar el Estado como Columna en la vista minimalista así facilita la búsqeuda de los documentos viendo claramente su estado, de lo contrario tendría que ir registro a registro para ver el campo de estado arriba en la barra de herramientas nueva.

**Comment by EdwinBetanc0urt** [comment]
Son diferentes pero se revisara para que coincidan, y agregar el estado del documento en la tabla es buena idea.

**Comment by EdwinBetanc0urt** [comment]
Se agrego lo comentado, listo para pruebas.
