### ISSUE TITLE
Ocultar pestañas hijas en vista Multi Registro

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#484]
## Feature request

Cuando se visualiza una ventana en modo "Multi Registro" es muy confuso el hecho que se muestren las pestañas hijas ya que el espacio de edición queda muy limitado tanto en la grilla de los cabezales como también en los registros de cada pestaña. 

Si bien se intentó brindar la opción de achicar las pestañas agrandando así el área de visualización de la grilla, las pestañas "reducidas" quedan abajo sin ninguna posibilidad de accionar sobre ellas dado que es muy reducido el espacio. 

Se sugiere permitir definir que cuando se vea una ventana en modo "Multi Registro", las pestañas hijas no se muestren de manera que sólo se muestren si se "abre" un registro y se visualiza en modo "Mono Registro". de esta manera se da suficiente espacio para manipular una grilla y cuando se desea accionar sobre sus  líneas simplemente se deberá ver como mono registro.

Se conversó que se podía agregar un check como preferencia de usuario para permitiir habilitar o no esta funcionalidad.

https://user-images.githubusercontent.com/31936815/195426300-65f1c040-8dac-4c2a-970d-3bee90ad9760.mp4

![image](https://user-images.githubusercontent.com/31936815/195426702-bef059e7-e14c-4b1c-913c-d347233b2224.png)

**Comment by EdwinBetanc0urt** [comment]
Aca se visualiza como activar la nueva opción para ocultar las pestañas hijas en multi registros

https://user-images.githubusercontent.com/45974454/197066363-73560546-bb07-4468-96df-f2e62d90e72b.mp4

**Comment by niclopup** [comment]
Se logra visualizar una vez con la grilla completa, pero luego simplemente se va la definición y las ventanas ya no se muestran con la grilla completa y las pestñaas se visualizan también en modo grilla

![image](https://user-images.githubusercontent.com/31936815/197905981-4a744fc8-c930-4833-9b14-7a415a3a33b0.png)

![image](https://user-images.githubusercontent.com/31936815/197906015-4ff9a2b6-c61c-40af-be90-3bba2067ac3b.png)

Cerre la ventana y la volví a abrir pero no pasa nada.

El cambio sólo aplica sobre ventana Socio del Negocio y Producto?

![image](https://user-images.githubusercontent.com/31936815/197906290-a3957bfd-5cb4-4905-ba20-83519925757c.png)

Debería funcionar para todas! más aún es utilizado en Documentos.

**Comment by niclopup** [comment]
En Producto, cuando se selecciona un producto con la opción de Grilla compelta, se deja de ver los campos del Cabezal cuando se pasa a mono registro, mostrando sólo las pestañas y mostrando campos para la derecha, haciendo scroll se pueden ver. pero no se ve nada del Cabezal



![image](https://user-images.githubusercontent.com/31936815/197907598-c712e01f-078e-4607-af0f-e41abc6c0d68.png)

**Comment by EdwinBetanc0urt** [comment]
No se visualiza en ventanas de documentos

**Comment by elsiosanchez** [comment]
https://user-images.githubusercontent.com/45974454/198128552-9e604287-a82b-4579-a919-ba41dd6da71c.mp4

**Comment by niclopup** [comment]
No funciona correctamente en ventana "Órdenes de Venta"

![image](https://user-images.githubusercontent.com/31936815/200912574-943c7d25-c7a7-4301-8298-bf5d51cc95af.png)


Pero en Socio del Negocio se ve bien

![image](https://user-images.githubusercontent.com/31936815/200913148-dfe01d73-302f-4db7-9c77-aff2f33172f8.png)

**Comment by EdwinBetanc0urt** [comment]
Cambios disponibles para pruebas en https://vue-develop.solopcloud.com

![Screenshot_20221110_120109](https://user-images.githubusercontent.com/20288327/201144699-7d1263e8-2367-478f-aae7-4b3cecef63a1.png)

**Comment by niclopup** [comment]
Veo que está oK en la ventana de Órdenes de Venta, pero viendo la de "Documentos por Cobrar" veo que aún se ven las pestañas hijas

![image](https://user-images.githubusercontent.com/31936815/201153323-226a52a3-a555-40aa-926d-b0104d74dc93.png)


ördenes de venta se ve bien

![image](https://user-images.githubusercontent.com/31936815/201153262-d6d70322-feea-4b1b-8dbb-64d76a5265de.png)

**Comment by elsiosanchez** [comment]
https://user-images.githubusercontent.com/45974454/201360653-7fcff558-a213-41dd-accc-3309e0363716.mp4
