### ISSUE TITLE
Click en Documento Relacionado no lleva a registro

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#487]
## Bug report

al hacer click en uno de los documentos relacionados no se abre la ventana con el registro en cuestión.

https://user-images.githubusercontent.com/31936815/195432799-caf10d3d-c1d9-4228-b5fa-78abd53bb6d5.mp4

#### Steps to reproduce

1. [xxx]
2. [xxx]
3. [xxxx]

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:

**Comment by elsiosanchez** [comment]
### **_Nota_**
Cabe destacar tanto como en el zk como en la UI no permite acercar ese registro en particular por lo cual es un error de ADempiere

**Comment by EdwinBetanc0urt** [comment]
La corrección esta disponible para pruebas en https://vue-develop.solopcloud.com

**Comment by niclopup** [comment]
No se visualiza opción de Referencias en los procesos del Documento. no está el campo en la lista.



![image](https://user-images.githubusercontent.com/31936815/197905312-6c21d276-0cd8-4be9-9a1d-ac8c92134c21.png)

**Comment by EdwinBetanc0urt** [comment]
Corregido con el cambio https://github.com/solop-develop/frontend-default-theme/pull/413

**Comment by niclopup** [comment]
Se intenta navegar dede el SDN "Test Edwin 2" pero abre una ventana de orden de venta vacía

![image](https://user-images.githubusercontent.com/31936815/216710116-00154bbf-228c-4c4f-a85c-32e3a29672c6.png)

Justo tenía antes abierta la orden de venta que entiendo tiene relacionada, no se si eso puede implicar algo

![image](https://user-images.githubusercontent.com/31936815/216710162-c8db0ce8-8485-46e5-8c1f-f990cd736653.png)

se intenta navegar a la ventana "Documentos por Cobrar" desde el SDN JOE Block y navega correctamente.

![image](https://user-images.githubusercontent.com/31936815/216710667-ee386ba6-9432-4ec5-9904-811b63a2cdbe.png)

Tal vez será que la primera no está completa?

**Comment by EdwinBetanc0urt** [comment]
Corregidos
