### ISSUE TITLE
Reporte: Ejecución > Acercar a registros desde enlaces HTML

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#489]
## Feature request

Se debe permitir navegar a un registro desde el reporte en HTML tal como lo permite ZK

https://user-images.githubusercontent.com/31936815/195436141-ca6a77ee-b0a7-44bd-95f1-87ba810e717a.mp4

**Comment by yamelsenih** [comment]
Esto no es posible directamente desde el HTML, creo que es conveniente agregarlo como parte de la fase de desarrollo de reportes con el nuevo motor
