### ISSUE TITLE
Reporte: Ejecución > Navegar a Documento desde línea de Asiento en Balance de Prueba

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#490]
## Feature request

Se desea contar con la funcionalidad de navegar a los documentos correspondientes a los asientos que se visualizan en el Balance de Prueba  como ahora se puede hacer en ZK con la LUPA.

https://user-images.githubusercontent.com/31936815/195437421-ab8eb572-f3b0-4c73-afde-b6aa7dfc2c34.mp4

para poder ver los datos en VUE se definen los siguientes parámetros:

![image](https://user-images.githubusercontent.com/31936815/195436413-97edff6e-b72f-47b8-b50d-ecb27bbf86eb.png)

https://user-images.githubusercontent.com/31936815/195437501-82021450-8aa6-49e8-8c20-711cc871e4d1.mp4

**Comment by niclopup** [comment]
No se visualiza como se estaria dando soporte a navegar al registro.

https://github.com/user-attachments/assets/72ddae08-ca19-485f-beee-5ad2448b67a1


https://github.com/user-attachments/assets/e66be7d5-2a54-4acd-8fa9-8a211c46bcf3

**Comment by EdwinBetanc0urt** [comment]
cambios disponibles a partir del frontend https://github.com/solop-develop/frontend-core/releases/tag/4.4.024 y del backend https://github.com/solop-develop/adempiere-grpc-server/releases/tag/3.10.007

https://github.com/user-attachments/assets/b5e80c54-df72-4f48-876e-0dde324f00ca
