### ISSUE TITLE
No se puede Completar una Orden de Venta desde VUE

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#496]
## Bug report

No se puede completar una orden de venta desde VUE

Se le da al proceso pero queda procesando eternamente.

https://user-images.githubusercontent.com/31936815/195930276-0bf99abc-75d5-42db-baee-d1b0e67902b8.mp4

Se intenta ir desde ZK y completarla pero da error como un flujo de trabajo activo.

**Comment by EdwinBetanc0urt** [comment]
Como se observa en el siguiente video, se pueden completar documentos en vue, sin embargo esto es posible parcheando un error de adempiere.

https://user-images.githubusercontent.com/45974454/195939922-937b0e6e-e627-4598-85a1-6c9a3d2ceb17.mp4

**Comment by EdwinBetanc0urt** [comment]
Adjunto la clase con las modificaciones en ADempiere (créditos de @yamelsenih) para poder ejecutar un flujo de trabajo de un documento, ya que el problema también se evidencia al ejecutar `Procesar Factura` de los procesos asociados a la pestaña.

![Screenshot_20221019_113347](https://user-images.githubusercontent.com/20288327/196737686-030cbaa0-85c9-40c6-9fe6-98bbf4600d25.png)


[ProcessBuilder.java.txt](https://github.com/solop-develop/frontend-core/files/9821979/ProcessBuilder.java.txt)

**Comment by yamelsenih** [comment]
Esto ya fue enviado a @rcapecce
