### ISSUE TITLE
Campo: Campo Localización > Dar soporte a solo lectura

### ISSUE THREAD

**Issue by EdwinBetanc0urt** [solop-develop/vue-1.0#502]
Si el registro o campo esta solo lectura actualmente no se esta respetando, ya que permite la edición de campos de dirección de localización.

https://user-images.githubusercontent.com/20288327/196230902-e0abb46d-ac95-47fe-9935-8fff45970ccb.mp4

**Comment by niclopup** [comment]
no se puede aprobar ya que no se ven registros en ventana ALmacén y Ubicaciones

https://github.com/solop-develop/frontend-core/issues/527

**Comment by EdwinBetanc0urt** [comment]
Este problema fue solventado con el cambio https://github.com/solop-develop/backend/pull/134 esta listo para pruebas
