### ISSUE TITLE
Campo: Campo Localización > Limpiar correctamente los valores del formulario.

### ISSUE THREAD

**Issue by EdwinBetanc0urt** [solop-develop/vue-1.0#503]
Al seleccionar otros registros con distintos valores de la localización, mantiene los valores del primer registro desplegado.

De igual forma al seleccionar el botón nuevo, debe limpiar los valores de la localización.

https://user-images.githubusercontent.com/20288327/196528183-bb99aa56-3068-477b-9901-facaa1fb8d19.mp4

**Comment by EdwinBetanc0urt** [comment]
Así se ve la diferencia del manejo con corrección:

https://user-images.githubusercontent.com/20288327/196529657-16e6586b-1f2c-4a9b-89d9-a19428104472.mp4

**Comment by niclopup** [comment]
ok
