### ISSUE TITLE
Campo: Campo Localización > Agregar nuevos campos de coordenadas.

### ISSUE THREAD

**Issue by EdwinBetanc0urt** [solop-develop/vue-1.0#504]
En la actualización de ADempiere https://github.com/adempiere/adempiere/pull/3877 se agregaron los nuevos campos para la localización referentes a las coordenadas, como la longitud, la latitud y la altura.

#### Versión Zk:
![coordenates](https://user-images.githubusercontent.com/20288327/196250598-d11610a0-edc2-477d-8f47-bfe2d3937979.png)

#### Version Vue:

Actualmente en vue esos campos no están presentes, se debe agregar soporte.

![Screenshot_20221017_140309](https://user-images.githubusercontent.com/20288327/196250702-c2e6294e-c92f-4341-996b-a0af4c90bb59.png)

**Comment by EdwinBetanc0urt** [comment]
Se agregaron los 3 nuevos campos en relación a las coordenadas (longitud, latitud, altitud), adicionalmente también se agrego el campo de `Código Postal Adicional` ya que si en la secuencia de captura se tenia el valor de @A@ no mostraba el campo de `Código Postal Adicional`.


https://user-images.githubusercontent.com/20288327/196540463-34848329-5412-4af3-b480-4e9d7d9a9832.mp4


Cabe destacar que los campos relacionados a las coordenadas siempre están visibles y al final de los demás campos, ya que así se maneja en el swing y el zk.

**Comment by niclopup** [comment]
Hoy se logró ver bien pero luego noté que faltaba el campo Longitud  y no permitía guardar la dirección.

ahora se verifica nuevamente y no se ven las coordenadas

![image](https://user-images.githubusercontent.com/31936815/197897961-a88d5a8a-e89d-486b-b7e2-032ac4d2b37f.png)

**Comment by EdwinBetanc0urt** [comment]
Saludos, no puedo reproducir el error, ni local ni en https://vue-develop.solopcloud.com

**Comment by EdwinBetanc0urt** [comment]
El problema esta detallado en este issue https://github.com/solop-develop/frontend-core/issues/560 y resuelto en https://github.com/solop-develop/backend/pull/145 también esta actualizado el cambio en el servidor de pruebas https://vue-develop.solopcloud.com/
