### ISSUE TITLE
Campo: Campo Localización > Si el país tiene nombre de región, no cambia el nombre del campo `Region`.

### ISSUE THREAD

**Issue by EdwinBetanc0urt** [solop-develop/vue-1.0#506]
Si en la definición del país se maneja regiones y se tiene un nombre de región para ese país, no cambia, ejemplo para el caso de Estados Unidos la región es `State`, para el caso de Argentina es `Provincia`, para el caso de Alemania es `Bundesland` y para el caso de Venezuela es `Estado`.

Versión en Zk:

https://user-images.githubusercontent.com/20288327/196465378-98e9761f-87b2-4bb0-a701-d12be6b4c1e5.mp4

Versión en Vue:

https://user-images.githubusercontent.com/20288327/196465416-40c25a30-ef0f-4b39-a25e-20150167e443.mp4

**Comment by niclopup** [comment]
Quedó bueno la ventana minimalista para definir la localización , pero no se logra ver la Calle ni el País que son necesarios para definir la localización.

https://user-images.githubusercontent.com/31936815/197797961-d726668d-2d71-4238-9ff1-40e8bf23f70c.mp4

**Comment by EdwinBetanc0urt** [comment]
Saludos, no puedo reproducir el error, ni local ni en https://vue-develop.solopcloud.com

Asumo que es el mismo error comentado en https://github.com/solop-develop/frontend-core/issues/504#issuecomment-1291254944

**Comment by EdwinBetanc0urt** [comment]
El problema esta detallado en este issue https://github.com/solop-develop/frontend-core/issues/560 y resuelto en https://github.com/solop-develop/backend/pull/145 también esta actualizado el cambio en el servidor de pruebas https://vue-develop.solopcloud.com/
