### ISSUE TITLE
[Bug Report] Perder Seleccion al Refrescar 

### ISSUE THREAD

**Issue by elsiosanchez** [solop-develop/vue-1.0#508]
### Error
En modo Grilla al refrescar un registro con los botones de (conveniencia o accion rapida) se pierde la seleccion

### Pasos a Seguir

1. Abrir una la ventana _**Tipo Relación**_
2. Cambiar vista a modo _**Multi Registo**_
3. Pulse la opcion _**Refrescar**_

### Gif

https://user-images.githubusercontent.com/45974454/196483777-f5347712-6d35-42ea-827f-3f5df41c4fdc.mp4

**Comment by EdwinBetanc0urt** [comment]
Otro error relacionado al refrescar registros es que al perder la selección en la tabla, e intentar cambiar a mono registro generaba el siguiente error:

```log
changeShowedRecords@webpack-internal:///./node_modules/cache-loader/dist/cjs.js?!./node_modules/@vue/cli-plugin-babel/node_modules/babel-loader/lib/index.js!./node_modules/cache-loader/dist/cjs.js?!./node_modules/vue-loader/lib/index.js?!./src/themes/default/components/ADempiere/TabManager/TabOptions.vue?vue&type=script&lang=js&:170:92
invokeWithErrorHandling@webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:1862:26 invoker@webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:2187:14
invokeWithErrorHandling@webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:1862:26
```
