### ISSUE TITLE
Campo: Campo Localización > Abrir el mapa de google en función de los valores de dirección.

### ISSUE THREAD

**Issue by EdwinBetanc0urt** [solop-develop/vue-1.0#510]
Se requiere dar soporte para abrir el mapa en función de los valores de dirección de localización.

Versión Zk:

https://user-images.githubusercontent.com/20288327/196710059-79f03c2b-b631-4f9c-8813-f32c12912c5a.mp4

**Comment by EdwinBetanc0urt** [comment]
Como se observa en el ejemplo, toma como prioritario la búsqueda en el mapa con las coordenadas ya que es una ubicación mas precisa, si no tiene valores entonces realizara la búsqueda con el valor de visualización de la dirección de localización.


https://user-images.githubusercontent.com/20288327/196713202-de175d27-8d2c-4169-89a1-b9449b23882d.mp4




Ejemplo con valores de coordenadas https://www.google.com/maps?q=10.046955,-69.325574

Ejemplo con valor de visualizacion https://www.google.com/maps?q=,+OR,+Furniture+Transit,+United+States

**Comment by niclopup** [comment]
Falta longitud

![image](https://user-images.githubusercontent.com/31936815/197798302-f0463cfa-5eed-4886-ab2e-7dad903f2874.png)

**Comment by EdwinBetanc0urt** [comment]
El problema esta detallado en este issue https://github.com/solop-develop/frontend-core/issues/560 y resuelto en https://github.com/solop-develop/backend/pull/145 también esta actualizado el cambio en el servidor de pruebas https://vue-develop.solopcloud.com/
