### ISSUE TITLE
No se puede navegar pestañas hijas en ventana SDN

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#525]
## Bug report
No se puede navegar pestañas hijas en ventana SDN

https://user-images.githubusercontent.com/31936815/197804495-673a4863-de90-4045-8074-98815fb31d80.mp4

**Comment by elsiosanchez** [comment]
Solucionado y listo para pruebas en https://vue-develop.solopcloud.com

![error](https://user-images.githubusercontent.com/45974454/201102866-bc8652f9-4559-409a-8113-33c54c8f2fb9.gif)
