### ISSUE TITLE
no se ve registros en ventana Almacén y Ubicaciones

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#527]
## Bug report

Se abre la ventana Almacén y Ubicaciones y no se ven registros

![image](https://user-images.githubusercontent.com/31936815/197903746-110ec1ff-f4df-4a8a-b1e7-db9e8ef76eb9.png)

![image](https://user-images.githubusercontent.com/31936815/197903795-f7c98815-ce4e-44f4-a6b7-9ff571acbbf0.png)

Se hace click en Refrescar registros pero tampoco aparecen

![image](https://user-images.githubusercontent.com/31936815/197903843-255e1c6a-20b0-4955-958a-15afd9026148.png)

Se inicia sesión con Admin

![image](https://user-images.githubusercontent.com/31936815/197903882-afa32467-fd2c-469a-836d-e45c3f9041bc.png)

#### Steps to reproduce

1. [xxx]
2. [xxx]
3. [xxxx]

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:

**Comment by EdwinBetanc0urt** [comment]
Solucionado y listo para pruebas en https://vue-develop.solopcloud.com

https://user-images.githubusercontent.com/45974454/201103539-9dae7caf-6570-4bfc-a92d-a717150fec09.mp4
