### ISSUE TITLE
No se ven Socios del Negocio desde Buscador en ventanas

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#528]
## Bug report
No se visualiza ningun SDN en el buscador desde el campo Socio del Negocio en ventanas del documento Orden de Venta, Orden de Compra, Pago/Cobro

Orden de Venta 
![image](https://user-images.githubusercontent.com/31936815/197904402-b54bf623-4289-4310-8565-e2101ac95c63.png)

Orden de Compra
![image](https://user-images.githubusercontent.com/31936815/197904459-88cf5f2f-5cd1-4552-a326-0bafdb933c96.png)

Pago/Cobro
![image](https://user-images.githubusercontent.com/31936815/197904566-7a56fc8f-4bfe-476e-b186-1af4b6281241.png)

#### Steps to reproduce

1. [xxx]
2. [xxx]
3. [xxxx]

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:

**Comment by EdwinBetanc0urt** [comment]
Solucionado y listo para pruebas en https://vue-develop.solopcloud.com
