### ISSUE TITLE
[Bug Report] POS: No realiza la agrupación del IGTF cuando se trabaja con metodo de pagos distinto pero con la misma moneda

### ISSUE THREAD

**Issue by silvianapatricia** [solop-develop/vue-1.0#535]
Servicio: http://20.12.0.2:55105/#
Orden de Venta:  OVT-8333

Monto Total: 1.597,09 VES - 189,90 USD

Primer Pago:  Efectivo USD 50 $ IGTF 1,5 $
Segundo Pago: Zelle USD 100$ IGTF 3$

Dando un total de IGTF de 4,5 $

![image](https://user-images.githubusercontent.com/36901843/198316134-ef4f5932-146c-46c3-a6e2-a09a92910e60.png)

No realiza la agrupación del IGTF cuando se trabaja con método de pagos distinto pero con la misma moneda

**Comment by yamelsenih** [comment]
Esto es un problema de implementación en backend
