### ISSUE TITLE
[Bug Report] Error Campo de Búsqueda de Registro

### ISSUE THREAD

**Issue by elsiosanchez** [solop-develop/vue-1.0#541]
## Bug report
El campo de busqueda de registro solo debe aparecer en el panel de ventana
#### Steps to reproduce

- Abra un Reporte y observe que aparece el campo de busqueda de registro
- Abra un Proceso y observe que aparece el campo de busqueda de registro
- Abra un Smart Browser y observe que aparece el campo de busqueda de registro

#### Screenshot or Gif（截图或动态图）

https://user-images.githubusercontent.com/45974454/199028426-c67025eb-f14c-4ed4-9f44-5633138772ee.mp4

**Comment by EdwinBetanc0urt** [comment]
Esto ya fue solucionado y esta listo para pruebas en https://vue-develop.solopcloud.com
