### ISSUE TITLE
Permitir Asignar Vendedor en el POS

### ISSUE THREAD

**Issue by MarianaGallardo** [solop-develop/vue-1.0#542]
**Descripción del Problema**
Existen tiendas donde no hay un terminal en el pasillo sino que en su defecto hay una persona que factura los pedidos a nombre de otro vendedor. Esta funcionalidad no existe actualmente en ADempiere ya que siempre los pedidos son creados con el vendedor de login.

**Descripción de la Solución**
Permitir modificar el vendedor de la orden de ventas en el campo donde se muestra como se ve en la imagen:
![Screenshot from 2022-10-28 15-54-08](https://user-images.githubusercontent.com/2333092/198721336-c4b545d5-ae81-4880-b2d3-7ef58d52c2d3.png)

**Algunas Alternativas a tomar en cuenta**
No vi otra alternativa mejor

**Información Adicional**
Al cambiar el vendedor debe actualizar la orden de venta y establecer el valor del nuevo vendedor en el campo `SalesRep_ID`

**Comment by MarianaGallardo** [comment]
Prueba en: Se realizó la prueba en el contenedor local: http://20.12.0.2:55105/#/

No permite modificar el vendedor desde donde indica el Issue. Está apareciendo otro campo el cual permite seleccionar, pero no actualiza el vendedor:

![image](https://user-images.githubusercontent.com/44775211/199109365-e02fcd0a-7d59-47dd-b731-4f73a592cda7.png)
![image](https://user-images.githubusercontent.com/44775211/199109575-2fd8a7ab-4691-4e39-8578-9def59e46e52.png)

**Comment by MarianaGallardo** [comment]
Luego de actualizar el contenedor con la versión que indican el cambio. El resultado no fue satisfactorio debido que no muestra el listado de los vendedores a asignar. El en terminal del Asesor, muestra al mismo usuario que inició sesión y creó la orden. En el terminal de la Caja, muestra en blanco.

Asesor
![Screenshot 2022-11-01 12 25 26 PM](https://user-images.githubusercontent.com/44775211/199284977-231cb418-db52-4702-b3be-af4670509eb1.png)

Cajero
![Screenshot 2022-11-01 12 24 50 PM](https://user-images.githubusercontent.com/44775211/199285010-4d079aa2-88f7-4a0a-a2e7-8b465251621a.png)

**Comment by MarianaGallardo** [comment]
Ya realiza el cambio del vendedor en el contenedor. http://20.12.0.2:9527/#/dashboard

**Comment by EdwinBetanc0urt** [comment]
https://user-images.githubusercontent.com/45974454/199325872-13ab14bb-5500-4c15-8af3-beebeb399224.mp4
