### ISSUE TITLE
POS: Límite de Porcentaje de Descuento

### ISSUE THREAD

**Issue by MarianaGallardo** [solop-develop/vue-1.0#547]
**Descripción del Error**
Se configura un usuario con límite de porcentaje de descuento  desde la pestaña _Vendedores Asignados_ , se coloca en el campo  _% Descuento Máximo_ el 15% al usuario Dayana Yépez, en el terminal de la caja **Caja 01 (CORPORATIVO)** y al hacer una orden y colocarle el descuento por más del 15%, permite realizarlo.

**Pasos para Reproducirlo**
Pasos para reproducir el error:
1. Ubicar el terminal de la caja **Caja 01 (CORPORATIVO)**
2. Configurar el usuario de Dayana Yépez con el 15% como porcentaje de descuento máximo.
3. Registrar un pedido
4. Colocar un porcentaje de descuento por más de 15%
5. Observar que permite hacer el descuento sin pedir pin.

**Comportamiento Esperado**
Que pida pin cuando se pase del límite que se establece en el campo _% Máximo de Descuento_

Se realizó la prueba en el contenedor local: http://20.12.0.2:55105/#/

Se configura un usuario con límite de porcentaje de descuento desde la pestaña Vendedores Asignados , se coloca en el campo % Descuento Máximo el 15% al usuario Dayana Yépez, en el terminal de la caja Caja 01 (CORPORATIVO) y al realizar el proceso indica lo siguiente:

![Screenshot 2022-10-31 2 21 30 PM](https://user-images.githubusercontent.com/44775211/199081867-1024fbfc-2f87-4f11-9369-24799f6aed0c.png)

En la imagen de arriba no pude capturar el mensaje que indica que fue actualizado al mismo tiempo del otro mensaje, por lo que vuelvo a cambiar el porcentaje y arroja:

![image](https://user-images.githubusercontent.com/44775211/199081387-11e30f79-2199-4184-ba01-795c0159a673.png)

A pesar de mostrar la cantidad que fue actualizada, al ubicar la orden por ADempiere o refrescar en el terminal pdv, se actualiza a 0,00 indicando que no se hizo el descuento. Debe automáticamente no mostrar el mensaje que fue actualizado, y que no actualice la cantidad si es el caso. Caso contrario que tenga el acceso, y se sobrepase el límite, entonces mostrar solicitud de pin para ser actualizado, si no se sobrepasa del límite y tiene acceso, entonces debe actualizarse sin irregularidad.

![image](https://user-images.githubusercontent.com/44775211/199110147-b3dc84a1-8766-441e-8632-4c9fc2efbced.png)

Usuario y Clave: corporativo@prosein.com

**Comment by MarianaGallardo** [comment]
Aún persiste el error en el contenedor:  http://20.12.0.2:9527/#/dashboard

**Comment by MarianaGallardo** [comment]
**NO APROBADO**
Se realizó la prueba en el contenedor local **http://20.12.0.2:55105/#/** 
**Versión 51.3**
**Usuario y Clave:** corporativo@prosein.com

A nivel de usuario, se observa que existe otro campo  **% Descuento Máximo por Linea** por lo cual se quita la configuración anterior y se coloca en ese campo el **15%** para el usuario indicado arriba. 

Se procede a realizar el proceso, se crea el pedido **OVT-8794** y se agregan 2 productos, a un producto se le coloca el porcentaje de descuento de 3% y efectivamente lo realiza sin problemas. Luego se procede a cambiar el porcentaje para el 15.10% ó 16% y arroja un mensaje que no se puede actualizar porque no tiene acceso, y visualmente se observa que deja el 16% pero internamente no lo realiza. Entonces:

1. Si sobrepasa el límite, debe pedir PIN
2. Si sobrepasa el límite, no debe seguir mostrando el porcentaje que al que se está actualizando sino el anterior ya que confunde al usuario.

![Screenshot 2022-11-03 1 42 10 PM](https://user-images.githubusercontent.com/44775211/199797475-4ab183c3-ab5f-4479-b9cd-ca1e98f2a527.png)
![Screenshot 2022-11-03 1 40 18 PM](https://user-images.githubusercontent.com/44775211/199797478-0e36d44c-d1da-47c8-91f1-c472392c35b5.png)
![Screenshot 2022-11-03 1 40 02 PM](https://user-images.githubusercontent.com/44775211/199797550-54240471-7de2-48fe-a136-5274240c54e7.png)
![image](https://user-images.githubusercontent.com/44775211/199797655-c58c1110-4e89-4031-92c6-e84040d693df.png)

**Comment by MarianaGallardo** [comment]
Prueba en http://20.12.0.2:55105/#

Avy tiene configurado hasta el 20% de descuento (Es supervisor)
Danilo tien configurado que hace descuento pero sin límite (Es supervisor)

Seleccioné la orden, y coloqué 21% permitió dejar hacer el descuento con el PIN de Avy. 

Usuarioy Clave de inicio de sesión: corporativo@prosein.com

PIN de Avy: 3569
PIN de Danilo: 260320

**Comment by MarianaGallardo** [comment]
Ya confirmado el cambio en la versión 51.4

**Comment by yamelsenih** [comment]
Esto está en manos de @rcapecce

**Comment by niclopup** [comment]
no se logra aplicar el control definido por usuario en el punto de venta según el campo 

![image](https://user-images.githubusercontent.com/31936815/203456970-19fa0084-e68e-4223-bf68-b960c2c294c1.png)

Si se intenta modificar directo en el campo descuento de la línea, permite siempre modificarlo. sin controlar si supera o no el límite.

![image](https://user-images.githubusercontent.com/31936815/203457301-56337265-3097-4163-84cc-b4bb88a32fee.png)


Si se intenta modificar desde el botón de editar la línea y luego me pide siempre un PIN

![image](https://user-images.githubusercontent.com/31936815/203457071-c862d1fc-7b44-4d9b-b713-2f35fecf27bb.png)

**Comment by EdwinBetanc0urt** [comment]
Se ajusto un inconveniente que tenia el porcentaje de descuento. Listo para pruebas

**Comment by niclopup** [comment]
por favor volver a ver este tema
Aún sigue sin funcionar

**Comment by elsiosanchez** [comment]
> no se logra aplicar el control definido por usuario en el punto de venta según el campo
> ![image](https://user-images.githubusercontent.com/31936815/203456970-19fa0084-e68e-4223-bf68-b960c2c294c1.png)
> 

Para que te tome la configuacion de la Pestaña de `Vendedores Asignados`. Debe estar marcado en verdadero el Campo `Permitir Asignar Vendedor` en el `POs Terminal` para que tome el valor del campo `Permitir Modificar Descuento (Por Linea) ` . Cabe destacar que este campo no se encuentra en el encabezado del pos por lo que solo es configurable dese la Pestaña de `Vendedores Asignados` 

https://github.com/solop-develop/frontend-core/assets/45974454/beb03e58-e555-41a3-aff9-25c9a8c33892
