### ISSUE TITLE
POS: Modificar Cliente

### ISSUE THREAD

**Issue by MarianaGallardo** [solop-develop/vue-1.0#550]
Prueba en el contenedor: http://20.12.0.2:55105/#/

Se realiza la prueba nuevamente luego de los cambios. Se obtiene como resultado:
1. Con el usuario que se configuró para que no permita modificar cliente, al darle al check después de modificar en el PDV, arrojó mensaje que no tiene acceso a modificar cliente, sin embargo cuando se selecciona de nuevo para modificar el cliente queda la información que se colocó por última vez, ésto causa confusión debido que el usuario puede interpretar que sí se hizo el cambio a pesar que mostró el mensaje. Lo más importante es que ciertamente no se actualizó la información en ADempiere de la modificación.

![Screenshot 2022-11-02 4 48 23 PM](https://user-images.githubusercontent.com/44775211/199599839-60002c6a-476a-4409-9382-24f4e2762156.png)

![Screenshot 2022-11-02 4 44 40 PM](https://user-images.githubusercontent.com/44775211/199599843-12f129e3-b2c0-46c6-80fd-842f621afb80.png)

2. Con el usuario que se configuró para permitir modificar cliente, le permite modificar el cliente porque lo muestra en ADempiere, pero no muestra mensaje de que fue actualizado el cliente, tampoco actualiza de una vez en el campo Socio de Negocio de la parte superior al crear la orden, pero sí lo actualiza en el formulario del Actualizar el socio de negocio. adjunto imagen de ejemplo:
![Screenshot 2022-11-02 4 52 29 PM](https://user-images.githubusercontent.com/44775211/199601660-fa84a952-fe71-426e-ba25-52aae35ccb08.png)

![Screenshot 2022-11-02 5 06 04 PM](https://user-images.githubusercontent.com/44775211/199602528-fefb59f9-f412-473a-ba26-fa327e66d13b.png)

**Comment by MarianaGallardo** [comment]
Asesor: marodriguez@prosein.com.ve con clave 1234567890* tiene el check tildado de modificar cliente, debió dejar modificar el cliente pero el resultado no fue satisfactorio debido que se visualiza en gris.

Asesor: mzamora@prosein.com.ve con clave mzamora@prosein.com.ve no tiene el check tildado para modificar cliente, al visualizar en el punto de venta, en efecto se ve en gris la opción.

Para el caso del primer asesor, se tildó el check del encabezado del punto de venta para chequear si estaba validando por allí, sin embargo el resultado no fue satisfactorio.

**Comment by MarianaGallardo** [comment]
**Versión 51.4**
**Actualizar Socio de Negocio**
-Cuando se actualiza el nombre, chévere.
-Cuando se actualiza tipo de persona, chévere.
-Cuando se actualiza la cédula, queda en blanco la parte de arriba donde dice socio de negocio, adjunto imagen.

**Comment by MarianaGallardo** [comment]
Ya al editar la cédula se visualiza el cambio, ya no se ve en blanco en la versión de la UI https://github.com/solop-develop/frontend-core/releases/tag/experimental-1.8.5

**Comment by yamelsenih** [comment]
Esto está en manos de @rcapecce
