### ISSUE TITLE
Modificar Cantidades en línea de orden de venta Divide en vez de Multiplicar el precio

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#561]
## Bug report

Modificar Cantidades en línea de orden de venta Divide en vez de Multiplicar el precio.

Además, la línea anterior por ejemplo se carga con 10 cantidades pero no multiplicó tampoco el precio por dicha cantidad.

#### Steps to reproduce

https://user-images.githubusercontent.com/31936815/200928583-e4fdf8cc-251e-49d3-aefb-777660c74556.mp4

1. [xxx]
2. [xxx]
3. [xxxx]

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:

**Comment by EdwinBetanc0urt** [comment]
En el log se detallan las siguientes advertencias

```log
-----------> GridTab.query: No link column [182]
===========> MProductPricing.calculatePriceBasedOnPriceList: No PriceList [182]
```

**Comment by EdwinBetanc0urt** [comment]
Corregido y listo para pruebas.
