### ISSUE TITLE
Campo: Instancia de Conjunto de Atributo de Producto > Crear/Editar Instancia de Conjunto de Atributo.

### ISSUE THREAD

**Issue by EdwinBetanc0urt** [solop-develop/vue-1.0#563]
https://user-images.githubusercontent.com/45974454/203586239-0da167f6-332b-4080-b57e-b89211cde84d.mp4

**Comment by niclopup** [comment]
Se ve bien el campo y cómo se busca entre los atributos del producto seleccionado, pero no se logra terminar de definir el Atributo en la línea de orden de Compra.


https://user-images.githubusercontent.com/31936815/203601515-6f8517d0-443e-4cdb-a2d5-ba9444802965.mp4
