### ISSUE TITLE
Ventana: Búsqueda > Búsqueda Avanzada > Mostrar campos marcados como selección.

### ISSUE THREAD

**Issue by EdwinBetanc0urt** [solop-develop/vue-1.0#566]
Se requiere que en el panel de la busqueda avanzada muestre puro los campos que esten marcado como `isSelectionColumn`

![image](https://user-images.githubusercontent.com/45974454/201666787-49d3ca58-65fb-4176-8548-c6d477d56464.png)

**Comment by niclopup** [comment]
Se agrega en la tabla C_Order el campo "DateOrdered" como "Columna Selección", se logra ver el campo para seleccionarlo en la búsqueda avanzada pero no encuentra ningún registro.


![image](https://user-images.githubusercontent.com/31936815/203604923-b6b569af-06b4-422b-b40d-741f5c8ed5f4.png)



https://user-images.githubusercontent.com/31936815/203605066-fe8fda81-00bf-4242-8747-6da7759a5cf6.mp4
