### ISSUE TITLE
Ventana: Búsqueda > Búsqueda Avanzada > Campos `Si-No` como lista `[' ', 'Si' 'No']`, para permitir omitir valor en la búsqueda.

### ISSUE THREAD

**Issue by EdwinBetanc0urt** [solop-develop/vue-1.0#568]
En el zk el dialogo de búsqueda renderiza los campos de `Si-No` como una lista de selección.

https://user-images.githubusercontent.com/20288327/201424614-d254e220-2967-4725-909a-c56db5e5dfef.mp4

**Comment by niclopup** [comment]
ok, filtra bien
