### ISSUE TITLE
Ventana: Complementos > Adjuntos > Descarga de Archivos

### ISSUE THREAD

**Issue by EdwinBetanc0urt** [solop-develop/vue-1.0#581]
https://user-images.githubusercontent.com/45974454/203352422-35112f2e-7b98-48a4-8d38-6085dedbb19b.mp4

**Comment by niclopup** [comment]
No se logra ya que da error 

Manejador de Archivos no encontrado


![image](https://user-images.githubusercontent.com/31936815/217611174-e3c6a8f8-d690-49a5-b012-6e2f5f1076a6.png)

**Comment by EdwinBetanc0urt** [comment]
Esto ya esta operativo en https://vue-develop.solopcloud.com

**Comment by niclopup** [comment]
no se logra descargar. 

se apreta el botón pero no hace nada

![image](https://github.com/solop-develop/frontend-core/assets/31936815/3463404c-5b4a-41f3-901b-cb4525ffa38a)

**Comment by EdwinBetanc0urt** [comment]
Corregido

https://github.com/user-attachments/assets/9ab14fa2-791a-4931-8d2b-cd378abc7a12
