### ISSUE TITLE
Ventana: Complementos > Adjuntos > Pre-visualización de Archivos

### ISSUE THREAD

**Issue by EdwinBetanc0urt** [solop-develop/vue-1.0#582]
https://user-images.githubusercontent.com/45974454/203352368-328b14ce-ca73-4914-bf7e-eda532b51148.mp4

**Comment by niclopup** [comment]
No se logra verificar ya que no hay manejador de archivos definido

**Comment by EdwinBetanc0urt** [comment]
Esto ya esta operativo en https://vue-develop.solopcloud.com

**Comment by niclopup** [comment]
Ok como mosaico

Falla como Grilla

![Captura de pantalla 2024-03-19 223616](https://github.com/solop-develop/frontend-core/assets/31936815/c8f62ca2-f61f-4efa-85b5-745e19dce583)

**Comment by Ricargame** [comment]
Cambios disponibles apartir de la versión: https://github.com/solop-develop/frontend-core/releases/tag/3.9.8


![image](https://github.com/solop-develop/frontend-core/assets/78000356/3e877a59-e43e-41ed-892d-fe48fe881d0c)
