### ISSUE TITLE
Ventana: Pestañas tipo Orden o Secuencia > Buscar en lista de registros de pestaña de secuencia.

### ISSUE THREAD

**Issue by EdwinBetanc0urt** [solop-develop/vue-1.0#587]
Existen pestañas de secuencia como la de `Orden de Despliegue` en la ventana `Formato de Impresión`, o la de `Secuencia de Campos` en la ventana de `Consulta Inteligente`, donde existen muchos registros, y puede facilitar el manejo tener un buscador de registros en este tipo de pestañas, en la interfaz zk o en la interfaz swing no es posible actualmente.

https://user-images.githubusercontent.com/20288327/202854991-d0f13862-27fe-4b02-8081-1ad6d13eb294.mp4

**Comment by EdwinBetanc0urt** [comment]
La nueva funcionalidad de búsqueda se ve de la siguiente manera:

https://user-images.githubusercontent.com/20288327/202855912-6e616eec-c7e8-47d2-a714-b9e3827f168f.mp4

Cabe destacar que si existe una búsqueda, la funcionalidad de arrastrar y soltar se deshabilita.

**Comment by niclopup** [comment]
OK
