### ISSUE TITLE
Reporte: Apertura > Árbol del Menú

### ISSUE THREAD

**Issue by elsiosanchez** [solop-develop/vue-1.0#59]
### Árbol de Menú
Aperturar un reporte dede el arbol de menú:
1. Desplegar el árbol de menu en **Gestión de Saldos Pendientes**.
2. Seleccionar el reporte **Saldos Abiertos**.

#### Requiere dar soporte para abrir los reporte desde el menú como actualmente se realiza en la interfaz ZK

![open-menu-zk](https://user-images.githubusercontent.com/45974454/168147215-d9a03f82-361d-4230-a0de-49f13f013a70.gif)

#### Actualmente en la interfaz de ADempiere-Vue se le dio soporte para abrir los reporte desde el menu

![open-menu-vue](https://user-images.githubusercontent.com/45974454/168147283-b8cceb4b-8693-4745-b8bf-9fa400e62210.gif)

**Comment by EdwinBetanc0urt** [comment]
https://solop-develop.github.io/frontend-core/es/guide/use-cases/reports.html#arbol-de-menu
