### ISSUE TITLE
Búsqueda de Producto en POS por Nombre toma última búsqueda

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#592]
## Bug report

Error búsqueda Punto de Venta: 

En algunas búsquedas de producto se toma un producto que no aplica correctamente, hay veces que lo encuentra, otras que no y otras que lo encuentra tarde cuando se está buscando otro producto

ElsioSanchez — hoy a las 16:10
Lo del producto el componente guarda la ultima búsqueda para el momento de escribir primero buscara en la lista que guardo de la búsqueda anterior si no la consigue lo buscara en el servidor 
Esto se hizo de la siguiente manera para evitar múltiples peticiones al servidor 
ElsioSanchez — hoy a las 16:10
con que criterio se puede replicar ? 
Nico López — hoy a las 16:13
bien entiendo, pero en este caso sucede que esta limitación genera una selección equivocada
podemos hacer alguna manera para que eso no funcione así?
entiendo el objetivo de cargar menos las consultas, pero esto hace que se lleve a un error en la búsqueda por el nombre
EdwinBetanc0urt — hoy a las 16:15
Hola Nico López , no guardar el resultado de la búsqueda , de esa manera haría más peticiones al servidor
Nico López — hoy a las 16:16
podemos hacer una prueba a ver que implicaría dejarlo asi?
entiendo que se quiere limitar las consultas, pero de esta manera puede ocasionar un error si no se da cuenta el usuario y no puede ser
EdwinBetanc0urt — hoy a las 16:19
Aca realmente no sucede, porque utilizan lector de codigo de barras por lo que la busqueda no se repite
Nico López — hoy a las 16:21
pero en el caso de los códigos de Barra entiendo que tampoco ahorraría nada en la consultas al servidor el hehcho de que guarde la última oconsulta... no?
EdwinBetanc0urt — hoy a las 16:21
podrías explicar como es el flujo donde sucede? ahí analizamos cual seria la forma mas correcta para que tenga un buen funcionamiento sin tener que sacrificar el rendimiento, ya que esa búsqueda (de productos) específicamente es un poco pesada
EdwinBetanc0urt — hoy a las 16:22
si pero al reducir la coincidencia con un código único, es mas rápido y exacto
Puedes crear el issue para revisarlo?
lo otro que se puede hacer es que si se tienen 3 o menos caracteres en la búsqueda, busque primero en la lista local, si este no tiene coincidencias, busque en el servidor (como ya hace), y adicionalmente si tiene mas de 3 caracteres (aunque tenga coincidencias con la lista local) haga la búsqueda remota al servidor
Nico López — hoy a las 16:48
es que la verdad si en un punto de venta se busca en algun caso por el nombre, no veo correcto tomar estos supuestos de que busque primero entre la última búsqueda para obtener un producto. es muy riesgoso ya que puede que se defina un producto automáticamente que nunca se pidió y esto no puede pasar nunca
Nico López — hoy a las 16:48
pero no entiendo como aplicaría en repetir la búsqueda si se utilizan el códiugo EAN
son todos únicos, no estaría nucna buscando sobre la bísqueda anterior... por eso no entiendo con que objetivo lo están utiolizando ustedes actualmente si sólo se buscan con el códugo de Barra.

#### Steps to reproduce

1. [xxx]
2. [xxx]
3. [xxxx]

#### Screenshot or Gif（截图或动态图）

https://user-images.githubusercontent.com/31936815/203155358-c304afca-ab2e-4019-8574-0ba80ec3a11a.mp4

https://user-images.githubusercontent.com/31936815/203155377-03e1e29a-1590-453e-a305-42e25f451a4c.mp4

Se hace una prueba de elegir un producto diferente y luego volver a repetir el caso que definía incorrectamente el producto y no se repite más.

https://user-images.githubusercontent.com/31936815/203155391-6632d5ae-7014-4e21-81f2-9663b3e130e2.mp4

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:

**Comment by EdwinBetanc0urt** [comment]
Se elimina la persistencia de datos, siempre que tenga 3 o mas caracteres hará siempre una búsqueda al servidor, ya que se elimino la búsqueda local.
