### ISSUE TITLE
Metodo de Pago (PDV)

### ISSUE THREAD

**Issue by silvianapatricia** [solop-develop/vue-1.0#593]
**Descripción del Problema**
Se creo a nivel del terminal un nuevo método de pago para el Terminal de Caja 1 (Acarigua), 14_PDV-MERCANTIL

![image](https://user-images.githubusercontent.com/36901843/203160880-9914c13b-c108-42f2-9c9d-ec791593e17b.png)

El mismo no se visualiza a nivel del PDV ya que solo muestra a nivel de lista 15 Registro 

![image](https://user-images.githubusercontent.com/36901843/203161278-3f91d92e-5425-4563-a44d-93d209dfa342.png)

**Comment by EdwinBetanc0urt** [comment]
Se aumenta la cantidad máxima de registros que trae en los métodos de pago, ahora es de 50 registros.

**Comment by silvianapatricia** [comment]
Se verifico
--


![image](https://user-images.githubusercontent.com/36901843/203392265-e4649232-76cc-4df0-85d2-8f90844ea47c.png)


Servicio: http://20.12.0.2:9527/
