### ISSUE TITLE
POS Acción de Copiar en búsqueda de producto

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#597]
## Feature request

Actualmente veo que existe la opción de Copiar un producto desde la línea del punto de venta. Acción que entiendo puede ser útil para facilitar la identificación de un producto que esté definido en una línea.

![image](https://user-images.githubusercontent.com/31936815/203411814-0dce2a85-4bbb-4603-9192-d3d1abc6253b.png)

Ahora creo que sería de mucha utilidad que esta opción esté también en el buscador de producto 

https://user-images.githubusercontent.com/31936815/203412190-3f1f54f2-dd97-44f5-9246-f5ef26345cee.mp4

![image](https://user-images.githubusercontent.com/31936815/203412284-0854b6e4-a9c8-41bf-952c-49a54cdaaab0.png)

**Comment by EdwinBetanc0urt** [comment]
En la linea se agrego para facilitar aumentar la cantidad del producto, en el buscador con seleccionar y pulsar el botón de aceptar o simplemente con doble clic agrega el producto y aumenta la cantidad si ya existe

**Comment by niclopup** [comment]
> En la linea se agrego para facilitar aumentar la cantidad del producto, en el buscador con seleccionar y pulsar el botón de aceptar o simplemente con doble clic agrega el producto y aumenta la cantidad si ya existe

Muchas gracias Edwin

Lo que decis la verdad que si funciona sería lo ideal, ya que permitiría siempre tener una búsqueda completa y ágil de todo lo que se desea buscar.
Actualmente intenté que con hacer doble click, o oprimiendo el botón de Aceptar se agregue el producto a la línea de la orden pero no lo logré. Es jutamente lo que estaría necesitando

Por favor podrías confirmarme si eso funciona tal como decis? muchas gracias

**Comment by EdwinBetanc0urt** [comment]
Efectivamente, con doble clic no estaba agregando el producto, se agrego la funcionalidad, adicionalmente también se agrego la opcion de copiar codigo en la tabla de registros del producto 

![Screenshot_20221125_175059](https://user-images.githubusercontent.com/20288327/204058302-a4a41eba-9853-42f8-9a14-85f11f8eb981.png)
