### ISSUE TITLE
Proceso: Carga > Parámetros

### ISSUE THREAD

**Issue by elsiosanchez** [solop-develop/vue-1.0#6]
Saludos, se propone implementar un componente dinámico que llame mediante carga diferida a componentes de campo en base a referencias de ADempiere. Este componente será el que comunique los campos con las vistas, tomando las principales validaciones como de solo lectura, visualización y obligatorias y mostrando la referencia del campo correspondiente.

Cargando los campos y sus metadatos desde el diccionario de la aplicación. Allí, con el atributo 'displayType', se le asigna el atributo 'componentPath'.

https://github.com/adempiere/adempiere-vue/blob/develop/src/utils/ADempiere/dictionaryUtils.js#L388

![image](https://user-images.githubusercontent.com/45974454/166722552-605e9de7-02c4-4824-852f-a3d711dfa01b.png)

La ruta del componente a mostrar se almacena en la constante 'REFERENCIAS', que devuelve la ruta del componente (en el atributo tipo) según el tipo de visualización (en el atributo alias o id de la referencia).

![image](https://user-images.githubusercontent.com/45974454/166722810-03dbc228-4f36-4f1d-994b-072627da68e2.png)

Con la etiqueta genérica 'componente' y la ruta del componente a importar en el atributo 'es', realiza el renderizado para visualizar la referencia del campo correspondiente.

![image](https://user-images.githubusercontent.com/45974454/166723356-13304d89-e184-475e-98f1-1dcfb1fa6bc7.png)
![image](https://user-images.githubusercontent.com/45974454/166723433-c7dc334d-93e1-4527-8d01-62eff11a6160.png)

Para más información: https://vuejs.org/v2/guide/components-dynamic-async.html

Como resultado mostrará los diferentes tipos de campos asociados a las referencias.

![image](https://user-images.githubusercontent.com/45974454/166723647-90dad0d9-d82e-4dae-b3cd-0631c74087b5.png)

**Comment by elsiosanchez** [comment]
Error en el campo del Proceso (**Transferencia Bancaria** )
https://demo-ui.erpya.com/#/7aa4242a-93c0-42d8-92be-8250002d3e3c/d97027fd-4cd5-445e-8fd8-ef5d3f7959b4/process/53190

El campo tipo selec (** Bank Account To**) se queda cargando y nunca trae resultados

![image](https://user-images.githubusercontent.com/45974454/166819724-40e3faaa-6ef9-4c6d-ac04-405d2099ab65.png)


### Curl de la LLamada `lookup-items`
```shell
curl --location --request GET 'https://api.erpya.com/api/adempiere/user-interface/window/lookup-items?process_parameter_uuid=a43deb2a-fb40-11e8-a479-7a0060f0aa01&search_value=&token=1968440b-0625-430d-9f75-74099c89048b&language=es
```

Error de la consulta del SQL

```shell
{"code":500,"result":"Pestaña Cláusula Where SQL Unparseable\nPestaña Cláusula Where SQL Unparseable"}
```



###  Logs del back-end

![image](https://user-images.githubusercontent.com/45974454/167020008-0c6b466d-805a-433f-82c5-293f0464c772.png)

**Comment by elsiosanchez** [comment]
En este PR se solvente el problema

https://github.com/adempiere/adempiere/pull/3814/files#diff-b5a2da6051c90ee9a616897a9fc3f17653d6f54969d0b2beadbca803c7d7ff1bR143

https://github.com/adempiere/adempiere/issues/3812

![image](https://user-images.githubusercontent.com/45974454/167020735-b7df4289-0c7f-464c-b40e-1d49b3520e26.png)

**Comment by EdwinBetanc0urt** [comment]
Los casos de uso para esta funcionalidad se pueden ver aquí:
https://solop-develop.github.io/frontend-core/es/guide/use-cases/process.html#parametros
