### ISSUE TITLE
Reporte: Apertura > Buscador del Menú

### ISSUE THREAD

**Issue by elsiosanchez** [solop-develop/vue-1.0#60]
### Buscador del Menú
Aperturar un reporte desde el buscador del menú:
### Pasos
1. Desplegar el árbol de menu.
2. En el buscador de la parte superior escribir **Saldos Abiertos**.
3. Seleccionar el reporte coincidente con el resultado.

##### Versión ZK:
Para abrir los reportes desde el buscador del menú como actualmente desde la interfaz ZK 

![open-search-menu](https://user-images.githubusercontent.com/45974454/168148566-bfc2cb88-b2cb-4884-bb7d-6f6ce2c23e37.gif)

##### Versión Vue:
Actualmente en la interfaz de ADempiere-Vue se le dio soporte para abrir los reportes desde el buscador del menú. Tambien se cambio de ubicación del buscador del menú al encabezado de la interfaz de ADempiere-Vue para una busqueda mas rapida y agradable para los usuarios

![open-search-menu-vue](https://user-images.githubusercontent.com/45974454/168148633-1a0c41f7-fd04-49a3-a199-4314e5be3158.gif)

**Comment by EdwinBetanc0urt** [comment]
https://solop-develop.github.io/frontend-core/es/guide/use-cases/reports.html#buscador-del-menu
