### ISSUE TITLE
[Bug Report] Doble Facturación de Orden en POS

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#600]
## Bug report
Cuando se apreta el botón del "Carrito" y el usuario abre nuevamente la sección del Cobro y apreta nuevamente el bnotón del carrito, se genera 2 facturas. Si bien por suerte parce que la factura se genera sólo sobre la "Cantidad pendiente de Facturar", la 2da factura se genera por CERO unidades pero de todas maneras no debería de permitir generar nuevamente una factura de alguna manera.

https://user-images.githubusercontent.com/31936815/203595514-b6394345-21c8-44d8-b8d5-57550894ae9c.mp4

#### Steps to reproduce

1. [xxx]
2. [xxx]
3. [xxxx]

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:

**Comment by EdwinBetanc0urt** [comment]
Se agrego validación con la carga, de manera que si aun no se ha recibido una respuesta del primer cobro en curso, el usuario no puede volver a darle clic a la cobranza.
