### ISSUE TITLE
Acercar desde Campo Socio del Negocio no abre el registro desde donde se navegó

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#601]
## Bug report
Al acercar en un registro, en ZK abría la ventana definida pero en el registro desde donde se está acercando.

Ahora si bien abre correctamente la ventana de la tabla del registro,  no muestra el Socio del Negocio desde donde se navegó.

Se intenta también guardando el registro pero tampoco lleva al ID del SDN definido en el campo.

#### Screenshot or Gif（截图或动态图）

https://user-images.githubusercontent.com/31936815/203600078-7e7b845f-98f0-4fa4-abc5-c531c26d489e.mp4

**Comment by EdwinBetanc0urt** [comment]
Corregido y listo para pruebas

**Comment by niclopup** [comment]
No se logra acercar desde ventana Orden de Compra

https://user-images.githubusercontent.com/31936815/217613382-f1cf77bc-a4aa-4c34-82fc-da08b789637e.mp4

**Comment by EdwinBetanc0urt** [comment]
Corregido

https://user-images.githubusercontent.com/20288327/219699007-5a2bb946-f7d8-4305-a1d4-4be3f0b78236.mp4
