### ISSUE TITLE
Reporte: Apertura > Elementos Recientes

### ISSUE THREAD

**Issue by elsiosanchez** [solop-develop/vue-1.0#61]
### Ítems Recientes
Aperturar un reporte de ítems recientes:
### Pasos a Seguir
1. Ubicar el tablero **Ítems Recientes**.
2. Seleccionar caulquier reporte o en caso de usar la busqueda rapida de la tabla de ítems recientes seeleccione la  coincidencia del resultado.

#### Versión ZK:
![open-recient-item-zk](https://user-images.githubusercontent.com/45974454/168151500-bd9f9c26-7ca1-4028-95dc-e48c19fae99e.gif)

#### Versión Vue:
Actualmente en la interfaz de ADempiere-Vue se le dio soporte para abrir los procesos desde los favoritos o artículos recientes. También se cambió la visualización ya que ahora son unas tarjetas y el cual puedes realizar búsquedas rápidas dentro de ellas para mejor la experiencia del usuario a abrir un proceso desde los favoritos o Artículos recientes
![open-recient-item-vue](https://user-images.githubusercontent.com/45974454/168151519-4745e702-57b8-4e62-93a0-e426cd8297bc.gif)

**Comment by niclopup** [comment]
como el Scroll no funciona actualmente, no puedo validarla aún

**Comment by EdwinBetanc0urt** [comment]
solucionado en https://github.com/solop-develop/frontend-core/pull/193
