### ISSUE TITLE
búsqueda en Ventanas como System busca en Español cuando el nombre está en Inglés

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#612]
## Bug report

Si uno ingresa al sistema con un Rol SYSTEM y abre la ventana "Ventana, pestaña, campo" para hacer la búsqueda en buscar registros, se debe poner el nombre en español para que aparezcan ventanas que tienen nombre en inglés.

esto es lo que se busca? no es muy claro ya que uno tiene que escribir algo en un idioma que el resultado trae registros en otro idioma.

#### Screenshot or Gif（截图或动态图）

https://user-images.githubusercontent.com/31936815/204646686-07971c63-1e06-4ef0-9507-1de4421c32cc.mp4

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:

**Comment by EdwinBetanc0urt** [comment]
También sucede en los campos tipo búsqueda

https://user-images.githubusercontent.com/20288327/204689179-be2eb7d3-047b-4eab-ac1d-f8ff41cb5c62.mp4

**Comment by EdwinBetanc0urt** [comment]
Listo para pruebas en https://vue-develop.solopcloud.com
