### ISSUE TITLE
Reporte: Apertura > Menú de Relaciones

### ISSUE THREAD

**Issue by elsiosanchez** [solop-develop/vue-1.0#62]
Aperturar un reporte desde las relaciones del mismo nivel del menú:

Actualmente en el cliente ZK de ADempiere no cuenta con una caracteristica equivalente.

### Pasos a seguir

1.  Desplegar el árbol de menú en **Gestión de Saldos Pendientes**
2.  Seleccione el reporte de **Saldos Abiertos a la Fecha**
3.  Desplegar la lista del el menú de relacciones, en la parte superior a la derecha de la ventana.
4. Ubicar y seleccionar el reporte **Saldos Abiertos**.

#### Versión Vue:
![open-relations-vue](https://user-images.githubusercontent.com/45974454/168153143-74f95fda-3c47-47f2-a50c-769ee5a09348.gif)

**Comment by EdwinBetanc0urt** [comment]
https://solop-develop.github.io/frontend-core/es/guide/use-cases/reports.html#relaciones

**Comment by EdwinBetanc0urt** [comment]
Este componente queda depreciado al ser redundante con la funcionalidad y sobrecargar la vista al usuario.


https://user-images.githubusercontent.com/20288327/173915949-baccb3a5-0bc4-4f6b-a3ae-74c2c49c9f67.mp4

**Comment by niclopup** [comment]
Se da por entregado pero en realidad no se verifica ya que justamente no está la opción
