### ISSUE TITLE
POS PIN al cambiar precio

### ISSUE THREAD

**Issue by MarianaGallardo** [solop-develop/vue-1.0#627]
Prueba en contenedor local: 
http://20.12.0.2:55150/#     
http://20.12.0.2:55901/

Usuario y Clave: aliavila@prosein.com.ve
Orden de Venta: OVT-8814

Se desea cambiar el precio de la orden, pero al cambiar indica que se debe ingresar el pin. A pesar que el usuario está configurado que puede modificar precio. El usuario es Alirio Ávila y para ingresar, arriba están los datos.

**Comment by EdwinBetanc0urt** [comment]
Esto fue corregido en el backend. El inconveniente es que no estaba considerando la configuración del check Modificar Precio del vendedor, solo el del Terminal PDV.
