### ISSUE TITLE
Ventana: Complementos > Adjuntos > Eliminar Archivos

### ISSUE THREAD

**Issue by EdwinBetanc0urt** [solop-develop/vue-1.0#630]
https://user-images.githubusercontent.com/20288327/205613323-7668bfe4-e5e3-4574-9329-454a3dce5af7.mp4

**Comment by EdwinBetanc0urt** [comment]
https://user-images.githubusercontent.com/20288327/205421953-3133917d-1f52-4833-a12c-1844984cdc18.mp4

**Comment by niclopup** [comment]
no se puede adjuntar

**Comment by EdwinBetanc0urt** [comment]
Esto ya esta operativo en https://vue-develop.solopcloud.com
