### ISSUE TITLE
[Bug Report] Callouts: Cuando se cambia el Socio de Negocio no actualiza el valor de visualización de Dirección

### ISSUE THREAD

**Issue by EdwinBetanc0urt** [solop-develop/vue-1.0#636]
#### Steps to reproduce

1. Abrir la ventana `Òrdendes de Venta`.
2. Seleccionar `Nuevo` en el encabezado para establecer los valores por defecto.
3. Seleccionar distintos socios de negocio que tengan registros en la `Dirección`

#### Screenshot or Gif（截图或动态图）

https://user-images.githubusercontent.com/20288327/205949599-a155a39e-c6ef-4bb3-8c71-a79deba38c58.mp4

#### Expected behavior
Nótese como en el campo `Dirección` no se muestra el valor de visualización, solo el identificador. Al intercambiar de socios de negocio debería mostrar la dirección correspondiente al socio de negocio previamente establecido.

**Comment by niclopup** [comment]
Funciona correctamente sólo si el Nuevo SDN tiene una Localización definida.

Si se selecciona un SDN que no tiene ninguna localización deja la localización del SDN anterior

![image](https://user-images.githubusercontent.com/31936815/233260861-81243ec6-a8dd-4478-8029-7ace517ce75c.png)
