### ISSUE TITLE
Reporte: Carga > Validación Dinámica

### ISSUE THREAD

**Issue by elsiosanchez** [solop-develop/vue-1.0#64]
Para verificar esta funcionalidad:

1. Abrir reporte de `Detalles de MRP`.
2. Listar los valores del parámetro `Almacén`, nótese que aparece solo `*`.
3. Listar los valores del parámetro `Organización` y seleccionar `HQ`.
4. Volver a listar los valores del parámetro `Almacén`, verificar que los valores listados cambiaron, en función del valor que se seleccione en `Organización`.

https://user-images.githubusercontent.com/20288327/171209288-efac3aba-afcb-40c9-ad76-40d12f45fc51.mp4

**Comment by EdwinBetanc0urt** [comment]
Esta funcionalidad esta soportada en la interfaz vue:


https://user-images.githubusercontent.com/20288327/171209592-09f16ad6-9ebb-4c00-bdc8-b8a5083e03cf.mp4
