### ISSUE TITLE
Mejorar visor de Actividades Flujo de Trabajo

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#643]
## Feature request

Actualmente la ventana de "Flujo de Actividades" donde se realizan las aprobaciones puede ser mejorada para lograr una mejora sustancial frente a ZK.

A continuación agrego algunas ideas conversadas hoy junto con Edwin:

![image](https://user-images.githubusercontent.com/31936815/206285181-c9f1f075-7697-4583-9c33-65790c833d33.png)

- [x] Agregar Botones de Acciones para poder Aprobar documentos y Completarlos

![image](https://user-images.githubusercontent.com/31936815/206285651-cae3ce08-bd92-43a9-91e1-98ebf7c9a317.png)

- [x] #654

Actualmente desde un Móvil se ve así:
![image](https://user-images.githubusercontent.com/31936815/206285995-0f18f9c3-4d39-4661-b071-2230d019f8f6.png)

Cambiar el orden de los campos:

1. Bitácora de cambios
2. Acción
3. Flujo de trabajo visual (dejar de alguna manera oculto para que no se vea siempre, sólo si se desea se abre la sección y se visualiza)

- [x] Agregar datos que actualmente se definen en la "Bitácora de Cambios" en el texto que se visualiza si se hace click sobre un Nodo, de manera que el flujo de trabajo ya no será más Estático, sino que se mostrará lo que tiene cada nodo en cada uno de los documentos que se estarán aprobando.

https://user-images.githubusercontent.com/31936815/206287764-cf83c968-4a25-4ca3-82e6-6701d26c2830.mp4

![image](https://user-images.githubusercontent.com/31936815/206287858-24b44a22-9f4e-440c-8a34-e866f1d11960.png)

- [ ] Agregar datos del Registro en la Acción: Actualmente no se visualiza el Nro de Documento, Tipo de Documento, Importe,  Socio del Negocio, agente comercial. Esta información sólo se puede visualizar desde la "Bitácora de Cambios" lo que hace que no sea tan fácil ni rápido de ver. Sería bueno si agregamos unos campos ya que estos datos entiendo que existen al tener el botón de "Acercar", teniendo el ID del Registro y su Tabla, podemos obtener también esta información que se está aprobando.

**Comment by EdwinBetanc0urt** [comment]
Aun falta mejorar en el diseño mobil


![Image](https://user-images.githubusercontent.com/20288327/215941954-1f8d5777-7202-40a6-8746-2316a83d35b8.png)

**Comment by niclopup** [comment]
> Aun falta mejorar en el diseño mobil
> 
> ![Image](https://user-images.githubusercontent.com/20288327/215941954-1f8d5777-7202-40a6-8746-2316a83d35b8.png)

Veo que ya se corrigió el responsive viendo desde el celular, es correcto?

lo único que ahora no veo es el check para poder darle el ok

![image](https://user-images.githubusercontent.com/31936815/216966854-77c3a3b4-02ff-4998-b970-6d737a0233b7.png)

Yo desde el teléfono le sacaría el Flujo de trabajo si se puede, sólo que se vea la bitácora para ver los datos y un texto de abajo para escribir llegado el caso.

Pero ahora sin el check no se puede aprobar desde el teléfono.

Una pregunta ahora tampoco veo las notificaciones desde el teléfono y veo que vos en tu foto si la veías. Se modificó esto?


Avisame si te parece que cree una nueva issue por esto

**Comment by niclopup** [comment]
no se ve el acercar ni el check del OK

tampoco se ve en el teléfono la barra de inicio de búsqueda y las notificaciones

**Comment by niclopup** [comment]
Corregir cómo se visualiza en el Celular. En mi caso aún no logro ver correctamente la información que se necesita.

Si bien están una arriba de la otra, el espacio de las líneas en cuestión es muy pequeño para permitir visualizar correctamente.

lo más importante que se debería ver de manera AMPLIA debería ser los FLUJOS A APROBAR.

Las secciones siguientes de "Bitácora de Cambios" puede ser útil para ver más información del documento pero debería estar colapsado por defecto, al menos desde el móvil. en caso que no se pueda colapsar sólo en un móvil entonces lo dejaría colapsado y cualquier cosa que el usuario lo abra si quiere ver info.

El Flujo gráfico desde un móvil no sirve de nada y molesta ya que hay poco espacio y mostrar eso que es grande no tiene mucho sentido. EN todo caso lo dejaría Colapsado por efecto y cualquier cosa lo abre. Esto creo que podría ir perfectamente siempre colapsado y si desean  verlo que lo abran.

![Screenshot_2023-04-20-00-20-56-683_com android chrome](https://user-images.githubusercontent.com/31936815/233252873-76915891-88ff-4ae6-a636-802ef605a7e3.jpg)

**Comment by niclopup** [comment]
Se agregan además nuevos puntos en la Issue #971

**Comment by niclopup** [comment]
Creo que sigue estando muy chico la tabla donde se ven los Documentos pendientes de aprobación. Es lo más importante y debería tener más protagonismo en esta ventana.

El Diagrama de flujo debería estar "Colapsado" por defecto, si se desea visualizar se puede abrir. 

La tabla de "Sus Actividades de Flujo de Trabajo" debe ser lo más predominante, incluso hasta lo pondría 70% del ancho total y 30% dejaría a la bitácora de cambios que normalmente es mucho menos texto y todo para abajo

![image](https://github.com/solop-develop/frontend-core/assets/31936815/755c98d1-3d3a-4037-82cc-4602357220d3)

**Comment by niclopup** [comment]
Error:
no se ve el check de correr eñl proceso y aprobar finalmente con Zoom 100%, 

Mejoras:
Definiría más más pequeña la letra para q entre más

![image](https://github.com/solop-develop/frontend-core/assets/31936815/8bd279b3-add0-4cf9-99e3-bf7e4547bc21)

Rojo lo achicaria

Azul lo agrandaría

"Sus actividades de Trabajo las agrandaría para q ocupe el 3/4  o 2/3 del ancho.

Bitácora de cambios con 1/3 o 1/ alcanza bien

**Comment by EdwinBetanc0urt** [comment]
Los cambios fueron aplicados




![Image](https://github.com/solop-develop/frontend-core/assets/20288327/e57c22f9-f2a7-4848-adca-a1292725c367)
