### ISSUE TITLE
Ventana Proyectos con Errores

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#645]
## Bug report

Se encuentran varios errores en esta ventana:

1. Lógica de mostrar / Ocultar pestañas

Dentro de la ventana proyectos, la misma tiene una lógica que según el dato definido en el nivel de línea, se muestra unas pestañas y se ocultan otras.

En este ejemplo se modifica un proyecto definiendo el "Nivel de Línea" Fase, se supone que se deben ocultar la pestaña "Línea del Proyecto" y mostrar la pestaña Fase y Línea de Fase.

No se oculta la ventana Líneas del Proyecto

https://user-images.githubusercontent.com/31936815/206291124-07fedc40-8a86-42d0-bb2e-12cc38d49620.mp4

2. Dentro de la Fase, esxiste un campo llamado "Porcentaje Completado"

![image](https://user-images.githubusercontent.com/31936815/206290885-e15aae47-bf0a-4431-85ec-d51d55a9eaed.png)

No se logra encontrar el mismo en la pestaña Fase en VUE.

#### Steps to reproduce

1. [xxx]
2. [xxx]
4. [xxxx]

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:

**Comment by EdwinBetanc0urt** [comment]
https://user-images.githubusercontent.com/20288327/212895917-e0020a24-8aad-44dc-88b4-18142888e9b0.mp4

**Comment by niclopup** [comment]
ok, veo que se agrega la lógica de mostrar o no las pestañas según el nivel... ahora no puedo navegar a las Fases de ninguna manera. 
Se intenta con nivel FASE y TAREA pero sigue estando sólo lectura. 

![image](https://user-images.githubusercontent.com/31936815/233258086-a8f1e994-b601-4ebf-877d-5fed40a68fc2.png)

![image](https://user-images.githubusercontent.com/31936815/233258154-e7f02752-3bb1-4322-b9a5-5a0eef23a9ba.png)
