### ISSUE TITLE
Ventana "Todas las Solicitudes" y "Solicitudes"

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#646]
## Feature request

Se desea aplicar algunos efectos nuevos en la ventana "Todas las Solicitudes" para que se pueda emular lo que actualmente tenemos en ZK.

**Color según Campo**

Se desea poder definir un color en un campo según su valor. Igual a como sucede actualmente con el campo "Estado del Documento" en ventana Órdenes de venta

![image](https://user-images.githubusercontent.com/31936815/206291511-9893647e-bba3-4b6f-bb9a-e8cf42a7812f.png)

Ejemplo en ZK

https://user-images.githubusercontent.com/31936815/206294223-48806330-8a45-440e-a752-dc60bf9efe3b.mp4

Campo: Tipo de Vencimiento 

Este campo se define por diccionario su "Definición de campo" donde se setea el color por la condición.

![image](https://user-images.githubusercontent.com/31936815/206292590-d3a2046a-a7f4-47a7-a912-2aff287e0939.png)

No se cómo se haría en VUE pero la idea sería que según sea el tipo de vencimiento, se defina el mismo con un COLOR.

Este color puede estar bien mismo en el campo "Tipo de Vencimiento" o en un nuevo campo que sea tipo semáforo. mejor si es el mismo campo de Tipo de Vencimiento.

Vencido: ROJO
Por Vencer: Amarillo
Programado: Verde

![image](https://user-images.githubusercontent.com/31936815/206291617-9aad01a7-1b7f-40db-afa6-99e29251be13.png)

Campo no se visualiza en Grilla:

no se por que razón, este campo no se logra visualizar en grilla si es agregado en la vista mono registro.

https://user-images.githubusercontent.com/31936815/206294123-910dd1f9-4eaf-4077-989a-8a7289c6a680.mp4

**Avance con Progreso**

En las Solicitudes no se encontró un cmpo que sea sólo de % de avance (estaría bueno tenerlo) pero si se encontró un cmapo de "Estado Tarea" que tiene un % y un texto. No se si podemos utilizar esta para definir un Progress 

![image](https://user-images.githubusercontent.com/31936815/206293295-3e01196a-a0c9-439d-86b5-69389d7f691a.png)

![image](https://user-images.githubusercontent.com/31936815/206293410-3e89f530-7f58-4ef3-bd13-2701a9e6942f.png)

![image](https://user-images.githubusercontent.com/31936815/206289130-7e716ed7-ea94-4284-b4bb-81bc7bfd11c1.png)

**Comment by EdwinBetanc0urt** [comment]
Este issue es considerado aun? ya que se cuenta con el nuevo formulario de solicitudes

![imagen](https://github.com/solop-develop/frontend-core/assets/20288327/eafe7c18-af8a-4fb9-a6bc-89b2607cbf87)
