### ISSUE TITLE
Progreso en % mostrar con una Barra gráfica

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#651]
## Feature request

Agregar Campo de Progreso de manera gráfica con una Barra

**Avance con Progreso**

En las Solicitudes no se encontró un cmpo que sea sólo de % de avance (estaría bueno tenerlo) pero si se encontró un cmapo de "Estado Tarea" que tiene un % y un texto. No se si podemos utilizar esta para definir un Progress 

![image](https://user-images.githubusercontent.com/31936815/206293295-3e01196a-a0c9-439d-86b5-69389d7f691a.png)

![image](https://user-images.githubusercontent.com/31936815/206293410-3e89f530-7f58-4ef3-bd13-2701a9e6942f.png)

![image](https://user-images.githubusercontent.com/31936815/206289130-7e716ed7-ea94-4284-b4bb-81bc7bfd11c1.png)

**Comment by EdwinBetanc0urt** [comment]
De la siguiente manera se muestra el primer prototipo, aunque se debe cambiar a un campo numérico o de cantidad para el calculo correcto de porcentaje, ya que el enfoque actual no es el adecuado y puede tender a errores.

![2022-12-15_00-31](https://user-images.githubusercontent.com/20288327/207772986-581a0b32-ba48-4236-ba99-83839bbedf70.png)

**Comment by EdwinBetanc0urt** [comment]
A solicitud se cambio el color de la barra de progreso:

![Screenshot_20221216_075042](https://user-images.githubusercontent.com/20288327/208112485-794702ec-2184-4d94-b57c-d8bcb27707a5.png)

**Comment by niclopup** [comment]
entiendo que aún no estaría realizado esto de la manera que sugirió Yamel que se haga.

Definir cómo se debería hacer correctamente para aplicarlo como debe ser. 

En caso de poder validarlo como está ahora volver a asignarme la petición

**Comment by EdwinBetanc0urt** [comment]
Considero que esta resuelto con el formulario de `Issues`

![imagen](https://github.com/solop-develop/frontend-core/assets/20288327/4c88e599-5254-4827-9fbe-c033a49da954)
