### ISSUE TITLE
Cambiar la visual de la ventana para que sea más amigable a ver desde un móvil: Pasar todo a una columna en vez de 2 como está ahora, de manera que haciendo Scroll se logra ver todo.

### ISSUE THREAD

**Issue by EdwinBetanc0urt** [solop-develop/vue-1.0#654]
Actualmente desde un Móvil se ve así:
![image](https://user-images.githubusercontent.com/31936815/206285995-0f18f9c3-4d39-4661-b071-2230d019f8f6.png)

Cambiar el orden de los campos:

1. Bitácora de cambios
2. Acción
3. Flujo de trabajo visual (dejar de alguna manera oculto para que no se vea siempre, sólo si se desea se abre la sección y se visualiza)

**Comment by EdwinBetanc0urt** [comment]
Corregido



![Image](https://github.com/solop-develop/frontend-core/assets/20288327/dbb71e17-6ba0-4ef4-8a20-db6f59dc5cce)

**Comment by niclopup** [comment]
![Screenshot_2023-05-23-22-09-11-837_com android chrome](https://github.com/solop-develop/frontend-core/assets/31936815/6cdac413-2978-4612-ad10-4d836d579f79)

**Comment by niclopup** [comment]
![Screenshot_2023-05-23-22-09-11-837_com android chrome](https://github.com/solop-develop/frontend-core/assets/31936815/3e5875dd-063a-4f3e-bce5-7489eca7297c)

**Comment by niclopup** [comment]
todavía se visualiza el flujo en el fondo lo que hace que toda la ventana sea dificil de comprender

![image](https://github.com/solop-develop/frontend-core/assets/31936815/7801bd87-1a1f-4c48-9d88-14460708d92d)

el flujo entiendo que no se debería mostrar o al menos que esté siempre oculto ya que desde el móvil es muy dificil.

se debería permitir que se visualice al menos 5 líneas de Documentos a aprobar y no sólo 2 como ahora.
![image](https://github.com/solop-develop/frontend-core/assets/31936815/12dde33b-a4d2-4bdc-87cf-06b0b803bef9)


´dejaría colapsado tanto la bitácora de cambios cómo el flujo para darle más importancia a la grilla de documentos y al texto de abajo. 
Si se agranda alguno de estos se debería bajar el texto dando más espacio y que se haga scroll de la página para abajo. 

Ahora si se agranda queda todo muy chico ya qe no baja el texto y los checks de aprobaciones.

**Comment by niclopup** [comment]
Quedó mejor pero aún creo que se debería ver mucho más alta la tabla de "Sus Actividades de Flujo de Trabajo". ahora sólo se ven 2 líneas. 

Además la columna más ancha debería ser la de "Resumen"

Dejaría colapsado por defecto la Bitácora de Cambios

**Comment by EdwinBetanc0urt** [comment]
Se oculta el diagrama para que la información ocupe el contenido de mejor manera.

https://github.com/solop-develop/frontend-core/assets/20288327/16df3c3c-5abd-4739-a867-f234f4dc39a4
