### ISSUE TITLE
POS: Modificar descuento desde el modal

### ISSUE THREAD

**Issue by MarianaGallardo** [solop-develop/vue-1.0#656]
**Descripción del Error**
Actualmente está permitiendo modificar el descuento desde el modal, a pesar de no tener acceso a ingresar descuento.

**Pasos para Reproducirlo**
-Crear pedido con un usuario Asesor
-Seleccionar opción botón verde (dibujo lápiz)
  -Colocar descuento
    -Vea el error (permite ingresar descuento)

Se revisa permisología desde el terminal y el usuario no tiene acceso a modificar descuento. De hecho desde el terminal del Asesor, no tienen habilitada la columna de descuento.

Contenedor de pruebas: http://20.12.0.2:55105/# y http://20.12.0.2:55901/webui/timeout.zul
Versión: rs-52.4

**Comment by EdwinBetanc0urt** [comment]
Cierro este issue al estar en estatus entregado.
