### ISSUE TITLE
POS: Opción para visualizar órdenes Anuladas

### ISSUE THREAD

**Issue by MarianaGallardo** [solop-develop/vue-1.0#657]
Se requiere una opción en la UI que se puedan ver todas las órdenes anuladas

**Comment by EdwinBetanc0urt** [comment]
Cual de los estados de documentos indica que esta anulada?
![imagen](https://github.com/solop-develop/frontend-core/assets/20288327/68355767-51eb-4d0a-8ef3-d948391bbc0c)
