### ISSUE TITLE
Reporte: Carga > Obligatoriedad

### ISSUE THREAD

**Issue by elsiosanchez** [solop-develop/vue-1.0#66]
##### Versión ZK:
1. Abrir el reporte **Saldo en Banco**.
2. Los campos obligatorios muestran con un asterisco (*) rojo al lado derecho de su nombre.
![carga-mandatory-zk](https://user-images.githubusercontent.com/45974454/168162574-5b1d0613-031f-4327-90a1-b3d639dae10d.png)

##### Versión Vue:
1. Abrir el reporte **Saldo en Banco**.
2. Los campos obligatorios muestran con un asterisco (*) rojo al lado derecho de su nombre, y aquellos obligatorios vacios resaltan con un borde rojo sobre el campo.
![image](https://user-images.githubusercontent.com/45974454/168162550-b05346a8-5bd7-460b-833e-a38b328f4862.png)

**Comment by niclopup** [comment]
doy por entregada esta tarea pero no logre replicar con el ejemplo presentado. 

Entiendo que no existe el reporte "saldo en Banco" en Develop
