### ISSUE TITLE
Reporte: Carga > Valor por Defecto

### ISSUE THREAD

**Issue by elsiosanchez** [solop-develop/vue-1.0#67]
Manejar valor por defecto para los distintos tipos de parámetros.

##### Versión Vue:
1. Abrir el reporte **Asignación de Pago**.
2. Hacer clic contrario en el valor del parámetro y seleccionar **Valor de Preferencia**.
3. Observe que el parámetro **Document Status** tiene valor por defecto (CO = Completo).

![carga-defaul-value-zk](https://user-images.githubusercontent.com/45974454/168164303-d88605cd-0014-4723-8c82-4743c421d32a.gif)

##### Versión Vue:
1. Abrir el reporte **Asignación de Pago**.
2. Hacer clic en el nombre del parámetro y seleccionar **Información** o **Preferencia**.
3. Observe que el parámetro **Document Status** tiene valor por defecto (CO = Completo).
![carga-defaul-value-vue](https://user-images.githubusercontent.com/45974454/168164276-6e7276e4-32a7-407a-b06a-ee9e0aa84744.gif)

**Comment by niclopup** [comment]
doy por entregada esta tarea pero no está funcionando la Información ni las preferencias de un campo/parámetro 

Creo nueva tarea para seguir esto
https://github.com/solop-develop/frontend-core/issues/194

**Comment by EdwinBetanc0urt** [comment]
La información del campo fue corregida en https://github.com/solop-develop/frontend-default-theme/pull/56

https://user-images.githubusercontent.com/20288327/174921682-29b68b63-3421-4c56-82ad-26139f41b475.mp4
