### ISSUE TITLE
Ventana: Apertura > Acercar desde Parámetro de Reporte

### ISSUE THREAD

**Issue by elsiosanchez** [solop-develop/vue-1.0#68]
En ADempiere actualmente se puede acceder a una ventana desde un campo que está en otro que está relacionado, como se muestra a continuación.

### Versión Vue:
1. Abrir el reporte **Detalle de Selección de Pagos**.
2. Hacer clic contrario en el parámetro **Cargo** y seleccionar **Acercar**.

![carga-zoom-zk](https://user-images.githubusercontent.com/45974454/168165981-3e4b9231-f6f3-48db-b73c-ce223a87d2a1.gif)

### Versión Vue:
1. Abrir el reporte **Detalle de Selección de Pagos**.
2. Hacer clic contrario en el parámetro **Cargo** y seleccionar **Acercar**.

![carga-zoom-vue](https://user-images.githubusercontent.com/45974454/168165963-8eec9e05-f2f9-4d08-8d74-0f2617656258.gif)

**Comment by niclopup** [comment]
entiendo que la tarea no está asignada a mi aún pero comento que la verifique y está navegando incorrectamente al registro definido en el parámetro.

https://user-images.githubusercontent.com/31936815/174903409-27abcb3b-7d4b-485d-b6c8-82033d48ceca.mp4


https://user-images.githubusercontent.com/31936815/174903420-da0fe31b-7787-4b12-82c4-c1aa4df1e24c.mp4
