### ISSUE TITLE
[Bug Report] Permite realizar peticiones aun con un token de sesión cerrado

### ISSUE THREAD

**Issue by EdwinBetanc0urt** [solop-develop/vue-1.0#685]
#### Steps to reproduce

1. Iniciar sesión.
2. Copiar cualquier petición tipo GET que involucre respuesta del backend gRPC.
3. Cerrar la sesión.
4. Pegar la petición en una nueva pestaña.

Nótese como se obtienen datos del servidor aun cuando la sesión esta cerrada.

#### Screenshot or Gif（截图或动态图）

https://user-images.githubusercontent.com/20288327/210658095-e4aaf0c1-ed9d-40af-8386-da6d9448540a.mp4

#### Expected behavior
Esto es un problema de seguridad ya que si la sesión fue cerrada no debería permitir devolver ninguna respuesta del servidor.

**Comment by niclopup** [comment]
doy por cerrada ya que no comprendo yo esta funcionalidad pero veo que yamel dio el ok
