### ISSUE TITLE
Ventana: Pestañas tipo Árbol > Listar Registros

### ISSUE THREAD

**Issue by EdwinBetanc0urt** [solop-develop/vue-1.0#686]
Se debe dar soporte a listar los registros de pestañas tipo árbol:

La versión en la interfaz Zk se visualiza de la siguiente manera:

https://user-images.githubusercontent.com/20288327/210806372-3df0dd6a-bd12-4f46-97e3-481f0e2985b4.mp4

**Comment by EdwinBetanc0urt** [comment]
https://user-images.githubusercontent.com/20288327/212894671-6a0e67d8-d70b-4e4e-a8c1-20782cc93a79.mp4

**Comment by niclopup** [comment]
no se logra navegar entre diferentes registros desde el arbol

algunas cuentas aparecen bien pero hay ptras que no se ve el nombre, aparece vacío

![image](https://user-images.githubusercontent.com/31936815/215933515-2184226b-47a3-44df-81fb-7ed88af34c5f.png)

Otras si se ve bien

![image](https://user-images.githubusercontent.com/31936815/215933627-cad25696-fe3b-4935-9c4c-df104c4c2568.png)

SI vemos el ID de Registro se ve vacío el ID

![image](https://user-images.githubusercontent.com/31936815/215934065-ae6b03ab-41d6-48fb-b7e4-2ac978b217de.png)

**Comment by EdwinBetanc0urt** [comment]
Revisando es un tema de paginación, ya que son aproximadamente 400 cuentas, y en la tabla están disponibles de manera predeterminada 15 registros a un máximo de 100 registros, pero al seleccionarse un registro del árbol que no se encuentra en la pagina de registros actual de la tabla, el panel mono registro se coloca en modo crear nuevo registro.

**Comment by EdwinBetanc0urt** [comment]
En transcoding falla.
