### ISSUE TITLE
Reporte: Apertura > Asociado a Ventana > Autoejecutar si no tiene parámetros

### ISSUE THREAD

**Issue by EdwinBetanc0urt** [solop-develop/vue-1.0#689]
En la versión Zk se tiene la opción de imprimir, el cual se genera un reporte del proceso que esta asociado a nivel de pestaña

https://user-images.githubusercontent.com/20288327/211215010-db770c2c-5f44-4d1a-b079-7e351c3a3cb7.mp4

![invoice-customer-window](https://user-images.githubusercontent.com/20288327/211215170-2daa544c-7678-42ba-ae02-34bd02b6bd56.png)

**Comment by EdwinBetanc0urt** [comment]
En la versión vue, la opción esta dentro de los procesos asociados. Si el reporte no tiene parámetros asociados, debe autoejecutarse.


https://user-images.githubusercontent.com/20288327/211215576-0fe074bc-a90d-4bb4-a49f-c698b94f0c97.mp4

**Comment by niclopup** [comment]
Se puede sacar este proceso a un botón de impresión cuando el documento tenga esto "Activo"?

La idea es dejar en los procesos sólo los procesos q no son muy utilizados y que pueden ser accesibles desde un botón específico (Imprimir, Completar, etc)


![image](https://github.com/solop-develop/frontend-core/assets/31936815/83d93169-dbba-444e-874d-e836786966ae)

**Comment by EdwinBetanc0urt** [comment]
Se podría agregar, se debe modificar la estructura de la pestaña en el backend ya que actualmente tenemos la lista completa de procesos y no sabemos específicamente en el frontend cual de esos procesos es el que verdaderamente esta asociado a la pestaña y si es un reporte para hacer la impresión.

**Comment by EdwinBetanc0urt** [comment]
Disponible a partir de la versión del frontend https://github.com/solop-develop/frontend-core/releases/tag/3.6.1 y del backend https://github.com/solop-develop/adempiere-grpc-server/releases/tag/3.0.4


https://github.com/solop-develop/frontend-core/assets/45974454/9823d56b-e483-4306-939e-95a1d8002ffc
