### ISSUE TITLE
[Bug Report] Ventana: Registro procesado se puede editar si no tiene registros en las lineas

### ISSUE THREAD

**Issue by EdwinBetanc0urt** [solop-develop/vue-1.0#699]
## Bug report

Si el encabezado esta procesado y no tiene registros en las lineas

#### Steps to reproduce

1. Iniciar sesión con `GardenAdmin`.
2. Abrir la ventana `Selección de Pago`.
3. Buscar un registro que este completado sin lineas (existente en la base de datos semilla `Payment selection (manual) - 2002-09-07 20:18:51.041`)

#### Screenshot or Gif（截图或动态图）

https://user-images.githubusercontent.com/20288327/211426716-2d791630-dddc-4625-8cc1-cfafc3d6efcd.mp4

#### Expected behavior
Se puede observar como los campos están habilitados, tanto en las lineas como en el encabezado, para su edición a pesar de que el documento esta procesado.

**Comment by niclopup** [comment]
no parece estar corregido

![image](https://user-images.githubusercontent.com/31936815/217699237-d623c550-7f90-442c-be27-b04b19e344a7.png)

Pude guardar el cambio y quedó como sólo lectura

![image](https://user-images.githubusercontent.com/31936815/217699293-7416d387-72a4-43ff-a2f8-bddee19fe234.png)

**Comment by EdwinBetanc0urt** [comment]
No he podido replicar el error, incluso haciendo pruebas con el mismo registro 1000002

https://user-images.githubusercontent.com/20288327/219697928-b6bbc94a-3562-4ca7-9811-d303f46374ba.mp4
