### ISSUE TITLE
Proceso: Carga > Solo Lectura

### ISSUE THREAD

**Issue by elsiosanchez** [solop-develop/vue-1.0#7]
Se debe manejar el soporte para los atributos de lógica de solo lectura y para el atributo de inhabilitación para que los campos tengan ese comportamiento.

**Comment by niclopup** [comment]
recordas algún proceso que cuente actualmente con esta lógica? @EdwinBetanc0urt

**Comment by EdwinBetanc0urt** [comment]
No recuerdo ninguno en este momento, sin embargo para efectos de prueba se coloco lógica de solo lectura `1=1` en el parámetro `Is Generate UUID for all records` del proceso `Generate Surrogate Keys`.

Visualización en interfaz vue:

https://user-images.githubusercontent.com/20288327/175946853-58de4634-792b-4b30-b82f-d842029e689f.mp4


Visualización en interfaz Zk:


https://user-images.githubusercontent.com/20288327/175948164-dc841c11-a7b6-453b-863b-ea4d88509ab9.mp4
