### ISSUE TITLE
Drag and Drop: Ventana > Guardar secuencia campos de pestañas.

### ISSUE THREAD

**Issue by elsiosanchez** [solop-develop/vue-1.0#710]
https://user-images.githubusercontent.com/45974454/212110802-deafd8a5-2b03-44b6-b150-20fa03985635.mp4

**Comment by niclopup** [comment]
Sólo se logra "Guardar" el orden definido de los campos para el Usuario

![image](https://user-images.githubusercontent.com/31936815/217421389-99bee679-8c77-42f9-90af-2d1362c2f548.png)

Pero sólo se guarda si no se cierra sesión, se verifica que se puede cerrar la ventana y al volverla abrir si se mantiene el orden definido. Ahora si se cierra sesión y se vuelve a ingresar no se ven los cambios realizados.

![image](https://user-images.githubusercontent.com/31936815/217420954-bd034995-296a-4637-9fc5-25967c478a9f.png)

Se prueba también con el Rol y no se logra guardar en ningun momento. Si se cierra ventana y se vuelve a abrir no se mantiene el orden de los campos

**Comment by EdwinBetanc0urt** [comment]
Corregido y actualizado en vue-develop.solopcloud.com

**Comment by niclopup** [comment]
Se guarda un orden en la ventana "Project"
![Peek 2023-06-14 17-28](https://github.com/solop-develop/frontend-core/assets/31936815/b8bff38a-c20d-48bc-930a-c306e3867464)


Se sale y vuelvo a ingresar y abro la ventana. No se ve el orden de campos recién guardado para el ROL

![se vuelve a entrar y no respeta orden guardado para el ROL](https://github.com/solop-develop/frontend-core/assets/31936815/31c650ef-46de-4f5b-a98e-9ffdda5ffb69)

**Comment by EdwinBetanc0urt** [comment]
Se debe reiniciar cache para que sea tomado el cambio, si bien una vez guardado se puede seguir viendo la secuencia de campos guardada (siempre que no se refresque), al cambiar rol, o refrescar la pagina se debe reinicar cache, ya que se mantiene el orden de campos anterior (a nivel de cache del servidor)
