### ISSUE TITLE
Drag and Drop: Reporte > Guardar secuencia parámetros de reportes.

### ISSUE THREAD

**Issue by EdwinBetanc0urt** [solop-develop/vue-1.0#715]

**Comment by niclopup** [comment]
![image](https://user-images.githubusercontent.com/31936815/217422458-b82cce70-8833-4ad2-ae82-11b2d534d1cb.png)

Se verifica ok quese guarda por Rol y por usuario.

Se respetan los cambios tanto de los parametros que se muestran como también el orden. Tanto cerrando el proceso como saliendo y volviendo a ingresar

Se prueba reiniciando cache y se van los cambios, está ok esto?

![image](https://user-images.githubusercontent.com/31936815/217424155-825c2988-6b33-4e11-8048-c35e1deb90cd.png)

**Comment by EdwinBetanc0urt** [comment]
Corregido y actualizado en vue-develop.solopcloud.com

**Comment by EdwinBetanc0urt** [comment]
Corregido y actualizado en vue-develop.solopcloud.com
