### ISSUE TITLE
[Bug Report] Botones de Notificación no Abre la Pestaña correspondiente

### ISSUE THREAD

**Issue by elsiosanchez** [solop-develop/vue-1.0#717]
### _**GIF**_

https://user-images.githubusercontent.com/45974454/212149027-5f19756d-b783-40de-8319-003f183730f6.mp4

**Comment by EdwinBetanc0urt** [comment]
Adicionalmente se corrige el posicionamiento del contador (de adjuntos, notas, referencias)

![badge-notification](https://user-images.githubusercontent.com/20288327/212171030-55b842ce-f39d-4a6d-8302-01d01cc9a045.png)
