### ISSUE TITLE
No se puede crear NUEVO SDN Cliente

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#726]
## Bug report

Al intentar crear un nuevo SND como Cliente no se puede ya que al ir a la pestaña Cliente no se permite guardar el cambio del check "Es Cliente = Y"

![Error Crear Cliente](https://user-images.githubusercontent.com/31936815/212332342-cebe7fba-799a-41b1-aa08-50318d734eab.gif)

#### Steps to reproduce

1. [xxx]
2. [xxx]
3. [xxxx]

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:

**Comment by EdwinBetanc0urt** [comment]
Trate de replicar el error pero no me fue posible, intenta limpiando el cache del navegador.

https://user-images.githubusercontent.com/20288327/212351789-b8a3e0c1-9adb-453a-a470-9b2848602f70.mp4

**Comment by niclopup** [comment]
ok, también pude ahora.

lo raro es que al pasar de pestaña como que demora en actualizar el dato del nombre del SDN.

![error crear cliente corregido](https://user-images.githubusercontent.com/31936815/212704970-4c7e2860-fcf1-43be-97b8-b7e66dcaea72.gif)



Más allá de este problema, no sería mejor esta ventana pasar los check de "Es Cliente" y "Es Proveedor" al cabezal? y en base a estos checks mostrar la pestaña de "Cliente" o de "Proveedor"?

**Comment by EdwinBetanc0urt** [comment]
El error reportado esta resuelto, el nuevo requerimiento sobre mostrar de manera predeterminada los campos Cliente, Proveedor, Empleado en el cabezal se sigue en el issue https://github.com/solop-develop/frontend-core/issues/726
