### ISSUE TITLE
Al crear nueva requisición no aparece el tipo de documento

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#727]
## Bug report

Si se intenta crear una nueva requisición desde la ventana "Requisiciones" pero no permite seleccionar el Tipo de documento. 

Se prueba en ZK y si lo permite, luego de creada en ZK si se ve correctamente la lista desplegable del Tipo de Documento.

![error crear requisición](https://user-images.githubusercontent.com/31936815/212338424-0a01cbd7-266a-4adf-ba7b-8bf4d11b8c9e.gif)

**Comment by EdwinBetanc0urt** [comment]
Esto solo sucedía si se seleccionaba un registro procesado y posteriormente se pulsa el botón `Nuevo`.

https://user-images.githubusercontent.com/20288327/212894843-1fd1ad62-7015-4b10-a07b-cc7dd39e671b.mp4
