### ISSUE TITLE
[Bug Report] Reporte no Permite Cambiar Exportación

### ISSUE THREAD

**Issue by elsiosanchez** [solop-develop/vue-1.0#728]
#### Screenshot or Gif（截图或动态图）

https://user-images.githubusercontent.com/45974454/212387992-8f595a38-1962-491e-9958-4586d1e2e55c.mp4

**Comment by niclopup** [comment]
se cambia a HTLM y queda procesando

![image](https://user-images.githubusercontent.com/31936815/217700184-c54e5922-6932-4650-a8fc-d65cd34d20d9.png)


![image](https://user-images.githubusercontent.com/31936815/217700136-e7df89e8-fad0-4472-b635-5bfe052e146c.png)


Se cambia como antes se hacía y da error

![image](https://user-images.githubusercontent.com/31936815/217700365-4be71846-5ca3-4dae-bdcd-1719f87b8757.png)

**Comment by EdwinBetanc0urt** [comment]
@yamelsenih Es un error en los renombres de paquetes con lo de adempiere, se actualizaron los paquetes a 3.9.4 pero no funciono.
