### ISSUE TITLE
Cambios Ventana Socio del Negocio

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#739]
## Feature request

Sería mejor esta ventana pasar los check de "Es Cliente" y "Es Proveedor" al cabezal? 

y en base a estos checks mostrar la pestaña de "Cliente" o de "Proveedor"?

**Comment by EdwinBetanc0urt** [comment]
Esto se manejara por diccionario de aplicación

**Comment by EdwinBetanc0urt** [comment]
Seria buena idea, pero habría que colocar visibles esos check en la pestaña principal, y agregar lógica de visualización a `Cliente`, `Proveedor`, y `Empleado`, ademas de las pestañas de contabilidad de esa ventana. 

Si esos campos no están agregados y visibles en la pestaña principal a través de la definición de la ventana, no llegaran ni si quiera a la interfaz vue (esto para aumentar el rendimiento evitando la carga de campos no usados), por lo que es imposible su manipulación en vue.

Por ahora se puede colocar visible de forma predeterminada los campos `Es Cliente`, `Es Proveedor`, y `Es Empleado`, en sus respectivas pestañas.

![imagen](https://github.com/solop-develop/frontend-core/assets/20288327/110044e7-d607-4fc9-abcd-c72ad78d89c0)

![imagen](https://github.com/solop-develop/frontend-core/assets/20288327/a172edf2-2962-4872-ae43-87b5db6c217c)

![imagen](https://github.com/solop-develop/frontend-core/assets/20288327/a6c3abdc-390c-49cd-b412-85d80a58fc65)
