### ISSUE TITLE
[Bug Report] Botón de Notas 

### ISSUE THREAD

**Issue by elsiosanchez** [solop-develop/vue-1.0#741]
## Bug report

1. Visibilidad del Botón de Notas
2. Cambiar Icono del Botón de Notas

#### Screenshot or Gif（截图或动态图）

![image](https://user-images.githubusercontent.com/45974454/212711258-835a6176-334f-4e01-86f8-725746751c30.png)
![image](https://user-images.githubusercontent.com/45974454/212711318-769a3f2c-4c77-4b37-bd8a-ad28f28a31c0.png)

**Comment by EdwinBetanc0urt** [comment]
![image](https://user-images.githubusercontent.com/45974454/212712189-8f5dc4aa-b6ee-431a-9a54-a8a2e6a577e0.png)
