### ISSUE TITLE
Reportes: Carga > Parámetros

### ISSUE THREAD

**Issue by elsiosanchez** [solop-develop/vue-1.0#75]
### Parámetros
Los parámetros (campos) de los procesos deben cargar al abrirse en el caso de que el reporte maneje parámetros segun cada tipo de visualizacion.

1. Abrir el reporte **Saldos Abiertos**.
2. Notese los diferentes tipos de parámetros: Cadena, Si y No, Fecha, Monto, Lista, Tabla.

##### Versión ZK:
![run-params-zk](https://user-images.githubusercontent.com/45974454/168348278-abd24a68-cb5f-431b-a9d8-16619b259cf0.gif)

##### Versión Vue:
![run-params-vue](https://user-images.githubusercontent.com/45974454/168348428-09e62336-da70-4da9-8587-1677b408f51f.gif)

**Comment by elsiosanchez** [comment]
### Nota:
 
 El servidor devuelve los parámetros en los reportes con los value y no con el displayValue como se observa en la siguiente imagen

#### Versión Vue:
![image](https://user-images.githubusercontent.com/45974454/168352906-34e048a8-0a72-480c-b77e-4ea1b9c6c348.png)

#### Versión ZK:
Los parámetros deberían visualizarse de la siguiente manera
![image](https://user-images.githubusercontent.com/45974454/168353985-6ad6ac74-82d4-459c-8b1b-7d192e36cbb5.png)

**Comment by EdwinBetanc0urt** [comment]
> ### Nota:
> 
> El servidor devuelve los parámetros en los reportes con los value y no con el displayValue como se observa en la siguiente imagen
> #### Versión Vue:
> 
> ![image](https://user-images.githubusercontent.com/45974454/168352906-34e048a8-0a72-480c-b77e-4ea1b9c6c348.png)
> #### Versión ZK:
> 
> Los parámetros deberían visualizarse de la siguiente manera ![image](https://user-images.githubusercontent.com/45974454/168353985-6ad6ac74-82d4-459c-8b1b-7d192e36cbb5.png)

@elsiosanchez el valor de visualización es error del backend, por favor crear un nuevo issue al repositorio https://github.com/solop-develop/backend/ y hacer referencia a este issue.

**Comment by EdwinBetanc0urt** [comment]
Issue reportado en el repositorio backend https://github.com/solop-develop/backend/issues/24

**Comment by niclopup** [comment]
más allá del error reportado en el backend no veo otro problema

Ahora tengo una consulta, no veo ningun campo en los reportes que sean como Búsqueda y no una lista desplegable. En el caso de Productos, facturas o Socios del Negocio no sería muy práctico manejarlo como lista desplegable nada más.

![image](https://user-images.githubusercontent.com/31936815/174904531-c5980736-f7e4-4dde-ab21-3b02bd6e2c8d.png)

Tienen pensado algún cambio en este sentido?

![image](https://user-images.githubusercontent.com/31936815/174904653-5df24613-fba1-4f12-8ed2-e74973f692b8.png)

**Comment by EdwinBetanc0urt** [comment]
@niclopup por ahora no se han desarrollado campos tipo búsqueda, ya que básicamente se manejarían formas o formularios, sin embargo los campos tipo búsqueda, tabla, lista y tabla directa se presentan visualmente como listas desplegables, todos permiten escritura para filtrar resultados de la lista.

**Comment by niclopup** [comment]
Gracias @EdwinBetanc0urt 
y esto les parece que sea eficiente para realizar búsquedas con miles de Productos, facturas, órdenes o Socios del negocio? No se permitirá de ninguna forma facilitar esa búsqueda según otros criterios como nombre de contacto, nombre fantasía, categoría de producto, grupo de producot, etc? entiendo que si no se permite la opción de la búsqueda, hay varios aspectos que no sería tan fácil realizar búsquedas sin poder filtrar por algo más que no sea sólo el valor esperado (código producto, nombre, Identificador, etc)

**Comment by EdwinBetanc0urt** [comment]
Saludos @niclopup , actualmente solo esta habilitada esta opción de lista filtrable para las búsquedas en campos. Sin embargo en una de las fases posteriores están la entrega los formularios o formas, es donde se le dará soporte también a los formularios utilizados en los campos tipo búsquedas, similar al campo de socio de negocio o información de productos implementados en el punto de venta vue.

Socio de Negocio:
![business-partner-create](https://user-images.githubusercontent.com/20288327/178768147-12048b1b-4b12-4b16-ab5c-83d4f53ffef0.gif)


Información de Productos:

![info-product](https://user-images.githubusercontent.com/20288327/178768183-091531b6-873e-4222-84f4-d7bcb62efe0b.gif)



Por otra parte si lo referente a los parámetros de reportes esta validado a nivel funcional, por favor cambia el estatus a `Entregado`.

**Comment by niclopup** [comment]
doy por entregado esta issue. 

esperamos que se solucione el problema de los parámtros en el issue relacionado
