### ISSUE TITLE
No permite cerrar ventana "órdenes de Venta" por cambios en línea

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#750]
## Bug report
Se abre ventana de órdenes de venta donde se crea una nueva Orden de Venta y se guarda el cabezal, se baja un momento a la línea de la orden pero no se crea ninguna línea nueva y no permite cerrar hasta que GUARDE la línea vacia.

Esto entiendo que sería un error, el control no debería de impedir que no guarde ninguna línea en la pestaña hija pese a que haya bajado a dicha pestaña.

Además, si el control da la opción de "Descartar cambios" estos cambios deberían ser descartados (línea de la orden) y permitir cerrar ventana correctamente.

![Error Cerrar ventana OV con nuevo registor pide guardar cambios en línea si o si ](https://user-images.githubusercontent.com/31936815/212958191-6c7df830-c7d9-412c-b976-d44604f0f658.gif)

**Comment by EdwinBetanc0urt** [comment]
https://user-images.githubusercontent.com/20288327/215891206-b286cf95-2d00-4347-ae07-2d909048a707.mp4
