### ISSUE TITLE
POS Cambiar Cantidad y Descuento

### ISSUE THREAD

**Issue by MarianaGallardo** [solop-develop/vue-1.0#754]
Se realizan los siguientes escenarios:

**CASO 1**
**_Se tilda check de Modificar Descuento. Y no se coloca porcentaje de descuento, es decir, se deja en 0,00 en el campo % Descuento Máximo por Linea:_**

_**Cambiar Cantidad:**_
-Al cambiar la Cantidad directamente desde la línea de la orden, NO PIDE PIN, y deja cambiar la cantidad.
-Al cambiar la Cantidad desde el modal (editar línea), NO PIDE PIN deja cambiar la cantidad.

**_Cambiar Descuento:_**
-Al colocar % de Descuento directamente desde la línea de la orden, NO PIDE PIN, y permite el descuento.
-Al colocar % de Descuento desde el modal (editar línea), NO PIDE PIN permite el descuento.

**CASO 2**
_**Se tilda check de Modificar Descuento. Y se coloca un límite de % de descuento, ejemplo 15%, en el campo % Descuento Máximo por Linea:**_

_**Cambiar Cantidad:**_
-Al cambiar la Cantidad menor a 15 directamente desde la línea de la orden, NO PIDE PIN.
-Al cambiar la Cantidad mayor a 15 directamente desde la línea de la orden, PIDE PIN mostrando mensaje sobre descuento.
-Al cambiar la Cantidad menor a 15 desde el modal (editar línea), NO PIDE PIN.
-Al cambiar la Cantidad mayor a 15 desde el modal (editar línea), NO PIDE PIN.

**_Cambiar Descuento:_**
-Al colocar % de Descuento mayor a 15 directamente desde la línea de la orden, PIDE PIN.
-Al colocar % de Descuento menor a 15 directamente desde la línea de la orden, PIDE PIN.
-Al colocar % de Descuento mayor a 15 desde el modal (editar línea), NO PIDE PIN.
-Al colocar % de Descuento menor a 15 desde el modal (editar línea), NO PIDE PIN.

**CASO 3**

**_Se queda destildado el check de Modificar Descuento y no se coloca límite de porcentaje de descuento en el campo % Descuento Máximo por Linea:_**

_**Cambiar Cantidad:**_
 
-Al cambiar la Cantidad directamente desde la línea de la orden, NO PIDE PIN.
-Al cambiar Cantidad desde el modal (editar línea), NO PIDE PIN.

**_Cambiar Descuento:_**
-Al cambiar Descuento directamente desde la línea de la orden, PIDE PIN.
-Al cambiar Descuento desde el modal (editar línea), NO PIDE PIN.

**Resultado Esperado:**
El cambiar la cantidad no debe depender del campo % Descuento Máximo por Linea, ni en la línea de la orden ni en el modal (editar línea).

Debe existir validación con el check de Permitir Modificar Descuento (Por Linea), si está destildado, NO debe permitir hacer descuento ni por la línea de la orden, ni por el modal (editar línea).

**Comment by niclopup** [comment]
> Se realizan los siguientes escenarios:
> 
> **CASO 1** **_Se tilda check de Modificar Descuento. Y no se coloca porcentaje de descuento, es decir, se deja en 0,00 en el campo % Descuento Máximo por Linea:_**
> 
> _**Cambiar Cantidad:**_ -Al cambiar la Cantidad directamente desde la línea de la orden, NO PIDE PIN, y deja cambiar la cantidad. -Al cambiar la Cantidad desde el modal (editar línea), NO PIDE PIN deja cambiar la cantidad.
> 
> **CASO 2** _**Se tilda check de Modificar Descuento. Y se coloca un límite de % de descuento, ejemplo 15%, en el campo % Descuento Máximo por Linea:**_
> 
> _**Cambiar Cantidad:**_ -Al cambiar la Cantidad menor a 15 directamente desde la línea de la orden, NO PIDE PIN. -Al cambiar la Cantidad mayor a 15 directamente desde la línea de la orden, PIDE PIN mostrando mensaje sobre descuento. -Al cambiar la Cantidad menor a 15 desde el modal (editar línea), NO PIDE PIN. -Al cambiar la Cantidad mayor a 15 desde el modal (editar línea), NO PIDE PIN.
> 
> **CASO 3**
> 
> **_Se queda destildado el check de Modificar Descuento y no se coloca límite de porcentaje de descuento en el campo % Descuento Máximo por Linea:_**
> 
> _**Cambiar Cantidad:**_
> 
> -Al cambiar la Cantidad directamente desde la línea de la orden, NO PIDE PIN. -Al cambiar Cantidad desde el modal (editar línea), NO PIDE PIN.
> 
> **Resultado Esperado:** El cambiar la cantidad no debe depender del campo % Descuento Máximo por Linea, ni en la línea de la orden ni en el modal (editar línea).

Estos puntos están OK. Permite siempre modificar las cantidades independientemente de la lógica del descuento que se aplique.

**Comment by niclopup** [comment]
> Se realizan los siguientes escenarios:
> 
> **CASO 1** **_Se tilda check de Modificar Descuento. Y no se coloca porcentaje de descuento, es decir, se deja en 0,00 en el campo % Descuento Máximo por Linea:_**
> 
> **_Cambiar Descuento:_** -Al colocar % de Descuento directamente desde la línea de la orden, NO PIDE PIN, y permite el descuento. -Al colocar % de Descuento desde el modal (editar línea), NO PIDE PIN permite el descuento.
> 

**Resultado Esperado:** 
Al dejar en 0,00 en el campo _% Descuento Máximo por Linea_ se entiende que no se aplicaría ningún límite en el descuento a aplicar. Esto es correcto? 
Se entiende que si no se desea permitir ningún descuento bastaría con definir el check de "Modificar Descuento en línea" y listo.

**Resultado Prueba:** 
Error
Al intentar modificar el % de descuento de la línea, PIDE PIN


![Caso 1  Pin para definir descuento](https://github.com/solop-develop/frontend-core/assets/31936815/aecf41bb-9efc-4a0d-9bff-0eda85c3390e)



> **CASO 2** _**Se tilda check de Modificar Descuento. Y se coloca un límite de % de descuento, ejemplo 15%, en el campo % Descuento Máximo por Linea:**_
> 
> **_Cambiar Descuento:_** -Al colocar % de Descuento mayor a 15 directamente desde la línea de la orden, PIDE PIN. -Al colocar % de Descuento menor a 15 directamente desde la línea de la orden, PIDE PIN. -Al colocar % de Descuento mayor a 15 desde el modal (editar línea), NO PIDE PIN. -Al colocar % de Descuento menor a 15 desde el modal (editar línea), NO PIDE PIN.
> 

**Resultado Prueba:** 
Error
Al intentar modificar el % de descuento de la línea con un % **menor** al definido, PIDE PIN
Al intentar modificar el % de descuento de la línea con un % **mayor** al definido, PIDE PIN





> **CASO 3**
> **_Se queda destildado el check de Modificar Descuento y no se coloca límite de porcentaje de descuento en el campo % Descuento Máximo por Linea:_**
> 
> **_Cambiar Descuento:_** -Al cambiar Descuento directamente desde la línea de la orden, PIDE PIN. -Al cambiar Descuento desde el modal (editar línea), NO PIDE PIN.
> 
> **Resultado Esperado:** El cambiar la cantidad no debe depender del campo % Descuento Máximo por Linea, ni en la línea de la orden ni en el modal (editar línea).
> 
> Debe existir validación con el check de Permitir Modificar Descuento (Por Linea), si está destildado, NO debe permitir hacer descuento ni por la línea de la orden, ni por el modal (editar línea).


![Caso 3  Pin para definir descuento](https://github.com/solop-develop/frontend-core/assets/31936815/afb0dbf6-ede2-4af2-9f00-273d9b0033f7)



No se permite en ningún caso aplicar un descuento sin que pida PIN para aplicar el cambio

**Comment by elsiosanchez** [comment]
Saludos @niclopup me permites un suario para realizar esta prueba

**Comment by elsiosanchez** [comment]
### _**CASO 1:**_
> Resultado Esperado:
> Al dejar en 0,00 en el campo % Descuento Máximo por Linea se entiende que no se aplicaría ningún límite en el descuento a > aplicar. Esto es correcto?
> Se entiende que si no se desea permitir ningún descuento bastaría con definir el check de "Modificar Descuento en línea" y listo.

**_Resultado Prueba:_**

> Resultado Prueba:
> Error
> Al intentar modificar el % de descuento de la línea, PIDE PIN

Te solicita Pin porque tiene el check de `is_allows_modify_discount` en `false`  debe tenerlo en `true` para que no te solicite pin
