### ISSUE TITLE
[Feature Request] Ver cantidad de notas relacionadas al registro

### ISSUE THREAD

**Issue by EdwinBetanc0urt** [solop-develop/vue-1.0#755]
## Feature request

Se requiere hacer un ajuste al icono de mostrar las notas del registro, quedando similar al de los documentos relacionados del registro, de manera que el usuario vea rápidamente la cantidad de notas que están disponibles en ese registro.

![window-document-related](https://user-images.githubusercontent.com/20288327/213464533-1bda768f-4e90-4b76-a736-6b0d41ba94d8.png)

**Comment by EdwinBetanc0urt** [comment]
https://user-images.githubusercontent.com/45974454/215937442-edb633f9-9c97-460f-80bb-0dc5c4d65615.mp4

**Comment by niclopup** [comment]
OK
