### ISSUE TITLE
[Feature Request] Agregar información de usuario en las notas

### ISSUE THREAD

**Issue by EdwinBetanc0urt** [solop-develop/vue-1.0#756]
## Feature request

Se necesita agregar información como el nombre de usuario que creo la nota del registro. 

![window-notes-list](https://user-images.githubusercontent.com/20288327/213468050-d36d92ba-7db2-4531-896f-531db98099e7.png)

Esto similar a como esta actualmente el histórico de cambios.

![window-notes-list-user](https://user-images.githubusercontent.com/20288327/213468292-472c318c-1257-45a0-b82c-b275a21caaca.png)

Ademas de formatear correctamente la fecha.

**Comment by niclopup** [comment]
se ve ok
