### ISSUE TITLE
Solicitudes: Crear Comentario (Actualización) de Solicitud.

### ISSUE THREAD

**Issue by elsiosanchez** [solop-develop/vue-1.0#771]

**Comment by niclopup** [comment]
El crear un comentario desde la ventana "Issues" no se ve bien el espacio para agregar el comentario

![image](https://user-images.githubusercontent.com/31936815/217376695-bf27d3c5-6c3b-4639-b0ae-1efc1987a9ba.png)

Yamel realiza el siguiente comentario en Issue

> le dije que se puede agregar un panel redimensionable ahí y en donde se agrega comentario para minimizar
