### ISSUE TITLE
Solicitudes: Editar Solicitud asociado a un registro.

### ISSUE THREAD

**Issue by EdwinBetanc0urt** [solop-develop/vue-1.0#778]

**Comment by niclopup** [comment]
Se logra editar una solicitud modificando la prioridad de la misma y el tipo de solicitud. el problema es que ambas modificaciones aparecen en el timeline de los cambios de la solicitud pero no dice que se cambió.

![image](https://user-images.githubusercontent.com/31936815/215936331-fb3e8bda-3512-4899-8811-0c5290d20bd0.png)

**Comment by EdwinBetanc0urt** [comment]
Esto fue actualizado, se visualiza de la siguiente manera:



![Image](https://user-images.githubusercontent.com/20288327/215939424-4ee386ae-52b9-450d-9f2f-c3461e1338ed.png)
