### ISSUE TITLE
Reporte: Ejecución > Descargar

### ISSUE THREAD

**Issue by elsiosanchez** [solop-develop/vue-1.0#78]
### Descargar

Actualmente en la interfaz de ADempiere ZK si ejecuto un reporte en formato PDF y se requiere descargarlo en EXCEL debe volver a ejecutar el reporte en el formato de EXCEL y luego hacer click en la opción de descargar

En la interfaz de ADempiere-Vue si ejecuto un reporte en HTML y se requiere descargarlo no es necesario volver a ejecutar el reporte con el formato que se desea descargar. En la parte inferior del titulo del reporte posicionado al izquierda tiene la opción de descargarlo en cualquier tipo de formato

##### Versión ZK:
![run-download-zk](https://user-images.githubusercontent.com/45974454/168376449-a946934c-34d7-4708-b813-fd623428acdd.gif)

##### Versión Vue:
![run-download-vue](https://user-images.githubusercontent.com/45974454/168376501-618db2f7-1b74-4e31-8932-a3104344eb6d.gif)

**Comment by EdwinBetanc0urt** [comment]
Cambios relacionados:
https://github.com/solop-develop/frontend-default-theme/pull/16
