### ISSUE TITLE
Solicitudes: Editar Comentario (Actualización) de Solicitud.

### ISSUE THREAD

**Issue by EdwinBetanc0urt** [solop-develop/vue-1.0#781]

**Comment by niclopup** [comment]
no se si está ok que se permita hacer esto. Actualmente en ZK no permite y entiendo que no debería ya que es una auditoría

como se ve en la foto, no se permite modificar ni crear nueva desde esta pestaña 

![image](https://user-images.githubusercontent.com/31936815/215936937-0cdf8d85-ded4-4418-85be-ea0efa7900a2.png)

**Comment by niclopup** [comment]
salta este error al intentar agregar un comentario en una solicitud

![image](https://user-images.githubusercontent.com/31936815/216711942-2168cf41-55c3-4ee6-8b63-2a28d48cc943.png)
