### ISSUE TITLE
[Bug Report] Campo Combinación Contable: Deshacer no establece el valor correctamente.

### ISSUE THREAD

**Issue by EdwinBetanc0urt** [solop-develop/vue-1.0#786]
#### Steps to reproduce

1. Abrir la ventana `Grupo de Socios de Negocio`.
2. Ir a la pestaña `Contabilidad`.
3. Desplegar el campo de búsqueda de cualquiera de las combinaciones contables.
4. Pulsar el botón de cancelar (`X` roja) del formulario de combinaciones.
5. Pulse el botón `Deshacer` de la pestaña.

#### Screenshot or Gif（截图或动态图）

https://user-images.githubusercontent.com/20288327/214867452-12fe06dd-e302-4165-be0d-025198dcc026.mp4

#### Expected behavior
Nótese que al descartar los cambios el campo sigue vació, cuando debería establecer el valor que estaba previamente ya que al descartar debería dejar el registro exactamente igual.

**Comment by EdwinBetanc0urt** [comment]
Este campo no esta operando correctamente, al abrir la combinación contable no muestra el registro (y si lo encuentra), al hacer una búsqueda al parecer filtra múltiples registros, y al establecer uno no parece cambiar.

Ademas que existe una impresión de `console.log` en la consola del navegador`.

**Comment by Ricargame** [comment]
Cambios disponibles a partir de la versión: https://github.com/solop-develop/frontend-core/releases/tag/4.4.006

https://github.com/user-attachments/assets/1bb3c634-7857-4bf4-ba7e-4d6a6c46e393
