### ISSUE TITLE
Reporte: Ejecución > Cambiar Parámetros

### ISSUE THREAD

**Issue by elsiosanchez** [solop-develop/vue-1.0#79]
### Cambiar Parámetros

Actualmente en la interfaz de ADempiere ZK no se puede cambiar de parámetros en el contenedor del visor de reporte

##### Versión Vue:
![run-change-params-vue](https://user-images.githubusercontent.com/45974454/168377180-286b3867-10aa-478d-a507-217084c57066.gif)

**Comment by EdwinBetanc0urt** [comment]
https://solop-develop.github.io/frontend-core/es/guide/use-cases/reports.html#relaciones

**Comment by EdwinBetanc0urt** [comment]
Cambios relacionados:
https://github.com/solop-develop/frontend-core/pull/89
https://github.com/solop-develop/frontend-default-theme/pull/19
