### ISSUE TITLE
[Bug Report] Solicitud: Crear una solicitud desde una ventana especifica debe establecer esos valoes

### ISSUE THREAD

**Issue by EdwinBetanc0urt** [solop-develop/vue-1.0#794]
#### Steps to reproduce

Si se crea una solicitud desde una ventana especifica que corresponda con
![request-source](https://user-images.githubusercontent.com/20288327/215191655-9312957d-4a76-4c29-9851-037f435dc93b.png)

Debe establecer ese valor para conocer la referencia desde donde se origina la solicitud.

**Comment by EdwinBetanc0urt** [comment]
https://user-images.githubusercontent.com/20288327/215192014-4f378129-959b-4ff6-bf60-1dddc2f19fd9.mp4

**Comment by niclopup** [comment]
se valida bien creando una solicitud desde el SDN
