### ISSUE TITLE
Solicitudes: Listar Solicitudes asociadas al rol o usuario.

### ISSUE THREAD

**Issue by EdwinBetanc0urt** [solop-develop/vue-1.0#797]
Se debe abrir el componente de las solicitudes asociadas al registro, pero en este caso se debe abrir como una vista de formulario, filtrando por las solicitudes que tiene el usuario o rol de la sesión.

![request-panel](https://user-images.githubusercontent.com/20288327/215504657-afd59087-be1e-4b3c-9068-31edb027edde.png)

cabe destacar que para acceder a este componente se debe hacer clic en las notificaciones y seleccionar `Solicitud`:

![request-notifications](https://user-images.githubusercontent.com/20288327/215505181-5815f776-3881-4071-afeb-6c96e99c5cc0.png)

**Comment by niclopup** [comment]
Entiendo que se refieren a esta ventana correcto?

![image](https://user-images.githubusercontent.com/31936815/215938062-42a5f8c9-1d15-48b5-b2e4-fa648037c444.png)

Entiendo que faltan campos importantes como los campos de fechas, por ejemplo el campo "fecha de siguiente acción" que la fecha que define el vencimiento.

Tampoco veo ningún campo de referencia así como tampoco los de auditoría

**Comment by EdwinBetanc0urt** [comment]
La lista como tal del usuario o rol esta correcta, se agrega como nuevo requerimiento la fecha de siguiente acción en el issue https://github.com/solop-develop/frontend-core/issues/816
