### ISSUE TITLE
Proceso: Carga > Obligatoriedad

### ISSUE THREAD

**Issue by elsiosanchez** [solop-develop/vue-1.0#8]
El campo no está tomando el atributo requerido al cumplir con la lógica obligatoria.

![image](https://user-images.githubusercontent.com/45974454/166727771-07db34d2-fa11-4532-a28b-e3a0e6a0da78.png)

**Comment by EdwinBetanc0urt** [comment]
Aunque los parámetros de procesos manejan el check de obligatoriedad, no manejan lógica de obligatoriedad desde el core de ADempiere, a futuro se puede agregar dicha funcionalidad, y de esta manera darle soporte en el front-end.

**Comment by EdwinBetanc0urt** [comment]
Los casos de uso para esta funcionalidad se pueden ver aquí:
https://solop-develop.github.io/frontend-core/es/guide/use-cases/process.html#obligatoriedad
