### ISSUE TITLE
Reporte: Ejecución > Cambiar Formato de Impresión

### ISSUE THREAD

**Issue by elsiosanchez** [solop-develop/vue-1.0#80]
### Cambiar Formato de Impresión

Se requiere que desde el visor de reporte se pueda cambiar formato de impresión para generar nuevo reporte

##### Versión ZK:
![run-print-format-zk](https://user-images.githubusercontent.com/45974454/168379511-f967e3f0-3866-4d6d-b3fb-4c2b385be736.gif)

##### Versión Vue:
![run-print-format-vue](https://user-images.githubusercontent.com/45974454/168379328-676aa690-4fb2-4c70-a657-947718b82308.gif)

**Comment by elsiosanchez** [comment]
### Nota: 
Esta dando error del lado del Back-End ya que cuando se cambia el formato de impresion se esta enviando el `print_format_uuid` .Pero el servidor devuelve el mismo formato

https://github.com/adempiere/proxy-adempiere-api/blob/master/src/modules/adempiere-api/api/extensions/adempiere/common/api/index.js#L251

![image](https://user-images.githubusercontent.com/45974454/168379999-ec012bc5-0dbb-4f1a-b1ab-0e251fb9aa1b.png)


### CURL 

```shell
curl --location --request POST 'https://api.erpya.com/api/adempiere/common/api/process?token=9756a150-89cb-463b-a015-688f8e3a8bfe&language=es' \
--header 'Content-Type: application/json' \
--data-raw '{
    "process_uuid": "a42b9c36-fb40-11e8-a479-7a0060f0aa01",
    "report_type": "html",
    "parameters": [
        {
            "key": "IsSOTrx",
            "value": true
        },
        {
            "key": "DaysDue",
            "value": -99999
        },
        {
            "key": "DaysDue_To",
            "value": 99999
        }
    ],
    "selections": [],
    "print_format_uuid": "0abe35d1-2fa9-425f-a7aa-79031a28da38"
}'
```

**Comment by niclopup** [comment]
veo que no estoyt asignado pero igual comento por las dudas No se logra obtener un reprote en HTML, sólo en pdf


https://user-images.githubusercontent.com/31936815/174905145-ad3ca768-3014-46db-9f58-e96a151119d4.mp4

**Comment by EdwinBetanc0urt** [comment]
Extraño, no se ha realizado cambios referentes, de hecho en Google Chrome y basados en Chromium se corrigió recientemente el generar reportes en PDF https://github.com/solop-develop/frontend-core/pull/190.

Generado en Mozilla Firefox:

https://user-images.githubusercontent.com/20288327/174922755-8244de30-9561-4070-9306-912cad35c424.mp4

Generado en Google Chrome

https://user-images.githubusercontent.com/20288327/174922713-cdcee18a-5e3d-4d93-bcde-cc591e90fb04.mp4

Quizas podrías indicar que navegador y versión estas usando para revisarlo mas a fondo.

**Comment by niclopup** [comment]
Perfecto, lo intente obtener desde otro chrome y funciona correctamente!

Muchas gracias
