### ISSUE TITLE
Reporte: Ejecución > Cambiar Extensión de Archivo

### ISSUE THREAD

**Issue by elsiosanchez** [solop-develop/vue-1.0#81]
#### Cambiar Extensión de Archivo

Se requiere que desde el visor de reporte se pueda cambiar la extensión del archivo para generar nuevo reporte

##### Versión ZK:
![run-change-file-extension-zk](https://user-images.githubusercontent.com/45974454/168381304-7b7ad4aa-3507-40db-b204-ec69909d87ec.gif)

##### Versión Vue:
![run-change-file-extension-vue](https://user-images.githubusercontent.com/45974454/168381683-cc0a8dc5-9072-4ef9-a149-f10fbfe09c38.gif)

**Comment by EdwinBetanc0urt** [comment]
Cambios relacionados:
https://github.com/solop-develop/backend/pull/5
https://github.com/solop-develop/backend/pull/6
