### ISSUE TITLE
Acercar al documento desde la ventana de Flujo de Actividades

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#812]
## Feature request

No veo la opción de poder navegar al registro que se está aprobando.

actualmente ZK tiene esta opción desde un botón de acercar que está donde se procesa la aprobación. 

![image](https://user-images.githubusercontent.com/31936815/215927995-4803d3ef-c7b3-4158-b228-29f34a1fa2b9.png)

**Comment by EdwinBetanc0urt** [comment]
![zoom-window](https://user-images.githubusercontent.com/20288327/216716403-c38a5ce7-f3d0-4b6f-aa97-4fd15a867539.png)
