### ISSUE TITLE
Error al elegir cuenta bancaria en Pago/Cobro

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#813]
## Bug report

La cuenta bancaria es obligatoria de definir en un Pago/Cobro. Al intentar definir una cuenta bancaria da el siguiente error

Se ha producido un error inesperado, intente nuevamente org.postgresql.util.PSQLException: ERROR: syntax error at or near ")" Position: 169, SQL=SELECT COUNT(*) FROM C_BankAccount ba INNER JOIN C_Bank b ON(b.C_Bank_ID = ba.C_Bank_ID) WHERE ba.C_BankAccount_ID = C_BankAccount.C_BankAccount_ID AND b.BankType = 'B')) AND C_BankAccount.AD_Client_ID IN(0,11) AND C_BankAccount.AD_Org_ID IN(0,11,12,50000,1000000,50002,50001,50004,50006,50005,50007) AND (C_BankAccount.C_BankAccount_ID IS NULL OR C_BankAccount.C_BankAccount_ID NOT IN ( SELECT Record_ID FROM AD_Private_Access WHERE AD_Table_ID = 297 AND AD_User_ID <> 101 AND IsActive = 'Y' ))

![image](https://user-images.githubusercontent.com/31936815/215930068-1b3cdf31-44cf-46f5-a2e7-baf68f7e51e0.png)

Mismo error se repite al buscar Cuenta Bancaria desde Ventana Estado de Cuneta Bancario

![image](https://user-images.githubusercontent.com/31936815/215931010-60fc1f13-198d-4667-8286-43e01eb9d3ea.png)

Se ha producido un error inesperado, intente nuevamente org.postgresql.util.PSQLException: ERROR: syntax error at or near ")" Position: 169, SQL=SELECT COUNT(*) FROM C_BankAccount ba INNER JOIN C_Bank b ON(b.C_Bank_ID = ba.C_Bank_ID) WHERE ba.C_BankAccount_ID = C_BankAccount.C_BankAccount_ID AND b.BankType = 'B')) AND C_BankAccount.AD_Client_ID IN(0,11) AND C_BankAccount.AD_Org_ID IN(0,11,12,50000,1000000,50002,50001,50004,50006,50005,50007) AND (C_BankAccount.C_BankAccount_ID IS NULL OR C_BankAccount.C_BankAccount_ID NOT IN ( SELECT Record_ID FROM AD_Private_Access WHERE AD_Table_ID = 297 AND AD_User_ID <> 101 AND IsActive = 'Y' ))

#### Steps to reproduce

1. [xxx]
2. [xxx]
3. [xxxx]

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:

**Comment by EdwinBetanc0urt** [comment]
Corregido en el cambio https://github.com/solop-develop/backend/commit/4a835b963930137e358326c38b879db4abd96530


https://user-images.githubusercontent.com/20288327/216171542-780a3e8f-0002-4ea3-8e33-4cf2ba6b1a7e.mp4
