### ISSUE TITLE
Error cerrar ventana con cambios sin guardar

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#814]
## Bug report

No es posible cerrar una ventana con cambios sin guardar directo desde la ventana que te avisa que hay cambios sin guardar

![image](https://user-images.githubusercontent.com/31936815/215932046-e3c38d1b-8216-4cda-808a-6746857be300.png)

entiendo que la idea es si se hace click en "Descartar Cambios" entonces debería proceder a cerrar la ventana y descartar los cambios del registro pero no lo hace. Sólo permite cerrar ventana si se apreta el botón de "Deshacer" en el cabezal

![image](https://user-images.githubusercontent.com/31936815/215932278-a6a54cce-aca1-4625-9552-44be5ca24475.png)

#### Steps to reproduce

1. [xxx]
2. [xxx]
3. [xxxx]

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:

**Comment by EdwinBetanc0urt** [comment]
Duplicado con https://github.com/solop-develop/frontend-core/issues/750

Corregido en la versión https://github.com/solop-develop/frontend-core/releases/tag/experimental-2.0.4

https://user-images.githubusercontent.com/20288327/215891206-b286cf95-2d00-4347-ae07-2d909048a707.mp4
