### ISSUE TITLE
Reporte: Ejecución > Vista de Reporte

### ISSUE THREAD

**Issue by elsiosanchez** [solop-develop/vue-1.0#82]
### Drill Down

Se requiere que desde el visor de reporte se pueda cambiar Vista de Reporte para generar nuevo reporte

##### Versión ZK:
![run-drill-down-zk](https://user-images.githubusercontent.com/45974454/168383311-baff5fa5-dd3e-4210-9177-52f88c257f9a.gif)

##### Versión Vue:
![run-drill-down-vue](https://user-images.githubusercontent.com/45974454/168383333-0932ee81-7299-435b-b079-fbcb029019ca.gif)

**Comment by elsiosanchez** [comment]
### Nota: 
Esta dando error del lado del Back-End ya que cuando se cambia la **_vista de reporte_** se esta enviando el `report_view_uuid` .Pero el servidor devuelve el mismo formato

https://github.com/adempiere/proxy-adempiere-api/blob/master/src/modules/adempiere-api/api/extensions/adempiere/common/api/index.js#L252

![image](https://user-images.githubusercontent.com/45974454/168383552-df4ab11c-03d5-49b8-9ada-1e57edf68dd6.png)


### CURL 

```shell
curl --location --request POST 'https://api.erpya.com/api/adempiere/common/api/process?token=9756a150-89cb-463b-a015-688f8e3a8bfe&language=es' \
--header 'Content-Type: application/json' \
--data-raw '{
    "process_uuid": "a42b9ca4-fb40-11e8-a479-7a0060f0aa01",
    "report_type": "html",
    "report_view_uuid": "c3e12552-ce3e-4cda-b9e0-433723b7904d",
    "parameters": [
        {
            "key": "DocStatus",
            "value": "CO"
        }
    ],
    "selections": []
}'
```

**Comment by EdwinBetanc0urt** [comment]
Reporte de problema con posible solución https://github.com/solop-develop/backend/issues/30

**Comment by niclopup** [comment]
Se crea una nueva vista sobre el reporte de "Detalles del Pago" en ZK pero no se logra visualizar en VUE 

![image](https://user-images.githubusercontent.com/31936815/193155862-2a6dabc5-74c9-4173-9e9e-2c8001a9fdf5.png)

![image](https://user-images.githubusercontent.com/31936815/193155946-f6756ab4-8803-4b27-b852-23bad5d45c06.png)

Según se analiza, lo que se está viendo es el Campo de al lado, no las diferentes vistas del reporte.

![image](https://user-images.githubusercontent.com/31936815/193172334-60c02c47-15fc-42d0-9280-b1fb2383d760.png)


![image](https://user-images.githubusercontent.com/31936815/193172183-2754c20d-93a4-4d56-910f-9695b1cd3a2e.png)

**Comment by EdwinBetanc0urt** [comment]
Con respecto a que no se visualiza en vue, si el reporte ya fue cargado en esa sesión antes de crear la vista debes reiniciar cache desde vue.

**Comment by niclopup** [comment]
Correcto, me confundí de opción.

está ok
