### ISSUE TITLE
Ventana mantiene filtro luego de quitarlo

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#829]
## Bug report

Se navega a la ventana de Socio del Negocio mediante "Acercar"  desde el campo Socio del Negocio desde la ventana órdenes de venta. Se abre correctamente la ventana de Socio del negocio con el registro en cuestión. 

![image](https://user-images.githubusercontent.com/31936815/216711181-fc8b2a28-2f81-4e1a-abd5-9f6d6efcfa81.png)

Luego se utiliza la búsqueda para "quitar el filtro" y mostrar todos los SDN de la ventana.

![image](https://user-images.githubusercontent.com/31936815/216711254-85c05c1c-2412-4504-b5a4-0c83a1d686a3.png)

luego se abre una ventana diferente, al volver a la ventana de SOcio del Negocio, vuelve a aparecer el primer filtro aplicado

![image](https://user-images.githubusercontent.com/31936815/216711488-5a599988-d3fc-4c34-a613-fd9bb5ad2d36.png)

Es como que se mantiene el filtro inicialmente y al hacer una nueva búisqueda no lo borra por completo.

#### Steps to reproduce

1. [xxx]
2. [xxx]
3. [xxxx]

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:

**Comment by EdwinBetanc0urt** [comment]
Corregido
