### ISSUE TITLE
Se elimina localización en SDN y no permite volver a crearla

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#831]
## Bug report

Luego de Borrar una localización que recién se había creado, no se puede definir nuevamente una nueva localización para un SDN.

Se cierra la ventana y se vuelve a abrir. ahora si aparecen los campos pero no se logra guardar por el siguiente error:

#### Steps to reproduce

1. Se crea un nuevo SDN y se crea una localización
2. Se borra la localización creada
3. Se intenta crear nueva localización pero no se logra.

#### Screenshot or Gif（截图或动态图）

![image](https://user-images.githubusercontent.com/31936815/216984757-80b6eb99-aa11-46de-872e-bf08bdeadd2b.png)

**Comment by niclopup** [comment]
se crea un nuevo SDN y tampoco se puede abrir la ventana de localización


https://user-images.githubusercontent.com/31936815/216985685-3ef86b7c-c9cb-41d3-86ff-3356f38c2451.mp4

Se procede a cerrar la ventana y me pregunta por todo esto:

![image](https://user-images.githubusercontent.com/31936815/216985771-06fece53-e9e3-457a-9b94-7824139a4086.png)

este era mi usuario

![image](https://user-images.githubusercontent.com/31936815/216985888-cd86b998-fce5-4737-b20e-2e13841c14b0.png)

Se vuelve a abrir ventana pero persiste el error


https://user-images.githubusercontent.com/31936815/216986244-77a17e78-546e-418e-9397-81d372f9897c.mp4

**Comment by niclopup** [comment]
finalmente se refresca la página y se logra solucionar el problema


https://user-images.githubusercontent.com/31936815/216987927-3e48d352-6c0f-4201-b449-76cc07f75ff5.mp4

**Comment by EdwinBetanc0urt** [comment]
Corregido

https://user-images.githubusercontent.com/20288327/217101569-99ea5f88-0f20-4a5f-9647-63e43c239e4f.mp4

**Comment by niclopup** [comment]
Se borra pero no permite crear una nueva

![image](https://user-images.githubusercontent.com/31936815/217418695-8b2f71f5-e44a-4f89-b538-2345665b44e5.png)
