### ISSUE TITLE
Error al guardar Localización con Ciudad definida que no existe en la base de datos

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#832]
## Bug report

Al intentar definir una dirección salta el siguiente msj de error. 

Al parecer la guardó correctamente pero no se que sería ese msj

![image](https://user-images.githubusercontent.com/31936815/216983016-53b22b4e-8014-4a15-8af4-891633accca0.png)

#### Steps to reproduce

1. Crear nuevo Socio del Negocio
2. Crear nueva localización definiendo Dirección 1, 
3. [xxxx]

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:

**Comment by EdwinBetanc0urt** [comment]
Corregido

https://user-images.githubusercontent.com/20288327/217101569-99ea5f88-0f20-4a5f-9647-63e43c239e4f.mp4

**Comment by niclopup** [comment]
esto ya se subió al testing?

volvi a crear una y me apareció de nuevo el error

![image](https://user-images.githubusercontent.com/31936815/217418378-c7bc052c-ea6f-48b4-b9a5-d824d57d6726.png)


Más alla de eso, no llegue a guardarlo y puse deshacer para crearla de nuevo la localización, al abrir la ventana los campos aparecen como con el código o el ID entiendo que es y no me deja modificarla ni crear una nueva

![image](https://user-images.githubusercontent.com/31936815/217418038-969caeba-e5be-4f07-9a2f-6aadf113de3d.png)

**Comment by niclopup** [comment]
no se logra. da error
![error al crear una dirección en cliente 2](https://user-images.githubusercontent.com/31936815/233261626-14207c1e-58fc-4673-89dc-4ef6dfedcce0.jpg)
![error al crear una dirección en cliente](https://user-images.githubusercontent.com/31936815/233261629-6a77e4d7-dc74-453e-a43b-0e0f8112f47e.jpg)

**Comment by EdwinBetanc0urt** [comment]
Corregido si en encabezado es nuevo o si el encabezado es solo lectura o el registro actual es solo lectura no expande el formulario de campos.

Corregido si el campo es obligatorio como el país Colombia que la secuencia de captura es `@CO@ @R!@ @C!@ @A1!@ @A2@ @A3@ @A4@ @P@` indicando que la región, ciudad y dirección 1 son obligatorios con el símbolo de `!`.

Validar si uno de los campos obligatorios esta vació no habilitar el botón de Ok.

Corregir valores de visualización en listas desplegables.
