### ISSUE TITLE
Ventana de Coordenadas arriba en la izquierda de la pantalla

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#838]
## Bug report
Se intenta crear una Localización pero al hacer click en el campo Localización desde la pestaña Localización en modo Griilla, se abre arriba a la izquierda una ventana cortada de Coordenadas. se intenta cerrar pero no se puede.

![image](https://user-images.githubusercontent.com/31936815/217417529-4af39cd0-8f46-4972-9abd-a5fc7ec77b68.png)

**Comment by EdwinBetanc0urt** [comment]
Hola @niclopup, de que manera se puede replicar este comportamiento?

**Comment by niclopup** [comment]
Ahora ni siquiera puedo elegir una coordenadas.  no abre en ningun lado la ventana de definición de Coordenadas.

**Comment by Ricargame** [comment]
Cambios disponibles apartir de la version: https://github.com/solop-develop/frontend-core/releases/tag/3.8.3
![image](https://github.com/solop-develop/frontend-core/assets/78000356/ee16c580-725f-45f6-9919-a4832cbe0901)

**Comment by Ricargame** [comment]
Cambios disponibles apartir de la versión: https://github.com/solop-develop/frontend-core/releases/tag/3.8.5



![Image](https://github.com/solop-develop/frontend-core/assets/78000356/61edbf44-328c-46ac-ad81-fcedfb60f9f3)



https://github.com/solop-develop/frontend-core/assets/78000356/87a28d35-2025-4916-a283-c7ac1fe26153
