### ISSUE TITLE
Callout Agente Comercial en Orden de Compra

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#841]
## Bug report

Al crear una Orden de Compra desde la ventana órdenes de compra, no se está definiendo por defecto automáticamente el Agente Comercial que tiene definido el Usuario que la crea.

Ver como sucede en ZK que se define simplemente el Socio del Negocio y se carga automáticamente la localización y cómo el usuario "GardenAdmin" tiene definido un SDN vinculado que esta definido como "Agente Comercial" este se setea automáticamente en el documento. 

Actualmente en VUE lo pide que se defina manualmente

https://user-images.githubusercontent.com/31936815/217610226-157f10d0-16e8-40d8-9646-3c30ff231234.mp4

lo mismo pasa para la OV y debe pasar para todos los documentos. Siempre si el Usuario tiene un Agente comercial definido se debería setear automáticamente

https://user-images.githubusercontent.com/31936815/217610628-61e8a703-7386-40fd-9411-ccefd4356d7a.mp4

Ejemplo en ZK

https://user-images.githubusercontent.com/31936815/217610269-e56e506e-0078-4844-8e9a-5e9f335fbf1a.mp4

**Comment by EdwinBetanc0urt** [comment]
El valor del agente comercial no se establece por callouts sino por el contexto de la sesión `#SalesRepresentative_ID`, el cual no se esta incluyendo en el contexto de la sesión de vue.

**Comment by niclopup** [comment]
entiendo.

No se piensa agregar? este es un campo que es obligatorio en muchos documentos por el cuál sería bueno contar con un automatismo como se tiene en ZK
