### ISSUE TITLE
SB Crear Desde no funciona desde Documentos por pagar

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#842]
## Bug report

Se intenta generar un Documento por pagar desde una orden de compra generada pero no se logra filtrar correctamente en el SB de "Crear Desde" (Create from Order/Receipt)

#### Steps to reproduce

https://user-images.githubusercontent.com/31936815/217615747-f61b84d9-3ce0-4378-9ed2-16ed4b04b871.mp4

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:

**Comment by EdwinBetanc0urt** [comment]
https://user-images.githubusercontent.com/20288327/218084205-908fbac9-5b7b-4255-acb4-448537d4196b.mp4

**Comment by niclopup** [comment]
ok, funciona ahora muestra las ordenes y las líneas OK, pero no funciona la Acción del SB.

Al seleccionar las líneas que se desean Cargar en el DxP, se pueden definif una cantidad diferente, lo cuál ahora al parecer permite, pero al darle OK al proceso debería cargar las líneas seleccionadas con las cantidades definidas en las líneas del DxP en cuestión y Cerrarse el SB automáticamente ya que no se necesitará para más nada. 

Ahora no está definiendo las líneas y no se está cerrando.


https://user-images.githubusercontent.com/31936815/218097522-3a6668ae-28de-4c8f-a7fc-0d749048677a.mp4

**Comment by EdwinBetanc0urt** [comment]
@yamelsenih los procesos están estableciendo correctamente la selección de registros, a pesar de que en la depuración en el backend sigue el ciclo correctamente, sin error, excepciones ni advertencias, no esta generando los registros que debería.

En el backend todo esta correcto, existe algún cambio de adempiere core que pueda afectar el funcionamiento?

**Comment by EdwinBetanc0urt** [comment]
Corregido el problema era que no establecía el ID del registro de la ventana en la ejecución del proceso.


https://user-images.githubusercontent.com/20288327/222635072-890765cf-b749-4b88-9ec7-b4632fead13e.mp4
