### ISSUE TITLE
Acercar desde ventana Issues a Ventana Todas las Solicitudes o Solicitud

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#844]
## Feature request

Se desea poder acercar a la ventana de Request para poder ver el registro con todos los datos. 

![image](https://user-images.githubusercontent.com/31936815/217626481-1a50115f-b05b-4096-885f-f1e8ae533ba1.png)

Creo que siguiendo la lógica debería ser la ventana "Request" a la que se navegue y no a la ventana de "Request (all)"

![image](https://user-images.githubusercontent.com/31936815/217627528-a28423cc-3cd1-47bd-8f14-de7ec67e91d8.png)

**Comment by EdwinBetanc0urt** [comment]
https://user-images.githubusercontent.com/20288327/217681276-eeb3cb8a-09b2-463b-896f-5c7155e0e2e6.mp4

**Comment by EdwinBetanc0urt** [comment]
@elsiosanchez el uuid de la ventana `Solicitud` es `a5216792-fb40-11e8-a479-7a0060f0aa01` para hacer el acercar con el id del issue.
