### ISSUE TITLE
Permitir guardar Cuidades fuera de la tabla

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#846]
## Feature request

Existe un check en la definición de los Paises donde se marca si se desea aceptar la definición de "Ciudades fuera de la tabla", esta opción es para que no sea necesario que exista el registro para seleccionarlo en la ciudad, sino que se puede guardar un dato cualquiera que se digite. 

![image](https://user-images.githubusercontent.com/31936815/217685979-87aaeb81-f70f-4660-a998-d5b2934fc24c.png)

Esta funcionalidad existe actualmente en ZK y deberíamos permitir también en VUE.

actualmente si se define una ciudad que no está guardada no se guarda.

Ver ejemplo del País Uruguay

![image](https://user-images.githubusercontent.com/31936815/217686119-4a9a705b-9d22-4409-8976-51a8a43ff265.png)

**Comment by EdwinBetanc0urt** [comment]
De momento existen un par de limitantes técnicas:

1. El componente para listas si bien permite crear, no es compatible con al búsqueda remota, la cual nos permite disminuir la carga de rendimiento del backend y de la base de datos, pasando un máximo de 50 registros a la vez. En conclusión o se activa la búsqueda remota o se activa el crear opción nueva en la lista, en este caso ciudad.

2. Al evaluar este issue, se busco implementar cuando el valor ira al campo numérico `C_City_ID` (identificador de las ciudades existentes) y cuando ira al campo de texto `City` (donde van las nuevas ciudades). Lamentablemente el componente de element-ui no tiene un método o evento que nos permita identificar que se ha creado un nuevo elemento, y al enviar el valor de la ciudad en texto al servidor generara error, ya que tratara de insertar un texto (ya que en el componente no tiene identificador cuando es un nuevo elemento) en un campo numérico.

**Comment by EdwinBetanc0urt** [comment]
Se agrego la funcionalidad agregando un campo texto que se oculta si la lista de ciudad tiene valor.

Ese campo solo es visible si en la captura de secuencia existe `@C@` y si `Permite ciudades fuera de la lista` esta marcado en la definición del país.

https://user-images.githubusercontent.com/20288327/224801201-53947196-45b6-4a59-b64f-b89c55f95212.mp4

**Comment by niclopup** [comment]
No se logra definir una ciudad en modo Texto

![error al crear una dirección en cliente 2](https://user-images.githubusercontent.com/31936815/233255394-929c4695-0133-4d63-83d3-5076ee7afaab.jpg)
![error al crear una dirección en cliente](https://user-images.githubusercontent.com/31936815/233255395-18e900f4-bd04-4cdd-98e5-f6f5851f0f5a.jpg)

El país tiene el check

![image](https://user-images.githubusercontent.com/31936815/233255453-4ffe6b2d-31b0-4286-b75e-54f29af30a4d.png)
