### ISSUE TITLE
Smart Browser Create From Invoice en Selección de Pago no funciona

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#847]
## Bug report

Se intenta buscar una Factura de CxP pero da error y no se logra completar la búsqueda

![image](https://user-images.githubusercontent.com/31936815/217697579-f24dcec0-df06-45c6-be88-ee0ebd6a7bfe.png)

![image](https://user-images.githubusercontent.com/31936815/217697254-30b09d3e-0c2b-4854-8fe5-4072d19ca4f0.png)

Se realiza la búsqueda en ZK y da registros

![image](https://user-images.githubusercontent.com/31936815/217697424-af38e8a4-79b9-4a32-8759-96d94521c11e.png)

#### Steps to reproduce

1. [xxx]
2. [xxx]
3. [xxxx]

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:

**Comment by EdwinBetanc0urt** [comment]
https://github.com/solop-develop/frontend-core/assets/20288327/3936573b-bb60-491e-9047-5e095c31f0d1
