### ISSUE TITLE
SB de Crear desde Orden en la Recepción de Productos no muestra líneas

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#854]
## Bug report

Ahora que se puede guardar la recepción, al intentar crear líneas desde una Orden de compra, no se puede debido a que si bien el SB muestra la Orden en cuestión, no llega a mostrar las líneas de esa orden nunca.

#### Screenshot or Gif（截图或动态图）

https://user-images.githubusercontent.com/31936815/218099342-57e40d8d-9a42-4e3a-b779-4f9eadb03756.mp4

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:

**Comment by EdwinBetanc0urt** [comment]
https://user-images.githubusercontent.com/20288327/218195282-8966c43f-3a0b-4d2a-ae97-2cba0a3a92ee.mp4

**Comment by niclopup** [comment]
buenas Edwin, esto aún no está  montado no?

Acabo de probar pero no logre crear las líneas desde el SB

https://user-images.githubusercontent.com/31936815/218466916-def822da-5a2f-49bf-93e4-651ca78b9c6f.mp4

**Comment by EdwinBetanc0urt** [comment]
Corregido listo para pruebas
