### ISSUE TITLE
[Feature Request] Campo: Acercar en campos de búsqueda personalizada.

### ISSUE THREAD

**Issue by EdwinBetanc0urt** [solop-develop/vue-1.0#870]
#### Describe the solution you'd like
Agregar la funcionalidad de acercar (zoom) en campos de búsqueda personalizada.
- [x] `Combinación Contable`.
- [x] `Localización de Dirección`.
- [x] `Instancia de Conjunto de Atributo`.
- [x] `Ubicación de Almacén`

#### Additional context
Esta funcionalidad solo esta soportada en el Zk solo por el campo de búsqueda personalizada `Ubicación de Almacén` y parcialmente por el campo `Instancia de Conjunto de Atributo`.

https://user-images.githubusercontent.com/20288327/221211285-adeadf06-14f8-458c-b9ec-b3d90d7a6624.mp4

**Comment by EdwinBetanc0urt** [comment]
https://user-images.githubusercontent.com/20288327/221220630-0d76875c-f8cc-4282-883d-7405afd108ae.mp4

**Comment by niclopup** [comment]
Si se intenta acercar a una Ubicación de Almacén desde la línea de una Recepción, abre la ventana de almacén pero sin ningún registro.

![image](https://user-images.githubusercontent.com/31936815/233260112-402345a9-a0ac-4b15-913e-98ab89b34dfb.png)

Instancia de atributo navega a la ventana de Ajuste

![image](https://user-images.githubusercontent.com/31936815/233260145-6bb590c5-a0b6-44d6-9781-2d632905e1de.png)


Localización tampoco navega correctamente


![image](https://user-images.githubusercontent.com/31936815/233260189-a5b6cda8-8ec9-4ee0-8766-4e710e32fb49.png)

**Comment by EdwinBetanc0urt** [comment]
Con respecto al acercar en campos de tipo `Instancia de Conjunto de Atributos` a que ventana debería acercar? Ya que esta navegando correctamente en la ventana donde se guardan las instancias de conjuntos de atributo (no confundir con la ventana `Conjunto de Atributos`), quizás se confunda con la traducción que tiene:

![imagen](https://github.com/solop-develop/frontend-core/assets/20288327/c8c052d8-eb60-4c22-a5f1-eec3e3c78782)

**Comment by EdwinBetanc0urt** [comment]
En cuanto al acercar en campos tipo `Localización / Dirección` parece funcionar correctamente:


https://github.com/solop-develop/frontend-core/assets/20288327/34ffa7e7-8188-46b5-abf7-6d18b3a688b7

**Comment by Ricargame** [comment]
Cambios disponibles apartir de la versión: https://github.com/solop-develop/frontend-core/releases/tag/3.9.8


https://github.com/solop-develop/frontend-core/assets/78000356/b18ffe00-5640-43af-8c61-7811b9580deb
