### ISSUE TITLE
Campo: Ubicación de Almacén > Crear/Editar ubicación de almacén.

### ISSUE THREAD

**Issue by EdwinBetanc0urt** [solop-develop/vue-1.0#873]
Si bien esta soportado en zk, es poco viable debido a que puede ser un problema de seguridad, ya que si un usuario no tiene acceso a la ventana de Almacenes y Ubicaciones, puede crear registros sin considerar del todo si es la ubicación del almacén correcto.

**Comment by niclopup** [comment]
se entiende que no se le da soporte
