### ISSUE TITLE
[Bug Report] Campo: Combinación Contable > Botón de cancelar de la lista no limpia los valores del campo padre.

### ISSUE THREAD

**Issue by EdwinBetanc0urt** [solop-develop/vue-1.0#892]
#### Steps to reproduce

1. Abrir la ventana `Socio de Negocio`.
2. Abrir en la pestaña `Contabilidad Cliente` en mono registro.
3. Pulsar el botón de cualquier campo visible tipo `Combinación Contable` para desplegar la lista.
4. Pulsar el botón de cancelar rojo.

#### Screenshot or Gif（截图或动态图）

https://user-images.githubusercontent.com/20288327/222191299-d47ab8e0-adc2-4537-ab69-4eb25f1a076e.mp4

#### Expected behavior

El cancelar en todos los campos personalizados debe limpiar el valor en el campo padre del mono registro. sin embargo se sigue visualizando el nombre de la combinación contable en lugar de colocar el valor en blanco y resaltar el borde rojo indicando que es un campo obligatorio vació.

**Comment by EdwinBetanc0urt** [comment]
Corregido

https://user-images.githubusercontent.com/20288327/221653417-557c39ca-b03b-46af-9eaf-04d4813955ce.mp4

**Comment by niclopup** [comment]
no se ve nada cuando se abre la combinación contable

![image](https://github.com/solop-develop/frontend-core/assets/31936815/26f06ba4-f56e-4526-818f-8ff9dd61d5ef)

**Comment by Ricargame** [comment]
buen día @niclopup revise en ambas instancias y no pude replicar el error

https://github.com/solop-develop/frontend-core/assets/78000356/9b0ba1c9-1927-4470-b100-92aa1e4d8e55

**Comment by niclopup** [comment]
no se puede replicar el error. hay otros errores q serán reportados en nueva issue
