### ISSUE TITLE
[Bug Report] Campo: Combinación Contable > Lista no consigue registros.

### ISSUE THREAD

**Issue by EdwinBetanc0urt** [solop-develop/vue-1.0#893]
#### Steps to reproduce

1. Abrir la ventana `Socio de Negocio`.
2. Abrir en la pestaña `Contabilidad Cliente` en mono registro.
3. Pulsar el botón de cualquier campo visible tipo `Combinación Contable` para desplegar la lista.

#### Screenshot or Gif（截图或动态图）

https://user-images.githubusercontent.com/20288327/221652009-8bce4c55-4f29-466f-b45b-5858c03ff261.mp4

#### Expected behavior
Si ya el campo origen tiene un valor, debería por lo menos coincidir ese valor en la lista de registros, sin embargo nunca trae registros.

**Comment by EdwinBetanc0urt** [comment]
Corregido

https://user-images.githubusercontent.com/20288327/221651988-8ead560e-f7c0-491b-bb88-c2e556186e6f.mp4

**Comment by niclopup** [comment]
![image](https://github.com/solop-develop/frontend-core/assets/31936815/3db62acf-9199-4814-9474-37b6adca5f40)

**Comment by Ricargame** [comment]
Cambios disponibles apartir de la versión: https://github.com/solop-develop/frontend-core/releases/tag/3.8.3

https://github.com/solop-develop/frontend-core/assets/78000356/9987ba98-096c-45c6-9bb4-e01f61e2da8a
