### ISSUE TITLE
Ventana: Apertura > Acercar desde Parámetro de Proceso

### ISSUE THREAD

**Issue by elsiosanchez** [solop-develop/vue-1.0#9]
En ADempiere actualmente se puede acceder a una ventana desde un campo que está en otro que está relacionado, como se muestra a continuación.

![Peek 04-05-2022 13-53](https://user-images.githubusercontent.com/45974454/166752236-5d72f976-18d7-4947-80c4-673bfcf44f3a.gif)

![Peek 04-05-2022 13-531](https://user-images.githubusercontent.com/45974454/166752600-aa1bd1c9-c7da-4e7c-b490-ce6a2684903e.gif)

**Comment by elsiosanchez** [comment]
El Acercar del ADempiere-Vue del proceso ( **Transferencia Bancaria** ) no funciona correctamente

En la interfaz del ZK si en el proceso ( **Transferencia Bancaria** ) en el campo cargo seleccione una opción y luego doy click derecho al campo y seleccione acercar. Abre la ventana cargó con el registro que había seleccionado como se observa en el gif

![zk](https://user-images.githubusercontent.com/45974454/166823752-9c2949cf-0e12-4221-9b42-4e4e34fd7ce5.gif)


En la Interfaz de ADempiere-Vue solo Abre la ventan mas no con el registro que se selecciono antes de acercar el campo

![Ui](https://user-images.githubusercontent.com/45974454/166824239-fbb0743e-aac9-4ed8-aa15-1b096a80e425.gif)

**Comment by elsiosanchez** [comment]
Se debe revisar la consulta de  `entities` del lado del back-end ya que con ciertos registro el acercar si funciona correctamente 

### Ejemplo 1

si en el campo de `cargo` se usa la opcion de acercar con el valor de ` ajuste de cliente` no funciona
#### CULR
```shell
https://api.erpya.com/api/adempiere/user-interface/window/entities?window_uuid=a5211562-fb40-11e8-a479-7a0060f0aa01&tab_uuid=a4a04a22-fb40-11e8-a479-7a0060f0aa01&context_attributes[]= {"key":"C_Charge_ID","value":1000278}&token=1fbd790b-e607-4940-afe5-3f66188c1ac0&language=es
```
### Ejemplo 2
si en el campo de `cargo` se usa la opcion de acercar con el valor de ` Alquiler de Silos` si funciona
#### GIF
![acercar](https://user-images.githubusercontent.com/45974454/166933116-9fa3a269-aac1-429c-9c58-91fd10122655.gif)

**Comment by elsiosanchez** [comment]
El error parece estar del lado de la consulta del `Back-End`  se realiso la petición de `entities` la cual esta es la que realiza la búsqueda de registro al servidor con los siguientes  parámetros

```Shell
window_uuid: a5211562-fb40-11e8-a479-7a0060f0aa01
tab_uuid: a4a04a22-fb40-11e8-a479-7a0060f0aa01
context_attributes[]: {"key":"C_Charge_ID","value":1000264}
token: ba799911-7b90-400a-9731-12f5644526fb
language: es
```
`context_attributes` se utiliza para flitrar la busqueda pero no esta funcionando 

https://github.com/adempiere/proxy-adempiere-api/blob/master/src/modules/adempiere-api/api/extensions/adempiere/user-interface/window/index.js#L437


### CURL
```Shell
curl --location -g --request GET 'https://api.erpya.com/api/adempiere/user-interface/window/entities?window_uuid=a5211562-fb40-11e8-a479-7a0060f0aa01&tab_uuid=a4a04a22-fb40-11e8-a479-7a0060f0aa01&context_attributes[]= {"key":"C_Charge_ID","value":1000264}&token=1fbd790b-e607-4940-afe5-3f66188c1ac0&language=es'
```

**Comment by EdwinBetanc0urt** [comment]
Esto esta funcionando correctamente:

https://user-images.githubusercontent.com/20288327/179514882-fcf77963-9c26-4a47-b3f2-f5b1c4b5c26d.mp4

**Comment by niclopup** [comment]
Se verifica OK que acerca al registro "Cargo" desde el campo "Cargo" de la transferencia, el detalle que se encuentra es que muestra el cargo en Inglés y no en español como se visualiza en el campo del proceso.

Se realiza otra prueba en el proceso de "Detalle de la Orden" Producto,, Socio del Negocio , Campaign y navega correctamente 

Cuando se intenta navegar al Socio del Negocio, hay veces que si bien abre la ventana, si antes navegaste a otro registro, desde la ventana primero abre el registro anterior que se navegó, y al ratito refresca la ventana y muestra el registro correcto al cual se acercó inicialmente. Lo comento nada más, si se mantiene esto creo un issue.


**Errores:**

Por otro lado, se intenta Acercar al campo "Bank Account" pero no se logra navegar correctamente a ningún registro. 

Tampoco se logra navegar al campo "Sales Representative" "dasdasd" desde el reporte Detalle de la Orden

**Comment by EdwinBetanc0urt** [comment]
@niclopup en el ZK se muestra igual el registro, al acercar el registro `Cargo Bancario` del campo `Cargo`, en la ventana se ve en ingles `Bank Charge`:

https://user-images.githubusercontent.com/20288327/182232546-59f9a00c-2eb4-4930-a58b-872306fcc527.mp4

Esto debido a que es una ventana con pestaña de traducciones y no se esta visualizando la pestaña de traducción:

![Screenshot_20220801_155511](https://user-images.githubusercontent.com/20288327/182233983-fcf0057f-0ec6-421d-8262-c8eb92e58bbc.png)


Sin embargo en vue para visualizar las traducciones de los campos basta con desplegar la lista de opciones del campo dando clic en el nombre, y seleccionar la opción `Traducción`, el cual en esta ventana específicamente solo tiene para traducir los campos `Nombre` y `Descripción`:

https://user-images.githubusercontent.com/20288327/182232541-c321e651-118a-4cf2-a5f3-ecd37c1186ae.mp4
