### ISSUE TITLE
[Bug Report] Campo: Localización > Cambiar país entra en un ciclo infinito de peticiones.

### ISSUE THREAD

**Issue by EdwinBetanc0urt** [solop-develop/vue-1.0#912]
#### Steps to reproduce

1. Abrir la ventana `Socio de Negocio`.
2. Ir a la pestaña `Localización`
3. Desplegar el formulario del campo `Localización / Dirección`.
4. Cerrar el campo `Localización / Dirección`.
5. Desplegar el formulario del campo `Localización / Dirección` y cambiar el campo `País`.

Observe como entra en un bucle infinito de peticiones para tratar de consultar el valor de visualización del país seleccionado.

#### Screenshot or Gif（截图或动态图）

https://user-images.githubusercontent.com/20288327/223239150-4df2aa19-a590-4411-b7cd-de285bdc0714.mp4

#### Expected behavior
Se espera que si debe hacerse la petición, debe hacerse una sola vez, sin embargo al desplegar la lista, el valor de visualización ya esta disponible, por lo que no debería hacerse peticiones para buscar el valor de visualización.

**Comment by EdwinBetanc0urt** [comment]
Corregido

https://user-images.githubusercontent.com/20288327/223242902-22018a06-3422-42e2-bc50-421c4b0c1b95.mp4

**Comment by niclopup** [comment]
Ya no hace loop pero da otro error
