### ISSUE TITLE
Carga de Tiempo Dedicado en Solicitudes (M_Request)

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#923]
## Feature request

Según lo conversado con Yamel y Edwin se define habilitar la posibilidad de cargar tiempo dedicado a las Solicitudes (M_Request).

El tiempo dedicado se cargará en la tabla original de ADempiere "S_ResourceAssignment" en la cuál se deberá agregar los campos de "M_Request_ID" y "C_Project_ID"

### Cargar Tiempo desde Solicitud

se define crear una ventana para que se permita la imputación de tiempo dedicado con la menor información necesaria para su carga. Los datos a definir deben ser los siguientes:
* Fecha
* Cantidad (se definirá el tiempo inicialmente en Horas)
* Descripción
* Usuario/Recurso
* Solicitud (M_Request)

Donde ubicar el proceso?

![image](https://user-images.githubusercontent.com/31936815/224715024-c0ff4343-f6eb-4f45-8239-7455a6e73f71.png)

La idea es que esta ventana pueda ser abierta tanto desde una Issue (Ventana nueva de Solicitudes en VUE) como también desde la ventana original de Solicitudes, al ser un proceso se podrá agregar a la ventana fácilmente.

### Cargar Tiempo múltiples solicitudes

Otra opción para realizar la carga de tiempo dedicado podrá ser contar con un nuevo formulario similar al actual definición de "Combinación Contable" donde se pueda ir definiendo en el cabezal diferentes combinaciones de datos y que al poner "GUARDAR" se genere la imputación del tiempo correspondiente. Muy similar a como funciona actualmente el formuario de Combinaciones contables para definir una cuenta contable.

![image](https://user-images.githubusercontent.com/31936815/224715085-8871a73b-3251-4936-ba8b-040eb5c6532d.png)

De esta manera, si un usuario desea cargar horas masivamente seleccionando varias solicitudes de manera rápida, de esta formas será posible

Tabla de ADempiere S_ResourceAssignment

![image](https://user-images.githubusercontent.com/31936815/224715651-70b0956b-58ba-4104-ad08-b71e44bd52d5.png)

v

**Comment by EdwinBetanc0urt** [comment]
@niclopup el campo a agregar si no me equivoco seria `R_Request_ID` en lugar de `M_Request_ID`.

**Comment by EdwinBetanc0urt** [comment]
Queda de la siguiente manera la funcionalidad:

https://user-images.githubusercontent.com/20288327/226674908-ef96bef6-23fa-48b6-8652-af1405424312.mp4
