### ISSUE TITLE
[Bug Report] Error on Advanced Search and tab list field

### ISSUE THREAD

**Issue by rcapecce** [solop-develop/vue-1.0#942]
## Bug report

When search in Advanced Search and add a table list field filter like Currency, this not limit and show all currencies in the table.

#### Steps to reproduce

1. Open the Sales Order window
2. Filter in Advanced Search a table list field like Currency (is the example)
3. You can select the currency you want without filter.

#### Screenshot or Gif

![Peek 2023-03-22 19-41](https://user-images.githubusercontent.com/14218144/227054508-ed678a71-0c6b-488a-8272-2d81814b8c43.gif)

#### Expected behavior

Do the Advanced Search

#### Other relevant information
- Your OS: Kubuntu 22.04
- Web Browser: Chrome
- Node.js version:
- adempiere-vue version:

**Comment by EdwinBetanc0urt** [comment]
As seen in the Zk interface, the advanced search also does not limit the records in the table when an av search is performed.

![imagen](https://github.com/solop-develop/frontend-core/assets/20288327/a446997d-60cb-42e4-ae9d-1b8108d2af80)
