### ISSUE TITLE
Crear tableros en Ventanas de dimensiones (SDN, Producto, etc)

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#959]
## Feature request

Debido a la imposibilidad de definir filtros en las gráficas actualmente disponibles en VUE, se decide agregar nuevas pestañas dentro de las ventanas que son definidas como "Dimensiones" las cuáles son de gran utilidad para obtener algun dato en particular.

Las ventanas a definir serían las siguientes:

- Producto
- Categoría de Producto
- Socio del Negocio
- Grupo del Socio del Negocio
- Usuario (Agente Comercial)
- Cuenta Bancaria

La idea es entonces agregar en estos tableros, una lógica que por defecto tome el ID del registro padre para generar a partir del mismo varios tableros independientes presentando información sobre el mismo.

Por ejemplo: 

**Producto:**

- Días de Stock
- Ventas por mes último AÑO (-12 Meses) detallado por mes
- Ventas por Cliente últimos 12 meses
- Compras por Proveedor últimos 12 meses

**Socio del Negocio:**

- Ventas por mes último AÑO (-12 Meses) detallado por mes
- Ventas por Categoría de Producto últimos 12 meses
- Compras por mes último AÑO (-12 Meses) detallado por mes
- Compras por Categoría de Producto últimos 12 meses

**Comment by EdwinBetanc0urt** [comment]
Como requisito se deben importar los xml del proyecto https://github.com/adempiere/adempiere-dashboard-improvements en la base de datos ademas de hacer uso del paquete de maven `io.github.adempiere:adempiere-dashboard-improvements`

#### Pasos para configurar un gráfico

1. Se define el gráfico, con el rol `System`:

![Image](https://github.com/solop-develop/frontend-core/assets/20288327/bec7a791-cf0e-499c-8197-71a7cd4fd382)


2. Se asignan los gráficos a la ventana, con el rol `System`:


![Image](https://github.com/solop-develop/frontend-core/assets/20288327/fc0afa2e-7704-4ce3-b827-78af51be7d48)


Si este tiene marcado el campo `Enable Data Transformation` se selecciona la regla para habilitar la transformación javascript del gráfico basado en los ejemplos de https://echarts.apache.org/examples/en/index.html.

Es importante destacar que la regla debe estar creada estableciendo en el campo `Event Type` el valor `Chart Transformation`. Y dentro del script el nombre reservado de la variable que contiene el resultado de los graficos se llama `data`.


![Image](https://github.com/solop-develop/frontend-core/assets/20288327/b63f2fea-149f-48ee-8184-1413110b3a26)


Se crearon 4 ejemplos de transformación como base de partida para los graficos tipo `Linea`, `Barra`, `Cascada` y `Pastel`.


3. En caso de aplicar, se definen los parámetros como filtros. Considerando que:

* `DB Column Name` es el nombre clave con el que recibirá el valor del cliente, debe ser irrepetible entre los parámetros.
* `Column SQL*` es el alias de la tabla con el nombre del campo, segun el data source de la definicion del grafico del paso 1.
* `Enable Selection` es para marcar que el filtro es manipulable por el usuario, es decir puede establecer el valor a conveniencia, en caso de estar en falso buscara el valor de `DB Column Name` en el contexto para establecerlo sin intervención del usuario.
* `Reference` el tipo de visualizacion para establecer el campo, aactua de igual manera que en los campos de ventana, parametros de proceso/reporte, campos de consulta inteligente.


![Image](https://github.com/solop-develop/frontend-core/assets/20288327/c0881d3d-12ea-4870-b0b9-df289c8de72d)



4. Se asigna el acceso de gráficos por rol, en este caso con el rol `GardenAdmin`:

![Image](https://github.com/solop-develop/frontend-core/assets/20288327/95b0bf98-92b7-48b7-88be-9737519aafe8)


#### 


https://github.com/solop-develop/frontend-core/assets/20288327/8701c4f3-31fc-4e8b-a4f2-19267ff155b5

**Comment by niclopup** [comment]
Se desea poder comparar y controlar el resultado de los Tableros definidos en las ventanas

Se toma como ejemplo el tablero definido en la ventana Productos,  filtrando por ELM se navega a los tableros pero no se comprende cómo se llega a los números que muestra.

Se crean 2 facturas para poder ver la diferencia pero sólo se ve que aumente el eje de las Y y no se ve que aumente el dato en el gráfico (Barra o Línea)

![image](https://github.com/solop-develop/frontend-core/assets/31936815/b81af941-97db-40f3-964e-29983bf958b7)

![image](https://github.com/solop-develop/frontend-core/assets/31936815/fdf9cc3f-489d-4ddd-9566-75e81b7e2edb)

La idea es poder verificar los datos con un Reporte. Entiendo que podría confirmarse con el reporte de "Facturación Mensual de Producto" con la agrupación definida por "Grupo de Producto". Adjunto Excel y gif

[Facturación Mensual Producto por Grupo de Producto .xlsx](https://github.com/solop-develop/frontend-core/files/11653993/Facturacion.Mensual.Producto.por.Grupo.de.Producto.xlsx)
![Reporte comparación Tableros Productos](https://github.com/solop-develop/frontend-core/assets/31936815/80689db0-802d-449d-8b0e-4d43b6f468f7)

**Comment by niclopup** [comment]
Se intenta realizar una definición de un parámetro en un tablero agregado en una ventana pero al intentar filtrar por dicho parámetro el mismo no es agregado a la consulta y no se modifica nada en los datos de la gráfica.

![Filtro en Parámetros no aplica en consulta](https://github.com/solop-develop/frontend-core/assets/31936815/3c9f01b6-6cc6-4b5f-99f8-00f7f8be6f8c)

el ejemplo se ve en la ventana de "Proyecto de Medios"
Organización "Agencia S.A."
Rol "Admin Agencia"

**Comment by niclopup** [comment]
no estaría cargando cuando se define un parámetro.

![image](https://github.com/solop-develop/frontend-core/assets/31936815/efb5b13e-4357-423f-9b0d-5a8809af9c3f)

**Comment by EdwinBetanc0urt** [comment]
Por lo visto en la definición en db column name deberia ser `M_Product_Category_ID`

![2024-01-30_17-41](https://github.com/solop-develop/frontend-core/assets/20288327/33e1892c-304f-4374-baaf-c21eabcaf1c9)

Y en el column sql debería ser `p.M_Product_Category_ID` o `i.M_Product_Category_ID` dependiendo de donde exista esa columna de las tablas que estén en el `FromClause` del datasource en el chart

![2024-01-30_17-42_1](https://github.com/solop-develop/frontend-core/assets/20288327/bd05eb3b-07b5-4075-ba75-c866b14ab62d)
