### ISSUE TITLE
Formulario: Recepción Rápida

### ISSUE THREAD

**Issue by EdwinBetanc0urt** [solop-develop/vue-1.0#960]
- [x] Listar Socios de Negocio filtrando solo Proveedores.

- [x] Listar Ordenes de Compra filtrado por Socio de Negocio seleccionado.

- [x] Crear encabezado de la Recepción al seleccionar la Orden de Compra.
En caso de que exista una Recepción en borrador asociada a esa Orden de Compra, devolverá esa recepción en lugar de crear una nueva.

- [x] Listar Productos filtrando por las Líneas de la Orden de Compra.
Se listaran solo los productos que estén en las lineas de la orden de compra.

- [x] Crear Linea de la Recepción.
Esta línea se creara asociada a la Línea de la Orden de Compra que coincida con el producto con el cual se esta registrando. Si el check de `Cantidad Completa de la Línea` esta marcado crea la línea de la recepción con la cantidad en reserva de la línea de la orden de compra.

- [x] Listar Lineas de la Recepción.
Se listaran las líneas de la recepción actual.

- [x] Editar Linea de la Recepción.

- [x] Eliminar Linea de la Recepción.

![image](https://user-images.githubusercontent.com/45974454/230164182-eb76511a-9d3b-43a3-820c-daeb1379a513.png)

**Comment by niclopup** [comment]
Se intenta generar un ejemplo en VUE pero no se logra. No logro que se vean las líneas de la OC.

![Recepción Rápida no encuentra Nombre ni código de Producto](https://user-images.githubusercontent.com/31936815/232536482-4603202d-ccd4-4586-a239-8dea1cea1170.gif)
![Recepción Rápida no encuentra por EAN](https://user-images.githubusercontent.com/31936815/232536493-1e78dd7a-af29-4340-9146-7298fbeb4eeb.gif)
