### ISSUE TITLE
[Bug Report] POS: Error creating sales order

### ISSUE THREAD

**Issue by elsiosanchez** [solop-develop/vue-1.0#961]
## Bug report
Error creating sales order
#### Steps to reproduce

1. Open the Point of Sale
2. Create a sales order
3. Throws a SQL Query error

#### Screenshot or Gif（截图或动态图）
![errorpos](https://user-images.githubusercontent.com/45974454/231211848-bc5f2067-3f1f-44d3-9009-389c8a7c40d4.gif)

**Comment by niclopup** [comment]
Cómo puedo probar esto? entro con GardenUser y saltan errores. no está el POS acá aún no?

![image](https://user-images.githubusercontent.com/31936815/233244959-f4f5ff43-807c-4f1f-97e2-ffe3f4a0afdc.png)

**Comment by EdwinBetanc0urt** [comment]
Aun no se han importado los xml del proyecto del POS en la base de datos de solop, intente hacerlo pero me dio un error al 3er o 4to script xml.
