### ISSUE TITLE
POS: Soporte a Atajo de Comandos

### ISSUE THREAD

**Issue by elsiosanchez** [solop-develop/vue-1.0#967]
## Solicitud de función

Se requiere agregar atajos o Comandos Mnemónicos en el Punto de Venta

#### Describe la solución que te gustaría
Agregar una nueva Opcion en el Punto de Venta  que permita seleccionar una opcion y asignarle un Atajos o Comandos Mnemónicos
#### **_Asignar Atajo_**
![#940](https://user-images.githubusercontent.com/45974454/230227246-efcd661d-ff1f-4fc2-89dd-91db0762ac5f.gif)

#### **_Usar Atajo_**
![pos](https://user-images.githubusercontent.com/45974454/231864395-d7b2c45f-3fdd-41c9-a311-11a420a66c4a.gif)

**Comment by niclopup** [comment]
no se logra en Linux.. pero si se logra desde un Windows

**Comment by EdwinBetanc0urt** [comment]
@niclopup que navegadores usaste donde no funciono?

> no se logra en Linux.. pero si se logra desde un Windows
