### ISSUE TITLE
Ver Flujos de Trabajo existentes para un Documento

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#970]
## Feature request

Actualmente no se cómo puedo ver los flujos de trabajo que tiene definido un documento puntual. Si quiero ver a quién está asignado para que pueda aprobarlo, cómo se hace para mirar desde VUE si estoy parado en el documento? 

Por ejemplo si estoy en una Requisición que está "EN Suspenso" a la espera de la aprobación.

![image](https://user-images.githubusercontent.com/31936815/233248257-0eed1530-88df-4a93-b3c1-f2b6041fd3e2.png)

![image](https://user-images.githubusercontent.com/31936815/233248336-08d0671b-f68f-4237-b9f7-7fd03cd94584.png)

No veo donde acceder a los Flujos de Trabajo por ej de la Requisición de Compra 900044

![image](https://user-images.githubusercontent.com/31936815/233248597-a910094e-f0cd-417d-9cd8-60106f6bcb39.png)

#### Describe the solution you'd like

Si bien lo ideal sería poder visualizar rápidamente a quién se encuentra asignado el Flujo de Trabajo, al menos a que aprobador... creo que no sería necesario agregar una pestaña más donde está la auditoría y los anexos.

Tal vez una opción en los procesos es suficiente. 

Sugerir que opciones les parece

**Comment by EdwinBetanc0urt** [comment]
![Peek 2023-06-01 12-09](https://github.com/solop-develop/frontend-default-theme/assets/45974454/24da7027-f296-49fa-b157-da420060a248)

**Comment by niclopup** [comment]
![image](https://github.com/solop-develop/frontend-core/assets/31936815/3d971ad8-890c-4265-aa7d-e0c987176650)

**Comment by niclopup** [comment]
Esto no estaría visible en documentos actualmente en la pestaña lateral.

**VUE Legacy**

![image](https://github.com/solop-develop/frontend-core/assets/31936815/e03242ef-19c5-477a-a953-337403623663)

VUE  3.7.6

![image](https://github.com/solop-develop/frontend-core/assets/31936815/51627258-18f1-46b2-b87b-8602fdc8c4f5)

**Comment by Ricargame** [comment]
Cambios disponibles apartir de la versión: https://github.com/solop-develop/frontend-core/releases/tag/3.8.3


https://github.com/solop-develop/frontend-core/assets/78000356/4f0e1f1f-c101-4853-8c40-f3ff4beee12f
