### ISSUE TITLE
Si se abren o cierran ventanas luego de lanzar un reporte, el mismo nunca sale

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#972]
## Bug report

Se intenta obtener un Saldos Abiertos y mientras pensaba se cierran unas ventanas. El reporte nunca sale.

**Comment by elsiosanchez** [comment]
![Peek 2023-05-05 09-53](https://user-images.githubusercontent.com/45974454/236477185-f820c35e-2e37-45b8-9045-b4d2ac4a07fc.gif)


Saludos @niclopup puedes indicarme que parametros usaste ya que no logro replicar el error
