### ISSUE TITLE
Muy dificil de leer letra de campos sólo lectura. Está muy clara

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#973]
## Bug report

No les parece que está muy clara la letra de los campos sólo lectura?

![image](https://user-images.githubusercontent.com/31936815/233256931-2f3927dc-6742-4b55-9e4e-09e62f75e6a9.png)

SI bien está bueno los colores tenues, no es la idea cansar tanto la vista o forzarla.

En ZK creo que están más claros justamente por que la letra es igual de negra que los que no están sólo lectura.

![image](https://user-images.githubusercontent.com/31936815/233257001-dea9d9e6-0007-4813-95ad-d5913a6ffaaa.png)

#### Steps to reproduce

1. [xxx]
2. [xxx]
3. [xxxx]

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:

**Comment by elsiosanchez** [comment]
![image](https://user-images.githubusercontent.com/45974454/235772783-96a75019-cf4a-4990-b5d3-0b668978ef2d.png)
