### ISSUE TITLE
Portlet de Tarjeta como objetivo de Desempeño en el Panel de Control

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#976]
## Feature request

Tarjetas informativas

Se desea utilizar la funcionalidad de Objetivos de Desempeño para que no sólo nos brinden datos en Gráficas, sino también tomar el resultado de los mismos y presentarlos en "Tarjetas"

**Cómo obtener el dato?** 

La idea es utilizar al máximo el motor actual que existe en ADempiere con los objetivos de desempeño. 
A continuación agrego algunas opciones que podemos tomar para definir las tarjetas.
 
![image](https://user-images.githubusercontent.com/31936815/233431289-1edf7725-efc5-476d-b519-458e8b413333.png)

Las tarjetas serán de la siguiente forma:
![image](https://user-images.githubusercontent.com/31936815/233430050-ee259e73-ff4d-4901-83d2-3826a3fd8834.png)

lo ideal sería como está en element-plus donde podemos ver que muestra un DATO y también una COMPARACION con un análisis si MEJORO (Verde) o Empeoró (Rojo)

https://element-plus.org/en-US/component/statistic.html#card-usage

Opción más simple en element

![image](https://user-images.githubusercontent.com/31936815/233430263-24330d1a-6f00-422c-b239-2e591e0de21d.png)

Tal vez también podemos utilizar la Card

https://element.eleme.io/#/es/component/card

**Comment by niclopup** [comment]
En la base actual de demo, podemos considerar el Objetivo de Desempeño "Ventas del Mes" (PA_Goal_ID=1000007) como referencia para jhacer las pruebas.

Se desea contar con una tarjeta donde se visualice el importe del resultado en GRANDE

**Nombre:** Nombre del objetivo
**Medida Actual:** importe grande a mostrar
**Meta del Rendimiento:** si es positivo mostrar en verde von icono de crecimiento de tendencia, negativo en rojo con icono de decrecimiento 

**Medida Objetivo:** contra quew comparo. importe en tamaño menor


![image](https://github.com/solop-develop/frontend-core/assets/31936815/029d6e62-54c6-4334-a943-4690ad8ef033)

**Comment by elsiosanchez** [comment]
![image](https://github.com/solop-develop/frontend-core/assets/45974454/453b0501-e1b7-4e06-842c-83d27a5cd0f9)

![image](https://github.com/solop-develop/frontend-core/assets/45974454/3edf9b22-ae17-48bf-8356-889480bfbea1)

**Comment by niclopup** [comment]
intenté ver una tarjeta con los 2 importes que se desean visualizar pero no lo logro.

Se desea ver en algú lado el resultado REAL de lo que se consulta, en estos ejemplos el importe sería: 228,303,398.52 que hacen el % 45,6607


para realizar la prueba tomé un Objetivo de Desempeño que tenía datos calculados y le hice una copia poniendole nombre "Tarjeta" y el tipo de Gráfico Porlet

![image](https://github.com/solop-develop/frontend-core/assets/31936815/8ccda0e7-5122-4f16-952c-496f766d3f10)


Objetivo con datos 1
![image](https://github.com/solop-develop/frontend-core/assets/31936815/c73ed24a-5fb7-4ee7-a6f1-4ee5907f462c)

Objetivo con datos 2
![image](https://github.com/solop-develop/frontend-core/assets/31936815/e133e82c-0733-45bf-9cce-6c18a8a83834)

**Comment by niclopup** [comment]
> ![image](https://private-user-images.githubusercontent.com/45974454/290625345-453b0501-e1b7-4e06-842c-83d27a5cd0f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0OTAxMDMsIm5iZiI6MTcwNDQ4OTgwMywicGF0aCI6Ii80NTk3NDQ1NC8yOTA2MjUzNDUtNDUzYjA1MDEtZTFiNy00ZTA2LTg0MmMtODNkMjdhNWNkMGY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA1VDIxMjMyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2YzYxNjllMjEyZGUxMWZmMjY5NjAzNThkYTZmOTFmN2E1MGUwMDc1NDk3MTcyMWJkYzQ4Y2M2MWYxOWVlNzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.y7AyEQU2pmQy91Vu-hWpFzYPhx7kouPJfWaH2ypDZDE)
> 
> ![image](https://private-user-images.githubusercontent.com/45974454/290635809-3edf9b22-ae17-48bf-8356-889480bfbea1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0OTAxMDMsIm5iZiI6MTcwNDQ4OTgwMywicGF0aCI6Ii80NTk3NDQ1NC8yOTA2MzU4MDktM2VkZjliMjItYWUxNy00OGJmLTgzNTYtODg5NDgwYmZiZWExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA1VDIxMjMyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzOWRjOTYyMTlhNGY0ZTg2NTI0NDJkYjhiYjA0NWYzZGMxZWM5N2Q2NmZjZjNlNzg0OTk0ZWY0YjhjOTZjZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.my5a-7Vf_edDQ6dXEYdEheXX9y90BRXeZkvJUS-QBos)

Ya enn este comentario yu en el ejemplo que agregron, no se ven los importes que se solicitan que aparezcan en las tarjetas.

**Comment by EdwinBetanc0urt** [comment]
Corregido y disponible a partir del release https://github.com/solop-develop/adempiere-grpc-server/releases/tag/2.1.8 del backend y https://github.com/solop-develop/frontend-core/releases/tag/3.3.9 del frontend

**Comment by niclopup** [comment]
no carga la tarjeta
![image](https://github.com/solop-develop/frontend-core/assets/31936815/6b5aafa9-84fb-49af-8b65-828d03d8d9f9)

**Comment by EdwinBetanc0urt** [comment]
Esto esta operando bien 

![Image](https://github.com/solop-develop/frontend-core/assets/20288327/c17904cb-c6fc-40c6-976c-4040d067176d)
