### ISSUE TITLE
Crear nueva ventana de Inicio (Home) de entrada al sistema

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#978]
## Feature request

Se desea mejorar la visual a la primer pantalla que aparece del sistema cuando el usuario inicia sesión de manera que la misma sea lo más simple posible y que de una sensación de claridad y no agobie al usuario ni bien ingresa.

Por esta razón se sugiere realizar lo siguientes cambios:

Crear una nueva ventana de "Inicio" donde se muestren los siguientes "Portlets" 
1. Favoritos (Usuario)
2. Recent Items
3. Calendario
4. Favorites (System)
5. Document Tasks
6. Portlet de "Tarjetas". Ver cómo se podrían organizar para mostrar cierta cantidad de tarjetas una al lado de la otra de manera horizontal. (Ver todo más abajo)
7. Gráficas para la Home. Ver cómo podemos definir en ciertos tableros la posibilidad de marcarlos para qeu los mismos si se muestren en la página de inicio del usuario
8. Agregar FIJO un Saludo al Usuario con el Nombre del mismo (Ver Foto Ejemplo)
9. 

![image](https://user-images.githubusercontent.com/31936815/233429625-e8d0128f-886f-4ddc-abeb-72e6d2b6ccae.png)

**Ejemplo tarjetas:**

Se ampliará la definición de las tarjetas en la siguiente Issue  solop-develop/vue-1.0#976

![image](https://user-images.githubusercontent.com/31936815/233429035-5314e8b7-d135-4584-81db-b54a3935ea6d.png)

**Ejemplo Indicadores**

Se ampliará la definición de las tarjetas en la siguiente Issue solop-develop/frontend-core#61 
![image](https://user-images.githubusercontent.com/31936815/233434241-77a68e28-dd5c-4513-bc1d-403ca17ff312.png)

**Comment by EdwinBetanc0urt** [comment]
Se modifico el panel de control agregando el mensaje de bienvenida e información básica del usuario/sesión, también se coloco al principio los tableros y al final los gráficos, quedando de la siguiente manera el panel de control:

![imagen](https://github.com/solop-develop/frontend-core/assets/20288327/06addca5-d18f-486c-9bee-ac2c710f3bc2)
