### ISSUE TITLE
Consulta Inteligente: Carga > Criterio de Búsqueda

### ISSUE THREAD

**Issue by elsiosanchez** [solop-develop/vue-1.0#99]
Requiere dar soporte para la busqueda de registro en el Smart Browser. Actualmente se realiza en la interfaz ZK de la siguiente manera

![search-record-sb-zk](https://user-images.githubusercontent.com/45974454/169856591-9f88f050-c81c-48c0-85dd-c3dfe1835d91.gif)

Actualmente en la interfaz de ADempiere-Vue

![search-record-sb-vue](https://user-images.githubusercontent.com/45974454/169856417-120127aa-0ee1-4b46-9a0b-ccb80106a510.gif)

**Comment by elsiosanchez** [comment]
### _**Nota:**_
Los casos de uso para esta funcionalidad se pueden ver aquí: [Smart Browser > Criterio de Búsqueda](https://solop-develop.github.io/frontend-core/es/guide/use-cases/smartbrowser.html#CriteriodeBúsqueda)

**Comment by niclopup** [comment]
No se logra ver registros en un SB

https://user-images.githubusercontent.com/31936815/175380291-c9bd8158-35b8-4049-947a-f86ac732b12c.mp4

**Comment by niclopup** [comment]
> 

No se logra ver los casos de uso referidos

**Comment by niclopup** [comment]
Se logra visualizar ok datos y columnas
gracias
